In [1]:
year_1=2100

In [2]:
import pandas as pd
Emp_home_select_2030_part2_new2 = pd.read_pickle('Emp_home_select_{0}_part2_new2.pickle'.format(year_1))

In [3]:


Emp_home_select_2030_part2_new2['geometry'] = Emp_home_select_2030_part2_new2['geometry'].to_crs('epsg:4326')

In [4]:
Emp_home_select_2030_part2_new2 = Emp_home_select_2030_part2_new2.astype({"h_geocode":'int64'})

In [5]:
Emp_home_select_2030_part2_new2['C000'].sum()

62328.0

In [6]:
Emp_home_select_2030_new_values =  Emp_home_select_2030_part2_new2[Emp_home_select_2030_part2_new2['C000'] > 0]
len(Emp_home_select_2030_new_values)

16213

In [7]:
Emp_cells_2030_old = pd.read_pickle('bldgs_RES_remain_{0}.pickle'.format(year_1-10))

In [8]:
Emp_cells = Emp_cells_2030_old

In [9]:
Emp_cells =  Emp_cells.dropna(subset=['cell'])
len(Emp_cells)

331127

In [10]:
Emp_cells =  Emp_cells.dropna(subset=['h_geocode'])
len(Emp_cells)

331127

In [11]:
Emp_cells = Emp_cells.astype({"cell":'int64',"fd_id":'int64',"h_geocode":'int64'})

In [12]:
Emp_cells = Emp_cells.drop_duplicates(subset=['fd_id'])
len(Emp_cells)

331127

In [13]:
Emp_cells_ = Emp_cells.select_dtypes(exclude=['geometry','object'])

In [14]:
Emp_cells_sum = Emp_cells_.groupby(["h_geocode"], as_index=False).sum()
Emp_cells_sum

,h_geocode,fid,fd_id,num_story,sqft,found_ht,med_yr_blt,val_struct,val_cont,val_vehic,...,pop2amo65,pop2pmu65,pop2pmo65,o65disable,u65disable,x,y,grnd_elv_m,ground_elv,cell
0,120150101001000,7260298.0,3934160594,8.0,9500.0,12.0,15904,9.985299e+05,4.992649e+05,216000.0,...,1,1,1,1.44,0.64,-653.518738,215.838190,125.811646,412.767879,8
1,120150101001005,2382353.0,1474969444,3.0,2364.0,4.5,5964,3.329845e+05,1.664923e+05,81000.0,...,2,2,2,0.54,0.24,-245.047288,80.890388,52.006138,170.623817,3
2,120150101001009,38057582.0,23108594843,47.0,129770.0,54.0,93436,1.057596e+07,5.287978e+06,1269000.0,...,12,16,12,8.46,3.76,-3848.650638,1268.360722,361.454433,1185.874161,47
3,120150101001010,4043137.0,2458356555,5.0,12313.0,3.5,9940,1.131022e+06,5.655112e+05,135000.0,...,0,1,0,0.90,0.40,-409.584315,135.001219,34.736947,113.966364,5
4,120150101001011,798669.0,491661116,1.0,2217.0,1.5,1988,2.523237e+05,1.261619e+05,27000.0,...,1,1,1,0.18,0.08,-81.867307,27.001371,9.555853,31.351224,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19854,121150027472071,7099896.0,988826660,2.0,3590.0,1.0,4008,3.506347e+05,1.753174e+05,54000.0,...,2,4,2,0.34,0.10,-164.277355,54.100514,14.855018,48.736938,2
19855,121150027481003,36843015.0,8872376375,18.0,31597.0,9.0,36072,3.586240e+06,1.793120e+06,486000.0,...,1,3,1,3.06,0.90,-1478.399192,487.492153,159.039194,521.782150,18
19856,121150027481009,60817754.0,12332393747,25.0,41849.0,12.5,50100,4.691628e+06,2.345814e+06,675000.0,...,2,3,2,4.25,1.25,-2053.191099,676.946151,213.421710,700.202483,25
19857,121150027481010,14346167.0,3450388481,7.0,13258.0,3.5,14028,1.488367e+06,7.441835e+05,189000.0,...,2,5,2,1.19,0.35,-574.859939,189.559891,61.200643,200.789516,7
19858,121150027482003,10294134.0,2464608641,5.0,8561.0,2.5,10020,8.456077e+05,4.228038e+05,135000.0,...,2,4,2,0.85,0.25,-410.709463,135.390427,40.981065,134.452317,5

In [15]:
Emp_cells_sum = Emp_cells_sum[['h_geocode','cell']]
Emp_cells_sum

             h_geocode  cell
0      120150101001000     8
1      120150101001005     3
2      120150101001009    47
3      120150101001010     5
4      120150101001011     1
...                ...   ...
19854  121150027472071     2
19855  121150027481003    18
19856  121150027481009    25
19857  121150027481010     7
19858  121150027482003     5

[19859 rows x 2 columns]

In [16]:
Emp_cells_sum = Emp_cells_sum.astype({"h_geocode":'int64'})
# Emp_cells_sum = Emp_cells_sum [['h_geocode','cell']]

In [17]:
import pandas as pd

Emp_home_select_2030_new_values_merge = pd.merge(Emp_home_select_2030_new_values, Emp_cells_sum,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

In [18]:
Emp_work = pd.read_pickle('Emp_work.pickle')

In [19]:
Emp_work['w_geocode']

9        120210113042009
15       120210001021033
16       120210112062003
17       120210111141006
58       121150006012024
              ...
43986    120210108012000
43987    120210103003013
43989    120210102082001
43990    120210105112010
43991    120210104371010
Name: w_geocode, Length: 15195, dtype: object

In [20]:
OD_main= pd.read_pickle("/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/OD_main.pkl")

In [21]:
OD_main

               w_geocode        h_geocode
0        120010002011000  120010006003047
1        120010002011000  120010012025015
2        120010002011000  120010017022003
3        120010002011000  120010019072015
4        120010002011000  120010022181001
...                  ...              ...
7645809  121339703032101  121339703032084
7645810  121339703032101  121339703032092
7645811  121339703032101  121339703032096
7645812  121339703032142  120632101001066
7645813  121339703032142  121339701032003

[7645814 rows x 2 columns]

In [22]:


OD_main = OD_main.astype({"h_geocode":'int64',"w_geocode":'int64' })

In [23]:
len(Emp_home_select_2030_new_values_merge)

16213

In [24]:
Emp_home_select_2030_new_values_merge

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CT02,CD01,CD02,CD03,CD04,CS01,CS02,createdate,geometry,cell
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",NaN
1,12,021,010411,1000,120210104111000,Block 1000,G5040,NaN,NaN,NaN,...,1.0,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.69629 26.18436, -81.69546 26.184...",317.0
2,12,081,002003,1002,120810020031002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-82.50990 27.50864, -82.50986 27.508...",36.0
3,12,081,001904,2006,120810019042006,Block 2006,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-82.52838 27.51722, -82.52836 27.518...",148.0
4,12,087,971800,1022,120879718001022,Block 1022,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,1.0,2.0,2.0,20231016,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16208,12,081,002018,3029,120810020183029,Block 3029,G5040,NaN,NaN,NaN,...,0.0,3.0,1.0,6.0,2.0,6.0,6.0,20231016,"POLYGON ((-82.42543 27.48683, -82.42515 27.486...",NaN
16209,12,081,001914,2082,120810019142082,Block 2082,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-82.36136 27.55343, -82.36129 27.553...",1.0
16210,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",NaN
16211,12,081,000406,3010,120810004063010,Block 3010,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,20231016,"POLYGON ((-82.61226 27.47755, -82.61029 27.477...",1.0
16212,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,4.0,0.0,2.0,6.0,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",NaN

In [25]:
Emp_home_select_2030_new_values_merge['cell'] = Emp_home_select_2030_new_values_merge['cell'].fillna(0)

In [26]:
Emp_home_select_2030_new_values_merge['C000'].unique()

array([ 1.,  2.,  4.,  3., 14.,  8., 12.,  5., 19.,  6., 50., 18.,  9.,
        7., 36., 15., 21., 13., 11., 25., 23., 16., 10., 27., 24., 37.,
       17., 22., 20., 38., 43., 52., 29., 49., 53., 28., 48., 47., 32.,
       41., 31., 39., 34., 26., 33., 35., 44., 54., 45., 30., 70., 40.,
       64., 46., 59., 51., 66., 42., 57., 56., 60., 72.])

In [27]:
# number of projected employees are more than number of cells

Emp_home_select_2030_new_values_merge_s = Emp_home_select_2030_new_values_merge[Emp_home_select_2030_new_values_merge['C000']- Emp_home_select_2030_new_values_merge['cell'] > 0]


len(Emp_home_select_2030_new_values_merge_s)

9085

In [28]:
Emp_home_select_2030_new_values_merge_s['C000'].sum()

45389.0

In [29]:
Emp_home_select_2030_new_values_merge_s_dup = Emp_home_select_2030_new_values_merge_s.drop_duplicates(subset=['h_geocode'])
Emp_home_select_2030_new_values_merge_s_dup['h_geocode']

0        120710012051002
4        120879718001022
7        120150103013009
8        120810001052013
10       120810003131000
              ...
16205    120810019163004
16207    120879714011032
16208    120810020183029
16210    120810007043047
16212    120810014051003
Name: h_geocode, Length: 9085, dtype: int64

In [30]:
Emp_home_select_2030_new_values_merge_s['h_geocode']

0        120710012051002
4        120879718001022
7        120150103013009
8        120810001052013
10       120810003131000
              ...
16205    120810019163004
16207    120879714011032
16208    120810020183029
16210    120810007043047
16212    120810014051003
Name: h_geocode, Length: 9085, dtype: int64

In [31]:
Emp_home_select_2030_new_values_merge_s['C000']

0         1.0
4         4.0
7         3.0
8         1.0
10        2.0
         ...
16205     3.0
16207    16.0
16208    12.0
16210     1.0
16212     9.0
Name: C000, Length: 9085, dtype: float64

In [32]:
Emp_home_select_2030_new_values_merge_s['cell']

0        0.0
4        0.0
7        1.0
8        0.0
10       0.0
        ...
16205    1.0
16207    0.0
16208    0.0
16210    0.0
16212    0.0
Name: cell, Length: 9085, dtype: float64

In [33]:
Emp_home_select_2030_new_values_merge_home_work = pd.merge(Emp_home_select_2030_new_values_merge_s, OD_main,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

In [34]:
Emp_home_select_2030_new_values_merge_home_work['h_geocode']

0         120710012051002
1         120710012051002
2         120710012051002
3         120710012051002
4         120710012051002
               ...
154354    120810007043047
154355    120810007043047
154356    120810014051003
154357    120810014051003
154358    120810014051003
Name: h_geocode, Length: 154359, dtype: int64

In [35]:
Emp_work_geo = Emp_work[['w_geocode','geometry']]

In [36]:
# To drop Null values in h_geocode
Emp_work_geo_select = []

Emp_work_geo_select = Emp_work_geo.dropna(subset=['w_geocode'])
Emp_work_geo_select

             w_geocode                                           geometry
9      120210113042009  POLYGON ((-81.43523 26.42843, -81.43424 26.428...
15     120210001021033  POLYGON ((-81.79587 26.14958, -81.79449 26.149...
16     120210112062003  POLYGON ((-81.54530 26.28530, -81.53442 26.285...
17     120210111141006  POLYGON ((-81.58065 26.12690, -81.58065 26.127...
58     121150006012024  POLYGON ((-82.53674 27.30010, -82.53671 27.300...
...                ...                                                ...
43986  120210108012000  POLYGON ((-81.72085 26.09891, -81.72050 26.099...
43987  120210103003013  POLYGON ((-81.79861 26.19522, -81.79598 26.195...
43989  120210102082001  POLYGON ((-81.80221 26.23201, -81.80210 26.232...
43990  120210105112010  POLYGON ((-81.69014 26.15579, -81.68997 26.155...
43991  120210104371010  POLYGON ((-81.76449 26.26234, -81.76422 26.262...

[15195 rows x 2 columns]

In [37]:
Emp_work_geo_select = Emp_work_geo_select.astype({"w_geocode":'int64'})

In [38]:
# Emp_work_geo_select.to_pickle("Emp_work_geo_select.pkl")

In [39]:
Emp_home_select_2030_new_values_home_work2 = pd.merge(Emp_home_select_2030_new_values_merge_home_work, Emp_work_geo_select,  how='left', 
                left_on=['w_geocode'], right_on = ['w_geocode'])

In [40]:
Emp_home_select_2030_new_values_home_work2['geometry_y'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [41]:

Emp_home_select_2030_new_values_home_work2['geometry_y'] = Emp_home_select_2030_new_values_home_work2['geometry_y'].to_crs('epsg:4326')

In [42]:
len(Emp_home_select_2030_new_values_home_work2)

155636

In [43]:
Emp_home_select_2030_new_values_home_work2['geometry_y'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [44]:
#The following home zone doesn't have work zone in AL State, so we will find the closest available zone using (find_cells) 

Emp_home_select_2030_new_values_home_work2[Emp_home_select_2030_new_values_home_work2['GEOID20']== '010030107032226']

Empty GeoDataFrame
Columns: [STATEFP20, COUNTYFP20, TRACTCE20, BLOCKCE20, GEOID20, NAME20, MTFCC20, UR20, UACE20, UATYPE20, FUNCSTAT20, ALAND20, AWATER20, INTPTLAT20, INTPTLON20, h_geocode, C000, CA01, CA02, CA03, CE01, CE02, CE03, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, CR01, CR02, CR03, CR04, CR05, CR07, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, createdate, geometry_x, cell, w_geocode, geometry_y]
Index: []

[0 rows x 62 columns]

In [45]:
# To drop Null values in h_geocode
#geometry_x for h_geocode #geometry_y for w_geocode

Emp_home_select_2030_new_values_home_work3 = []

Emp_home_select_2030_new_values_home_work3 = Emp_home_select_2030_new_values_home_work2.dropna(subset=['geometry_y'])
Emp_home_select_2030_new_values_home_work3

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CD02,CD03,CD04,CS01,CS02,createdate,geometry_x,cell,w_geocode,geometry_y
23,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.01216 26.91745, -82.01002 26.917..."
24,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.00568 26.92149, -82.00567 26.922..."
25,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810..."
26,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810..."
27,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201502e+14,"POLYGON ((-82.00338 27.01668, -82.00338 27.017..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155626,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,1.0,0.0,0.0,1.0,0.0,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",0.0,1.208100e+14,"POLYGON ((-82.44773 27.39627, -82.44770 27.397..."
155632,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,1.0,0.0,0.0,1.0,0.0,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",0.0,1.211500e+14,"POLYGON ((-82.52081 27.25862, -82.52042 27.258..."
155633,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.208100e+14,"POLYGON ((-82.55469 27.57930, -82.55467 27.579..."
155634,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.208100e+14,"POLYGON ((-82.49139 27.56843, -82.49139 27.569..."
155635,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.211500e+14,"POLYGON ((-82.54265 27.36911, -82.54264 27.373..."

In [46]:
Emp_home_select_2030_new_values_home_work3= Emp_home_select_2030_new_values_home_work3.reset_index()
Emp_home_select_2030_new_values_home_work3=Emp_home_select_2030_new_values_home_work3.drop(['index'],axis=1)

In [47]:
Emp_home_select_2030_new_values_home_work3['centr_x'] = ''
Emp_home_select_2030_new_values_home_work3['centr_y'] = ''

# Emp_home_select_2030_new_values_home_work3.columns.get_loc("centr_x")]   #this works with .iloc

for n in range(0,len(Emp_home_select_2030_new_values_home_work3)):
    Emp_home_select_2030_new_values_home_work3.loc[n,"centr_x"]\
    = Emp_home_select_2030_new_values_home_work3.loc[n,"geometry_x"].centroid.wkt
    
    Emp_home_select_2030_new_values_home_work3.loc[n,"centr_y"]\
    = Emp_home_select_2030_new_values_home_work3.loc[n,"geometry_y"].centroid.wkt

In [48]:
Emp_home_select_2030_new_values_home_work3

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CD04,CS01,CS02,createdate,geometry_x,cell,w_geocode,geometry_y,centr_x,centr_y
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.01216 26.91745, -82.01002 26.917...",POINT (-81.83670946952485 26.60879448950761),POINT (-82.00393932791506 26.906692300176676)
1,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.00568 26.92149, -82.00567 26.922...",POINT (-81.83670946952485 26.60879448950761),POINT (-82.00371617488155 26.919173431524626)
2,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810...",POINT (-81.83670946952485 26.60879448950761),POINT (-81.92500197920806 26.788264429264913)
3,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810...",POINT (-81.83670946952485 26.60879448950761),POINT (-81.92500197920806 26.788264429264913)
4,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201502e+14,"POLYGON ((-82.00338 27.01668, -82.00338 27.017...",POINT (-81.83670946952485 26.60879448950761),POINT (-82.00091384765571 27.015878602423022)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112714,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",0.0,1.208100e+14,"POLYGON ((-82.44773 27.39627, -82.44770 27.397...",POINT (-82.53898111624851 27.490487410652122),POINT (-82.44225378781577 27.397417520481284)
112715,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",0.0,1.211500e+14,"POLYGON ((-82.52081 27.25862, -82.52042 27.258...",POINT (-82.53898111624851 27.490487410652122),POINT (-82.51352924682716 27.256857033913214)
112716,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.208100e+14,"POLYGON ((-82.55469 27.57930, -82.55467 27.579...",POINT (-82.57536581542169 27.528115444660585),POINT (-82.55211582638482 27.580899986583574)
112717,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.208100e+14,"POLYGON ((-82.49139 27.56843, -82.49139 27.569...",POINT (-82.57536581542169 27.528115444660585),POINT (-82.48549868485239 27.571010911913238)
112718,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.211500e+14,"POLYGON ((-82.54265 27.36911, -82.54264 27.373...",POINT (-82.57536581542169 27.528115444660585),POINT (-82.53667213394652 27.371293249956587)

In [49]:
from shapely import wkt
import geopandas as gpd

Emp_home_select_2030_new_values_home_work3['centr_x'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_home_work3['centr_x'])
Emp_home_select_2030_new_values_home_work3['centr_y'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_home_work3['centr_y'])

Emp_home_select_2030_new_values_home_work3 = gpd.GeoDataFrame(Emp_home_select_2030_new_values_home_work3, geometry='centr_x')
Emp_home_select_2030_new_values_home_work3 = gpd.GeoDataFrame(Emp_home_select_2030_new_values_home_work3, geometry='centr_y')

Emp_home_select_2030_new_values_home_work3

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CD04,CS01,CS02,createdate,geometry_x,cell,w_geocode,geometry_y,centr_x,centr_y
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.01216 26.91745, -82.01002 26.917...",POINT (-81.83671 26.60879),POINT (-82.00394 26.90669)
1,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.00568 26.92149, -82.00567 26.922...",POINT (-81.83671 26.60879),POINT (-82.00372 26.91917)
2,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810...",POINT (-81.83671 26.60879),POINT (-81.92500 26.78826)
3,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810...",POINT (-81.83671 26.60879),POINT (-81.92500 26.78826)
4,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201502e+14,"POLYGON ((-82.00338 27.01668, -82.00338 27.017...",POINT (-81.83671 26.60879),POINT (-82.00091 27.01588)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112714,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",0.0,1.208100e+14,"POLYGON ((-82.44773 27.39627, -82.44770 27.397...",POINT (-82.53898 27.49049),POINT (-82.44225 27.39742)
112715,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",0.0,1.211500e+14,"POLYGON ((-82.52081 27.25862, -82.52042 27.258...",POINT (-82.53898 27.49049),POINT (-82.51353 27.25686)
112716,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.208100e+14,"POLYGON ((-82.55469 27.57930, -82.55467 27.579...",POINT (-82.57537 27.52812),POINT (-82.55212 27.58090)
112717,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.208100e+14,"POLYGON ((-82.49139 27.56843, -82.49139 27.569...",POINT (-82.57537 27.52812),POINT (-82.48550 27.57101)
112718,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,2.0,7.0,2.0,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.211500e+14,"POLYGON ((-82.54265 27.36911, -82.54264 27.373...",POINT (-82.57537 27.52812),POINT (-82.53667 27.37129)

In [50]:
from shapely.ops import transform

# Emp_home_select_2030_new_values_home_work3.columns.get_loc("centr_x") #this works with .iloc

for n in range(0,len(Emp_home_select_2030_new_values_home_work3)):
    Emp_home_select_2030_new_values_home_work3.loc[n, "centr_x"] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_home_work3.loc[n, "centr_x"])
#    
    Emp_home_select_2030_new_values_home_work3.loc[n, "centr_y"] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_home_work3.loc[n, "centr_y"])

In [51]:

coord_list_x =  Emp_home_select_2030_new_values_home_work3['centr_x'].geometry.apply(lambda p: list(p.coords)[0])

coord_list_y =  Emp_home_select_2030_new_values_home_work3['centr_y'].geometry.apply(lambda p: list(p.coords)[0])


# rc = dataset_ex[column_name].apply(lambda x: pd.Series(x, dtype="object"))


Emp_home_select_2030_new_values_home_work3['centr_x_co'] = coord_list_x

Emp_home_select_2030_new_values_home_work3['centr_y_co'] = coord_list_y

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

In [52]:
from geopy.distance import geodesic as GD  

Emp_home_select_2030_new_values_home_work3['dist'] = ''

# Emp_home_select_2030_new_values_home_work3.columns.get_loc("dist") #this works with .iloc

for n in range(0,len(Emp_home_select_2030_new_values_home_work3)):
#     print('n=',n)
    Emp_home_select_2030_new_values_home_work3.loc[n,"dist"]\
    = GD(Emp_home_select_2030_new_values_home_work3.loc[n,"centr_x_co"],Emp_home_select_2030_new_values_home_work3.loc[n,"centr_y_co"]).km

In [53]:
#Remove those zones that w_geocode is the same as h_geocode (zones people live and work in the same one)

Emp_home_select_2030_new_values_home_work3___ = Emp_home_select_2030_new_values_home_work3[Emp_home_select_2030_new_values_home_work3['w_geocode']!=Emp_home_select_2030_new_values_home_work3['h_geocode']]


len(Emp_home_select_2030_new_values_home_work3___)

112538

In [54]:
Emp_home_select_2030_new_values_home_work3_ = Emp_home_select_2030_new_values_home_work3___.select_dtypes(exclude=['geometry'])

In [55]:
len(Emp_home_select_2030_new_values_home_work3_)

112538

In [56]:
len(Emp_home_select_2030_new_values_home_work3_['h_geocode'].unique())

8877

In [57]:
Emp_home_select_2030_new_values_home_work3_final =\
    Emp_home_select_2030_new_values_home_work3.loc[Emp_home_select_2030_new_values_home_work3_.groupby(['h_geocode'])['dist'].idxmin()].sort_index()

In [58]:
len(Emp_home_select_2030_new_values_home_work3_final)

8877

In [59]:
Emp_home_select_2030_new_values_home_work3_final

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,createdate,geometry_x,cell,w_geocode,geometry_y,centr_x,centr_y,centr_x_co,centr_y_co,dist
82,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.207100e+14,"POLYGON ((-81.83893 26.60236, -81.83888 26.602...",POINT (26.60879 -81.83671),POINT (26.60195 -81.83745),"(26.60879448950761, -81.83670946952485)","(26.60195360533018, -81.83745360718054)",0.761567
355,12,087,971800,1022,120879718001022,Block 1022,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",POINT (24.56733 -81.73019),POINT (24.57052 -81.73536),"(24.567331297140306, -81.73018543710354)","(24.570518191572866, -81.73536038670079)",0.631994
434,12,015,010301,3009,120150103013009,Block 3009,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.05398 26.88800, -82.05390 26.888...",1.0,1.201501e+14,"POLYGON ((-82.07083 26.90300, -82.07082 26.903...",POINT (26.89843 -82.04864),POINT (26.90338 -82.06281),"(26.898428984189465, -82.04864164289536)","(26.90338473738821, -82.06281275534279)",1.511083
512,12,081,000105,2013,120810001052013,Block 2013,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.56297 27.47066, -82.56096 27.470...",0.0,1.208100e+14,"POLYGON ((-82.55892 27.46871, -82.55892 27.468...",POINT (27.46995 -82.56067),POINT (27.46936 -82.55676),"(27.469953224671354, -82.56067433150785)","(27.4693646814615, -82.55675637221044)",0.392701
596,12,081,000313,1000,120810003131000,Block 1000,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.56310 27.44031, -82.56257 27.440...",0.0,1.208100e+14,"POLYGON ((-82.56307 27.43159, -82.56275 27.431...",POINT (27.43847 -82.56104),POINT (27.43033 -82.56235),"(27.438468618486127, -82.56104460107711)","(27.43033401230265, -82.56235256307012)",0.910628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112693,12,081,001916,3004,120810019163004,Block 3004,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.51255 27.58683, -82.51128 27.588...",1.0,1.208100e+14,"POLYGON ((-82.56547 27.49466, -82.56543 27.495...",POINT (27.58767 -82.51136),POINT (27.49459 -82.56481),"(27.587667683685137, -82.51136264593538)","(27.494588873790878, -82.5648145914234)",11.587041
112699,12,087,971401,1032,120879714011032,Block 1032,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-81.35092 24.67245, -81.35092 24.672...",0.0,1.208797e+14,"POLYGON ((-81.36233 24.67438, -81.36080 24.674...",POINT (24.67234 -81.35061),POINT (24.67195 -81.35948),"(24.67234482418839, -81.35060508777484)","(24.67194887577219, -81.35947862744457)",0.899217
112704,12,081,002018,3029,120810020183029,Block 3029,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.42543 27.48683, -82.42515 27.486...",0.0,1.208100e+14,"POLYGON ((-82.45919 27.44140, -82.45919 27.442...",POINT (27.48524 -82.42345),POINT (27.44915 -82.45439),"(27.48523508150931, -82.42345191216556)","(27.44914815856054, -82.45438614070632)",5.033827
112707,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",0.0,1.208100e+14,"POLYGON ((-82.56678 27.47713, -82.56306 27.477...",POINT (27.49049 -82.53898),POINT (27.47570 -82.56439),"(27.490487410652122, -82.53898111624851)","(27.47569707264196, -82.56439020787943)",2.99863
112716,12,081,001405,1003,120810014051003,Block 1003,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...",0.0,1.208100e+14,"POLYGON ((-82.55469 27.57930, -82.55467 27.579...",POINT (27.52812 -82.57537),POINT (27.58090 -82.55212),"(27.528115444660585, -82.57536581542169)","(27.580899986583574, -82.55211582638482)",6.283759

In [60]:
len(Emp_home_select_2030_new_values_home_work3_final['dist'].unique())

8870

In [61]:
df1_dup= pd.DataFrame(Emp_home_select_2030_new_values_home_work3_final.pivot_table(index=['dist'], aggfunc='size'), columns=['size'])

df1_dup[df1_dup['size']>1]

          size
dist
0.164471     2
0.287071     2
0.458122     2
0.565498     2
0.591535     2
0.910628     2
2.078687     2

In [62]:
Emp_home_select_2030_new_values_home_work3_final_missing = Emp_home_select_2030_new_values_home_work2.loc[~Emp_home_select_2030_new_values_home_work2['GEOID20'].isin(Emp_home_select_2030_new_values_home_work3_final['GEOID20'])]
len(Emp_home_select_2030_new_values_home_work3_final_missing)

285

In [63]:
len(Emp_home_select_2030_new_values_home_work3_final)

8877

In [64]:
import pandas as pd 
Emp_home_select_2030_new_values_home_work3_final_=pd.concat([Emp_home_select_2030_new_values_home_work3_final, Emp_home_select_2030_new_values_home_work3_final_missing], axis=0)
len(Emp_home_select_2030_new_values_home_work3_final_)

9162

In [65]:
Emp_home_select_2030_new_values_home_work3_final['C000'].sum()

44518.0

In [66]:
Emp_home_select_2030_new_values_home_work3_final_['C000'].sum()

45708.0

In [67]:
Emp_home_select_2030_new_values_home_work3_final_['C000']

82        1.0
355       4.0
434       3.0
512       1.0
596       2.0
         ...
155075    5.0
155248    1.0
155249    1.0
155442    5.0
155448    9.0
Name: C000, Length: 9162, dtype: float64

In [68]:
Emp_home_select_2030_new_values_home_work3_final_['C000'].sum()

45708.0

In [69]:
select = Emp_home_select_2030_new_values_home_work3_final_

In [70]:
 #geometry_x for h_geocode #geometry_y for w_geocode
select= select[['h_geocode','geometry_x','C000','CA01','CA02','CA03','CR01','CR02','CR03','CR04','CR05','CR07','CE01',
                'CE02','CE03','CT01','CT02','CD01','CD02','CD03','CD04','CS01','CS02','CNS01','CNS02','CNS03','CNS04',
                'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                'CNS17','CNS18','CNS19','CNS20','cell','w_geocode','geometry_y','dist']]

In [71]:
len(select)

9162

In [72]:
select_min_select2 = select

In [73]:
# h_geocode_x is h_geocode associated with each w_geocode
# h_geocode_y is original h_geocode (projected employees)
#geometry_x for h_geocode_y #geometry_y for w_geocode



select_min_OD = pd.merge(OD_main, select_min_select2,  how='right', 
                left_on=['w_geocode'], right_on = ['w_geocode'])

In [74]:
len(select_min_OD)

4946809

In [75]:
select_hgeocode = pd.merge(select_min_OD, Emp_cells_sum,  how='left', 
                left_on=['h_geocode_x'], right_on = ['h_geocode'])

In [76]:
len(select_hgeocode)

4946809

In [77]:
#cell_y for h_geocode_x (associate with each w_geocode)
select_hgeocode =  select_hgeocode.dropna(subset=['cell_y'])
len(select_hgeocode)

2496521

In [78]:
# select_hgeocode = select_hgeocode.drop(['row_num'], axis = 1)
select_hgeocode = select_hgeocode.astype({"h_geocode":'int64'})

In [79]:
# Emp_home_geo = Emp_home_select[['geometry','h_geocode']]
# Emp_home_geo= Emp_home_geo.astype ({"h_geocode":'int64'})

In [80]:
# Emp_home_geo.to_pickle("Emp_home_geo.pkl")

In [81]:
Emp_home_geo= pd.read_pickle('Emp_home_geo.pkl')

In [82]:
len(Emp_home_geo)

34223

In [83]:
Emp_home_geo

                                                 geometry        h_geocode
54      POLYGON ((-81.70222 26.25009, -81.70186 26.250...  120210104352008
55      POLYGON ((-81.71808 26.24722, -81.71795 26.247...  120210104351004
56      POLYGON ((-81.79335 26.17518, -81.79232 26.175...  120210002001025
57      POLYGON ((-81.43775 26.42658, -81.43746 26.426...  120210113042013
58      POLYGON ((-81.43369 26.42571, -81.43158 26.425...  120210114002005
...                                                   ...              ...
143190  POLYGON ((-82.48703 27.56261, -82.48697 27.562...  120810019081011
143191  POLYGON ((-82.57396 27.45439, -82.57092 27.454...  120810002014001
143192  POLYGON ((-82.57562 27.52858, -82.57510 27.528...  120810014051003
143311  POLYGON ((-82.12026 27.26250, -82.11883 27.265...  120810020102028
143312  POLYGON ((-82.11041 27.46021, -82.10932 27.460...  120810019142045

[34223 rows x 2 columns]

In [84]:
select_hgeocode['geometry_x1'] = select_hgeocode['geometry_x']
select_hgeocode['geometry_y1'] = select_hgeocode['geometry_y']

In [85]:
select_hgeocode = select_hgeocode.drop(['geometry_x','geometry_y'], axis = 1)

In [86]:
# h_geocode_x is h_geocode associated with each w_geocode
# h_geocode_y is original h_geocode (projected employees)
#geometry_x1 for h_geocode_y        #geometry for h_geocode_x       #geometry_y1 for w_geocode
#cell_x for h_geocode_y #cell_y for h_geocode_x


select_hgeocode_geo = pd.merge(select_hgeocode, Emp_home_geo,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

select_hgeocode_geo

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS18,CNS19,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry
0,1.207100e+14,1.207104e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.761567,120710401171000,434.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553..."
1,1.207100e+14,1.207104e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.761567,120710401174006,1.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.81464 26.55431, -81.81258 26.554..."
2,1.207100e+14,1.207105e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.761567,120710503122003,12.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.75083 26.37834, -81.75082 26.378..."
3,1.208797e+14,1.208797e+14,120879718001022,4.0,1.0,2.0,1.0,3.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.631994,120879713001011,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.10946 24.70668, -81.10944 24.706..."
4,1.201501e+14,1.201501e+14,120150103013009,3.0,0.0,2.0,1.0,3.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.511083,120150101001009,47.0,"POLYGON ((-82.05398 26.88800, -82.05390 26.888...","POLYGON ((-82.07083 26.90300, -82.07082 26.903...","POLYGON ((-81.95094 27.00205, -81.95092 27.002..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2496516,1.206105e+14,1.211500e+14,120150105052077,5.0,0.0,2.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,121150027451033,10.0,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",None,"POLYGON ((-82.18120 27.05343, -82.18069 27.054..."
2496517,1.209502e+14,1.202101e+14,120150204022186,9.0,0.0,9.0,0.0,9.0,0.0,0.0,...,3.0,0.0,0.0,0.0,NaN,120210105192000,146.0,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",None,"POLYGON ((-81.71855 26.14931, -81.71823 26.149..."
2496518,1.209502e+14,1.207100e+14,120150204022186,9.0,0.0,9.0,0.0,9.0,0.0,0.0,...,3.0,0.0,0.0,0.0,NaN,120710019172006,14.0,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",None,"POLYGON ((-81.93580 26.51814, -81.93390 26.518..."
2496519,1.209502e+14,1.207101e+14,120150204022186,9.0,0.0,9.0,0.0,9.0,0.0,0.0,...,3.0,0.0,0.0,0.0,NaN,120710104202006,14.0,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",None,"POLYGON ((-82.01887 26.62789, -82.01882 26.627..."
2496520,1.209502e+14,1.208100e+14,120150204022186,9.0,0.0,9.0,0.0,9.0,0.0,0.0,...,3.0,0.0,0.0,0.0,NaN,120810020191008,5.0,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",None,"POLYGON ((-82.40782 27.44046, -82.40767 27.440..."

In [87]:
select_hgeocode_geo_ = select_hgeocode_geo.dropna(subset=['geometry_y1'])
len(select_hgeocode_geo_)

2487954

In [88]:
select_hgeocode_geo3 = select_hgeocode_geo_.dropna(subset=['cell_y'])
len(select_hgeocode_geo3)

2487954

In [89]:
select_hgeocode_geo3['centr_x'] = ''
select_hgeocode_geo3['centr_y'] = ''


for n in range(0,len(select_hgeocode_geo3)):
    select_hgeocode_geo3.iloc[n,select_hgeocode_geo3.columns.get_loc("centr_x")]\
    = select_hgeocode_geo3.iloc\
    [n,select_hgeocode_geo3.columns.get_loc("geometry")].centroid.wkt
    
    select_hgeocode_geo3.iloc[n,select_hgeocode_geo3.columns.get_loc("centr_y")]\
    = select_hgeocode_geo3.iloc\
    [n,select_hgeocode_geo3.columns.get_loc("geometry_y1")].centroid.wkt

In [90]:
from shapely import wkt
import geopandas as gpd

select_hgeocode_geo3['centr_x'] = gpd.GeoSeries.from_wkt(select_hgeocode_geo3['centr_x'])
select_hgeocode_geo3['centr_y'] = gpd.GeoSeries.from_wkt(select_hgeocode_geo3['centr_y'])

select_hgeocode_geo3 = gpd.GeoDataFrame(select_hgeocode_geo3, geometry='centr_x')
select_hgeocode_geo3 = gpd.GeoDataFrame(select_hgeocode_geo3, geometry='centr_y')

select_hgeocode_geo3

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,centr_x,centr_y
0,1.207100e+14,1.207104e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.761567,120710401171000,434.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",POINT (-81.82858 26.55344),POINT (-81.83745 26.60195)
1,1.207100e+14,1.207104e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.761567,120710401174006,1.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.81464 26.55431, -81.81258 26.554...",POINT (-81.80925 26.55189),POINT (-81.83745 26.60195)
2,1.207100e+14,1.207105e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.761567,120710503122003,12.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.75083 26.37834, -81.75082 26.378...",POINT (-81.74807 26.37807),POINT (-81.83745 26.60195)
3,1.208797e+14,1.208797e+14,120879718001022,4.0,1.0,2.0,1.0,3.0,1.0,0.0,...,0.0,0.0,0.631994,120879713001011,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.10946 24.70668, -81.10944 24.706...",POINT (-81.10911 24.70639),POINT (-81.73536 24.57052)
4,1.201501e+14,1.201501e+14,120150103013009,3.0,0.0,2.0,1.0,3.0,0.0,0.0,...,0.0,1.0,1.511083,120150101001009,47.0,"POLYGON ((-82.05398 26.88800, -82.05390 26.888...","POLYGON ((-82.07083 26.90300, -82.07082 26.903...","POLYGON ((-81.95094 27.00205, -81.95092 27.002...",POINT (-81.85844 27.00261),POINT (-82.06281 26.90338)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2487949,1.208100e+14,1.208100e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,0.0,0.0,6.283759,120810020253004,149.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.45344 27.49613, -82.45294 27.496...",POINT (-82.45104 27.49122),POINT (-82.55212 27.58090)
2487950,1.208100e+14,1.211500e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,0.0,0.0,6.283759,121150012053000,146.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.49824 27.38336, -82.49822 27.383...",POINT (-82.48824 27.38446),POINT (-82.55212 27.58090)
2487951,1.208100e+14,1.211500e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,0.0,0.0,6.283759,121150012053007,55.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.50110 27.38589, -82.50110 27.385...",POINT (-82.49965 27.38665),POINT (-82.55212 27.58090)
2487952,1.208100e+14,1.211500e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,0.0,0.0,6.283759,121150017031001,146.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.51417 27.28410, -82.51386 27.284...",POINT (-82.51114 27.28004),POINT (-82.55212 27.58090)
2487953,1.208100e+14,1.211500e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,0.0,0.0,6.283759,121150027321000,184.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.39778 27.03035, -82.39778 27.030...",POINT (-82.39291 27.03355),POINT (-82.55212 27.58090)

In [91]:
from shapely.ops import transform

for n in range(0,len(select_hgeocode_geo3)):
    select_hgeocode_geo3.iloc[n, select_hgeocode_geo3.columns.get_loc("centr_x")] = transform(lambda x, y: (y, x), select_hgeocode_geo3.iloc[n, select_hgeocode_geo3.columns.get_loc("centr_x")])
#    
    select_hgeocode_geo3.iloc[n, select_hgeocode_geo3.columns.get_loc("centr_y")] = transform(lambda x, y: (y, x), select_hgeocode_geo3.iloc[n, select_hgeocode_geo3.columns.get_loc("centr_y")])

In [92]:
coord_list_x =  select_hgeocode_geo3['centr_x'].geometry.apply(lambda p: list(p.coords)[0])
coord_list_y =  select_hgeocode_geo3['centr_y'].geometry.apply(lambda p: list(p.coords)[0])


select_hgeocode_geo3['centr_x_co'] = coord_list_x

select_hgeocode_geo3['centr_y_co'] = coord_list_y

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

In [93]:
select_hgeocode_geo3= select_hgeocode_geo3.reset_index()
select_hgeocode_geo3=select_hgeocode_geo3.drop(['index'],axis=1)
select_hgeocode_geo3

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,centr_x,centr_y,centr_x_co,centr_y_co
0,1.207100e+14,1.207104e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.761567,120710401171000,434.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",POINT (26.55344 -81.82858),POINT (26.60195 -81.83745),"(26.553440439226623, -81.82857774635599)","(26.60195360533018, -81.83745360718054)"
1,1.207100e+14,1.207104e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.761567,120710401174006,1.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.81464 26.55431, -81.81258 26.554...",POINT (26.55189 -81.80925),POINT (26.60195 -81.83745),"(26.55188845469163, -81.8092548148376)","(26.60195360533018, -81.83745360718054)"
2,1.207100e+14,1.207105e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.761567,120710503122003,12.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.75083 26.37834, -81.75082 26.378...",POINT (26.37807 -81.74807),POINT (26.60195 -81.83745),"(26.37806981170607, -81.74807257700093)","(26.60195360533018, -81.83745360718054)"
3,1.208797e+14,1.208797e+14,120879718001022,4.0,1.0,2.0,1.0,3.0,1.0,0.0,...,0.631994,120879713001011,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.10946 24.70668, -81.10944 24.706...",POINT (24.70639 -81.10911),POINT (24.57052 -81.73536),"(24.706386615281172, -81.10910699357544)","(24.570518191572866, -81.73536038670079)"
4,1.201501e+14,1.201501e+14,120150103013009,3.0,0.0,2.0,1.0,3.0,0.0,0.0,...,1.511083,120150101001009,47.0,"POLYGON ((-82.05398 26.88800, -82.05390 26.888...","POLYGON ((-82.07083 26.90300, -82.07082 26.903...","POLYGON ((-81.95094 27.00205, -81.95092 27.002...",POINT (27.00261 -81.85844),POINT (26.90338 -82.06281),"(27.00260783004593, -81.85843666422753)","(26.90338473738821, -82.06281275534279)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2487949,1.208100e+14,1.208100e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,6.283759,120810020253004,149.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.45344 27.49613, -82.45294 27.496...",POINT (27.49122 -82.45104),POINT (27.58090 -82.55212),"(27.49122292657018, -82.45103553632057)","(27.580899986583574, -82.55211582638482)"
2487950,1.208100e+14,1.211500e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,6.283759,121150012053000,146.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.49824 27.38336, -82.49822 27.383...",POINT (27.38446 -82.48824),POINT (27.58090 -82.55212),"(27.384461558010496, -82.48823914474545)","(27.580899986583574, -82.55211582638482)"
2487951,1.208100e+14,1.211500e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,6.283759,121150012053007,55.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.50110 27.38589, -82.50110 27.385...",POINT (27.38665 -82.49965),POINT (27.58090 -82.55212),"(27.386646558458633, -82.49964551925828)","(27.580899986583574, -82.55211582638482)"
2487952,1.208100e+14,1.211500e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,6.283759,121150017031001,146.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.51417 27.28410, -82.51386 27.284...",POINT (27.28004 -82.51114),POINT (27.58090 -82.55212),"(27.28004476632911, -82.511142602728)","(27.580899986583574, -82.55211582638482)"
2487953,1.208100e+14,1.211500e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,6.283759,121150027321000,184.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.39778 27.03035, -82.39778 27.030...",POINT (27.03355 -82.39291),POINT (27.58090 -82.55212),"(27.033553890061416, -82.39291418870401)","(27.580899986583574, -82.55211582638482)"

In [94]:
from geopy.distance import geodesic as GD  

select_hgeocode_geo3['dist_x'] = ''

for n in range(0,len(select_hgeocode_geo3)):
#     print('n=',n)
    select_hgeocode_geo3.loc[n,"dist_x"]\
    = GD(select_hgeocode_geo3.loc[n,"centr_x_co"],select_hgeocode_geo3.loc[n,"centr_y_co"]).km

In [95]:
len(select_hgeocode_geo3)

2487954

In [96]:
select_hgeocode_geo4_1 = select_hgeocode_geo3.drop(['centr_x_co','centr_y_co','centr_x','centr_y'], axis = 1)

In [97]:
select_hgeocode_geo4_2 = select_hgeocode_geo4_1[select_hgeocode_geo4_1['cell_y']>select_hgeocode_geo4_1['C000']]
len(select_hgeocode_geo4_2)

1807249

In [98]:
select_hgeocode_geo4_2_1 =  select_hgeocode_geo4_2[select_hgeocode_geo4_2['w_geocode'] != select_hgeocode_geo4_2['h_geocode_y']]
len(select_hgeocode_geo4_2_1)

1807249

In [99]:
select_hgeocode_geo4_2_2 = select_hgeocode_geo4_2_1[select_hgeocode_geo4_2_1['w_geocode'] != select_hgeocode_geo4_2_1['h_geocode_x']]
len(select_hgeocode_geo4_2_2)

1806567

In [100]:
#to get the min dist from orginal h_geocode (h_geocode_y) to w_geocode



select_hgeocode_geo5_1 =\
    select_hgeocode_geo4_2_2.loc[ select_hgeocode_geo4_2_2.groupby(['h_geocode_y'])['dist_x'].idxmin()].sort_index()

len(select_hgeocode_geo5_1)

8488

In [101]:
len(select_hgeocode_geo5_1['h_geocode_y'].unique())

8488

## This is the output I'm looking for

In [102]:
del select

In [103]:
del select_min_OD

In [104]:
del OD_main

In [105]:
select_hgeocode_geo5_3 = select_hgeocode_geo5_1

In [106]:
# h_geocode_x is h_geocode associated with each w_geocode
# h_geocode_y is original h_geocode (projected employees)
#geometry_x1 for h_geocode_y        #geometry for h_geocode_x       #geometry_y1 for w_geocode
#cell_x for h_geocode_y #cell_y for h_geocode_x


# select_hgeocode_geo5_6_ = select_hgeocode_geo5_3.drop_duplicates(subset=['h_geocode_y'])
select_hgeocode_geo5_6_ = select_hgeocode_geo5_3

select_hgeocode_geo5_6_

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS19,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,dist_x
0,1.207100e+14,1.207104e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.761567,120710401171000,434.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",5.447355
23,1.201501e+14,1.201501e+14,120150103013009,3.0,0.0,2.0,1.0,3.0,0.0,0.0,...,0.0,0.0,1.0,1.511083,120150104053012,492.0,"POLYGON ((-82.05398 26.88800, -82.05390 26.888...","POLYGON ((-82.07083 26.90300, -82.07082 26.903...","POLYGON ((-82.08442 26.89855, -82.08441 26.898...",1.034546
175,1.208100e+14,1.208100e+14,120810001052013,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.392701,120810008121002,13.0,"POLYGON ((-82.56297 27.47066, -82.56096 27.470...","POLYGON ((-82.55892 27.46871, -82.55892 27.468...","POLYGON ((-82.54662 27.47652, -82.54662 27.476...",1.811006
265,1.208100e+14,1.208100e+14,120810003131000,2.0,0.0,1.0,1.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.910628,120810008053004,133.0,"POLYGON ((-82.56310 27.44031, -82.56257 27.440...","POLYGON ((-82.56307 27.43159, -82.56275 27.431...","POLYGON ((-82.53010 27.39671, -82.53005 27.396...",5.404398
271,1.208100e+14,1.208100e+14,120810003051007,14.0,3.0,7.0,4.0,12.0,2.0,0.0,...,0.0,0.0,0.0,0.597262,120810003042007,29.0,"POLYGON ((-82.55490 27.44363, -82.55488 27.444...","POLYGON ((-82.55493 27.45132, -82.55481 27.451...","POLYGON ((-82.56123 27.44769, -82.56034 27.447...",1.009383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2485434,1.208100e+14,1.208100e+14,120810019163004,3.0,0.0,2.0,1.0,3.0,0.0,0.0,...,0.0,0.0,1.0,11.587041,120810001053014,60.0,"POLYGON ((-82.51255 27.58683, -82.51128 27.588...","POLYGON ((-82.56547 27.49466, -82.56543 27.495...","POLYGON ((-82.57124 27.47295, -82.57124 27.473...",2.609075
2487289,1.208797e+14,1.208797e+14,120879714011032,16.0,0.0,16.0,0.0,16.0,0.0,0.0,...,0.0,1.0,0.0,0.899217,120879710012039,96.0,"POLYGON ((-81.35092 24.67245, -81.35092 24.672...","POLYGON ((-81.36233 24.67438, -81.36080 24.674...","POLYGON ((-81.01974 24.72897, -81.01960 24.729...",35.182148
2487615,1.208100e+14,1.208100e+14,120810020183029,12.0,2.0,4.0,6.0,11.0,1.0,0.0,...,0.0,0.0,0.0,5.033827,120810020121004,35.0,"POLYGON ((-82.42543 27.48683, -82.42515 27.486...","POLYGON ((-82.45919 27.44140, -82.45919 27.442...","POLYGON ((-82.46830 27.44550, -82.46819 27.445...",0.783195
2487829,1.208100e+14,1.208100e+14,120810007043047,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.99863,120810001053014,60.0,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...","POLYGON ((-82.56678 27.47713, -82.56306 27.477...","POLYGON ((-82.57124 27.47295, -82.57124 27.473...",0.594089
2487940,1.208100e+14,1.208100e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,0.0,0.0,0.0,6.283759,120810016041008,16.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.54383 27.56064, -82.54383 27.560...",2.554003

In [107]:
len(Emp_home_select_2030_new_values_home_work3_final)

8877

In [108]:
len(Emp_home_select_2030_new_values_home_work3_final_)

9162

In [109]:
Emp_home_select_2030_new_values_home_work3_final_['h_geocode']

82        120710012051002
355       120879718001022
434       120150103013009
512       120810001052013
596       120810003131000
               ...
155075    120150304022029
155248    120879725002054
155249    120879725002054
155442    120150105052077
155448    120150204022186
Name: h_geocode, Length: 9162, dtype: int64

In [110]:
Emp_home_select_2030_new_values_home_work3_final['h_geocode']

82        120710012051002
355       120879718001022
434       120150103013009
512       120810001052013
596       120810003131000
               ...
112693    120810019163004
112699    120879714011032
112704    120810020183029
112707    120810007043047
112716    120810014051003
Name: h_geocode, Length: 8877, dtype: int64

In [111]:
Emp_home_select_2030_new_values_home_work3_final['h_geocode']

82        120710012051002
355       120879718001022
434       120150103013009
512       120810001052013
596       120810003131000
               ...
112693    120810019163004
112699    120879714011032
112704    120810020183029
112707    120810007043047
112716    120810014051003
Name: h_geocode, Length: 8877, dtype: int64

In [112]:
select_min_select2_missing = select_min_select2.loc[~select_min_select2['h_geocode'].isin(Emp_home_select_2030_new_values_home_work3_final['h_geocode'])]
select_min_select2_missing

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS15,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist
109054,120150203021098,"POLYGON ((-82.14857 26.97642, -82.14765 26.976...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.210302e+14,None,NaN
109297,120150203011144,"POLYGON ((-82.15527 27.02277, -82.15432 27.022...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.201105e+14,None,NaN
109298,120150203011144,"POLYGON ((-82.15527 27.02277, -82.15432 27.022...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.209901e+14,None,NaN
109684,120710401271004,"POLYGON ((-81.71670 26.64980, -81.71626 26.649...",1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.203101e+14,None,NaN
109800,120710403023032,"POLYGON ((-81.68050 26.57491, -81.67979 26.574...",2.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.201106e+14,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155075,120150304022029,"POLYGON ((-82.28716 26.82583, -82.28708 26.825...",5.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN
155248,120879725002054,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.208600e+14,None,NaN
155249,120879725002054,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.210501e+14,None,NaN
155442,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",5.0,0.0,2.0,3.0,5.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN
155448,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,...,1.0,1.0,0.0,3.0,0.0,0.0,0.0,1.209502e+14,None,NaN

In [113]:
# select_2040_hgeocode_geo4_3_1 is the remaining zones from select_2040_hgeocode_geo4_3 
# after excluding zones that workzones number = homezone number (zones poeple work and live)

select_2030_hgeocode_geo4_3_1 = select_min_select2.loc[~select_min_select2['h_geocode'].isin(select_hgeocode_geo5_6_['h_geocode_y'])]
len(select_2030_hgeocode_geo4_3_1)

674

In [114]:
import pandas as pd 
select_2030_hgeocode_geo4_3_1_conc=pd.concat([select_2030_hgeocode_geo4_3_1, select_min_select2_missing], axis=0)
len(select_2030_hgeocode_geo4_3_1_conc)

959

In [115]:
Emp_cells_sum

             h_geocode  cell
0      120150101001000     8
1      120150101001005     3
2      120150101001009    47
3      120150101001010     5
4      120150101001011     1
...                ...   ...
19854  121150027472071     2
19855  121150027481003    18
19856  121150027481009    25
19857  121150027481010     7
19858  121150027482003     5

[19859 rows x 2 columns]

In [116]:
Emp_cells_sum_no_dups = Emp_cells_sum.drop_duplicates(subset=['h_geocode'])
Emp_cells_sum_no_dups_pre = Emp_cells_sum_no_dups
Emp_cells_sum_no_dups_pre = Emp_cells_sum_no_dups
Emp_cells_sum_no_dups_final = Emp_cells_sum_no_dups_pre.loc[~Emp_cells_sum_no_dups_pre['h_geocode'].isin(select_hgeocode_geo5_6_['h_geocode_x'])]

len(Emp_cells_sum_no_dups_final)

17122

In [117]:
Emp_home_select_2030_new_geo = Emp_home_select_2030_part2_new2[['h_geocode','geometry']]

In [118]:
Emp_home_select_2030_new_geo = Emp_home_select_2030_new_geo.astype({"h_geocode":'int64'})

In [119]:
Emp_cells_sum_no_dups_final_geo = pd.merge(Emp_cells_sum_no_dups_final,Emp_home_select_2030_new_geo, how='left',
                                          left_on=['h_geocode'],right_on = ['h_geocode'])
Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo.dropna(subset=['geometry'])
len(Emp_cells_sum_no_dups_final_geo2)

17122

In [120]:
def find_coordinates(Emp_cells_sum_no_dups_final_geo2):

    from shapely import wkt
    import geopandas as gpd
    from shapely.ops import transform

    
    temp = Emp_cells_sum_no_dups_final_geo2.copy()

    Emp_cells_sum_no_dups_final_geo2['centr'] = ''
    
#     Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.reset_index()
#     Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.drop(['index'], axis = 1)
    
#     print(Emp_cells_sum_no_dups_final_geo2)
        
#     for i in range (0,len(Emp_cells_sum_no_dups_final_geo2)):
    if 'geometry' in Emp_cells_sum_no_dups_final_geo2.columns:
        print('Yes')
    else: 
        print('No')
        Emp_cells_sum_no_dups_final_geo2.rename(columns = {'geometry_x':'geometry'}, inplace = True)

    

    for n in range(0,len(Emp_cells_sum_no_dups_final_geo2)):
        Emp_cells_sum_no_dups_final_geo2.iloc[n,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("centr")]\
        = Emp_cells_sum_no_dups_final_geo2.iloc\
        [n,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("geometry")].centroid.wkt

    Emp_cells_sum_no_dups_final_geo2['centr'] = gpd.GeoSeries.from_wkt(Emp_cells_sum_no_dups_final_geo2['centr'])
    Emp_cells_sum_no_dups_final_geo2 = gpd.GeoDataFrame(Emp_cells_sum_no_dups_final_geo2, geometry='centr')

    for n in range(0,len(Emp_cells_sum_no_dups_final_geo2)):
        Emp_cells_sum_no_dups_final_geo2.iloc[n, Emp_cells_sum_no_dups_final_geo2.columns.get_loc("centr")] = transform(lambda x, y: (y, x),
                            Emp_cells_sum_no_dups_final_geo2.iloc[n, Emp_cells_sum_no_dups_final_geo2.columns.get_loc("centr")])

    coord_list =  Emp_cells_sum_no_dups_final_geo2['centr'].geometry.apply(lambda p: list(p.coords)[0])
    Emp_cells_sum_no_dups_final_geo2['centr_co'] = coord_list
        
    if 'geometry' in temp.columns:
        print('Yes')
    else: 
        print('No')
        Emp_cells_sum_no_dups_final_geo2.rename(columns = {'geometry':'geometry_x'}, inplace = True)
        Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.drop(['centr_x_co','centr'],axis=1)
        Emp_cells_sum_no_dups_final_geo2.rename(columns = {'centr_co':'centr_x_co'}, inplace = True)


    return Emp_cells_sum_no_dups_final_geo2

In [121]:
Emp_cells_sum_no_dups_final_geo2= find_coordinates(Emp_cells_sum_no_dups_final_geo2)

Yes

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

Yes

In [122]:
# Emp_home_select_2030_new_values_home_work3 for (h_geocode and w_geocode relations) 

Emp_home_select_2030_new_values_home_work3_subset = Emp_home_select_2030_new_values_home_work3[['h_geocode','centr_x_co']]

select_2030_hgeocode_geo4_3_1_geo = pd.merge(select_2030_hgeocode_geo4_3_1_conc,Emp_home_select_2030_new_values_home_work3_subset, how='left',
                                          left_on=['h_geocode'],right_on = ['h_geocode'])
select_2030_hgeocode_geo4_3_1_geo2 = select_2030_hgeocode_geo4_3_1_geo.drop_duplicates(subset=['h_geocode'])
select_2030_hgeocode_geo4_3_1_geo2

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist,centr_x_co
0,120879718001022,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",4.0,1.0,2.0,1.0,3.0,1.0,0.0,0.0,...,2.0,0.0,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",0.631994,"(24.567331297140306, -81.73018543710354)"
89,120879717003014,"POLYGON ((-81.67570 24.60202, -81.67570 24.602...",8.0,2.0,4.0,2.0,7.0,1.0,0.0,0.0,...,2.0,0.0,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.66069 24.60108, -81.66053 24.601...",1.129322,"(24.599937349116697, -81.66874555206641)"
192,120710201031017,"POLYGON ((-81.90898 26.72997, -81.90881 26.729...",2.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.207102e+14,"POLYGON ((-81.90026 26.73959, -81.90024 26.739...",0.95799,"(26.727752498586256, -81.89952848815554)"
260,120879715011003,"POLYGON ((-81.50261 24.66138, -81.50261 24.661...",2.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.48056 24.66379, -81.48054 24.664...",0.735556,"(24.66276660460335, -81.48720077363569)"
346,120710103052003,"POLYGON ((-81.91549 26.64060, -81.91547 26.644...",19.0,4.0,8.0,7.0,16.0,3.0,0.0,0.0,...,4.0,1.0,2.0,1.0,0.0,0.0,1.207101e+14,"POLYGON ((-81.91040 26.64691, -81.90886 26.646...",0.441576,"(26.643469872107385, -81.91235912964126)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,120710403122096,"POLYGON ((-81.62359 26.54015, -81.62357 26.540...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.205701e+14,None,NaN,NaN
6203,120150304022029,"POLYGON ((-82.28716 26.82583, -82.28708 26.825...",5.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN,NaN
6204,120879725002054,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.208600e+14,None,NaN,NaN
6206,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",5.0,0.0,2.0,3.0,5.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,NaN
6207,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.209502e+14,None,NaN,NaN

In [123]:
#this cell trying to find those rows that don't have centr_x_co

select_2030_hgeocode_geo4_3_1_geo22w2w2 = select_2030_hgeocode_geo4_3_1_geo2.dropna(subset=['centr_x_co'])
select_2030_hgeocode_geo4_3_1_geo22w2w2_find = select_2030_hgeocode_geo4_3_1_geo2.loc[~select_2030_hgeocode_geo4_3_1_geo2['h_geocode'].isin(select_2030_hgeocode_geo4_3_1_geo22w2w2['h_geocode'])]
                                                                                     
select_2030_hgeocode_geo4_3_1_geo22w2w2_find

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist,centr_x_co
5923,120150203021098,"POLYGON ((-82.14857 26.97642, -82.14765 26.976...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.210302e+14,None,NaN,NaN
5924,120150203011144,"POLYGON ((-82.15527 27.02277, -82.15432 27.022...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.201105e+14,None,NaN,NaN
5926,120710401271004,"POLYGON ((-81.71670 26.64980, -81.71626 26.649...",1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.203101e+14,None,NaN,NaN
5927,120710403023032,"POLYGON ((-81.68050 26.57491, -81.67979 26.574...",2.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,1.201106e+14,None,NaN,NaN
5931,120710402093114,"POLYGON ((-81.59055 26.65150, -81.58911 26.651...",3.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.205701e+14,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,120710403122096,"POLYGON ((-81.62359 26.54015, -81.62357 26.540...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.205701e+14,None,NaN,NaN
6203,120150304022029,"POLYGON ((-82.28716 26.82583, -82.28708 26.825...",5.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN,NaN
6204,120879725002054,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.208600e+14,None,NaN,NaN
6206,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",5.0,0.0,2.0,3.0,5.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,NaN
6207,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.209502e+14,None,NaN,NaN

In [124]:
#getting centr_x_co using their geometery

select_2030_hgeocode_geo4_3_1_geo22w2w2_find= find_coordinates(select_2030_hgeocode_geo4_3_1_geo22w2w2_find)

No
No

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/var/folders/pc/11vhsnt944j5yjbbz3_d41k00000gq/T/ipykernel_17931/3361184365.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Emp_cells_sum_no_dups_final_geo2.rename(columns = {'geometry_x':'geometry'}, inplace = True)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

In [125]:
select_2030_hgeocode_geo4_3_1_geo22w2w2_find

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist,centr_x_co
5923,120150203021098,"POLYGON ((-82.14857 26.97642, -82.14765 26.976...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.210302e+14,None,NaN,"(26.975178051396938, -82.1481059337103)"
5924,120150203011144,"POLYGON ((-82.15527 27.02277, -82.15432 27.022...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.201105e+14,None,NaN,"(27.02153284242703, -82.15480086799396)"
5926,120710401271004,"POLYGON ((-81.71670 26.64980, -81.71626 26.649...",1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.203101e+14,None,NaN,"(26.648702806784605, -81.71608598347991)"
5927,120710403023032,"POLYGON ((-81.68050 26.57491, -81.67979 26.574...",2.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,1.201106e+14,None,NaN,"(26.574475834030732, -81.67993074183829)"
5931,120710402093114,"POLYGON ((-81.59055 26.65150, -81.58911 26.651...",3.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.205701e+14,None,NaN,"(26.649717932746178, -81.58980960043311)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,120710403122096,"POLYGON ((-81.62359 26.54015, -81.62357 26.540...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.205701e+14,None,NaN,"(26.539100061105547, -81.6231019415148)"
6203,120150304022029,"POLYGON ((-82.28716 26.82583, -82.28708 26.825...",5.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN,"(26.825418608381277, -82.28636504224013)"
6204,120879725002054,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.208600e+14,None,NaN,"(24.54895967349272, -81.80399944673492)"
6206,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",5.0,0.0,2.0,3.0,5.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,"(26.86072744671804, -82.0168655661004)"
6207,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.209502e+14,None,NaN,"(27.004866401536365, -82.20261830319743)"

In [126]:
#add back to the zones that need to find cells for them (using nearest availble zones)

select_2030_hgeocode_geo4_3_1_geo2=pd.concat([select_2030_hgeocode_geo4_3_1_geo22w2w2,select_2030_hgeocode_geo4_3_1_geo22w2w2_find], axis=0)
select_2030_hgeocode_geo4_3_1_geo2

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist,centr_x_co
0,120879718001022,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",4.0,1.0,2.0,1.0,3.0,1.0,0.0,0.0,...,2.0,0.0,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",0.631994,"(24.567331297140306, -81.73018543710354)"
89,120879717003014,"POLYGON ((-81.67570 24.60202, -81.67570 24.602...",8.0,2.0,4.0,2.0,7.0,1.0,0.0,0.0,...,2.0,0.0,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.66069 24.60108, -81.66053 24.601...",1.129322,"(24.599937349116697, -81.66874555206641)"
192,120710201031017,"POLYGON ((-81.90898 26.72997, -81.90881 26.729...",2.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.207102e+14,"POLYGON ((-81.90026 26.73959, -81.90024 26.739...",0.95799,"(26.727752498586256, -81.89952848815554)"
260,120879715011003,"POLYGON ((-81.50261 24.66138, -81.50261 24.661...",2.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.48056 24.66379, -81.48054 24.664...",0.735556,"(24.66276660460335, -81.48720077363569)"
346,120710103052003,"POLYGON ((-81.91549 26.64060, -81.91547 26.644...",19.0,4.0,8.0,7.0,16.0,3.0,0.0,0.0,...,4.0,1.0,2.0,1.0,0.0,0.0,1.207101e+14,"POLYGON ((-81.91040 26.64691, -81.90886 26.646...",0.441576,"(26.643469872107385, -81.91235912964126)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,120710403122096,"POLYGON ((-81.62359 26.54015, -81.62357 26.540...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.205701e+14,None,NaN,"(26.539100061105547, -81.6231019415148)"
6203,120150304022029,"POLYGON ((-82.28716 26.82583, -82.28708 26.825...",5.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN,"(26.825418608381277, -82.28636504224013)"
6204,120879725002054,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.208600e+14,None,NaN,"(24.54895967349272, -81.80399944673492)"
6206,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",5.0,0.0,2.0,3.0,5.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,"(26.86072744671804, -82.0168655661004)"
6207,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.209502e+14,None,NaN,"(27.004866401536365, -82.20261830319743)"

In [127]:
def find_cells(Emp_cells_sum_no_dups_final_geo2, select_2030_hgeocode_geo4_3_1_geo2):
    from geopy.distance import geodesic as GD  

    Emp_cells_sum_no_dups_final_geo2['cell_remain'] =Emp_cells_sum_no_dups_final_geo2['cell']

    select_2030_hgeocode_geo4_3_1_geo2['h_geocode_x'] = ''
    select_2030_hgeocode_geo4_3_1_geo2['dist_x'] = ''

    for n1 in range(0,len(select_2030_hgeocode_geo4_3_1_geo2)):
        temprory_hgeocode_final = pd.DataFrame(columns = ['h_geocode', 'dist','cell'])
        temprory = []
        temprory_hgeocode = []
        temprory_cell = []
        temprory3 = []
        temprory4 = []
        print('n1=',n1)
        for l in range(0,len(Emp_cells_sum_no_dups_final_geo2)):
#             print('l=',l)
#             print('select_2030_hgeocode_geo4_3_1_geo2[C000]=',select_2030_hgeocode_geo4_3_1_geo2.iloc[n,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")])
#             print('Emp_cells_sum_no_dups_final_geo2[cell_remain]=',Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")])
            if  (select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")] < Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")]) and (Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")]>0) :
                temprory2= GD(Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("centr_co")],
                                 select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("centr_x_co")]).km
                temprory2_h = Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("h_geocode")]
    #             print('temprory2_h=',Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("h_geocode")])

                temprory2_c = Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")]

                temprory.append(temprory2)
                temprory_hgeocode.append(temprory2_h)
                temprory_cell.append(temprory2_c)
                continue   

        if len(temprory_hgeocode) == 0:
            break
                
#         print('temprory_hgeocode=',temprory_hgeocode)
#         print('temprory_hgeocode=',temprory_hgeocode)
        temprory_hgeocode_final['h_geocode'] = temprory_hgeocode
        temprory_hgeocode_final['dist'] = temprory
        temprory_hgeocode_final['cell'] = temprory_cell
#         print('temprory_hgeocode_final=',temprory_hgeocode_final)
#         print('temprory_hgeocode_final_select=',temprory_hgeocode_final[temprory_hgeocode_final['h_geocode'] == 10030105001012 ])
#         print('temprory_hgeocode_final_select2=',temprory_hgeocode_final[temprory_hgeocode_final['h_geocode'] == 10030101001014 ])
        temprory3 = temprory_hgeocode_final[temprory_hgeocode_final.dist == temprory_hgeocode_final.dist.min()]
    #     print('temprory3=',temprory3)
        temprory4 = temprory3.drop_duplicates(subset=['h_geocode'])
        print('temprory4=',temprory4)  
        select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("h_geocode_x")] = temprory4.h_geocode.to_numpy()[0]
        select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("dist_x")] = temprory4.dist.to_numpy()[0]

        for l in range(0,len(Emp_cells_sum_no_dups_final_geo2)):
            for s in range(0,len(temprory4)):
                if Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("h_geocode")] == temprory4.iloc[s,temprory4.columns.get_loc("h_geocode")]: 
                    print('RHS=',temprory4.iloc[s,temprory4.columns.get_loc("h_geocode")])
                    print('C000=',select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")])
                    Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")] =  Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")] -  select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")]
                    print('cell_remain=',Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")])
                    break
                else:
                    continue
    #     Emp_cells_sum_no_dups_final_geo2.loc[Emp_cells_sum_no_dups_final_geo2['h_geocode'] == temprory3['h_geocode'],'cell_remain'] = Emp_cells_sum_no_dups_final_geo2.loc[Emp_cells_sum_no_dups_final_geo2['h_geocode'] == temprory3['h_geocode'],'cell_remain'] - select_2030_hgeocode_geo4_3_1_geo2.iloc[n,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")]

    return

In [128]:
find_cells(Emp_cells_sum_no_dups_final_geo2,select_2030_hgeocode_geo4_3_1_geo2)

n1= 0
temprory4=             h_geocode        dist  cell
1432  120210110032007  148.643301    12
RHS= 120210110032007
C000= 4.0
cell_remain= 8
n1= 1
temprory4=            h_geocode        dist  cell
923  120210110032009  145.201288    24
RHS= 120210110032009
C000= 8.0
cell_remain= 16
n1= 2
temprory4=             h_geocode     dist  cell
4453  120710201021019  0.56111    16
RHS= 120710201021019
C000= 2.0
cell_remain= 14
n1= 3
temprory4=             h_geocode      dist  cell
8231  120879715021034  2.953606     3
RHS= 120879715021034
C000= 2.0
cell_remain= 1
n1= 4
temprory4=            h_geocode      dist  cell
707  120710103082013  1.612062    20
RHS= 120710103082013
C000= 19.0
cell_remain= 1
n1= 5
temprory4=             h_geocode      dist  cell
9763  120879728001011  1.853529     2
RHS= 120879728001011
C000= 1.0
cell_remain= 1
n1= 6
temprory4=             h_geocode      dist  cell
4085  120710103064029  0.298118    14
RHS= 120710103064029
C000= 1.0
cell_remain= 13
n1= 7
temprory4=             h_geocode      dist  cell
7770  120810004101006  0.158768     8
RHS= 120810004101006
C000= 1.0
cell_remain= 7
n1= 8
temprory4=             h_geocode      dist  cell
8256  121150002003017  0.204611     9
RHS= 121150002003017
C000= 2.0
cell_remain= 7
n1= 9
temprory4=             h_geocode      dist  cell
9750  120879717002005  7.444208     3
RHS= 120879717002005
C000= 1.0
cell_remain= 2
n1= 10
temprory4=             h_geocode       dist  cell
7187  120879704004019  53.992637     4
RHS= 120879704004019
C000= 3.0
cell_remain= 1
n1= 11
temprory4=             h_geocode        dist  cell
1432  120210110032007  149.804578     8
RHS= 120210110032007
C000= 4.0
cell_remain= 4
n1= 12
temprory4=             h_geocode     dist  cell
1766  120710403031031  0.74965    27
RHS= 120710403031031
C000= 11.0
cell_remain= 16
n1= 13
temprory4=             h_geocode       dist  cell
5661  120879727003090  25.011695     6
RHS= 120879727003090
C000= 5.0
cell_remain= 1
n1= 14
temprory4=             h_geocode      dist  cell
2261  120710015012004  0.476721    17
RHS= 120710015012004
C000= 2.0
cell_remain= 15
n1= 15
temprory4=             h_geocode      dist  cell
9162  120810019161000  1.499588     2
RHS= 120810019161000
C000= 1.0
cell_remain= 1
n1= 16
temprory4=             h_geocode      dist  cell
7635  120810003121000  0.379688    62
RHS= 120810003121000
C000= 1.0
cell_remain= 61
n1= 17
temprory4=             h_geocode       dist  cell
8234  120879728004026  14.689702     3
RHS= 120879728004026
C000= 2.0
cell_remain= 1
n1= 18
temprory4=            h_geocode      dist  cell
775  120710102064005  1.324427    18
RHS= 120710102064005
C000= 17.0
cell_remain= 1
n1= 19
temprory4=             h_geocode      dist  cell
1589  120710205011020  1.807271    16
RHS= 120710205011020
C000= 11.0
cell_remain= 5
n1= 20
temprory4=             h_geocode       dist  cell
8227  120879712001011  69.250698     3
RHS= 120879712001011
C000= 2.0
cell_remain= 1
n1= 21
temprory4=             h_geocode      dist  cell
6894  120710502131030  0.329998     2
RHS= 120710502131030
C000= 1.0
cell_remain= 1
n1= 22
temprory4=             h_geocode      dist  cell
1720  120210104213009  0.262344     2
RHS= 120210104213009
C000= 1.0
cell_remain= 1
n1= 23
temprory4=             h_geocode        dist  cell
1032  120210111072004  125.872034    10
RHS= 120210111072004
C000= 7.0
cell_remain= 3
n1= 24
temprory4=             h_geocode      dist  cell
1833  120710019031002  0.538748    12
RHS= 120710019031002
C000= 4.0
cell_remain= 8
n1= 25
temprory4=             h_geocode       dist  cell
8224  120879710021020  87.674261     3
RHS= 120879710021020
C000= 2.0
cell_remain= 1
n1= 26
temprory4=            h_geocode        dist  cell
439  120210111111001  155.716937    35
RHS= 120210111111001
C000= 22.0
cell_remain= 13
n1= 27
temprory4=            h_geocode        dist  cell
803  120210110032009  148.806707    16
RHS= 120210110032009
C000= 10.0
cell_remain= 6
n1= 28
temprory4=             h_geocode      dist  cell
2638  120710003061027  0.100531     2
RHS= 120710003061027
C000= 1.0
cell_remain= 1
n1= 29
temprory4=             h_geocode     dist  cell
5370  120810001062010  0.16038     5
RHS= 120810001062010
C000= 3.0
cell_remain= 2
n1= 30
temprory4=             h_geocode      dist  cell
5556  120710401212043  0.660424     3
RHS= 120710401212043
C000= 1.0
cell_remain= 2
n1= 31
temprory4=             h_geocode        dist  cell
7184  120879727001012  114.001408     4
RHS= 120879727001012
C000= 3.0
cell_remain= 1
n1= 32
temprory4=             h_geocode      dist  cell
8219  120879705001036  2.445915     3
RHS= 120879705001036
C000= 2.0
cell_remain= 1
n1= 33
temprory4=             h_geocode      dist  cell
1429  120210101112000  0.412146    35
RHS= 120210101112000
C000= 1.0
cell_remain= 34
n1= 34
temprory4=            h_geocode       dist  cell
988  120210109062017  145.87643    12
RHS= 120210109062017
C000= 7.0
cell_remain= 5
n1= 35
temprory4=            h_geocode        dist  cell
549  120210109062002  152.191988    20
RHS= 120210109062002
C000= 16.0
cell_remain= 4
n1= 36
temprory4=            h_geocode      dist  cell
684  120810019091001  0.723202    91
RHS= 120810019091001
C000= 41.0
cell_remain= 50
n1= 37
temprory4=             h_geocode      dist  cell
9882  121150005023001  0.202619     3
RHS= 121150005023001
C000= 1.0
cell_remain= 2
n1= 38
temprory4=             h_geocode        dist  cell
1103  120210109062040  145.349331    12
RHS= 120210109062040
C000= 6.0
cell_remain= 6
n1= 39
temprory4=            h_geocode        dist  cell
921  120210110032014  150.628953    51
RHS= 120210110032014
C000= 8.0
cell_remain= 43
n1= 40
temprory4=             h_geocode       dist  cell
8221  120879710022024  84.958941     3
RHS= 120879710022024
C000= 2.0
cell_remain= 1
n1= 41
temprory4=             h_geocode      dist  cell
2732  120710104142011  0.287426     6
RHS= 120710104142011
C000= 4.0
cell_remain= 2
n1= 42
temprory4=             h_geocode       dist  cell
9741  120879717003022  12.286766     2
RHS= 120879717003022
C000= 1.0
cell_remain= 1
n1= 43
temprory4=             h_geocode        dist  cell
1431  120210110032009  149.600024     6
RHS= 120210110032009
C000= 4.0
cell_remain= 2
n1= 44
temprory4=             h_geocode     dist  cell
4625  120810019151017  0.55262    11
RHS= 120810019151017
C000= 6.0
cell_remain= 5
n1= 45
temprory4=            h_geocode      dist  cell
779  120210106062010  0.286477    22
RHS= 120210106062010
C000= 8.0
cell_remain= 14
n1= 46
temprory4=             h_geocode      dist  cell
9418  121150027391014  0.130325     6
RHS= 121150027391014
C000= 3.0
cell_remain= 3
n1= 47
temprory4=             h_geocode      dist  cell
1455  120710010012045  0.447825     6
RHS= 120710010012045
C000= 5.0
cell_remain= 1
n1= 48
temprory4=            h_geocode        dist  cell
638  120210109061010  146.843075   104
RHS= 120210109061010
C000= 13.0
cell_remain= 91
n1= 49
temprory4=             h_geocode       dist  cell
9739  120879717002005  15.311627     2
RHS= 120879717002005
C000= 1.0
cell_remain= 1
n1= 50
temprory4=             h_geocode       dist  cell
9738  120879715012018  35.026131     2
RHS= 120879715012018
C000= 1.0
cell_remain= 1
n1= 51
temprory4=            h_geocode        dist  cell
607  120210109062006  155.721388    60
RHS= 120210109062006
C000= 14.0
cell_remain= 46
n1= 52
temprory4=             h_geocode        dist  cell
1266  120210110032014  149.833701    43
RHS= 120210110032014
C000= 5.0
cell_remain= 38
n1= 53
temprory4=            h_geocode        dist  cell
359  120210109062006  152.013482    46
RHS= 120210109062006
C000= 25.0
cell_remain= 21
n1= 54
temprory4=             h_geocode       dist  cell
8218  120879710022026  90.613414     3
RHS= 120879710022026
C000= 2.0
cell_remain= 1
n1= 55
temprory4=             h_geocode        dist  cell
1266  120210110032014  149.616482    38
RHS= 120210110032014
C000= 5.0
cell_remain= 33
n1= 56
temprory4=             h_geocode       dist  cell
8217  120879709003023  89.541699     3
RHS= 120879709003023
C000= 2.0
cell_remain= 1
n1= 57
temprory4=             h_geocode       dist  cell
9735  120879711002070  76.387059     2
RHS= 120879711002070
C000= 1.0
cell_remain= 1
n1= 58

temprory4=             h_geocode       dist  cell
9731  120879710021004  86.894668     2
RHS= 120879710021004
C000= 1.0
cell_remain= 1
n1= 59
temprory4=             h_geocode        dist  cell
1432  120210110032014  148.598561    33
RHS= 120210110032014
C000= 4.0
cell_remain= 29
n1= 60
temprory4=             h_geocode       dist  cell
9732  120879710022015  90.121502     2
RHS= 120879710022015
C000= 1.0
cell_remain= 1
n1= 61
temprory4=             h_geocode        dist  cell
1652  120210110032007  150.529055     4
RHS= 120210110032007
C000= 3.0
cell_remain= 1
n1= 62
temprory4=             h_geocode       dist  cell
9731  120879710022023  87.668874     2
RHS= 120879710022023
C000= 1.0
cell_remain= 1
n1= 63
temprory4=            h_geocode        dist  cell
921  120210110032014  150.630561    29
RHS= 120210110032014
C000= 8.0
cell_remain= 21
n1= 64
temprory4=            h_geocode        dist  cell
518  120210109062006  152.310876    21
RHS= 120210109062006
C000= 17.0
cell_remain= 4
n1= 65
temprory4=             h_geocode        dist  cell
8215  120879708003026  133.964038     3
RHS= 120879708003026
C000= 2.0
cell_remain= 1
n1= 66
temprory4=            h_geocode        dist  cell
800  120210110032014  150.542043    21
RHS= 120210110032014
C000= 10.0
cell_remain= 11
n1= 67
temprory4=            h_geocode        dist  cell
190  120210109061010  156.553314    91
RHS= 120210109061010
C000= 49.0
cell_remain= 42
n1= 68
temprory4=             h_geocode        dist  cell
1132  120210110032014  150.250255    11
RHS= 120210110032014
C000= 6.0
cell_remain= 5
n1= 69
temprory4=             h_geocode      dist  cell
8215  120879727001030  4.502085     3
RHS= 120879727001030
C000= 2.0
cell_remain= 1
n1= 70
temprory4=             h_geocode       dist  cell
9729  120879710022010  16.070876     2
RHS= 120879710022010
C000= 1.0
cell_remain= 1
n1= 71
temprory4=             h_geocode        dist  cell
1264  120210110032013  151.201503    13
RHS= 120210110032013
C000= 5.0
cell_remain= 8
n1= 72
temprory4=             h_geocode        dist  cell
9726  120879709001052  112.801307     2
RHS= 120879709001052
C000= 1.0
cell_remain= 1
n1= 73
temprory4=             h_geocode        dist  cell
1653  120210110032014  150.476694     5
RHS= 120210110032014
C000= 3.0
cell_remain= 2
n1= 74
temprory4=            h_geocode        dist  cell
431  120210109061010  156.569073    42
RHS= 120210109061010
C000= 20.0
cell_remain= 22
n1= 75
temprory4=            h_geocode        dist  cell
724  120210109062039  152.027113    13
RHS= 120210109062039
C000= 11.0
cell_remain= 2
n1= 76
temprory4=             h_geocode        dist  cell
1953  120210110032011  150.688376     3
RHS= 120210110032011
C000= 2.0
cell_remain= 1
n1= 77
temprory4=             h_geocode        dist  cell
9726  120879709003026  109.296551     2
RHS= 120879709003026
C000= 1.0
cell_remain= 1
n1= 78
temprory4=             h_geocode        dist  cell
1130  120210110032013  150.113018     8
RHS= 120210110032013
C000= 6.0
cell_remain= 2
n1= 79
temprory4=             h_geocode        dist  cell
1897  120210109061009  150.103748    22
RHS= 120210109061009
C000= 2.0
cell_remain= 20
n1= 80
temprory4=             h_geocode        dist  cell
1222  120210109061009  150.108853    20
RHS= 120210109061009
C000= 5.0
cell_remain= 15
n1= 81
temprory4=             h_geocode       dist  cell
1092  120210109061009  151.04392    15
RHS= 120210109061009
C000= 6.0
cell_remain= 9
n1= 82
temprory4=            h_geocode        dist  cell
886  120210109061009  150.258646     9
RHS= 120210109061009
C000= 8.0
cell_remain= 1
n1= 83
temprory4=             h_geocode        dist  cell
1393  120210109062017  145.266196     5
RHS= 120210109062017
C000= 4.0
cell_remain= 1
n1= 84
temprory4=             h_geocode     dist  cell
8209  120879727001034  6.51642     3
RHS= 120879727001034
C000= 2.0
cell_remain= 1
n1= 85
temprory4=             h_geocode        dist  cell
1095  120210109061013  150.968287    11
RHS= 120210109061013
C000= 6.0
cell_remain= 5
n1= 86
temprory4=            h_geocode        dist  cell
224  120210110032002  150.443456   171
RHS= 120210110032002
C000= 43.0
cell_remain= 128
n1= 87
temprory4=             h_geocode        dist  cell
9723  120879709002026  127.246673     2
RHS= 120879709002026
C000= 1.0
cell_remain= 1
n1= 88
temprory4=             h_geocode        dist  cell
1900  120210109061013  151.217246     5
RHS= 120210109061013
C000= 2.0
cell_remain= 3
n1= 89
temprory4=             h_geocode        dist  cell
1263  120210110033016  151.259892    10
RHS= 120210110033016
C000= 5.0
cell_remain= 5
n1= 90
temprory4=             h_geocode        dist  cell
1900  120210109061013  150.819599     3
RHS= 120210109061013
C000= 2.0
cell_remain= 1
n1= 91
temprory4=            h_geocode       dist  cell
739  120210110032002  150.71079   128
RHS= 120210110032002
C000= 11.0
cell_remain= 117
n1= 92
temprory4=             h_geocode        dist  cell
1952  120210110033016  150.554732     5
RHS= 120210110033016
C000= 2.0
cell_remain= 3
n1= 93
temprory4=             h_geocode        dist  cell
1425  120210110032002  150.930838   117
RHS= 120210110032002
C000= 4.0
cell_remain= 113
n1= 94
temprory4=             h_geocode        dist  cell
1647  120210110032002  151.208011   113
RHS= 120210110032002
C000= 3.0
cell_remain= 110
n1= 95
temprory4=            h_geocode      dist  cell
426  120150204011032  1.629154    17
RHS= 120150204011032
C000= 1.0
cell_remain= 16
n1= 96
temprory4=             h_geocode      dist  cell
2980  120710201021004  0.619159    16
RHS= 120710201021004
C000= 5.0
cell_remain= 11
n1= 97
temprory4=             h_geocode      dist  cell
2314  120710101081049  0.597777     5
RHS= 120710101081049
C000= 3.0
cell_remain= 2
n1= 98
temprory4=             h_geocode     dist  cell
2438  120710502061009  0.25046     9
RHS= 120710502061009
C000= 8.0
cell_remain= 1
n1= 99
temprory4=             h_geocode      dist  cell
6722  120810008081011  0.034715     9
RHS= 120810008081011
C000= 2.0
cell_remain= 7
n1= 100
temprory4=             h_geocode        dist  cell
1425  120210110032002  149.109279   110
RHS= 120210110032002
C000= 4.0
cell_remain= 106
n1= 101
temprory4=             h_geocode      dist  cell
6294  120810014051009  0.225998     6
RHS= 120810014051009
C000= 3.0
cell_remain= 3
n1= 102
temprory4=            h_geocode      dist  cell
282  120710105014010  4.706018    79
RHS= 120710105014010
C000= 53.0
cell_remain= 26
n1= 103
temprory4=            h_geocode      dist  cell
229  120150205013009  0.083889     5
RHS= 120150205013009
C000= 4.0
cell_remain= 1
n1= 104
temprory4=             h_geocode      dist  cell
3222  120810002031002  0.400044    11
RHS= 120810002031002
C000= 7.0
cell_remain= 4
n1= 105
temprory4=            h_geocode      dist  cell
922  120710502122000  0.687032    27
RHS= 120710502122000
C000= 21.0
cell_remain= 6
n1= 106
temprory4=            h_geocode        dist  cell
319  120210109061022  142.451703    61
RHS= 120210109061022
C000= 29.0
cell_remain= 32
n1= 107
temprory4=             h_geocode      dist  cell
4293  120710402055025  0.257227     7
RHS= 120710402055025
C000= 3.0
cell_remain= 4
n1= 108
temprory4=            h_geocode      dist  cell
257  120150302022009  0.203292     6
RHS= 120150302022009
C000= 5.0
cell_remain= 1
n1= 109
temprory4=              h_geocode      dist  cell
11057  121150020143012  0.147218     5
RHS= 121150020143012
C000= 1.0
cell_remain= 4
n1= 110
temprory4=             h_geocode      dist  cell
1500  120710102032080  0.423714     8
RHS= 120710102032080
C000= 7.0
cell_remain= 1
n1= 111
temprory4=            h_geocode      dist  cell
275  120710104222000  1.035167    57
RHS= 120710104222000
C000= 54.0
cell_remain= 3
n1= 112
temprory4=             h_geocode      dist  cell
7866  120810005041004  0.076106    25
RHS= 120810005041004
C000= 1.0
cell_remain= 24
n1= 113
temprory4=             h_geocode     dist  cell
8477  121150027442096  1.15496     5
RHS= 121150027442096
C000= 4.0
cell_remain= 1
n1= 114
temprory4=             h_geocode      dist  cell
1440  120710101081078  0.222271     9
RHS= 120710101081078
C000= 7.0
cell_remain= 2
n1= 115
temprory4=            h_geocode      dist  cell
326  120150202061041  0.365814     5
RHS= 120150202061041
C000= 1.0
cell_remain= 4

n1= 116
temprory4=            h_geocode      dist  cell
115  120150202052034  0.566566    13
RHS= 120150202052034
C000= 5.0
cell_remain= 8
n1= 117
temprory4=             h_geocode      dist  cell
5209  120810019164015  0.834059     7
RHS= 120810019164015
C000= 5.0
cell_remain= 2
n1= 118
temprory4=             h_geocode      dist  cell
5388  120810003071011  0.334804     6
RHS= 120810003071011
C000= 3.0
cell_remain= 3
n1= 119
temprory4=             h_geocode      dist  cell
2248  121150027362042  7.359959    21
RHS= 121150027362042
C000= 19.0
cell_remain= 2
n1= 120
temprory4=             h_geocode      dist  cell
3692  120710104142012  0.217634    16
RHS= 120710104142012
C000= 2.0
cell_remain= 14
n1= 121
temprory4=             h_geocode      dist  cell
4638  120710401091003  0.650327     4
RHS= 120710401091003
C000= 2.0
cell_remain= 2
n1= 122
temprory4=             h_geocode      dist  cell
5963  121150027382013  0.383167    10
RHS= 121150027382013
C000= 7.0
cell_remain= 3
n1= 123
temprory4=             h_geocode      dist  cell
2544  121150027412011  0.388531    18
RHS= 121150027412011
C000= 17.0
cell_remain= 1
n1= 124
temprory4=             h_geocode      dist  cell
2705  121150027361017  1.157733    19
RHS= 121150027361017
C000= 16.0
cell_remain= 3
n1= 125
temprory4=             h_geocode      dist  cell
3254  120810003112004  0.244881   110
RHS= 120810003112004
C000= 7.0
cell_remain= 103
n1= 126
temprory4=             h_geocode      dist  cell
3753  120710402071029  0.089853    14
RHS= 120710402071029
C000= 4.0
cell_remain= 10
n1= 127
temprory4=            h_geocode      dist  cell
782  120710401201012  3.471446    70
RHS= 120710401201012
C000= 22.0
cell_remain= 48
n1= 128
temprory4=             h_geocode      dist  cell
4105  120710401242039  0.094124     8
RHS= 120710401242039
C000= 3.0
cell_remain= 5
n1= 129
temprory4=             h_geocode      dist  cell
4115  120710401243016  0.189196     4
RHS= 120710401243016
C000= 3.0
cell_remain= 1
n1= 130
temprory4=            h_geocode      dist  cell
659  120710104043034  0.396984    25
RHS= 120710104043034
C000= 21.0
cell_remain= 4
n1= 131
temprory4=             h_geocode      dist  cell
2473  120710401241006  0.221875    10
RHS= 120710401241006
C000= 7.0
cell_remain= 3
n1= 132
temprory4=             h_geocode      dist  cell
7074  120710503201006  0.415429     3
RHS= 120710503201006
C000= 1.0
cell_remain= 2
n1= 133
temprory4=           h_geocode      dist  cell
19  120150210032021  9.288683    70
RHS= 120150210032021
C000= 32.0
cell_remain= 38
n1= 134
temprory4=             h_geocode      dist  cell
9670  121150027462142  0.331943     4
RHS= 121150027462142
C000= 3.0
cell_remain= 1
n1= 135
temprory4=             h_geocode     dist  cell
1896  120710402081171  0.97321    25
RHS= 120710402081171
C000= 10.0
cell_remain= 15
n1= 136
temprory4=            h_geocode      dist  cell
273  120210101081019  0.423528    13
RHS= 120210101081019
C000= 8.0
cell_remain= 5
n1= 137
temprory4=             h_geocode      dist  cell
3397  120810005033022  0.202908    10
RHS= 120810005033022
C000= 7.0
cell_remain= 3
n1= 138
temprory4=             h_geocode      dist  cell
2984  120710104043050  0.273695     6
RHS= 120710104043050
C000= 3.0
cell_remain= 3
n1= 139
temprory4=             h_geocode      dist  cell
2895  120710401372004  1.381961    15
RHS= 120710401372004
C000= 6.0
cell_remain= 9
n1= 140
temprory4=             h_geocode      dist  cell
2654  120710005032018  0.214276     4
RHS= 120710005032018
C000= 1.0
cell_remain= 3
n1= 141
temprory4=             h_geocode      dist  cell
3616  120810019103004  1.341406     9
RHS= 120810019103004
C000= 8.0
cell_remain= 1
n1= 142
temprory4=            h_geocode     dist  cell
668  120710104192012  3.30901    27
RHS= 120710104192012
C000= 22.0
cell_remain= 5
n1= 143
temprory4=            h_geocode        dist  cell
577  120210109061010  155.121785    22
RHS= 120210109061010
C000= 15.0
cell_remain= 7
n1= 144
temprory4=             h_geocode      dist  cell
8225  121150003001026  0.189628     3
RHS= 121150003001026
C000= 2.0
cell_remain= 1
n1= 145
temprory4=             h_geocode      dist  cell
5213  120710403016028  0.718795     3
RHS= 120710403016028
C000= 2.0
cell_remain= 1
n1= 146
temprory4=             h_geocode      dist  cell
8731  121150014032000  0.454788    40
RHS= 121150014032000
C000= 2.0
cell_remain= 38
n1= 147
temprory4=             h_geocode      dist  cell
1099  120710403113003  0.611461    26
RHS= 120710403113003
C000= 17.0
cell_remain= 9
n1= 148
temprory4=             h_geocode      dist  cell
5472  120710401091007  0.570359     4
RHS= 120710401091007
C000= 1.0
cell_remain= 3
n1= 149
temprory4=             h_geocode        dist  cell
1096  120210112083004  143.748964    10
RHS= 120210112083004
C000= 7.0
cell_remain= 3
n1= 150
temprory4=            h_geocode      dist  cell
566  120210106022023  0.281161    29
RHS= 120210106022023
C000= 12.0
cell_remain= 17
n1= 151
temprory4=             h_geocode     dist  cell
6273  120710403031014  0.09445     2
RHS= 120710403031014
C000= 1.0
cell_remain= 1
n1= 152
temprory4=             h_geocode      dist  cell
1349  120210112081057  0.600316    12
RHS= 120210112081057
C000= 5.0
cell_remain= 7
n1= 153
temprory4=             h_geocode        dist  cell
1126  120210110032002  150.567571   106
RHS= 120210110032002
C000= 6.0
cell_remain= 100
n1= 154
temprory4=              h_geocode      dist  cell
12923  121150027461007  0.185768     2
RHS= 121150027461007
C000= 1.0
cell_remain= 1
n1= 155
temprory4=              h_geocode      dist  cell
10613  121150027381079  0.096353    10
RHS= 121150027381079
C000= 2.0
cell_remain= 8
n1= 156
temprory4=             h_geocode      dist  cell
4227  120710401361006  0.787746    14
RHS= 120710401361006
C000= 3.0
cell_remain= 11
n1= 157
temprory4=             h_geocode      dist  cell
1833  120210113041011  5.908339     5
RHS= 120210113041011
C000= 3.0
cell_remain= 2
n1= 158
temprory4=             h_geocode      dist  cell
9709  120879706001038  1.120792     2
RHS= 120879706001038
C000= 1.0
cell_remain= 1
n1= 159
temprory4=             h_geocode      dist  cell
4908  120710401384049  5.178043     3
RHS= 120710401384049
C000= 2.0
cell_remain= 1
n1= 160
temprory4=            h_geocode     dist  cell
746  120150301012013  0.11644     3
RHS= 120150301012013
C000= 1.0
cell_remain= 2
n1= 161
temprory4=            h_geocode      dist  cell
145  120150203033031  0.400063    10
RHS= 120150203033031
C000= 5.0
cell_remain= 5
n1= 162
temprory4=             h_geocode        dist  cell
1227  120210109062040  142.383644     6
RHS= 120210109062040
C000= 5.0
cell_remain= 1
n1= 163
temprory4=             h_geocode      dist  cell
8620  120810014021007  0.697132     2
RHS= 120810014021007
C000= 1.0
cell_remain= 1
n1= 164
temprory4=            h_geocode      dist  cell
498  120710401271003  1.912834    41
RHS= 120710401271003
C000= 34.0
cell_remain= 7
n1= 165
temprory4=            h_geocode      dist  cell
868  120710103073002  3.228651    25
RHS= 120710103073002
C000= 15.0
cell_remain= 10
n1= 166
temprory4=            h_geocode      dist  cell
169  120150205012060  0.091183     7
RHS= 120150205012060
C000= 5.0
cell_remain= 2
n1= 167
temprory4=             h_geocode        dist  cell
7151  120879727003086  100.760266     4
RHS= 120879727003086
C000= 3.0
cell_remain= 1
n1= 168
temprory4=             h_geocode       dist  cell
8191  120879727003093  28.442393     3
RHS= 120879727003093
C000= 2.0
cell_remain= 1
n1= 169
temprory4=             h_geocode      dist  cell
1132  120710101072048  0.857687    12
RHS= 120710101072048
C000= 10.0
cell_remain= 2
n1= 170
temprory4=             h_geocode      dist  cell
7041  121150027101022  0.411598     9
RHS= 121150027101022
C000= 5.0
cell_remain= 4
n1= 171
temprory4=             h_geocode        dist  cell
1260  120210110033021  145.889799    34
RHS= 120210110033021
C000= 5.0
cell_remain= 29
n1= 172
temprory4=             h_geocode       dist  cell
9707  120879708002014  86.360636     2
RHS= 120879708002014
C000= 1.0
cell_remain= 1
n1= 173
temprory4=             h_geocode      dist  cell
6394  120710403082123  0.428477     4
RHS= 120710403082123
C000= 1.0
cell_remain= 3

n1= 174
temprory4=            h_geocode        dist  cell
736  120210110032002  151.176613   100
RHS= 120210110032002
C000= 11.0
cell_remain= 89
n1= 175
temprory4=             h_geocode        dist  cell
1947  120210110033016  151.212791     3
RHS= 120210110033016
C000= 2.0
cell_remain= 1
n1= 176
temprory4=             h_geocode      dist  cell
5195  120710403015014  0.840253    16
RHS= 120710403015014
C000= 2.0
cell_remain= 14
n1= 177
temprory4=             h_geocode      dist  cell
3079  120710101061018  0.188905     2
RHS= 120710101061018
C000= 1.0
cell_remain= 1
n1= 178
temprory4=             h_geocode      dist  cell
1532  120710102063025  0.544434     8
RHS= 120710102063025
C000= 7.0
cell_remain= 1
n1= 179
temprory4=             h_geocode      dist  cell
6526  120710403141022  0.215841     3
RHS= 120710403141022
C000= 1.0
cell_remain= 2
n1= 180
temprory4=             h_geocode      dist  cell
3902  120710403051016  0.081752     7
RHS= 120710403051016
C000= 4.0
cell_remain= 3
n1= 181
temprory4=             h_geocode      dist  cell
5399  120710302025023  0.103479     8
RHS= 120710302025023
C000= 1.0
cell_remain= 7
n1= 182
temprory4=             h_geocode      dist  cell
9699  120879704004020  0.219589     2
RHS= 120879704004020
C000= 1.0
cell_remain= 1
n1= 183
temprory4=             h_geocode     dist  cell
5412  121150027411064  1.40162    10
RHS= 121150027411064
C000= 8.0
cell_remain= 2
n1= 184
temprory4=             h_geocode      dist  cell
1836  120710101111035  0.094362     6
RHS= 120710101111035
C000= 5.0
cell_remain= 1
n1= 185
temprory4=             h_geocode      dist  cell
4589  120710403141005  1.731238     4
RHS= 120710403141005
C000= 3.0
cell_remain= 1
n1= 186
temprory4=             h_geocode      dist  cell
3396  120710403023018  0.268629    30
RHS= 120710403023018
C000= 5.0
cell_remain= 25
n1= 187
temprory4=             h_geocode      dist  cell
3847  120710201024005  0.366281     5
RHS= 120710201024005
C000= 3.0
cell_remain= 2
n1= 188
temprory4=             h_geocode        dist  cell
2023  120210111131170  130.013283     3
RHS= 120210111131170
C000= 2.0
cell_remain= 1
n1= 189
temprory4=             h_geocode      dist  cell
6432  120810004102016  0.344843    39
RHS= 120810004102016
C000= 2.0
cell_remain= 37
n1= 190
temprory4=             h_geocode      dist  cell
2388  120210111072037  9.738515     3
RHS= 120210111072037
C000= 1.0
cell_remain= 2
n1= 191
temprory4=             h_geocode      dist  cell
2933  120710402072028  1.085388    11
RHS= 120710402072028
C000= 6.0
cell_remain= 5
n1= 192
temprory4=             h_geocode      dist  cell
4052  120710103062023  0.413419     2
RHS= 120710103062023
C000= 1.0
cell_remain= 1
n1= 193
temprory4=             h_geocode      dist  cell
7482  121150027422038  0.790519     7
RHS= 121150027422038
C000= 5.0
cell_remain= 2
n1= 194
temprory4=             h_geocode        dist  cell
1255  120210110032002  150.324412    89
RHS= 120210110032002
C000= 5.0
cell_remain= 84
n1= 195
temprory4=              h_geocode      dist  cell
13012  121150027472049  0.184775     4
RHS= 121150027472049
C000= 1.0
cell_remain= 3
n1= 196
temprory4=             h_geocode     dist  cell
6117  121150025081034  0.07688    13
RHS= 121150025081034
C000= 6.0
cell_remain= 7
n1= 197
temprory4=            h_geocode      dist  cell
960  121150027392001  6.648948    47
RHS= 121150027392001
C000= 41.0
cell_remain= 6
n1= 198
temprory4=             h_geocode      dist  cell
1056  120710101072030  0.274283    12
RHS= 120710101072030
C000= 11.0
cell_remain= 1
n1= 199
temprory4=             h_geocode       dist  cell
9699  120879708003049  86.258324     2
RHS= 120879708003049
C000= 1.0
cell_remain= 1
n1= 200
temprory4=             h_geocode      dist  cell
1448  120710402072000  1.460117    22
RHS= 120710402072000
C000= 13.0
cell_remain= 9
n1= 201
temprory4=              h_geocode      dist  cell
12376  121150027381008  0.197848     8
RHS= 121150027381008
C000= 1.0
cell_remain= 7
n1= 202
temprory4=             h_geocode      dist  cell
6238  120810013002014  0.111463     6
RHS= 120810013002014
C000= 3.0
cell_remain= 3
n1= 203
temprory4=             h_geocode      dist  cell
4224  120710401362008  0.959627    32
RHS= 120710401362008
C000= 3.0
cell_remain= 29
n1= 204
temprory4=            h_geocode        dist  cell
906  120210111111001  156.618161    13
RHS= 120210111111001
C000= 9.0
cell_remain= 4
n1= 205
temprory4=             h_geocode       dist  cell
9698  120879708003007  95.035745     2
RHS= 120879708003007
C000= 1.0
cell_remain= 1
n1= 206
temprory4=             h_geocode      dist  cell
5823  120710402051049  0.188877     5
RHS= 120710402051049
C000= 1.0
cell_remain= 4
n1= 207
temprory4=            h_geocode      dist  cell
734  120150301011166  0.167991     3
RHS= 120150301011166
C000= 1.0
cell_remain= 2
n1= 208
temprory4=             h_geocode      dist  cell
6313  121150003001022  0.382544     6
RHS= 121150003001022
C000= 4.0
cell_remain= 2
n1= 209
temprory4=             h_geocode      dist  cell
6039  120710402102025  0.142647     2
RHS= 120710402102025
C000= 1.0
cell_remain= 1
n1= 210
temprory4=             h_geocode      dist  cell
1484  120710403111003  3.228406    16
RHS= 120710403111003
C000= 13.0
cell_remain= 3
n1= 211
temprory4=             h_geocode        dist  cell
1129  120210110033021  147.905724    29
RHS= 120210110033021
C000= 6.0
cell_remain= 23
n1= 212
temprory4=             h_geocode        dist  cell
9696  120879707002020  137.402866     2
RHS= 120879707002020
C000= 1.0
cell_remain= 1
n1= 213
temprory4=             h_geocode      dist  cell
1868  120710101132030  0.150378     8
RHS= 120710101132030
C000= 5.0
cell_remain= 3
n1= 214
temprory4=             h_geocode      dist  cell
2391  120710103033016  0.246146    10
RHS= 120710103033016
C000= 4.0
cell_remain= 6
n1= 215
temprory4=             h_geocode       dist  cell
9695  120879706001004  96.100824     2
RHS= 120879706001004
C000= 1.0
cell_remain= 1
n1= 216
temprory4=            h_geocode        dist  cell
783  120210111141018  155.389663    14
RHS= 120210111141018
C000= 11.0
cell_remain= 3
n1= 217
temprory4=             h_geocode      dist  cell
6379  120710403082045  0.557347     3
RHS= 120710403082045
C000= 1.0
cell_remain= 2
n1= 218
temprory4=             h_geocode        dist  cell
1943  120210110032002  151.459547    84
RHS= 120210110032002
C000= 2.0
cell_remain= 82
n1= 219
temprory4=            h_geocode      dist  cell
873  120150302013064  0.145267     2
RHS= 120150302013064
C000= 1.0
cell_remain= 1
n1= 220
temprory4=             h_geocode     dist  cell
8373  121150027421016  0.59837     7
RHS= 121150027421016
C000= 4.0
cell_remain= 3
n1= 221
temprory4=            h_geocode      dist  cell
307  120710101091030  5.369589    58
RHS= 120710101091030
C000= 46.0
cell_remain= 12
n1= 222
temprory4=             h_geocode      dist  cell
6513  120710403131082  0.215132     4
RHS= 120710403131082
C000= 1.0
cell_remain= 3
n1= 223
temprory4=             h_geocode      dist  cell
3151  120810016032002  1.072639    14
RHS= 120810016032002
C000= 9.0
cell_remain= 5
n1= 224
temprory4=             h_geocode       dist  cell
9693  120879705002007  123.05436     2
RHS= 120879705002007
C000= 1.0
cell_remain= 1
n1= 225
temprory4=             h_geocode      dist  cell
9653  121150027471020  0.267376    13
RHS= 121150027471020
C000= 3.0
cell_remain= 10
n1= 226
temprory4=            h_geocode      dist  cell
427  120150204012012  0.333122     2
RHS= 120150204012012
C000= 1.0
cell_remain= 1
n1= 227
temprory4=             h_geocode      dist  cell
3297  120710402072006  3.305214     6
RHS= 120710402072006
C000= 5.0
cell_remain= 1
n1= 228
temprory4=             h_geocode      dist  cell
3368  121150027332027  2.320467    24
RHS= 121150027332027
C000= 13.0
cell_remain= 11
n1= 229
temprory4=             h_geocode       dist  cell
2783  120810019142041  14.278371    27
RHS= 120810019142041
C000= 11.0
cell_remain= 16
n1= 230
temprory4=             h_geocode       dist  cell
1643  120210110032002  150.25636    82
RHS= 120210110032002
C000= 3.0
cell_remain= 79
n1= 231
temprory4=             h_geocode        dist  cell
1255  120210110032002  151.176259    79
RHS= 120210110032002
C000= 5.0
cell_remain= 74

n1= 232
temprory4=             h_geocode      dist  cell
1064  120710104042013  0.618024    17
RHS= 120710104042013
C000= 12.0
cell_remain= 5
n1= 233
temprory4=            h_geocode        dist  cell
521  120210111111002  156.681974    37
RHS= 120210111111002
C000= 18.0
cell_remain= 19
n1= 234
temprory4=             h_geocode       dist  cell
1603  120210109062002  142.15102     4
RHS= 120210109062002
C000= 3.0
cell_remain= 1
n1= 235
temprory4=            h_geocode        dist  cell
637  120210109061022  155.922481    32
RHS= 120210109061022
C000= 13.0
cell_remain= 19
n1= 236
temprory4=             h_geocode      dist  cell
1922  120710403044006  1.640893    16
RHS= 120710403044006
C000= 10.0
cell_remain= 6
n1= 237
temprory4=             h_geocode        dist  cell
1255  120210110032002  150.318479    74
RHS= 120210110032002
C000= 5.0
cell_remain= 69
n1= 238
temprory4=             h_geocode      dist  cell
3931  120710403131058  1.291227     5
RHS= 120710403131058
C000= 4.0
cell_remain= 1
n1= 239
temprory4=             h_geocode      dist  cell
1927  120710403131001  1.087242    48
RHS= 120710403131001
C000= 10.0
cell_remain= 38
n1= 240
temprory4=             h_geocode        dist  cell
9688  120879704004025  108.455344     2
RHS= 120879704004025
C000= 1.0
cell_remain= 1
n1= 241
temprory4=             h_geocode        dist  cell
1957  120210111072004  144.445748     3
RHS= 120210111072004
C000= 2.0
cell_remain= 1
n1= 242
temprory4=             h_geocode        dist  cell
1255  120210110032002  150.190768    69
RHS= 120210110032002
C000= 5.0
cell_remain= 64
n1= 243
temprory4=             h_geocode      dist  cell
4930  120710402053057  0.196767     4
RHS= 120710402053057
C000= 2.0
cell_remain= 2
n1= 244
temprory4=             h_geocode     dist  cell
2330  120710403031031  0.40169    16
RHS= 120710403031031
C000= 8.0
cell_remain= 8
n1= 245
temprory4=           h_geocode      dist  cell
76  120150302011002  2.613716    12
RHS= 120150302011002
C000= 11.0
cell_remain= 1
n1= 246
temprory4=            h_geocode      dist  cell
890  120710403011009  0.809165    44
RHS= 120710403011009
C000= 20.0
cell_remain= 24
n1= 247
temprory4=             h_geocode      dist  cell
1615  120710007001013  1.568291     5
RHS= 120710007001013
C000= 4.0
cell_remain= 1
n1= 248
temprory4=             h_geocode      dist  cell
1019  120710401233022  2.131906    25
RHS= 120710401233022
C000= 17.0
cell_remain= 8
n1= 249
temprory4=             h_geocode      dist  cell
1288  120210101021020  0.232758    70
RHS= 120210101021020
C000= 1.0
cell_remain= 69
n1= 250
temprory4=             h_geocode      dist  cell
4349  120710107014004  0.060117    10
RHS= 120710107014004
C000= 2.0
cell_remain= 8
n1= 251
temprory4=             h_geocode      dist  cell
3709  120710402055005  0.808666    12
RHS= 120710402055005
C000= 4.0
cell_remain= 8
n1= 252
temprory4=             h_geocode      dist  cell
4355  120710402091075  0.380672     4
RHS= 120710402091075
C000= 3.0
cell_remain= 1
n1= 253
temprory4=             h_geocode        dist  cell
1941  120210110032002  150.651772    64
RHS= 120210110032002
C000= 2.0
cell_remain= 62
n1= 254
temprory4=             h_geocode      dist  cell
8433  121150027441010  1.303321     6
RHS= 121150027441010
C000= 4.0
cell_remain= 2
n1= 255
temprory4=           h_geocode      dist  cell
13  120150105052009  2.323063    39
RHS= 120150105052009
C000= 10.0
cell_remain= 29
n1= 256
temprory4=             h_geocode      dist  cell
5307  120710901002043  0.157378     8
RHS= 120710901002043
C000= 3.0
cell_remain= 5
n1= 257
temprory4=            h_geocode     dist  cell
921  120710003031015  3.37949    16
RHS= 120710003031015
C000= 10.0
cell_remain= 6
n1= 258
temprory4=             h_geocode      dist  cell
3605  120710401272017  0.182814    12
RHS= 120710401272017
C000= 4.0
cell_remain= 8
n1= 259
temprory4=             h_geocode      dist  cell
7284  120810016021057  0.732408    10
RHS= 120810016021057
C000= 2.0
cell_remain= 8
n1= 260
temprory4=             h_geocode      dist  cell
4345  120710402081166  0.543669     6
RHS= 120710402081166
C000= 3.0
cell_remain= 3
n1= 261
temprory4=            h_geocode        dist  cell
910  120210110032002  150.621854    62
RHS= 120210110032002
C000= 8.0
cell_remain= 54
n1= 262
temprory4=              h_geocode      dist  cell
10135  121150027101025  0.568753     3
RHS= 121150027101025
C000= 2.0
cell_remain= 1
n1= 263
temprory4=           h_geocode      dist  cell
17  120150101001105  5.082756     2
RHS= 120150101001105
C000= 1.0
cell_remain= 1
n1= 264
temprory4=              h_geocode      dist  cell
10626  121150027383001  0.155242     5
RHS= 121150027383001
C000= 2.0
cell_remain= 3
n1= 265
temprory4=             h_geocode      dist  cell
3609  120710401272047  0.272704    16
RHS= 120710401272047
C000= 4.0
cell_remain= 12
n1= 266
temprory4=             h_geocode      dist  cell
9485  121150022031023  0.226835     4
RHS= 121150022031023
C000= 2.0
cell_remain= 2
n1= 267
temprory4=            h_geocode     dist  cell
315  120150202053047  0.09369     5
RHS= 120150202053047
C000= 1.0
cell_remain= 4
n1= 268
temprory4=             h_geocode       dist  cell
9686  120879727001044  12.172225     2
RHS= 120879727001044
C000= 1.0
cell_remain= 1
n1= 269
temprory4=            h_geocode        dist  cell
884  120210109061022  155.442163    19
RHS= 120210109061022
C000= 8.0
cell_remain= 11
n1= 270
temprory4=             h_geocode      dist  cell
3554  120710102031030  1.275309     2
RHS= 120710102031030
C000= 1.0
cell_remain= 1
n1= 271
temprory4=              h_geocode      dist  cell
10124  121150027101007  1.892118     5
RHS= 121150027101007
C000= 2.0
cell_remain= 3
n1= 272
temprory4=           h_geocode      dist  cell
10  120150105052009  0.810823    29
RHS= 120150105052009
C000= 12.0
cell_remain= 17
n1= 273
temprory4=             h_geocode      dist  cell
2080  120710205024001  0.771897    21
RHS= 120710205024001
C000= 8.0
cell_remain= 13
n1= 274
temprory4=             h_geocode      dist  cell
4267  120710402055005  1.059402     8
RHS= 120710402055005
C000= 3.0
cell_remain= 5
n1= 275
temprory4=             h_geocode      dist  cell
3807  120710402113026  0.285102     6
RHS= 120710402113026
C000= 4.0
cell_remain= 2
n1= 276
temprory4=            h_geocode      dist  cell
612  120150207002019  0.267072     3
RHS= 120150207002019
C000= 1.0
cell_remain= 2
n1= 277
temprory4=             h_geocode      dist  cell
1878  120710402092005  1.923342    12
RHS= 120710402092005
C000= 10.0
cell_remain= 2
n1= 278
temprory4=            h_geocode      dist  cell
749  120710403052004  2.420824    35
RHS= 120710403052004
C000= 24.0
cell_remain= 11
n1= 279
temprory4=           h_geocode      dist  cell
44  120150305063005  4.754938    60
RHS= 120150305063005
C000= 21.0
cell_remain= 39
n1= 280
temprory4=             h_geocode        dist  cell
1088  120210109061010  155.323576     7
RHS= 120210109061010
C000= 6.0
cell_remain= 1
n1= 281
temprory4=             h_geocode      dist  cell
8121  120810020241023  0.306425     9
RHS= 120810020241023
C000= 2.0
cell_remain= 7
n1= 282
temprory4=            h_geocode     dist  cell
114  120150208001007  0.40621    15
RHS= 120150208001007
C000= 7.0
cell_remain= 8
n1= 283
temprory4=            h_geocode      dist  cell
913  120710401361001  2.671144    33
RHS= 120710401361001
C000= 19.0
cell_remain= 14
n1= 284
temprory4=             h_geocode      dist  cell
6028  121150027462177  0.367316    10
RHS= 121150027462177
C000= 7.0
cell_remain= 3
n1= 285
temprory4=             h_geocode      dist  cell
1492  120710401201012  1.830909    48
RHS= 120710401201012
C000= 12.0
cell_remain= 36
n1= 286
temprory4=             h_geocode      dist  cell
2715  120710101091017  0.068312    38
RHS= 120710101091017
C000= 2.0
cell_remain= 36
n1= 287
temprory4=             h_geocode      dist  cell
6025  121150027461086  0.722827    11
RHS= 121150027461086
C000= 7.0
cell_remain= 4
n1= 288
temprory4=             h_geocode        dist  cell
1417  120210110032002  151.482097    54
RHS= 120210110032002
C000= 4.0
cell_remain= 50
n1= 289
temprory4=             h_geocode      dist  cell
8732  120810016041053  0.324087    12
RHS= 120810016041053
C000= 1.0
cell_remain= 11
n1= 290

temprory4=             h_geocode      dist  cell
1785  120710401201012  8.232164    36
RHS= 120710401201012
C000= 10.0
cell_remain= 26
n1= 291
temprory4=             h_geocode        dist  cell
1223  120210109062038  139.220431     6
RHS= 120210109062038
C000= 5.0
cell_remain= 1
n1= 292
temprory4=             h_geocode      dist  cell
5030  120710402091067  0.416702     5
RHS= 120710402091067
C000= 2.0
cell_remain= 3
n1= 293
temprory4=            h_geocode      dist  cell
450  120150204022074  0.140263     2
RHS= 120150204022074
C000= 1.0
cell_remain= 1
n1= 294
temprory4=           h_geocode      dist  cell
10  120150105052009  1.758893    17
RHS= 120150105052009
C000= 13.0
cell_remain= 4
n1= 295
temprory4=             h_geocode      dist  cell
5188  121150027231029  1.560311    14
RHS= 121150027231029
C000= 8.0
cell_remain= 6
n1= 296
temprory4=             h_geocode      dist  cell
6091  120710402113032  0.142548     4
RHS= 120710402113032
C000= 1.0
cell_remain= 3
n1= 297
temprory4=            h_geocode      dist  cell
709  120150210032054  0.191745     6
RHS= 120150210032054
C000= 1.0
cell_remain= 5
n1= 298
temprory4=             h_geocode        dist  cell
1639  120210110032002  150.515929    50
RHS= 120210110032002
C000= 3.0
cell_remain= 47
n1= 299
temprory4=             h_geocode      dist  cell
6003  120710402093024  0.142553     2
RHS= 120710402093024
C000= 1.0
cell_remain= 1
n1= 300
temprory4=             h_geocode      dist  cell
2066  120710402092007  2.785857    13
RHS= 120710402092007
C000= 9.0
cell_remain= 4
n1= 301
temprory4=            h_geocode      dist  cell
949  120710401201012  2.665675    26
RHS= 120710401201012
C000= 18.0
cell_remain= 8
n1= 302
temprory4=             h_geocode      dist  cell
3812  120710402121032  0.307095     6
RHS= 120710402121032
C000= 4.0
cell_remain= 2
n1= 303
temprory4=             h_geocode        dist  cell
1639  120210110032002  151.418098    47
RHS= 120210110032002
C000= 3.0
cell_remain= 44
n1= 304
temprory4=             h_geocode      dist  cell
5420  121150027462092  0.597682    10
RHS= 121150027462092
C000= 8.0
cell_remain= 2
n1= 305
temprory4=             h_geocode       dist  cell
9680  120879727001043  108.72578     2
RHS= 120879727001043
C000= 1.0
cell_remain= 1
n1= 306
temprory4=            h_geocode      dist  cell
498  120150210011059  0.185968     3
RHS= 120150210011059
C000= 2.0
cell_remain= 1
n1= 307
temprory4=             h_geocode      dist  cell
2783  120710401201031  0.865137     8
RHS= 120710401201031
C000= 6.0
cell_remain= 2
n1= 308
temprory4=             h_geocode      dist  cell
1524  121150027211020  3.025133    30
RHS= 121150027211020
C000= 26.0
cell_remain= 4
n1= 309
temprory4=             h_geocode      dist  cell
3002  120710504013009  0.470214     8
RHS= 120710504013009
C000= 7.0
cell_remain= 1
n1= 310
temprory4=              h_geocode      dist  cell
11005  121150027462357  0.681099     4
RHS= 121150027462357
C000= 2.0
cell_remain= 2
n1= 311
temprory4=             h_geocode      dist  cell
2764  120810006013024  0.786898    13
RHS= 120810006013024
C000= 9.0
cell_remain= 4
n1= 312
temprory4=            h_geocode      dist  cell
140  120150202031034  0.095708    13
RHS= 120150202031034
C000= 2.0
cell_remain= 11
n1= 313
temprory4=            h_geocode        dist  cell
585  120210109072033  156.480949    31
RHS= 120210109072033
C000= 15.0
cell_remain= 16
n1= 314
temprory4=             h_geocode      dist  cell
6517  120710403141181  0.384859     2
RHS= 120710403141181
C000= 1.0
cell_remain= 1
n1= 315
temprory4=            h_geocode      dist  cell
152  120150204024024  0.616827    12
RHS= 120150204024024
C000= 5.0
cell_remain= 7
n1= 316
temprory4=             h_geocode      dist  cell
3362  120710403011021  0.884339     8
RHS= 120710403011021
C000= 5.0
cell_remain= 3
n1= 317
temprory4=             h_geocode      dist  cell
4406  121150027361023  0.940588    11
RHS= 121150027361023
C000= 10.0
cell_remain= 1
n1= 318
temprory4=             h_geocode      dist  cell
1255  120710403131001  3.889729    38
RHS= 120710403131001
C000= 15.0
cell_remain= 23
n1= 319
temprory4=             h_geocode      dist  cell
2226  121150027371014  3.095283    26
RHS= 121150027371014
C000= 19.0
cell_remain= 7
n1= 320
temprory4=             h_geocode      dist  cell
1533  120810016042000  1.464112    24
RHS= 120810016042000
C000= 18.0
cell_remain= 6
n1= 321
temprory4=             h_geocode      dist  cell
2212  120710102052048  0.234984    10
RHS= 120710102052048
C000= 4.0
cell_remain= 6
n1= 322
temprory4=            h_geocode        dist  cell
461  120210109072021  157.508591    54
RHS= 120210109072021
C000= 19.0
cell_remain= 35
n1= 323
temprory4=             h_geocode        dist  cell
9676  120879727001037  141.431913     2
RHS= 120879727001037
C000= 1.0
cell_remain= 1
n1= 324
temprory4=             h_geocode      dist  cell
2116  120710303001002  1.260348     9
RHS= 120710303001002
C000= 8.0
cell_remain= 1
n1= 325
temprory4=             h_geocode      dist  cell
2638  120710005023008  0.451404     2
RHS= 120710005023008
C000= 1.0
cell_remain= 1
n1= 326
temprory4=            h_geocode        dist  cell
685  120210109072033  156.767627    16
RHS= 120210109072033
C000= 12.0
cell_remain= 4
n1= 327
temprory4=             h_geocode      dist  cell
5375  120710403152028  0.198924     3
RHS= 120710403152028
C000= 2.0
cell_remain= 1
n1= 328
temprory4=             h_geocode        dist  cell
1414  120210110032002  148.654895    44
RHS= 120210110032002
C000= 4.0
cell_remain= 40
n1= 329
temprory4=             h_geocode      dist  cell
2038  120710402053014  0.157346    22
RHS= 120710402053014
C000= 9.0
cell_remain= 13
n1= 330
temprory4=             h_geocode      dist  cell
3834  120710102071000  0.646522     5
RHS= 120710102071000
C000= 1.0
cell_remain= 4
n1= 331
temprory4=            h_geocode     dist  cell
363  120150304011029  0.73788     8
RHS= 120150304011029
C000= 4.0
cell_remain= 4
n1= 332
temprory4=             h_geocode       dist  cell
1700  120210111111001  29.467057     4
RHS= 120210111111001
C000= 3.0
cell_remain= 1
n1= 333
temprory4=             h_geocode      dist  cell
3117  121150027452012  5.352775    15
RHS= 121150027452012
C000= 14.0
cell_remain= 1
n1= 334
temprory4=             h_geocode        dist  cell
2361  120210110032009  151.239539     2
RHS= 120210110032009
C000= 1.0
cell_remain= 1
n1= 335
temprory4=            h_geocode      dist  cell
157  120150203012023  0.681571     6
RHS= 120150203012023
C000= 4.0
cell_remain= 2
n1= 336
temprory4=             h_geocode     dist  cell
4342  120710402081173  0.95973     5
RHS= 120710402081173
C000= 3.0
cell_remain= 2
n1= 337
temprory4=             h_geocode        dist  cell
1936  120210110032002  151.702037    40
RHS= 120210110032002
C000= 2.0
cell_remain= 38
n1= 338
temprory4=             h_geocode      dist  cell
7865  120810006013022  0.150766     2
RHS= 120810006013022
C000= 1.0
cell_remain= 1
n1= 339
temprory4=             h_geocode      dist  cell
1585  120210103003013  0.174771     7
RHS= 120210103003013
C000= 1.0
cell_remain= 6
n1= 340
temprory4=             h_geocode      dist  cell
2337  121150025071015  0.470197    18
RHS= 121150025071015
C000= 17.0
cell_remain= 1
n1= 341
temprory4=            h_geocode        dist  cell
356  120210110032002  150.373711    38
RHS= 120210110032002
C000= 26.0
cell_remain= 12
n1= 342
temprory4=            h_geocode      dist  cell
984  120150304022014  0.404327     2
RHS= 120150304022014
C000= 1.0
cell_remain= 1
n1= 343
temprory4=            h_geocode       dist  cell
685  120210109072037  155.81179    17
RHS= 120210109072037
C000= 12.0
cell_remain= 5
n1= 344
temprory4=            h_geocode      dist  cell
444  120150204022014  0.314303     2
RHS= 120150204022014
C000= 1.0
cell_remain= 1
n1= 345
temprory4=            h_geocode     dist  cell
133  120150203023012  0.16498     7
RHS= 120150203023012
C000= 5.0
cell_remain= 2
n1= 346
temprory4=             h_geocode     dist  cell
9667  120879727001026  0.29063     2
RHS= 120879727001026
C000= 1.0
cell_remain= 1
n1= 347
temprory4=             h_geocode      dist  cell
5361  120710403151058  0.443155     6
RHS= 120710403151058
C000= 2.0
cell_remain= 4

n1= 348
temprory4=             h_geocode        dist  cell
2360  120210110032014  150.049123     2
RHS= 120210110032014
C000= 1.0
cell_remain= 1
n1= 349
temprory4=            h_geocode      dist  cell
525  120150305041013  1.627213     5
RHS= 120150305041013
C000= 3.0
cell_remain= 2
n1= 350
temprory4=            h_geocode      dist  cell
656  120710103081017  0.542136    24
RHS= 120710103081017
C000= 20.0
cell_remain= 4
n1= 351
temprory4=             h_geocode      dist  cell
4810  120810005031007  0.116992     5
RHS= 120810005031007
C000= 4.0
cell_remain= 1
n1= 352
temprory4=            h_geocode      dist  cell
517  120150205012016  0.217919     7
RHS= 120150205012016
C000= 1.0
cell_remain= 6
n1= 353
temprory4=             h_geocode      dist  cell
1597  120710003051015  0.444592     6
RHS= 120710003051015
C000= 4.0
cell_remain= 2
n1= 354
temprory4=             h_geocode       dist  cell
9665  120879727002018  84.260573     2
RHS= 120879727002018
C000= 1.0
cell_remain= 1
n1= 355
temprory4=            h_geocode        dist  cell
855  120210110032002  151.347071    12
RHS= 120210110032002
C000= 9.0
cell_remain= 3
n1= 356
temprory4=             h_geocode        dist  cell
1598  120210109062006  155.568077     4
RHS= 120210109062006
C000= 3.0
cell_remain= 1
n1= 357
temprory4=             h_geocode      dist  cell
5996  120710402093074  0.481475     4
RHS= 120710402093074
C000= 1.0
cell_remain= 3
n1= 358
temprory4=             h_geocode        dist  cell
1214  120210109061015  155.649482     7
RHS= 120210109061015
C000= 5.0
cell_remain= 2
n1= 359
temprory4=            h_geocode      dist  cell
303  120710403022000  7.020848    59
RHS= 120710403022000
C000= 56.0
cell_remain= 3
n1= 360
temprory4=              h_geocode      dist  cell
10587  121150016023005  0.074297     4
RHS= 121150016023005
C000= 1.0
cell_remain= 3
n1= 361
temprory4=             h_geocode      dist  cell
2988  120710104213031  0.105061    22
RHS= 120710104213031
C000= 4.0
cell_remain= 18
n1= 362
temprory4=           h_geocode      dist  cell
87  120150105031021  1.865225    14
RHS= 120150105031021
C000= 1.0
cell_remain= 13
n1= 363
temprory4=            h_geocode      dist  cell
113  120150303011026  1.444983     9
RHS= 120150303011026
C000= 8.0
cell_remain= 1
n1= 364
temprory4=             h_geocode      dist  cell
1118  120710101071016  1.190327    13
RHS= 120710101071016
C000= 10.0
cell_remain= 3
n1= 365
temprory4=            h_geocode      dist  cell
116  120150105061003  3.756584     4
RHS= 120150105061003
C000= 1.0
cell_remain= 3
n1= 366
temprory4=            h_geocode      dist  cell
793  120710101103017  2.136428    51
RHS= 120710101103017
C000= 16.0
cell_remain= 35
n1= 367
temprory4=             h_geocode      dist  cell
3482  120710401093009  0.518141    11
RHS= 120710401093009
C000= 4.0
cell_remain= 7
n1= 368
temprory4=             h_geocode       dist  cell
2357  120210110032013  145.67546     2
RHS= 120210110032013
C000= 1.0
cell_remain= 1
n1= 369
temprory4=             h_geocode      dist  cell
1953  120710101071030  0.363871     5
RHS= 120710101071030
C000= 4.0
cell_remain= 1
n1= 370
temprory4=             h_geocode       dist  cell
1214  120210109062008  156.34777     7
RHS= 120210109062008
C000= 5.0
cell_remain= 2
n1= 371
temprory4=           h_geocode      dist  cell
26  120150201042010  8.509199    20
RHS= 120150201042010
C000= 19.0
cell_remain= 1
n1= 372
temprory4=             h_geocode      dist  cell
4682  120710401233039  0.094578     5
RHS= 120710401233039
C000= 2.0
cell_remain= 3
n1= 373
temprory4=             h_geocode        dist  cell
2307  120210109061014  139.566005     3
RHS= 120210109061014
C000= 1.0
cell_remain= 2
n1= 374
temprory4=           h_geocode      dist  cell
27  120150201042017  5.191218    20
RHS= 120150201042017
C000= 17.0
cell_remain= 3
n1= 375
temprory4=             h_geocode      dist  cell
1425  120710402071000  0.646811    54
RHS= 120710402071000
C000= 13.0
cell_remain= 41
n1= 376
temprory4=             h_geocode        dist  cell
2036  120210112083004  140.837225     3
RHS= 120210112083004
C000= 2.0
cell_remain= 1
n1= 377
temprory4=             h_geocode      dist  cell
5016  120710402092007  0.432568     4
RHS= 120710402092007
C000= 2.0
cell_remain= 2
n1= 378
temprory4=             h_geocode      dist  cell
6510  120710403142102  0.673005     2
RHS= 120710403142102
C000= 1.0
cell_remain= 1
n1= 379
temprory4=             h_geocode      dist  cell
1342  120710403131001  0.850881    23
RHS= 120710403131001
C000= 14.0
cell_remain= 9
n1= 380
temprory4=             h_geocode        dist  cell
1886  120210109061018  155.371031     4
RHS= 120210109061018
C000= 2.0
cell_remain= 2
n1= 381
temprory4=             h_geocode      dist  cell
5516  120710401221007  0.342308     2
RHS= 120710401221007
C000= 1.0
cell_remain= 1
n1= 382
temprory4=             h_geocode     dist  cell
6505  120710403142043  0.35059     3
RHS= 120710403142043
C000= 1.0
cell_remain= 2
n1= 383
temprory4=             h_geocode        dist  cell
1927  120210110032002  151.201225     3
RHS= 120210110032002
C000= 2.0
cell_remain= 1
n1= 384
temprory4=            h_geocode        dist  cell
587  120210110033021  151.165738    23
RHS= 120210110033021
C000= 15.0
cell_remain= 8
n1= 385
temprory4=             h_geocode        dist  cell
1632  120210110033021  150.580018     8
RHS= 120210110033021
C000= 3.0
cell_remain= 5
n1= 386
temprory4=              h_geocode    dist  cell
10955  121150027461070  0.2563     6
RHS= 121150027461070
C000= 2.0
cell_remain= 4
n1= 387
temprory4=             h_geocode      dist  cell
1935  120710101062090  0.211532     6
RHS= 120710101062090
C000= 4.0
cell_remain= 2
n1= 388
temprory4=             h_geocode        dist  cell
1888  120210109062007  156.476655     3
RHS= 120210109062007
C000= 2.0
cell_remain= 1
n1= 389
temprory4=            h_geocode     dist  cell
371  120150205012018  0.26598     6
RHS= 120150205012018
C000= 2.0
cell_remain= 4
n1= 390
temprory4=            h_geocode      dist  cell
351  120150203011102  0.723281     3
RHS= 120150203011102
C000= 1.0
cell_remain= 2
n1= 391
temprory4=             h_geocode      dist  cell
5630  120710401271007  0.124423     2
RHS= 120710401271007
C000= 1.0
cell_remain= 1
n1= 392
temprory4=             h_geocode      dist  cell
5180  120710403023030  0.118285     3
RHS= 120710403023030
C000= 2.0
cell_remain= 1
n1= 393
temprory4=             h_geocode      dist  cell
4345  120710402112000  1.272444    24
RHS= 120710402112000
C000= 3.0
cell_remain= 21
n1= 394
temprory4=             h_geocode      dist  cell
8709  120810016043014  0.574023     2
RHS= 120810016043014
C000= 1.0
cell_remain= 1
n1= 395
temprory4=             h_geocode      dist  cell
8917  120810019092009  0.242178    11
RHS= 120810019092009
C000= 1.0
cell_remain= 10
n1= 396
temprory4=             h_geocode      dist  cell
5644  121150019092010  0.652897    75
RHS= 121150019092010
C000= 6.0
cell_remain= 69
n1= 397
temprory4=             h_geocode      dist  cell
8387  120810011081008  0.376331     7
RHS= 120810011081008
C000= 1.0
cell_remain= 6
n1= 398
temprory4=            h_geocode     dist  cell
759  120150301021015  0.09627     2
RHS= 120150301021015
C000= 1.0
cell_remain= 1
n1= 399
temprory4=             h_geocode      dist  cell
5346  120710403152004  0.417924     3
RHS= 120710403152004
C000= 2.0
cell_remain= 1
n1= 400
temprory4=            h_geocode     dist  cell
350  120150203011053  0.60553     2
RHS= 120150203011053
C000= 1.0
cell_remain= 1
n1= 401
temprory4=             h_geocode      dist  cell
5968  121150027432047  2.133443     8
RHS= 121150027432047
C000= 7.0
cell_remain= 1
n1= 402
temprory4=            h_geocode      dist  cell
863  120150302013063  0.238379     2
RHS= 120150302013063
C000= 1.0
cell_remain= 1
n1= 403
temprory4=             h_geocode      dist  cell
8697  120810016041001  0.408822     7
RHS= 120810016041001
C000= 1.0
cell_remain= 6
n1= 404
temprory4=             h_geocode      dist  cell
9425  121150027421038  0.216765     9
RHS= 121150027421038
C000= 3.0
cell_remain= 6
n1= 405
temprory4=             h_geocode      dist  cell
2719  120710101093003  0.555388     7
RHS= 120710101093003
C000= 2.0
cell_remain= 5

n1= 406
temprory4=             h_geocode      dist  cell
9595  121150027462195  1.639889     5
RHS= 121150027462195
C000= 3.0
cell_remain= 2
n1= 407
temprory4=           h_geocode     dist  cell
33  120150205011043  3.50072    19
RHS= 120150205011043
C000= 15.0
cell_remain= 4
n1= 408
temprory4=             h_geocode      dist  cell
8706  120810016043029  0.961083     2
RHS= 120810016043029
C000= 1.0
cell_remain= 1
n1= 409
temprory4=             h_geocode    dist  cell
1020  120210104321021  0.2295     6
RHS= 120210104321021
C000= 4.0
cell_remain= 2
n1= 410
temprory4=             h_geocode      dist  cell
5208  120710702022026  0.775754   103
RHS= 120710702022026
C000= 3.0
cell_remain= 100
n1= 411
temprory4=            h_geocode      dist  cell
208  120150202032006  0.437182     7
RHS= 120150202032006
C000= 1.0
cell_remain= 6
n1= 412
temprory4=             h_geocode       dist  cell
1687  120210111111002  29.890561    19
RHS= 120210111111002
C000= 3.0
cell_remain= 16
n1= 413
temprory4=             h_geocode      dist  cell
2138  120710003051010  0.839462     3
RHS= 120710003051010
C000= 2.0
cell_remain= 1
n1= 414
temprory4=             h_geocode      dist  cell
1314  120210105132016  0.886341    13
RHS= 120210105132016
C000= 3.0
cell_remain= 10
n1= 415
temprory4=             h_geocode      dist  cell
3229  120710401384003  6.171488     6
RHS= 120710401384003
C000= 5.0
cell_remain= 1
n1= 416
temprory4=             h_geocode      dist  cell
4344  120810020202002  3.670801     8
RHS= 120810020202002
C000= 7.0
cell_remain= 1
n1= 417
temprory4=             h_geocode        dist  cell
2365  120210111072037  140.264697     2
RHS= 120210111072037
C000= 1.0
cell_remain= 1
n1= 418
temprory4=             h_geocode      dist  cell
6989  120810011081008  0.898934     6
RHS= 120810011081008
C000= 2.0
cell_remain= 4
n1= 419
temprory4=             h_geocode      dist  cell
4983  120710402081061  0.569443     5
RHS= 120710402081061
C000= 2.0
cell_remain= 3
n1= 420
temprory4=            h_geocode      dist  cell
729  120150301011169  0.215697     2
RHS= 120150301011169
C000= 1.0
cell_remain= 1
n1= 421
temprory4=             h_geocode        dist  cell
2001  120210111141018  156.089846     3
RHS= 120210111141018
C000= 2.0
cell_remain= 1
n1= 422
temprory4=            h_geocode       dist  cell
877  120210109061022  155.79457    11
RHS= 120210109061022
C000= 8.0
cell_remain= 3
n1= 423
temprory4=             h_geocode       dist  cell
1045  120210111111002  29.444829    16
RHS= 120210111111002
C000= 7.0
cell_remain= 9
n1= 424
temprory4=            h_geocode      dist  cell
944  120710403152001  6.015165    35
RHS= 120710403152001
C000= 19.0
cell_remain= 16
n1= 425
temprory4=          h_geocode     dist  cell
5  120150104053000  2.52134    18
RHS= 120150104053000
C000= 13.0
cell_remain= 5
n1= 426
temprory4=             h_geocode      dist  cell
9641  121150001021015  0.274427     5
RHS= 121150001021015
C000= 1.0
cell_remain= 4
n1= 427
temprory4=             h_geocode      dist  cell
2548  120710402073043  0.939539     9
RHS= 120710402073043
C000= 7.0
cell_remain= 2
n1= 428
temprory4=            h_geocode      dist  cell
342  120150204024024  0.959172     7
RHS= 120150204024024
C000= 2.0
cell_remain= 5
n1= 429
temprory4=             h_geocode      dist  cell
8618  120810014061018  0.554377     6
RHS= 120810014061018
C000= 1.0
cell_remain= 5
n1= 430
temprory4=             h_geocode      dist  cell
4966  120710503222009  0.718786     5
RHS= 120710503222009
C000= 3.0
cell_remain= 2
n1= 431
temprory4=            h_geocode     dist  cell
374  120150203021065  0.09148     2
RHS= 120150203021065
C000= 1.0
cell_remain= 1
n1= 432
temprory4=             h_geocode      dist  cell
9452  121150022032029  0.098621     6
RHS= 121150022032029
C000= 2.0
cell_remain= 4
n1= 433
temprory4=           h_geocode      dist  cell
50  120150105052049  0.503124     4
RHS= 120150105052049
C000= 3.0
cell_remain= 1
n1= 434
temprory4=             h_geocode        dist  cell
1884  120210109061025  153.982037     3
RHS= 120210109061025
C000= 2.0
cell_remain= 1
n1= 435
temprory4=            h_geocode     dist  cell
568  120150305071050  0.42254     4
RHS= 120150305071050
C000= 3.0
cell_remain= 1
n1= 436
temprory4=            h_geocode      dist  cell
128  120150205012050  0.417006     8
RHS= 120150205012050
C000= 6.0
cell_remain= 2
n1= 437
temprory4=             h_geocode      dist  cell
7303  120810018011013  0.176178     5
RHS= 120810018011013
C000= 2.0
cell_remain= 3
n1= 438
temprory4=           h_geocode      dist  cell
33  120150202032013  0.918999    17
RHS= 120150202032013
C000= 12.0
cell_remain= 5
n1= 439
temprory4=            h_geocode      dist  cell
326  120150204022070  0.091454     3
RHS= 120150204022070
C000= 2.0
cell_remain= 1
n1= 440
temprory4=           h_geocode      dist  cell
18  120150105052006  0.937862    23
RHS= 120150105052006
C000= 6.0
cell_remain= 17
n1= 441
temprory4=             h_geocode      dist  cell
5788  120710503211003  0.332434    64
RHS= 120710503211003
C000= 2.0
cell_remain= 62
n1= 442
temprory4=             h_geocode      dist  cell
5197  120710201041019  0.916484    10
RHS= 120710201041019
C000= 1.0
cell_remain= 9
n1= 443
temprory4=             h_geocode      dist  cell
2078  120710019131002  0.592452    15
RHS= 120710019131002
C000= 3.0
cell_remain= 12
n1= 444
temprory4=             h_geocode      dist  cell
6486  120810006011013  0.328058     3
RHS= 120810006011013
C000= 2.0
cell_remain= 1
n1= 445
temprory4=             h_geocode       dist  cell
1878  120210109061011  156.25138    10
RHS= 120210109061011
C000= 2.0
cell_remain= 8
n1= 446
temprory4=           h_geocode      dist  cell
74  120150105053099  0.615812     3
RHS= 120150105053099
C000= 2.0
cell_remain= 1
n1= 447
temprory4=             h_geocode      dist  cell
4033  120710401201028  1.145441    13
RHS= 120710401201028
C000= 3.0
cell_remain= 10
n1= 448
temprory4=           h_geocode      dist  cell
67  120150103022080  0.424171     2
RHS= 120150103022080
C000= 1.0
cell_remain= 1
n1= 449
temprory4=             h_geocode      dist  cell
3656  120710401382026  1.241968    75
RHS= 120710401382026
C000= 4.0
cell_remain= 71
n1= 450
temprory4=             h_geocode      dist  cell
8293  120810010012001  0.278321    11
RHS= 120810010012001
C000= 1.0
cell_remain= 10
n1= 451
temprory4=             h_geocode      dist  cell
1997  120810016042025  2.303692    24
RHS= 120810016042025
C000= 14.0
cell_remain= 10
n1= 452
temprory4=              h_geocode      dist  cell
12733  121150027442062  0.246165     3
RHS= 121150027442062
C000= 1.0
cell_remain= 2
n1= 453
temprory4=             h_geocode      dist  cell
3762  120810020113004  0.304321    28
RHS= 120810020113004
C000= 8.0
cell_remain= 20
n1= 454
temprory4=             h_geocode     dist  cell
5000  120710402092042  1.12801     3
RHS= 120710402092042
C000= 2.0
cell_remain= 1
n1= 455
temprory4=            h_geocode      dist  cell
905  120710003031014  1.886622    17
RHS= 120710003031014
C000= 10.0
cell_remain= 7
n1= 456
temprory4=            h_geocode      dist  cell
440  120150204022028  0.208134     2
RHS= 120150204022028
C000= 1.0
cell_remain= 1
n1= 457
temprory4=             h_geocode      dist  cell
1664  120710402053014  1.834162    13
RHS= 120710402053014
C000= 11.0
cell_remain= 2
n1= 458
temprory4=             h_geocode      dist  cell
3233  120710101091008  0.436894     3
RHS= 120710101091008
C000= 1.0
cell_remain= 2
n1= 459
temprory4=             h_geocode     dist  cell
1004  120150305012128  0.99601     3
RHS= 120150305012128
C000= 1.0
cell_remain= 2
n1= 460
temprory4=             h_geocode      dist  cell
7429  120710901002040  1.887367     2
RHS= 120710901002040
C000= 1.0
cell_remain= 1
n1= 461
temprory4=             h_geocode     dist  cell
6437  120710403122111  0.37221     2
RHS= 120710403122111
C000= 1.0
cell_remain= 1
n1= 462
temprory4=             h_geocode        dist  cell
1202  120210109061011  149.119459     8
RHS= 120210109061011
C000= 5.0
cell_remain= 3
n1= 463
temprory4=             h_geocode      dist  cell
1403  120710003033038  0.158242     7
RHS= 120710003033038
C000= 5.0
cell_remain= 2
n1= 464
temprory4=             h_geocode      dist  cell
2939  120710019152002  0.519263    73
RHS= 120710019152002
C000= 1.0
cell_remain= 72

n1= 465
temprory4=            h_geocode      dist  cell
523  120150301012110  0.464918     5
RHS= 120150301012110
C000= 2.0
cell_remain= 3
n1= 466
temprory4=            h_geocode      dist  cell
238  120150204022107  0.192916     5
RHS= 120150204022107
C000= 3.0
cell_remain= 2
n1= 467
temprory4=            h_geocode      dist  cell
755  120150305062019  0.336589     4
RHS= 120150305062019
C000= 2.0
cell_remain= 2
n1= 468
temprory4=            h_geocode      dist  cell
211  120150301012121  0.805107     6
RHS= 120150301012121
C000= 5.0
cell_remain= 1
n1= 469
temprory4=             h_geocode     dist  cell
6325  120710403082022  0.09064     2
RHS= 120710403082022
C000= 1.0
cell_remain= 1
n1= 470
temprory4=            h_geocode      dist  cell
543  120710019111009  0.753449    66
RHS= 120710019111009
C000= 23.0
cell_remain= 43
n1= 471
temprory4=             h_geocode      dist  cell
3289  120710402101000  1.799964    22
RHS= 120710402101000
C000= 5.0
cell_remain= 17
n1= 472
temprory4=             h_geocode      dist  cell
6905  120710503123025  0.408944     2
RHS= 120710503123025
C000= 1.0
cell_remain= 1
n1= 473
temprory4=          h_geocode      dist  cell
5  120150102001026  1.307241    12
RHS= 120150102001026
C000= 4.0
cell_remain= 8
n1= 474
temprory4=             h_geocode      dist  cell
3038  120710501062005  0.287653     9
RHS= 120710501062005
C000= 6.0
cell_remain= 3
n1= 475
temprory4=             h_geocode      dist  cell
2921  120710019122006  0.378696     3
RHS= 120710019122006
C000= 1.0
cell_remain= 2
n1= 476
temprory4=              h_geocode      dist  cell
11749  121150026032014  0.210896     3
RHS= 121150026032014
C000= 1.0
cell_remain= 2
n1= 477
temprory4=             h_geocode      dist  cell
4827  120810015013018  0.990246     6
RHS= 120810015013018
C000= 5.0
cell_remain= 1
n1= 478
temprory4=              h_geocode      dist  cell
12487  121150027402060  0.169398    11
RHS= 121150027402060
C000= 1.0
cell_remain= 10
n1= 479
temprory4=            h_geocode      dist  cell
202  120150203021093  0.584981     4
RHS= 120150203021093
C000= 3.0
cell_remain= 1
n1= 480
temprory4=             h_geocode      dist  cell
3878  120710403121026  1.642044     5
RHS= 120710403121026
C000= 4.0
cell_remain= 1
n1= 481
temprory4=             h_geocode      dist  cell
2273  120710402112000  0.874044    21
RHS= 120710402112000
C000= 8.0
cell_remain= 13
n1= 482
temprory4=             h_geocode      dist  cell
9411  121150027423004  0.084306     5
RHS= 121150027423004
C000= 3.0
cell_remain= 2
n1= 483
temprory4=            h_geocode      dist  cell
377  120150301011110  0.306941     4
RHS= 120150301011110
C000= 3.0
cell_remain= 1
n1= 484
temprory4=             h_geocode      dist  cell
7866  120810007042015  0.060834     2
RHS= 120810007042015
C000= 1.0
cell_remain= 1
n1= 485
temprory4=            h_geocode      dist  cell
418  120150204011032  0.442444    16
RHS= 120150204011032
C000= 1.0
cell_remain= 15
n1= 486
temprory4=             h_geocode      dist  cell
2965  120810020202039  1.242568    27
RHS= 120810020202039
C000= 11.0
cell_remain= 16
n1= 487
temprory4=             h_geocode      dist  cell
1401  120810004091005  0.316846   115
RHS= 120810004091005
C000= 17.0
cell_remain= 98
n1= 488
temprory4=             h_geocode      dist  cell
4044  120710401241030  0.137054     4
RHS= 120710401241030
C000= 3.0
cell_remain= 1
n1= 489
temprory4=           h_geocode     dist  cell
56  120150205013013  4.17348    15
RHS= 120150205013013
C000= 10.0
cell_remain= 5
n1= 490
temprory4=             h_geocode      dist  cell
6836  120810009013035  0.097612     3
RHS= 120810009013035
C000= 2.0
cell_remain= 1
n1= 491
temprory4=             h_geocode      dist  cell
2637  120710102071000  1.237604     4
RHS= 120710102071000
C000= 3.0
cell_remain= 1
n1= 492
temprory4=           h_geocode     dist  cell
53  120150105061025  3.04874     7
RHS= 120150105061025
C000= 3.0
cell_remain= 4
n1= 493
temprory4=             h_geocode      dist  cell
5777  120710503221004  0.121229     9
RHS= 120710503221004
C000= 2.0
cell_remain= 7
n1= 494
temprory4=            h_geocode      dist  cell
360  120150210011067  0.833231     7
RHS= 120150210011067
C000= 3.0
cell_remain= 4
n1= 495
temprory4=             h_geocode      dist  cell
7319  120710701023059  0.091287     2
RHS= 120710701023059
C000= 1.0
cell_remain= 1
n1= 496
temprory4=             h_geocode       dist  cell
2300  120210109062039  141.71016     2
RHS= 120210109062039
C000= 1.0
cell_remain= 1
n1= 497
temprory4=             h_geocode      dist  cell
1426  120710104192063  1.616841    13
RHS= 120710104192063
C000= 10.0
cell_remain= 3
n1= 498
temprory4=             h_geocode      dist  cell
6904  121150026021004  0.201981    15
RHS= 121150026021004
C000= 5.0
cell_remain= 10
n1= 499
temprory4=             h_geocode      dist  cell
3217  120710101081109  0.301858     2
RHS= 120710101081109
C000= 1.0
cell_remain= 1
n1= 500
temprory4=            h_geocode      dist  cell
975  120150305011007  0.773307     2
RHS= 120150305011007
C000= 1.0
cell_remain= 1
n1= 501
temprory4=            h_geocode      dist  cell
184  120150202062040  0.901505     7
RHS= 120150202062040
C000= 3.0
cell_remain= 4
n1= 502
temprory4=             h_geocode      dist  cell
4448  120710403041038  0.249377     4
RHS= 120710403041038
C000= 3.0
cell_remain= 1
n1= 503
temprory4=             h_geocode      dist  cell
7934  120810020202001  2.017332     6
RHS= 120810020202001
C000= 2.0
cell_remain= 4
n1= 504
temprory4=             h_geocode      dist  cell
6414  121150009001002  0.415187     7
RHS= 121150009001002
C000= 4.0
cell_remain= 3
n1= 505
temprory4=             h_geocode      dist  cell
5308  121150027372025  3.158906    14
RHS= 121150027372025
C000= 8.0
cell_remain= 6
n1= 506
temprory4=             h_geocode      dist  cell
7558  120810019141019  4.361685     4
RHS= 120810019141019
C000= 2.0
cell_remain= 2
n1= 507
temprory4=            h_geocode      dist  cell
369  120150203021035  0.917827     2
RHS= 120150203021035
C000= 1.0
cell_remain= 1
n1= 508
temprory4=             h_geocode      dist  cell
7301  120710701023013  0.764921     2
RHS= 120710701023013
C000= 1.0
cell_remain= 1
n1= 509
temprory4=            h_geocode      dist  cell
386  120150203031031  0.718433     6
RHS= 120150203031031
C000= 1.0
cell_remain= 5
n1= 510
temprory4=            h_geocode      dist  cell
991  120150305012069  0.375197    16
RHS= 120150305012069
C000= 1.0
cell_remain= 15
n1= 511
temprory4=           h_geocode     dist  cell
58  120150103021065  0.20726     3
RHS= 120150103021065
C000= 1.0
cell_remain= 2
n1= 512
temprory4=             h_geocode      dist  cell
5253  120710403102006  0.418471     5
RHS= 120710403102006
C000= 2.0
cell_remain= 3
n1= 513
temprory4=             h_geocode      dist  cell
7431  121150027432029  2.559884     6
RHS= 121150027432029
C000= 5.0
cell_remain= 1
n1= 514
temprory4=            h_geocode        dist  cell
828  120210109061012  150.823381    10
RHS= 120210109061012
C000= 9.0
cell_remain= 1
n1= 515
temprory4=             h_geocode      dist  cell
1197  120210109071003  0.199476    72
RHS= 120210109071003
C000= 5.0
cell_remain= 67
n1= 516
temprory4=             h_geocode       dist  cell
1072  120210112081012  10.119823    12
RHS= 120210112081012
C000= 7.0
cell_remain= 5
n1= 517
temprory4=              h_geocode     dist  cell
10918  121150027461112  0.48739     3
RHS= 121150027461112
C000= 2.0
cell_remain= 1
n1= 518
temprory4=           h_geocode      dist  cell
26  120150305013025  2.266927    77
RHS= 120150305013025
C000= 31.0
cell_remain= 46
n1= 519
temprory4=             h_geocode       dist  cell
2448  120210112083052  12.875463     2
RHS= 120210112083052
C000= 1.0
cell_remain= 1
n1= 520
temprory4=           h_geocode      dist  cell
29  120150201031009  1.623928    13
RHS= 120150201031009
C000= 10.0
cell_remain= 3
n1= 521
temprory4=            h_geocode      dist  cell
348  120150203011150  0.692866     2
RHS= 120150203011150
C000= 1.0
cell_remain= 1
n1= 522
temprory4=            h_geocode      dist  cell
112  120150105053291  2.069803     2
RHS= 120150105053291
C000= 1.0
cell_remain= 1
n1= 523
temprory4=             h_geocode      dist  cell
6450  120710403131105  0.371982     3
RHS= 120710403131105
C000= 1.0
cell_remain= 2

n1= 524
temprory4=             h_geocode      dist  cell
5294  120710403131072  0.449424     3
RHS= 120710403131072
C000= 2.0
cell_remain= 1
n1= 525
temprory4=            h_geocode      dist  cell
235  120150204022105  1.071852     4
RHS= 120150204022105
C000= 3.0
cell_remain= 1
n1= 526
temprory4=             h_geocode      dist  cell
9488  121150023041004  0.103401     8
RHS= 121150023041004
C000= 2.0
cell_remain= 6
n1= 527
temprory4=             h_geocode      dist  cell
2125  120710501064001  0.494816    71
RHS= 120710501064001
C000= 9.0
cell_remain= 62
n1= 528
temprory4=            h_geocode     dist  cell
468  120150204024078  0.18469     2
RHS= 120150204024078
C000= 1.0
cell_remain= 1
n1= 529
temprory4=            h_geocode     dist  cell
324  120150202062009  0.52173     4
RHS= 120150202062009
C000= 1.0
cell_remain= 3
n1= 530
temprory4=           h_geocode      dist  cell
19  120150103011068  0.748813    10
RHS= 120150103011068
C000= 3.0
cell_remain= 7
n1= 531
temprory4=             h_geocode      dist  cell
2223  120210108082020  0.328649    17
RHS= 120210108082020
C000= 1.0
cell_remain= 16
n1= 532
temprory4=            h_geocode      dist  cell
882  120150302021027  0.593401     2
RHS= 120150302021027
C000= 1.0
cell_remain= 1
n1= 533
temprory4=             h_geocode      dist  cell
2618  120710403151040  2.963613     9
RHS= 120710403151040
C000= 7.0
cell_remain= 2
n1= 534
temprory4=              h_geocode      dist  cell
12546  121150027421020  0.905375     3
RHS= 121150027421020
C000= 1.0
cell_remain= 2
n1= 535
temprory4=            h_geocode      dist  cell
282  120150301012006  0.696712     5
RHS= 120150301012006
C000= 4.0
cell_remain= 1
n1= 536
temprory4=             h_geocode      dist  cell
7483  121150027462135  0.821295     6
RHS= 121150027462135
C000= 5.0
cell_remain= 1
n1= 537
temprory4=             h_geocode      dist  cell
8582  120810014061039  0.185315     3
RHS= 120810014061039
C000= 1.0
cell_remain= 2
n1= 538
temprory4=             h_geocode      dist  cell
1514  120710104172001  0.337455   180
RHS= 120710104172001
C000= 9.0
cell_remain= 171
n1= 539
temprory4=             h_geocode      dist  cell
2973  120710403101007  4.203788     7
RHS= 120710403101007
C000= 6.0
cell_remain= 1
n1= 540
temprory4=            h_geocode      dist  cell
318  120150204021105  0.608837     3
RHS= 120150204021105
C000= 2.0
cell_remain= 1
n1= 541
temprory4=             h_geocode      dist  cell
4939  120710503221030  0.406569     7
RHS= 120710503221030
C000= 3.0
cell_remain= 4
n1= 542
temprory4=            h_geocode     dist  cell
644  120710101102007  1.15425   139
RHS= 120710101102007
C000= 20.0
cell_remain= 119
n1= 543
temprory4=            h_geocode      dist  cell
115  120150202061035  1.112925     8
RHS= 120150202061035
C000= 5.0
cell_remain= 3
n1= 544
temprory4=             h_geocode      dist  cell
3783  120810014051010  0.370667    11
RHS= 120810014051010
C000= 7.0
cell_remain= 4
n1= 545
temprory4=            h_geocode      dist  cell
621  120150209001003  0.308126     3
RHS= 120150209001003
C000= 1.0
cell_remain= 2
n1= 546
temprory4=             h_geocode      dist  cell
1282  120210105082007  0.041717    10
RHS= 120210105082007
C000= 3.0
cell_remain= 7
n1= 547
temprory4=              h_geocode      dist  cell
12718  121150027442125  0.285085     2
RHS= 121150027442125
C000= 1.0
cell_remain= 1
n1= 548
temprory4=             h_geocode      dist  cell
5252  120810011072010  0.302586   120
RHS= 120810011072010
C000= 4.0
cell_remain= 116
n1= 549
temprory4=             h_geocode      dist  cell
2192  120810018021004  0.313772    95
RHS= 120810018021004
C000= 13.0
cell_remain= 82
n1= 550
temprory4=            h_geocode      dist  cell
880  120150302021038  0.317993     5
RHS= 120150302021038
C000= 1.0
cell_remain= 4
n1= 551
temprory4=             h_geocode      dist  cell
4308  120710402101015  0.417827     6
RHS= 120710402101015
C000= 3.0
cell_remain= 3
n1= 552
temprory4=             h_geocode     dist  cell
8154  121150020163012  0.35194     6
RHS= 121150020163012
C000= 3.0
cell_remain= 3
n1= 553
temprory4=           h_geocode      dist  cell
18  120150105052006  4.997887    17
RHS= 120150105052006
C000= 6.0
cell_remain= 11
n1= 554
temprory4=             h_geocode      dist  cell
7304  121150027381107  0.091415     9
RHS= 121150027381107
C000= 5.0
cell_remain= 4
n1= 555
temprory4=             h_geocode      dist  cell
5000  120710402102048  1.196332     3
RHS= 120710402102048
C000= 2.0
cell_remain= 1
n1= 556
temprory4=             h_geocode      dist  cell
2895  120710019101013  0.598633     2
RHS= 120710019101013
C000= 1.0
cell_remain= 1
n1= 557
temprory4=            h_geocode      dist  cell
178  120150204011032  0.345765    15
RHS= 120150204011032
C000= 4.0
cell_remain= 11
n1= 558
temprory4=           h_geocode     dist  cell
18  120150210032021  3.14897    38
RHS= 120150210032021
C000= 36.0
cell_remain= 2
n1= 559
temprory4=             h_geocode      dist  cell
6489  121150027352012  0.222926    11
RHS= 121150027352012
C000= 6.0
cell_remain= 5
n1= 560
temprory4=             h_geocode      dist  cell
2426  120710019161004  0.841895     3
RHS= 120710019161004
C000= 2.0
cell_remain= 1
n1= 561
temprory4=             h_geocode      dist  cell
6289  120710403081026  0.359742     2
RHS= 120710403081026
C000= 1.0
cell_remain= 1
n1= 562
temprory4=            h_geocode     dist  cell
111  120150105052073  3.57521     3
RHS= 120150105052073
C000= 1.0
cell_remain= 2
n1= 563
temprory4=           h_geocode      dist  cell
99  120150305012069  1.108953    15
RHS= 120150305012069
C000= 9.0
cell_remain= 6
n1= 564
temprory4=             h_geocode      dist  cell
2338  120810013002018  0.293131    40
RHS= 120810013002018
C000= 12.0
cell_remain= 28
n1= 565
temprory4=            h_geocode      dist  cell
972  120150305011029  0.712612     2
RHS= 120150305011029
C000= 1.0
cell_remain= 1
n1= 566
temprory4=           h_geocode      dist  cell
57  120150305013025  0.700862    46
RHS= 120150305013025
C000= 13.0
cell_remain= 33
n1= 567
temprory4=             h_geocode      dist  cell
2414  120710019131009  0.831912   110
RHS= 120710019131009
C000= 2.0
cell_remain= 108
n1= 568
temprory4=             h_geocode      dist  cell
8264  120810010022000  0.513933    92
RHS= 120810010022000
C000= 1.0
cell_remain= 91
n1= 569
temprory4=             h_geocode      dist  cell
9597  121150001022001  0.309239     2
RHS= 121150001022001
C000= 1.0
cell_remain= 1
n1= 570
temprory4=            h_geocode      dist  cell
297  120150305071038  0.250974     6
RHS= 120150305071038
C000= 5.0
cell_remain= 1
n1= 571
temprory4=             h_geocode        dist  cell
1221  120210110033012  142.369394    10
RHS= 120210110033012
C000= 5.0
cell_remain= 5
n1= 572
temprory4=             h_geocode      dist  cell
7167  121150005033006  0.152532     6
RHS= 121150005033006
C000= 3.0
cell_remain= 3
n1= 573
temprory4=            h_geocode      dist  cell
945  120150304011049  0.252366     2
RHS= 120150304011049
C000= 1.0
cell_remain= 1
n1= 574
temprory4=             h_geocode      dist  cell
7448  120810002032018  0.224699     7
RHS= 120810002032018
C000= 1.0
cell_remain= 6
n1= 575
temprory4=             h_geocode      dist  cell
6217  120810003143003  0.288501     4
RHS= 120810003143003
C000= 2.0
cell_remain= 2
n1= 576
temprory4=             h_geocode      dist  cell
1508  121150005031032  0.704629    23
RHS= 121150005031032
C000= 22.0
cell_remain= 1
n1= 577
temprory4=             h_geocode      dist  cell
5938  120710402092013  0.371512     2
RHS= 120710402092013
C000= 1.0
cell_remain= 1
n1= 578
temprory4=             h_geocode      dist  cell
7194  120710506031027  0.286352     7
RHS= 120710506031027
C000= 1.0
cell_remain= 6
n1= 579
temprory4=              h_geocode      dist  cell
10636  121150018012014  0.091783     8
RHS= 121150018012014
C000= 1.0
cell_remain= 7
n1= 580
temprory4=             h_geocode      dist  cell
7289  121150027381018  0.365994     7
RHS= 121150027381018
C000= 5.0
cell_remain= 2
n1= 581
temprory4=             h_geocode      dist  cell
4466  120710702012023  0.395816    53
RHS= 120710702012023
C000= 4.0
cell_remain= 49
n1= 582
temprory4=             h_geocode      dist  cell
3412  121150007002035  0.334264    22

RHS= 121150007002035
C000= 10.0
cell_remain= 12
n1= 583
temprory4=             h_geocode      dist  cell
3361  121150002003024  0.603929    15
RHS= 121150002003024
C000= 10.0
cell_remain= 5
n1= 584
temprory4=             h_geocode      dist  cell
2590  120710005022027  0.187061     2
RHS= 120710005022027
C000= 1.0
cell_remain= 1
n1= 585
temprory4=             h_geocode      dist  cell
2607  120710403101010  5.961197     8
RHS= 120710403101010
C000= 7.0
cell_remain= 1
n1= 586
temprory4=             h_geocode      dist  cell
8004  121150027311003  0.909615     9
RHS= 121150027311003
C000= 4.0
cell_remain= 5
n1= 587
temprory4=              h_geocode      dist  cell
12857  121150027462357  1.030548     2
RHS= 121150027462357
C000= 1.0
cell_remain= 1
n1= 588
temprory4=             h_geocode      dist  cell
4475  120710403081133  2.829942     4
RHS= 120710403081133
C000= 3.0
cell_remain= 1
n1= 589
temprory4=            h_geocode      dist  cell
921  120150303011028  0.176477     2
RHS= 120150303011028
C000= 1.0
cell_remain= 1
n1= 590
temprory4=             h_geocode      dist  cell
7432  120810019103003  0.203938     3
RHS= 120810019103003
C000= 2.0
cell_remain= 1
n1= 591
temprory4=            h_geocode      dist  cell
925  120210101023010  0.149182     3
RHS= 120210101023010
C000= 2.0
cell_remain= 1
n1= 592
temprory4=             h_geocode      dist  cell
5266  120710403121061  0.757895     4
RHS= 120710403121061
C000= 2.0
cell_remain= 2
n1= 593
temprory4=            h_geocode      dist  cell
252  120150304022010  1.870262    72
RHS= 120150304022010
C000= 5.0
cell_remain= 67
n1= 594
temprory4=             h_geocode        dist  cell
2327  120210110033021  151.562293     5
RHS= 120210110033021
C000= 1.0
cell_remain= 4
n1= 595
temprory4=           h_geocode      dist  cell
23  120150105052048  1.045951     6
RHS= 120150105052048
C000= 5.0
cell_remain= 1
n1= 596
temprory4=           h_geocode      dist  cell
61  120150204013025  3.144822    21
RHS= 120150204013025
C000= 9.0
cell_remain= 12

In [129]:
select_2030_hgeocode_geo4_3_1_geo2.rename(columns = {'cell':'cell_x','geometry_x':'geometry_x1','geometry_y':'geometry_y1'}, inplace = True)
select_2030_hgeocode_geo4_3_1_geo2

,h_geocode,geometry_x1,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS18,CNS19,CNS20,cell_x,w_geocode,geometry_y1,dist,centr_x_co,h_geocode_x,dist_x
0,120879718001022,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",4.0,1.0,2.0,1.0,3.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",0.631994,"(24.567331297140306, -81.73018543710354)",120210110032007,148.643301
89,120879717003014,"POLYGON ((-81.67570 24.60202, -81.67570 24.602...",8.0,2.0,4.0,2.0,7.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.66069 24.60108, -81.66053 24.601...",1.129322,"(24.599937349116697, -81.66874555206641)",120210110032009,145.201288
192,120710201031017,"POLYGON ((-81.90898 26.72997, -81.90881 26.729...",2.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.207102e+14,"POLYGON ((-81.90026 26.73959, -81.90024 26.739...",0.95799,"(26.727752498586256, -81.89952848815554)",120710201021019,0.56111
260,120879715011003,"POLYGON ((-81.50261 24.66138, -81.50261 24.661...",2.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.48056 24.66379, -81.48054 24.664...",0.735556,"(24.66276660460335, -81.48720077363569)",120879715021034,2.953606
346,120710103052003,"POLYGON ((-81.91549 26.64060, -81.91547 26.644...",19.0,4.0,8.0,7.0,16.0,3.0,0.0,0.0,...,2.0,1.0,0.0,0.0,1.207101e+14,"POLYGON ((-81.91040 26.64691, -81.90886 26.646...",0.441576,"(26.643469872107385, -81.91235912964126)",120710103082013,1.612062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,120710403122096,"POLYGON ((-81.62359 26.54015, -81.62357 26.540...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.205701e+14,None,NaN,"(26.539100061105547, -81.6231019415148)",120710403121061,0.757895
6203,120150304022029,"POLYGON ((-82.28716 26.82583, -82.28708 26.825...",5.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN,"(26.825418608381277, -82.28636504224013)",120150304022010,1.870262
6204,120879725002054,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.208600e+14,None,NaN,"(24.54895967349272, -81.80399944673492)",120210110033021,151.562293
6206,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",5.0,0.0,2.0,3.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,"(26.86072744671804, -82.0168655661004)",120150105052048,1.045951
6207,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,1.209502e+14,None,NaN,"(27.004866401536365, -82.20261830319743)",120150204013025,3.144822

In [130]:
select_2030_hgeocode_geo4_3_1_geo2[select_2030_hgeocode_geo4_3_1_geo2['h_geocode']==10030102001033]

Empty GeoDataFrame
Columns: [h_geocode, geometry_x1, C000, CA01, CA02, CA03, CR01, CR02, CR03, CR04, CR05, CR07, CE01, CE02, CE03, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, cell_x, w_geocode, geometry_y1, dist, centr_x_co, h_geocode_x, dist_x]
Index: []

[0 rows x 50 columns]

In [131]:
select_2030_hgeocode_geo4_3_1_geo2.rename(columns = {'cell':'cell_x','geometry_x':'geometry_x1','geometry_y':'geometry_y1'}, inplace = True)
select_2030_hgeocode_geo4_3_1_geo2

,h_geocode,geometry_x1,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS18,CNS19,CNS20,cell_x,w_geocode,geometry_y1,dist,centr_x_co,h_geocode_x,dist_x
0,120879718001022,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",4.0,1.0,2.0,1.0,3.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",0.631994,"(24.567331297140306, -81.73018543710354)",120210110032007,148.643301
89,120879717003014,"POLYGON ((-81.67570 24.60202, -81.67570 24.602...",8.0,2.0,4.0,2.0,7.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.66069 24.60108, -81.66053 24.601...",1.129322,"(24.599937349116697, -81.66874555206641)",120210110032009,145.201288
192,120710201031017,"POLYGON ((-81.90898 26.72997, -81.90881 26.729...",2.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.207102e+14,"POLYGON ((-81.90026 26.73959, -81.90024 26.739...",0.95799,"(26.727752498586256, -81.89952848815554)",120710201021019,0.56111
260,120879715011003,"POLYGON ((-81.50261 24.66138, -81.50261 24.661...",2.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.48056 24.66379, -81.48054 24.664...",0.735556,"(24.66276660460335, -81.48720077363569)",120879715021034,2.953606
346,120710103052003,"POLYGON ((-81.91549 26.64060, -81.91547 26.644...",19.0,4.0,8.0,7.0,16.0,3.0,0.0,0.0,...,2.0,1.0,0.0,0.0,1.207101e+14,"POLYGON ((-81.91040 26.64691, -81.90886 26.646...",0.441576,"(26.643469872107385, -81.91235912964126)",120710103082013,1.612062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,120710403122096,"POLYGON ((-81.62359 26.54015, -81.62357 26.540...",2.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.205701e+14,None,NaN,"(26.539100061105547, -81.6231019415148)",120710403121061,0.757895
6203,120150304022029,"POLYGON ((-82.28716 26.82583, -82.28708 26.825...",5.0,0.0,5.0,0.0,5.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN,"(26.825418608381277, -82.28636504224013)",120150304022010,1.870262
6204,120879725002054,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.208600e+14,None,NaN,"(24.54895967349272, -81.80399944673492)",120210110033021,151.562293
6206,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",5.0,0.0,2.0,3.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,"(26.86072744671804, -82.0168655661004)",120150105052048,1.045951
6207,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,...,3.0,0.0,0.0,0.0,1.209502e+14,None,NaN,"(27.004866401536365, -82.20261830319743)",120150204013025,3.144822

In [132]:
select_2030_hgeocode_geo4_3_1_geo2.rename(columns = {'h_geocode':'h_geocode_y'}, inplace = True)

In [133]:
select_2030_hgeocode_geo4_3_1_geo2 = select_2030_hgeocode_geo4_3_1_geo2.drop(['centr_x_co'], axis =1 )

In [134]:
select_hgeocode_geo5_6_

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS19,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,dist_x
0,1.207100e+14,1.207104e+14,120710012051002,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.761567,120710401171000,434.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",5.447355
23,1.201501e+14,1.201501e+14,120150103013009,3.0,0.0,2.0,1.0,3.0,0.0,0.0,...,0.0,0.0,1.0,1.511083,120150104053012,492.0,"POLYGON ((-82.05398 26.88800, -82.05390 26.888...","POLYGON ((-82.07083 26.90300, -82.07082 26.903...","POLYGON ((-82.08442 26.89855, -82.08441 26.898...",1.034546
175,1.208100e+14,1.208100e+14,120810001052013,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.392701,120810008121002,13.0,"POLYGON ((-82.56297 27.47066, -82.56096 27.470...","POLYGON ((-82.55892 27.46871, -82.55892 27.468...","POLYGON ((-82.54662 27.47652, -82.54662 27.476...",1.811006
265,1.208100e+14,1.208100e+14,120810003131000,2.0,0.0,1.0,1.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.910628,120810008053004,133.0,"POLYGON ((-82.56310 27.44031, -82.56257 27.440...","POLYGON ((-82.56307 27.43159, -82.56275 27.431...","POLYGON ((-82.53010 27.39671, -82.53005 27.396...",5.404398
271,1.208100e+14,1.208100e+14,120810003051007,14.0,3.0,7.0,4.0,12.0,2.0,0.0,...,0.0,0.0,0.0,0.597262,120810003042007,29.0,"POLYGON ((-82.55490 27.44363, -82.55488 27.444...","POLYGON ((-82.55493 27.45132, -82.55481 27.451...","POLYGON ((-82.56123 27.44769, -82.56034 27.447...",1.009383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2485434,1.208100e+14,1.208100e+14,120810019163004,3.0,0.0,2.0,1.0,3.0,0.0,0.0,...,0.0,0.0,1.0,11.587041,120810001053014,60.0,"POLYGON ((-82.51255 27.58683, -82.51128 27.588...","POLYGON ((-82.56547 27.49466, -82.56543 27.495...","POLYGON ((-82.57124 27.47295, -82.57124 27.473...",2.609075
2487289,1.208797e+14,1.208797e+14,120879714011032,16.0,0.0,16.0,0.0,16.0,0.0,0.0,...,0.0,1.0,0.0,0.899217,120879710012039,96.0,"POLYGON ((-81.35092 24.67245, -81.35092 24.672...","POLYGON ((-81.36233 24.67438, -81.36080 24.674...","POLYGON ((-81.01974 24.72897, -81.01960 24.729...",35.182148
2487615,1.208100e+14,1.208100e+14,120810020183029,12.0,2.0,4.0,6.0,11.0,1.0,0.0,...,0.0,0.0,0.0,5.033827,120810020121004,35.0,"POLYGON ((-82.42543 27.48683, -82.42515 27.486...","POLYGON ((-82.45919 27.44140, -82.45919 27.442...","POLYGON ((-82.46830 27.44550, -82.46819 27.445...",0.783195
2487829,1.208100e+14,1.208100e+14,120810007043047,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.99863,120810001053014,60.0,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...","POLYGON ((-82.56678 27.47713, -82.56306 27.477...","POLYGON ((-82.57124 27.47295, -82.57124 27.473...",0.594089
2487940,1.208100e+14,1.208100e+14,120810014051003,9.0,0.0,4.0,5.0,9.0,0.0,0.0,...,0.0,0.0,0.0,6.283759,120810016041008,16.0,"POLYGON ((-82.57562 27.52858, -82.57510 27.528...","POLYGON ((-82.55469 27.57930, -82.55467 27.579...","POLYGON ((-82.54383 27.56064, -82.54383 27.560...",2.554003

In [135]:
len(select_2030_hgeocode_geo4_3_1_geo2)

597

In [136]:
import pandas as pd 
select_hgeocode_geo5_6=pd.concat([select_hgeocode_geo5_6_, select_2030_hgeocode_geo4_3_1_geo2], axis=0)
len(select_hgeocode_geo5_6)

9085

In [137]:
select_hgeocode_geo5_6['C000'].sum()

45389.0

In [138]:
Emp_home_select_2030_new_values_merge_s['C000'].sum() #if the out of this cell = the out of previous cell (correct)

45389.0

In [139]:
select_hgeocode_geo5_6 = select_hgeocode_geo5_6.astype({"C000":'int64',"CNS01":'int64',"CNS02":'int64',"CNS03":'int64',
                                                       "CNS04":'int64',"CNS05":'int64',"CNS06":'int64',"CNS07":'int64',
                                                       "CNS08":'int64',"CNS09":'int64',"CNS10":'int64',"CNS11":'int64',
                                                       "CNS12":'int64',"CNS13":'int64',"CNS14":'int64',"CNS15":'int64',
                                                       "CNS16":'int64',"CNS17":'int64',"CNS18":'int64',"CNS19":'int64',
                                                       "CNS20":'int64', "CR01":'int64','CR02':'int64' ,'CR03' :'int64',
                                                       "CR04" :'int64', "CR05":'int64','CR07':'int64' ,"CA01" :'int64',
                                                       "CA02" :'int64',"CA03" :'int64',"CE01":'int64' ,"CE02" :'int64',
                                                       "CE03" :'int64',"CT01" :'int64',"CT02":'int64' ,"CD01" :'int64',
                                                       "CD02" :'int64',"CD03" :'int64',"CD04":'int64' ,"CS01" :'int64',
                                                       "CS02" :'int64'})

In [140]:
select_hgeocode_geo5_6

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS19,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,dist_x
0,1.207100e+14,120710401171000.0,120710012051002,1,0,1,0,1,0,0,...,0,0,0.0,0.761567,1.207104e+14,434.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",5.447355
23,1.201501e+14,120150104053012.0,120150103013009,3,0,2,1,3,0,0,...,0,0,1.0,1.511083,1.201501e+14,492.0,"POLYGON ((-82.05398 26.88800, -82.05390 26.888...","POLYGON ((-82.07083 26.90300, -82.07082 26.903...","POLYGON ((-82.08442 26.89855, -82.08441 26.898...",1.034546
175,1.208100e+14,120810008121002.0,120810001052013,1,0,1,0,1,0,0,...,0,0,0.0,0.392701,1.208100e+14,13.0,"POLYGON ((-82.56297 27.47066, -82.56096 27.470...","POLYGON ((-82.55892 27.46871, -82.55892 27.468...","POLYGON ((-82.54662 27.47652, -82.54662 27.476...",1.811006
265,1.208100e+14,120810008053004.0,120810003131000,2,0,1,1,2,0,0,...,0,0,0.0,0.910628,1.208100e+14,133.0,"POLYGON ((-82.56310 27.44031, -82.56257 27.440...","POLYGON ((-82.56307 27.43159, -82.56275 27.431...","POLYGON ((-82.53010 27.39671, -82.53005 27.396...",5.404398
271,1.208100e+14,120810003042007.0,120810003051007,14,3,7,4,12,2,0,...,0,0,0.0,0.597262,1.208100e+14,29.0,"POLYGON ((-82.55490 27.44363, -82.55488 27.444...","POLYGON ((-82.55493 27.45132, -82.55481 27.451...","POLYGON ((-82.56123 27.44769, -82.56034 27.447...",1.009383
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6201,1.205701e+14,120710403121061,120710403122096,2,0,2,0,2,0,0,...,0,0,0.0,NaN,NaN,NaN,"POLYGON ((-81.62359 26.54015, -81.62357 26.540...",None,None,0.757895
6203,1.209901e+14,120150304022010,120150304022029,5,0,5,0,5,0,0,...,0,0,0.0,NaN,NaN,NaN,"POLYGON ((-82.28716 26.82583, -82.28708 26.825...",None,None,1.870262
6204,1.208600e+14,120210110033021,120879725002054,1,0,0,1,0,1,0,...,0,0,0.0,NaN,NaN,NaN,"POLYGON ((-81.80466 24.54960, -81.80444 24.549...",None,None,151.562293
6206,1.206105e+14,120150105052048,120150105052077,5,0,2,3,5,0,0,...,0,0,0.0,NaN,NaN,NaN,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",None,None,1.045951
6207,1.209502e+14,120150204013025,120150204022186,9,0,9,0,9,0,0,...,0,0,0.0,NaN,NaN,NaN,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",None,None,3.144822

In [141]:
# Emp_cells = Emp_cells_2030_old.copy()

In [142]:
Emp_cells

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
360,120150201011010,1898.0,491767073,76VV2X3Q+JV7-3-3-4-4,120150201012010,RES,RES1-1SNB,W,1.0,1999.0,...,0.18,0.08,-82.010330,27.004031,NaN,5.329113,17.483967,POINT (-82.01033 27.00403),015,1
379,120150202061034,1938.0,491915584,76VV2VFQ+CPH-4-2-3-3,120150202021046,RES,RES1-1SNB,W,1.0,1657.0,...,0.18,0.08,-82.110648,27.023557,NaN,4.227000,13.868111,POINT (-82.11065 27.02356),015,1
385,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.18,0.08,-82.306143,26.923544,NaN,3.585037,11.761934,POINT (-82.30614 26.92354),015,1
386,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.13,0.03,-81.728035,25.913643,NaN,3.590633,11.780292,POINT (-81.72803 25.91364),021,1
393,120810020212027,1973.0,492122842,76VVCHV3+323-4-5-4-4,120810020072028,RES,RES1-1SNB,W,1.0,2784.0,...,0.17,0.04,-82.447449,27.442633,NaN,11.965964,39.258414,POINT (-82.44745 27.44263),081,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544324,120710303001023,7362124.0,498226804,76RWP93W+264-0-0-0-0,120710303001022,RES,RES1-1SNB,W,1.0,510.0,...,0.17,0.05,-81.604428,26.702522,NaN,3.825020,12.549277,POINT (-81.60443 26.70252),071,1
2544591,120710302011004,7362643.0,498226048,76RWM7W6+V2V-0-0-0-0,120710302011005,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.739960,26.697237,AE,2.931039,9.616270,POINT (-81.73996 26.69724),071,1
2544592,120710302011004,7362644.0,498226050,76RWM7V5+6PJ-0-0-0-0,120710302011017,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.740725,26.693076,AE,3.146635,10.323605,POINT (-81.74073 26.69308),071,1
2544599,120710302012002,7362651.0,498226064,76RWM7R5+3WR-0-0-0-0,120710302011024,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.740242,26.690234,AE,1.498931,4.917752,POINT (-81.74024 26.69023),071,1
2544610,120710302011004,7362662.0,498226086,76RWM7X8+8GX-0-0-0-0,120710302011005,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.733640,26.698365,NaN,3.087558,10.129784,POINT (-81.73364 26.69836),071,1

In [143]:
Emp_cells2 =Emp_cells

In [144]:
# Emp_cells= Emp_cells.drop(['min_2030'],axis=1)

In [145]:
# Emp_cells2=Emp_cells2.drop(['row_num'],axis=1)

In [146]:
Emp_cells2 =  Emp_cells2.dropna(subset=['h_geocode'])
len(Emp_cells2)

331127

In [147]:
Emp_cells2 =  Emp_cells2.dropna(subset=['fd_id'])
len(Emp_cells2)

331127

In [148]:
Emp_cells2 = Emp_cells2.drop_duplicates(subset=['fd_id'])
len(Emp_cells2)

331127

In [149]:
Emp_cells2 = Emp_cells2.astype({"h_geocode":'int64',"fd_id":'int64'})

In [150]:
import pandas as pd
file = '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/DepthDamageFunction.xlsx'
xl = pd.ExcelFile(file)
print(xl.sheet_names)
WD_Coast = xl.parse('RES(Coastline)')

WD_Coast_final= WD_Coast.iloc[1:30,1:60].squeeze() #Buildings water damages

['RES(Riverline)', 'Other(Riverline)', 'RES(Coastline)', 'Sheet1', 'Sheet9', 'Recovery']

In [151]:
WD_Coast_final = WD_Coast_final.astype('float64')

In [152]:
# WD_Coast_final.to_pickle("WD_Coast_final.pkl")

In [153]:
select_hgeocode_geo5_6['C000'].sum()

45389

In [154]:
select_hgeocode_geo5_6['h_geocode_y']

0       120710012051002
23      120150103013009
175     120810001052013
265     120810003131000
271     120810003051007
             ...
6201    120710403122096
6203    120150304022029
6204    120879725002054
6206    120150105052077
6207    120150204022186
Name: h_geocode_y, Length: 9085, dtype: int64

In [155]:
select_hgeocode_geo5_6['h_geocode_y']

0       120710012051002
23      120150103013009
175     120810001052013
265     120810003131000
271     120810003051007
             ...
6201    120710403122096
6203    120150304022029
6204    120879725002054
6206    120150105052077
6207    120150204022186
Name: h_geocode_y, Length: 9085, dtype: int64

In [156]:
# select_hgeocode_geo5_6_try = select_hgeocode_geo5_6.drop_duplicates(subset=['h_geocode_x'])
# len(select_hgeocode_geo5_6_try)

In [157]:
select_hgeocode_geo5_6['h_geocode_x']

0       120710401171000.0
23      120150104053012.0
175     120810008121002.0
265     120810008053004.0
271     120810003042007.0
              ...
6201      120710403121061
6203      120150304022010
6204      120210110033021
6206      120150105052048
6207      120150204013025
Name: h_geocode_x, Length: 9085, dtype: object

In [158]:
select_hgeocode_geo5_6['h_geocode_x']

0       120710401171000.0
23      120150104053012.0
175     120810008121002.0
265     120810008053004.0
271     120810003042007.0
              ...
6201      120710403121061
6203      120150304022010
6204      120210110033021
6206      120150105052048
6207      120150204013025
Name: h_geocode_x, Length: 9085, dtype: object

In [159]:
Emp_cells2['fd_id'].max()

498226804

In [160]:
# select_hgeocode_geo5_6 = select_hgeocode_geo5_6.drop(['level_0'], axis = 1)

select_hgeocode_geo5_6 = select_hgeocode_geo5_6.reset_index()

In [161]:

select_hgeocode_geo5_6 = select_hgeocode_geo5_6.drop(['index'],axis=1)

In [162]:
dataframes_temp={}


# list of data frames
# Assume that the original dataframe is named 'original_df'
for i in range(0, 1): #0,90
    dataframes_temp[i] = select_hgeocode_geo5_6.copy()
    
# Convert the dictionary to a list of tuples
dataframes = list(dataframes_temp.values())
    

for k in range(0, 1):# 0,90
    dataframes[k] = dataframes[k].rename("{}_{}".format("{}_a",k).format)

# dictionary to save data frames
select_hgeocode_geo5_6_dic2_cells={} 

for key1, value1 in enumerate(dataframes):    
#     print('key1',key1)
#     print('value1',value1)

    select_hgeocode_geo5_6_dic2_cells[key1] = value1 # assigning data frame from list to key in dictionary

In [163]:
Emp_cells2 = Emp_cells2.reset_index()
Emp_cells2 = Emp_cells2.drop(['index'],axis=1)

In [164]:

dataframes_cells_temp={}


# list of data frames
# Assume that the original dataframe is named 'original_df'
for i in range(0, 1): #0,90
    dataframes_cells_temp[i] = Emp_cells2.copy()
    
# Convert the dictionary to a list of tuples
dataframes_cells = list(dataframes_cells_temp.values())
    

for k in range(0, 1): #0,90
    dataframes_cells[k] = dataframes_cells[k].rename("{}_{}".format("{}_a",k).format)

# dictionary to save data frames
Emp_cells2_dic={} 

for key1, value1 in enumerate(dataframes_cells):    
#     print('key1',key1)
#     print('value1',value1)

    Emp_cells2_dic[key1] = value1 # assigning data frame from list to key in dictionary

In [165]:
len(Emp_cells2_dic[0])

331127

In [166]:
len(Emp_cells2_dic[0]['fd_id'].unique())

331127

In [167]:

# for i in range(0,1):
#     Emp_cells2_dic[i] = Emp_cells2_dic[i][['h_geocode','fd_id','cell','geometry']]

In [168]:
import warnings
warnings.filterwarnings("ignore")

In [169]:
Emp_cells2['fd_id'].max()

498226804

In [170]:
def cells_calc_x_cells(Emp_home, Emp_cells):
    import time
    from scipy.interpolate import interp1d
    from iteration_utilities import deepflatten
    import random
    start = time.time()
    

    for i in range(0,len(Emp_home)):
        print('i=',i)
    

        temp22=[]
        temp30 = [[498226819,498226820,498226821]] #one number after Emp_cells2['row_num'].max()
        # temp25 = {}
        my_list = []
        my_dicts = {}
        Emp_home[i]['cells_used'] = ''
        for q in range (0,len(Emp_home[i])):
            temp22_1 = Emp_cells[i][Emp_cells[i]['h_geocode']== Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("h_geocode_x")]]
            list_temp30 = list(deepflatten(temp30, depth=1))
            temp22 = temp22_1.loc[~temp22_1['fd_id'].isin(list_temp30)]
            temp23 = sorted(temp22['fd_id'])
            if len(temp23) == 0:
#                 print('temp23=',temp23)
                temp24 = temp23
#                 print('len(temp24)=', len(temp24))
            if Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")] > len(temp23):
                temp24 = temp23
            else:
                temp24 = random.sample(population=temp23, k=Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")])
                temp24 = sorted(temp24)
            temp25 = temp22.loc[temp22['fd_id'].isin(temp24)]
            temp30.append(temp24)

            my_list.append(temp25)
            pd.DataFrame(Emp_home[i]).iloc[q,Emp_home[i].columns.get_loc("cells_used")]= len(temp24)

        cells2_2030=temp30 
        
    end = time.time()
    print(end - start)
    return cells2_2030
        
#         for key, value in en

In [171]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [172]:
def cells_calc_x(i, Emp_home, Emp_cells, cells2_2030):
    import time
    from scipy.interpolate import interp1d
    from iteration_utilities import deepflatten
#     start = time.time()
    
    
#     my_list_2=[]
#     my_list_3=[]
#     my_list_4=[]

#     for i in range(0,len(Emp_home)):   # 0 , len(Emp_home)
#     print('i=',i)


    temp22=[]
    temp30 = [[498226819,498226820,498226821]] #one number after Emp_cells2['row_num'].max()
    # temp25 = {}
    my_list = []
#         my_list_2=[]
#         my_list_3=[]
    my_dicts = {}
    Emp_home['cells_used'] = ''
    for q in range (0,len(Emp_home)):
        temp22_1 = Emp_cells[Emp_cells['h_geocode']== Emp_home.iloc[q,Emp_home.columns.get_loc("h_geocode_x")]]
        list_temp30 = list(deepflatten(temp30, depth=1))
        temp22 = temp22_1.loc[~temp22_1['fd_id'].isin(list_temp30)]
        temp23 = sorted(temp22['fd_id'])
        temp24 = cells2_2030[1:][q]
        temp25 = temp22.loc[temp22['fd_id'].isin(temp24)]
        temp30.append(temp24)
        my_list.append(temp25)
        pd.DataFrame(Emp_home).iloc[q,Emp_home.columns.get_loc("cells_used")]= len(temp24)

    for key, value in enumerate(my_list):
        my_dicts[key] = value

    Emp_home['C000_dmg']=''
    Emp_home['C000_dmg_mean']=''
    result_temp1 = []
    temp26 = []
    temp26_2 = []
    temp26_4 = []
    result_2 = []
    result_3 = []
    result_4 = []
    for k in range (0,len(Emp_home)):
        result_1 = []
        for value in my_dicts[k]["min_2030"]:
            result_temp1= value
            result_1.append(result_temp1)
        my_dicts[k]["SLR"] = result_1 #maybe replace result_1 with min_2030 (we don't need the previous 3 lines)
        my_dicts[k]['damage_SLR']=''
        for j in range(0, len(my_dicts[k])):
#                 print('row_num=', pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("row_num")])
#                 print('SLR=',pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] )
            if pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] == 0:
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = 0
            elif pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] > 7:
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = 100
            else: 
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = interp1d(WD_Coast_final['Depth.1']+pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("found_ht")]*0.3048,WD_Coast_final['R11N'],
                                                           bounds_error=False, fill_value=(0,1))(pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")])
#                 print('damage=',pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] )


        my_dicts[k] = my_dicts[k].astype({"damage_SLR":'float'})
        temp26 = len(my_dicts[k][my_dicts[k]["damage_SLR"]>50]) # damage is larger than 50%
        result_2.append(temp26)
        temp26_2 = (my_dicts[k][my_dicts[k]["damage_SLR"]>50])["damage_SLR"].mean()
        result_3.append(temp26_2)
        temp26_4 =my_dicts[k]["damage_SLR"]
        result_4.append(temp26_4)
    my_list_2.append(result_2)
    my_list_3.append(result_3)
    my_list_4.append(result_4)

#     end = time.time()
#     print(end - start)
    return my_list_2, my_list_3,my_list_4

In [173]:
# cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)

In [174]:
import os
from iteration_utilities import deepflatten

if os.path.exists('cells2_2030_for{0}.pickle'.format(year_1)):
    cells2_2030_temp = pd.read_pickle('cells2_2030_for{0}.pickle'.format(year_1))
    select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_cells_for{0}_Renters.pickle'.format(year_1))
    cells2_2030_temp2= cells2_2030_temp.values.tolist()
    
    cells2_2030=[]
    for i in range(0,len(cells2_2030_temp2)):
        df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
        df_temp = df_temp.astype(int)
        cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
        cells2_2030.append(cells2_2030_temp3)
    
else:
    cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
    pd.DataFrame(cells2_2030).to_pickle('cells2_2030_for{0}.pickle'.format(year_1))
    select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_cells_for{0}_Renters.pickle'.format(year_1))

i= 0
30.235286712646484

In [175]:
# select_hgeocode_geo5_6_dic2_cells[0]['C000']

In [176]:
# select_hgeocode_geo5_6_dic2_cells[0]['C000'].sum()

In [177]:
# select_hgeocode_geo5_6_dic2_cells[0]['cells_used'].sum()

In [178]:

from iteration_utilities import deepflatten

list_cells2_2030 = list(deepflatten(cells2_2030[1:], depth=1))

In [179]:
len(pd.DataFrame(list_cells2_2030)[0].unique())

34246

In [180]:
from iteration_utilities import deepflatten

list_cells2_2030 = list(deepflatten(cells2_2030, depth=1))
Emp_cells2_2030_dic_find = {}
for i in range(0, len(Emp_cells2_dic)):
    Emp_cells2_2030_dic_find[i] = Emp_cells2_dic[i].loc[Emp_cells2_dic[i]['fd_id'].isin(list_cells2_2030)]
len(Emp_cells2_2030_dic_find[0])

34246

In [181]:
Emp_cells2_2030_dic_find[0]

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
2_a_0,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.18,0.08,-82.306143,26.923544,NaN,3.585037,11.761934,POINT (-82.30614 26.92354),015,1
3_a_0,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.13,0.03,-81.728035,25.913643,NaN,3.590633,11.780292,POINT (-81.72803 25.91364),021,1
20_a_0,121150006021025,2554.0,494920398,76VV8F6F+8G4-2-3-2-3,121150006021027,RES,RES1-1SNB,W,1.0,1436.0,...,0.17,0.05,-82.526172,27.310759,NaN,5.999467,19.683291,POINT (-82.52617 27.31076),115,1
30_a_0,120210106041005,2691.0,495489665,76RW46MQ+RGF-0-0-0-0,120210106043008,RES,RES1-1SNB,W,1.0,1270.0,...,0.13,0.03,-81.761196,26.134560,NaN,1.580856,5.186536,POINT (-81.76120 26.13456),021,1
74_a_0,120150101001064,794179.0,491656542,76RWV7FJ+H84-4-3-5-3,120150101001001,RES,RES1-1SNB,M,1.0,1056.0,...,0.18,0.08,-81.719182,26.873877,D,10.465429,34.335399,POINT (-81.71918 26.87388),015,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331109_a_0,120710402061002,7361637.0,498226301,76RWM8V6+FMJ-0-0-0-0,120710402061013,RES,RES1-1SNB,M,1.0,1646.0,...,0.17,0.05,-81.688349,26.693718,NaN,5.160393,16.930423,POINT (-81.68835 26.69372),071,1
331118_a_0,120710303001002,7361737.0,498226412,76RWPC88+6Q9-0-0-0-0,120710303001001,RES,RES1-1SNB,M,1.0,1278.0,...,0.17,0.05,-81.583024,26.715525,AE,2.445596,8.023611,POINT (-81.58302 26.71553),071,1
331119_a_0,120710303001002,7361738.0,498226414,76RWPC78+PQW-0-0-0-0,120710303001001,RES,RES1-1SNB,M,1.0,1278.0,...,0.17,0.05,-81.583053,26.714367,AE,1.147627,3.765179,POINT (-81.58305 26.71437),071,1
331120_a_0,120710303001002,7361745.0,498226794,76RWPC68+98M-0-0-0-0,120710303001001,RES,RES1-1SNB,M,1.0,1278.0,...,0.17,0.05,-81.584193,26.710973,NaN,4.383068,14.380144,POINT (-81.58419 26.71097),071,1
331121_a_0,120710303001002,7361746.0,498226796,76RWPC68+9WM-0-0-0-0,120710303001001,RES,RES1-1SNB,M,1.0,1278.0,...,0.17,0.05,-81.582714,26.710963,NaN,4.133729,13.562103,POINT (-81.58271 26.71096),071,1

In [182]:
Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find[0][['fd_id','geometry']]
Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find_1.reset_index()
Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find_1.drop(['index'],axis=1)
Emp_cells2_2030_dic_find_1

           fd_id                    geometry
0      492073948  POINT (-82.30614 26.92354)
1      492083201  POINT (-81.72803 25.91364)
2      494920398  POINT (-82.52617 27.31076)
3      495489665  POINT (-81.76120 26.13456)
4      491656542  POINT (-81.71918 26.87388)
...          ...                         ...
34241  498226301  POINT (-81.68835 26.69372)
34242  498226412  POINT (-81.58302 26.71553)
34243  498226414  POINT (-81.58305 26.71437)
34244  498226794  POINT (-81.58419 26.71097)
34245  498226796  POINT (-81.58271 26.71096)

[34246 rows x 2 columns]

In [183]:
zs2_dic_0 = Emp_cells2_2030_dic_find_1.copy()
zs2_dic_0 = zs2_dic_0.drop(['geometry'],axis=1)
zs2_dic_0.rename(columns={'row_num':'min'}, inplace=True)
zs2_dic_0['min']=0.0
zs2_dic_0

           fd_id  min
0      492073948  0.0
1      492083201  0.0
2      494920398  0.0
3      495489665  0.0
4      491656542  0.0
...          ...  ...
34241  498226301  0.0
34242  498226412  0.0
34243  498226414  0.0
34244  498226794  0.0
34245  498226796  0.0

[34246 rows x 2 columns]

In [184]:
# Create an empty list
zs2_dic_0_list = []

# Iterate over each row in the DataFrame
for index, row in zs2_dic_0.iterrows():
    # Append a dictionary to the list with the 'min' key and the row value
    zs2_dic_0_list.append({'min': row['min']})

In [185]:
# Get the list of all pickle file paths
Raster_file_paths = []
for k in range(0,6): 
    if k==2 or k==3 or k==4:
        continue
    else:
        print('k=',k)
        for x in range(0,40): 
            Raster_file_path = '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_{0}_{1}.tif'.format(k,x)
            Raster_file_paths.append(Raster_file_path)

# for i in range(0,1): #0,90
#     cell_open_read2[i] = pd.read_pickle(pickle_file_paths[i])

k= 0
k= 1
k= 5

In [186]:
len(Raster_file_paths)

120

In [187]:
#list_iterate is the number of hazards to be skipped calculations (zonal stats)

list_iterate=[]
for l in range(0,len(Raster_file_paths),8):
    list_iterate.append(l)
    list_iterate.append(l+1)
    list_iterate.append(l+2)
    list_iterate.append(l+3)
    list_iterate.append(l+4)
    list_iterate.append(l+5)
    list_iterate.append(l+6)

In [188]:
# list_iterate

In [189]:
for l in range(0,len(Raster_file_paths)):
    if l in list_iterate:
        print('yes')
    else:
        print(l)

yes
yes
yes
yes
yes
yes
yes
7
yes
yes
yes
yes
yes
yes
yes
15
yes
yes
yes
yes
yes
yes
yes
23
yes
yes
yes
yes
yes
yes
yes
31
yes
yes
yes
yes
yes
yes
yes
39
yes
yes
yes
yes
yes
yes
yes
47
yes
yes
yes
yes
yes
yes
yes
55
yes
yes
yes
yes
yes
yes
yes
63
yes
yes
yes
yes
yes
yes
yes
71
yes
yes
yes
yes
yes
yes
yes
79
yes
yes
yes
yes
yes
yes
yes
87
yes
yes
yes
yes
yes
yes
yes
95
yes
yes
yes
yes
yes
yes
yes
103
yes
yes
yes
yes
yes
yes
yes
111
yes
yes
yes
yes
yes
yes
yes
119

In [190]:
Raster_file_paths_new=[]
for i in range(0,len(Raster_file_paths)):
    if i not in list_iterate:
        Raster_file_paths_new_temp=Raster_file_paths[i]
        Raster_file_paths_new.append(Raster_file_paths_new_temp)

In [191]:
Raster_file_paths_new

['/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_7.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_15.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_23.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_31.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_39.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_7.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_15.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_23.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_31.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_39.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_7.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_15.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_23.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_31.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_39.tif']

In [192]:
new_list=[]
for i in range(0,len(Raster_file_paths)):
    if i not in list_iterate:
        new_list_temp=i
        new_list.append(new_list_temp)

In [193]:
new_list

[7, 15, 23, 31, 39, 47, 55, 63, 71, 79, 87, 95, 103, 111, 119]

In [194]:
from rasterstats import zonal_stats
import time
from joblib import Parallel, delayed
import joblib

def worker(i, Raster_file_paths_new, Emp_cells2_2030_dic_find_1):
    return zonal_stats(Emp_cells2_2030_dic_find_1, Raster_file_paths_new[i], stats=['min'])

def main():
    global zs2_dic
    zs2_dic = {}

    start = time.time()

    num_cores = joblib.cpu_count()
    results = Parallel(n_jobs=5)(delayed(worker)(i, Raster_file_paths_new, Emp_cells2_2030_dic_find_1) for i in range(0,len(Raster_file_paths_new)))

    # The 'retrieve' argument returns the results from all the jobs as soon as they are ready.
    zs2_dic = dict(enumerate(results))

    end = time.time()
    print(end - start)

    return zs2_dic

if __name__ == "__main__":
    zs2_dic = main()
#     print(zs2_dic)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

153.26885509490967

In [195]:
# from rasterstats import zonal_stats
# import time

# zs2_dic = {}

# start = time.time()
# for k in range(0,len(Raster_file_paths_new)):
#     print('k=',k)
# #     if k in list_iterate:
# #         print('Skipped')
# #         zs2_dic[k] = zs2_dic_0_list
# #     else:
#     zs2_dic[k] = zonal_stats(Emp_cells2_2030_dic_find_1, Raster_file_paths_new[k],
#                     stats=['min'])
# end = time.time()
# print(end - start)

In [196]:
len(pd.DataFrame(list_cells2_2030)[0].unique())

34249

In [197]:
import pandas as pd

import time

Emp_cells2_2030_dic_find_1_dic = {}
demstats_df2_dic = {}

start = time.time()
for k in range(0,len(Raster_file_paths_new)):
    print('k=',k)
    demstats_df2_dic[k] = pd.DataFrame(zs2_dic[k])
    demstats_df2_dic[k].rename(columns={'min':'min_2030'}, inplace=True)
    Emp_cells2_2030_dic_find_1_dic[k] = pd.concat([Emp_cells2_2030_dic_find_1, demstats_df2_dic[k]], axis=1)
    
end = time.time()
print(end - start)

k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.10875916481018066

In [198]:
# Emp_cells2_2030_dic_find_1_dic[89][Emp_cells2_2030_dic_find_1_dic[89]['min_2030']>0]

In [199]:
# Emp_cells2_2030_dic_find_1_dic[719].to_file('Emp_cells2_2030_dic_find_1_dic_719.shp')

In [200]:
import geopandas as gpd
#To read shapefile
fp13 = "/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/FL_Levee_polygon_min_H_calc.shp"
Emp_home_levee = gpd.read_file(fp13)

In [201]:
Emp_home_levee =  Emp_home_levee[['min_ht','geometry']]

In [202]:
cell_open_read3={}

for i in range(0,len(Raster_file_paths_new)):
    cell_open_read3[i] = Emp_cells2_2030_dic_find_1_dic[i][['min_2030','fd_id']]

In [203]:
Emp_cells2_dic[0].head()

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
0_a_0,120150201011010,1898.0,491767073,76VV2X3Q+JV7-3-3-4-4,120150201012010,RES,RES1-1SNB,W,1.0,1999.0,...,0.18,0.08,-82.010330,27.004031,NaN,5.329113,17.483967,POINT (-82.01033 27.00403),015,1
1_a_0,120150202061034,1938.0,491915584,76VV2VFQ+CPH-4-2-3-3,120150202021046,RES,RES1-1SNB,W,1.0,1657.0,...,0.18,0.08,-82.110648,27.023557,NaN,4.227000,13.868111,POINT (-82.11065 27.02356),015,1
2_a_0,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.18,0.08,-82.306143,26.923544,NaN,3.585037,11.761934,POINT (-82.30614 26.92354),015,1
3_a_0,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.13,0.03,-81.728035,25.913643,NaN,3.590633,11.780292,POINT (-81.72803 25.91364),021,1
4_a_0,120810020212027,1973.0,492122842,76VVCHV3+323-4-5-4-4,120810020072028,RES,RES1-1SNB,W,1.0,2784.0,...,0.17,0.04,-82.447449,27.442633,NaN,11.965964,39.258414,POINT (-82.44745 27.44263),081,1

In [204]:
# Emp_cells2_dic[0] = Emp_cells2_dic[0].drop(['min_2030'],axis=1)

In [205]:
Emp_cells2_dic_filter = {}
for i in range(0,1):
    Emp_cells2_dic_filter[i]=Emp_cells2_dic[i][['h_geocode','fd_id','found_ht','geometry','cell']]

In [206]:
import pandas as pd

Emp_cells2_dic2={}

for i in range(0,len(Raster_file_paths_new)):#0,90
    Emp_cells2_dic2[i] = pd.merge(Emp_cells2_dic_filter[0], cell_open_read3[i],  how='left', 
                    left_on=['fd_id'], right_on = ['fd_id'])

In [207]:
Emp_select_levee_120 = gpd.sjoin(Emp_cells2_dic2[len(Emp_cells2_dic2)-1], Emp_home_levee, op="intersects", how='left')
Emp_select_levee_120.head()

,h_geocode,fd_id,found_ht,geometry,cell,min_2030,index_right,min_ht
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN,NaN,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN,NaN,NaN
2,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,0.893456,NaN,NaN
3,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,4.462747,NaN,NaN
4,120810020212027,492122842,0.5,POINT (-82.44745 27.44263),1,NaN,NaN,NaN

In [208]:
Emp_select_levee_120[~Emp_select_levee_120['min_ht'].isna()][
    ~Emp_select_levee_120[~Emp_select_levee_120['min_ht'].isna()]
['min_2030'].isna()]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030,index_right,min_ht
16102,120210111072004,492089488,1.5,POINT (-81.03316 25.85731),1,0.0,44.0,7.4501

In [209]:
del Emp_select_levee_120

In [210]:
del cell_open_read3

In [211]:
del Emp_cells2_dic_filter

In [212]:
Emp_cells2_dic2[1]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,0.0
3,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,0.0
4,120810020212027,492122842,0.5,POINT (-82.44745 27.44263),1,NaN
...,...,...,...,...,...,...
331122,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
331123,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
331124,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
331125,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
331126,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [213]:
Emp_cells2['geometry'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [214]:
# Emp_cells2[Emp_cells2['row_num']==162935]['geometry'][128557]

In [215]:
Emp_cells2_2030_dic_find_1

           fd_id                    geometry
0      492073948  POINT (-82.30614 26.92354)
1      492083201  POINT (-81.72803 25.91364)
2      494920398  POINT (-82.52617 27.31076)
3      495489665  POINT (-81.76120 26.13456)
4      491656542  POINT (-81.71918 26.87388)
...          ...                         ...
34241  498226301  POINT (-81.68835 26.69372)
34242  498226412  POINT (-81.58302 26.71553)
34243  498226414  POINT (-81.58305 26.71437)
34244  498226794  POINT (-81.58419 26.71097)
34245  498226796  POINT (-81.58271 26.71096)

[34246 rows x 2 columns]

In [216]:
# Emp_cells2_2030_dic_find_1.to_pickle('Emp_cells2_2030_dic_find_1.pickle')

In [217]:
def check_input_type(input):
    if isinstance(input, pd.DataFrame):
        return True
    elif isinstance(input, dict):
        return False
    else:
        return False
# checking input types
check_input_type(select_hgeocode_geo5_6)

True

In [218]:
def find_cells_SLR(select_hgeocode_geo5_6, Emp_cells2):
    from iteration_utilities import deepflatten
    from rasterstats import zonal_stats
    import time
    import os


    dataframes_temp={}



    # list of data frames
    for i in range(0, 1): #0,90
        dataframes_temp[i] = select_hgeocode_geo5_6.copy()

    # Convert the dictionary to a list of tuples
    dataframes = list(dataframes_temp.values())

    for k in range(0, 1):# 0,90
        dataframes[k] = dataframes[k].rename("{}_{}".format("{}_a",k).format)

    # dictionary to save data frames
    select_hgeocode_geo5_6_dic2_cells={} 

    for key1, value1 in enumerate(dataframes):    
        select_hgeocode_geo5_6_dic2_cells[key1] = value1 # assigning data frame from list to key in dictionary
        
     
    Emp_cells2 = Emp_cells2.reset_index()
    Emp_cells2 = Emp_cells2.drop(['index'],axis=1)
    
    Emp_cells2= Emp_cells2.drop(['min_2030'],axis=1)
    
    
    dataframes_cells_temp={}


    # list of data frames
    for i in range(0, 1): #0,90
        dataframes_cells_temp[i] = Emp_cells2.copy()

    # Convert the dictionary to a list of tuples
    dataframes_cells = list(dataframes_cells_temp.values())


    for k in range(0, 1): #0,90
        dataframes_cells[k] = dataframes_cells[k].rename("{}_{}".format("{}_a",k).format)

    # dictionary to save data frames
    Emp_cells2_dic={} 

    for key1, value1 in enumerate(dataframes_cells):    
        Emp_cells2_dic[key1] = value1 # assigning data frame from list to key in dictionary


#     for i in range(0,1):
#         Emp_cells2_dic[i] = Emp_cells2_dic[i][['h_geocode','row_num','cell','geometry']]
    
    if 'h_geocode_x' in select_hgeocode_geo5_6.columns:
        print('Yes')
        
        if 'loop_num' in select_hgeocode_geo5_6.columns:
            
            loop_num = select_hgeocode_geo5_6['loop_num'][0]


            if os.path.exists('cells2_2030_1_try{1}_for{0}.pickle'.format(year_1,loop_num)):
                cells2_2030_temp = pd.read_pickle('cells2_2030_1_try{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_cells{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
                cells2_2030_temp2= cells2_2030_temp.values.tolist()

                cells2_2030=[]
                for i in range(0,len(cells2_2030_temp2)):
                    df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                    df_temp = df_temp.astype(int)
                    cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                    cells2_2030.append(cells2_2030_temp3)
            else:
                cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
                pd.DataFrame(cells2_2030).to_pickle('cells2_2030_1_try{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_cells{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
        
        
        elif 'loop_num_2' in select_hgeocode_geo5_6.columns:
            
            loop_num = select_hgeocode_geo5_6['loop_num_2'][0]


            if os.path.exists('cells2_2030_3_try{1}_for{0}.pickle'.format(year_1,loop_num)):
                cells2_2030_temp = pd.read_pickle('cells2_2030_3_try{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_cells__{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
                cells2_2030_temp2= cells2_2030_temp.values.tolist()

                cells2_2030=[]
                for i in range(0,len(cells2_2030_temp2)):
                    df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                    df_temp = df_temp.astype(int)
                    cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                    cells2_2030.append(cells2_2030_temp3)
            else:
                cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
                pd.DataFrame(cells2_2030).to_pickle('cells2_2030_3_try{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_cells__{1}_for{0}_Renters.pickle'.format(year_1,loop_num))

        elif 'loop_num_3' in select_hgeocode_geo5_6.columns:
            
            loop_num = select_hgeocode_geo5_6['loop_num_3'][0]


            if os.path.exists('cells2_2030_4_{1}_for{0}.pickle'.format(year_1,loop_num)):
                cells2_2030_temp = pd.read_pickle('cells2_2030_4_{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_cells_4_{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
                cells2_2030_temp2= cells2_2030_temp.values.tolist()

                cells2_2030=[]
                for i in range(0,len(cells2_2030_temp2)):
                    df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                    df_temp = df_temp.astype(int)
                    cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                    cells2_2030.append(cells2_2030_temp3)
            else:
                cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
                pd.DataFrame(cells2_2030).to_pickle('cells2_2030_4_{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_cells_4_{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
        
        else: 
            if os.path.exists('cells2_2030_3_for{0}.pickle'.format(year_1)):
                cells2_2030_temp = pd.read_pickle('cells2_2030_3_for{0}.pickle'.format(year_1))
                select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_3cells_for{0}_Renters.pickle'.format(year_1))
                cells2_2030_temp2= cells2_2030_temp.values.tolist()

                cells2_2030=[]
                for i in range(0,len(cells2_2030_temp2)):
                    df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                    df_temp = df_temp.astype(int)
                    cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                    cells2_2030.append(cells2_2030_temp3)
            else:
                cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
                pd.DataFrame(cells2_2030).to_pickle('cells2_2030_3_for{0}.pickle'.format(year_1))
                select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_3cells_for{0}_Renters.pickle'.format(year_1))


                
    else: 
        print('No')
        if os.path.exists('cells2_2030_2_for{0}.pickle'.format(year_1)):
            cells2_2030_temp = pd.read_pickle('cells2_2030_2_for{0}.pickle'.format(year_1))
            select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_2cells_for{0}_Renters.pickle'.format(year_1))
            cells2_2030_temp2= cells2_2030_temp.values.tolist()
    
            cells2_2030=[]
            for i in range(0,len(cells2_2030_temp2)):
                df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                df_temp = df_temp.astype(int)
                cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                cells2_2030.append(cells2_2030_temp3)
        else:
            cells2_2030 =  cells_calc_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
            pd.DataFrame(cells2_2030).to_pickle('cells2_2030_2_for{0}.pickle'.format(year_1))
            select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_2cells_for{0}_Renters.pickle'.format(year_1))
    
    print('your here 1')
    
    
    list_cells2_2030 = list(deepflatten(cells2_2030[1:], depth=1))
    
    Emp_cells2_2030_dic_find = {}
    for i in range(0, len(Emp_cells2_dic)):
        Emp_cells2_2030_dic_find[i] = Emp_cells2_dic[i].loc[Emp_cells2_dic[i]['fd_id'].isin(list_cells2_2030)]    
    Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find[0][['fd_id','geometry']]
    Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find_1.reset_index()
    Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find_1.drop(['index'],axis=1)
    
    print('your here 2')

    zs2_dic_0 = Emp_cells2_2030_dic_find_1.copy()
    zs2_dic_0 = zs2_dic_0.drop(['geometry'],axis=1)
    zs2_dic_0.rename(columns={'fd_id':'min'}, inplace=True)
    zs2_dic_0['min']=0.0
    # Create an empty list
    zs2_dic_0_list = []

    # Iterate over each row in the DataFrame
    for index, row in zs2_dic_0.iterrows():
        # Append a dictionary to the list with the 'min' key and the row value
        zs2_dic_0_list.append({'min': row['min']})

    
    zs2_dic = {}

    def worker(i, Raster_file_paths_new, Emp_cells2_2030_dic_find_1):
        return zonal_stats(Emp_cells2_2030_dic_find_1, Raster_file_paths_new[i], stats=['min'])
    
    def main():
        global zs2_dic
        zs2_dic = {}

        start = time.time()

        num_cores = joblib.cpu_count()
        results = Parallel(n_jobs=num_cores)(delayed(worker)(i, Raster_file_paths_new, Emp_cells2_2030_dic_find_1) for i in range(0,len(Raster_file_paths_new)))

        # The 'retrieve' argument returns the results from all the jobs as soon as they are ready.
        zs2_dic = dict(enumerate(results))

        end = time.time()
        print(end - start)

        return zs2_dic

    if __name__ == "__main__":
        zs2_dic = main()
    
    print('your here 3')

    
    Emp_cells2_2030_dic_find_1_dic = {}
    demstats_df2_dic = {}

    start = time.time()
    for k in range(0,len(Raster_file_paths_new)):
        print('k=',k)
        demstats_df2_dic[k] = pd.DataFrame(zs2_dic[k])
        demstats_df2_dic[k].rename(columns={'min':'min_2030'}, inplace=True)
        Emp_cells2_2030_dic_find_1_dic[k] = pd.concat([Emp_cells2_2030_dic_find_1, demstats_df2_dic[k]], axis=1)

    end = time.time()
    print(end - start)
    
    cell_open_read3={}

    for i in range(0,len(Raster_file_paths_new)):
        cell_open_read3[i] = Emp_cells2_2030_dic_find_1_dic[i][['min_2030','fd_id']]
        
    Emp_cells2_dic2={}
    Emp_select_levee_120={}

    for i in range(0,len(Raster_file_paths_new)):#0,90
        Emp_cells2_dic2[i] = pd.merge(Emp_cells2_dic[0], cell_open_read3[i],  how='left', 
                        left_on=['fd_id'], right_on = ['fd_id'])
        
        
    for i in range(0,len(Raster_file_paths_new)):#0,90
        Emp_select_levee_120[i] = gpd.sjoin(Emp_cells2_dic2[i], Emp_home_levee, op="intersects", how='left')
        Emp_select_levee_120[i]['zero']=0
        mask = Emp_select_levee_120[i]['min_ht'] > Emp_select_levee_120[i]['min_2030']
    
        # Update the 'min_2030' column with the values from 'min_ht' where the mask is True
        Emp_select_levee_120[i].loc[mask, 'min_2030'] = Emp_select_levee_120[i].loc[mask, 'zero']
        Emp_select_levee_120[i]=Emp_select_levee_120[i].drop(['index_right','min_ht','zero'],axis=1)
        
        Emp_cells2_dic2[i] = Emp_select_levee_120[i].copy()
        
        
    del Emp_select_levee_120
        

    del cell_open_read3
        
    dataframes2_temp={}

    if check_input_type(select_hgeocode_geo5_6_dic2_cells) :
        
        select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.reset_index()

        if 'index' in select_hgeocode_geo5_6_dic2_cells.columns:
            select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.drop(['index'],axis=1)
        if 'level_0' in select_hgeocode_geo5_6_dic2_cells.columns:
            select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.drop(['level_0'],axis=1)

        # list of data frames
        # Assume that the original dataframe is named 'original_df'
        for i in range(0, len(new_list)):
            dataframes2_temp[i] = select_hgeocode_geo5_6_dic2_cells.copy()

        
    else:

        select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].reset_index()

        if 'index' in select_hgeocode_geo5_6_dic2_cells[0].columns:
            select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].drop(['index'],axis=1)
        if 'level_0' in select_hgeocode_geo5_6_dic2_cells[0].columns:
            select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].drop(['level_0'],axis=1)

        # list of data frames
        # Assume that the original dataframe is named 'original_df'
        for i in range(0, len(Raster_file_paths_new)):
            dataframes2_temp[i] = select_hgeocode_geo5_6_dic2_cells[0].copy()

    # Convert the dictionary to a list of tuples
    dataframes2 = list(dataframes2_temp.values())

    for k in range(0, len(Raster_file_paths_new)):
        dataframes2[k] = dataframes2[k].rename("{}_{}".format("{}_a",k).format)

    # dictionary to save data frames
    select_hgeocode_geo5_6_dic2_cells_dic={} 

    for key2, value2 in enumerate(dataframes2):    
        select_hgeocode_geo5_6_dic2_cells_dic[key2] = value2 # assigning data frame from list to key in dictionary
        
        
        
        
    return Emp_cells2_dic2, cells2_2030, select_hgeocode_geo5_6_dic2_cells_dic

In [219]:
# Emp_cells2_dic2 = find_cells_SLR(select_hgeocode_geo5_6, Emp_cells2)

In [220]:
len(dataframes_temp)

1

In [221]:
dataframes_temp={}

if check_input_type(select_hgeocode_geo5_6_dic2_cells) :

    select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.reset_index()

    if 'index' in select_hgeocode_geo5_6_dic2_cells.columns:
        select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.drop(['index'],axis=1)
    if 'level_0' in select_hgeocode_geo5_6_dic2_cells.columns:
        select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.drop(['level_0'],axis=1)

    # list of data frames
    # Assume that the original dataframe is named 'original_df'
    for i in range(0, len(new_list)):
        dataframes_temp[i] = select_hgeocode_geo5_6_dic2_cells.copy()


else:

    select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].reset_index()

    if 'index' in select_hgeocode_geo5_6_dic2_cells[0].columns:
        select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].drop(['index'],axis=1)
    if 'level_0' in select_hgeocode_geo5_6_dic2_cells[0].columns:
        select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].drop(['level_0'],axis=1)

    # list of data frames
    # Assume that the original dataframe is named 'original_df'
    for i in range(0, len(Raster_file_paths_new)):
        dataframes_temp[i] = select_hgeocode_geo5_6_dic2_cells[0].copy()
    
# Convert the dictionary to a list of tuples
dataframes = list(dataframes_temp.values())
    

for k in range(0, len(Raster_file_paths_new)):# 0,90
    dataframes[k] = dataframes[k].rename("{}_{}".format("{}_a",k).format)

# dictionary to save data frames
select_hgeocode_geo5_6_dic2={} 

for key1, value1 in enumerate(dataframes):    
#     print('key1',key1)
#     print('value1',value1)

    select_hgeocode_geo5_6_dic2[key1] = value1 # assigning data frame from list to key in dictionary

In [222]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [223]:
Emp_cells2_dic2[0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,0.0
3,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,0.0
4,120810020212027,492122842,0.5,POINT (-82.44745 27.44263),1,NaN
...,...,...,...,...,...,...
331122,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
331123,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
331124,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
331125,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
331126,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [224]:
from joblib import Parallel, delayed

my_list_2=[]
my_list_3=[]
my_list_4=[]

start = time.time()


# Step 3: Use the provided code snippet to parallelize the calculations using the 'worker' function
result = Parallel(n_jobs=5)(delayed(cells_calc_x)(i, select_hgeocode_geo5_6_dic2[i], Emp_cells2_dic2[i], cells2_2030) for i in range(0,len(Raster_file_paths_new)))

# Convert the result to a dictionary with keys as indices
zs2_dic = dict(enumerate(result))

# Step 4: After calculating the results, retrieve the values from the 'zs2_dic' dictionary and store them in the lists 'my_list_2', 'my_list_3', and 'my_list_4'
my_list_2 = [zs2_dic[i][0] for i in range(len(Raster_file_paths_new))]
my_list_3 = [zs2_dic[i][1] for i in range(len(Raster_file_paths_new))]
my_list_4 = [zs2_dic[i][2] for i in range(len(Raster_file_paths_new))]

end = time.time()
print(end - start)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

184.49457812309265

In [225]:
# my_list_2, my_list_3,my_list_4 =  cells_calc_x(select_hgeocode_geo5_6_dic2,Emp_cells2_dic2,cells2_2030)

In [226]:
len(select_hgeocode_geo5_6_dic2[0])

9085

In [227]:
len(cells2_2030)

9086

In [228]:
len(my_list_2[0])

1

In [229]:
my_list_2_final={}
my_list_3_final={}
my_list_4_final={}

for l in range(0,len(Raster_file_paths_new)):
    my_list_2_final[l]= my_list_2[l][0]
    my_list_3_final[l]= my_list_3[l][0]
    my_list_4_final[l]= my_list_4[l][0]

In [230]:
my_list_2={}
my_list_3={}
my_list_4={}

In [231]:
def list_4_calc(my_list_4,cells2_2030_2,Emp_cells2_try4_dic2):
    my_list_4_test3=[]
    for k in range(0,len(my_list_4)):
        my_list_4_test2=[]
        for i in range(0,len(my_list_4[k])):
            if len(my_list_4[k][i])==0:
                continue
            else:
                temo_list= list(deepflatten(my_list_4[k][i], depth=1))
                my_list_4_test2.append(temo_list)
        my_list_4_test3.append(my_list_4_test2)
        
    my_list_4_test4=[]
    for k in range(0,len(my_list_4)):
        my_list_4_test4_temp = list(deepflatten(my_list_4_test3[k], depth=1))
        my_list_4_test4.append(my_list_4_test4_temp)
    
    cells2_2030_2_list = list(deepflatten(cells2_2030_2[1:], depth=1))

    
    df_test=[]
    df_test = pd.DataFrame({'fd_id': cells2_2030_2_list})
    # Loop through the list of lists and add each list as a new column in the DataFrame
    for i, list_1 in enumerate(my_list_4_test4):
        df_test[f'damage{i}'] = list_1
        
    Emp_cells2_try4_dic2_test2 = Emp_cells2_try4_dic2[0][Emp_cells2_try4_dic2[0]['fd_id'].isin(df_test['fd_id'])]

    Emp_cells2_try4_dic2_test_final = pd.merge(Emp_cells2_try4_dic2_test2, df_test,  how='left', 
                        left_on=['fd_id'], right_on = ['fd_id']) 
    
    return Emp_cells2_try4_dic2_test_final

In [232]:
# Emp_cells2_dic2[719][Emp_cells2_dic2[719]['row_num']==5046 ]

In [233]:
Emp_cells2_dic_list4 =list_4_calc(my_list_4_final,cells2_2030,Emp_cells2_dic)

In [234]:
# Emp_cells2_dic_list4[Emp_cells2_dic_list4['damage89']>0]

In [235]:
# Emp_cells2_dic_list4[Emp_cells2_dic_list4['fd_id']==499824024]['found_ht']

In [236]:
# Emp_cells2_2030_dic_find_1_dic[28][Emp_cells2_2030_dic_find_1_dic[28]['fd_id']==499824024]

In [237]:
# Emp_cells2_2030_dic_find_1_dic[10][Emp_cells2_2030_dic_find_1_dic[10]['fd_id']==499824024]

In [238]:
# Emp_cells2_dic_list4[Emp_cells2_dic_list4['fd_id']==499824024].to_csv('499824024.csv')

In [239]:
def custom_sort(col):
    base = int(col.lstrip('damage'))
    if col[0] == 'd':
        return base
    else:
        return float('inf')

In [240]:
# def list4_2_full (Emp_cells2_dic_list4_2):
#     Emp_cells2_dic_list4_2_modify = Emp_cells2_dic_list4_2.copy()

#     for k in range(0,len(my_list_4)):
#         Emp_cells2_dic_list4_2_modify= Emp_cells2_dic_list4_2_modify.drop(['damage{0}'.format(k)],axis=1)

#     Emp_cells2_dic_list4_2_modify

#     for index, i in enumerate(new_list):
#     #     print(f"i: {i}, j: {index+1}")
#         Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = Emp_cells2_dic_list4_2['damage{0}'.format(index)]

#     for i in list_iterate:
#         Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = 0
#     Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify.iloc[:,33:]
#     Emp_cells2_dic_list4_2_modify_select2 = Emp_cells2_dic_list4_2_modify.iloc[:,:33]

#     sorted_columns = sorted(Emp_cells2_dic_list4_2_modify_select.columns, key=custom_sort)
#     sorted_Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify_select[sorted_columns]

#     Emp_cells2_dic_list4_2 = pd.concat([ Emp_cells2_dic_list4_2_modify_select2,sorted_Emp_cells2_dic_list4_2_modify_select],axis=1)

#     return Emp_cells2_dic_list4_2

In [241]:
# Emp_cells2_dic_list4 = list4_2_full(Emp_cells2_dic_list4)

In [242]:
Emp_cells2_dic_list4

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage5,damage6,damage7,damage8,damage9,damage10,damage11,damage12,damage13,damage14
0,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,17.826245,55.741721
1,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.0,0.0,0.0,0.000000,0.000000,23.189341,37.594087,79.50681,100.000000,100.000000
2,121150006021025,2554.0,494920398,76VV8F6F+8G4-2-3-2-3,121150006021027,RES,RES1-1SNB,W,1.0,1436.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
3,120210106041005,2691.0,495489665,76RW46MQ+RGF-0-0-0-0,120210106043008,RES,RES1-1SNB,W,1.0,1270.0,...,0.0,0.0,0.0,15.936725,52.108027,100.000000,100.000000,100.00000,100.000000,100.000000
4,120150101001064,794179.0,491656542,76RWV7FJ+H84-4-3-5-3,120150101001001,RES,RES1-1SNB,M,1.0,1056.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34241,120710402061002,7361637.0,498226301,76RWM8V6+FMJ-0-0-0-0,120710402061013,RES,RES1-1SNB,M,1.0,1646.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,23.381956
34242,120710303001002,7361737.0,498226412,76RWPC88+6Q9-0-0-0-0,120710303001001,RES,RES1-1SNB,M,1.0,1278.0,...,0.0,0.0,0.0,0.000000,0.000000,100.000000,100.000000,100.00000,100.000000,100.000000
34243,120710303001002,7361738.0,498226414,76RWPC78+PQW-0-0-0-0,120710303001001,RES,RES1-1SNB,M,1.0,1278.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,17.053065,54.254829
34244,120710303001002,7361745.0,498226794,76RWPC68+98M-0-0-0-0,120710303001001,RES,RES1-1SNB,M,1.0,1278.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
34245,120710303001002,7361746.0,498226796,76RWPC68+9WM-0-0-0-0,120710303001001,RES,RES1-1SNB,M,1.0,1278.0,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,31.028986

In [243]:

dataframes3_list_2_temp={}
dataframes3_list_3_temp={}


for k in range(0, len(new_list)):
    dataframes3_list_2_temp[k] = pd.DataFrame(my_list_2_final[k]).copy()
    dataframes3_list_3_temp[k] = pd.DataFrame(my_list_3_final[k]).copy()    
    
dataframes3_list_2 = list(dataframes3_list_2_temp.values())
dataframes3_list_3 = list(dataframes3_list_3_temp.values())


for k in range(0, len(new_list)):
    dataframes3_list_2[k] = dataframes3_list_2[k].rename("{}_{}".format("{}_a",k).format)
    dataframes3_list_3[k] = dataframes3_list_3[k].rename("{}_{}".format("{}_a",k).format)

In [244]:
# dictionary to save data frames
my_dicts_2={}
my_dicts_3={} 

for key_list2, value_list2 in enumerate(dataframes3_list_2):    
    my_dicts_2[key_list2] = value_list2 # assigning data frame from list to key in dictionary
for key_list3, value_list3 in enumerate(dataframes3_list_3):    
    my_dicts_3[key_list3] = value_list3 # assigning data frame from list to key in dictionary

In [245]:
for i in range(0,len(select_hgeocode_geo5_6_dic2)):
    select_hgeocode_geo5_6_dic2[i]['C000_dmg'] = my_dicts_2[i]
    select_hgeocode_geo5_6_dic2[i]['C000_dmg_mean'] = my_dicts_3[i]

In [246]:
len(select_hgeocode_geo5_6_dic2)

15

In [247]:
# select_hgeocode_geo5_6_dic2[89][select_hgeocode_geo5_6_dic2[89]['C000_dmg']>0]['C000_dmg'].sum()

In [248]:
# def dataframe_full (select_hgeocode_geo5_6_dic2):

#     select_hgeocode_geo5_6_dic2_full={}

#     for index, i in enumerate(new_list):
#         #     print(f"i: {i}, j: {index+1}")
#             select_hgeocode_geo5_6_dic2_full[i] = select_hgeocode_geo5_6_dic2[index]


#     for i in list_iterate:
#             select_hgeocode_geo5_6_dic2_full[i] = select_hgeocode_geo5_6_dic2[0].copy()
#             select_hgeocode_geo5_6_dic2_full[i]['C000_dmg'] = 0
#             select_hgeocode_geo5_6_dic2_full[i]['C000_dmg_mean'] = 0
#     return select_hgeocode_geo5_6_dic2_full

In [249]:
# select_hgeocode_geo5_6_dic2_full = dataframe_full(select_hgeocode_geo5_6_dic2)

In [250]:
select_hgeocode_geo5_6_dic2[0]['C000'].sum()

45389

In [251]:
select_hgeocode_geo5_6_dic2[0]['cells_used'].sum()

34246

In [252]:
len(Emp_cells2_dic2[0])

331127

In [253]:

from iteration_utilities import deepflatten

list_cells2_2030 = list(deepflatten(cells2_2030, depth=1))
Emp_cells2_2030_dic = {}
for i in range(0, 1):
    Emp_cells2_2030_dic[i] = Emp_cells2_dic2[i].loc[~Emp_cells2_dic2[i]['fd_id'].isin(list_cells2_2030)]
len(Emp_cells2_2030_dic[0])

296881

In [254]:
Emp_cells2_2030_dic[0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
4,120810020212027,492122842,0.5,POINT (-82.44745 27.44263),1,NaN
5,120810020101000,492164773,0.5,POINT (-82.12509 27.35222),1,NaN
6,120810020101000,492165521,0.5,POINT (-82.11979 27.44118),1,NaN
...,...,...,...,...,...,...
331122,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
331123,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
331124,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
331125,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
331126,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [255]:
select_hgeocode_geo5_6_dic2[0]['C000'].sum()

45389

In [256]:
len(Emp_cells2_dic2[0]) - len(Emp_cells2_2030_dic[0])

34246

In [257]:
len(Emp_cells2_dic[0])-len(Emp_cells2_2030_dic[0])

34246

In [258]:
select_hgeocode_geo5_6_dic2[0][select_hgeocode_geo5_6_dic2[0]['C000']<0]

Empty DataFrame
Columns: [w_geocode, h_geocode_x, h_geocode_y, C000, CA01, CA02, CA03, CR01, CR02, CR03, CR04, CR05, CR07, CE01, CE02, CE03, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, cell_x, dist, h_geocode, cell_y, geometry_x1, geometry_y1, geometry, dist_x, cells_used, C000_dmg, C000_dmg_mean]
Index: []

[0 rows x 55 columns]

In [259]:
select_hgeocode_geo5_6_try2 = select_hgeocode_geo5_6_dic2[0].loc[select_hgeocode_geo5_6_dic2[0]['C000']!=select_hgeocode_geo5_6_dic2[0]['cells_used']]
select_hgeocode_geo5_6_try2

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,dist_x,cells_used,C000_dmg,C000_dmg_mean
66_a_0,1.208797e+14,120879714021021.0,120879704001017,12,2,7,3,11,0,0,...,1.074565,1.208797e+14,20.0,"POLYGON ((-80.44592 25.12323, -80.44589 25.123...","POLYGON ((-80.42276 25.11324, -80.42266 25.113...","POLYGON ((-81.40211 24.73044, -81.40205 24.730...",106.747967,0,0,NaN
105_a_0,1.208797e+14,120879714021021.0,120879714012003,6,1,3,2,6,0,0,...,2.486092,1.208797e+14,20.0,"POLYGON ((-81.35912 24.69543, -81.35903 24.695...","POLYGON ((-81.37982 24.69698, -81.37981 24.697...","POLYGON ((-81.40211 24.73044, -81.40205 24.730...",3.326614,0,0,NaN
148_a_0,1.207100e+14,120710010021030.0,120710012032016,1,0,1,0,1,0,0,...,0.568051,1.207100e+14,3.0,"POLYGON ((-81.85537 26.61176, -81.85537 26.611...","POLYGON ((-81.85974 26.60450, -81.85829 26.604...","POLYGON ((-81.88224 26.61691, -81.88091 26.616...",2.689181,0,0,NaN
233_a_0,1.208797e+14,120879715012008.0,120879721003003,2,0,2,0,2,0,0,...,0.120262,1.208797e+14,4.0,"POLYGON ((-81.78166 24.57740, -81.78165 24.577...","POLYGON ((-81.77763 24.57594, -81.77736 24.576...","POLYGON ((-81.47899 24.66341, -81.47897 24.663...",31.696287,1,0,NaN
258_a_0,1.208797e+14,120879714021021.0,120879714012004,1,0,1,0,1,0,0,...,0.904574,1.208797e+14,20.0,"POLYGON ((-81.35900 24.69076, -81.35884 24.690...","POLYGON ((-81.35211 24.69813, -81.35211 24.698...","POLYGON ((-81.40211 24.73044, -81.40205 24.730...",4.532331,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8482_a_0,1.208797e+14,120879715021039.0,120879714012008,3,0,3,0,3,0,0,...,7.45181,1.208797e+14,22.0,"POLYGON ((-81.35804 24.68464, -81.35804 24.684...","POLYGON ((-81.39824 24.62321, -81.39823 24.623...","POLYGON ((-81.45465 24.66143, -81.45454 24.661...",6.722684,0,0,NaN
8483_a_0,1.208100e+14,120810001053014.0,120810019163004,3,0,2,1,3,0,0,...,11.587041,1.208100e+14,60.0,"POLYGON ((-82.51255 27.58683, -82.51128 27.588...","POLYGON ((-82.56547 27.49466, -82.56543 27.495...","POLYGON ((-82.57124 27.47295, -82.57124 27.473...",2.609075,0,0,NaN
8484_a_0,1.208797e+14,120879710012039.0,120879714011032,16,0,16,0,16,0,0,...,0.899217,1.208797e+14,96.0,"POLYGON ((-81.35092 24.67245, -81.35092 24.672...","POLYGON ((-81.36233 24.67438, -81.36080 24.674...","POLYGON ((-81.01974 24.72897, -81.01960 24.729...",35.182148,1,0,NaN
8485_a_0,1.208100e+14,120810020121004.0,120810020183029,12,2,4,6,11,1,0,...,5.033827,1.208100e+14,35.0,"POLYGON ((-82.42543 27.48683, -82.42515 27.486...","POLYGON ((-82.45919 27.44140, -82.45919 27.442...","POLYGON ((-82.46830 27.44550, -82.46819 27.445...",0.783195,0,0,NaN
8486_a_0,1.208100e+14,120810001053014.0,120810007043047,1,0,1,0,0,1,0,...,2.99863,1.208100e+14,60.0,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...","POLYGON ((-82.56678 27.47713, -82.56306 27.477...","POLYGON ((-82.57124 27.47295, -82.57124 27.473...",0.594089,0,0,NaN

In [260]:
select_hgeocode_geo5_6_try2['C000'].sum()

12690

In [261]:
(select_hgeocode_geo5_6_try2['C000']-select_hgeocode_geo5_6_try2['cells_used']).sum()

11143

In [262]:
def try_function(select_hgeocode_geo5_6_try2,Emp_cells2_2030_1_dic, select_hgeocode_geo4_2_2):

    select_hgeocode_geo5_6_try2 = select_hgeocode_geo5_6_try2.astype({"cells_used":'int64'})
    
    print('select_hgeocode_geo5_6_try2[cells_used]=', select_hgeocode_geo5_6_try2['cells_used'].sum())
    
    select_hgeocode_geo5_6_try2['C000'] = select_hgeocode_geo5_6_try2['C000']- select_hgeocode_geo5_6_try2['cells_used']

    select_hgeocode_geo5_6_try2 = select_hgeocode_geo5_6_try2.astype({"C000":'int64'})
    
    print('select_hgeocode_geo5_6_try2[C000]=', select_hgeocode_geo5_6_try2['C000'].sum())
    
#     if 'h_geocode_y' in select_hgeocode_geo5_6_try2.columns:
#         print('Yes')
#     else: 
#         print('No')
#         select_hgeocode_geo5_6_try2.rename(columns = {'h_geocode':'h_geocode_y'}, inplace = True)
        
    
    select_hgeocode_geo5_6_try2_c000 = select_hgeocode_geo5_6_try2[['C000','h_geocode_y']]    
        
    select_hgeocode_geo5_6_try3 = select_hgeocode_geo4_2_2.loc[select_hgeocode_geo4_2_2['h_geocode_y'].isin(select_hgeocode_geo5_6_try2['h_geocode_y'])]
        
    
#     print('len select_hgeocode_geo5_6_try3', len(select_hgeocode_geo5_6_try3))
    
    select_hgeocode_geo5_6_try3_missing = select_hgeocode_geo5_6_try2.loc[~select_hgeocode_geo5_6_try2['h_geocode_y'].isin(select_hgeocode_geo5_6_try3['h_geocode_y'])]
    
    print('len select_hgeocode_geo5_6_try3_missing', len(select_hgeocode_geo5_6_try3_missing))
            
    select_hgeocode_geo5_6_try3_ = pd.merge(
        select_hgeocode_geo5_6_try3, select_hgeocode_geo5_6_try2_c000, how="left", on=["h_geocode_y"])
    
#     print('len select_hgeocode_geo5_6_try3_', len(select_hgeocode_geo5_6_try3_))
    
    select_hgeocode_geo5_6_try3_ = select_hgeocode_geo5_6_try3_.drop(['C000_x'],axis=1)
    select_hgeocode_geo5_6_try3_.rename(columns={'C000_y':'C000'},inplace= True)
    
    select_hgeocode_geo5_6_try4 = select_hgeocode_geo5_6_try3_.loc[~select_hgeocode_geo5_6_try3_['h_geocode_x'].isin(select_hgeocode_geo5_6_try2['h_geocode_x'])]
    
#     print('len select_hgeocode_geo5_6_try4', len(select_hgeocode_geo5_6_try4))

    
    #to get the min dist from orginal h_geocode (h_geocode_y) to w_geocode
    select_hgeocode_geo5_6_try4 = select_hgeocode_geo5_6_try4.select_dtypes(exclude=['geometry'])
    select_hgeocode_geo4_3_try = select_hgeocode_geo5_6_try4.groupby(["h_geocode_y"], as_index=False).min()

    select_hgeocode_geo4_3_try = select_hgeocode_geo4_3_try[['dist']]
    select_hgeocode_geo5_1_try = pd.merge(select_hgeocode_geo4_3_try, select_hgeocode_geo5_6_try4,  how='left', 
                    left_on=['dist'], right_on = ['dist'])


#     select_hgeocode_geo5_1_try = select_hgeocode_geo5_1_try.drop(['level_0','index'],axis=1)
    select_hgeocode_geo5_1_try = select_hgeocode_geo5_1_try.reset_index()
    select_hgeocode_geo5_1_try = select_hgeocode_geo5_1_try.astype({"index":'object'})
    
    
    
    select_hgeocode_geo5_1_try_ = select_hgeocode_geo5_1_try.loc[select_hgeocode_geo5_1_try['h_geocode_x'].isin(Emp_cells2_2030_1_dic[0]['h_geocode'])]
    
#     print('len select_hgeocode_geo5_1_try_', len(select_hgeocode_geo5_1_try_))

#     select_hgeocode_geo5_2_try = select_hgeocode_geo5_1_try_.groupby(["h_geocode_y"], as_index=False)['dist_x'].min()
    select_hgeocode_geo5_2_try = select_hgeocode_geo5_1_try_.groupby(["h_geocode_y"], as_index=False)['dist_x'].min()

    
    select_hgeocode_geo5_2_try = select_hgeocode_geo5_2_try[['dist_x']]
    select_hgeocode_geo5_3_try = pd.merge(select_hgeocode_geo5_2_try, select_hgeocode_geo5_1_try_,  how='left', 
                    left_on=['dist_x'], right_on = ['dist_x'])
    
#     print('len select_hgeocode_geo5_3_try', len(select_hgeocode_geo5_3_try))

    select_hgeocode_geo5_6_try_ = select_hgeocode_geo5_3_try.drop_duplicates(subset=['h_geocode_y']) # this should be select_hgeocode_geo5_6_try 
    
    select_hgeocode_geo5_6_try_missing = select_hgeocode_geo5_6_try2.loc[~select_hgeocode_geo5_6_try2['h_geocode_y'].isin(select_hgeocode_geo5_6_try_['h_geocode_y'])]
    
    print('select_hgeocode_geo5_6_try_missing_h_geocode_x', select_hgeocode_geo5_6_try_missing['h_geocode_x'])
    
    print('select_hgeocode_geo5_6_try_missing_h_geocode_y', select_hgeocode_geo5_6_try_missing['h_geocode_y'])


    print('len select_hgeocode_geo4_2_2', len(select_hgeocode_geo4_2_2))

    
    select_hgeocode_geo4_2_2_missing = select_hgeocode_geo4_2_2.loc[select_hgeocode_geo4_2_2['h_geocode_y'].isin(select_hgeocode_geo5_6_try_missing['h_geocode_y'])]
    print('len select_hgeocode_geo4_2_2_missing', len(select_hgeocode_geo4_2_2_missing))

    select_hgeocode_geo4_2_2_exist =  select_hgeocode_geo4_2_2.loc[~select_hgeocode_geo4_2_2['h_geocode_y'].isin(select_hgeocode_geo5_6_try_missing['h_geocode_y'])]
    
    print('len select_hgeocode_geo4_2_2_exist', len(select_hgeocode_geo4_2_2_exist))

    select_hgeocode_geo4_2_2_missing2 = select_hgeocode_geo4_2_2_missing.loc[~select_hgeocode_geo4_2_2_missing['h_geocode_x'].isin(select_hgeocode_geo5_6_try_missing['h_geocode_x'])]
    
    print('len select_hgeocode_geo4_2_2_missing2', len(select_hgeocode_geo4_2_2_missing2))
    
    select_hgeocode_geo4_2_2_final = pd.concat([select_hgeocode_geo4_2_2_exist,select_hgeocode_geo4_2_2_missing2], axis=0 )

    print('len select_hgeocode_geo4_2_2_final', len(select_hgeocode_geo4_2_2_final))

    
    print('len select_hgeocode_geo5_6_try_missing', len(select_hgeocode_geo5_6_try_missing))
    
    select_hgeocode_geo5_6_try_missing_final = select_hgeocode_geo5_6_try_missing.loc[~select_hgeocode_geo5_6_try_missing['h_geocode_y'].isin(select_hgeocode_geo5_6_try3_missing['h_geocode_y'])]
    
    print('len select_hgeocode_geo5_6_try_missing_final', len(select_hgeocode_geo5_6_try_missing_final))
    print('len select_hgeocode_geo5_6_try_missing_final_h_geocode_x', select_hgeocode_geo5_6_try_missing_final['h_geocode_x'])

    select_hgeocode_geo5_6_try =  select_hgeocode_geo5_6_try_       
    
#     print('len select_hgeocode_geo5_6_try', len(select_hgeocode_geo5_6_try))
                                                      
    
    find_cells = Emp_cells2_2030_1_dic[0].loc[Emp_cells2_2030_1_dic[0]['h_geocode'].isin(select_hgeocode_geo5_6_try['h_geocode_x'])]
    
    find_cells_sum = find_cells.groupby(["h_geocode"], as_index=False)['cell'].sum()
    
#     for select_hgeocode_geo5_1_try
    
#     print('find_cells(cells_num)=',find_cells_sum)
    
    
    
    select_hgeocode_geo5_6_try = select_hgeocode_geo5_6_try.drop(['index'],axis=1)
    select_hgeocode_geo5_6_try = select_hgeocode_geo5_6_try.reset_index()
#     print('select_hgeocode_geo5_6_try=',pd.DataFrame(select_hgeocode_geo5_6_try))



#     select_hgeocode_geo5_6_try['C000']= select_hgeocode_geo5_6_try['C000'].replace('',np.nan.fillna(0))
    print('select_hgeocode_geo5_6_try[C000]=',select_hgeocode_geo5_6_try['C000'].unique())
    
    select_hgeocode_geo5_6_try = select_hgeocode_geo5_6_try.dropna(subset=['C000'])
    
    print('select_hgeocode_geo5_6_try[C000]=',select_hgeocode_geo5_6_try['C000'].unique())

    select_hgeocode_geo5_6_try = select_hgeocode_geo5_6_try.astype({"C000":'int64',"CNS01":'int64',"CNS02":'int64',"CNS03":'int64',
                                                           "CNS04":'int64',"CNS05":'int64',"CNS06":'int64',"CNS07":'int64',
                                                           "CNS08":'int64',"CNS09":'int64',"CNS10":'int64',"CNS11":'int64',
                                                           "CNS12":'int64',"CNS13":'int64',"CNS14":'int64',"CNS15":'int64',
                                                           "CNS16":'int64',"CNS17":'int64',"CNS18":'int64',"CNS19":'int64',
                                                           "CNS20":'int64', "CR01":'int64','CR02':'int64' ,'CR03' :'int64',
                                                           "CR04" :'int64', "CR05":'int64','CR07':'int64' ,"CA01" :'int64',
                                                           "CA02" :'int64',"CA03" :'int64',"CE01":'int64' ,"CE02" :'int64',
                                                           "CE03" :'int64',"CT01" :'int64',"CT02":'int64' ,"CD01" :'int64',
                                                           "CD02" :'int64',"CD03" :'int64',"CD04":'int64' ,"CS01" :'int64',
                                                           "CS02" :'int64'})

    
    print('select_hgeocode_geo5_6_try[C000]=', select_hgeocode_geo5_6_try['C000'].sum())

    
    dataframes2_temp={}


    # list of data frames
    # Assume that the original dataframe is named 'original_df'
    for i in range(0, 1):
        dataframes2_temp[i] = select_hgeocode_geo5_6_try.copy()

    # Convert the dictionary to a list of tuples
    dataframes2 = list(dataframes2_temp.values())

    for k in range(0, 1):
        dataframes2[k] = dataframes2[k].rename("{}_{}".format("{}_a",k).format)

    # dictionary to save data frames
    select_hgeocode_geo5_6_try_dic={} 

    for key2, value2 in enumerate(dataframes2):    
        select_hgeocode_geo5_6_try_dic[key2] = value2 # assigning data frame from list to key in dictionary

    return select_hgeocode_geo5_6_try_dic , select_hgeocode_geo4_2_2_final, select_hgeocode_geo5_6_try_missing #,select_hgeocode_geo5_6_try_missing

In [263]:
def dmg_calc(my_list_2,my_list_3,select_hgeocode_geo5_6_dic2):
    dataframes3_list_2_temp={}
    dataframes3_list_3_temp={}


    for k in range(0, len(Raster_file_paths_new)):
        dataframes3_list_2_temp[k] = pd.DataFrame(my_list_2[k]).copy()
        dataframes3_list_3_temp[k] = pd.DataFrame(my_list_3[k]).copy()    

    dataframes3_list_2 = list(dataframes3_list_2_temp.values())
    dataframes3_list_3 = list(dataframes3_list_3_temp.values())


    for k in range(0, len(Raster_file_paths_new)):
        dataframes3_list_2[k] = dataframes3_list_2[k].rename("{}_{}".format("{}_a",k).format)
        dataframes3_list_3[k] = dataframes3_list_3[k].rename("{}_{}".format("{}_a",k).format)


    # dictionary to save data frames
    my_dicts_2={}
    my_dicts_3={} 

    for key_list2, value_list2 in enumerate(dataframes3_list_2):    
        my_dicts_2[key_list2] = value_list2 # assigning data frame from list to key in dictionary
    for key_list3, value_list3 in enumerate(dataframes3_list_3):    
        my_dicts_3[key_list3] = value_list3 # assigning data frame from list to key in dictionary


    for i in range(0,len(select_hgeocode_geo5_6_dic2)):
        select_hgeocode_geo5_6_dic2[i]['C000_dmg'] = my_dicts_2[i]
        select_hgeocode_geo5_6_dic2[i]['C000_dmg_mean'] = my_dicts_3[i]
        
    return select_hgeocode_geo5_6_dic2

In [264]:
select_hgeocode_geo5_6_try2[select_hgeocode_geo5_6_try2['C000']<0]

Empty DataFrame
Columns: [w_geocode, h_geocode_x, h_geocode_y, C000, CA01, CA02, CA03, CR01, CR02, CR03, CR04, CR05, CR07, CE01, CE02, CE03, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, cell_x, dist, h_geocode, cell_y, geometry_x1, geometry_y1, geometry, dist_x, cells_used, C000_dmg, C000_dmg_mean]
Index: []

[0 rows x 55 columns]

In [265]:
# select_hgeocode_geo5_6_try_dic,select_hgeocode_geo5_6_try_dic_missing = try_function(select_hgeocode_geo5_6_try2,Emp_cells2_2030_dic,select_hgeocode_geo4_2_2)

In [266]:
def list4_2_full (Emp_cells2_dic_list4_2):
    Emp_cells2_dic_list4_2_modify = Emp_cells2_dic_list4_2.copy()

    for k in range(0,len(my_list_4)):
        Emp_cells2_dic_list4_2_modify= Emp_cells2_dic_list4_2_modify.drop(['damage{0}'.format(k)],axis=1)

    Emp_cells2_dic_list4_2_modify

    for index, i in enumerate(new_list):
    #     print(f"i: {i}, j: {index+1}")
        Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = Emp_cells2_dic_list4_2['damage{0}'.format(index)]

    for i in list_iterate:
        Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = 0
    Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify.iloc[:,33:]
    Emp_cells2_dic_list4_2_modify_select2 = Emp_cells2_dic_list4_2_modify.iloc[:,:33]

    sorted_columns = sorted(Emp_cells2_dic_list4_2_modify_select.columns, key=custom_sort)
    sorted_Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify_select[sorted_columns]

    Emp_cells2_dic_list4_2 = pd.concat([ Emp_cells2_dic_list4_2_modify_select2,sorted_Emp_cells2_dic_list4_2_modify_select],axis=1)

    return Emp_cells2_dic_list4_2

In [267]:
# Emp_cells2_dic_list4 = list4_2_full(Emp_cells2_dic_list4)

In [268]:
len(select_hgeocode_geo5_6_try2)

2656

In [269]:
def dataframe_full (select_hgeocode_geo5_6_dic2):

    select_hgeocode_geo5_6_dic2_full={}

    for index, i in enumerate(new_list):
        #     print(f"i: {i}, j: {index+1}")
            select_hgeocode_geo5_6_dic2_full[i] = select_hgeocode_geo5_6_dic2[index]


    for i in list_iterate:
            select_hgeocode_geo5_6_dic2_full[i] = select_hgeocode_geo5_6_dic2[0].copy()
            select_hgeocode_geo5_6_dic2_full[i]['C000_dmg'] = 0
            select_hgeocode_geo5_6_dic2_full[i]['C000_dmg_mean'] = 0
    return select_hgeocode_geo5_6_dic2_full

In [270]:
# select_hgeocode_geo5_6_dic2_full = dataframe_full(select_hgeocode_geo5_6_dic2)

In [271]:

from iteration_utilities import deepflatten

list_cells2_2030 = list(deepflatten(cells2_2030, depth=1))
Emp_cells2_2030_1_try1_dic = {}
for i in range(0, 1):
    Emp_cells2_2030_1_try1_dic[i] = Emp_cells2_dic2[i].loc[~Emp_cells2_dic2[i]['fd_id'].isin(list_cells2_2030)]
#     Emp_cells2_2030_1_try1_dic[i]=Emp_cells2_2030_1_try1_dic[i].drop(['min_2030'],axis=1)
    
len(Emp_cells2_2030_1_try1_dic[0])

296881

In [272]:
len(Emp_cells2_2030_1_try1_dic[0])

296881

In [273]:
len(Emp_cells2_dic2[0])-len(Emp_cells2_2030_1_try1_dic[0])

34246

In [274]:
# for x in range(0, 2):
#     globals()['list_cells2_2030_1_try%s_dic' % x] = 'Hello'
    
#     print(len(globals()['list_cells2_2030_1_try%s_dic' % x]))

In [275]:
select_hgeocode_geo5_6_dic2[0]['C000'].sum()

45389

In [276]:
select_hgeocode_geo5_6_try2[select_hgeocode_geo5_6_try2['C000']<0]

Empty DataFrame
Columns: [w_geocode, h_geocode_x, h_geocode_y, C000, CA01, CA02, CA03, CR01, CR02, CR03, CR04, CR05, CR07, CE01, CE02, CE03, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, cell_x, dist, h_geocode, cell_y, geometry_x1, geometry_y1, geometry, dist_x, cells_used, C000_dmg, C000_dmg_mean]
Index: []

[0 rows x 55 columns]

In [277]:
Emp_cells2_2030_1_try1_dic[0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
4,120810020212027,492122842,0.5,POINT (-82.44745 27.44263),1,NaN
5,120810020101000,492164773,0.5,POINT (-82.12509 27.35222),1,NaN
6,120810020101000,492165521,0.5,POINT (-82.11979 27.44118),1,NaN
...,...,...,...,...,...,...
331122,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
331123,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
331124,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
331125,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
331126,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [278]:
select_hgeocode_geo5_6['w_geocode'][0]

120710012052012.0

In [286]:
# select_hgeocode_geo4_2_2 is the dataframe that has the connection between h_geocode_y and nearest h_geocode_x
# from nearest (w_geocode_x)

select_hgeocode_geo4_2_2_try1 = select_hgeocode_geo4_2_2.copy()


for j in range(2,40):
    print('j loop =',j)
    globals()['select_hgeocode_geo5_6_try_try%s_dic' % j] ={}
    globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % j] =[]
    globals()['cells2_2030_1_try%s' % j] = []
    globals()['list_cells2_2030_1_try%s' % j] = []
    globals()['select_hgeocode_geo5_6_try%s' % (j+1)] = []
    
    my_list_2=[]
    my_list_3=[]
    my_list_4=[]
    
#     print(globals()['select_hgeocode_geo5_6_try_try%s' % i])
    
#     print(globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)])

    
    globals()['select_hgeocode_geo5_6_try_try%s_dic' % j] , globals()['select_hgeocode_geo4_2_2_try%s' % j], globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = try_function(globals()['select_hgeocode_geo5_6_try%s' % j], globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)], globals()['select_hgeocode_geo4_2_2_try%s' % (j-1)])
    
    globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0]['loop_num'] = j
    
    globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)], globals()['cells2_2030_1_try%s' % j], globals()['select_hgeocode_geo5_6_try_try%s_dic' % j] = find_cells_SLR(globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0], globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)][0])
    
#     my_list_2, my_list_3,my_list_4 =  cells_calc_x(globals()['select_hgeocode_geo5_6_try_try%s_dic' % j[i]],globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)[i]], globals()['cells2_2030_1_try%s' % j])
    
    start = time.time()
    
    result = Parallel(n_jobs=-1)(delayed(cells_calc_x)(i, globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][i],globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)][i], globals()['cells2_2030_1_try%s' % j]) for i in range(0,len(Raster_file_paths_new)))
    
    zs2_dic3 = dict(enumerate(result))
    
    my_list_2 = [zs2_dic3[i][0] for i in range(len(Raster_file_paths_new))]
    my_list_3 = [zs2_dic3[i][1] for i in range(len(Raster_file_paths_new))]
    my_list_4 = [zs2_dic3[i][2] for i in range(len(Raster_file_paths_new))]
    
    my_list_2_final={}
    my_list_3_final={}
    my_list_4_final={}

    for l in range(0,len(Raster_file_paths_new)):
        my_list_2_final[l]= my_list_2[l][0]
        my_list_3_final[l]= my_list_3[l][0]
        my_list_4_final[l]= my_list_4[l][0]

    end = time.time()
    print(end - start)
    
    globals()['select_hgeocode_geo5_6_try_try%s_dic' % j]= dmg_calc(my_list_2_final, my_list_3_final,globals()['select_hgeocode_geo5_6_try_try%s_dic' % j])
    
#     globals()['select_hgeocode_geo5_6_try_try%s_dic_full' % j] = dataframe_full(globals()['select_hgeocode_geo5_6_try_try%s_dic' % j])
    
    globals()['Emp_cells2_2030_1_try_list%s' % j]  =list_4_calc(my_list_4_final,globals()['cells2_2030_1_try%s' % j], Emp_cells2_dic)
#     globals()['Emp_cells2_2030_1_try_list%s' % j]  = list4_2_full(globals()['Emp_cells2_2030_1_try_list%s' % j])
    
    
    globals()['list_cells2_2030_1_try%s' % j] = list(deepflatten(globals()['cells2_2030_1_try%s' % j], depth=1))
    globals()['Emp_cells2_2030_1_try%s_dic' % j] = {}
    for k in range(0, 1):
        globals()['Emp_cells2_2030_1_try%s_dic' % j][k] = globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)][k].loc[~globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)][k]['fd_id'].isin(globals()['list_cells2_2030_1_try%s' % j])]

    globals()['select_hgeocode_geo5_6_try%s' % (j+1)] = globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0].loc[globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0]['C000']!=globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0]['cells_used']]
    print('len(select_hgeocode_geo5_6_try))=',len(globals()['select_hgeocode_geo5_6_try%s' % (j+1)]) )
    if len(globals()['select_hgeocode_geo5_6_try%s' % (j+1)])>0:
        if len(globals()['select_hgeocode_geo5_6_try%s' % (j+1)])!=len(globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)]):
            continue
        else: break
    else: 
        break

j loop = 2
select_hgeocode_geo5_6_try2[cells_used]= 1547
select_hgeocode_geo5_6_try2[C000]= 11143
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x 105_a_0     120879714021021.0
258_a_0     120879714021021.0
472_a_0     120710403034017.0
772_a_0     120879714021021.0
773_a_0     120879715021052.0
                  ...
8173_a_0    120879705002019.0
8184_a_0    120210106061005.0
8287_a_0    120879715012008.0
8432_a_0    120879714021021.0
8441_a_0    120879714021021.0
Name: h_geocode_x, Length: 62, dtype: object
select_hgeocode_geo5_6_try_missing_h_geocode_y 105_a_0     120879714012003
258_a_0     120879714012004
472_a_0     120710403034025
772_a_0     120879711002066
773_a_0     120879710021001
                 ...
8173_a_0    120879706001017
8184_a_0    120879706001043
8287_a_0    120879715011015
8432_a_0    120879714012079
8441_a_0    120879714021078
Name: h_geocode_y, Length: 62, dtype: int64
len select_hgeocode_geo4_2_2 1806567
len select_hgeocode_geo4_2_2_missing 79
len select_hgeocode_geo4_2_2_exist 1806488
len select_hgeocode_geo4_2_2_missing2 11
len select_hgeocode_geo4_2_2_final 1806499
len select_hgeocode_geo5_6_try_missing 62
len select_hgeocode_geo5_6_try_missing_final 62
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x 105_a_0     120879714021021.0
258_a_0     120879714021021.0
472_a_0     120710403034017.0
772_a_0     120879714021021.0
773_a_0     120879715021052.0
                  ...
8173_a_0    120879705002019.0
8184_a_0    120210106061005.0
8287_a_0    120879715012008.0
8432_a_0    120879714021021.0
8441_a_0    120879714021021.0
Name: h_geocode_x, Length: 62, dtype: object
select_hgeocode_geo5_6_try[C000]= [ 5  2  3  1 14  9  4 11  8  7  6 13 12 19 24 15 16 23 29 36 18 17 10 20
 34 21 31 22 37 27 33 28 32 26 60 41 38 25 49 66 42 30 45 51]
select_hgeocode_geo5_6_try[C000]= [ 5  2  3  1 14  9  4 11  8  7  6 13 12 19 24 15 16 23 29 36 18 17 10 20
 34 21 31 22 37 27 33 28 32 26 60 41 38 25 49 66 42 30 45 51]
select_hgeocode_geo5_6_try[C000]= 10928
Yes
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

24.757720947265625
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.029840946197509766

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

33.37311100959778
len(select_hgeocode_geo5_6_try))= 1241
j loop = 3
select_hgeocode_geo5_6_try2[cells_used]= 641
select_hgeocode_geo5_6_try2[C000]= 4751
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x 2311_a_0    1.207101e+14
2313_a_0    1.207101e+14
2314_a_0    1.207101e+14
2317_a_0    1.207101e+14
2338_a_0    1.202101e+14
2339_a_0    1.202101e+14
2340_a_0    1.202101e+14
2343_a_0    1.208797e+14
2344_a_0    1.208797e+14
2345_a_0    1.208797e+14
2381_a_0    1.207105e+14
2423_a_0    1.208797e+14
Name: h_geocode_x, dtype: float64
select_hgeocode_geo5_6_try_missing_h_geocode_y 2311_a_0    120879710021006
2313_a_0    120879710022018
2314_a_0    120879710022023
2317_a_0    120879710023012
2338_a_0    120879714011038
2339_a_0    120879714011052
2340_a_0    120879715022036
2343_a_0    120879714011050
2344_a_0    120879714012008
2345_a_0    120879714012055
2381_a_0    120879719003014
2423_a_0    120879728003012
Name: h_geocode_y, dtype: int64
len select_hgeocode_geo4_2_2 1806499
len select_hgeocode_geo4_2_2_missing 48
len select_hgeocode_geo4_2_2_exist 1806451
len select_hgeocode_geo4_2_2_missing2 36
len select_hgeocode_geo4_2_2_final 1806487
len select_hgeocode_geo5_6_try_missing 12
len select_hgeocode_geo5_6_try_missing_final 12
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x 2311_a_0    1.207101e+14
2313_a_0    1.207101e+14
2314_a_0    1.207101e+14
2317_a_0    1.207101e+14
2338_a_0    1.202101e+14
2339_a_0    1.202101e+14
2340_a_0    1.202101e+14
2343_a_0    1.208797e+14
2344_a_0    1.208797e+14
2345_a_0    1.208797e+14
2381_a_0    1.207105e+14
2423_a_0    1.208797e+14
Name: h_geocode_x, dtype: float64
select_hgeocode_geo5_6_try[C000]= [ 9  3  7  1  6  4  2  5 12 16  8 10 13 11 14 15 19 27 22 17 30 21 20 31
 24 23 29 38 26 51]
select_hgeocode_geo5_6_try[C000]= [ 9  3  7  1  6  4  2  5 12 16  8 10 13 11 14 15 19 27 22 17 30 21 20 31
 24 23 29 38 26 51]
select_hgeocode_geo5_6_try[C000]= 4716
Yes
your here 1
your here 2
7.469871759414673
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.016945362091064453

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

15.375098943710327
len(select_hgeocode_geo5_6_try))= 771
j loop = 4
select_hgeocode_geo5_6_try2[cells_used]= 212
select_hgeocode_geo5_6_try2[C000]= 2758
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x 1082_a_0    1.208797e+14
1093_a_0    1.208797e+14
1094_a_0    1.208797e+14
1095_a_0    1.208797e+14
1106_a_0    1.208797e+14
1108_a_0    1.208797e+14
1109_a_0    1.208797e+14
Name: h_geocode_x, dtype: float64
select_hgeocode_geo5_6_try_missing_h_geocode_y 1082_a_0    120879706001041
1093_a_0    120879710021023
1094_a_0    120879710022031
1095_a_0    120879710023002
1106_a_0    120879720002006
1108_a_0    120879721002017
1109_a_0    120879721002032
Name: h_geocode_y, dtype: int64
len select_hgeocode_geo4_2_2 1806487
len select_hgeocode_geo4_2_2_missing 51
len select_hgeocode_geo4_2_2_exist 1806436
len select_hgeocode_geo4_2_2_missing2 44
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 7
len select_hgeocode_geo5_6_try_missing_final 7
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x 1082_a_0    1.208797e+14
1093_a_0    1.208797e+14
1094_a_0    1.208797e+14
1095_a_0    1.208797e+14
1106_a_0    1.208797e+14
1108_a_0    1.208797e+14
1109_a_0    1.208797e+14
Name: h_geocode_x, dtype: float64
select_hgeocode_geo5_6_try[C000]= [ 6  1  9  3  4  2  5 12  7 13  8 11 14 15 10 22 17 21 20 31 19 24 16 23
 29 38]
select_hgeocode_geo5_6_try[C000]= [ 6  1  9  3  4  2  5 12  7 13  8 11 14 15 10 22 17 21 20 31 19 24 16 23
 29 38]
select_hgeocode_geo5_6_try[C000]= 2746
Yes
your here 1
your here 2
4.390711784362793
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.014394283294677734

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

9.183637142181396
len(select_hgeocode_geo5_6_try))= 483
j loop = 5
select_hgeocode_geo5_6_try2[cells_used]= 81
select_hgeocode_geo5_6_try2[C000]= 1636
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 4  7  1  3  5  2  6 12 11 16  8 31 14 22 17 24 23 29 13 15  9 19 10]
select_hgeocode_geo5_6_try[C000]= [ 4  7  1  3  5  2  6 12 11 16  8 31 14 22 17 24 23 29 13 15  9 19 10]
select_hgeocode_geo5_6_try[C000]= 1636
Yes
your here 1
your here 2
1.5749671459197998
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.012778997421264648

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

5.967489004135132
len(select_hgeocode_geo5_6_try))= 386
j loop = 6
select_hgeocode_geo5_6_try2[cells_used]= 106
select_hgeocode_geo5_6_try2[C000]= 1237
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 3  7  1  5  2  6  4 12 14 22 17  8 11 16 23 29  9 15 13 19 10]
select_hgeocode_geo5_6_try[C000]= [ 3  7  1  5  2  6  4 12 14 22 17  8 11 16 23 29  9 15 13 19 10]
select_hgeocode_geo5_6_try[C000]= 1237
Yes
your here 1
your here 2
1.5263817310333252
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.012234926223754883
4.903387069702148
len(select_hgeocode_geo5_6_try))= 315
j loop = 7
select_hgeocode_geo5_6_try2[cells_used]= 23
select_hgeocode_geo5_6_try2[C000]= 864
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 5  1  3  2  6  7  4  9  8 10 12 13 15 19]
select_hgeocode_geo5_6_try[C000]= [ 5  1  3  2  6  7  4  9  8 10 12 13 15 19]
select_hgeocode_geo5_6_try[C000]= 864
Yes
your here 1
your here 2
0.6268548965454102
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011548757553100586
3.96659517288208
len(select_hgeocode_geo5_6_try))= 276
j loop = 8
select_hgeocode_geo5_6_try2[cells_used]= 18
select_hgeocode_geo5_6_try2[C000]= 711
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 4  1  3  5  2  6  7 12 10 13  9 15  8 19]
select_hgeocode_geo5_6_try[C000]= [ 4  1  3  5  2  6  7 12 10 13  9 15  8 19]
select_hgeocode_geo5_6_try[C000]= 711
Yes
your here 1
your here 2
0.3019890785217285
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011299848556518555

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

3.3939661979675293
len(select_hgeocode_geo5_6_try))= 249
j loop = 9
select_hgeocode_geo5_6_try2[cells_used]= 9
select_hgeocode_geo5_6_try2[C000]= 641
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 3  1  5  2  6  7  4 10 13  9  8 12 15 19]
select_hgeocode_geo5_6_try[C000]= [ 3  1  5  2  6  7  4 10 13  9  8 12 15 19]
select_hgeocode_geo5_6_try[C000]= 641
Yes
your here 1
your here 2
0.43223094940185547
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011762857437133789

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

3.353994131088257
len(select_hgeocode_geo5_6_try))= 222
j loop = 10
select_hgeocode_geo5_6_try2[cells_used]= 9
select_hgeocode_geo5_6_try2[C000]= 532
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 2  1  3  4  5  6  7 10  9  8 13]
select_hgeocode_geo5_6_try[C000]= [ 2  1  3  4  5  6  7 10  9  8 13]
select_hgeocode_geo5_6_try[C000]= 532
Yes
your here 1
your here 2
0.307725191116333
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011136054992675781

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

2.804809808731079
len(select_hgeocode_geo5_6_try))= 194
j loop = 11
select_hgeocode_geo5_6_try2[cells_used]= 13
select_hgeocode_geo5_6_try2[C000]= 456
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  5  6  9  8  7 13]
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  5  6  9  8  7 13]
select_hgeocode_geo5_6_try[C000]= 456
Yes
your here 1
your here 2
0.2263941764831543
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011466026306152344
2.7356278896331787
len(select_hgeocode_geo5_6_try))= 176
j loop = 12
select_hgeocode_geo5_6_try2[cells_used]= 16
select_hgeocode_geo5_6_try2[C000]= 403
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 4 5 6 7 8]
select_hgeocode_geo5_6_try[C000]= [1 2 3 4 5 6 7 8]
select_hgeocode_geo5_6_try[C000]= 403
Yes
your here 1
your here 2
0.25272488594055176
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011148929595947266

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

2.5458271503448486
len(select_hgeocode_geo5_6_try))= 154
j loop = 13
select_hgeocode_geo5_6_try2[cells_used]= 6
select_hgeocode_geo5_6_try2[C000]= 342
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 4 5 6 7]
select_hgeocode_geo5_6_try[C000]= [1 2 3 4 5 6 7]
select_hgeocode_geo5_6_try[C000]= 342
Yes
your here 1
your here 2
0.17802691459655762
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011298894882202148

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

2.357975721359253
len(select_hgeocode_geo5_6_try))= 140
j loop = 14
select_hgeocode_geo5_6_try2[cells_used]= 10
select_hgeocode_geo5_6_try2[C000]= 298
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 4 5 6 7]
select_hgeocode_geo5_6_try[C000]= [1 2 3 4 5 6 7]
select_hgeocode_geo5_6_try[C000]= 298
Yes
your here 1
your here 2
0.19414377212524414
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011362075805664062
2.2503151893615723
len(select_hgeocode_geo5_6_try))= 122
j loop = 15
select_hgeocode_geo5_6_try2[cells_used]= 9
select_hgeocode_geo5_6_try2[C000]= 256
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [2 1 3 4 5 6 7]
select_hgeocode_geo5_6_try[C000]= [2 1 3 4 5 6 7]
select_hgeocode_geo5_6_try[C000]= 256
Yes
your here 1
your here 2
0.19655489921569824
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011316061019897461

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

2.1778500080108643
len(select_hgeocode_geo5_6_try))= 110
j loop = 16
select_hgeocode_geo5_6_try2[cells_used]= 13
select_hgeocode_geo5_6_try2[C000]= 213
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 5 4 7]
select_hgeocode_geo5_6_try[C000]= [1 2 3 5 4 7]
select_hgeocode_geo5_6_try[C000]= 213
Yes
your here 1
your here 2
0.1652817726135254
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011566877365112305
2.0521979331970215
len(select_hgeocode_geo5_6_try))= 94
j loop = 17
select_hgeocode_geo5_6_try2[cells_used]= 6
select_hgeocode_geo5_6_try2[C000]= 174
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 4 5]
select_hgeocode_geo5_6_try[C000]= [1 2 3 4 5]
select_hgeocode_geo5_6_try[C000]= 174
Yes
your here 1
your here 2
0.13550090789794922
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011141061782836914
1.9959640502929688
len(select_hgeocode_geo5_6_try))= 81
j loop = 18
select_hgeocode_geo5_6_try2[cells_used]= 6
select_hgeocode_geo5_6_try2[C000]= 145
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 5 4]
select_hgeocode_geo5_6_try[C000]= [1 2 3 5 4]
select_hgeocode_geo5_6_try[C000]= 145
Yes
your here 1
your here 2
0.14730310440063477
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011312007904052734

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

1.8916940689086914
len(select_hgeocode_geo5_6_try))= 66
j loop = 19
select_hgeocode_geo5_6_try2[cells_used]= 3
select_hgeocode_geo5_6_try2[C000]= 115
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 4]
select_hgeocode_geo5_6_try[C000]= [1 2 3 4]
select_hgeocode_geo5_6_try[C000]= 115
Yes
your here 1
your here 2
0.1152801513671875
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010956048965454102

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

1.8941166400909424
len(select_hgeocode_geo5_6_try))= 55
j loop = 20
select_hgeocode_geo5_6_try2[cells_used]= 2
select_hgeocode_geo5_6_try2[C000]= 90
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 3 2]
select_hgeocode_geo5_6_try[C000]= [1 3 2]
select_hgeocode_geo5_6_try[C000]= 90
Yes
your here 1
your here 2
0.035926103591918945
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010654926300048828
1.7262799739837646
len(select_hgeocode_geo5_6_try))= 52
j loop = 21
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 85
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 3 2]
select_hgeocode_geo5_6_try[C000]= [1 3 2]
select_hgeocode_geo5_6_try[C000]= 85
Yes
your here 1
your here 2
0.05030703544616699
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010937690734863281
1.7317619323730469
len(select_hgeocode_geo5_6_try))= 49
j loop = 22
select_hgeocode_geo5_6_try2[cells_used]= 1
select_hgeocode_geo5_6_try2[C000]= 79
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= 79
Yes
your here 1
your here 2
0.051260948181152344
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010646581649780273
1.648432731628418
len(select_hgeocode_geo5_6_try))= 45
j loop = 23
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 73
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= 73
Yes
your here 1
your here 2
0.11321187019348145
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010597944259643555
1.6506381034851074
len(select_hgeocode_geo5_6_try))= 38
j loop = 24
select_hgeocode_geo5_6_try2[cells_used]= 3
select_hgeocode_geo5_6_try2[C000]= 53
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= 53
Yes
your here 1
your here 2
0.09029197692871094
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010552167892456055

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

1.6188609600067139
len(select_hgeocode_geo5_6_try))= 31
j loop = 25
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 39
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= 39
Yes
your here 1
your here 2
0.05102109909057617
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011083126068115234
1.6408910751342773
len(select_hgeocode_geo5_6_try))= 26
j loop = 26
select_hgeocode_geo5_6_try2[cells_used]= 1
select_hgeocode_geo5_6_try2[C000]= 33
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= 33
Yes
your here 1
your here 2
0.0524449348449707
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010754108428955078
1.5649220943450928
len(select_hgeocode_geo5_6_try))= 21
j loop = 27
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 27
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= 27
Yes
your here 1
your here 2
0.03848600387573242
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010705947875976562
1.5264050960540771
len(select_hgeocode_geo5_6_try))= 18
j loop = 28
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 24
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= 24
Yes
your here 1
your here 2
0.0370020866394043
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010492086410522461
1.5154192447662354
len(select_hgeocode_geo5_6_try))= 16
j loop = 29
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 22
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [2 1]
select_hgeocode_geo5_6_try[C000]= [2 1]
select_hgeocode_geo5_6_try[C000]= 22
Yes
your here 1
your here 2
0.036241769790649414
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010418891906738281
1.6737868785858154
len(select_hgeocode_geo5_6_try))= 14
j loop = 30
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 19
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= [1 2]
select_hgeocode_geo5_6_try[C000]= 19
Yes
i= 0
0.027385950088500977
your here 1
your here 2
0.07079792022705078
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010757923126220703
1.535855770111084
len(select_hgeocode_geo5_6_try))= 8
j loop = 31
select_hgeocode_geo5_6_try2[cells_used]= 1
select_hgeocode_geo5_6_try2[C000]= 8
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1]
select_hgeocode_geo5_6_try[C000]= [1]
select_hgeocode_geo5_6_try[C000]= 8
Yes
i= 0
0.01621699333190918
your here 1
your here 2
0.035804033279418945
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.010440826416015625

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

1.4532060623168945
len(select_hgeocode_geo5_6_try))= 5
j loop = 32
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 5
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1806480
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1806480
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1806480
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1]
select_hgeocode_geo5_6_try[C000]= [1]
select_hgeocode_geo5_6_try[C000]= 5
Yes
i= 0
0.011378049850463867
your here 1
your here 2
0.0482020378112793
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.011002779006958008

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

1.4274871349334717
len(select_hgeocode_geo5_6_try))= 0

In [280]:
# # select_hgeocode_geo4_2_2 is the dataframe that has the connection between h_geocode_y and nearest h_geocode_x
# # from nearest (w_geocode_x)

# select_hgeocode_geo4_2_2_try1 = select_hgeocode_geo4_2_2.copy()


# for i in range(2,20):
#     print('i loop =',i)
#     globals()['select_hgeocode_geo5_6_try_try%s_dic' % i] ={}
#     globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % i] =[]
#     globals()['cells2_2030_1_try%s' % i] = []
#     globals()['list_cells2_2030_1_try%s' % i] = []
#     globals()['select_hgeocode_geo5_6_try%s' % (i+1)] = []
    
    
    
# #     print(globals()['select_hgeocode_geo5_6_try_try%s' % i])
    
# #     print(globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)])

    
#     globals()['select_hgeocode_geo5_6_try_try%s_dic' % i] , globals()['select_hgeocode_geo4_2_2_try%s' % i], globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)] = try_function(globals()['select_hgeocode_geo5_6_try%s' % i], globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)], globals()['select_hgeocode_geo4_2_2_try%s' % (i-1)])
    
#     globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0]['loop_num'] = i
    
#     globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)], globals()['cells2_2030_1_try%s' % i], globals()['select_hgeocode_geo5_6_try_try%s_dic' % i] = find_cells_SLR(globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0], globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)][0])
    
#     my_list_2, my_list_3,my_list_4 =  cells_calc_x(globals()['select_hgeocode_geo5_6_try_try%s_dic' % i],globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)], globals()['cells2_2030_1_try%s' % i])
#     globals()['select_hgeocode_geo5_6_try_try%s_dic' % i]= dmg_calc(my_list_2, my_list_3,globals()['select_hgeocode_geo5_6_try_try%s_dic' % i])
    
# #     globals()['select_hgeocode_geo5_6_try_try%s_dic_full' % i] = dataframe_full(globals()['select_hgeocode_geo5_6_try_try%s_dic' % i])
    
#     globals()['Emp_cells2_2030_1_try_list%s' % i]  =list_4_calc(my_list_4,globals()['cells2_2030_1_try%s' % i], Emp_cells2_dic)
# #     globals()['Emp_cells2_2030_1_try_list%s' % i]  = list4_2_full(globals()['Emp_cells2_2030_1_try_list%s' % i])
    
    
#     globals()['list_cells2_2030_1_try%s' % i] = list(deepflatten(globals()['cells2_2030_1_try%s' % i], depth=1))
#     globals()['Emp_cells2_2030_1_try%s_dic' % i] = {}
#     for k in range(0, len(Emp_cells2_dic2)):
#         globals()['Emp_cells2_2030_1_try%s_dic' % i][k] = globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)][k].loc[~globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)][k]['fd_id'].isin(globals()['list_cells2_2030_1_try%s' % i])]

#     globals()['select_hgeocode_geo5_6_try%s' % (i+1)] = globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0].loc[globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0]['C000']!=globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0]['cells_used']]
#     print('len(select_hgeocode_geo5_6_try))=',len(globals()['select_hgeocode_geo5_6_try%s' % (i+1)]) )
#     if len(globals()['select_hgeocode_geo5_6_try%s' % (i+1)])>0:
#         if len(globals()['select_hgeocode_geo5_6_try%s' % (i+1)])!=len(globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)]):
#             continue
#         else: break
#     else: 
#         break

In [287]:
Emp_cells2_2030_1_try_list2

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage5,damage6,damage7,damage8,damage9,damage10,damage11,damage12,damage13,damage14
0,120710802042005,3080.0,497915823,76RVFX26+JCM-0-0-0-0,120710802043007,RES,RES1-1SNB,W,1.0,1166.0,...,100.0,100.0,100.0,100.0,100.0,100.000000,100.0,100.0,100.0,100.0
1,120150101001005,794052.0,491656425,76RWX8H5+9HW-2-2-2-2,120150101002000,RES,RES1-1SNB,M,1.0,732.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,120150201031021,859719.0,491722137,76VW2292+QFG-3-3-3-3,120150201031016,RES,RES1-1SNB,W,1.0,1440.0,...,0.0,0.0,0.0,0.0,0.0,100.000000,100.0,100.0,100.0,100.0
3,120150201031021,859723.0,491722141,76VW22C2+2R9-4-3-3-4,120150201031016,RES,RES1-1SNB,W,1.0,1844.0,...,0.0,0.0,0.0,0.0,0.0,100.000000,100.0,100.0,100.0,100.0
4,120150201031021,859732.0,491722150,76VW22C2+92V-4-2-3-2,120150201031016,RES,RES1-1SNB,W,1.0,1688.0,...,0.0,0.0,0.0,0.0,0.0,87.304409,100.0,100.0,100.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6172,120710403042019,7356574.0,498221254,76RWH8VX+WP2-0-0-0-0,120710403042033,RES,RES1-1SNB,W,1.0,1353.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
6173,120710403042019,7356586.0,498221278,76RWH8VX+PPF-0-0-0-0,120710403042033,RES,RES1-1SNB,W,1.0,1402.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
6174,120710402111009,7356953.0,498221652,76RWJ95P+QFM-0-0-0-0,120710402031026,RES,RES1-1SNB,W,1.0,1388.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
6175,120710402111009,7356954.0,498221653,76RWJ95P+XF8-0-0-0-0,120710402031026,RES,RES1-1SNB,W,1.0,1035.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
6176,120710402111009,7356955.0,498221654,76RWJ95P+H5P-0-0-0-0,120710402031026,RES,RES1-1SNB,W,1.0,992.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [288]:
# len(select_hgeocode_geo5_6_try20)

In [289]:
len(globals()['select_hgeocode_geo5_6_try{0}'.format(2)])

2656

In [290]:
for i in range(2,40):
    if len(globals()['select_hgeocode_geo5_6_try{0}'.format(i)])==0:
        loop_ended = i-1
        break
loop_ended

32

In [291]:
for i in range(1,loop_ended+1):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32

In [292]:
for i in range(1,loop_ended+1):
    globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(i)] = globals()['Emp_cells2_2030_1_try{0}_dic'.format(i)][0]

In [293]:
for i in range(1,loop_ended+1):
    del globals()['Emp_cells2_2030_1_try{0}_dic'.format(i)]

In [294]:
# Emp_cells2_2030_1_try5_dic_0 = Emp_cells2_2030_1_try5_dic[0]
# Emp_cells2_2030_1_try5_dic={}

In [295]:
len(Emp_cells2_2030_1_try1_dic_0)- len( globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)])

10881

In [296]:
select_hgeocode_geo5_6_try_try2_dic_missing['C000'].sum()

215

In [297]:
globals()['Emp_cells2_2030_1_try{0}_'.format(loop_ended)]=[]
globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)]=[]


globals()['Emp_cells2_2030_1_try{0}_'.format(loop_ended)] = globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)].select_dtypes(exclude=['geometry','object'])
globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)] = globals()['Emp_cells2_2030_1_try{0}_'.format(loop_ended)].groupby(["h_geocode"], as_index=False).sum()

In [298]:
globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)]

             h_geocode       fd_id  found_ht  cell  min_2030
0      120150101001000  3934160594      12.0     8       0.0
1      120150101001005   983313019       3.0     2       0.0
2      120150101001009  6391582755      15.5    13       0.0
3      120150101001010  2458356555       3.5     5       0.0
4      120150101001011   491661116       1.5     1       0.0
...                ...         ...       ...   ...       ...
18623  121150027472066   495342021       0.5     1       0.0
18624  121150027472068   495342018       0.5     1       0.0
18625  121150027472069  2475194518       2.5     5       0.0
18626  121150027472070  1971686396       2.0     4       0.0
18627  121150027482003  2464608641       2.5     5       0.0

[18628 rows x 5 columns]

In [299]:
# number of cells are more than number of projected employees

Emp_home_select_2030_new_values_merge_u = Emp_home_select_2030_new_values_merge[Emp_home_select_2030_new_values_merge['C000']- Emp_home_select_2030_new_values_merge['cell'] <= 0]


len(Emp_home_select_2030_new_values_merge_u)

7128

In [300]:
Emp_home_select_2030_new_values_merge_u  = Emp_home_select_2030_new_values_merge_u.astype({
            "C000":'int64',"CNS01":'int64',"CNS02":'int64',"CNS03":'int64',
            "CNS04":'int64',"CNS05":'int64',"CNS06":'int64',"CNS07":'int64',
            "CNS08":'int64',"CNS09":'int64',"CNS10":'int64',"CNS11":'int64',
            "CNS12":'int64',"CNS13":'int64',"CNS14":'int64',"CNS15":'int64',
            "CNS16":'int64',"CNS17":'int64',"CNS18":'int64',"CNS19":'int64',
            "CNS20":'int64', "CR01":'int64','CR02':'int64' ,'CR03' :'int64',
            "CR04" :'int64', "CR05":'int64','CR07':'int64' ,"CA01" :'int64',
            "CA02" :'int64',"CA03" :'int64',"CE01":'int64' ,"CE02" :'int64',
            "CE03" :'int64',"CT01" :'int64',"CT02":'int64' ,"CD01" :'int64',
            "CD02" :'int64',"CD03" :'int64',"CD04":'int64' ,"CS01" :'int64',
            "CS02" :'int64',"cell":'int64'})

In [301]:
Emp_home_select_2030_new_values_merge_u = Emp_home_select_2030_new_values_merge_u.reset_index()

In [302]:
def cells_calc_cells(Emp_home, Emp_cells):
    import time
    from scipy.interpolate import interp1d
    from iteration_utilities import deepflatten
    import random
    start = time.time()
    

    for i in range(0,len(Emp_home)):
        print('i=',i)

        temp22=[]
        temp30 = [[498226819,498226820,498226821]] #one number after Emp_cells2['row_num'].max()
        # temp25 = {}
        my_list = []
        my_dicts = {}
        Emp_home[i]['cells_used'] = ''
        for q in range (0,len(Emp_home[i])):
            temp22_1 = Emp_cells[i][Emp_cells[i]['h_geocode']== Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("h_geocode")]]
            list_temp30 = list(deepflatten(temp30, depth=1))
            temp22 = temp22_1.loc[~temp22_1['fd_id'].isin(list_temp30)]
            temp23 = sorted(temp22['fd_id'])
            if len(temp23) == 0:
#                 print('temp23=',temp23)
                temp24 = temp23
#                 print('len(temp24)=', len(temp24))
                
            if Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")] > len(temp23):
                temp24 = temp23
            else:
#                 temp23 = sorted(temp22['fd_id'])
                temp24 = random.sample(population=temp23, k=Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")])
                temp24 = sorted(temp24)

#             temp24= temp23[0:Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")]]
            temp25 = temp22.loc[temp22['fd_id'].isin(temp24)]
            temp30.append(temp24)

            my_list.append(temp25)
            pd.DataFrame(Emp_home[i]).iloc[q,Emp_home[i].columns.get_loc("cells_used")]= len(temp24)

        cells2_2030=temp30 
        
    end = time.time()
    print(end - start)
    return cells2_2030
        
#         for key, value in en

In [303]:
Emp_home_select_2030_new_values_merge_u['cell'].sum()

148357

In [304]:

Emp_home_select_2030_new_values_merge_u  = Emp_home_select_2030_new_values_merge_u.drop(['cell'],axis=1)

Emp_home_select_2030_new_values_merge_u = pd.merge(Emp_home_select_2030_new_values_merge_u, globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)],  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

In [305]:
Emp_home_select_2030_new_values_merge_u['cell'].sum()

127465.0

In [306]:
globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)], cells2_2030_2, Emp_home_select_2030_new_values_merge_u_dic  = find_cells_SLR(Emp_home_select_2030_new_values_merge_u, globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)])

No
i= 0
18.211066961288452
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

61.858136892318726
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.058708906173706055

In [307]:
globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)][0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120810020212027,492122842,0.5,POINT (-82.44745 27.44263),1,NaN
3,120810020101000,492164773,0.5,POINT (-82.12509 27.35222),1,NaN
4,120810020101000,492165521,0.5,POINT (-82.11979 27.44118),1,NaN
...,...,...,...,...,...,...
285995,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
285996,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
285997,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
285998,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
285999,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [308]:
import warnings
warnings.filterwarnings("ignore")

In [309]:
import numpy as np

def unique(list1):
    x = np.array(list1)
    print(np.unique(x))

In [310]:
Emp_cells2['fd_id'].max()

498226804

In [311]:

for k in range(0,len(Raster_file_paths)):
    if k in list_iterate:
        print('Skipped')
    else:
        print(k)

Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
7
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
15
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
23
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
31
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
39
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
47
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
55
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
63
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
71
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
79
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
87
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
95
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
103
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
111
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
119

In [312]:
def cells_calc(i, Emp_home, Emp_cells, cells2_2030):
    import time
    from scipy.interpolate import interp1d
    from iteration_utilities import deepflatten
#     start = time.time()
    
    
#     my_list_2=[]
#     my_list_3=[]
#     my_list_4=[]

#     for i in range(0,len(Emp_home)):   # 0 , len(Emp_home)
#     print('i=',i)


    temp22=[]
    temp30 = [[498226819,498226820,498226821]] #one number after Emp_cells2['row_num'].max()
    # temp25 = {}
    my_list = []
#         my_list_2=[]
#         my_list_3=[]
    my_dicts = {}
    Emp_home['cells_used'] = ''
    for q in range (0,len(Emp_home)):
        temp22_1 = Emp_cells[Emp_cells['h_geocode']== Emp_home.iloc[q,Emp_home.columns.get_loc("h_geocode")]]
        list_temp30 = list(deepflatten(temp30, depth=1))
        temp22 = temp22_1.loc[~temp22_1['fd_id'].isin(list_temp30)]
        temp23 = sorted(temp22['fd_id'])
        temp24 = cells2_2030[1:][q]
        temp25 = temp22.loc[temp22['fd_id'].isin(temp24)]
        temp30.append(temp24)
        my_list.append(temp25)
        pd.DataFrame(Emp_home).iloc[q,Emp_home.columns.get_loc("cells_used")]= len(temp24)

    for key, value in enumerate(my_list):
        my_dicts[key] = value

    Emp_home['C000_dmg']=''
    Emp_home['C000_dmg_mean']=''
    result_temp1 = []
    temp26 = []
    temp26_2 = []
    temp26_4 = []
    result_2 = []
    result_3 = []
    result_4 = []
    for k in range (0,len(Emp_home)):
        result_1 = []
        for value in my_dicts[k]["min_2030"]:
            result_temp1= value
            result_1.append(result_temp1)
        my_dicts[k]["SLR"] = result_1 #maybe replace result_1 with min_2030 (we don't need the previous 3 lines)
        my_dicts[k]['damage_SLR']=''
        for j in range(0, len(my_dicts[k])):
#                 print('row_num=', pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("row_num")])
#                 print('SLR=',pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] )
            if pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] == 0:
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = 0
            elif pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] > 7:
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = 100
            else: 
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = interp1d(WD_Coast_final['Depth.1']+pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("found_ht")]*0.3048,WD_Coast_final['R11N'],
                                                           bounds_error=False, fill_value=(0,1))(pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")])
#                 print('damage=',pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] )


        my_dicts[k] = my_dicts[k].astype({"damage_SLR":'float'})
        temp26 = len(my_dicts[k][my_dicts[k]["damage_SLR"]>50]) # damage is larger than 50%
        result_2.append(temp26)
        temp26_2 = (my_dicts[k][my_dicts[k]["damage_SLR"]>50])["damage_SLR"].mean()
        result_3.append(temp26_2)
        temp26_4 =my_dicts[k]["damage_SLR"]
        result_4.append(temp26_4)
    my_list_2.append(result_2)
    my_list_3.append(result_3)
    my_list_4.append(result_4)

#     end = time.time()
#     print(end - start)
    return my_list_2, my_list_3,my_list_4

In [313]:
globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)][0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120810020212027,492122842,0.5,POINT (-82.44745 27.44263),1,NaN
3,120810020101000,492164773,0.5,POINT (-82.12509 27.35222),1,NaN
4,120810020101000,492165521,0.5,POINT (-82.11979 27.44118),1,NaN
...,...,...,...,...,...,...
285995,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
285996,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
285997,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
285998,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
285999,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [314]:
Emp_home_select_2030_new_values_merge_u['cell'].sum()

127465.0

In [315]:

# Emp_home_select_2030_new_values_merge_u  = Emp_home_select_2030_new_values_merge_u.drop(['cell'],axis=1)

# Emp_home_select_2030_new_values_merge_u = pd.merge(Emp_home_select_2030_new_values_merge_u, globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)],  how='left', 
#                 left_on=['h_geocode'], right_on = ['h_geocode'])

In [316]:
Emp_home_select_2030_new_values_merge_u['cell'].sum()

127465.0

In [317]:
# from concurrent.futures import ProcessPoolExecutor

In [318]:
from joblib import Parallel, delayed

In [319]:
del zs2_dic

In [320]:
my_list_2=[]
my_list_3=[]
my_list_4=[]

start = time.time()

# Step 3: Use the provided code snippet to parallelize the calculations using the 'worker' function
result = Parallel(n_jobs=5)(delayed(cells_calc)(i, Emp_home_select_2030_new_values_merge_u_dic[i], globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)][i], cells2_2030_2) for i in range(0,len(Raster_file_paths_new)))

# Convert the result to a dictionary with keys as indices
zs2_dic2 = dict(enumerate(result))

# Step 4: After calculating the results, retrieve the values from the 'zs2_dic' dictionary and store them in the lists 'my_list_2', 'my_list_3', and 'my_list_4'
my_list_2 = [zs2_dic2[i][0] for i in range(len(Raster_file_paths_new))]
my_list_3 = [zs2_dic2[i][1] for i in range(len(Raster_file_paths_new))]
my_list_4 = [zs2_dic2[i][2] for i in range(len(Raster_file_paths_new))]

end = time.time()
print(end - start)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

122.73228406906128

In [321]:
# my_list_2, my_list_3,my_list_4  = cells_calc(Emp_home_select_2030_new_values_merge_u_dic,globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)],cells2_2030_2)

In [322]:
my_list_2

[[[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   ...]],
 [[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   ...]],
 [[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   2,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   2,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   2,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   2,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   ...]],
 [[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   3,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   2,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   2,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,

In [323]:
my_list_2_final={}
my_list_3_final={}
my_list_4_final={}

for l in range(0,len(Raster_file_paths_new)):
    my_list_2_final[l]= my_list_2[l][0]
    my_list_3_final[l]= my_list_3[l][0]
    my_list_4_final[l]= my_list_4[l][0]
    
my_list_2={}
my_list_3={}
my_list_4={}

In [324]:
# cells2_2030_2_list = list(deepflatten(cells2_2030_2[1:], depth=1))

Emp_cells2_dic_list4_2 =list_4_calc(my_list_4_final,cells2_2030_2,Emp_cells2_dic)

In [325]:
Emp_cells2_dic_list4_2

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage5,damage6,damage7,damage8,damage9,damage10,damage11,damage12,damage13,damage14
0,120150303024023,793687.0,491656050,76RVWMH8+W6P-4-4-4-4,120150303024030,RES,RES1-1SNB,W,1.0,1858.0,...,0.000000,0.000000,0.000000,0.0,14.895956,100.0,100.0,100.0,100.0,100.0
1,120150101001064,794219.0,491656578,76RWQ7J5+93C-4-3-3-4,120150101001001,RES,RES1-1SNB,M,1.0,2859.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,120150101001064,794633.0,491657021,76RWQ7H6+3PX-3-3-4-4,120150101001001,RES,RES1-1SNB,M,1.0,1670.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,120150101001064,794640.0,491657035,76RWQ7G7+H44-4-3-5-3,120150101001001,RES,RES1-1SNB,M,1.0,2252.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
4,120150101001064,794709.0,491657087,76RWV7GH+HCW-3-4-2-5,120150101001001,RES,RES1-1SNB,M,1.0,1056.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15428,120710402111000,7359385.0,498224078,76RWJC72+34H-0-0-0-0,120710402031000,RES,RES1-1SNB,M,1.0,747.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
15429,120710301003016,7361018.0,498226164,76RWP7HQ+FV9-0-0-0-0,120710301004015,RES,RES1-1SNB,W,1.0,530.0,...,14.862118,23.221699,63.492911,100.0,100.000000,100.0,100.0,100.0,100.0,100.0
15430,120710302022001,7361486.0,498226150,76RWP786+PX2-0-0-0-0,120710302022015,RES,RES1-1SNB,M,1.0,1405.0,...,41.853051,57.929165,99.841888,100.0,100.000000,100.0,100.0,100.0,100.0,100.0
15431,120710301003016,7361533.0,498226205,76RWP7GW+958-0-0-0-0,120710301004015,RES,RES1-1SNB,W,1.0,1104.0,...,93.776099,100.000000,100.000000,100.0,100.000000,100.0,100.0,100.0,100.0,100.0
15432,120710303004010,7361726.0,498226390,76RWP95R+XV9-0-0-0-0,120710303004033,RES,RES1-1SNB,W,1.0,336.0,...,0.000000,0.000000,0.000000,0.0,7.166165,100.0,100.0,100.0,100.0,100.0

In [326]:
# Emp_cells2_dic_list4_2[Emp_cells2_dic_list4_2['damage89']>0]

In [327]:
# Emp_cells2_dic_list4_2 = list4_2_full(Emp_cells2_dic_list4_2)

In [328]:
# Emp_cells2_dic_list4_2[Emp_cells2_dic_list4_2['damage179']>0]

In [329]:
Emp_home_select_2030_new_values_merge_u_dic = dmg_calc(my_list_2_final, my_list_3_final,Emp_home_select_2030_new_values_merge_u_dic)

In [330]:
# Emp_home_select_2030_new_values_merge_u_dic_full = dataframe_full(Emp_home_select_2030_new_values_merge_u_dic)

In [331]:
# len(Emp_home_select_2030_new_values_merge_u_dic_full)

In [332]:
Emp_home_select_2030_new_values_merge_u_dic[0]['C000'].sum()

16939

In [333]:
# unique(Emp_home_select_2030_new_values_merge_u_dic[0]['C000_dmg_mean'])

In [334]:
list_cells2_2030_2 = list(deepflatten(cells2_2030_2, depth=1))
Emp_cells2_2030_2_dic = []
# for i in range(0, len(Emp_cells2_dic2)):

Emp_cells2_2030_2_dic =globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)].loc[~globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)]['fd_id'].isin(list_cells2_2030_2)]
len(Emp_cells2_2030_2_dic)

270567

In [335]:
Emp_cells2_2030_2_=[]
Emp_cells2_2030_2_sum=[]

# for i in range(0, len(Emp_cells2_dic2)):
Emp_cells2_2030_2_ = Emp_cells2_2030_2_dic.select_dtypes(exclude=['geometry','object'])
Emp_cells2_2030_2_sum = Emp_cells2_2030_2_.groupby(["h_geocode"], as_index=False).sum()
Emp_cells2_2030_2_sum

             h_geocode       fd_id  found_ht  cell  min_2030
0      120150101001000  3934160594      12.0     8       0.0
1      120150101001005   983313019       3.0     2       0.0
2      120150101001009  5408261652      12.5    11       0.0
3      120150101001010  2458356555       3.5     5       0.0
4      120150101001011   491661116       1.5     1       0.0
...                ...         ...       ...   ...       ...
17223  121150027472065  1971686487       2.0     4       0.0
17224  121150027472066   495342021       0.5     1       0.0
17225  121150027472069  2475194518       2.5     5       0.0
17226  121150027472070  1971686396       2.0     4       0.0
17227  121150027482003  1478765180       1.5     3       0.0

[17228 rows x 5 columns]

In [336]:

len(globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)])-len(Emp_cells2_2030_2_dic)

15433

In [337]:
len(Emp_cells2)-len(Emp_cells2_2030_2_dic)

60560

In [338]:
Emp_home_select_2030_new_values_merge_u_dic[0]['C000'].sum()

16939

In [339]:
OD_main=pd.read_pickle('/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/OD_main.pkl')

In [340]:
OD_main= OD_main.astype({"h_geocode":'int64'})
OD_main= OD_main.astype({"w_geocode":'int64'})

In [341]:
Emp_home_select_2030_new_values_merge_u_try2 = Emp_home_select_2030_new_values_merge_u_dic[0].loc[Emp_home_select_2030_new_values_merge_u_dic[0]['C000']!=Emp_home_select_2030_new_values_merge_u_dic[0]['cells_used']]
Emp_home_select_2030_new_values_merge_u_try2

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CS02,createdate,geometry,fd_id,found_ht,cell,min_2030,cells_used,C000_dmg,C000_dmg_mean
1_a_0,12,081,002003,1002,120810020031002,Block 1002,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-82.50990 27.50864, -82.50986 27.508...",NaN,NaN,NaN,NaN,0,0,NaN
5_a_0,12,081,000304,1005,120810003041005,Block 1005,G5040,NaN,NaN,NaN,...,0,20231016,"POLYGON ((-82.57543 27.44206, -82.57542 27.443...",NaN,NaN,NaN,NaN,0,0,NaN
13_a_0,12,071,000303,3006,120710003033006,Block 3006,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-81.82496 26.67948, -81.82477 26.679...",NaN,NaN,NaN,NaN,0,0,NaN
15_a_0,12,081,000305,3000,120810003053000,Block 3000,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-82.55900 27.43524, -82.55899 27.436...",NaN,NaN,NaN,NaN,0,0,NaN
26_a_0,12,015,020103,3004,120150201033004,Block 3004,G5040,NaN,NaN,NaN,...,3,20231016,"POLYGON ((-82.04063 27.02423, -82.04061 27.025...",NaN,NaN,NaN,NaN,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7001_a_0,12,115,000502,1001,121150005021001,Block 1001,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-82.52197 27.32955, -82.51988 27.329...",NaN,NaN,NaN,NaN,0,0,NaN
7009_a_0,12,015,020205,1008,120150202051008,Block 1008,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-82.10701 27.01349, -82.10609 27.013...",NaN,NaN,NaN,NaN,0,0,NaN
7019_a_0,12,071,010305,1009,120710103051009,Block 1009,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-81.92204 26.64601, -81.92203 26.646...",NaN,NaN,NaN,NaN,0,0,NaN
7087_a_0,12,071,010601,2010,120710106012010,Block 2010,G5040,NaN,NaN,NaN,...,0,20231016,"POLYGON ((-81.95138 26.59936, -81.95116 26.599...",NaN,NaN,NaN,NaN,0,0,NaN
7112_a_0,12,115,002738,3016,121150027383016,Block 3016,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-82.24344 27.08773, -82.24312 27.087...",495074031.0,0.5,1.0,0.0,1,0,NaN

In [342]:
def try_function2(Emp_home_select_2030_new_values_merge_u_try2,Emp_cells2_2030_2_sum):

    Emp_home_select_2030_new_values_merge_u_try2['C000'] = Emp_home_select_2030_new_values_merge_u_try2['C000']- Emp_home_select_2030_new_values_merge_u_try2['cells_used']

    Emp_home_select_2030_new_values_merge_u_try3 = pd.merge(Emp_home_select_2030_new_values_merge_u_try2, OD_main,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])
    
    Emp_home_select_2030_new_values_merge_u_try4 = pd.merge(Emp_home_select_2030_new_values_merge_u_try3, Emp_work_geo_select,  how='left', 
                left_on=['w_geocode'], right_on = ['w_geocode'])
    
    Emp_home_select_2030_new_values_merge_u_try4['geometry_y']\
    = Emp_home_select_2030_new_values_merge_u_try4['geometry_y'].to_crs({'init': 'epsg:4326'})

    Emp_home_select_2030_new_values_merge_u_try5 = []
    Emp_home_select_2030_new_values_merge_u_try5 = Emp_home_select_2030_new_values_merge_u_try4.dropna(subset=['geometry_y'])


    print('step1 done')
    
    Emp_home_select_2030_new_values_merge_u_try5['centr_x'] = ''
    Emp_home_select_2030_new_values_merge_u_try5['centr_y'] = ''
  
    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5)):
        Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_x")]\
        = Emp_home_select_2030_new_values_merge_u_try5.iloc\
        [n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("geometry_x")].centroid.wkt

        Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_y")]\
        = Emp_home_select_2030_new_values_merge_u_try5.iloc\
        [n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("geometry_y")].centroid.wkt
    
    
    Emp_home_select_2030_new_values_merge_u_try5['centr_x'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_merge_u_try5['centr_x'])
    Emp_home_select_2030_new_values_merge_u_try5['centr_y'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_merge_u_try5['centr_y'])

    Emp_home_select_2030_new_values_merge_u_try5 = gpd.GeoDataFrame(Emp_home_select_2030_new_values_merge_u_try5, geometry='centr_x')
    Emp_home_select_2030_new_values_merge_u_try5 = gpd.GeoDataFrame(Emp_home_select_2030_new_values_merge_u_try5, geometry='centr_y')
    
    print('step2 done')

    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5)):
        Emp_home_select_2030_new_values_merge_u_try5.iloc[n, Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_x")] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_merge_u_try5.iloc[n, Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_x")])
        Emp_home_select_2030_new_values_merge_u_try5.iloc[n, Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_y")] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_merge_u_try5.iloc[n, Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_y")])
    
    coord_list_x =  Emp_home_select_2030_new_values_merge_u_try5['centr_x'].geometry.apply(lambda p: list(p.coords)[0])
    coord_list_y =  Emp_home_select_2030_new_values_merge_u_try5['centr_y'].geometry.apply(lambda p: list(p.coords)[0])
    Emp_home_select_2030_new_values_merge_u_try5['centr_x_co'] = coord_list_x
    Emp_home_select_2030_new_values_merge_u_try5['centr_y_co'] = coord_list_y
    
    from geopy.distance import geodesic as GD  

    Emp_home_select_2030_new_values_merge_u_try5['dist'] = ''
    
    print('step3 done')

    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5)):
        Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("dist")]\
        = GD(Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_x_co")],Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_y_co")]).km

    print('step4 done')
        
    #to get the min dist from orginal h_geocode (h_geocode_y) to w_geocode

    Emp_home_select_2030_new_values_merge_u_try5_ = Emp_home_select_2030_new_values_merge_u_try5.select_dtypes(exclude=['geometry'])

    Emp_home_select_2030_new_values_merge_u_try5_1 = Emp_home_select_2030_new_values_merge_u_try5_.groupby(["h_geocode"], as_index=False).min()

    Emp_home_select_2030_new_values_merge_u_try5_1 = Emp_home_select_2030_new_values_merge_u_try5_1[['dist']]
    Emp_home_select_2030_new_values_merge_u_try5_2 = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_1,
                                                              Emp_home_select_2030_new_values_merge_u_try5,
                                                              how='left', left_on=['dist'], right_on = ['dist'])
    
    # h_geocode_x is h_geocode associated with each w_geocode
    # h_geocode_y is original h_geocode (projected employees)
    #geometry_x for h_geocode_y #geometry_y for w_geocode

    Emp_home_select_2030_new_values_merge_u_try5_OD = pd.merge(OD_main, Emp_home_select_2030_new_values_merge_u_try5_2,
                                                               how='right', left_on=['w_geocode'], right_on = ['w_geocode'])

    
    Emp_home_select_2030_new_values_merge_u_try5_OD = Emp_home_select_2030_new_values_merge_u_try5_OD.drop(['centr_x','centr_x','centr_x_co','centr_y_co'], axis = 1)
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_OD, Emp_cells2_2030_2_sum,  how='left', 
                left_on=['h_geocode_x'], right_on = ['h_geocode'])

    
    #cell_y for h_geocode_x (associate with each w_geocode)
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode =  Emp_home_select_2030_new_values_merge_u_try5_hgeocode.dropna(subset=['cell_y'])
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode = Emp_home_select_2030_new_values_merge_u_try5_hgeocode.astype({"h_geocode":'int64'})

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode['geometry_x1'] = Emp_home_select_2030_new_values_merge_u_try5_hgeocode['geometry_x']
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode['geometry_y1'] = Emp_home_select_2030_new_values_merge_u_try5_hgeocode['geometry_y']
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode = Emp_home_select_2030_new_values_merge_u_try5_hgeocode.drop(['geometry_x','geometry_y'], axis = 1)
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_hgeocode, Emp_home_geo,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo = Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.dropna(subset=['cell_y'])

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x'] = ''
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y'] = ''
    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo)):
        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_x")]\
        = Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc\
        [n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("geometry")].centroid.wkt

        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_y")]\
        = Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc\
        [n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("geometry_y1")].centroid.wkt

    print('step5 done')
    
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x'])
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y'])

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo = gpd.GeoDataFrame(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo, geometry='centr_x')
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo = gpd.GeoDataFrame(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo, geometry='centr_y')

    print('step6 done')

    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo)):
        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n, Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_x")] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n, Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_x")])
        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n, Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_y")] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n, Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_y")])
    
    print('step7 done')
    
    coord_list_x =  Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x'].geometry.apply(lambda p: list(p.coords)[0])
    coord_list_y =  Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y'].geometry.apply(lambda p: list(p.coords)[0])

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x_co'] = coord_list_x

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y_co'] = coord_list_y

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['dist_x'] = ''
    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo)):
        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("dist_x")]\
        = GD(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_x_co")],Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_y_co")]).km

    print('step8 done')
    
    Emp_home_select_2030_new_values_merge_u_try5_4 = Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.drop(['centr_x_co','centr_y_co','centr_x','centr_y'], axis = 1)


    Emp_home_select_2030_new_values_merge_u_try5_4_ = Emp_home_select_2030_new_values_merge_u_try5_4.drop(['cell_y'], axis = 1)

    Emp_cells2_2030_2_sum_ = Emp_cells2_2030_2_sum.copy()

    Emp_cells2_2030_2_sum_.rename(columns = {'cell':'cell_y'}, inplace = True)

    Emp_home_select_2030_new_values_merge_u_try5_4__ = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_4_,Emp_cells2_2030_2_sum_, how='left', left_on=['h_geocode_x'], right_on = ['h_geocode'],suffixes=('', '_remove'))

    Emp_home_select_2030_new_values_merge_u_try5_4_2 = Emp_home_select_2030_new_values_merge_u_try5_4__[Emp_home_select_2030_new_values_merge_u_try5_4__['cell_y']>Emp_home_select_2030_new_values_merge_u_try5_4__['C000']]
    
    Emp_home_select_2030_new_values_merge_u_try5_4_2 = Emp_home_select_2030_new_values_merge_u_try5_4_2.drop(['h_geocode_remove'],axis = 1)
    
    #Ignore the working zones that are the same as residential zones(when searching for new home zones for new employees)
    Emp_home_select_2030_new_values_merge_u_try5_4_2_1 =  Emp_home_select_2030_new_values_merge_u_try5_4_2[Emp_home_select_2030_new_values_merge_u_try5_4_2['w_geocode'] != Emp_home_select_2030_new_values_merge_u_try5_4_2['h_geocode_y']]

    Emp_home_select_2030_new_values_merge_u_try5_4_2_2 = Emp_home_select_2030_new_values_merge_u_try5_4_2_1[Emp_home_select_2030_new_values_merge_u_try5_4_2_1['w_geocode'] != Emp_home_select_2030_new_values_merge_u_try5_4_2_1['h_geocode_x']]

    
    #to get the min dist from orginal h_geocode (h_geocode_y) to w_geocode

    Emp_home_select_2030_new_values_merge_u_try5_4_2_2_ = Emp_home_select_2030_new_values_merge_u_try5_4_2_2.select_dtypes(exclude=['geometry'])

    Emp_home_select_2030_new_values_merge_u_try5_4_3 = Emp_home_select_2030_new_values_merge_u_try5_4_2_2_.groupby(["h_geocode_y"], as_index=False).min()
    Emp_home_select_2030_new_values_merge_u_try5_4_3 = Emp_home_select_2030_new_values_merge_u_try5_4_3[['dist']]
    Emp_home_select_2030_new_values_merge_u_try5_5 = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_4_3, Emp_home_select_2030_new_values_merge_u_try5_4_2_2,  how='left', 
                    left_on=['dist'], right_on = ['dist'])
    
    Emp_home_select_2030_new_values_merge_u_try5_5_1 = Emp_home_select_2030_new_values_merge_u_try5_5.reset_index()
    Emp_home_select_2030_new_values_merge_u_try5_5_1 = Emp_home_select_2030_new_values_merge_u_try5_5_1.astype({"index":'object'})
    Emp_home_select_2030_new_values_merge_u_try5_5_2 = Emp_home_select_2030_new_values_merge_u_try5_5_1.groupby(["h_geocode_y"], as_index=False)['dist_x'].min()
    Emp_home_select_2030_new_values_merge_u_try5_5_2 = Emp_home_select_2030_new_values_merge_u_try5_5_2[['dist_x']]
    Emp_home_select_2030_new_values_merge_u_try5_5_3 = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_5_2, Emp_home_select_2030_new_values_merge_u_try5_5_1,  how='left', 
                left_on=['dist_x'], right_on = ['dist_x'])
    Emp_home_select_2030_new_values_merge_u_try5_5_6 = Emp_home_select_2030_new_values_merge_u_try5_5_3.drop_duplicates(subset=['h_geocode_y'])
    Emp_home_select_2030_new_values_merge_u_try5_5_6 = Emp_home_select_2030_new_values_merge_u_try5_5_6.astype({"C000":'int64'})

    return Emp_home_select_2030_new_values_merge_u_try5_5_6, Emp_home_select_2030_new_values_merge_u_try5_4_2_2_

In [343]:
Emp_home_select_2030_new_values_merge_u_try5_5_6, Emp_home_select_2030_new_values_merge_u_try5_4_2_2_ = try_function2(Emp_home_select_2030_new_values_merge_u_try2, Emp_cells2_2030_2_sum)

Emp_home_select_2030_new_values_merge_u_try5_5_6

step1 done
step2 done
step3 done
step4 done
step5 done
step6 done
step7 done
step8 done

,dist_x,index,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,...,fd_id_y,found_ht_y,min_2030_y,geometry_x1,geometry_y1,geometry,fd_id,found_ht,cell_y,min_2030
0,6.968161,0,3.527525,120150102004018,120150201031014,12,015,010200,1089,120150102001089,...,1.524416e+10,24.5,0.0,"POLYGON ((-81.96930 26.98590, -81.96916 26.986...","POLYGON ((-81.97797 26.96409, -81.97786 26.964...","POLYGON ((-82.00558 27.02413, -82.00549 27.024...",15244164377,24.5,31,0.0
1,8.38327,3,0.59246,120150104021000,120150201014003,12,015,010402,1004,120150104021004,...,8.762873e+10,240.0,0.0,"POLYGON ((-82.06488 26.92035, -82.06486 26.920...","POLYGON ((-82.06464 26.92458, -82.06460 26.924...","POLYGON ((-82.03709 27.00262, -82.03526 27.002...",87628727774,240.0,178,0.0
2,4.357815,10,4.035699,120150103022027,120150104011000,12,015,010503,2026,120150105032026,...,1.121479e+11,184.5,0.0,"POLYGON ((-82.00152 26.94510, -81.99897 26.945...","POLYGON ((-82.04201 26.94058, -82.04074 26.941...","POLYGON ((-82.07890 26.91056, -82.07890 26.911...",112147941304,184.5,228,0.0
3,4.717145,151,4.804653,120150105032123,120150105052010,12,015,010503,2095,120150105032095,...,5.901239e+09,6.0,0.0,"POLYGON ((-81.96713 26.89864, -81.96514 26.898...","POLYGON ((-82.00568 26.92149, -82.00567 26.922...","POLYGON ((-82.02166 26.87867, -82.02165 26.878...",5901239272,6.0,12,0.0
4,0.791743,358,4.254489,120710101041007,120710101041003,12,015,010506,1014,120150105061014,...,9.853028e+10,956.0,0.0,"POLYGON ((-82.03731 26.79488, -82.03645 26.794...","POLYGON ((-82.06355 26.75709, -82.06332 26.757...","POLYGON ((-82.05619 26.75849, -82.05618 26.758...",98530275215,956.0,198,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964,4.690703,80978,3.3962,121150027422002,121150027471001,12,115,002747,2017,121150027472017,...,1.973146e+09,2.0,0.0,"POLYGON ((-82.12680 27.06676, -82.12665 27.066...","POLYGON ((-82.16166 27.06845, -82.15702 27.068...","POLYGON ((-82.11872 27.07576, -82.11801 27.075...",1973145951,2.0,4,0.0
965,3.215851,80860,9.582295,120150210032002,120150209001055,12,115,002746,1112,121150027461112,...,2.459449e+09,2.5,0.0,"POLYGON ((-82.11877 27.03726, -82.11841 27.037...","POLYGON ((-82.06549 26.96526, -82.06407 26.965...","POLYGON ((-82.07445 26.99138, -82.07349 26.992...",2459449040,2.5,5,0.0
966,4.39081,80867,3.509871,121150027462141,121150027461118,12,115,002746,1141,121150027461141,...,9.908125e+08,1.0,0.0,"POLYGON ((-82.12675 27.04653, -82.12396 27.048...","POLYGON ((-82.10346 27.07308, -82.10332 27.073...","POLYGON ((-82.11677 27.03402, -82.11677 27.034...",990812496,1.0,2,0.0
967,1.092537,80903,5.335091,121150027422028,121150027412026,12,115,002746,2138,121150027462138,...,2.476435e+09,2.5,0.0,"POLYGON ((-82.10879 27.07040, -82.10816 27.070...","POLYGON ((-82.16631 27.07370, -82.16627 27.073...","POLYGON ((-82.16416 27.08408, -82.16075 27.081...",2476435497,2.5,5,0.0
968,3.73842,80918,3.546679,121150027423002,121150027461117,12,115,002746,2167,121150027462167,...,9.907956e+08,1.0,0.0,"POLYGON ((-82.10480 27.06712, -82.10479 27.067...","POLYGON ((-82.15232 27.06869, -82.15230 27.068...","POLYGON ((-82.12285 27.04339, -82.12270 27.043...",990795645,1.0,2,0.0

In [344]:
Emp_home_select_2030_new_values_merge_u_try5_4_2_2_

,w_geocode,h_geocode_x,dist,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,...,C000_dmg_mean,h_geocode,fd_id_y,found_ht_y,min_2030_y,dist_x,fd_id,found_ht,cell_y,min_2030
0,120150102004018,120150201031014,3.527525,12,015,010200,1089,120150102001089,Block 1089,G5040,...,NaN,120150201031014,1.524416e+10,24.5,0.0,6.968161,15244164377,24.5,31,0.0
1,120150102004018,120150203021108,3.527525,12,015,010200,1089,120150102001089,Block 1089,G5040,...,NaN,120150203021108,3.445239e+09,4.5,0.0,18.286445,3445238588,4.5,7,0.0
2,120150102004018,120710701021006,3.527525,12,015,010200,1089,120150102001089,Block 1089,G5040,...,NaN,120710701021006,1.343226e+10,27.5,0.0,38.787842,13432257438,27.5,27,0.0
3,120150104021000,120150201014003,0.59246,12,015,010402,1004,120150104021004,Block 1004,G5040,...,NaN,120150201014003,8.762873e+10,240.0,0.0,8.38327,87628727774,240.0,178,0.0
1345,120150103022027,120150101001009,4.035699,12,015,010503,2026,120150105032026,Block 2026,G5040,...,NaN,120150101001009,5.408262e+09,12.5,0.0,19.336511,5408261652,12.5,11,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141315,120150203011091,121150027423031,4.170695,12,115,002747,2071,121150027472071,Block 2071,G5040,...,NaN,121150027423031,1.483366e+09,1.5,0.0,6.353888,1483366332,1.5,3,0.0
141316,120150203011091,121150027423033,4.170695,12,115,002747,2071,121150027472071,Block 2071,G5040,...,NaN,121150027423033,1.483236e+09,1.5,0.0,6.16494,1483236452,1.5,3,0.0
141319,120150203011091,121150027432069,4.170695,12,115,002747,2071,121150027472071,Block 2071,G5040,...,NaN,121150027432069,5.422657e+09,5.5,0.0,6.516598,5422656833,5.5,11,0.0
141321,120150203011091,121150027451072,4.170695,12,115,002747,2071,121150027472071,Block 2071,G5040,...,NaN,121150027451072,1.977790e+09,2.0,0.0,5.130062,1977789664,2.0,4,0.0
141323,120150203011091,121150027452020,4.170695,12,115,002747,2071,121150027472071,Block 2071,G5040,...,NaN,121150027452020,2.472517e+09,2.5,0.0,5.813214,2472517237,2.5,5,0.0

In [345]:
# select_2030__merge_try2 is the remaining zones from Emp_home_select_2030_new_values_merge_u_try5_5_6

select_2030__merge_try2 = Emp_home_select_2030_new_values_merge_u_try2.loc[~Emp_home_select_2030_new_values_merge_u_try2['h_geocode'].isin(Emp_home_select_2030_new_values_merge_u_try5_5_6['h_geocode_y'])]
len(select_2030__merge_try2)

55

In [346]:
#geometery_y1 for w_geocode and geometery_x1 for h_geocode

for j in range(2,loop_ended+1):
    globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].astype({"h_geocode":'int64'})

In [347]:
# select_hgeocode_geo5_6_try_try2_dic_missing = select_hgeocode_geo5_6_try_try2_dic_missing.drop(['w_geocode','h_geocode','h_geocode_x','geometry'], axis = 1)

# select_hgeocode_geo5_6_try_try2_dic_missing.rename(columns = {'h_geocode_y':'h_geocode'}, inplace = True)

for j in range(2,loop_ended+1):
    if 'geometry' in globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].columns:    
        globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].drop(['w_geocode','h_geocode','h_geocode_x','geometry'], axis = 1)
    else:
        globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].drop(['w_geocode','h_geocode','h_geocode_x'], axis = 1)

    globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].rename(columns = {'h_geocode_y':'h_geocode'}, inplace = True)

In [348]:
Emp_home_select_2030_part2_new2_temp =Emp_home_select_2030_part2_new2[['h_geocode','geometry']]

In [349]:
Emp_home_select_2030_part2_new2_temp.head()

         h_geocode                                           geometry
0  120710012051002  POLYGON ((-81.84015 26.61223, -81.83993 26.612...
1  120210104111000  POLYGON ((-81.69629 26.18436, -81.69546 26.184...
2  120210104081005  POLYGON ((-81.73524 26.20540, -81.73522 26.205...
3  120210112081028  POLYGON ((-81.44029 26.32594, -81.44019 26.326...
4  120810020031002  POLYGON ((-82.50990 27.50864, -82.50986 27.508...

In [350]:
select_hgeocode_geo5_6_try_try3_dic_missing

,dist_x,dist,h_geocode,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS18,CNS19,CNS20,cell_x,cell_y,C000,loop_num,cells_used,C000_dmg,C000_dmg_mean
2311_a_0,232.1955,4.616195,120879710021006,1,1,1,2,1,0,0,...,0,0,0,0.0,42.0,3,2,0,0,NaN
2313_a_0,232.1955,0.979693,120879710022018,0,2,1,3,0,0,0,...,0,0,0,1.0,42.0,1,2,0,0,NaN
2314_a_0,232.1955,1.237162,120879710022023,1,2,0,3,0,0,0,...,0,0,0,2.0,42.0,3,2,0,0,NaN
2317_a_0,232.1955,2.173152,120879710023012,0,2,1,3,0,0,0,...,1,0,0,0.0,42.0,3,2,0,0,NaN
2338_a_0,182.645421,2.485745,120879714011038,0,1,0,1,0,0,0,...,0,0,0,0.0,12.0,1,2,0,0,NaN
2339_a_0,182.645421,2.079728,120879714011052,1,1,0,2,0,0,0,...,0,0,0,0.0,12.0,2,2,0,0,NaN
2340_a_0,182.645421,4.81926,120879715022036,0,1,0,1,0,0,0,...,0,0,0,0.0,12.0,1,2,0,0,NaN
2343_a_0,38.916917,6.945383,120879714011050,0,1,1,2,0,0,0,...,0,0,0,0.0,77.0,2,2,0,0,NaN
2344_a_0,38.916917,7.45181,120879714012008,0,3,0,3,0,0,0,...,0,0,0,1.0,77.0,3,2,0,0,NaN
2345_a_0,38.916917,5.458475,120879714012055,0,7,2,9,0,0,0,...,1,0,0,0.0,77.0,9,2,0,0,NaN
2381_a_0,195.353561,0.830763,120879719003014,0,4,2,6,0,0,0,...,1,0,0,0.0,8.0,6,2,0,0,NaN
2423_a_0,80.18007,0.142819,120879728003012,0,1,0,1,0,0,0,...,0,0,0,0.0,77.0,1,2,0,0,NaN

In [351]:
for j in range(2,loop_ended+1):
    if 'geometry_x1' in globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].columns:       
        globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].rename(columns = {'geometry_x1':'geometry'}, inplace = True)
        globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].drop(['geometry_y1'], axis = 1)

    else:
         globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = pd.merge( globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)], Emp_home_select_2030_part2_new2_temp,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

In [352]:
select_hgeocode_geo5_6_try_try2_dic_missing

,h_geocode,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,CR05,...,CNS19,CNS20,cell_x,dist,cell_y,geometry,dist_x,cells_used,C000_dmg,C000_dmg_mean
105_a_0,120879714012003,6,1,3,2,6,0,0,0,0,...,0,0,0.0,2.486092,20.0,"POLYGON ((-81.35912 24.69543, -81.35903 24.695...",3.326614,0,0,NaN
258_a_0,120879714012004,1,0,1,0,1,0,0,0,0,...,1,0,0.0,0.904574,20.0,"POLYGON ((-81.35900 24.69076, -81.35884 24.690...",4.532331,0,0,NaN
472_a_0,120710403034025,8,2,5,3,8,2,0,0,0,...,0,0,0.0,1.80009,16.0,"POLYGON ((-81.67332 26.60590, -81.67264 26.605...",1.550353,2,0,NaN
772_a_0,120879711002066,2,0,1,1,2,0,0,0,0,...,0,0,0.0,1.02721,20.0,"POLYGON ((-81.06114 24.72875, -81.06099 24.728...",34.134872,0,0,NaN
773_a_0,120879710021001,2,1,5,3,8,1,0,0,0,...,1,0,0.0,1.829846,23.0,"POLYGON ((-80.95780 24.76478, -80.95737 24.765...",49.646291,7,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8173_a_0,120879706001017,3,0,2,1,3,0,0,0,0,...,0,0,1.0,0.804102,4.0,"POLYGON ((-80.48780 25.04786, -80.48750 25.048...",7.545299,0,0,NaN
8184_a_0,120879706001043,5,0,6,6,11,0,0,0,0,...,0,0,1.0,36.020444,18.0,"POLYGON ((-80.50047 25.03420, -80.50030 25.034...",172.404988,6,0,NaN
8287_a_0,120879715011015,2,0,1,1,2,0,0,0,0,...,0,0,0.0,1.671089,4.0,"POLYGON ((-81.47403 24.65405, -81.47402 24.654...",1.18747,0,0,NaN
8432_a_0,120879714012079,1,1,0,0,1,0,0,0,0,...,0,0,0.0,1.68253,20.0,"POLYGON ((-81.35902 24.68678, -81.35902 24.687...",4.532331,0,0,NaN
8441_a_0,120879714021078,7,0,3,4,5,2,0,0,0,...,0,0,0.0,1.385731,20.0,"POLYGON ((-81.37512 24.70866, -81.37511 24.709...",3.358103,0,0,NaN

In [353]:
select_hgeocode_geo5_6_try_try2_dic_missing.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62 entries, 105_a_0 to 8441_a_0
Data columns (total 50 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   h_geocode      62 non-null     int64
 1   C000           62 non-null     int64
 2   CA01           62 non-null     int64
 3   CA02           62 non-null     int64
 4   CA03           62 non-null     int64
 5   CR01           62 non-null     int64
 6   CR02           62 non-null     int64
 7   CR03           62 non-null     int64
 8   CR04           62 non-null     int64
 9   CR05           62 non-null     int64
 10  CR07           62 non-null     int64
 11  CE01           62 non-null     int64
 12  CE02           62 non-null     int64
 13  CE03           62 non-null     int64
 14  CT01           62 non-null     int64
 15  CT02           62 non-null     int64
 16  CD01           62 non-null     int64
 17  CD02           62 non-null     int64
 18  CD03           62 non-null     int64
 19  CD04           62 non-null     int64
 20  CS01           62 non-null     int64
 21  CS02           62 non-null     int64
 22  CNS01          62 non-null     int64
 23  CNS02          62 non-null     int64
 24  CNS03          62 non-null     int64
 25  CNS04          62 non-null     int64
 26  CNS05          62 non-null     int64
 27  CNS06          62 non-null     int64
 28  CNS07          62 non-null     int64
 29  CNS08          62 non-null     int64
 30  CNS09          62 non-null     int64
 31  CNS10          62 non-null     int64
 32  CNS11          62 non-null     int64
 33  CNS12          62 non-null     int64
 34  CNS13          62 non-null     int64
 35  CNS14          62 non-null     int64
 36  CNS15          62 non-null     int64
 37  CNS16          62 non-null     int64
 38  CNS17          62 non-null     int64
 39  CNS18          62 non-null     int64
 40  CNS19          62 non-null     int64
 41  CNS20          62 non-null     int64
 42  cell_x         62 non-null     float64
 43  dist           62 non-null     object
 44  cell_y         62 non-null     float64
 45  geometry       62 non-null     geometry
 46  dist_x         62 non-null     object
 47  cells_used     62 non-null     int64
 48  C000_dmg       62 non-null     int64
 49  C000_dmg_mean  0 non-null      float64
dtypes: float64(3), geometry(1), int64(44), object(2)
memory usage: 24.7+ KB

In [354]:
select_hgeocode_geo5_6_try_try3_dic_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 51 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   dist_x         12 non-null     object
 1   dist           12 non-null     object
 2   h_geocode      12 non-null     int64
 3   CA01           12 non-null     int64
 4   CA02           12 non-null     int64
 5   CA03           12 non-null     int64
 6   CR01           12 non-null     int64
 7   CR02           12 non-null     int64
 8   CR03           12 non-null     int64
 9   CR04           12 non-null     int64
 10  CR05           12 non-null     int64
 11  CR07           12 non-null     int64
 12  CE01           12 non-null     int64
 13  CE02           12 non-null     int64
 14  CE03           12 non-null     int64
 15  CT01           12 non-null     int64
 16  CT02           12 non-null     int64
 17  CD01           12 non-null     int64
 18  CD02           12 non-null     int64
 19  CD03           12 non-null     int64
 20  CD04           12 non-null     int64
 21  CS01           12 non-null     int64
 22  CS02           12 non-null     int64
 23  CNS01          12 non-null     int64
 24  CNS02          12 non-null     int64
 25  CNS03          12 non-null     int64
 26  CNS04          12 non-null     int64
 27  CNS05          12 non-null     int64
 28  CNS06          12 non-null     int64
 29  CNS07          12 non-null     int64
 30  CNS08          12 non-null     int64
 31  CNS09          12 non-null     int64
 32  CNS10          12 non-null     int64
 33  CNS11          12 non-null     int64
 34  CNS12          12 non-null     int64
 35  CNS13          12 non-null     int64
 36  CNS14          12 non-null     int64
 37  CNS15          12 non-null     int64
 38  CNS16          12 non-null     int64
 39  CNS17          12 non-null     int64
 40  CNS18          12 non-null     int64
 41  CNS19          12 non-null     int64
 42  CNS20          12 non-null     int64
 43  cell_x         12 non-null     float64
 44  cell_y         12 non-null     float64
 45  C000           12 non-null     int64
 46  loop_num       12 non-null     int64
 47  cells_used     12 non-null     int64
 48  C000_dmg       12 non-null     int64
 49  C000_dmg_mean  0 non-null      float64
 50  geometry       12 non-null     geometry
dtypes: float64(3), geometry(1), int64(45), object(2)
memory usage: 4.9+ KB

In [355]:
# for i in range(2, loop_ended+1):
#     globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)] = gpd.GeoDataFrame(globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)], geometry='geometry')
    
#     globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)].to_crs("EPSG:4326")

select_2030__merge_try2_=pd.concat([select_2030__merge_try2, select_hgeocode_geo5_6_try_try2_dic_missing,select_hgeocode_geo5_6_try_try3_dic_missing], axis=0)
    
len(select_2030__merge_try2_)

129

In [356]:
select_2030__merge_try2_

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,cell,min_2030,cells_used,C000_dmg,C000_dmg_mean,cell_x,dist,cell_y,dist_x,loop_num
5_a_0,12,081,000304,1005,120810003041005,Block 1005,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
13_a_0,12,071,000303,3006,120710003033006,Block 3006,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
33_a_0,12,071,040301,2007,120710403012007,Block 2007,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
55_a_0,12,071,050603,2017,120710506032017,Block 2017,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
69_a_0,12,115,002743,2017,121150027432017,Block 2017,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,0.0,6.945383,77.0,38.916917,2.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,1.0,7.45181,77.0,38.916917,2.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,0.0,5.458475,77.0,38.916917,2.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,0.0,0.830763,8.0,195.353561,2.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,0.0,0.142819,77.0,80.18007,2.0

In [357]:
Emp_cells_sum_no_dups_final_geo2

,h_geocode,cell,geometry,centr,centr_co,cell_remain
0,120150101001000,8,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",8
1,120150101001005,3,"POLYGON ((-81.71209 26.97490, -81.71177 26.974...",POINT (26.96410 -81.68482),"(26.9640954048572, -81.68481803155792)",3
2,120150101001010,5,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",5
3,120150101001011,1,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",1
4,120150101001014,4,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",4
...,...,...,...,...,...,...
17117,121150027472068,1,"POLYGON ((-82.14348 27.03837, -82.14304 27.038...",POINT (27.03798 -82.14217),"(27.03798107697083, -82.14216555983586)",1
17118,121150027472069,5,"POLYGON ((-82.14445 27.03720, -82.14444 27.037...",POINT (27.03731 -82.14328),"(27.03730758631683, -82.14328497861773)",5
17119,121150027472070,4,"POLYGON ((-82.14693 27.03859, -82.14691 27.038...",POINT (27.03854 -82.14601),"(27.038540446197718, -82.14600924202706)",4
17120,121150027472071,2,"POLYGON ((-82.13975 27.05094, -82.13947 27.051...",POINT (27.05049 -82.13887),"(27.05048945351484, -82.13886747332714)",2
17121,121150027482003,5,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)",5

In [358]:
if 'cell' in Emp_cells_sum_no_dups_final_geo2.columns:   
    Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.drop(['cell'], axis = 1)
else:
    pass
Emp_cells_sum_no_dups_final_geo2

,h_geocode,geometry,centr,centr_co,cell_remain
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",8
1,120150101001005,"POLYGON ((-81.71209 26.97490, -81.71177 26.974...",POINT (26.96410 -81.68482),"(26.9640954048572, -81.68481803155792)",3
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",5
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",1
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",4
...,...,...,...,...,...
17117,121150027472068,"POLYGON ((-82.14348 27.03837, -82.14304 27.038...",POINT (27.03798 -82.14217),"(27.03798107697083, -82.14216555983586)",1
17118,121150027472069,"POLYGON ((-82.14445 27.03720, -82.14444 27.037...",POINT (27.03731 -82.14328),"(27.03730758631683, -82.14328497861773)",5
17119,121150027472070,"POLYGON ((-82.14693 27.03859, -82.14691 27.038...",POINT (27.03854 -82.14601),"(27.038540446197718, -82.14600924202706)",4
17120,121150027472071,"POLYGON ((-82.13975 27.05094, -82.13947 27.051...",POINT (27.05049 -82.13887),"(27.05048945351484, -82.13886747332714)",2
17121,121150027482003,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)",5

In [359]:
if 'cell_remain' in Emp_cells_sum_no_dups_final_geo2.columns:   
    Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.drop(['cell_remain'], axis = 1)
else:
    pass
Emp_cells_sum_no_dups_final_geo2

,h_geocode,geometry,centr,centr_co
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)"
1,120150101001005,"POLYGON ((-81.71209 26.97490, -81.71177 26.974...",POINT (26.96410 -81.68482),"(26.9640954048572, -81.68481803155792)"
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)"
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)"
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)"
...,...,...,...,...
17117,121150027472068,"POLYGON ((-82.14348 27.03837, -82.14304 27.038...",POINT (27.03798 -82.14217),"(27.03798107697083, -82.14216555983586)"
17118,121150027472069,"POLYGON ((-82.14445 27.03720, -82.14444 27.037...",POINT (27.03731 -82.14328),"(27.03730758631683, -82.14328497861773)"
17119,121150027472070,"POLYGON ((-82.14693 27.03859, -82.14691 27.038...",POINT (27.03854 -82.14601),"(27.038540446197718, -82.14600924202706)"
17120,121150027472071,"POLYGON ((-82.13975 27.05094, -82.13947 27.051...",POINT (27.05049 -82.13887),"(27.05048945351484, -82.13886747332714)"
17121,121150027482003,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)"

In [360]:
Emp_cells_sum_no_dups_final_geo2_2030_final2 = pd.merge(Emp_cells_sum_no_dups_final_geo2, Emp_cells2_2030_2_sum,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])
len(Emp_cells_sum_no_dups_final_geo2_2030_final2)

17122

In [361]:
Emp_cells_sum_no_dups_final_geo2_2030_final2

,h_geocode,geometry,centr,centr_co,fd_id,found_ht,cell,min_2030
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",3.934161e+09,12.0,8.0,0.0
1,120150101001005,"POLYGON ((-81.71209 26.97490, -81.71177 26.974...",POINT (26.96410 -81.68482),"(26.9640954048572, -81.68481803155792)",9.833130e+08,3.0,2.0,0.0
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",2.458357e+09,3.5,5.0,0.0
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",4.916611e+08,1.5,1.0,0.0
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",1.969459e+09,4.0,4.0,0.0
...,...,...,...,...,...,...,...,...
17117,121150027472068,"POLYGON ((-82.14348 27.03837, -82.14304 27.038...",POINT (27.03798 -82.14217),"(27.03798107697083, -82.14216555983586)",NaN,NaN,NaN,NaN
17118,121150027472069,"POLYGON ((-82.14445 27.03720, -82.14444 27.037...",POINT (27.03731 -82.14328),"(27.03730758631683, -82.14328497861773)",2.475195e+09,2.5,5.0,0.0
17119,121150027472070,"POLYGON ((-82.14693 27.03859, -82.14691 27.038...",POINT (27.03854 -82.14601),"(27.038540446197718, -82.14600924202706)",1.971686e+09,2.0,4.0,0.0
17120,121150027472071,"POLYGON ((-82.13975 27.05094, -82.13947 27.051...",POINT (27.05049 -82.13887),"(27.05048945351484, -82.13886747332714)",NaN,NaN,NaN,NaN
17121,121150027482003,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)",1.478765e+09,1.5,3.0,0.0

In [362]:
Emp_cells_sum_no_dups_final_geo2_2030_final2 = Emp_cells_sum_no_dups_final_geo2_2030_final2.drop([
    'min_2030'
],axis=1)

In [363]:
Emp_home_select_2030_new_values_merge[Emp_home_select_2030_new_values_merge['C000']<0]

Empty GeoDataFrame
Columns: [STATEFP20, COUNTYFP20, TRACTCE20, BLOCKCE20, GEOID20, NAME20, MTFCC20, UR20, UACE20, UATYPE20, FUNCSTAT20, ALAND20, AWATER20, INTPTLAT20, INTPTLON20, h_geocode, C000, CA01, CA02, CA03, CE01, CE02, CE03, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, CR01, CR02, CR03, CR04, CR05, CR07, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, createdate, geometry, cell]
Index: []

[0 rows x 60 columns]

In [364]:
select_2030__merge_try2 = select_2030__merge_try2_.copy()

In [365]:

        
select_2030__merge_try2['centr'] = ''


for n in range(0,len(select_2030__merge_try2)):
    select_2030__merge_try2.iloc[n,select_2030__merge_try2.columns.get_loc("centr")]\
    = select_2030__merge_try2.iloc\
    [n,select_2030__merge_try2.columns.get_loc("geometry")].centroid.wkt
    
select_2030__merge_try2['centr'] = gpd.GeoSeries.from_wkt(select_2030__merge_try2['centr'])
select_2030__merge_try2 = gpd.GeoDataFrame(select_2030__merge_try2, geometry='centr')

for n in range(0,len(select_2030__merge_try2)):
    select_2030__merge_try2.iloc[n, select_2030__merge_try2.columns.get_loc("centr")] = transform(lambda x, y: (y, x),
                        select_2030__merge_try2.iloc[n, select_2030__merge_try2.columns.get_loc("centr")])

coord_list =  select_2030__merge_try2['centr'].geometry.apply(lambda p: list(p.coords)[0])
select_2030__merge_try2['centr_x_co'] = coord_list

In [366]:
# select_2030__merge_try2['h_geocode']

In [367]:
select_2030__merge_try2.head()

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,cells_used,C000_dmg,C000_dmg_mean,cell_x,dist,cell_y,dist_x,loop_num,centr,centr_x_co
5_a_0,12,081,000304,1005,120810003041005,Block 1005,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (27.44387 -82.57167),"(27.443871885889017, -82.57166692688503)"
13_a_0,12,071,000303,3006,120710003033006,Block 3006,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (26.67997 -81.81831),"(26.679967839065085, -81.81831089441661)"
33_a_0,12,071,040301,2007,120710403012007,Block 2007,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (26.60909 -81.70739),"(26.609092407625464, -81.7073913333572)"
55_a_0,12,071,050603,2017,120710506032017,Block 2017,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (26.33356 -81.79809),"(26.333560243311474, -81.79808611592769)"
69_a_0,12,115,002743,2017,121150027432017,Block 2017,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (27.05396 -82.18513),"(27.053958169803494, -82.18512562690302)"

In [368]:
# Emp_home_select_2030_part2_new2_temp

In [547]:
# select_2030__merge_try2_temp = pd.merge(select_2030__merge_try2, Emp_home_select_2030_part2_new2_temp,  how='left', 
#                 left_on=['geometry'], right_on = ['geometry'])
# select_2030__merge_try2_temp.head()

In [370]:
# select_2030__merge_try2_temp= select_2030__merge_try2_temp.drop(['h_geocode_x'],axis=1)

# select_2030__merge_try2_temp.rename(columns = {'h_geocode_y':'h_geocode'}, inplace = True)

In [371]:
# select_2030__merge_try2=select_2030__merge_try2_temp.copy()

In [372]:
select_2030__merge_try2 = select_2030__merge_try2.astype({"h_geocode":'int64'})
select_2030__merge_try2['h_geocode']

5_a_0     120810003041005
13_a_0    120710003033006
33_a_0    120710403012007
55_a_0    120710506032017
69_a_0    121150027432017
               ...
7         120879714011050
8         120879714012008
9         120879714012055
10        120879719003014
11        120879728003012
Name: h_geocode, Length: 129, dtype: int64

In [373]:
len(Emp_cells_sum_no_dups_final_geo2_2030_final2)

17122

In [374]:
Emp_cells_sum_no_dups_final_geo2_2030_final2 = Emp_cells_sum_no_dups_final_geo2_2030_final2.loc[~Emp_cells_sum_no_dups_final_geo2_2030_final2['h_geocode'].isin(select_2030__merge_try2['h_geocode'])]

len(Emp_cells_sum_no_dups_final_geo2_2030_final2)

17095

In [375]:
select_2030__merge_try2 = select_2030__merge_try2.reset_index()

select_2030__merge_try2 = select_2030__merge_try2.drop(['index'], axis = 1)

In [376]:
Emp_cells_sum_no_dups_final_geo2_2030_final2

,h_geocode,geometry,centr,centr_co,fd_id,found_ht,cell
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",3.934161e+09,12.0,8.0
1,120150101001005,"POLYGON ((-81.71209 26.97490, -81.71177 26.974...",POINT (26.96410 -81.68482),"(26.9640954048572, -81.68481803155792)",9.833130e+08,3.0,2.0
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",2.458357e+09,3.5,5.0
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",4.916611e+08,1.5,1.0
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",1.969459e+09,4.0,4.0
...,...,...,...,...,...,...,...
17117,121150027472068,"POLYGON ((-82.14348 27.03837, -82.14304 27.038...",POINT (27.03798 -82.14217),"(27.03798107697083, -82.14216555983586)",NaN,NaN,NaN
17118,121150027472069,"POLYGON ((-82.14445 27.03720, -82.14444 27.037...",POINT (27.03731 -82.14328),"(27.03730758631683, -82.14328497861773)",2.475195e+09,2.5,5.0
17119,121150027472070,"POLYGON ((-82.14693 27.03859, -82.14691 27.038...",POINT (27.03854 -82.14601),"(27.038540446197718, -82.14600924202706)",1.971686e+09,2.0,4.0
17120,121150027472071,"POLYGON ((-82.13975 27.05094, -82.13947 27.051...",POINT (27.05049 -82.13887),"(27.05048945351484, -82.13886747332714)",NaN,NaN,NaN
17121,121150027482003,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)",1.478765e+09,1.5,3.0

In [377]:
find_cells(Emp_cells_sum_no_dups_final_geo2_2030_final2,select_2030__merge_try2)

n1= 0
temprory4=             h_geocode      dist  cell
6533  120810003041002  0.554835   8.0
RHS= 120810003041002
C000= 1
cell_remain= 7.0
n1= 1
temprory4=             h_geocode      dist  cell
2215  120710003033007  0.240467   3.0
RHS= 120710003033007
C000= 1
cell_remain= 2.0
n1= 2
temprory4=             h_geocode      dist  cell
5362  120710403012009  0.470605  45.0
RHS= 120710403012009
C000= 1
cell_remain= 44.0
n1= 3
temprory4=             h_geocode      dist  cell
6311  120710506032005  0.299073  12.0
RHS= 120710506032005
C000= 1
cell_remain= 11.0
n1= 4
temprory4=             h_geocode      dist  cell
4240  121150027431040  0.425919  10.0
RHS= 121150027431040
C000= 9
cell_remain= 1.0
n1= 5
temprory4=             h_geocode      dist  cell
8985  121150013031026  0.104343   2.0
RHS= 121150013031026
C000= 1
cell_remain= 1.0
n1= 6
temprory4=            h_geocode     dist  cell
723  120710004012011  4.29318  14.0
RHS= 120710004012011
C000= 12
cell_remain= 2.0
n1= 7
temprory4=             h_geocode     dist  cell
1804  120710301003008  3.49824  10.0
RHS= 120710301003008
C000= 8
cell_remain= 2.0
n1= 8
temprory4=             h_geocode      dist  cell
1641  120810014021036  0.925018  22.0
RHS= 120810014021036
C000= 15
cell_remain= 7.0
n1= 9
temprory4=            h_geocode      dist  cell
330  120150204013025  0.495519  12.0
RHS= 120150204013025
C000= 1
cell_remain= 11.0
n1= 10
temprory4=             h_geocode     dist  cell
2553  120710019191003  0.48183  38.0
RHS= 120710019191003
C000= 1
cell_remain= 37.0
n1= 11
temprory4=             h_geocode     dist  cell
1401  120710016011001  0.63111   5.0
RHS= 120710016011001
C000= 4
cell_remain= 1.0
n1= 12
temprory4=             h_geocode      dist  cell
6505  121150013011010  0.383901   4.0
RHS= 121150013011010
C000= 3
cell_remain= 1.0
n1= 13
temprory4=            h_geocode      dist  cell
247  120210002002027  0.813503   6.0
RHS= 120210002002027
C000= 5
cell_remain= 1.0
n1= 14
temprory4=            h_geocode      dist  cell
736  120710401382026  0.675821  70.0
RHS= 120710401382026
C000= 22
cell_remain= 48.0
n1= 15
temprory4=          h_geocode     dist  cell
4  120150104052021  0.71053  27.0
RHS= 120150104052021
C000= 13
cell_remain= 14.0
n1= 16
temprory4=             h_geocode      dist  cell
1023  120210104332001  0.829104   7.0
RHS= 120210104332001
C000= 3
cell_remain= 4.0
n1= 17
temprory4=             h_geocode      dist  cell
9500  121150018041006  0.370001   2.0
RHS= 121150018041006
C000= 1
cell_remain= 1.0
n1= 18
temprory4=             h_geocode     dist  cell
1972  120210109062009  1.32433   4.0
RHS= 120210109062009
C000= 1
cell_remain= 3.0
n1= 19
temprory4=            h_geocode      dist  cell
438  120150206021015  0.806449   2.0
RHS= 120150206021015
C000= 1
cell_remain= 1.0
n1= 20
temprory4=             h_geocode      dist  cell
2419  121150027391006  1.346909  24.0
RHS= 121150027391006
C000= 16
cell_remain= 8.0
n1= 21
temprory4=             h_geocode      dist  cell
1598  120710013002003  0.223427   5.0
RHS= 120710013002003
C000= 3
cell_remain= 2.0
n1= 22
temprory4=             h_geocode      dist  cell
5441  120710403032034  0.412438   2.0
RHS= 120710403032034
C000= 1
cell_remain= 1.0
n1= 23
temprory4=             h_geocode      dist  cell
8796  121150010002001  0.349258   3.0
RHS= 121150010002001
C000= 1
cell_remain= 2.0
n1= 24
temprory4=             h_geocode      dist  cell
6325  120710601011013  0.987954   7.0
RHS= 120710601011013
C000= 1
cell_remain= 6.0
n1= 25
temprory4=             h_geocode      dist  cell
8478  121150025041020  0.098623  19.0
RHS= 121150025041020
C000= 2
cell_remain= 17.0
n1= 26
temprory4=             h_geocode      dist  cell
4816  120710401211024  0.821831   2.0
RHS= 120710401211024
C000= 1
cell_remain= 1.0
n1= 27
temprory4=             h_geocode        dist  cell
1059  120210109072034  153.497156   9.0
RHS= 120210109072034
C000= 5
cell_remain= 4.0
n1= 28
temprory4=             h_geocode      dist  cell
1675  120210111092019  0.334457  21.0
RHS= 120210111092019
C000= 2
cell_remain= 19.0
n1= 29
temprory4=             h_geocode     dist  cell
8339  121150027451034  0.18259   9.0
RHS= 121150027451034
C000= 3
cell_remain= 6.0
n1= 30
temprory4=             h_geocode      dist  cell
9518  121150027432055  0.444965   6.0
RHS= 121150027432055
C000= 2
cell_remain= 4.0
n1= 31
temprory4=             h_geocode     dist  cell
3303  120710202022000  1.42262   6.0
RHS= 120710202022000
C000= 3
cell_remain= 3.0
n1= 32
temprory4=              h_geocode      dist  cell
10124  121150025052041  0.130268   8.0
RHS= 121150025052041
C000= 1
cell_remain= 7.0
n1= 33
temprory4=             h_geocode      dist  cell
8317  121150027432059  0.111325   7.0
RHS= 121150027432059
C000= 3
cell_remain= 4.0
n1= 34
temprory4=            h_geocode      dist  cell
214  120150202041066  0.125501   2.0
RHS= 120150202041066
C000= 1
cell_remain= 1.0
n1= 35
temprory4=            h_geocode      dist  cell
702  120150303013024  0.321229   2.0
RHS= 120150303013024
C000= 1
cell_remain= 1.0
n1= 36
temprory4=            h_geocode      dist  cell
239  120150202052039  0.182957   4.0
RHS= 120150202052039
C000= 1
cell_remain= 3.0
n1= 37
temprory4=             h_geocode      dist  cell
8555  121150025072029  0.076106  14.0
RHS= 121150025072029
C000= 2
cell_remain= 12.0
n1= 38
temprory4=             h_geocode     dist  cell
9533  121150019032004  0.16276   2.0
RHS= 121150019032004
C000= 1
cell_remain= 1.0
n1= 39
temprory4=             h_geocode      dist  cell
2144  120710102051002  0.401063   5.0
RHS= 120710102051002
C000= 3
cell_remain= 2.0
n1= 40
temprory4=             h_geocode      dist  cell
3828  120710205022008  0.290759   7.0
RHS= 120710205022008
C000= 2
cell_remain= 5.0
n1= 41
temprory4=             h_geocode        dist  cell
1967  120210109061018  151.051419   2.0
RHS= 120210109061018
C000= 1
cell_remain= 1.0
n1= 42
temprory4=             h_geocode        dist  cell
1585  120210109061022  140.383551   3.0
RHS= 120210109061022
C000= 2
cell_remain= 1.0
n1= 43
temprory4=            h_geocode      dist  cell
460  120150208001040  0.226761   8.0
RHS= 120150208001040
C000= 1
cell_remain= 7.0
n1= 44
temprory4=             h_geocode      dist  cell
2155  120710102051058  0.105924   7.0
RHS= 120710102051058
C000= 3
cell_remain= 4.0
n1= 45
temprory4=             h_geocode     dist  cell
8524  121150001042008  0.36493   4.0
RHS= 121150001042008
C000= 1
cell_remain= 3.0
n1= 46
temprory4=             h_geocode      dist   cell
7508  120810014021002  0.755967  137.0
RHS= 120810014021002
C000= 1
cell_remain= 136.0
n1= 47
temprory4=             h_geocode      dist  cell
2779  120710104191013  0.295649   9.0
RHS= 120710104191013
C000= 3
cell_remain= 6.0
n1= 48
temprory4=            h_geocode      dist  cell
488  120150209003009  0.280772   9.0
RHS= 120150209003009
C000= 1
cell_remain= 8.0
n1= 49
temprory4=           h_geocode      dist  cell
50  120150305062012  0.190292  19.0
RHS= 120150305062012
C000= 13
cell_remain= 6.0
n1= 50
temprory4=             h_geocode      dist  cell
5623  120710403142143  0.325499   3.0
RHS= 120710403142143
C000= 1
cell_remain= 2.0
n1= 51
temprory4=             h_geocode    dist  cell
1567  120710103083028  0.0921   8.0
RHS= 120710103083028
C000= 6
cell_remain= 2.0
n1= 52
temprory4=             h_geocode      dist  cell
3749  120710402124028  0.285175   4.0
RHS= 120710402124028
C000= 3
cell_remain= 1.0
n1= 53
temprory4=            h_geocode     dist  cell
375  120150205011024  0.20427   4.0
RHS= 120150205011024
C000= 1
cell_remain= 3.0
n1= 54
temprory4=             h_geocode      dist  cell
9555  121150027451043  0.182917   4.0
RHS= 121150027451043
C000= 2
cell_remain= 2.0
n1= 55
temprory4=            h_geocode        dist  cell
954  120210110033006  139.769725  10.0
RHS= 120210110033006
C000= 6
cell_remain= 4.0
n1= 56
temprory4=             h_geocode        dist  cell
1965  120210109061014  139.760391   2.0
RHS= 120210109061014
C000= 1
cell_remain= 1.0
n1= 57
temprory4=             h_geocode      dist  cell
2002  120710403042009  0.914157  11.0
RHS= 120710403042009
C000= 8
cell_remain= 3.0
n1= 58
temprory4=             h_geocode        dist  cell
1613  120210109072033  147.053969   3.0
RHS= 120210109072033
C000= 2
cell_remain= 1.0

n1= 59
temprory4=             h_geocode        dist  cell
1584  120210109061011  148.732008   3.0
RHS= 120210109061011
C000= 2
cell_remain= 1.0
n1= 60
temprory4=            h_geocode        dist  cell
955  120210110033019  141.314664   8.0
RHS= 120210110033019
C000= 6
cell_remain= 2.0
n1= 61
temprory4=             h_geocode        dist  cell
1620  120210110033012  148.856867   5.0
RHS= 120210110033012
C000= 2
cell_remain= 3.0
n1= 62
temprory4=             h_geocode        dist  cell
1400  120210110033006  151.025842   4.0
RHS= 120210110033006
C000= 3
cell_remain= 1.0
n1= 63
temprory4=             h_geocode        dist  cell
2003  120210110033012  151.558239   3.0
RHS= 120210110033012
C000= 1
cell_remain= 2.0
n1= 64
temprory4=             h_geocode        dist  cell
2003  120210110033012  150.549035   2.0
RHS= 120210110033012
C000= 1
cell_remain= 1.0
n1= 65
temprory4=             h_geocode      dist  cell
4023  120710401242051  0.193449   3.0
RHS= 120710401242051
C000= 2
cell_remain= 1.0
n1= 66
temprory4=             h_geocode        dist  cell
1964  120210109061015  140.477457   2.0
RHS= 120210109061015
C000= 1
cell_remain= 1.0
n1= 67
temprory4=             h_geocode        dist  cell
1200  120210110033017  143.453998  10.0
RHS= 120210110033017
C000= 4
cell_remain= 6.0
n1= 68
temprory4=             h_geocode        dist  cell
1619  120210110033017  151.695429   6.0
RHS= 120210110033017
C000= 2
cell_remain= 4.0
n1= 69
temprory4=             h_geocode        dist  cell
2003  120210110033019  151.428357   2.0
RHS= 120210110033019
C000= 1
cell_remain= 1.0
n1= 70
temprory4=            h_geocode        dist  cell
778  120210109061003  153.568068  10.0
RHS= 120210109061003
C000= 8
cell_remain= 2.0
n1= 71
temprory4=             h_geocode        dist  cell
1995  120210109072034  146.488665   4.0
RHS= 120210109072034
C000= 1
cell_remain= 3.0
n1= 72
temprory4=             h_geocode      dist  cell
2002  120210110033017  150.7873   4.0
RHS= 120210110033017
C000= 1
cell_remain= 3.0
n1= 73
temprory4=             h_geocode        dist  cell
1995  120210109072034  142.901905   3.0
RHS= 120210109072034
C000= 1
cell_remain= 2.0
n1= 74
temprory4=             h_geocode        dist  cell
2002  120210110033017  152.173494   3.0
RHS= 120210110033017
C000= 1
cell_remain= 2.0
n1= 75
temprory4=             h_geocode        dist  cell
1612  120210109072038  143.751378   3.0
RHS= 120210109072038
C000= 2
cell_remain= 1.0
n1= 76
temprory4=             h_geocode      dist  cell
1070  120710402102065  2.575911  27.0
RHS= 120710402102065
C000= 15
cell_remain= 12.0
n1= 77
temprory4=             h_geocode        dist  cell
2001  120210110033017  151.232907   2.0
RHS= 120210110033017
C000= 1
cell_remain= 1.0
n1= 78
temprory4=          h_geocode      dist  cell
2  120150104012003  7.276351  38.0
RHS= 120150104012003
C000= 13
cell_remain= 25.0
n1= 79
temprory4=             h_geocode        dist  cell
2060  120210111111002  156.124394   7.0
RHS= 120210111111002
C000= 1
cell_remain= 6.0
n1= 80
temprory4=             h_geocode      dist  cell
1269  120710403051007  0.997329  23.0
RHS= 120710403051007
C000= 13
cell_remain= 10.0
n1= 81
temprory4=             h_geocode        dist  cell
1995  120210109072034  143.326014   2.0
RHS= 120210109072034
C000= 1
cell_remain= 1.0
n1= 82
temprory4=             h_geocode       dist  cell
1053  120210109072021  141.58332  32.0
RHS= 120210109072021
C000= 5
cell_remain= 27.0
n1= 83
temprory4=             h_geocode        dist  cell
1969  120210109071010  151.482181  41.0
RHS= 120210109071010
C000= 1
cell_remain= 40.0
n1= 84
temprory4=             h_geocode       dist  cell
1611  120210109072037  142.54861   4.0
RHS= 120210109072037
C000= 2
cell_remain= 2.0
n1= 85
temprory4=             h_geocode      dist  cell
2526  120710403042002  0.476646  11.0
RHS= 120710403042002
C000= 6
cell_remain= 5.0
n1= 86
temprory4=             h_geocode        dist  cell
1969  120210109071010  152.388929  40.0
RHS= 120210109071010
C000= 1
cell_remain= 39.0
n1= 87
temprory4=             h_geocode        dist  cell
1588  120210109071010  151.325652  39.0
RHS= 120210109071010
C000= 2
cell_remain= 37.0
n1= 88
temprory4=             h_geocode      dist  cell
5396  120710403023018  0.181156  25.0
RHS= 120710403023018
C000= 1
cell_remain= 24.0
n1= 89
temprory4=             h_geocode      dist  cell
1882  120710101062006  0.192003   8.0
RHS= 120710101062006
C000= 3
cell_remain= 5.0
n1= 90
temprory4=             h_geocode       dist  cell
1605  120210109072021  138.72102  27.0
RHS= 120210109072021
C000= 2
cell_remain= 25.0
n1= 91
temprory4=             h_geocode        dist  cell
1588  120210109071010  151.284936  37.0
RHS= 120210109071010
C000= 2
cell_remain= 35.0
n1= 92
temprory4=             h_geocode       dist  cell
1605  120210109072021  142.87367  25.0
RHS= 120210109072021
C000= 2
cell_remain= 23.0
n1= 93
temprory4=            h_geocode        dist  cell
863  120210109072021  143.315173  23.0
RHS= 120210109072021
C000= 7
cell_remain= 16.0
n1= 94
temprory4=             h_geocode        dist  cell
1969  120210109071010  152.409081  35.0
RHS= 120210109071010
C000= 1
cell_remain= 34.0
n1= 95
temprory4=             h_geocode        dist  cell
1387  120210109072021  143.384253  16.0
RHS= 120210109072021
C000= 3
cell_remain= 13.0
n1= 96
temprory4=            h_geocode        dist  cell
628  120210109071010  142.238577  34.0
RHS= 120210109071010
C000= 11
cell_remain= 23.0
n1= 97
temprory4=             h_geocode        dist  cell
1583  120210109062009  156.213961   3.0
RHS= 120210109062009
C000= 2
cell_remain= 1.0
n1= 98
temprory4=           h_geocode      dist  cell
21  120150201042009  4.942882  15.0
RHS= 120150201042009
C000= 14
cell_remain= 1.0
n1= 99
temprory4=             h_geocode        dist  cell
1586  120210109071010  152.032998  23.0
RHS= 120210109071010
C000= 2
cell_remain= 21.0
n1= 100
temprory4=             h_geocode        dist  cell
1603  120210109072021  143.364089  13.0
RHS= 120210109072021
C000= 2
cell_remain= 11.0
n1= 101
temprory4=             h_geocode      dist  cell
4593  120710206003016  0.653925   2.0
RHS= 120710206003016
C000= 1
cell_remain= 1.0
n1= 102
temprory4=             h_geocode        dist  cell
1603  120210109072021  148.217526  11.0
RHS= 120210109072021
C000= 2
cell_remain= 9.0
n1= 103
temprory4=             h_geocode       dist  cell
1963  120210109062011  156.36304   9.0
RHS= 120210109062011
C000= 1
cell_remain= 8.0
n1= 104
temprory4=             h_geocode        dist  cell
1993  120210109072037  140.811219   2.0
RHS= 120210109072037
C000= 1
cell_remain= 1.0
n1= 105
temprory4=            h_geocode        dist  cell
776  120210109061002  157.194205  10.0
RHS= 120210109061002
C000= 8
cell_remain= 2.0
n1= 106
temprory4=             h_geocode        dist  cell
1986  120210109072021  139.336971   9.0
RHS= 120210109072021
C000= 1
cell_remain= 8.0
n1= 107
temprory4=             h_geocode        dist  cell
1967  120210109071010  152.217427  21.0
RHS= 120210109071010
C000= 1
cell_remain= 20.0
n1= 108
temprory4=             h_geocode      dist  cell
9553  121150027452026  0.144421   3.0
RHS= 121150027452026
C000= 2
cell_remain= 1.0
n1= 109
temprory4=             h_geocode        dist  cell
1585  120210109071010  140.414194  20.0
RHS= 120210109071010
C000= 2
cell_remain= 18.0
n1= 110
temprory4=            h_geocode        dist  cell
852  120210109071010  152.550037  18.0
RHS= 120210109071010
C000= 7
cell_remain= 11.0
n1= 111
temprory4=             h_geocode        dist  cell
1585  120210109071010  151.914309  11.0
RHS= 120210109071010
C000= 2
cell_remain= 9.0
n1= 112
temprory4=             h_geocode        dist  cell
1365  120210109062011  156.300688   8.0
RHS= 120210109062011
C000= 3
cell_remain= 5.0
n1= 113
temprory4=             h_geocode        dist  cell
1050  120210109072021  156.759095   8.0
RHS= 120210109072021
C000= 5
cell_remain= 3.0
n1= 114
temprory4=             h_geocode        dist  cell
1585  120210109071010  142.897295   9.0
RHS= 120210109071010
C000= 2
cell_remain= 7.0
n1= 115
temprory4=             h_geocode        dist  cell
1986  120210109072021  141.760743   3.0
RHS= 120210109072021
C000= 1
cell_remain= 2.0
n1= 116
temprory4=            h_geocode        dist  cell
852  120210109072001  139.214544  10.0
RHS= 120210109072001
C000= 7
cell_remain= 3.0

n1= 117
temprory4=             h_geocode        dist  cell
1364  120210109061000  149.134798   4.0
RHS= 120210109061000
C000= 3
cell_remain= 1.0
n1= 118
temprory4=             h_geocode        dist  cell
1961  120210109061003  150.854647   2.0
RHS= 120210109061003
C000= 1
cell_remain= 1.0
n1= 119
temprory4=             h_geocode        dist  cell
1383  120210109072023  151.058079   5.0
RHS= 120210109072023
C000= 3
cell_remain= 2.0
n1= 120
temprory4=             h_geocode        dist  cell
1364  120210109062011  150.640978   5.0
RHS= 120210109062011
C000= 3
cell_remain= 2.0
n1= 121
temprory4=             h_geocode        dist  cell
1984  120210109072021  143.635798   2.0
RHS= 120210109072021
C000= 1
cell_remain= 1.0
n1= 122
temprory4=             h_geocode        dist  cell
1583  120210109071010  144.033692   7.0
RHS= 120210109071010
C000= 2
cell_remain= 5.0
n1= 123
temprory4=             h_geocode       dist  cell
1965  120210109071010  143.01038   5.0
RHS= 120210109071010
C000= 1
cell_remain= 4.0
n1= 124
temprory4=             h_geocode        dist  cell
1583  120210109071010  144.111921   4.0
RHS= 120210109071010
C000= 2
cell_remain= 2.0
n1= 125
temprory4=             h_geocode        dist  cell
1381  120210109072024  142.333258   9.0
RHS= 120210109072024
C000= 3
cell_remain= 6.0
n1= 126
temprory4=            h_geocode        dist  cell
741  120210109072016  144.170086  44.0
RHS= 120210109072016
C000= 9
cell_remain= 35.0
n1= 127
temprory4=            h_geocode        dist  cell
928  120210109071003  151.103477  60.0
RHS= 120210109071003
C000= 6
cell_remain= 54.0
n1= 128
temprory4=             h_geocode        dist  cell
1965  120210109071010  151.424246   2.0
RHS= 120210109071010
C000= 1
cell_remain= 1.0

In [378]:
select_2030__merge_try2

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,C000_dmg,C000_dmg_mean,cell_x,dist,cell_y,dist_x,loop_num,centr,centr_x_co,h_geocode_x
0,12,081,000304,1005,120810003041005,Block 1005,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.554835,NaN,POINT (27.44387 -82.57167),"(27.443871885889017, -82.57166692688503)",120810003041002
1,12,071,000303,3006,120710003033006,Block 3006,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.240467,NaN,POINT (26.67997 -81.81831),"(26.679967839065085, -81.81831089441661)",120710003033007
2,12,071,040301,2007,120710403012007,Block 2007,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.470605,NaN,POINT (26.60909 -81.70739),"(26.609092407625464, -81.7073913333572)",120710403012009
3,12,071,050603,2017,120710506032017,Block 2017,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.299073,NaN,POINT (26.33356 -81.79809),"(26.333560243311474, -81.79808611592769)",120710506032005
4,12,115,002743,2017,121150027432017,Block 2017,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.425919,NaN,POINT (27.05396 -82.18513),"(27.053958169803494, -82.18512562690302)",121150027431040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,6.945383,77.0,144.111921,2.0,POINT (24.66992 -81.34314),"(24.669922951349808, -81.34313648233238)",120210109071010
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,1.0,7.45181,77.0,142.333258,2.0,POINT (24.68455 -81.35705),"(24.68455255400899, -81.35704563857345)",120210109072024
126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,5.458475,77.0,144.170086,2.0,POINT (24.66673 -81.36251),"(24.666730218175683, -81.36250886730556)",120210109072016
127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,0.830763,8.0,151.103477,2.0,POINT (24.56461 -81.76028),"(24.564608887324344, -81.7602770673833)",120210109071003
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,0.142819,77.0,151.424246,2.0,POINT (24.55790 -81.79375),"(24.55790451809923, -81.79375418066722)",120210109071010

In [379]:

select_2030__merge_try2 = select_2030__merge_try2.astype({"C000":'int64'})

# select_2030__merge_try2 = select_2030__merge_try2.drop(['level_0'], axis = 1)

# select_2030__merge_try2 = select_2030__merge_try2.reset_index()

select_2030__merge_try2

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,C000_dmg,C000_dmg_mean,cell_x,dist,cell_y,dist_x,loop_num,centr,centr_x_co,h_geocode_x
0,12,081,000304,1005,120810003041005,Block 1005,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.554835,NaN,POINT (27.44387 -82.57167),"(27.443871885889017, -82.57166692688503)",120810003041002
1,12,071,000303,3006,120710003033006,Block 3006,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.240467,NaN,POINT (26.67997 -81.81831),"(26.679967839065085, -81.81831089441661)",120710003033007
2,12,071,040301,2007,120710403012007,Block 2007,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.470605,NaN,POINT (26.60909 -81.70739),"(26.609092407625464, -81.7073913333572)",120710403012009
3,12,071,050603,2017,120710506032017,Block 2017,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.299073,NaN,POINT (26.33356 -81.79809),"(26.333560243311474, -81.79808611592769)",120710506032005
4,12,115,002743,2017,121150027432017,Block 2017,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.425919,NaN,POINT (27.05396 -82.18513),"(27.053958169803494, -82.18512562690302)",121150027431040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,6.945383,77.0,144.111921,2.0,POINT (24.66992 -81.34314),"(24.669922951349808, -81.34313648233238)",120210109071010
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,1.0,7.45181,77.0,142.333258,2.0,POINT (24.68455 -81.35705),"(24.68455255400899, -81.35704563857345)",120210109072024
126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,5.458475,77.0,144.170086,2.0,POINT (24.66673 -81.36251),"(24.666730218175683, -81.36250886730556)",120210109072016
127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,0.830763,8.0,151.103477,2.0,POINT (24.56461 -81.76028),"(24.564608887324344, -81.7602770673833)",120210109071003
128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,0.142819,77.0,151.424246,2.0,POINT (24.55790 -81.79375),"(24.55790451809923, -81.79375418066722)",120210109071010

In [380]:
select_2030__merge_try2['geometry'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [381]:
# Emp_home_select_2030_new_values_merge_u_try5_5_6= Emp_home_select_2030_new_values_merge_u_try5_5_6.drop(['level_0'],axis=1)

In [382]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_geo = gpd.GeoDataFrame(
    Emp_home_select_2030_new_values_merge_u_try5_5_6, geometry=Emp_home_select_2030_new_values_merge_u_try5_5_6['geometry'], crs="EPSG:4326"
)
# Emp_home_select_2030_new_values_merge_u_try5_5_6['geometry'] = Emp_home_select_2030_new_values_merge_u_try5_5_6['geometry'].to_crs('epsg:4326')

In [383]:
len(Emp_home_select_2030_new_values_merge_u_try5_5_6)

568

In [384]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_geo['geometry']=Emp_home_select_2030_new_values_merge_u_try5_5_6_geo['geometry'].to_crs('epsg:4326')

In [385]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_geo['geometry'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [386]:
select_2030__merge_try2 = gpd.GeoDataFrame(
    select_2030__merge_try2, geometry=select_2030__merge_try2['geometry'], crs="EPSG:4326"
)

In [387]:
# select_2030__merge_try2.drop(['geometry_y1'],axis=1)

In [388]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_geo=Emp_home_select_2030_new_values_merge_u_try5_5_6_geo.drop(['geometry_x1','geometry_y1'],axis=1)

In [389]:
import pandas as pd 
Emp_home_select_2030_new_values_merge_u_try5_5_6_=pd.concat([Emp_home_select_2030_new_values_merge_u_try5_5_6_geo, select_2030__merge_try2], axis=0)
len(Emp_home_select_2030_new_values_merge_u_try5_5_6_)

697

In [390]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_

,dist_x,index,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,...,min_2030_y,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co
0,6.968161,0,3.527525,1.201501e+14,120150201031014,12,015,010200,1089,120150102001089,...,0.0,"POLYGON ((-82.00558 27.02413, -82.00549 27.024...",1.524416e+10,24.5,31.0,0.0,NaN,NaN,None,NaN
1,8.38327,3,0.59246,1.201501e+14,120150201014003,12,015,010402,1004,120150104021004,...,0.0,"POLYGON ((-82.03709 27.00262, -82.03526 27.002...",8.762873e+10,240.0,178.0,0.0,NaN,NaN,None,NaN
2,4.357815,10,4.035699,1.201501e+14,120150104011000,12,015,010503,2026,120150105032026,...,0.0,"POLYGON ((-82.07890 26.91056, -82.07890 26.911...",1.121479e+11,184.5,228.0,0.0,NaN,NaN,None,NaN
3,4.717145,151,4.804653,1.201501e+14,120150105052010,12,015,010503,2095,120150105032095,...,0.0,"POLYGON ((-82.02166 26.87867, -82.02165 26.878...",5.901239e+09,6.0,12.0,0.0,NaN,NaN,None,NaN
4,0.791743,358,4.254489,1.207101e+14,120710101041003,12,015,010506,1014,120150105061014,...,0.0,"POLYGON ((-82.05619 26.75849, -82.05618 26.758...",9.853028e+10,956.0,198.0,0.0,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,144.111921,NaN,6.945383,NaN,120210109071010,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.34386 24.67004, -81.34387 24.670...",NaN,NaN,77.0,NaN,NaN,2.0,POINT (24.66992 -81.34314),"(24.669922951349808, -81.34313648233238)"
125,142.333258,NaN,7.45181,NaN,120210109072024,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.35804 24.68464, -81.35804 24.684...",NaN,NaN,77.0,NaN,NaN,2.0,POINT (24.68455 -81.35705),"(24.68455255400899, -81.35704563857345)"
126,144.170086,NaN,5.458475,NaN,120210109072016,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.36352 24.66796, -81.36330 24.667...",NaN,NaN,77.0,NaN,NaN,2.0,POINT (24.66673 -81.36251),"(24.666730218175683, -81.36250886730556)"
127,151.103477,NaN,0.830763,NaN,120210109071003,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.76104 24.56456, -81.76091 24.564...",NaN,NaN,8.0,NaN,NaN,2.0,POINT (24.56461 -81.76028),"(24.564608887324344, -81.7602770673833)"
128,151.424246,NaN,0.142819,NaN,120210109071010,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.79439 24.55820, -81.79428 24.558...",NaN,NaN,77.0,NaN,NaN,2.0,POINT (24.55790 -81.79375),"(24.55790451809923, -81.79375418066722)"

In [391]:

# Emp_home_select_2030_new_values_merge_u_try5_5_6_ = Emp_home_select_2030_new_values_merge_u_try5_5_6_.drop(['level_0'], axis = 1)
Emp_home_select_2030_new_values_merge_u_try5_5_6_ = Emp_home_select_2030_new_values_merge_u_try5_5_6_.reset_index()

Emp_home_select_2030_new_values_merge_u_try5_5_6_['C000']

0      4
1      2
2      1
3      1
4      1
      ..
692    2
693    3
694    9
695    6
696    1
Name: C000, Length: 697, dtype: int64

In [392]:

Emp_home_select_2030_new_values_merge_u_try5_5_6_ = Emp_home_select_2030_new_values_merge_u_try5_5_6_.drop(['level_0'], axis = 1)

In [393]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_['C000'].sum()

1756

In [394]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_

,dist_x,index,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,...,min_2030_y,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co
0,6.968161,0,3.527525,1.201501e+14,120150201031014,12,015,010200,1089,120150102001089,...,0.0,"POLYGON ((-82.00558 27.02413, -82.00549 27.024...",1.524416e+10,24.5,31.0,0.0,NaN,NaN,None,NaN
1,8.38327,3,0.59246,1.201501e+14,120150201014003,12,015,010402,1004,120150104021004,...,0.0,"POLYGON ((-82.03709 27.00262, -82.03526 27.002...",8.762873e+10,240.0,178.0,0.0,NaN,NaN,None,NaN
2,4.357815,10,4.035699,1.201501e+14,120150104011000,12,015,010503,2026,120150105032026,...,0.0,"POLYGON ((-82.07890 26.91056, -82.07890 26.911...",1.121479e+11,184.5,228.0,0.0,NaN,NaN,None,NaN
3,4.717145,151,4.804653,1.201501e+14,120150105052010,12,015,010503,2095,120150105032095,...,0.0,"POLYGON ((-82.02166 26.87867, -82.02165 26.878...",5.901239e+09,6.0,12.0,0.0,NaN,NaN,None,NaN
4,0.791743,358,4.254489,1.207101e+14,120710101041003,12,015,010506,1014,120150105061014,...,0.0,"POLYGON ((-82.05619 26.75849, -82.05618 26.758...",9.853028e+10,956.0,198.0,0.0,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,144.111921,NaN,6.945383,NaN,120210109071010,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.34386 24.67004, -81.34387 24.670...",NaN,NaN,77.0,NaN,NaN,2.0,POINT (24.66992 -81.34314),"(24.669922951349808, -81.34313648233238)"
693,142.333258,NaN,7.45181,NaN,120210109072024,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.35804 24.68464, -81.35804 24.684...",NaN,NaN,77.0,NaN,NaN,2.0,POINT (24.68455 -81.35705),"(24.68455255400899, -81.35704563857345)"
694,144.170086,NaN,5.458475,NaN,120210109072016,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.36352 24.66796, -81.36330 24.667...",NaN,NaN,77.0,NaN,NaN,2.0,POINT (24.66673 -81.36251),"(24.666730218175683, -81.36250886730556)"
695,151.103477,NaN,0.830763,NaN,120210109071003,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.76104 24.56456, -81.76091 24.564...",NaN,NaN,8.0,NaN,NaN,2.0,POINT (24.56461 -81.76028),"(24.564608887324344, -81.7602770673833)"
696,151.424246,NaN,0.142819,NaN,120210109071010,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.79439 24.55820, -81.79428 24.558...",NaN,NaN,77.0,NaN,NaN,2.0,POINT (24.55790 -81.79375),"(24.55790451809923, -81.79375418066722)"

In [395]:
# dataframes4_temp={}


# # list of data frames
# # Assume that the original dataframe is named 'original_df'
# for i in range(0, 720):
#     dataframes4_temp[i] = Emp_home_select_2030_new_values_merge_u_try5_5_6_.copy()

# # Convert the dictionary to a list of tuples
# dataframes4 = list(dataframes4_temp.values())

# for k in range(0, 720):
#     dataframes4[k] = dataframes4[k].rename("{}_{}".format("{}_a",k).format)

# # dictionary to save data frames
# Emp_home_select_2030_new_values_merge_u_try5_5_6_dic={} 

# for key4, value4 in enumerate(dataframes4):    
#     Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[key4] = value4 # assigning data frame from list to key in dictionary

In [396]:
# Emp_cells2_2030_2_dic[0]

In [397]:
Emp_cells2_2030_2_dic, cells2_2030_3, Emp_home_select_2030_new_values_merge_u_try5_5_6_dic = find_cells_SLR(Emp_home_select_2030_new_values_merge_u_try5_5_6_, Emp_cells2_2030_2_dic)

Yes
i= 0
1.3370308876037598
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

7.378459930419922
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.017712116241455078

In [398]:
# Emp_cells2_2030_2_dic[89][Emp_cells2_2030_2_dic[89]['min_2030']>0]

In [399]:
# to_findit = Emp_cells2_2030_2_dic[719][Emp_cells2_2030_2_dic[719]['row_num']==32642]
# to_findit.to_file('to_findit.shp')

In [400]:
# Emp_cells2_2030_2_dic[719][Emp_cells2_2030_2_dic[719]['row_num']==32642]

In [401]:
# Emp_cells_2030_old[Emp_cells_2030_old['row_num']==32642]

In [402]:
cells2_2030_3

[[498226819, 498226820, 498226821],
 [491719207, 491719406, 491722174, 491722243],
 [491769489, 492525353],
 [491887778],
 [491769973],
 [497406099],
 [492144957, 492144974, 492144976],
 [492144978],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [491873416, 491873420],
 [492298633, 492298639],
 [492298636],
 [492298630],
 [492298628],
 [492143591, 492143601, 492143606, 492143607, 492143613, 492143614],
 [491866247, 491866274],
 [491893110],
 [491830047],
 [495047039, 495156932],
 [492328158],
 [495877835],
 [491776849,
  491777003,
  491777007,
  491780895,
  491791959,
  491791998,
  491792005,
  491792012],
 [492968628, 492968632, 494508645],
 [494891816, 494891820, 494892055, 494892057, 494892075],
 [492246487],
 [492246484],
 [491922755],
 [492468345],
 [491921812],
 [491905547, 491905554],
 [491905544],
 [491905558],
 [],
 [491904337, 491904338, 491904346],
 [491904349],
 [491974615, 491975701],
 [491772838, 491772848, 491772849, 492556699, 492556704],
 [492234701],
 [492234687, 492234696],
 [492234686],
 [492234691],
 [492138508],
 [492138509],
 [491951756],
 [491951758],
 [492914055, 492914064],
 [492251171],
 [492251172],
 [492251179],
 [492251178],
 [],
 [491887610, 491887616],
 [491887617],
 [491915912],
 [491874747],
 [491874738, 491874740],
 [491874742],
 [492916531],
 [492228653],
 [492955132, 492955137, 492955138],
 [492314681],
 [492314682, 492314683, 492314693],
 [492314680],
 [492314685],
 [492269087, 492269089, 492269092],
 [491905263],
 [491905257, 491905262],
 [495292299, 495292302, 495292304, 495292306],
 [497404380],
 [491832162, 491848333, 492488000],
 [492335885],
 [492335873],
 [492335872],
 [491873426],
 [492155317, 492155324],
 [492360570],
 [491769340, 491769348, 492529247, 492529257],
 [491776895, 491776914, 491776919, 491780863, 491780871],
 [491866346, 491866349],
 [491762366],
 [492328378, 492328391],
 [],
 [491874650, 491874663],
 [491786197, 491786206],
 [491786139, 491786193, 491786231, 491786264, 491788776],
 [492137859, 492137874, 492137878],
 [491875006, 491875016, 491875047, 491876706, 491876752, 491876767],
 [491746058, 491746070, 491746421],
 [492009709],
 [492043903, 492043919, 492043937, 492044787],
 [492294107],
 [495287131],
 [492113254, 492113325, 492113357, 492447264],
 [492066675, 492066693],
 [491996467],
 [493167115, 493170910, 493170939, 493170957],
 [493157560, 493157566],
 [492114569],
 [492066496],
 [493156173, 493156474],
 [492026309, 492027452],
 [492198608],
 [492198604],
 [492036315, 492038355],
 [492073702],
 [493228277, 493228283],
 [495155027],
 [495155011],
 [],
 [494317969, 494367939],
 [494502274, 494502445, 494523297],
 [495026300],
 [495737535, 495738096],
 [494678844,
  494678864,
  494678866,
  494678870,
  494678874,
  494678876,
  494678880,
  494678886,
  494678898],
 [495133626, 495133639],
 [495077821,
  495077831,
  495077833,
  495077836,
  495077838,
  495078306,
  495078790,
  495078791],
 [492331332, 492331386, 492331394, 492331396],
 [492285363],
 [492169950, 492169965],
 [492169920, 492170479, 492170504],
 [492124521],
 [493827711,
  493827729,
  493827742,
  493827749,
  493827757,
  493827764,
  493829047,
  493829211,
  493829237,
  493830063],
 [493677380],
 [496096776,
  496096791,
  496097193,
  496097199,
  496097200,
  496097202,
  496097222,
  496097225,
  496097227,
  496097239,
  496097761,
  496097765,
  496117642,
  496117667,
  496118152,
  496118155,
  496118162,
  496118173,
  496118180],
 [493249640,
  495621120,
  495622507,
  495622557,
  495624779,
  495625427,
  495627107,
  495628053,
  495628068,
  495628543,
  495628566,
  495638846],
 [492560062],
 [494127892],
 [494156568],
 [493786871, 493788033],
 [495351410],
 [495353948, 495357659],
 [492263504, 492263514, 492268169],
 [495394758],
 [495100477],
 [492444513, 492444529, 495568358],
 [492237641, 492238554],
 [492126351],
 [492110953],
 [492110977],
 [492126387],
 [496154046],
 [492110989],
 [492253445, 492253470, 492253501, 492253510, 492253591],
 [492124432],
 [492124416, 492126298],
 [492126381],
 [498033689, 498033913],
 [494837428, 494837431],
 [494841178],
 [492111087, 492111089],
 [496649702],
 [496970082],
 [496970083],
 [496675773],
 [497041722, 497041724],
 [496705967, 496705985],
 [496679128, 496679152],
 [496679116, 496679155],
 [496739064],
 [498162851, 498164265],
 [497540945],
 [497540940, 497540943],
 [496973279, 496973284, 496973285, 496973801],
 [498164252],
 [497073047, 497073123, 497073129, 497073140, 498161993, 498162295],
 [498141465],
 [496870746],
 [491764892],
 [497559061],
 [497559053, 497559065],
 [497559041, 497559067],
 [497559081, 497559115],
 [497559097],
 [498167617],
 [496964451, 496976433],
 [496973842],
 [497044038, 497044045, 497044074],
 [496961372, 496961459, 496963413, 498171824],
 [498206306],
 [496832879, 496833144],
 [498153669, 498153679, 498154048],
 [497035937],
 [497071758, 497073125],
 [497085095],
 [497099510],
 [497701022],
 [497031602, 497031605],
 [497069814,
  497069817,
  497069818,
  497069823,
  497069825,
  497069828,
  497069839,
  497069841,
  497069843,
  497069849],
 [497024132],
 [497801173],
 [497201883],
 [497352133, 497352214],
 [497119287],
 [497284430, 497284436, 497284446, 497284474, 497284489, 497284517, 497284544],
 [497397776, 497397829, 497399093],
 [497837234],
 [497408878, 497408915, 497408962, 497409373, 497638185, 497781549],
 [497767299, 497767331],
 [497397439, 497397452],
 [497811556, 497811560],
 [497730189],
 [497730195],
 [],
 [497954132],
 [497833867],
 [497833874],
 [497235057],
 [497235055],
 [497570501, 497570515, 497570517, 497570519],
 [497570493],
 [497570495],
 [497861897, 497861898, 497861900, 497861904],
 [497978385, 497978386],
 [497282245],
 [497281360, 497281362],
 [497630730],
 [497401790],
 [497380271, 497380372, 497955567],
 [497248473],
 [497383108],
 [497374804, 497374808, 497374809, 497374815, 497374819, 497374823],
 [497374817, 497374822],
 [497618903, 497618909, 497618914],
 [497205415],
 [497058157],
 [497804576, 497804577],
 [497208438, 497208446],
 [497149856,
  497149858,
  497149896,
  497149983,
  497150003,
  497150015,
  497150022,
  497150058,
  497150074,
  497186575,
  497186581,
  497186652,
  497186654,
  497186666,
  497834103],
 [497149941, 497150038],
 [497142535],
 [496961330],
 [497190609, 497562411],
 [497190615, 497190625, 497190632, 497562443, 497802398],
 [497237558],
 [497198529, 497198554, 497198562, 497198572, 497198574, 497239287, 497239308],
 [497257791],
 [497257785, 497257790],
 [497210772],
 [497761669, 497761673],
 [497761661],
 [497575629, 497575643],
 [497570497],
 [497269333],
 [497777969],
 [497229185,
  497229635,
  497229637,
  497229641,
  497229651,
  497229665,
  497229669,
  497229686,
  497229688,
  497229696,
  497229700,
  497229706,
  497229708],
 [497232003],
 [497269606],
 [497337754, 497337763],
 [497337748, 497337751, 497337752, 497337764],
 [497337746, 497337760],
 [497337747, 497337759],
 [497804504,
  497804506,
  497804507,
  497804508,
  497804509,
  497804513,
  497804519,
  497804523],
 [497804651, 497804652, 497804654, 497804656, 497804659, 497804664, 497804667],
 [497804666],
 [497804644, 497804669],
 [496543060,
  496543064,
  497198522,
  497198555,
  497208323,
  497208379,
  497208383,
  497208412,
  497239298,
  497239311],
 [497269605],
 [497224187, 497224192],
 [497076502],
 [497187775],
 [497150106, 497186635],
 [497976378, 497976380, 497976384],
 [497974290],
 [497562720, 497562722],
 [497334329],
 [497349993, 497350017, 497350036, 497350074],
 [497616399],
 [497771810, 497852499],
 [497281061],
 [497269450],
 [497571241, 497571245, 497571255],
 [497340045, 497340176],
 [497357269, 497357284],
 [497194925],
 [497409026, 497409034, 497409037, 497409046, 497409060],
 [497086672, 497086674, 497086675, 497086676, 497086679, 497086681],
 [497583982],
 [497804514, 497804517],
 [497195148, 497195150],
 [497350348],
 [496875158, 496875160],
 [497844624],
 [496966091],
 [496649319],
 [497976234],
 [497136607, 497164013],
 [496965984],
 [497571035,
  497571037,
  497571051,
  497571055,
  497571057,
  497571071,
  497571077,
  497571091],
 [497253319],
 [497149909,
  497149919,
  497149937,
  497149947,
  497150110,
  497150391,
  497186643,
  497186659,
  497186682,
  497739465],
 [497738990],
 [496676866],
 [497654846],
 [496592330,
  496592331,
  496596445,
  496596447,
  496596448,
  497650311,
  497650557,
  497796155,
  497796250,
  497796251,
  497841032,
  497841034,
  497857793,
  497857797,
  497882770,
  497885650,
  497885652,
  497893671],
 [496832914, 496832967],
 [497509305, 497509311, 497509313, 497509315],
 [496841355, 496841360],
 [496964335],
 [496580250, 496580253, 496580255, 496580261, 496580263, 496580264, 496580265],
 [496580257, 496580268],
 [],
 [496638287],
 [498198620, 498199121],
 [498194587],
 [497601065, 497926085],
 [496765629, 496765736, 496765796, 496765902, 496768372],
 [497201775, 497201787],
 [496705550, 496705635],
 [496652269,
  496652432,
  496652518,
  496652663,
  496652742,
  496653151,
  496653299,
  496653486,
  496655926],
 [496705470, 496727388],
 [496629364, 496629403, 496629598, 496629659, 496640492, 496640506],
 [497495117],
 [497816452],
 [497649245],
 [497657071],
 [496833609],
 [496570761],
 [498223846, 498223913],
 [497864544],
 [497864533],
 [],
 [],
 [497471100],
 [497471090],
 [496644213],
 [497858294],
 [497858306],
 [497820898, 497820915],
 [497655122],
 [497655127],
 [496636269],
 [497074604],
 [496587577, 496587578],
 [496593313],
 [498223942],
 [497649411],
 [496590779],
 [496575909, 496575935],
 [496921385, 496921395],
 [496651241],
 [497818435],
 [497657141],
 [497818828, 497818835, 497818851],
 [497558413],
 [498131331],
 [497859963, 498131276],
 [497525061, 497525089, 497525095],
 [497517693],
 [496922769, 496922791],
 [492190430, 492196274, 494845169, 494845890, 495087055],
 [496922758],
 [496867222, 496867251],
 [496726022],
 [496742924, 496742925],
 [497453110],
 [497761695],
 [497403032, 497403078, 497403132],
 [497954475],
 [497459408],
 [492141957, 492141961, 492141967],
 [495454823],
 [495298456, 495299057],
 [495298454, 495299056],
 [495298451, 495298455],
 [495315760],
 [495315764, 495315765, 495315771],
 [495529958],
 [495444289],
 [495444282],
 [495579860, 495579863, 495579866, 495579867],
 [495579862],
 [495579861, 495579865],
 [493745586],
 [495583286, 495583290, 495583294],
 [495861741],
 [494655669],
 [495021670,
  495021672,
  495021673,
  495021674,
  495021675,
  495021676,
  495021677,
  495021678,
  495021682,
  495021684,
  495021686,
  495021687,
  495021688],
 [494897856],
 [494906394],
 [495936698],
 [496127083],
 [495491974],
 [494742747],
 [494742742],
 [494742736, 494743833],
 [494700574],
 [494769159, 494769160],
 [495521699],
 [494842019, 495919943],
 [494818247, 494818265],
 [495309050, 495309052],
 [494807250, 494807266],
 [494808239, 494808245, 494808249, 494808255],
 [494848931, 494848932],
 [494848925, 494848927, 494848929],
 [495308564, 495308566],
 [495308943],
 [495602672],
 [494761132, 494772294],
 [494549481, 494549495],
 [495620684],
 [495500365,
  495500366,
  495500368,
  495500370,
  495500374,
  495500375,
  495500379,
  495500393,
  495500394,
  495500398],
 [495818054],
 [492116901, 492116903, 495001686, 495005032, 495606301],
 [496023528, 496023551, 496023554, 496026707, 496026747, 496026748],
 [495320444],
 [495456883, 495456889],
 [493570221, 493570241, 493570329, 493607581, 493607604, 495279443],
 [493658858,
  493658875,
  493658881,
  493658911,
  493658926,
  493658932,
  493658975,
  493659003,
  493664325,
  493664341,
  493664348],
 [495482236, 495482241, 495482245],
 [494419923, 494474507],
 [495235311, 495235332],
 [494954321],
 [495621135],
 [494749634, 494749705],
 [494749643, 494749707],
 [495222367, 495222375, 495222447, 495222449, 495222450],
 [492892865],
 [494144851, 494144852],
 [495187050, 495187052, 495187223, 495187225],
 [492088776,
  492088785,
  492088788,
  492088861,
  492088871,
  492090651,
  492091363,
  492091380],
 [495742218],
 [492120626],
 [492335771],
 [495651364, 495651446, 495651858, 495652354],
 [495651143, 495651855, 495652348, 495652349],
 [492419999],
 [492089679, 493011946, 493011983],
 [495529099],
 [492321719],
 [493238237],
 [492323140],
 [494290934, 494345071],
 [496112009],
 [496097203],
 [493751210, 493751229],
 [493575059,
  493575060,
  493575089,
  493575129,
  493575220,
  493575255,
  493575259,
  493576441],
 [493714888],
 [494163182, 494163193],
 [493721132, 493721136, 493721147, 493721149],
 [495228560],
 [493780238],
 [494990968],
 [495357876, 495357877, 495357879, 495358546, 495358594, 495358596, 495358604],
 [494862624],
 [493721271],
 [493751226, 493751241],
 [493821111],
 [493780844],
 [493781211, 493781230],
 [495958853, 495958855, 495958857, 495958860],
 [493726909, 493726912, 493726915, 493726919, 493726920],
 [494178812],
 [494178806],
 [493846905],
 [495274616],
 [494991261],
 [493581378, 493590836],
 [495722715],
 [493867236, 493867241, 493867244],
 [494178799,
  494178800,
  494178803,
  494178809,
  494178810,
  494178811,
  494178815,
  494178819,
  494179402,
  494179566],
 [495194459],
 [494324172],
 [493445920, 493500309],
 [494978533, 494978544],
 [492849543],
 [495026846, 495026849],
 [495240968, 495240974, 495240976, 495240985],
 [495822540],
 [495990152],
 [494872573, 494872578, 494872596],
 [495699370, 495699395],
 [493753162, 493753179, 493753183],
 [495012995, 495012996],
 [493418073, 493418083],
 [493502703],
 [493420923, 493420946, 493420948],
 [493610944],
 [493349884],
 [493551369, 493551373, 493551374],
 [493393075, 493393101],
 [493647110],
 [495171005, 495171007, 495171024],
 [494306701,
  494306708,
  494306710,
  494306712,
  494306714,
  494306723,
  494306728,
  494306732,
  494306737,
  494306746,
  495621068],
 [493316578],
 [493316111],
 [492842841, 492842851],
 [495560026],
 [493354993, 493355013, 493355015, 493355047],
 [495531011, 495532983, 495533008, 495533039],
 [493216116,
  493216153,
  495561070,
  495561561,
  495561569,
  495561576,
  495561579,
  495561605,
  495561617,
  495561649,
  495562176,
  495562184,
  495562841,
  495562896,
  495564332,
  495564472],
 [495390933],
 [493240503,
  493240510,
  493240514,
  493240539,
  493240547,
  493296873,
  493296880,
  493296883,
  493296885],
 [495127747],
 [495127751],
 [493232524],
 [495551848, 495552693],
 [493251974, 493251985],
 [495122127],
 [495112802, 495112810, 495112814],
 [493235280],
 [495307402, 495307406, 495307410, 495307933, 495307934, 495307938],
 [495347997],
 [493192561],
 [493167165, 493170988, 493170991],
 [493150297],
 [493157975, 495482054],
 [493155633],
 [494477139,
  494477141,
  494477143,
  494477145,
  494477147,
  494477151,
  494477153,
  494477155,
  494477160],
 [495601792],
 [493013444, 493013445, 493013449, 493013451, 493013457, 493013460, 495084101],
 [493013453],
 [492350042, 492350045],
 [493303284, 493303292],
 [492031239, 492031249, 492031257],
 [493132551, 493132568, 493132582, 493132591],
 [493097567, 493103057, 493135945, 493136164],
 [492983698, 492983699],
 [492983703],
 [494172665],
 [492985989, 492985995],
 [493024664, 493024665, 493024672],
 [493024959],
 [495068158, 495068161, 495068164, 495068166, 495068169, 495068171],
 [492986048, 492986052, 492986053],
 [492986049],
 [493042191],
 [492986144],
 [492955245, 492955256],
 [492955255],
 [492955253],
 [492955242, 492955249, 492955260],
 [492955240, 492955258],
 [],
 [],
 [],
 [],
 [493024674],
 [],
 [493224602, 493224603, 493224615],
 [492242544, 492242549, 492242552, 492242553, 492242554],
 [492242541],
 [],
 [],
 [493643216, 493643225],
 [497512236,
  497512237,
  497512242,
  497512248,
  497512251,
  497512254,
  497512262,
  497512268,
  497512272,
  497512276,
  497512282,
  497512286,
  497512288,
  497512292,
  497512296,
  497512303],
 [492011678, 492012541, 492012567],
 [494502598, 494502599],
 [492985959, 492985962, 492985963],
 [492975970, 492976088],
 [492968466],
 [492921657],
 [494402916],
 [492980487, 492980488],
 [492941354, 492941356, 492941357],
 [494428570],
 [492905787, 492905795],
 [491889801],
 [495406247],
 [495287095],
 [495397822],
 [494343468],
 [497844478],
 [496649180],
 [496846250],
 [492965163,
  492965165,
  492965166,
  492965167,
  492965168,
  492965169,
  492965170,
  492965172,
  492965173],
 [493360685],
 [497671814,
  497671815,
  497671816,
  497671819,
  497671820,
  497671821,
  497671822,
  497671823,
  497671825,
  497671827,
  497671829,
  497671830],
 [496730955,
  496730961,
  496730966,
  496730973,
  496730975,
  496730985,
  496730995,
  496730998],
 [494749957,
  494749961,
  494749963,
  494749969,
  494749971,
  494749975,
  494749977,
  494749981,
  494749983,
  494749985,
  494749989,
  494749994,
  494749998,
  494750002,
  494750004],
 [492368238],
 [497144330],
 [497723752, 497723756, 497723758, 497723771],
 [496002563, 496002567, 496003311],
 [494498270, 494498273, 494498276, 494498279, 494498281],
 [496738922,
  496738935,
  496738938,
  496738939,
  496738945,
  496738947,
  496738948,
  496738959,
  496738961,
  496738972,
  496738981,
  496738983,
  496738987,
  496738992,
  497882844,
  498131092,
  498131109,
  498135247,
  498135250,
  498135259,
  498135264,
  498135294],
 [491805954,
  491805955,
  491805956,
  491805964,
  491805968,
  491808202,
  491808208,
  491808215,
  491808217,
  491808218,
  491808223,
  491808224,
  491808226],
 [493497775, 493497777, 493497798],
 [493864309],
 [494902278],
 [491908384],
 [493013463,
  493013465,
  493013467,
  493013472,
  493013475,
  493013480,
  493013482,
  493013489,
  493013492,
  493013495,
  493013496,
  493013497,
  493013498,
  493013502,
  493013503,
  493013508],
 [497884856, 498167184, 498167201],
 [496629782],
 [495222087],
 [497269581],
 [494673009, 494673015],
 [497859809],
 [492993083, 492993092, 495182541, 495211100, 495217870],
 [492424700, 492424701],
 [492941352, 492941355, 492941358],
 [495289697, 495289701],
 [496875116, 496875134, 496875167],
 [495306878],
 [494507072, 494507093, 494507095],
 [492328365],
 [492111207],
 [492314579],
 [494679914, 494679925],
 [495029573],
 [497296136, 497296139, 497296141],
 [497534741, 497534743],
 [495099987],
 [492496488, 492496503],
 [491898424],
 [497330688, 497330690, 497330696],
 [495731216],
 [494920315],
 [497762230, 497762231, 497762233],
 [492143598],
 [492049874,
  492049875,
  492049877,
  492049879,
  492049881,
  492049883,
  492049884,
  492049888,
  492049889,
  492049891,
  492049895,
  492450165,
  492450166],
 [497462309],
 [497167870, 497167872, 497167875, 497167879, 497167882, 497167884],
 [497870607, 497870609, 497870611],
 [492273769],
 [492946969, 492950913],
 [493358878, 493358886, 493358888, 493358892, 493358894, 493358904],
 [495095695],
 [496616220,
  496616221,
  496616223,
  496616226,
  496616227,
  496616231,
  496616233,
  496616234],
 [492918110, 492918121],
 [494918585, 494918593],
 [493345460, 493345461, 493345463, 493345466, 493345467, 493345469],
 [493301210, 493301214],
 [493358876, 493358890, 493358902],
 [493301205],
 [493301209],
 [496676979, 496676980],
 [492466087],
 [494926579, 494926580, 494926583, 494926587],
 [494926581, 494926589],
 [493345465],
 [492505068,
  492505073,
  492505074,
  492505088,
  492505089,
  492505092,
  492505093,
  492505097],
 [492993085],
 [494926591],
 [492993088],
 [494926592],
 [495193572, 495193578],
 [496596449,
  497650314,
  497650563,
  497796157,
  497841036,
  497857795,
  497868836,
  497885635,
  497892465],
 [494926588],
 [491896867,
  491896877,
  492311385,
  492311387,
  492311388,
  492311389,
  492311390,
  492460693,
  492460696,
  492468102,
  492468107,
  492468127,
  492468132],
 [492247776],
 [496592141,
  496592146,
  496592149,
  496592156,
  496592157,
  496592159,
  496592160,
  496592164,
  496592168,
  496592169,
  496592170,
  496592178,
  496592179],
 [492993093],
 [492590164, 492592253, 492592276, 492592277, 492593726],
 [494928770],
 [494925076, 494925092],

In [403]:
# Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[89]['cells_used']

In [404]:
del zs2_dic2

In [405]:
#Because we used find_cells, then h_geocode_x should be used as new home zone for projcted empoloyees
#So cells_calc_x should be used (it takes h_geocode_x) 

my_list_2=[]
my_list_3=[]
my_list_4=[]

start = time.time()

result = Parallel(n_jobs=-5)(delayed(cells_calc_x)(i, Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[i], Emp_cells2_2030_2_dic[i], cells2_2030_3) for i in range(0,len(Raster_file_paths_new)))

# Convert the result to a dictionary with keys as indices
zs2_dic2 = dict(enumerate(result))

# Step 4: After calculating the results, retrieve the values from the 'zs2_dic' dictionary and store them in the lists 'my_list_2', 'my_list_3', and 'my_list_4'
my_list_2 = [zs2_dic2[i][0] for i in range(len(Raster_file_paths_new))]
my_list_3 = [zs2_dic2[i][1] for i in range(len(Raster_file_paths_new))]
my_list_4 = [zs2_dic2[i][2] for i in range(len(Raster_file_paths_new))]

end = time.time()
print(end - start)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

8.608182907104492

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [406]:
# #Because we used find_cells, then h_geocode_x should be used as new home zone for projcted empoloyees
# #So cells_calc_x should be used (it takes h_geocode_x) 

# my_list_2, my_list_3,my_list_4 = cells_calc_x(Emp_home_select_2030_new_values_merge_u_try5_5_6_dic,Emp_cells2_2030_2_dic, cells2_2030_3)

In [407]:
my_list_2_final={}
my_list_3_final={}
my_list_4_final={}

for l in range(0,len(Raster_file_paths_new)):
    my_list_2_final[l]= my_list_2[l][0]
    my_list_3_final[l]= my_list_3[l][0]
    my_list_4_final[l]= my_list_4[l][0]
    
my_list_2={}
my_list_3={}
my_list_4={}

In [408]:
Emp_cells2_dic_list4_3 =list_4_calc(my_list_4_final,cells2_2030_3,Emp_cells2_dic)

In [409]:
Emp_cells2_dic_list4_3

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage5,damage6,damage7,damage8,damage9,damage10,damage11,damage12,damage13,damage14
0,120150201031014,856790.0,491719207,76VW22C2+QR3-3-2-4-4,120150201031014,RES,RES1-1SNB,W,1.0,1970.0,...,0.0,0.0,0.0,0.0,0.0,100.000000,100.000000,100.000000,100.00000,100.0
1,120150201031014,856999.0,491719406,76VW22C4+XRP-3-3-4-4,120150201031014,RES,RES1-1SNB,M,1.0,2175.0,...,0.0,0.0,0.0,0.0,0.0,100.000000,100.000000,100.000000,100.00000,100.0
2,120150201031014,859756.0,491722174,76VV2XFX+C9C-4-3-3-4,120150201031005,RES,RES1-1SNB,W,1.0,1981.0,...,0.0,0.0,0.0,0.0,0.0,39.806078,55.882191,97.794914,100.00000,100.0
3,120150201031014,859825.0,491722243,76VV2XFW+RF7-4-4-4-3,120150201031005,RES,RES1-1SNB,W,1.0,2344.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,10.117762,37.991392,79.98614,100.0
4,120150201013007,883566.0,491746058,76RVXXVQ+WCW-4-3-5-4,120150201011036,RES,RES1-1SNB,M,1.0,2247.0,...,0.0,0.0,0.0,0.0,0.0,88.038636,100.000000,100.000000,100.00000,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1694,120710012083002,7334402.0,498199121,76RWH5VH+RHH-0-0-0-0,120710012024016,RES,RES1-1SNB,W,1.0,1149.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.0
1695,120710401322001,7341589.0,498206306,76RWJ667+C8C-0-0-0-0,120710401121002,RES,RES1-1SNB,M,1.0,1724.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.0
1696,120710402113048,7359114.0,498223846,76RWJC82+R87-0-0-0-0,120710402037052,RES,RES1-1SNB,W,1.0,923.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.0
1697,120710402113048,7359214.0,498223913,76RWJ98X+7Q5-0-0-0-0,120710402037051,RES,RES1-1SNB,M,1.0,791.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.0
1698,120710402113048,7359251.0,498223942,76RWJC82+GM4-0-0-0-0,120710402037052,RES,RES1-1SNB,M,1.0,1011.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.0

In [410]:
# Emp_cells2_dic_list4_3 = list4_2_full(Emp_cells2_dic_list4_3)

In [411]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic=dmg_calc(my_list_2_final, my_list_3_final, Emp_home_select_2030_new_values_merge_u_try5_5_6_dic)

In [412]:
# Emp_home_select_2030_new_values_merge_u_try5_5_6_dic_full = dataframe_full(Emp_home_select_2030_new_values_merge_u_try5_5_6_dic)

In [413]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000'].sum()

1756

In [414]:
select_hgeocode_geo5_6_try_try2_dic_missing['C000'].sum()

215

In [588]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0] = Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0].astype({"cells_used":'int64'})

merge_u_try2= Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0][Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000'] != Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['cells_used']]


merge_u_try2

,dist_x,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,...,min_2030_y,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co
6_a_0,3.607147,2.247294,1.201502e+14,120150202062003,12,015,020204,1049,120150202041049,Block 1049,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
7_a_0,3.607147,4.417017,1.201502e+14,120150202062003,12,015,020204,2038,120150202042038,Block 2038,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
8_a_0,3.607147,2.621194,1.201502e+14,120150202062003,12,015,020205,3013,120150202053013,Block 3013,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
9_a_0,3.607147,3.004297,1.201502e+14,120150202062003,12,015,020206,2092,120150202062092,Block 2092,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
10_a_0,3.607147,2.700523,1.201502e+14,120150202062003,12,015,020301,4013,120150203014013,Block 4013,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
11_a_0,3.607147,2.671328,1.201502e+14,120150202062003,12,015,020303,4024,120150203034024,Block 4024,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
12_a_0,3.607147,3.076096,1.201502e+14,120150202062003,12,015,020900,1011,120150209001011,Block 1011,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
13_a_0,3.607147,2.799715,1.201502e+14,120150202062003,12,015,020900,1024,120150209001024,Block 1024,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
14_a_0,3.607147,3.184898,1.201502e+14,120150202062003,12,015,020900,2046,120150209002046,Block 2046,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
15_a_0,3.607147,11.551681,1.201502e+14,120150202062003,12,115,002745,2012,121150027452012,Block 2012,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
35_a_0,2.336572,1.160781,1.201502e+14,120150203033006,12,015,020700,2001,120150207002001,Block 2001,...,0.0,"POLYGON ((-82.13094 26.98116, -82.12994 26.981...",1.476313e+09,2.5,3.0,0.0,NaN,NaN,None,NaN
38_a_0,5.176091,4.666908,1.201502e+14,120150206011037,12,015,020601,1023,120150206011023,Block 1023,...,0.0,"POLYGON ((-82.10795 26.98017, -82.10795 26.981...",1.967622e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
39_a_0,5.176091,5.077636,1.201502e+14,120150206011037,12,115,002745,1003,121150027451003,Block 1003,...,0.0,"POLYGON ((-82.10795 26.98017, -82.10795 26.981...",1.967622e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
47_a_0,2.871884,2.719423,1.201502e+14,120150202041028,12,015,020900,1018,120150209001018,Block 1018,...,0.0,"POLYGON ((-82.08524 27.01352, -82.08436 27.013...",2.461173e+09,2.5,5.0,0.0,NaN,NaN,None,NaN
57_a_0,4.641491,3.179328,1.201502e+14,120150205012033,12,115,002746,1075,121150027461075,Block 1075,...,0.0,"POLYGON ((-82.14527 26.96886, -82.14465 26.968...",1.969005e+09,3.0,4.0,0.0,NaN,NaN,None,NaN
63_a_0,3.323089,0.704998,1.201502e+14,120150202041055,12,015,020602,1001,120150206021001,Block 1001,...,0.0,"POLYGON ((-82.07406 27.00198, -82.07218 27.001...",1.967499e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
88_a_0,3.836065,1.226623,1.201502e+14,120150202041028,12,015,020900,2031,120150209002031,Block 2031,...,0.0,"POLYGON ((-82.08524 27.01352, -82.08436 27.013...",2.461173e+09,2.5,5.0,0.0,NaN,NaN,None,NaN
115_a_0,0.970572,1.461962,1.202100e+14,120210005002000,12,021,000402,2003,120210004022003,Block 2003,...,0.0,"POLYGON ((-81.80964 26.15565, -81.80935 26.155...",1.980514e+09,24.5,4.0,0.0,NaN,NaN,None,NaN
170_a_0,2.693923,1.091655,1.207100e+14,120710014013009,12,071,001001,2019,120710010012019,Block 2019,...,0.0,"POLYGON ((-81.88380 26.57684, -81.88370 26.576...",1.494491e+09,4.5,3.0,0.0,NaN,NaN,None,NaN
179_a_0,6.514556,5.015326,1.207100e+14,120710103083020,12,071,020502,3015,120710205023015,Block 3015,...,0.0,"POLYGON ((-81.92998 26.62539, -81.92943 26.625...",3.980473e+09,10.0,8.0,0.0,NaN,NaN,None,NaN
209_a_0,2.507802,2.668417,1.207101e+14,120710103033020,12,071,010309,1010,120710103091010,Block 1010,...,0.0,"POLYGON ((-81.94287 26.61762, -81.94284 26.618...",9.954604e+08,1.0,2.0,0.0,NaN,NaN,None,NaN
228_a_0,3.23617,3.024365,1.207101e+14,120710104202052,12,071,010419,1003,120710104191003,Block 1003,...,0.0,"POLYGON ((-82.00956 26.62562, -82.00846 26.625...",3.978999e+09,7.0,8.0,0.0,NaN,NaN,None,NaN
246_a_0,7.637803,1.390919,1.207101e+14,120710104041014,12,071,010305,1016,120710103051016,Block 1016,...,0.0,"POLYGON ((-81.98901 26.63410, -81.98897 26.636...",1.493285e+09,4.5,3.0,0.0,NaN,NaN,None,NaN
306_a_0,3.381244,2.113288,1.207104e+14,120710402111005,12,071,040303,4035,120710403034035,Block 4035,...,0.0,"POLYGON ((-81.61779 26.61391, -81.61637 26.613...",4.469222e+09,8.5,9.0,0.0,NaN,NaN,None,NaN
307_a_0,3.381244,2.12654,1.207104e+14,120710402111005,12,071,040305,1010,120710403051010,Block 1010,...,0.0,"POLYGON ((-81.61779 26.61391, -81.61637 26.613...",4.469222e+09,8.5,9.0,0.0,NaN,NaN,None,NaN
327_a_0,2.73743,2.705247,1.207104e+14,120710403011002,12,071,040305,1029,120710403051029,Block 1029,...,0.0,"POLYGON ((-81.68402 26.60679, -81.68142 26.606...",9.957291e+08,3.0,2.0,0.0,NaN,NaN,None,NaN
328_a_0,2.73743,7.639654,1.207104e+14,120710403011002,12,071,040313,1072,120710403131072,Block 1072,...,0.0,"POLYGON ((-81.68402 26.60679, -81.68142 26.606...",9.957291e+08,3.0,2.0,0.0,NaN,NaN,None,NaN
370_a_0,1.090003,0.376696,1.208100e+14,120810006031034,12,081,000604,3003,120810006043003,Block 3003,...,0.0,"POLYGON ((-82.58355 27.48094, -82.58273 27.480...",2.971792e+09,6.0,6.0,0.0,NaN,NaN,None,NaN
467_a_0,1.484772,1.312206,1.211500e+14,121150006012003,12,115,000602,2010,121150006022010,Block 2010,...,0.0,"POLYGON ((-82.53365 27.30515, -82.53338 27.305...",5.930147e+09,6.0,12.0,0.0,NaN,NaN,None,NaN
540_a_0,2.750198,2.884297,1.211500e+14,121150027411054,12,115,002743,2026,121150027432026,Block 2026,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
541_a_0,2.750198,2.597073,1.211500e+14,121150027411054,12,115,002743,2030,121150027432030,Block 2030,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
542_a_0,2.750198,3.949629,1.211500e+14,121150027411054,12,115,002745,1038,121150027451038,Block 1038,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
543_a_0,2.750198,3.900497,1.211500e+14,121150027411054,12,115,002745,2069,121150027452069,Block 2069,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
544_a_0,7.736942,7.282639,1.201502e+14,121150027103009,12,115,002741,2011,121150027412011,Block 2011,...,0.0,"POLYGON ((-82.23786 27.03648, -82.23775 27.036...",1.972099e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
545_a_0,2.075968,1.079633,1.211500e+14,121150027411054,12,115,002741,2051,121150027412051,Block 2051,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
549_a_0,5.715517,4.607533,1.201502e+14,120150208001031,12,115,002746,1041,121150027461041,Block 1041,...,0.0,"POLYGON ((-82.08539 26.99940, -82.08462 26.999...",2.953455e+09,4.0,6.0,0.0,NaN,NaN,None,NaN
550_a_0,5.715517,4.170695,1.201502e+14,120150208001031,12,115,002747,2071,121150027472071,Block 2071,...,0.0,"POLYGON ((-82.08539 26.99940, -82.08462 26.999...",2.953455e+09,4.0,6.0,0.0,NaN,NaN,None,NaN
644_a_0,2.575911,5.662147,NaN,120710402102065,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.66225 26.65072, -81.66223 26.651...",NaN,NaN,28.0,NaN,NaN,NaN,POINT (26.65233 -81.66151),"(26.652333963314053, -81.66151286567091)"

In [589]:
merge_u_try2['cells_used']

6_a_0       1
7_a_0       0
8_a_0       0
9_a_0       0
10_a_0      0
11_a_0      0
12_a_0      0
13_a_0      0
14_a_0      0
15_a_0      0
35_a_0      1
38_a_0      1
39_a_0      0
47_a_0      1
57_a_0      0
63_a_0      1
88_a_0      0
115_a_0     0
170_a_0     1
179_a_0     1
209_a_0     0
228_a_0     2
246_a_0     1
306_a_0     2
307_a_0     0
327_a_0     0
328_a_0     0
370_a_0     2
467_a_0    10
540_a_0     0
541_a_0     0
542_a_0     0
543_a_0     0
544_a_0     1
545_a_0     0
549_a_0     0
550_a_0     0
644_a_0     9
Name: cells_used, dtype: int64

In [590]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0][Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000']<0]

Empty GeoDataFrame
Columns: [dist_x, dist, w_geocode, h_geocode_x, STATEFP20, COUNTYFP20, TRACTCE20, BLOCKCE20, GEOID20, NAME20, MTFCC20, UR20, UACE20, UATYPE20, FUNCSTAT20, ALAND20, AWATER20, INTPTLAT20, INTPTLON20, h_geocode_y, C000, CA01, CA02, CA03, CE01, CE02, CE03, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, CR01, CR02, CR03, CR04, CR05, CR07, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, createdate, fd_id_x, found_ht_x, cell_x, min_2030_x, cells_used, C000_dmg, C000_dmg_mean, h_geocode, fd_id_y, found_ht_y, min_2030_y, geometry, fd_id, found_ht, cell_y, min_2030, cell, loop_num, centr, centr_x_co]
Index: []

[0 rows x 82 columns]

In [591]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000'].sum()

1756

In [592]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['cells_used'].sum()

1699

In [593]:
merge_u_try2['C000'].sum()

91

In [594]:
merge_u_try2 = merge_u_try2.reset_index()
# merge_u_try2 = merge_u_try2.drop(['level_0'], axis=1)
merge_u_try2

,index,dist_x,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,...,min_2030_y,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co
0,6_a_0,3.607147,2.247294,1.201502e+14,120150202062003,12,015,020204,1049,120150202041049,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
1,7_a_0,3.607147,4.417017,1.201502e+14,120150202062003,12,015,020204,2038,120150202042038,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
2,8_a_0,3.607147,2.621194,1.201502e+14,120150202062003,12,015,020205,3013,120150202053013,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
3,9_a_0,3.607147,3.004297,1.201502e+14,120150202062003,12,015,020206,2092,120150202062092,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
4,10_a_0,3.607147,2.700523,1.201502e+14,120150202062003,12,015,020301,4013,120150203014013,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
5,11_a_0,3.607147,2.671328,1.201502e+14,120150202062003,12,015,020303,4024,120150203034024,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
6,12_a_0,3.607147,3.076096,1.201502e+14,120150202062003,12,015,020900,1011,120150209001011,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
7,13_a_0,3.607147,2.799715,1.201502e+14,120150202062003,12,015,020900,1024,120150209001024,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
8,14_a_0,3.607147,3.184898,1.201502e+14,120150202062003,12,015,020900,2046,120150209002046,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
9,15_a_0,3.607147,11.551681,1.201502e+14,120150202062003,12,115,002745,2012,121150027452012,...,0.0,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
10,35_a_0,2.336572,1.160781,1.201502e+14,120150203033006,12,015,020700,2001,120150207002001,...,0.0,"POLYGON ((-82.13094 26.98116, -82.12994 26.981...",1.476313e+09,2.5,3.0,0.0,NaN,NaN,None,NaN
11,38_a_0,5.176091,4.666908,1.201502e+14,120150206011037,12,015,020601,1023,120150206011023,...,0.0,"POLYGON ((-82.10795 26.98017, -82.10795 26.981...",1.967622e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
12,39_a_0,5.176091,5.077636,1.201502e+14,120150206011037,12,115,002745,1003,121150027451003,...,0.0,"POLYGON ((-82.10795 26.98017, -82.10795 26.981...",1.967622e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
13,47_a_0,2.871884,2.719423,1.201502e+14,120150202041028,12,015,020900,1018,120150209001018,...,0.0,"POLYGON ((-82.08524 27.01352, -82.08436 27.013...",2.461173e+09,2.5,5.0,0.0,NaN,NaN,None,NaN
14,57_a_0,4.641491,3.179328,1.201502e+14,120150205012033,12,115,002746,1075,121150027461075,...,0.0,"POLYGON ((-82.14527 26.96886, -82.14465 26.968...",1.969005e+09,3.0,4.0,0.0,NaN,NaN,None,NaN
15,63_a_0,3.323089,0.704998,1.201502e+14,120150202041055,12,015,020602,1001,120150206021001,...,0.0,"POLYGON ((-82.07406 27.00198, -82.07218 27.001...",1.967499e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
16,88_a_0,3.836065,1.226623,1.201502e+14,120150202041028,12,015,020900,2031,120150209002031,...,0.0,"POLYGON ((-82.08524 27.01352, -82.08436 27.013...",2.461173e+09,2.5,5.0,0.0,NaN,NaN,None,NaN
17,115_a_0,0.970572,1.461962,1.202100e+14,120210005002000,12,021,000402,2003,120210004022003,...,0.0,"POLYGON ((-81.80964 26.15565, -81.80935 26.155...",1.980514e+09,24.5,4.0,0.0,NaN,NaN,None,NaN
18,170_a_0,2.693923,1.091655,1.207100e+14,120710014013009,12,071,001001,2019,120710010012019,...,0.0,"POLYGON ((-81.88380 26.57684, -81.88370 26.576...",1.494491e+09,4.5,3.0,0.0,NaN,NaN,None,NaN
19,179_a_0,6.514556,5.015326,1.207100e+14,120710103083020,12,071,020502,3015,120710205023015,...,0.0,"POLYGON ((-81.92998 26.62539, -81.92943 26.625...",3.980473e+09,10.0,8.0,0.0,NaN,NaN,None,NaN
20,209_a_0,2.507802,2.668417,1.207101e+14,120710103033020,12,071,010309,1010,120710103091010,...,0.0,"POLYGON ((-81.94287 26.61762, -81.94284 26.618...",9.954604e+08,1.0,2.0,0.0,NaN,NaN,None,NaN
21,228_a_0,3.23617,3.024365,1.207101e+14,120710104202052,12,071,010419,1003,120710104191003,...,0.0,"POLYGON ((-82.00956 26.62562, -82.00846 26.625...",3.978999e+09,7.0,8.0,0.0,NaN,NaN,None,NaN
22,246_a_0,7.637803,1.390919,1.207101e+14,120710104041014,12,071,010305,1016,120710103051016,...,0.0,"POLYGON ((-81.98901 26.63410, -81.98897 26.636...",1.493285e+09,4.5,3.0,0.0,NaN,NaN,None,NaN
23,306_a_0,3.381244,2.113288,1.207104e+14,120710402111005,12,071,040303,4035,120710403034035,...,0.0,"POLYGON ((-81.61779 26.61391, -81.61637 26.613...",4.469222e+09,8.5,9.0,0.0,NaN,NaN,None,NaN
24,307_a_0,3.381244,2.12654,1.207104e+14,120710402111005,12,071,040305,1010,120710403051010,...,0.0,"POLYGON ((-81.61779 26.61391, -81.61637 26.613...",4.469222e+09,8.5,9.0,0.0,NaN,NaN,None,NaN
25,327_a_0,2.73743,2.705247,1.207104e+14,120710403011002,12,071,040305,1029,120710403051029,...,0.0,"POLYGON ((-81.68402 26.60679, -81.68142 26.606...",9.957291e+08,3.0,2.0,0.0,NaN,NaN,None,NaN
26,328_a_0,2.73743,7.639654,1.207104e+14,120710403011002,12,071,040313,1072,120710403131072,...,0.0,"POLYGON ((-81.68402 26.60679, -81.68142 26.606...",9.957291e+08,3.0,2.0,0.0,NaN,NaN,None,NaN
27,370_a_0,1.090003,0.376696,1.208100e+14,120810006031034,12,081,000604,3003,120810006043003,...,0.0,"POLYGON ((-82.58355 27.48094, -82.58273 27.480...",2.971792e+09,6.0,6.0,0.0,NaN,NaN,None,NaN
28,467_a_0,1.484772,1.312206,1.211500e+14,121150006012003,12,115,000602,2010,121150006022010,...,0.0,"POLYGON ((-82.53365 27.30515, -82.53338 27.305...",5.930147e+09,6.0,12.0,0.0,NaN,NaN,None,NaN
29,540_a_0,2.750198,2.884297,1.211500e+14,121150027411054,12,115,002743,2026,121150027432026,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
30,541_a_0,2.750198,2.597073,1.211500e+14,121150027411054,12,115,002743,2030,121150027432030,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
31,542_a_0,2.750198,3.949629,1.211500e+14,121150027411054,12,115,002745,1038,121150027451038,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
32,543_a_0,2.750198,3.900497,1.211500e+14,121150027411054,12,115,002745,2069,121150027452069,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
33,544_a_0,7.736942,7.282639,1.201502e+14,121150027103009,12,115,002741,2011,121150027412011,...,0.0,"POLYGON ((-82.23786 27.03648, -82.23775 27.036...",1.972099e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
34,545_a_0,2.075968,1.079633,1.211500e+14,121150027411054,12,115,002741,2051,121150027412051,...,0.0,"POLYGON ((-82.17979 27.07794, -82.17979 27.078...",4.436597e+09,4.5,9.0,0.0,NaN,NaN,None,NaN
35,549_a_0,5.715517,4.607533,1.201502e+14,120150208001031,12,115,002746,1041,121150027461041,...,0.0,"POLYGON ((-82.08539 26.99940, -82.08462 26.999...",2.953455e+09,4.0,6.0,0.0,NaN,NaN,None,NaN
36,550_a_0,5.715517,4.170695,1.201502e+14,120150208001031,12,115,002747,2071,121150027472071,...,0.0,"POLYGON ((-82.08539 26.99940, -82.08462 26.999...",2.953455e+09,4.0,6.0,0.0,NaN,NaN,None,NaN
37,644_a_0,2.575911,5.662147,NaN,120710402102065,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.66225 26.65072, -81.66223 26.651...",NaN,NaN,28.0,NaN,NaN,NaN,POINT (26.65233 -81.66151),"(26.652333963314053, -81.66151286567091)"

In [595]:
# merge_u_try2['h_geocode_y']['396_a_0']

In [596]:
merge_u_try2['h_geocode_y'][0]

120150202041049.0

In [597]:
merge_u_try2['GEOID20']

0     120150202041049
1     120150202042038
2     120150202053013
3     120150202062092
4     120150203014013
5     120150203034024
6     120150209001011
7     120150209001024
8     120150209002046
9     121150027452012
10    120150207002001
11    120150206011023
12    121150027451003
13    120150209001018
14    121150027461075
15    120150206021001
16    120150209002031
17    120210004022003
18    120710010012019
19    120710205023015
20    120710103091010
21    120710104191003
22    120710103051016
23    120710403034035
24    120710403051010
25    120710403051029
26    120710403131072
27    120810006043003
28    121150006022010
29    121150027432026
30    121150027432030
31    121150027451038
32    121150027452069
33    121150027412011
34    121150027412051
35    121150027461041
36    121150027472071
37                NaN
Name: GEOID20, dtype: object

In [598]:
merge_u_try2['h_geocode_y'] = merge_u_try2['GEOID20']

In [599]:
merge_u_try2 = merge_u_try2.drop(['w_geocode'],axis=1)

In [600]:
merge_u_try2['h_geocode']

0     120150202062003
1     120150202062003
2     120150202062003
3     120150202062003
4     120150202062003
5     120150202062003
6     120150202062003
7     120150202062003
8     120150202062003
9     120150202062003
10    120150203033006
11    120150206011037
12    120150206011037
13    120150202041028
14    120150205012033
15    120150202041055
16    120150202041028
17    120210005002000
18    120710014013009
19    120710103083020
20    120710103033020
21    120710104202052
22    120710104041014
23    120710402111005
24    120710402111005
25    120710403011002
26    120710403011002
27    120810006031034
28    121150006012003
29    121150027411054
30    121150027411054
31    121150027411054
32    121150027411054
33    121150027103009
34    121150027411054
35    120150208001031
36    120150208001031
37    120710402102103
Name: h_geocode, dtype: int64

In [602]:
# Emp_home_select_2030_part2_new2_temp['GEOID20'] = Emp_home_select_2030_part2_new2_temp['h_geocode']

In [551]:
Emp_home_select_2030_part2_new2_temp=Emp_home_select_2030_part2_new2_temp.drop(['h_geocode'],axis=1)

In [552]:
select_2030__merge_try2_temp = pd.merge(merge_u_try2, Emp_home_select_2030_part2_new2_temp,  how='left', 
                left_on=['geometry'], right_on = ['geometry'])
select_2030__merge_try2_temp.head()

,index,dist_x,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20_x,...,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co,GEOID20_y
0,6_a_0,3.607147,2.247294,1.201502e+14,120150202062003,12,015,020204,1049,120150202041049,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN,120150202062003
1,7_a_0,3.607147,4.417017,1.201502e+14,120150202062003,12,015,020204,2038,120150202042038,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN,120150202062003
2,8_a_0,3.607147,2.621194,1.201502e+14,120150202062003,12,015,020205,3013,120150202053013,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN,120150202062003
3,9_a_0,3.607147,3.004297,1.201502e+14,120150202062003,12,015,020206,2092,120150202062092,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN,120150202062003
4,10_a_0,3.607147,2.700523,1.201502e+14,120150202062003,12,015,020301,4013,120150203014013,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,None,NaN,120150202062003

In [603]:
select_2030__merge_try2_temp[select_2030__merge_try2_temp['h_geocode_y'].isna()]['GEOID20_y']

37    120710402102103
Name: GEOID20_y, dtype: int64

In [604]:
merge_u_try2['h_geocode_y']

0     120150202041049
1     120150202042038
2     120150202053013
3     120150202062092
4     120150203014013
5     120150203034024
6     120150209001011
7     120150209001024
8     120150209002046
9     121150027452012
10    120150207002001
11    120150206011023
12    121150027451003
13    120150209001018
14    121150027461075
15    120150206021001
16    120150209002031
17    120210004022003
18    120710010012019
19    120710205023015
20    120710103091010
21    120710104191003
22    120710103051016
23    120710403034035
24    120710403051010
25    120710403051029
26    120710403131072
27    120810006043003
28    121150006022010
29    121150027432026
30    121150027432030
31    121150027451038
32    121150027452069
33    121150027412011
34    121150027412051
35    121150027461041
36    121150027472071
37                NaN
Name: h_geocode_y, dtype: object

In [605]:
merge_u_try2.loc[
    merge_u_try2[merge_u_try2['h_geocode_y'].isna()].index[0],
    'h_geocode_y'
] = select_2030__merge_try2_temp[select_2030__merge_try2_temp['h_geocode_y'].isna()]['GEOID20_y'][
    merge_u_try2[merge_u_try2['h_geocode_y'].isna()]['h_geocode_y'].index[0]
]

In [702]:
merge_u_try2['h_geocode_y']

0     120150202041049
1     120150202042038
2     120150202053013
3     120150202062092
4     120150203014013
5     120150203034024
6     120150209001011
7     120150209001024
8     120150209002046
9     121150027452012
10    120150207002001
11    120150206011023
12    121150027451003
13    120150209001018
14    121150027461075
15    120150206021001
16    120150209002031
17    120210004022003
18    120710010012019
19    120710205023015
20    120710103091010
21    120710104191003
22    120710103051016
23    120710403034035
24    120710403051010
25    120710403051029
26    120710403131072
27    120810006043003
28    121150006022010
29    121150027432026
30    121150027432030
31    121150027451038
32    121150027452069
33    121150027412011
34    121150027412051
35    121150027461041
36    121150027472071
37    120710402102103
Name: h_geocode_y, dtype: int64

In [607]:
merge_u_try2 = merge_u_try2.astype({"h_geocode_y":'int64'})

In [608]:
merge_u_try2['h_geocode_x']

0     120150202062003
1     120150202062003
2     120150202062003
3     120150202062003
4     120150202062003
5     120150202062003
6     120150202062003
7     120150202062003
8     120150202062003
9     120150202062003
10    120150203033006
11    120150206011037
12    120150206011037
13    120150202041028
14    120150205012033
15    120150202041055
16    120150202041028
17    120210005002000
18    120710014013009
19    120710103083020
20    120710103033020
21    120710104202052
22    120710104041014
23    120710402111005
24    120710402111005
25    120710403011002
26    120710403011002
27    120810006031034
28    121150006012003
29    121150027411054
30    121150027411054
31    121150027411054
32    121150027411054
33    121150027103009
34    121150027411054
35    120150208001031
36    120150208001031
37    120710402102065
Name: h_geocode_x, dtype: object

In [609]:
merge_u_try2['C000']

0      2
1      1
2      1
3      2
4      1
5      1
6      1
7      1
8      3
9      2
10     2
11     2
12     2
13     3
14     1
15     2
16     1
17     2
18     2
19     2
20     1
21     4
22     2
23     3
24     2
25     1
26     1
27     3
28    11
29     1
30     1
31     1
32     3
33     2
34     3
35     1
36     2
37    15
Name: C000, dtype: int64

In [610]:
merge_u_try2['cells_used']

0      1
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     0
13     1
14     0
15     1
16     0
17     0
18     1
19     1
20     0
21     2
22     1
23     2
24     0
25     0
26     0
27     2
28    10
29     0
30     0
31     0
32     0
33     1
34     0
35     0
36     0
37     9
Name: cells_used, dtype: int64

In [611]:

# Emp_home_select_2030_new_values_merge_u_try5_4_2_2_[Emp_home_select_2030_new_values_merge_u_try5_4_2_2_['h_geocode_y']==10970028005002]

In [612]:
list_cells2_2030_3 = list(deepflatten(cells2_2030_3, depth=1))
Emp_cells2_2030_3_dic = []
# for i in range(0, len(Emp_cells2_dic2)):
Emp_cells2_2030_3_dic = Emp_cells2_2030_2_dic[0].loc[~Emp_cells2_2030_2_dic[0]['fd_id'].isin(list_cells2_2030_3)]
len(Emp_cells2_2030_3_dic)

268868

In [613]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000'].sum()

1756

In [614]:
len(Emp_cells2_2030_2_dic[0]) - len(Emp_cells2_2030_3_dic)

1699

In [615]:
select_hgeocode_geo5_6_try_try2_dic_missing['C000'].sum()

215

In [616]:
len(Emp_cells2) - len(Emp_cells2_2030_3_dic)

62259

In [617]:
Emp_home_select_2030_part2_new2['C000'].sum()

62328.0

## Unlock if merge_u_try2 exists

In [618]:
merge_u_try2['loop_num_3'] = 1

In [619]:
merge_u_try2 = merge_u_try2.astype({"h_geocode_x":'int64'})

In [620]:
merge_u_try2['C000'] = merge_u_try2['C000']-merge_u_try2['cells_used']

In [621]:
merge_u_try2= find_coordinates(merge_u_try2)

Yes
Yes

In [622]:
merge_u_try2=merge_u_try2.drop(['centr_x_co'],axis=1)

In [623]:
merge_u_try2.rename(columns = {'centr_co':'centr_x_co'}, inplace = True)
merge_u_try2.head()

,index,dist_x,dist,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,...,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,loop_num_3,centr_x_co
0,6_a_0,3.607147,2.247294,120150202062003,12,015,020204,1049,120150202041049,Block 1049,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.02209 -82.08482),1,"(27.022085486675074, -82.08481506355643)"
1,7_a_0,3.607147,4.417017,120150202062003,12,015,020204,2038,120150202042038,Block 2038,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.02209 -82.08482),1,"(27.022085486675074, -82.08481506355643)"
2,8_a_0,3.607147,2.621194,120150202062003,12,015,020205,3013,120150202053013,Block 3013,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.02209 -82.08482),1,"(27.022085486675074, -82.08481506355643)"
3,9_a_0,3.607147,3.004297,120150202062003,12,015,020206,2092,120150202062092,Block 2092,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.02209 -82.08482),1,"(27.022085486675074, -82.08481506355643)"
4,10_a_0,3.607147,2.700523,120150202062003,12,015,020301,4013,120150203014013,Block 4013,...,"POLYGON ((-82.08589 27.02152, -82.08520 27.022...",1.968580e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.02209 -82.08482),1,"(27.022085486675074, -82.08481506355643)"

In [624]:
Emp_cells2_2030_3_=[]
Emp_cells2_2030_3_sum=[]

# for i in range(0, len(Emp_cells2_dic2)):
Emp_cells2_2030_3_ = Emp_cells2_2030_3_dic.select_dtypes(exclude=['geometry','object'])
Emp_cells2_2030_3_sum = Emp_cells2_2030_3_.groupby(["h_geocode"], as_index=False).sum()
Emp_cells2_2030_3_sum

             h_geocode       fd_id  found_ht  cell  min_2030
0      120150101001000  3934160594      12.0     8       0.0
1      120150101001005   983313019       3.0     2       0.0
2      120150101001009  5408261652      12.5    11       0.0
3      120150101001010  2458356555       3.5     5       0.0
4      120150101001011   491661116       1.5     1       0.0
...                ...         ...       ...   ...       ...
17184  121150027472065  1971686487       2.0     4       0.0
17185  121150027472066   495342021       0.5     1       0.0
17186  121150027472069  2475194518       2.5     5       0.0
17187  121150027472070  1971686396       2.0     4       0.0
17188  121150027482003  1478765180       1.5     3       0.0

[17189 rows x 5 columns]

In [625]:
Emp_cells2_2030_3_sum=  Emp_cells2_2030_3_sum[['h_geocode','cell']]

In [626]:

Emp_cells_sum_no_dups_final_geo2_2030_final2=Emp_cells_sum_no_dups_final_geo2_2030_final2.drop(['cell'],axis=1)

Emp_cells_sum_no_dups_final_geo2_2030_final2 = pd.merge(Emp_cells_sum_no_dups_final_geo2, Emp_cells2_2030_3_sum,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])
Emp_cells_sum_no_dups_final_geo2_2030_final2.head()

,h_geocode,geometry,centr,centr_co,cell
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",8.0
1,120150101001005,"POLYGON ((-81.71209 26.97490, -81.71177 26.974...",POINT (26.96410 -81.68482),"(26.9640954048572, -81.68481803155792)",2.0
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",5.0
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",1.0
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",4.0

In [627]:
find_cells(Emp_cells_sum_no_dups_final_geo2_2030_final2,merge_u_try2)

n1= 0
temprory4=            h_geocode      dist  cell
211  120150202042015  0.372094   3.0
RHS= 120150202042015
C000= 1
cell_remain= 2.0
n1= 1
temprory4=            h_geocode      dist  cell
211  120150202042015  0.372094   2.0
RHS= 120150202042015
C000= 1
cell_remain= 1.0
n1= 2
temprory4=            h_geocode      dist  cell
209  120150202042007  0.413094   2.0
RHS= 120150202042007
C000= 1
cell_remain= 1.0
n1= 3
temprory4=            h_geocode      dist  cell
140  120150202042013  0.512098   5.0
RHS= 120150202042013
C000= 2
cell_remain= 3.0
n1= 4
temprory4=            h_geocode      dist  cell
255  120150202062073  0.509156   2.0
RHS= 120150202062073
C000= 1
cell_remain= 1.0
n1= 5
temprory4=            h_geocode      dist  cell
209  120150202042013  0.512098   3.0
RHS= 120150202042013
C000= 1
cell_remain= 2.0
n1= 6
temprory4=            h_geocode      dist  cell
209  120150202042013  0.512098   2.0
RHS= 120150202042013
C000= 1
cell_remain= 1.0
n1= 7
temprory4=            h_geocode      dist  cell
191  120150202041006  0.718604   3.0
RHS= 120150202041006
C000= 1
cell_remain= 2.0
n1= 8
temprory4=           h_geocode      dist  cell
96  120150202041003  0.739425   4.0
RHS= 120150202041003
C000= 3
cell_remain= 1.0
n1= 9
temprory4=            h_geocode      dist  cell
166  120150202062078  0.748071   8.0
RHS= 120150202062078
C000= 2
cell_remain= 6.0
n1= 10
temprory4=            h_geocode      dist  cell
292  120150203033027  0.182898   2.0
RHS= 120150203033027
C000= 1
cell_remain= 1.0
n1= 11
temprory4=            h_geocode      dist  cell
407  120150206011045  0.184441   5.0
RHS= 120150206011045
C000= 1
cell_remain= 4.0
n1= 12
temprory4=            h_geocode      dist  cell
265  120150206011045  0.184441   4.0
RHS= 120150206011045
C000= 2
cell_remain= 2.0
n1= 13
temprory4=            h_geocode      dist  cell
128  120150202041043  0.581155   5.0
RHS= 120150202041043
C000= 2
cell_remain= 3.0
n1= 14
temprory4=            h_geocode      dist  cell
378  120150205012038  0.204226   6.0
RHS= 120150205012038
C000= 1
cell_remain= 5.0
n1= 15
temprory4=            h_geocode      dist  cell
203  120150202041054  0.091587   3.0
RHS= 120150202041054
C000= 1
cell_remain= 2.0
n1= 16
temprory4=            h_geocode      dist  cell
193  120150202041031  0.460758   2.0
RHS= 120150202041031
C000= 1
cell_remain= 1.0
n1= 17
temprory4=            h_geocode      dist  cell
565  120210001021056  0.216194  10.0
RHS= 120210001021056
C000= 2
cell_remain= 8.0
n1= 18
temprory4=             h_geocode      dist  cell
2241  120710015012005  0.611638   6.0
RHS= 120710015012005
C000= 1
cell_remain= 5.0
n1= 19
temprory4=             h_geocode      dist  cell
3471  120710103083021  0.405182   2.0
RHS= 120710103083021
C000= 1
cell_remain= 1.0
n1= 20
temprory4=             h_geocode      dist  cell
3400  120710103033016  0.246146   6.0
RHS= 120710103033016
C000= 1
cell_remain= 5.0
n1= 21
temprory4=             h_geocode      dist  cell
3260  120710104202049  0.178317   4.0
RHS= 120710104202049
C000= 2
cell_remain= 2.0
n1= 22
temprory4=             h_geocode      dist  cell
3488  120710104041019  0.290011  13.0
RHS= 120710104041019
C000= 1
cell_remain= 12.0
n1= 23
temprory4=             h_geocode      dist  cell
5172  120710402111010  0.142477   3.0
RHS= 120710402111010
C000= 1
cell_remain= 2.0
n1= 24
temprory4=             h_geocode      dist  cell
4248  120710402111007  0.275752  18.0
RHS= 120710402111007
C000= 2
cell_remain= 16.0
n1= 25
temprory4=             h_geocode      dist  cell
5268  120710403011007  0.098306   3.0
RHS= 120710403011007
C000= 1
cell_remain= 2.0
n1= 26
temprory4=             h_geocode      dist  cell
5268  120710403011007  0.098306   2.0
RHS= 120710403011007
C000= 1
cell_remain= 1.0
n1= 27
temprory4=             h_geocode      dist  cell
6754  120810006031041  0.101384   3.0
RHS= 120810006031041
C000= 1
cell_remain= 2.0
n1= 28
temprory4=             h_geocode      dist  cell
8567  121150006012005  0.185049   3.0
RHS= 121150006012005
C000= 1
cell_remain= 2.0
n1= 29
temprory4=              h_geocode      dist  cell
11053  121150027411055  0.098705   3.0
RHS= 121150027411055
C000= 1
cell_remain= 2.0
n1= 30
temprory4=              h_geocode      dist  cell
11053  121150027411055  0.098705   2.0
RHS= 121150027411055
C000= 1
cell_remain= 1.0
n1= 31
temprory4=              h_geocode      dist  cell
11053  121150027411056  0.191157  10.0
RHS= 121150027411056
C000= 1
cell_remain= 9.0
n1= 32
temprory4=             h_geocode      dist  cell
8157  121150027411056  0.191157   9.0
RHS= 121150027411056
C000= 3
cell_remain= 6.0
n1= 33
temprory4=              h_geocode      dist  cell
10430  121150027103012  0.134593   2.0
RHS= 121150027103012
C000= 1
cell_remain= 1.0
n1= 34
temprory4=             h_geocode      dist  cell
8157  121150027411056  0.191157   6.0
RHS= 121150027411056
C000= 3
cell_remain= 3.0
n1= 35
temprory4=            h_geocode     dist  cell
432  120150208001030  0.07721   5.0
RHS= 120150208001030
C000= 1
cell_remain= 4.0
n1= 36
temprory4=            h_geocode     dist  cell
283  120150208001030  0.07721   4.0
RHS= 120150208001030
C000= 2
cell_remain= 2.0
n1= 37
temprory4=             h_geocode      dist  cell
2447  120710402081176  1.751928   7.0
RHS= 120710402081176
C000= 6
cell_remain= 1.0

In [628]:
merge_u_try2=merge_u_try2.drop(['loop_num'],axis=1)

In [705]:
# merge_u_try2=merge_u_try2.drop(['loop_num'],axis=1)
Emp_cells2_2030_3_dic2, cells2_2030_4, merge_u_try2_dic = find_cells_SLR(merge_u_try2, Emp_cells2_2030_3_dic)

Yes
i= 0
0.06940627098083496
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

1.3178880214691162
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
0.014678001403808594

In [706]:
merge_u_try2_dic[0]['h_geocode_y']

0_a_0     120150202041049
1_a_0     120150202042038
2_a_0     120150202053013
3_a_0     120150202062092
4_a_0     120150203014013
5_a_0     120150203034024
6_a_0     120150209001011
7_a_0     120150209001024
8_a_0     120150209002046
9_a_0     121150027452012
10_a_0    120150207002001
11_a_0    120150206011023
12_a_0    121150027451003
13_a_0    120150209001018
14_a_0    121150027461075
15_a_0    120150206021001
16_a_0    120150209002031
17_a_0    120210004022003
18_a_0    120710010012019
19_a_0    120710205023015
20_a_0    120710103091010
21_a_0    120710104191003
22_a_0    120710103051016
23_a_0    120710403034035
24_a_0    120710403051010
25_a_0    120710403051029
26_a_0    120710403131072
27_a_0    120810006043003
28_a_0    121150006022010
29_a_0    121150027432026
30_a_0    121150027432030
31_a_0    121150027451038
32_a_0    121150027452069
33_a_0    121150027412011
34_a_0    121150027412051
35_a_0    121150027461041
36_a_0    121150027472071
37_a_0    120710402102103
Name: h_geocode_y, dtype: int64

In [707]:
from joblib import Parallel, delayed

my_list_2=[]
my_list_3=[]
my_list_4=[]

start = time.time()


# Step 3: Use the provided code snippet to parallelize the calculations using the 'worker' function
result = Parallel(n_jobs=6)(delayed(cells_calc_x)(i, merge_u_try2_dic[i], Emp_cells2_2030_3_dic2[i], cells2_2030_4) for i in range(0,len(Raster_file_paths_new)))

# Convert the result to a dictionary with keys as indices
zs2_dic2 = dict(enumerate(result))

# Step 4: After calculating the results, retrieve the values from the 'zs2_dic' dictionary and store them in the lists 'my_list_2', 'my_list_3', and 'my_list_4'
my_list_2 = [zs2_dic2[i][0] for i in range(len(Raster_file_paths_new))]
my_list_3 = [zs2_dic2[i][1] for i in range(len(Raster_file_paths_new))]
my_list_4 = [zs2_dic2[i][2] for i in range(len(Raster_file_paths_new))]

end = time.time()
print(end - start)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

2.2938578128814697

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [708]:
my_list_2_final={}
my_list_3_final={}
my_list_4_final={}

for l in range(0,len(Raster_file_paths_new)):
    my_list_2_final[l]= my_list_2[l][0]
    my_list_3_final[l]= my_list_3[l][0]
    my_list_4_final[l]= my_list_4[l][0]
    
my_list_2={}
my_list_3={}
my_list_4={}

In [709]:
merge_u_try2_dic = dmg_calc(my_list_2_final, my_list_3_final,merge_u_try2_dic)

In [710]:
merge_u_try2_dic_full = dataframe_full(merge_u_try2_dic)

In [711]:
Emp_cells2_2030_4_dic2_list = list_4_calc(my_list_4_final,cells2_2030_4,Emp_cells2_dic)
Emp_cells2_2030_4_dic2_list

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage5,damage6,damage7,damage8,damage9,damage10,damage11,damage12,damage13,damage14
0,120150202041031,1021902.0,491884637,76VV2W5C+J6J-3-3-3-3,120150202012043,RES,RES1-1SNB,W,1.0,2225.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.759532
1,120150202042013,1025118.0,491887860,76VV2WC9+HWV-3-3-4-3,120150202014010,RES,RES1-1SNB,W,1.0,2189.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,120150202042013,1025119.0,491887861,76VV2WCC+23P-4-2-3-2,120150202014010,RES,RES1-1SNB,W,1.0,1372.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,120150202042013,1025123.0,491887865,76VV2WC9+8W7-3-4-4-3,120150202014010,RES,RES1-1SNB,W,1.0,1772.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,120150202042013,1025124.0,491887866,76VV2WC9+4WJ-3-4-4-3,120150202014010,RES,RES1-1SNB,W,1.0,1889.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,120150202041003,1034801.0,491897591,76VV2W79+V25-3-2-3-2,120150202012003,RES,RES1-1SNB,W,1.0,1080.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,120150202041003,1034802.0,491897592,76VV2W89+663-4-3-3-2,120150202012003,RES,RES1-1SNB,W,1.0,1586.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,120150202041003,1034808.0,491897598,76VV2W89+H69-3-1-3-2,120150202012003,RES,RES1-1SNB,W,1.0,1482.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,120150202062078,1035853.0,491898630,76VV2WC4+4HM-3-3-3-3,120150202022064,RES,RES1-1SNB,W,1.0,1660.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.965281
9,120150202062078,1035856.0,491898637,76VV2WC5+7P6-3-3-3-2,120150202022064,RES,RES1-1SNB,M,1.0,1281.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,120150206011045,1043960.0,491906315,76RVXVJR+8CF-3-2-3-3,120150206011042,RES,RES1-1SNB,W,1.0,1725.0,...,0.0,0.000000,16.408285,50.472224,95.009619,100.000000,100.000000,100.000000,100.000000,100.000000
11,120150206011045,1043961.0,491906317,76RVXVJR+44V-2-2-2-2,120150206011042,RES,RES1-1SNB,W,1.0,968.0,...,0.0,7.673722,32.899644,74.894391,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
12,120150206011045,1043970.0,491906335,76RVXVJR+8JJ-2-3-3-2,120150206011042,RES,RES1-1SNB,W,1.0,1359.0,...,0.0,20.858115,58.947558,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
13,120150203033027,1059010.0,491921796,76RVXVHC+HC9-4-3-3-3,120150203033027,RES,RES1-1SNB,W,1.0,2078.0,...,0.0,0.000000,0.000000,11.172450,42.813340,100.000000,100.000000,100.000000,100.000000,100.000000
14,120150202042007,1280466.0,492143298,76VV2WFC+62V-3-2-4-3,120150202014014,RES,RES1-1SNB,W,1.0,1676.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,120150202041006,1300938.0,492163767,76VV2W88+834-3-3-4-2,120150202012006,RES,RES1-1SNB,W,1.0,1902.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,120150202041043,1369591.0,492232410,76VV2W49+VG8-3-2-3-3,120150202012049,RES,RES1-1SNB,W,1.0,970.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,7.903360,33.378055,75.372803,100.000000
17,120150202041043,1369593.0,492232412,76VV2W49+XPG-4-3-4-4,120150202012049,RES,RES1-1SNB,W,1.0,1508.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,8.066217,33.717340,75.712088,100.000000
18,120150202042015,1396168.0,492258919,76VV2WCC+W38-3-2-3-4,120150202014009,RES,RES1-1SNB,W,1.0,2104.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,120150202042015,1396174.0,492258925,76VV2WC9+QH9-2-3-3-3,120150202014009,RES,RES1-1SNB,W,1.0,1679.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,120150202041054,1465396.0,492328172,76VV2W2G+6H3-4-3-4-4,120150202012067,RES,RES1-1SNB,W,1.0,1191.0,...,0.0,0.000000,0.000000,0.000000,0.000000,7.121201,15.074214,47.824672,89.819420,100.000000
21,120150202062073,1465639.0,492328415,76VV2WF5+HXC-5-3-4-3,120150202022061,RES,RES1-1SNB,W,1.0,2280.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,120150208001030,1525323.0,492387985,76RVXWX8+G7W-4-3-4-2,120150208001029,RES,RES1-1SNB,W,1.0,988.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
23,120150208001030,1525325.0,492387987,76RVXWX8+F8Q-4-3-3-2,120150208001029,RES,RES1-1SNB,W,1.0,1323.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
24,120150208001030,1525328.0,492387990,76RVXWX8+J6X-3-3-3-2,120150208001029,RES,RES1-1SNB,W,1.0,1743.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
25,120150205012038,1530619.0,492393405,76RVXV83+822-3-3-4-2,120150205012038,RES,RES1-1SNB,W,1.0,1513.0,...,0.0,0.000000,30.964477,72.959225,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
26,121150027411056,3643054.0,494506756,76VV3RJF+J56-5-3-5-3,121150027121216,RES,RES1-1SNB,W,1.0,1937.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,121150027411056,3643056.0,494506758,76VV3RJF+QF4-3-3-4-3,121150027121216,RES,RES1-1SNB,W,1.0,1457.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,121150027411056,3643057.0,494506759,76VV3RJF+C53-4-3-5-3,121150027121216,RES,RES1-1SNB,W,1.0,1426.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,121150027411056,3643367.0,494506761,76VV3RJC+CX8-4-4-4-4,121150027121216,RES,RES1-1SNB,W,1.0,1858.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,121150027411056,3643368.0,494506762,76VV3RJF+F2G-4-4-3-4,121150027121216,RES,RES1-1SNB,W,1.0,1617.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,121150027411056,3643370.0,494506764,76VV3RJF+62P-4-3-4-4,121150027121216,RES,RES1-1SNB,W,1.0,2020.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,121150027411056,3643371.0,494506765,76VV3RJF+G4R-5-3-4-3,121150027121216,RES,RES1-1SNB,W,1.0,1512.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,121150027411055,4184676.0,495048144,76VV3RJF+JR8-4-3-3-4,121150027121212,RES,RES1-1SNB,W,1.0,1547.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,121150027411055,4184682.0,495048150,76VV3RJF+235-5-4-5-3,121150027121212,RES,RES1-1SNB,W,1.0,2033.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,120210001021056,4204829.0,495068407,76RW45XW+72R-4-3-4-4,120210001021057,RES,RES1-1SNB,M,1.0,2030.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
36,120210001021056,4204830.0,495068408,76RW45XV+3P9-5-3-4-3,120210001021057,RES,RES1-1SNB,M,1.0,4240.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
37,121150027103012,4433297.0,495296718,76VV2QM8+P32-3-1-3-2,121150027103023,RES,RES1-1SNB,W,1.0,1072.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
38,120810006031041,4434450.0,495298405,76VVFCH8+PQ5-3-4-2-4,120810006031040,RES,RES1-1SNB,W,1.0,1056.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,121150006012005,4545307.0,495409006,76VV8F38+8RV-3-2-3-3,121150006012005,RES,RES1-1SNB,W,1.0,1794.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,120710402111010,5716093.0,496580361,76RWJ96J+8CM-4-2-3-3,120710402031018,RES,RES1-1SNB,W,1.0,1212.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,120710402081176,5736501.0,496600779,76RWM88W+866-3-3-3-2,120710402081171,RES,RES1-1SNB,W,1.0,1660.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,120710402081176,5736504.0,496600782,76RWM88W+Q6C-3-2-4-3,120710402081171,RES,RES1-1SNB,W,1.0,1679.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,120710402081176,5736508.0,496600786,76RWM88W+W5X-3-3-3-2,120710402081171,RES,RES1-1SNB,W,1.0,1646.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,120710402081176,5736509.0,496600787,76RWM89W+65H-3-3-3-3,120710402081171,RES,RES1-1SNB,W,1.0,1646.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,120710402081176,5736510.0,496600788,76RWM88W+C29-3-3-4-2,120710402081171,RES,RES1-1SNB,W,1.0,1679.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,120710402081176,5736511.0,496600789,76RWM88W+H6R-3-3-4-3,120710402081171,RES,RES1-1SNB,W,1.0,1679.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
47,120710403011007,5769544.0,496633850,76RWJ849+X3R-2-2-2-2,120710403011039,RES,RES1-1SNB,W,1.0,916.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
48,120710403011007,5769545.0,496633852,76RWJ849+R5C-2-3-2-3,120710403011039,RES,RES1-1SNB,W,1.0,1320.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
49,120710015012005,6222036.0,497086668,76RWH4F7+F6P-3-4-4-3,120710015012007,RES,RES1-1SNB,W,1.0,1769.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
50,120710103083021,6316657.0,497181309,76RWJ3HF+83F-3-3-3-4,120710103044040,RES,RES1-1SNB,W,1.0,1486.0,...,0.0,0.000000,0.000000,13.632767,47.677335,100.000000,100.000000,100.000000,100.000000,100.000000
51,120710104202049,6505013.0,497369493,76RVJXFR+F3P-2-2-4-2,120710104091036,RES,RES1-1SNB,W,1.0,1408.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
52,120710104202049,6505019.0,497369499,76RVJXGR+P3M-3-3-3-3,120710104091036,RES,RES1-1SNB,W,1.0,1882.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
53,120710103033016,6726674.0,497591402,76RWJ394+R78-4-3-5-2,120710103033013,RES,RES1-1SNB,W,1.0,2025.0,...,0.0,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,100.000000,100.000000
54,120710104041019,6757496.0,497622297,76RWJ2M6+4V6-3-3-3-3,120710104041031,RES,RES1-1SNB,W,1.0,1627.0,...,0.0,0.000000,0.000000,0.000000,0.000000,25.007034,41.083148,82.995871,100.000000,100.000000
55,120710402111007,6927586.0,497792372,76RWJ97P+27X-3-4-4-5,120710402031013,RES,RES1-1SNB,W,1.0,992.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
56,120710402111007,6927592.0,497792384,76RWJ97P+F4J-5-2-5-3,120710402031013,RES,RES1-1SNB,W,1.0,1040.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [712]:
len(new_list)

15

In [713]:
len(list_iterate)

105

In [714]:
Emp_cells2_2030_4_dic2_list=Emp_cells2_2030_4_dic2_list.drop(['cell'],axis=1)

In [715]:
def list4_2_full (Emp_cells2_dic_list4_2):
    Emp_cells2_dic_list4_2_modify = Emp_cells2_dic_list4_2.copy()

    for k in range(0,len(my_list_4_final)):
        Emp_cells2_dic_list4_2_modify= Emp_cells2_dic_list4_2_modify.drop(['damage{0}'.format(k)],axis=1)

    Emp_cells2_dic_list4_2_modify

    for index, i in enumerate(new_list):
    #     print(f"i: {i}, j: {index+1}")
        Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = Emp_cells2_dic_list4_2['damage{0}'.format(index)]

    for i in list_iterate:
        Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = 0
    Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify.iloc[:,33:]
    Emp_cells2_dic_list4_2_modify_select2 = Emp_cells2_dic_list4_2_modify.iloc[:,:33]

    sorted_columns = sorted(Emp_cells2_dic_list4_2_modify_select.columns, key=custom_sort)
    sorted_Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify_select[sorted_columns]

    Emp_cells2_dic_list4_2 = pd.concat([ Emp_cells2_dic_list4_2_modify_select2,sorted_Emp_cells2_dic_list4_2_modify_select],axis=1)

    return Emp_cells2_dic_list4_2

In [716]:
Emp_cells2_2030_4_dic2_list = list4_2_full(Emp_cells2_2030_4_dic2_list)

In [717]:
list_cells2_2030_4 = list(deepflatten(cells2_2030_4, depth=1))
Emp_cells2_2030_4_dic = []
# for i in range(0, len(Emp_cells2_dic2)):
Emp_cells2_2030_4_dic = Emp_cells2_2030_3_dic.loc[~Emp_cells2_2030_3_dic['fd_id'].isin(list_cells2_2030_4)]
len(Emp_cells2_2030_4_dic)

268811

In [718]:
Emp_home_select_2030_part2_new2['C000'].sum()

62328.0

In [719]:
len(Emp_cells2_dic2[0])- len(Emp_cells2_2030_4_dic)

62316

In [720]:
# # Emp_cells2_2030_1_try_list9


# for i in range(2, loop_ended+1):
#     print(i)
#     pd_trail = pd.concat([globals()['Emp_cells2_2030_1_try_list{0}'.format(i)]],axis=1)

In [721]:
# len(Emp_cells2_2030_1_try_list2)+len(Emp_cells2_2030_1_try_list3)+len(Emp_cells2_2030_1_try_list4)\
# +len(Emp_cells2_2030_1_try_list5)+len(Emp_cells2_2030_1_try_list6)+len(Emp_cells2_2030_1_try_list7)\
# +len(Emp_cells2_2030_1_try_list8)

In [722]:
# Emp_cells2_dic_list4_3=Emp_cells2_dic_list4_3.drop(['cell'],axis=1)

In [723]:
Emp_cells2_dic_list4_3 = list4_2_full(Emp_cells2_dic_list4_3)

In [724]:
# Emp_cells2_dic_list4=Emp_cells2_dic_list4.drop(['cell'],axis=1)

In [725]:
Emp_cells2_dic_list4 = list4_2_full(Emp_cells2_dic_list4)

In [726]:
# Emp_cells2_dic_list4_2=Emp_cells2_dic_list4_2.drop(['cell'],axis=1)

In [727]:
Emp_cells2_dic_list4_2 = list4_2_full(Emp_cells2_dic_list4_2)

In [728]:
for i in range(2, loop_ended+1):
#     globals()['Emp_cells2_2030_1_try_list{0}'.format(i)] = globals()['Emp_cells2_2030_1_try_list{0}'.format(i)].drop(['cell'],axis=1)
    globals()['Emp_cells2_2030_1_try_list{0}'.format(i)] = list4_2_full(globals()['Emp_cells2_2030_1_try_list{0}'.format(i)])

In [729]:
# Assuming the dataframes are named in a sequential manner
dataframes = []
for i in range(2, loop_ended+1):
    dataframe_name = f"Emp_cells2_2030_1_try_list{i}"
    dataframe = eval(dataframe_name)
    dataframes.append(dataframe)

In [730]:
# Assuming all the dataframes have the same columns
# We will store them in a list and then concatenate them
# Assuming the dataframes are named in a sequential manner
dataframes = []
for i in range(2, loop_ended+1):
    dataframe_name = f"Emp_cells2_2030_1_try_list{i}"
    dataframe = eval(dataframe_name)
    dataframes.append(dataframe)

# We will initialize total_dataframe with the first dataframe
total_dataframe = dataframes[0]

# We will then loop through the remaining dataframes
for dataframe in dataframes[1:]:
    # And append each dataframe to the total_dataframe
    total_dataframe = pd.concat(dataframes, ignore_index=True)

# Now total_dataframe contains all the data from the other dataframes
pd.DataFrame(total_dataframe)

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage110,damage111,damage112,damage113,damage114,damage115,damage116,damage117,damage118,damage119
0,120710802042005,3080.0,497915823,76RVFX26+JCM-0-0-0-0,120710802043007,RES,RES1-1SNB,W,1.0,1166.0,...,0,0,0,0,0,0,0,0,0,0
1,120150101001005,794052.0,491656425,76RWX8H5+9HW-2-2-2-2,120150101002000,RES,RES1-1SNB,M,1.0,732.0,...,0,0,0,0,0,0,0,0,0,0
2,120150201031021,859719.0,491722137,76VW2292+QFG-3-3-3-3,120150201031016,RES,RES1-1SNB,W,1.0,1440.0,...,0,0,0,0,0,0,0,0,0,0
3,120150201031021,859723.0,491722141,76VW22C2+2R9-4-3-3-4,120150201031016,RES,RES1-1SNB,W,1.0,1844.0,...,0,0,0,0,0,0,0,0,0,0
4,120150201031021,859732.0,491722150,76VW22C2+92V-4-2-3-2,120150201031016,RES,RES1-1SNB,W,1.0,1688.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10876,120710103083020,6694301.0,497559045,76RWJ3FF+WW6-3-2-3-4,120710103044031,RES,RES1-1SNB,W,1.0,1363.0,...,0,0,0,0,0,0,0,0,0,0
10877,120710103083020,6694333.0,497559063,76RWJ3FC+WC7-3-3-3-3,120710103044031,RES,RES1-1SNB,W,1.0,1585.0,...,0,0,0,0,0,0,0,0,0,0
10878,120710103083020,6694337.0,497559071,76RWJ3FC+WW7-3-2-2-3,120710103044031,RES,RES1-1SNB,W,1.0,1624.0,...,0,0,0,0,0,0,0,0,0,0
10879,120710103083020,6694374.0,497559099,76RWJ3GF+366-3-3-4-3,120710103044031,RES,RES1-1SNB,W,1.0,1559.0,...,0,0,0,0,0,0,0,0,0,0
10880,120710103083020,6694381.0,497559113,76RWJ3GC+3J7-3-3-2-2,120710103044031,RES,RES1-1SNB,W,1.0,1257.0,...,0,0,0,0,0,0,0,0,0,0

In [731]:
len(pd.DataFrame(total_dataframe)['fd_id'].unique())

10881

In [732]:
list4_final_out = pd.concat([Emp_cells2_dic_list4, pd.DataFrame(total_dataframe), Emp_cells2_dic_list4_2, Emp_cells2_dic_list4_3, Emp_cells2_2030_4_dic2_list],axis=0) 
       
list4_final_out

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage110,damage111,damage112,damage113,damage114,damage115,damage116,damage117,damage118,damage119
0,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0,0.0,0,0,0,0,0,0,0,0.0
1,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0,0.0,0,0,0,0,0,0,0,0.0
2,121150006021025,2554.0,494920398,76VV8F6F+8G4-2-3-2-3,121150006021027,RES,RES1-1SNB,W,1.0,1436.0,...,0,0.0,0,0,0,0,0,0,0,0.0
3,120210106041005,2691.0,495489665,76RW46MQ+RGF-0-0-0-0,120210106043008,RES,RES1-1SNB,W,1.0,1270.0,...,0,0.0,0,0,0,0,0,0,0,0.0
4,120150101001064,794179.0,491656542,76RWV7FJ+H84-4-3-5-3,120150101001001,RES,RES1-1SNB,M,1.0,1056.0,...,0,0.0,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,120710104202049,6505019.0,497369499,76RVJXGR+P3M-3-3-3-3,120710104091036,RES,RES1-1SNB,W,1.0,1882.0,...,0,100.0,0,0,0,0,0,0,0,100.0
53,120710103033016,6726674.0,497591402,76RWJ394+R78-4-3-5-2,120710103033013,RES,RES1-1SNB,W,1.0,2025.0,...,0,100.0,0,0,0,0,0,0,0,100.0
54,120710104041019,6757496.0,497622297,76RWJ2M6+4V6-3-3-3-3,120710104041031,RES,RES1-1SNB,W,1.0,1627.0,...,0,100.0,0,0,0,0,0,0,0,100.0
55,120710402111007,6927586.0,497792372,76RWJ97P+27X-3-4-4-5,120710402031013,RES,RES1-1SNB,W,1.0,992.0,...,0,0.0,0,0,0,0,0,0,0,0.0
56,120710402111007,6927592.0,497792384,76RWJ97P+F4J-5-2-5-3,120710402031013,RES,RES1-1SNB,W,1.0,1040.0,...,0,0.0,0,0,0,0,0,0,0,0.0

In [733]:
list4_final_out = list4_final_out.rename(columns={'damage' + str(i): 'damage' + str(i+1) for i in range(0, 720)})

In [734]:
list4_final_out

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage111,damage112,damage113,damage114,damage115,damage116,damage117,damage118,damage119,damage120
0,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0,0.0,0,0,0,0,0,0,0,0.0
1,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0,0.0,0,0,0,0,0,0,0,0.0
2,121150006021025,2554.0,494920398,76VV8F6F+8G4-2-3-2-3,121150006021027,RES,RES1-1SNB,W,1.0,1436.0,...,0,0.0,0,0,0,0,0,0,0,0.0
3,120210106041005,2691.0,495489665,76RW46MQ+RGF-0-0-0-0,120210106043008,RES,RES1-1SNB,W,1.0,1270.0,...,0,0.0,0,0,0,0,0,0,0,0.0
4,120150101001064,794179.0,491656542,76RWV7FJ+H84-4-3-5-3,120150101001001,RES,RES1-1SNB,M,1.0,1056.0,...,0,0.0,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,120710104202049,6505019.0,497369499,76RVJXGR+P3M-3-3-3-3,120710104091036,RES,RES1-1SNB,W,1.0,1882.0,...,0,100.0,0,0,0,0,0,0,0,100.0
53,120710103033016,6726674.0,497591402,76RWJ394+R78-4-3-5-2,120710103033013,RES,RES1-1SNB,W,1.0,2025.0,...,0,100.0,0,0,0,0,0,0,0,100.0
54,120710104041019,6757496.0,497622297,76RWJ2M6+4V6-3-3-3-3,120710104041031,RES,RES1-1SNB,W,1.0,1627.0,...,0,100.0,0,0,0,0,0,0,0,100.0
55,120710402111007,6927586.0,497792372,76RWJ97P+27X-3-4-4-5,120710402031013,RES,RES1-1SNB,W,1.0,992.0,...,0,0.0,0,0,0,0,0,0,0,0.0
56,120710402111007,6927592.0,497792384,76RWJ97P+F4J-5-2-5-3,120710402031013,RES,RES1-1SNB,W,1.0,1040.0,...,0,0.0,0,0,0,0,0,0,0,0.0

In [735]:
# list4_final_out = list4_final_out.reset_index()

In [736]:
# list4_final_out= list4_final_out.drop(['index'],axis=1)

In [737]:
year_1

2100

In [738]:
#Allocated cells with damages 

list4_final_out.to_file('Buildings_list4_final_out_{0}.shp'.format(year_1))

In [739]:
Emp_cells

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
360,120150201011010,1898.0,491767073,76VV2X3Q+JV7-3-3-4-4,120150201012010,RES,RES1-1SNB,W,1.0,1999.0,...,0.18,0.08,-82.010330,27.004031,NaN,5.329113,17.483967,POINT (-82.01033 27.00403),015,1
379,120150202061034,1938.0,491915584,76VV2VFQ+CPH-4-2-3-3,120150202021046,RES,RES1-1SNB,W,1.0,1657.0,...,0.18,0.08,-82.110648,27.023557,NaN,4.227000,13.868111,POINT (-82.11065 27.02356),015,1
385,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.18,0.08,-82.306143,26.923544,NaN,3.585037,11.761934,POINT (-82.30614 26.92354),015,1
386,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.13,0.03,-81.728035,25.913643,NaN,3.590633,11.780292,POINT (-81.72803 25.91364),021,1
393,120810020212027,1973.0,492122842,76VVCHV3+323-4-5-4-4,120810020072028,RES,RES1-1SNB,W,1.0,2784.0,...,0.17,0.04,-82.447449,27.442633,NaN,11.965964,39.258414,POINT (-82.44745 27.44263),081,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544324,120710303001023,7362124.0,498226804,76RWP93W+264-0-0-0-0,120710303001022,RES,RES1-1SNB,W,1.0,510.0,...,0.17,0.05,-81.604428,26.702522,NaN,3.825020,12.549277,POINT (-81.60443 26.70252),071,1
2544591,120710302011004,7362643.0,498226048,76RWM7W6+V2V-0-0-0-0,120710302011005,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.739960,26.697237,AE,2.931039,9.616270,POINT (-81.73996 26.69724),071,1
2544592,120710302011004,7362644.0,498226050,76RWM7V5+6PJ-0-0-0-0,120710302011017,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.740725,26.693076,AE,3.146635,10.323605,POINT (-81.74073 26.69308),071,1
2544599,120710302012002,7362651.0,498226064,76RWM7R5+3WR-0-0-0-0,120710302011024,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.740242,26.690234,AE,1.498931,4.917752,POINT (-81.74024 26.69023),071,1
2544610,120710302011004,7362662.0,498226086,76RWM7X8+8GX-0-0-0-0,120710302011005,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.733640,26.698365,NaN,3.087558,10.129784,POINT (-81.73364 26.69836),071,1

In [740]:
Emp_cells2_2030_3_dic_out = Emp_cells[Emp_cells['fd_id'].isin(Emp_cells2_2030_4_dic['fd_id'])]

In [741]:
Emp_cells2_2030_3_dic_out

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
360,120150201011010,1898.0,491767073,76VV2X3Q+JV7-3-3-4-4,120150201012010,RES,RES1-1SNB,W,1.0,1999.0,...,0.18,0.08,-82.010330,27.004031,NaN,5.329113,17.483967,POINT (-82.01033 27.00403),015,1
379,120150202061034,1938.0,491915584,76VV2VFQ+CPH-4-2-3-3,120150202021046,RES,RES1-1SNB,W,1.0,1657.0,...,0.18,0.08,-82.110648,27.023557,NaN,4.227000,13.868111,POINT (-82.11065 27.02356),015,1
393,120810020212027,1973.0,492122842,76VVCHV3+323-4-5-4-4,120810020072028,RES,RES1-1SNB,W,1.0,2784.0,...,0.17,0.04,-82.447449,27.442633,NaN,11.965964,39.258414,POINT (-82.44745 27.44263),081,1
405,120810020101000,1989.0,492164773,76VV9V2F+VXJ-4-4-4-3,120810020101000,RES,RES1-1SNB,W,1.0,840.0,...,0.17,0.04,-82.125094,27.352217,NaN,15.040739,49.346258,POINT (-82.12509 27.35222),081,1
406,120810020101000,1990.0,492165521,76VVCVRJ+F3G-3-2-4-2,120810020101000,RES,RES1-1SNB,M,1.0,2038.0,...,0.17,0.04,-82.119791,27.441175,NaN,22.509680,73.850658,POINT (-82.11979 27.44118),081,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544324,120710303001023,7362124.0,498226804,76RWP93W+264-0-0-0-0,120710303001022,RES,RES1-1SNB,W,1.0,510.0,...,0.17,0.05,-81.604428,26.702522,NaN,3.825020,12.549277,POINT (-81.60443 26.70252),071,1
2544591,120710302011004,7362643.0,498226048,76RWM7W6+V2V-0-0-0-0,120710302011005,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.739960,26.697237,AE,2.931039,9.616270,POINT (-81.73996 26.69724),071,1
2544592,120710302011004,7362644.0,498226050,76RWM7V5+6PJ-0-0-0-0,120710302011017,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.740725,26.693076,AE,3.146635,10.323605,POINT (-81.74073 26.69308),071,1
2544599,120710302012002,7362651.0,498226064,76RWM7R5+3WR-0-0-0-0,120710302011024,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.740242,26.690234,AE,1.498931,4.917752,POINT (-81.74024 26.69023),071,1
2544610,120710302011004,7362662.0,498226086,76RWM7X8+8GX-0-0-0-0,120710302011005,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.733640,26.698365,NaN,3.087558,10.129784,POINT (-81.73364 26.69836),071,1

In [742]:
Emp_cells2_2030_3_dic_out.to_pickle("bldgs_RES_remain_{0}.pickle".format(year_1))

In [743]:
def prepare_sum(Emp_home_select_2030_new_values_merge_u_dic):
    select = {}
    Emp_home_select_2030_new_values_merge_u_dic_ = {}
    Emp_home_select_2030_new_values_merge_u_dic_sum = {}
    Emp_home_select_2030_new_values_merge_u_dic_mean={}

    for i in range (0,len(Emp_home_select_2030_new_values_merge_u_dic)):
        select[i] = Emp_home_select_2030_new_values_merge_u_dic[i][Emp_home_select_2030_new_values_merge_u_dic[i]["C000_dmg"]>0]
        
        
        Emp_home_select_2030_new_values_merge_u_dic_[i] =  select[i].select_dtypes(exclude=['geometry'])    
        Emp_home_select_2030_new_values_merge_u_dic_[i] =  Emp_home_select_2030_new_values_merge_u_dic_[i][[
            'C000','CA01','CA02','CA03','CR01','CR02','CR03','CR04','CR05','CR07','CE01','CE02','CE03',
            'CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12',
            'CNS13','CNS14','CNS15','CNS16','CNS17','CNS18','CNS19','CNS20','C000_dmg','C000_dmg_mean',
            'CD01','CD02','CD03','CD04','CT01','CT02','CS01','CS02','C000_2030','CNS01_2030','CNS02_2030',
        'CNS03_2030','CNS04_2030','CNS05_2030','CNS06_2030','CNS07_2030','CNS08_2030','CNS09_2030','CNS10_2030',
        'CNS11_2030','CNS12_2030','CNS13_2030','CNS14_2030','CNS15_2030','CNS16_2030','CNS17_2030','CNS18_2030',
        'CNS19_2030','CNS20_2030','CR01_2030','CR02_2030','CR03_2030','CR04_2030','CR05_2030','CR07_2030',
        'CA01_2030','CA02_2030','CA03_2030','CE01_2030','CE02_2030','CE03_2030','CT01_2030','CT02_2030','CD01_2030',
        'CD02_2030','CD03_2030','CD04_2030','CS01_2030','CS02_2030','C000A_2030','C000E_2030','C000R_2030',
        'C000D_2030','C000T_2030','C000S_2030']] 
        Emp_home_select_2030_new_values_merge_u_dic_sum[i] = (Emp_home_select_2030_new_values_merge_u_dic_[i][Emp_home_select_2030_new_values_merge_u_dic_[i]["C000_dmg"]>0]).sum()
        Emp_home_select_2030_new_values_merge_u_dic_sum[i] =Emp_home_select_2030_new_values_merge_u_dic_sum[i].astype('int64')
        Emp_home_select_2030_new_values_merge_u_dic_mean[i] = Emp_home_select_2030_new_values_merge_u_dic_[i][['C000_dmg_mean']]
        Emp_home_select_2030_new_values_merge_u_dic_sum[i]['C000_dmg_mean_2030'] = (Emp_home_select_2030_new_values_merge_u_dic_mean[i][Emp_home_select_2030_new_values_merge_u_dic_mean[i]["C000_dmg_mean"]>0]).mean()[0]

    return Emp_home_select_2030_new_values_merge_u_dic_sum

In [744]:
for i in range(0,10):
    if i ==0:
        print('no damage')
    else:
        print(i)

no damage
1
2
3
4
5
6
7
8
9

In [745]:
def select_sum(select_hgeocode_geo5_6_dic_sum):
    import numpy as np
    import random
    select1 = {}
    select = {}
    unselect ={}
    final1 = {}
    final2 = {}
    bucket = []
    bucket2 = []

    bucket_list = [['empty','empty'], 23121210]
    bucket.append(bucket_list)
    
    bucket_list2 = [['empty','empty'], 23121212]
    bucket2.append(bucket_list2)


    for i in range (0,len(select_hgeocode_geo5_6_dic_sum)):
        
        if 'h_geocode_y' in select_hgeocode_geo5_6_dic_sum[i].columns:
            pass
        else: 
            select_hgeocode_geo5_6_dic_sum[i].rename(columns = {'h_geocode':'h_geocode_y'}, inplace = True)
        
        print('i=',i)
        max_value = []
        select1[i] = select_hgeocode_geo5_6_dic_sum[i][select_hgeocode_geo5_6_dic_sum[i]["C000_dmg"]>0]
        
#         print('select1[C000_dmg]',select1[i]['C000_dmg'])
        
        unselect[i] =select1[i].drop(['C000','CA01','CA02','CA03','CR01','CR02','CR03','CR04','CR05','CR07','CE01','CE02','CE03',
            'CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12',
            'CNS13','CNS14','CNS15','CNS16','CNS17','CNS18','CNS19','CNS20','C000_dmg','C000_dmg_mean',
            'CD01','CD02','CD03','CD04','CT01','CT02','CS01','CS02','h_geocode_y'],axis=1)
        
        select[i] =select1[i][['C000','CA01','CA02','CA03','CR01','CR02','CR03','CR04','CR05','CR07','CE01','CE02','CE03',
            'CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12',
            'CNS13','CNS14','CNS15','CNS16','CNS17','CNS18','CNS19','CNS20','C000_dmg','C000_dmg_mean',
            'CD01','CD02','CD03','CD04','CT01','CT02','CS01','CS02','h_geocode_y']]
        
        select[i] = select[i].reset_index()
        
        
        select[i]['C000_2030'] ={}
        select[i]['CNS01_2030'] ={}
        select[i]['CNS02_2030'] ={}
        select[i]['CNS03_2030'] ={}
        select[i]['CNS04_2030'] ={}
        select[i]['CNS05_2030'] ={}
        select[i]['CNS06_2030'] ={}
        select[i]['CNS07_2030'] ={}
        select[i]['CNS08_2030'] ={}
        select[i]['CNS09_2030'] ={}
        select[i]['CNS10_2030'] ={}
        select[i]['CNS11_2030'] ={}
        select[i]['CNS12_2030'] ={}
        select[i]['CNS13_2030'] ={}
        select[i]['CNS14_2030'] ={}
        select[i]['CNS15_2030'] ={}
        select[i]['CNS16_2030'] ={}
        select[i]['CNS17_2030'] ={}
        select[i]['CNS18_2030'] ={}
        select[i]['CNS19_2030'] ={}
        select[i]['CNS20_2030'] ={}
        select[i]['C000_2030']  ={}
        select[i]['CA01_2030'] ={}
        select[i]['CA02_2030'] ={}
        select[i]['CA03_2030'] ={}
        select[i]['CE01_2030'] ={}
        select[i]['CE02_2030'] ={}
        select[i]['CE03_2030'] ={}
        select[i]['CR01_2030'] ={}
        select[i]['CR02_2030'] ={}
        select[i]['CR03_2030'] ={}
        select[i]['CR04_2030'] ={}
        select[i]['CR05_2030'] ={}
        select[i]['CR07_2030'] ={}
        select[i]['CD01_2030'] ={}
        select[i]['CD02_2030'] ={}
        select[i]['CD03_2030'] ={}
        select[i]['CD04_2030'] ={}
        select[i]['CT01_2030'] ={}
        select[i]['CT02_2030'] ={}
        select[i]['CS01_2030'] ={}
        select[i]['CS02_2030'] ={}
        select[i]['C000A_2030'] ={}
        select[i]['C000E_2030'] ={}
        select[i]['C000R_2030'] ={}
        select[i]['C000S_2030'] ={}
        select[i]['C000T_2030'] ={}
        select[i]['C000D_2030'] ={}
        
        for q in range (0,len(select[i])):
#             print('select[i][CNS01]=',select[i]['CNS01'])
#             print('select[i]=',select[i])
#             print('select[i][CNS01][q]=',select[i]['CNS01'][q])
#             if pd.isna(select[i]['CNS01'][q]):
#                 select[i]['CNS01'][q].replace(np.nan, 0, inplace=True)
#                 print('CNS01=',pd.DataFrame(select[i]['CNS01'][q]))
#             else:
#                 pass
#             print('CNS01=',select[i]['CNS01'][q])
#             print('C000=',select[i]['C000'][q])
#             print('C000_dmg=',select[i]['C000_dmg'][q])
#             print('h_geocode_y=',select[i]['h_geocode_y'][q])

            select[i]['CNS01_2030'][q]=Round_up((select[i]['CNS01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS02_2030'][q]=Round_up((select[i]['CNS02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS03_2030'][q]=Round_up((select[i]['CNS03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS04_2030'][q]=Round_up((select[i]['CNS04'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS05_2030'][q]=Round_up((select[i]['CNS05'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS06_2030'][q]=Round_up((select[i]['CNS06'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS07_2030'][q]=Round_up((select[i]['CNS07'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS08_2030'][q]=Round_up((select[i]['CNS08'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS09_2030'][q]=Round_up((select[i]['CNS09'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS10_2030'][q]=Round_up((select[i]['CNS10'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS11_2030'][q]=Round_up((select[i]['CNS11'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS12_2030'][q]=Round_up((select[i]['CNS12'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS13_2030'][q]=Round_up((select[i]['CNS13'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS14_2030'][q]=Round_up((select[i]['CNS14'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS15_2030'][q]=Round_up((select[i]['CNS15'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS16_2030'][q]=Round_up((select[i]['CNS16'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS17_2030'][q]=Round_up((select[i]['CNS17'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS18_2030'][q]=Round_up((select[i]['CNS18'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS19_2030'][q]=Round_up((select[i]['CNS19'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS20_2030'][q]=Round_up((select[i]['CNS20'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CA01_2030'][q]=Round_up((select[i]['CA01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CA02_2030'][q]=Round_up((select[i]['CA02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CA03_2030'][q]=Round_up((select[i]['CA03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CE01_2030'][q]=Round_up((select[i]['CE01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CE02_2030'][q]=Round_up((select[i]['CE02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CE03_2030'][q]=Round_up((select[i]['CE03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR01_2030'][q]=Round_up((select[i]['CR01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR02_2030'][q]=Round_up((select[i]['CR02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR03_2030'][q]=Round_up((select[i]['CR03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR04_2030'][q]=Round_up((select[i]['CR04'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR05_2030'][q]=Round_up((select[i]['CR05'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR07_2030'][q]=Round_up((select[i]['CR07'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CD01_2030'][q]=Round_up((select[i]['CD01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CD02_2030'][q]=Round_up((select[i]['CD02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CD03_2030'][q]=Round_up((select[i]['CD03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CD04_2030'][q]=Round_up((select[i]['CD04'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CT01_2030'][q]=Round_up((select[i]['CT01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CT02_2030'][q]=Round_up((select[i]['CT02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CS01_2030'][q]=Round_up((select[i]['CS01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CS02_2030'][q]=Round_up((select[i]['CS02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])      
            
#             print('CD01=',select[i]['CD01'][q])
#             print('CD02=',select[i]['CD02'][q])
#             print('CD03=',select[i]['CD03'][q])
#             print('CD04=',select[i]['CD04'][q])            
#             print('CD01_2030=',select[i]['CD01_2030'][q])
#             print('CD02_2030=',select[i]['CD02_2030'][q])
#             print('CD03_2030=',select[i]['CD03_2030'][q])
#             print('CD04_2030=',select[i]['CD04_2030'][q])
#             print('C000_dmg=',select[i]['C000_dmg'][q])
#             print('C000=',select[i]['C000'][q])

            select[i]['C000_2030'][q] = select[i]['CNS01_2030'][q]\
                                                            +select[i]['CNS02_2030'][q]\
                                                            +select[i]['CNS03_2030'][q]\
                                                            +select[i]['CNS04_2030'][q]\
                                                            +select[i]['CNS05_2030'][q]\
                                                            +select[i]['CNS06_2030'][q]\
                                                            +select[i]['CNS07_2030'][q]\
                                                            +select[i]['CNS08_2030'][q]\
                                                            +select[i]['CNS09_2030'][q]\
                                                            +select[i]['CNS10_2030'][q]\
                                                            +select[i]['CNS11_2030'][q]\
                                                            +select[i]['CNS12_2030'][q]\
                                                            +select[i]['CNS13_2030'][q]\
                                                            +select[i]['CNS14_2030'][q]\
                                                            +select[i]['CNS15_2030'][q]\
                                                            +select[i]['CNS16_2030'][q]\
                                                            +select[i]['CNS17_2030'][q]\
                                                            +select[i]['CNS18_2030'][q]\
                                                            +select[i]['CNS19_2030'][q]\
                                                            +select[i]['CNS20_2030'][q]
#             print('q=',q)
#             print('C000_2030',select[i]['C000_2030'] )


            select[i]['C000A_2030'][q] = select[i]['CA01_2030'][q]\
                                                             +select[i]['CA02_2030'][q]\
                                                             +select[i]['CA03_2030'][q]

            select[i]['C000E_2030'][q] = select[i]['CE01_2030'][q]\
                                                             +select[i]['CE02_2030'][q]\
                                                             +select[i]['CE03_2030'][q]

            select[i]['C000R_2030'][q] = select[i]['CR01_2030'][q]\
                                                             +select[i]['CR02_2030'][q]\
                                                             +select[i]['CR03_2030'][q]\
                                                             +select[i]['CR04_2030'][q]\
                                                             +select[i]['CR05_2030'][q]\
                                                             +select[i]['CR07_2030'][q]

            select[i]['C000D_2030'][q] = select[i]['CD01_2030'][q]\
                                                             +select[i]['CD02_2030'][q]\
                                                             +select[i]['CD03_2030'][q]\
                                                             +select[i]['CD04_2030'][q]

            select[i]['C000T_2030'][q] = select[i]['CT01_2030'][q]\
                                                             +select[i]['CT02_2030'][q]

            select[i]['C000S_2030'][q] = select[i]['CS01_2030'][q]\
                                                             +select[i]['CS02_2030'][q]
                
                
                
            if select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] == 1 :
#                 print('C000_dmg - C000_2030=', select[i]['C000_dmg'][q] - select[i]['C000_2030'][q])
#                 print('select[i][h_geocode_y] =',(select[i]['h_geocode_y'][q]))
                max_value_test0 = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                             'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                             'CNS19','CNS20']].iloc[q,:]).T.max().max() 
                max_value_columns_test0 = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].max() == max_value_test0]
#                 print('max_value_columns_test0=',max_value_columns_test0)
                max_value_random_test0 = random.choice(max_value_columns_test0) 
#                 print('max_value_random_test0=',max_value_random_test0)

                if (i in range(0,len(select_hgeocode_geo5_6_dic_sum),3)) and (select[i]['h_geocode_y'][q]) not in (pd.DataFrame(bucket2)[1].values):
                    max_value_0 = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.max().max() 
                    max_value_columns_0 = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].max() == max_value_0]
                    max_value_random_0 = random.choice(max_value_columns_0) 
                    
                    bucket_list2 = [max_value_random_0,select[i]['h_geocode_y'][q]]
#                     print('bucket_list=',bucket_list2)
                    
#                     print('max_value_random_0_if=',max_value_random_0)
                elif ((select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket2)[1].values)) :
                    max_value_random_0_temp = pd.DataFrame(bucket2)[0].values[pd.DataFrame(bucket2)[1].values == (select[i]['h_geocode_y'][q])]
#                     print('(max_value_random_0_temp[0])',(max_value_random_0_temp[0]))
#                     print('(max_value_random_0_temp)',(max_value_random_0_temp))

                    if isinstance((max_value_random_0_temp)[0], list) :
#                         print('used this one (if)')
                        max_value_random_0_list = max_value_random_0_temp[0]
                        max_value_random_0 = random.choice(max_value_random_0_list) 
                        
                    else:
                        max_value_random_0 = max_value_random_0_temp[0]
#                         print('used this (else)')
#                     print('max_value_random_0_elif=',max_value_random_0)   

                else:
                    max_value_random_0 = max_value_random_test0
                    bucket_list2 = [max_value_random_0,select[i]['h_geocode_y'][q]]

#                 print('max_value_random_0=',max_value_random_0)   
#                 print('LHS_before',select[i][max_value_random_0+'_2030'][q])
                select[i][max_value_random_0+'_2030'][q] =select[i][max_value_random_0+'_2030'][q]\
                    + (select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] )
#                 print('LHS_after',select[i][max_value_random_0+'_2030'][q])

                
            if select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] > 1 :
#                 print('C000_dmg - C000_2030=', select[i]['C000_dmg'][q] - select[i]['C000_2030'][q])
#                 print('select[i][h_geocode_y] =',(select[i]['h_geocode_y'][q]))
                max_value_test = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                             'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                             'CNS19','CNS20']].iloc[q,:]).T.max().max() 
                max_value_columns_test = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].max() == max_value_test]
#                 print('max_value_columns_test=',max_value_columns_test)
#                 print('len(max_value_columns_test)=',len(max_value_columns_test))
#                 print('max_value_columns_test[0]=',max_value_columns_test[0])
#                 print('C000_2030[q]',select[i]['C000_2030'][q] )
#                 select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                select[i]['C000_dmg'] = select[i]['C000_dmg'].astype(int)

                if len(max_value_columns_test) >1 :
#                     select[i]['C000_2030'] = select[i]['C000_2030'][q].astype(int)
                    if (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]) > len(max_value_columns_test):
                        temp_list = ['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                 'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                 'CNS19','CNS20']
                        temp_select = list(set(temp_list)-set(max_value_columns_test))
#                         print('temp_select=',temp_select)
                        max_value_test_try2 = pd.DataFrame(select[i][temp_select].iloc[q,:]).T.max().max()                     
                        max_value_columns_test_try2 = [col for col in pd.DataFrame(select[i][temp_select].iloc[q,:]).T.columns if pd.DataFrame(select[i][temp_select].iloc[q,:]).T[col].max() == max_value_test_try2]
                        temp_select_final = list(set(max_value_columns_test) | set(max_value_columns_test_try2))
#                         print('temp_select_final=',temp_select_final)
#                         print('k=',(select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                        if (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]) < len(temp_select_final):
                            select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                            max_value_random_test = random.sample(temp_select_final, k= (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                        else:
                            max_value_random_test=temp_select_final
                    else:
                        pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                        select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                        max_value_random_test = random.sample(max_value_columns_test, k= (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                        
                else:
                    max_value_random_test = max_value_columns_test[0]

#                 print('max_value_random_test=',max_value_random_test)
                if (i in range(0,len(select_hgeocode_geo5_6_dic_sum),3)) and (select[i]['h_geocode_y'][q]) not in (pd.DataFrame(bucket2)[1].values):
                    max_value_ = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.max().max() 
                    max_value_columns_ = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].max() == max_value_]
                    
#                     select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                    if len(max_value_columns_) > 1 :
                        if (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]) > len(max_value_columns_test):
                            temp_list = ['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                     'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                     'CNS19','CNS20']
                            temp_select_ = list(set(temp_list)-set(max_value_columns_))
#                             print('temp_select_=',temp_select_)
                            max_value_try2 = pd.DataFrame(select[i][temp_select_].iloc[q,:]).T.max().max()                     
                            max_value_columns_try2 = [col for col in pd.DataFrame(select[i][temp_select_].iloc[q,:]).T.columns if pd.DataFrame(select[i][temp_select_].iloc[q,:]).T[col].max() == max_value_try2]
                            temp_select_final_ = list(set(max_value_columns_) | set(max_value_columns_try2))
                            if (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]) < len(temp_select_final):
                                select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                                max_value_random_ = random.sample(temp_select_final_, k= (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                            else:
                                max_value_random_=temp_select_final_
                        else:
                            max_value_random_ = random.sample(max_value_columns_, k= (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                    else:
                        max_value_random_ = max_value_columns_[0]
                    bucket_list2 = [max_value_random_,select[i]['h_geocode_y'][q]]
#                     print('max_value_random_if=',max_value_random_)
#                     print('bucket_list2=',bucket_list2)

                elif ((select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket2)[1].values)) :
                    max_value_random_temp = pd.DataFrame(bucket2)[0].values[pd.DataFrame(bucket2)[1].values == (select[i]['h_geocode_y'][q])]
                    max_value_random_ = max_value_random_temp[0]
#                     print('max_value_random_elif=',max_value_random_)
                    
                else:
                    max_value_random_ = max_value_random_test
                    bucket_list2 = [max_value_random_,select[i]['h_geocode_y'][q]]
#                     print('max_value_random_else=',max_value_random_)

                if isinstance((max_value_random_), list) :
                    for o in range(0, len(max_value_random_)):
                        select[i][max_value_random_[o]+'_2030'][q] =select[i][max_value_random_[o]+'_2030'][q]\
                            + ((select[i]['C000_dmg'][q] - select[i]['C000_2030'][q])/len(max_value_random_) )    
                else:
                    select[i][max_value_random_+'_2030'][q] =(select[i][max_value_random_+'_2030'][q])\
                    + (select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] )
    
                
            if select[i]['C000D_2030'][q] < select[i]['C000_dmg'][q]:
                max_value = pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T.max().max() #to find the max number of employees between CD01, CD02, CD03,CD04
                max_value_columns = [col for col in pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T[col].max() == max_value]
                max_value_random = random.choice(max_value_columns) # to select one column rondomly in case two or more columns have the same number of employees
#                 print('max_value_random=',max_value_random)
#                 print('C000_D_2030_before=' , select[i][max_value_random][q]\
#                       + (select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] ))
                select[i][max_value_random+'_2030'][q] =(select[i][max_value_random+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000D_2030'][q] )
#                 print('C000_D_2030_after=' , (select[i][max_value_random][q])\
#                       + (select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] ))
                
            if select[i]['C000A_2030'][q] < select[i]['C000_dmg'][q]:
                max_value2 = pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T.max().max() #to find the max number of employees between CD01, CD02, CD03,CD04
                max_value_columns2 = [col for col in pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T[col].max() == max_value2]
                max_value_random2 = random.choice(max_value_columns2) # to select one column rondomly in case two or more columns have the same number of employees
                select[i][max_value_random2+'_2030'][q] =(select[i][max_value_random2+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000A_2030'][q] )

            if select[i]['C000E_2030'][q] < select[i]['C000_dmg'][q]:
                max_value3 = pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T.max().max() 
                max_value_columns3 = [col for col in pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T[col].max() == max_value3]
                max_value_random3 = random.choice(max_value_columns3) 
                select[i][max_value_random3+'_2030'][q] =(select[i][max_value_random3+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000E_2030'][q] )
                
            if select[i]['C000R_2030'][q] < select[i]['C000_dmg'][q]:
                max_value4 = pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T.max().max() 
                max_value_columns4 = [col for col in pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T[col].max() == max_value4]
                max_value_random4 = random.choice(max_value_columns4) 
                select[i][max_value_random4+'_2030'][q] =(select[i][max_value_random4+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000R_2030'][q] )
                
            if select[i]['C000T_2030'][q] < select[i]['C000_dmg'][q]:
                max_value4 = pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T.max().max() 
                max_value_columns4 = [col for col in pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T[col].max() == max_value4]
                max_value_random4 = random.choice(max_value_columns4) 
                select[i][max_value_random4+'_2030'][q] =(select[i][max_value_random4+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000T_2030'][q] )
                
            if select[i]['C000S_2030'][q] < select[i]['C000_dmg'][q]:
                max_value5 = pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T.max().max() 
                max_value_columns5 = [col for col in pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T[col].max() == max_value5]
                max_value_random5 = random.choice(max_value_columns5) 
                select[i][max_value_random5+'_2030'][q] =(select[i][max_value_random5+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000S_2030'][q] )
                
            if select[i]['C000D_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
                min_value = pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T.min().min() #to find the min number of employees between CD01, CD02, CD03,CD04
                min_value_columns = [col for col in pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T[col].min() == min_value]
                min_value_random = random.choice(min_value_columns) # to select one column rondomly in case two or more columns have the same number of employees
#                 print('min_value_random2=',min_value_random)
#                 print('C000_D_2030_before=' , select[i][min_value_random+'_2030'][q])
                select[i][min_value_random+'_2030'][q] =select[i][min_value_random+'_2030'][q]\
                    - (select[i]['C000D_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('C000_D_2030_after=' , select[i][min_value_random+'_2030'][q])
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))

    
            if select[i]['C000_2030'][q] - select[i]['C000_dmg'][q] == 1 :
#                 print('C000_2030 - C000_dmg=', select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])

#                 print('check_null_1_before', select[i].isnull().values.any())
                select[i].replace(0, np.nan, inplace=True)
#                 print('select[i][h_geocode_y] =',(select[i]['h_geocode_y'][q]))
#                 print('pd.DataFrame(bucket)[1].values)=',pd.DataFrame(bucket)[1].values)
#                 print('pd.DataFrame(bucket)[1].values)',(select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket)[1].values))
                min_value_test0 = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                             'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                             'CNS19','CNS20']].iloc[q,:]).T.min().min() 
                min_value_columns_test0 = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].min() == min_value_test0]
#                 print('min_value_columns_test0=',min_value_columns_test0)
                min_value_random_test0 = random.choice(min_value_columns_test0) 
#                 print('min_value_random_test0=',min_value_random_test0)

                if (i in range(0,len(select_hgeocode_geo5_6_dic_sum),3)) and (select[i]['h_geocode_y'][q]) not in (pd.DataFrame(bucket)[1].values):
                    min_value_0 = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.min().min() 
                    min_value_columns_0 = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].min() == min_value_0]
                    min_value_random_0 = random.choice(min_value_columns_0) 
                    
                    bucket_list = [min_value_random_0,select[i]['h_geocode_y'][q]]
#                     print('bucket_list=',bucket_list)
                    
#                     print('min_value_random_0_if=',min_value_random_0)
                elif ((select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket)[1].values)) :
                    min_value_random_0_temp = pd.DataFrame(bucket)[0].values[pd.DataFrame(bucket)[1].values == (select[i]['h_geocode_y'][q])]
#                     print('len(min_value_random_0_temp)',len(pd.DataFrame(min_value_random_0_temp)[0].T))
#                     print('(min_value_random_0_temp[0])',(min_value_random_0_temp[0]))
#                     print('(min_value_random_0_temp)',(min_value_random_0_temp))

                    if isinstance((min_value_random_0_temp)[0], list) :
#                         print('used this one (if)')
                        min_value_random_0_list = min_value_random_0_temp[0]
                        min_value_random_0 = random.choice(min_value_random_0_list) 
                        
                    else:
                        min_value_random_0 = min_value_random_0_temp[0]
#                         print('used this (else)')
#                     print('min_value_random_0_elif=',min_value_random_0)   

                else:
                    min_value_random_0 = min_value_random_test0
                    bucket_list = [min_value_random_0,select[i]['h_geocode_y'][q]]

                    
#                 bucket.append(bucket_list)
#                 print('bucket=',bucket)
#                 print('min_value_random_0=',min_value_random_0)   
#                 print('LHS_before',select[i][min_value_random_0+'_2030'][q])
                select[i][min_value_random_0+'_2030'][q] =select[i][min_value_random_0+'_2030'][q]\
                    - (select[i]['C000_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('LHS_after',select[i][min_value_random_0+'_2030'][q])

#                 print('check_null_1_after', select[i].isnull().values.any())
                select[i].replace(np.nan, 0, inplace=True)
#                 print('check_null_1_after2', select[i].isnull().values.any())
            
                
            if select[i]['C000_2030'][q] - select[i]['C000_dmg'][q] > 1 :
#                 print('C000_2030 - C000_dmg=', select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 print('select[i][h_geocode_y] =',(select[i]['h_geocode_y'][q]))
#                 print('pd.DataFrame(bucket)[1].values)=',pd.DataFrame(bucket)[1].values)
#                 print('pd.DataFrame(bucket)[1].values)',(select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket)[1].values))
                min_value_test = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                             'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                             'CNS19','CNS20']].iloc[q,:]).T.min().min() 
                min_value_columns_test = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].min() == min_value_test]
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                select[i]['C000_dmg'] = select[i]['C000_dmg'].astype(int)
#                 print('min_value_columns_test=',min_value_columns_test)
#                 print('select[i][C000_2030][q]=', select[i]['C000_2030'][q])
#                 print('select[i][C000_dmg][q]=', select[i]['C000_dmg'][q])
                
                if len(min_value_columns_test) >1 :
#                     select[i]['C000_2030'] = select[i]['C000_2030'][q].astype(int)
                    if (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]) > len(min_value_columns_test):
                        temp_list = ['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                 'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                 'CNS19','CNS20']
                        temp_select = list(set(temp_list)-set(min_value_columns_test))
#                         print('temp_select=',temp_select)
                        min_value_test_try2 = pd.DataFrame(select[i][temp_select].iloc[q,:]).T.min().min()                     
                        min_value_columns_test_try2 = [col for col in pd.DataFrame(select[i][temp_select].iloc[q,:]).T.columns if pd.DataFrame(select[i][temp_select].iloc[q,:]).T[col].min() == min_value_test_try2]
                        temp_select_final = list(set(min_value_columns_test) | set(min_value_columns_test_try2))
#                         print('temp_select_final=',temp_select_final)
                        select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                        min_value_random_test = random.sample(temp_select_final, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))
                    else:
                        pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                        select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                        min_value_random_test = random.sample(min_value_columns_test, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))
                        
                else:
                    min_value_random_test = min_value_columns_test[0]
                    
#                 print('min_value_random_test_error=',min_value_random_test)

#                 min_value_random_test = random.sample(min_value_columns_test, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))


                if (i in range(0,len(select_hgeocode_geo5_6_dic_sum),3)) and (select[i]['h_geocode_y'][q]) not in (pd.DataFrame(bucket)[1].values):
                    pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
                    min_value_ = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.min().min() 
                    min_value_columns_ = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].min() == min_value_]
#                 pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
#                 print('C000_2030=',select[i]['C000_2030'][q])
#                 print('C000_dmg=',select[i]['C000_dmg'][q])
#                 print('C000_2030_type', select[i]['C000_2030'][q].dtype)
#                 print('C000_2030_type_true_false=', select[i]['C000_2030'][q].dtype == 'float64' )
#                 print('C000_2030_list', select[i]['C000_2030'])
#                 if select[i]['C000_2030'][q].dtype == 'float64':  
                    
#                 print('C000_2030=',select[i]['C000_2030'][q])
#                 print('C000_2030_type', select[i]['C000_2030'][q].dtype)

                    pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                    select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
        
                    if len(min_value_columns_) >1 :
    #                     select[i]['C000_2030'] = select[i]['C000_2030'][q].astype(int)
                        if (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]) > len(min_value_columns_):
                            temp_list = ['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                     'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                     'CNS19','CNS20']
                            temp_select = list(set(temp_list)-set(min_value_columns_))
    #                         print('temp_select=',temp_select)
                            min_value_try2 = pd.DataFrame(select[i][temp_select].iloc[q,:]).T.min().min()                     
                            min_value_columns_try2 = [col for col in pd.DataFrame(select[i][temp_select].iloc[q,:]).T.columns if pd.DataFrame(select[i][temp_select].iloc[q,:]).T[col].min() == min_value_try2]
                            temp_select_final = list(set(min_value_columns_) | set(min_value_columns_try2))
#                             print('temp_select_final=',temp_select_final)
                            select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                            min_value_random_ = random.sample(temp_select_final, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))
                        else:
                            pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                            select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                            min_value_random_ = random.sample(min_value_columns_, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))

                    else:
                        min_value_random_ = min_value_columns_[0]
        
#                     min_value_random_ = random.sample(min_value_columns_, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))
                    bucket_list = [min_value_random_,select[i]['h_geocode_y'][q]]
#                     print('min_value_random_if=',min_value_random_)
#                     print('bucket_list=',bucket_list)
#                     print('bucket_list[0]=',bucket_list[0])

                elif ((select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket)[1].values)) :
                    min_value_random_temp = pd.DataFrame(bucket)[0].values[pd.DataFrame(bucket)[1].values == (select[i]['h_geocode_y'][q])]
                    min_value_random_ = min_value_random_temp[0]
#                     print('min_value_random_elif=',min_value_random_)    
                    
                else: 
                    min_value_random_ = min_value_random_test
                    bucket_list = [min_value_random_,select[i]['h_geocode_y'][q]]
#                     print('min_value_random_else=',min_value_random_)    
          
                if isinstance((min_value_random_), list) :
                    for o in range(0, len(min_value_random_)):
    #                     print('o=',o)
    #                     print('q=',q)
    #                     print('min_value_random_',min_value_random_)
    #                     print('LHS=',select[i][min_value_random_[o]+'_2030'][q])

    #                     print('RHS=',select[i][min_value_random_[o]+'_2030'][q]\
    #                         - ((select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])/len(min_value_random_) ))
                        select[i][min_value_random_[o]+'_2030'][q] =select[i][min_value_random_[o]+'_2030'][q]\
                            - ((select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])/len(min_value_random_) )
                else:
                    select[i][min_value_random_+'_2030'][q] =select[i][min_value_random_+'_2030'][q]\
                            - ((select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])/len(min_value_random_) )
    

                
            if select[i]['C000A_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 if i in range(0,720,3) : 
                min_value2 = pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T.min().min() 
                min_value_columns2 = [col for col in pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T[col].min() == min_value2]
                min_value_random2 = random.choice(min_value_columns2) 
#                 print('min_value_random2_if=',min_value_random2)                
#                 else:
#                     print('min_value_random2_else=',min_value_random2)                

                select[i][min_value_random2+'_2030'][q] =select[i][min_value_random2+'_2030'][q]\
                    - (select[i]['C000A_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_3', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
            if select[i]['C000E_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 if i in range(0,720,3) : 
                min_value3 = pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T.min().min()
                min_value_columns3 = [col for col in pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T[col].min() == min_value3]
                min_value_random3 = random.choice(min_value_columns3) 
#                 print('min_value_random3_if=',min_value_random3)     
#                 else:
#                     print('min_value_random3_else=',min_value_random3)     
                    
                select[i][min_value_random3+'_2030'][q] =select[i][min_value_random3+'_2030'][q]\
                    - (select[i]['C000E_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_4', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
            if select[i]['C000R_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 if i in range(0,15,3) : 
                min_value4 = pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T.min().min()
                min_value_columns4 = [col for col in pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T[col].min() == min_value4]
                min_value_random4 = random.choice(min_value_columns4) 
#                 print('min_value_random4_if=',min_value_random4)     
#                 else:
#                     print('min_value_random4_if=',min_value_random4)     
                    
                select[i][min_value_random4+'_2030'][q] =select[i][min_value_random4+'_2030'][q]\
                    - (select[i]['C000R_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_5', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
            if select[i]['C000T_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 if i in range(0,15,3) : 
                min_value5 = pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T.min().min()
                min_value_columns5 = [col for col in pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T[col].min() == min_value5]
                min_value_random5 = random.choice(min_value_columns5) 
#                 print('min_value_random5_if=',min_value_random5)     
#                 else:
#                     print('min_value_random5_if=',min_value_random5)     
                    
                select[i][min_value_random5+'_2030'][q] =select[i][min_value_random5+'_2030'][q]\
                    - (select[i]['C000T_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_6', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
            if select[i]['C000S_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True)) 
                min_value6 = pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T.min().min()
                min_value_columns6 = [col for col in pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T[col].min() == min_value6]
                min_value_random6 = random.choice(min_value_columns6) 
#                 print('min_value_random6_if=',min_value_random6)     

                select[i][min_value_random6+'_2030'][q] =select[i][min_value_random6+'_2030'][q]\
                    - (select[i]['C000S_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_7', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
                
#             print('check_null_final', select[i].isnull().values.any())
            select[i]['C000A_2030'][q] = select[i]['CA01_2030'][q]\
                                                             +select[i]['CA02_2030'][q]\
                                                             +select[i]['CA03_2030'][q]

            select[i]['C000E_2030'][q] = select[i]['CE01_2030'][q]\
                                                             +select[i]['CE02_2030'][q]\
                                                             +select[i]['CE03_2030'][q]

            select[i]['C000R_2030'][q] = select[i]['CR01_2030'][q]\
                                                             +select[i]['CR02_2030'][q]\
                                                             +select[i]['CR03_2030'][q]\
                                                             +select[i]['CR04_2030'][q]\
                                                             +select[i]['CR05_2030'][q]\
                                                             +select[i]['CR07_2030'][q]

            select[i]['C000D_2030'][q] = select[i]['CD01_2030'][q]\
                                                             +select[i]['CD02_2030'][q]\
                                                             +select[i]['CD03_2030'][q]\
                                                             +select[i]['CD04_2030'][q]

            select[i]['C000T_2030'][q] = select[i]['CT01_2030'][q]\
                                                             +select[i]['CT02_2030'][q]\

            select[i]['C000S_2030'][q] = select[i]['CS01_2030'][q]\
                                                             +select[i]['CS02_2030'][q]\

                

            select[i]['C000_2030'][q] = select[i]['CNS01_2030'][q]\
                                                            +select[i]['CNS02_2030'][q]\
                                                            +select[i]['CNS03_2030'][q]\
                                                            +select[i]['CNS04_2030'][q]\
                                                            +select[i]['CNS05_2030'][q]\
                                                            +select[i]['CNS06_2030'][q]\
                                                            +select[i]['CNS07_2030'][q]\
                                                            +select[i]['CNS08_2030'][q]\
                                                            +select[i]['CNS09_2030'][q]\
                                                            +select[i]['CNS10_2030'][q]\
                                                            +select[i]['CNS11_2030'][q]\
                                                            +select[i]['CNS12_2030'][q]\
                                                            +select[i]['CNS13_2030'][q]\
                                                            +select[i]['CNS14_2030'][q]\
                                                            +select[i]['CNS15_2030'][q]\
                                                            +select[i]['CNS16_2030'][q]\
                                                            +select[i]['CNS17_2030'][q]\
                                                            +select[i]['CNS18_2030'][q]\
                                                            +select[i]['CNS19_2030'][q]\
                                                            +select[i]['CNS20_2030'][q]
#         print('select[CA01_2030]=',select[i]['CA01_2030'])

            if bucket_list in bucket:
                pass
            else:                
                bucket.append(bucket_list)
#                 print('bucket=',bucket)
                
            if bucket_list2 in bucket2:
                pass
            else:                
                bucket2.append(bucket_list2)
#                 print('bucket2=',bucket2)
    

        select[i].set_index('index', inplace=True)
    
        final1[i] = pd.concat([select[i], unselect[i]], axis=1)
        final1[i].sort_index(inplace=True)
#         print('final1[CA01_2030]=',final1[i]['CA01_2030'])

#         final2[i] = pd.concat([final1[i], unselect1[i]], axis=0)
    return final1

# use the following function to combine all C000_dmg to the Emp_home_select_2030_part1_new2

In [746]:
dataframes2_temp2={}


# list of data frames
# Assume that the original dataframe is named 'original_df'
for i in range(0, len(Raster_file_paths)):
    dataframes2_temp2[i] = Emp_home_select_2030_part2_new2.copy()

# Convert the dictionary to a list of tuples
dataframes2_part2 = list(dataframes2_temp2.values())


# dictionary to save data frames
Emp_home_select_2030_part2_new2_dic={} 

for key22, value22 in enumerate(dataframes2_part2):    
    Emp_home_select_2030_part2_new2_dic[key22] = value22 # assigning data frame from list to key in dictionary

In [747]:
def get_accurate_C000(select_hgeocode_geo5_6_try3, Emp_home_select_2030_part1_new2_dic, n ):
    
    select_hgeocode_geo5_6_try3_C000={}
    Emp_home_select_2030_part1_new2_dic2={}
    
    for i in range(0, len(select_hgeocode_geo5_6_try3)):
        if 'h_geocode_y' in select_hgeocode_geo5_6_try3[i].columns:
            pass
        else: 
            select_hgeocode_geo5_6_try3[i].rename(columns = {'h_geocode':'h_geocode_y'}, inplace = True)    
            
        select_hgeocode_geo5_6_try3_C000[i] = select_hgeocode_geo5_6_try3[i][['h_geocode_y','C000_dmg','C000_dmg_mean','C000']]

        select_hgeocode_geo5_6_try3_C000[i].rename(columns = {'h_geocode_y':'h_geocode',
                                                               'C000_dmg':'C000_dmg_'+str(n),
                                                              'C000_dmg_mean':'C000_dmg_mean_'+str(n),
                                                               'C000':'C000_'+str(n)}, inplace = True)
        
        
        Emp_home_select_2030_part1_new2_dic2[i] = pd.merge(
            Emp_home_select_2030_part1_new2_dic[i], select_hgeocode_geo5_6_try3_C000[i], how="left", on=["h_geocode"])

    return Emp_home_select_2030_part1_new2_dic2

In [748]:
# len(select_hgeocode_geo5_6_dic2_full)

In [749]:
Emp_home_select_2030_part2_new2_dic[0].head()

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CT01,CT02,CD01,CD02,CD03,CD04,CS01,CS02,createdate,geometry
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612..."
1,12,021,010411,1000,120210104111000,Block 1000,G5040,NaN,NaN,NaN,...,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.69629 26.18436, -81.69546 26.184..."
2,12,021,010408,1005,120210104081005,Block 1005,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20231016,"POLYGON ((-81.73524 26.20540, -81.73522 26.205..."
3,12,021,011208,1028,120210112081028,Block 1028,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20231016,"POLYGON ((-81.44029 26.32594, -81.44019 26.326..."
4,12,081,002003,1002,120810020031002,Block 1002,G5040,NaN,NaN,NaN,...,2.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-82.50990 27.50864, -82.50986 27.508..."

In [750]:
len(select_hgeocode_geo5_6_dic2)

15

In [751]:
select_hgeocode_geo5_6_dic2_full = dataframe_full(select_hgeocode_geo5_6_dic2)

In [752]:
len(select_hgeocode_geo5_6_dic2_full)

120

In [753]:

Emp_home_select_2030_part2_new2_dic = get_accurate_C000(select_hgeocode_geo5_6_dic2_full,Emp_home_select_2030_part2_new2_dic, 1 )

In [754]:
len(Emp_home_select_2030_part2_new2_dic)

120

In [755]:
for i in range(2, loop_ended+1):
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32

In [756]:
# len(globals()['select_hgeocode_geo5_6_try_try{0}_dic_full'.format(i)])

In [757]:
for i in range(2, loop_ended+1):
    globals()['select_hgeocode_geo5_6_try_try{0}_dic_full'.format(i)] = dataframe_full(globals()['select_hgeocode_geo5_6_try_try{0}_dic'.format(i)])

In [758]:
for i in range(2, loop_ended+1):
    Emp_home_select_2030_part2_new2_dic = get_accurate_C000(globals()['select_hgeocode_geo5_6_try_try{0}_dic_full'.format(i)],Emp_home_select_2030_part2_new2_dic, i )

In [759]:
Emp_home_select_2030_new_values_merge_u_dic_full = dataframe_full(Emp_home_select_2030_new_values_merge_u_dic)

In [760]:

Emp_home_select_2030_part2_new2_dic = get_accurate_C000(Emp_home_select_2030_new_values_merge_u_dic_full,Emp_home_select_2030_part2_new2_dic, loop_ended+1 )

In [761]:
loop_ended+2

34

In [762]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic_full = dataframe_full(Emp_home_select_2030_new_values_merge_u_try5_5_6_dic)

In [763]:

Emp_home_select_2030_part2_new2_dic = get_accurate_C000(Emp_home_select_2030_new_values_merge_u_try5_5_6_dic_full,Emp_home_select_2030_part2_new2_dic, loop_ended+2 )

In [764]:
merge_u_try2_dic_full = dataframe_full(merge_u_try2_dic)

In [765]:
len(merge_u_try2_dic_full)

120

In [766]:
merge_u_try2_dic_full[0]['h_geocode_y']

0_a_0     120150202041049
1_a_0     120150202042038
2_a_0     120150202053013
3_a_0     120150202062092
4_a_0     120150203014013
5_a_0     120150203034024
6_a_0     120150209001011
7_a_0     120150209001024
8_a_0     120150209002046
9_a_0     121150027452012
10_a_0    120150207002001
11_a_0    120150206011023
12_a_0    121150027451003
13_a_0    120150209001018
14_a_0    121150027461075
15_a_0    120150206021001
16_a_0    120150209002031
17_a_0    120210004022003
18_a_0    120710010012019
19_a_0    120710205023015
20_a_0    120710103091010
21_a_0    120710104191003
22_a_0    120710103051016
23_a_0    120710403034035
24_a_0    120710403051010
25_a_0    120710403051029
26_a_0    120710403131072
27_a_0    120810006043003
28_a_0    121150006022010
29_a_0    121150027432026
30_a_0    121150027432030
31_a_0    121150027451038
32_a_0    121150027452069
33_a_0    121150027412011
34_a_0    121150027412051
35_a_0    121150027461041
36_a_0    121150027472071
37_a_0    120710402102103
Name: h_geocode_y, dtype: int64

In [767]:
len(Emp_home_select_2030_part2_new2_dic)

120

In [768]:
len(merge_u_try2_dic_full)

120

In [769]:
merge_u_try2_dic_full[0]['h_geocode_y']

0_a_0     120150202041049
1_a_0     120150202042038
2_a_0     120150202053013
3_a_0     120150202062092
4_a_0     120150203014013
5_a_0     120150203034024
6_a_0     120150209001011
7_a_0     120150209001024
8_a_0     120150209002046
9_a_0     121150027452012
10_a_0    120150207002001
11_a_0    120150206011023
12_a_0    121150027451003
13_a_0    120150209001018
14_a_0    121150027461075
15_a_0    120150206021001
16_a_0    120150209002031
17_a_0    120210004022003
18_a_0    120710010012019
19_a_0    120710205023015
20_a_0    120710103091010
21_a_0    120710104191003
22_a_0    120710103051016
23_a_0    120710403034035
24_a_0    120710403051010
25_a_0    120710403051029
26_a_0    120710403131072
27_a_0    120810006043003
28_a_0    121150006022010
29_a_0    121150027432026
30_a_0    121150027432030
31_a_0    121150027451038
32_a_0    121150027452069
33_a_0    121150027412011
34_a_0    121150027412051
35_a_0    121150027461041
36_a_0    121150027472071
37_a_0    120710402102103
Name: h_geocode_y, dtype: int64

In [770]:
Emp_home_select_2030_part2_new2_dic = get_accurate_C000(merge_u_try2_dic_full,Emp_home_select_2030_part2_new2_dic, loop_ended+3 )

In [771]:
prefix = 'C000_dmg_'
numbers = list(range(1, loop_ended+3+1))
columns_to_sum = [prefix + str(num) for num in numbers]

In [772]:
columns_to_sum

['C000_dmg_1',
 'C000_dmg_2',
 'C000_dmg_3',
 'C000_dmg_4',
 'C000_dmg_5',
 'C000_dmg_6',
 'C000_dmg_7',
 'C000_dmg_8',
 'C000_dmg_9',
 'C000_dmg_10',
 'C000_dmg_11',
 'C000_dmg_12',
 'C000_dmg_13',
 'C000_dmg_14',
 'C000_dmg_15',
 'C000_dmg_16',
 'C000_dmg_17',
 'C000_dmg_18',
 'C000_dmg_19',
 'C000_dmg_20',
 'C000_dmg_21',
 'C000_dmg_22',
 'C000_dmg_23',
 'C000_dmg_24',
 'C000_dmg_25',
 'C000_dmg_26',
 'C000_dmg_27',
 'C000_dmg_28',
 'C000_dmg_29',
 'C000_dmg_30',
 'C000_dmg_31',
 'C000_dmg_32',
 'C000_dmg_33',
 'C000_dmg_34',
 'C000_dmg_35']

In [773]:
for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    for j in range(1,loop_ended+3+1 ):
        Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_{0}'.format(j)] = Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_{0}'.format(j)].fillna(0)
    
  
    
    prefix = 'C000_dmg_'
    numbers = list(range(1, loop_ended+3+1))
    columns_to_sum = [prefix + str(num) for num in numbers]

    Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_total'] = Emp_home_select_2030_part2_new2_dic[i][columns_to_sum].sum(axis=1)

In [774]:
Emp_home_select_2030_part2_new2_dic[0]['C000_dmg_total'].sum()

0.0

In [775]:
1418+263+21+1+1+205+24

1933

In [776]:
for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    for j in range(1,loop_ended+3+1 ):
        Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_mean_{0}'.format(j)] = Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_mean_{0}'.format(j)].fillna(0)

        
    prefix2 = 'C000_dmg_mean_'
    numbers = list(range(1, loop_ended+3+1))
    columns_to_sum2 = [prefix2 + str(num) for num in numbers]    
           
    Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_mean_total'] = Emp_home_select_2030_part2_new2_dic[i][columns_to_sum2].sum(axis=1)

In [777]:
combined_list = columns_to_sum + columns_to_sum2
combined_list

['C000_dmg_1',
 'C000_dmg_2',
 'C000_dmg_3',
 'C000_dmg_4',
 'C000_dmg_5',
 'C000_dmg_6',
 'C000_dmg_7',
 'C000_dmg_8',
 'C000_dmg_9',
 'C000_dmg_10',
 'C000_dmg_11',
 'C000_dmg_12',
 'C000_dmg_13',
 'C000_dmg_14',
 'C000_dmg_15',
 'C000_dmg_16',
 'C000_dmg_17',
 'C000_dmg_18',
 'C000_dmg_19',
 'C000_dmg_20',
 'C000_dmg_21',
 'C000_dmg_22',
 'C000_dmg_23',
 'C000_dmg_24',
 'C000_dmg_25',
 'C000_dmg_26',
 'C000_dmg_27',
 'C000_dmg_28',
 'C000_dmg_29',
 'C000_dmg_30',
 'C000_dmg_31',
 'C000_dmg_32',
 'C000_dmg_33',
 'C000_dmg_34',
 'C000_dmg_35',
 'C000_dmg_mean_1',
 'C000_dmg_mean_2',
 'C000_dmg_mean_3',
 'C000_dmg_mean_4',
 'C000_dmg_mean_5',
 'C000_dmg_mean_6',
 'C000_dmg_mean_7',
 'C000_dmg_mean_8',
 'C000_dmg_mean_9',
 'C000_dmg_mean_10',
 'C000_dmg_mean_11',
 'C000_dmg_mean_12',
 'C000_dmg_mean_13',
 'C000_dmg_mean_14',
 'C000_dmg_mean_15',
 'C000_dmg_mean_16',
 'C000_dmg_mean_17',
 'C000_dmg_mean_18',
 'C000_dmg_mean_19',
 'C000_dmg_mean_20',
 'C000_dmg_mean_21',
 'C000_dmg_mean_22',
 'C000_dmg_mean_23',
 'C000_dmg_mean_24',
 'C000_dmg_mean_25',
 'C000_dmg_mean_26',
 'C000_dmg_mean_27',
 'C000_dmg_mean_28',
 'C000_dmg_mean_29',
 'C000_dmg_mean_30',
 'C000_dmg_mean_31',
 'C000_dmg_mean_32',
 'C000_dmg_mean_33',
 'C000_dmg_mean_34',
 'C000_dmg_mean_35']

In [778]:
prefix3 = 'C000_'
numbers = list(range(1, loop_ended+3+1))
columns_to_sum3 = [prefix3 + str(num) for num in numbers]    

combined_list = columns_to_sum+columns_to_sum2+columns_to_sum3


for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    Emp_home_select_2030_part2_new2_dic[i]= Emp_home_select_2030_part2_new2_dic[i].drop(combined_list, axis=1)

In [779]:
for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    Emp_home_select_2030_part2_new2_dic[i].rename(columns = {'C000_dmg_total':'C000_dmg'
                                                            }, inplace = True)

In [780]:
for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    Emp_home_select_2030_part2_new2_dic[i].rename(columns = {'C000_dmg_mean_total':'C000_dmg_mean'
                                                            }, inplace = True)

In [781]:
def Round_up(num):

    from decimal import localcontext, Decimal, ROUND_HALF_UP
    with localcontext() as ctx:
        ctx.rounding = ROUND_HALF_UP
        n = Decimal(num)
        nnnn = n.to_integral_value()
        int_number = int ( nnnn )
    return int_number

In [782]:
Emp_home_select_2030_part2_new2_dic[0].head()

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CD01,CD02,CD03,CD04,CS01,CS02,createdate,geometry,C000_dmg,C000_dmg_mean
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,0.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,0.0
1,12,021,010411,1000,120210104111000,Block 1000,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.69629 26.18436, -81.69546 26.184...",0.0,0.0
2,12,021,010408,1005,120210104081005,Block 1005,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,20231016,"POLYGON ((-81.73524 26.20540, -81.73522 26.205...",0.0,0.0
3,12,021,011208,1028,120210112081028,Block 1028,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,20231016,"POLYGON ((-81.44029 26.32594, -81.44019 26.326...",0.0,0.0
4,12,081,002003,1002,120810020031002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-82.50990 27.50864, -82.50986 27.508...",0.0,0.0

In [783]:
# Emp_home_select_2030_part1_new2_dic[1]['h_geocode_y']

In [784]:
Emp_home_select_2030_part2_new2['C000']

0        1.0
1        2.0
2        0.0
3        0.0
4        2.0
        ...
34218    1.0
34219    1.0
34220    0.0
34221    1.0
34222    9.0
Name: C000, Length: 34223, dtype: float64

In [785]:
len(Raster_file_paths)

120

In [786]:
Emp_home_select_2030_part2_new2_dic_sum= select_sum(Emp_home_select_2030_part2_new2_dic)

i= 0
i= 1
i= 2
i= 3
i= 4
i= 5
i= 6
i= 7
i= 8
i= 9
i= 10
i= 11
i= 12
i= 13
i= 14
i= 15
i= 16
i= 17
i= 18
i= 19
i= 20
i= 21
i= 22
i= 23
i= 24
i= 25
i= 26
i= 27
i= 28
i= 29
i= 30
i= 31
i= 32
i= 33
i= 34
i= 35
i= 36
i= 37
i= 38
i= 39
i= 40
i= 41
i= 42
i= 43
i= 44
i= 45
i= 46
i= 47
i= 48
i= 49
i= 50
i= 51
i= 52
i= 53
i= 54
i= 55
i= 56
i= 57
i= 58
i= 59
i= 60
i= 61
i= 62
i= 63
i= 64
i= 65
i= 66
i= 67
i= 68
i= 69
i= 70
i= 71
i= 72
i= 73
i= 74
i= 75
i= 76
i= 77
i= 78
i= 79
i= 80
i= 81
i= 82
i= 83
i= 84
i= 85
i= 86
i= 87
i= 88
i= 89
i= 90
i= 91
i= 92
i= 93
i= 94
i= 95
i= 96
i= 97
i= 98
i= 99
i= 100
i= 101
i= 102
i= 103
i= 104
i= 105
i= 106
i= 107
i= 108
i= 109
i= 110
i= 111
i= 112
i= 113
i= 114
i= 115
i= 116
i= 117
i= 118
i= 119

In [787]:
# Emp_home_select_2030_part2_new2_dic_sum[150]

In [788]:
# # # bucket_list= [['CNS01', 'CNS04', 'CNS12', 'CNS18', 'CNS15'], 10030107111003]
# # #bucket_out11 is the list of randomly selected minimum or maximum sectors ('CNS01', 'CNS04', 'CNS12', 'CNS18', 'CNS15')
# # #for each home zone (10030107111003) that will be used to fit C000_dmg to them 

# # #In this example ['CNS01', 'CNS04', 'CNS12', 'CNS15', 'CNS16', 'CNS18'] all have value of 1 after Round_up
# # # but C000_dmg is only 1 so to choose which sector will take that damage we randomly selected 5 sectors to opt out
# # # which are the bucket_out11 and the remaining sector 'CNS16' will take that damage


# Emp_home_select_2030_part2_new2_dic_sum2 = select_sum(Emp_home_select_2030_part2_new2_dic)

In [789]:
# Save_again = Emp_home_select_2030_new_values_merge_u_dic_sum[0][Emp_home_select_2030_new_values_merge_u_dic_sum[0]['C000_dmg']>0]

# Save_again.to_csv('Save_again.csv')

In [790]:
# Emp_home_select_2030_part2_new2_dic_sum2[0]

In [791]:
Emp_home_select_2030_part2_new2_dic_sum_result = prepare_sum(Emp_home_select_2030_part2_new2_dic_sum)

In [792]:

# Emp_home_select_2030_part2_new2_dic_sum_result[719]

In [793]:

# Emp_home_select_2030_part2_new2_dic_sum_result[719]

In [794]:
Emp_home_select_2030_new_values_final ={}
for i in range (0, len(Emp_home_select_2030_part2_new2_dic_sum_result)):
    Emp_home_select_2030_new_values_final[i] =Emp_home_select_2030_part2_new2_dic_sum_result[i]
    
#     Emp_home_select_2030_new_values_final[i]['C000_dmg_mean_2030'] = Emp_home_select_2030_new_values_final[i]['C000_dmg_mean_2030']
#     Emp_home_select_2030_new_values_final[i]['CA01_2030'] = (Emp_home_select_2030_new_values_final[i]['CA01_2030']/Emp_home_select_2030_new_values_final[i]['C000A_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CA02_2030'] = (Emp_home_select_2030_new_values_final[i]['CA02_2030']/Emp_home_select_2030_new_values_final[i]['C000A_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CA03_2030'] = (Emp_home_select_2030_new_values_final[i]['CA03_2030']/Emp_home_select_2030_new_values_final[i]['C000A_2030'])*100

#     Emp_home_select_2030_new_values_final[i]['CE01_2030'] = (Emp_home_select_2030_new_values_final[i]['CE01_2030']/Emp_home_select_2030_new_values_final[i]['C000E_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CE02_2030'] = (Emp_home_select_2030_new_values_final[i]['CE02_2030']/Emp_home_select_2030_new_values_final[i]['C000E_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CE03_2030'] = (Emp_home_select_2030_new_values_final[i]['CE03_2030']/Emp_home_select_2030_new_values_final[i]['C000E_2030'])*100

#     Emp_home_select_2030_new_values_final[i]['CR01_2030'] = (Emp_home_select_2030_new_values_final[i]['CR01_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR02_2030'] = (Emp_home_select_2030_new_values_final[i]['CR02_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR03_2030'] = (Emp_home_select_2030_new_values_final[i]['CR03_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR04_2030'] = (Emp_home_select_2030_new_values_final[i]['CR04_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR05_2030'] = (Emp_home_select_2030_new_values_final[i]['CR05_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR07_2030'] = (Emp_home_select_2030_new_values_final[i]['CR07_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100

#     Emp_home_select_2030_new_values_final[i]['CT01_2030'] = (Emp_home_select_2030_new_values_final[i]['CT01_2030']/Emp_home_select_2030_new_values_final[i]['C000T_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CT02_2030'] = (Emp_home_select_2030_new_values_final[i]['CT02_2030']/Emp_home_select_2030_new_values_final[i]['C000T_2030'])*100

#     Emp_home_select_2030_new_values_final[i]['CS01_2030'] = (Emp_home_select_2030_new_values_final[i]['CS01_2030']/Emp_home_select_2030_new_values_final[i]['C000S_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CS02_2030'] = (Emp_home_select_2030_new_values_final[i]['CS02_2030']/Emp_home_select_2030_new_values_final[i]['C000S_2030'])*100
   
#     Emp_home_select_2030_new_values_final[i]['CD01_2030'] = (Emp_home_select_2030_new_values_final[i]['CD01_2030']/Emp_home_select_2030_new_values_final[i]['C000D_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CD02_2030'] = (Emp_home_select_2030_new_values_final[i]['CD02_2030']/Emp_home_select_2030_new_values_final[i]['C000D_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CD03_2030'] = (Emp_home_select_2030_new_values_final[i]['CD03_2030']/Emp_home_select_2030_new_values_final[i]['C000D_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CD04_2030'] = (Emp_home_select_2030_new_values_final[i]['CD04_2030']/Emp_home_select_2030_new_values_final[i]['C000D_2030'])*100

In [795]:
for i in range (0, len(Emp_home_select_2030_new_values_final)):
    Emp_home_select_2030_new_values_final[i] = Emp_home_select_2030_new_values_final[i][[
        'C000','CA01','CA02','CA03','CE01','CE02','CE03', 'CNS01','CNS02','CNS03','CNS04','CNS05',
        'CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
        'CNS17','CNS18','CNS19','CNS20','CR01','CR02','CR03','CR04','CR05','CR07','CD01','CD02',
        'CD03','CD04','CT01','CT02','CS01','CS02','C000_dmg','C000_dmg_mean','C000_dmg_mean_2030',
        'CNS01_2030','CNS02_2030','CNS03_2030','CNS04_2030','CNS05_2030','CNS06_2030','CNS07_2030',
        'CNS08_2030','CNS09_2030','CNS10_2030','CNS11_2030','CNS12_2030','CNS13_2030','CNS14_2030',
        'CNS15_2030','CNS16_2030','CNS17_2030','CNS18_2030','CNS19_2030','CNS20_2030',
        'CA01_2030','CA02_2030','CA03_2030','CE01_2030','CE02_2030','CE03_2030','CR01_2030',
        'CR02_2030','CR03_2030','CR04_2030','CR05_2030','CR07_2030','CD01_2030','CD02_2030',
        'CD03_2030','CD04_2030','CT01_2030','CT02_2030','CS01_2030','CS02_2030','C000_2030',
        'C000A_2030','C000E_2030','C000R_2030','C000D_2030','C000T_2030','C000S_2030'

    ]]

In [796]:
len(Raster_file_paths)

120

In [797]:
len(Emp_home_select_2030_new_values_final)

120

In [798]:
final_save=[]
for i in range(0,len(Raster_file_paths)):
    temp_save = Emp_home_select_2030_new_values_final[i]
    final_save.append(temp_save)

In [799]:
pd.DataFrame(final_save)['C000_dmg']

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
        ...
115        0.0
116        0.0
117        0.0
118        0.0
119    36675.0
Name: C000_dmg, Length: 120, dtype: float64

In [800]:
year_1

2100

In [801]:
pd.DataFrame(final_save).T.to_csv('FL_{0}_new_values_final5_5_part2.csv'.format(year_1))

In [802]:
import pandas as pd
final_save_part2= pd.read_csv('FL_{0}_new_values_final5_5_part2.csv'.format(year_1))
final_save_part2

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,110,111,112,113,114,115,116,117,118,119
0,C000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0,0.0,...,0.0,38853.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40500.0
1,CA01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,...,0.0,5291.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5500.0
2,CA02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,...,0.0,22240.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23234.0
3,CA03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,...,0.0,11350.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11795.0
4,CE01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,5288.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5514.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,C000E_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,34454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36675.0
87,C000R_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,34454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36675.0
88,C000D_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,34458.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36680.0
89,C000T_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,34454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36675.0
90,C000S_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,0.0,34454.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36675.0

In [803]:
final_save_part1= pd.read_csv('FL_{0}_new_values_final5_5.csv'.format(year_1))
final_save_part1

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,110,111,112,113,114,115,116,117,118,119
0,C000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3178.0,0.0,...,0.0,72976.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,75599.0
1,CA01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,459.0,0.0,...,0.0,11085.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11476.0
2,CA02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1778.0,0.0,...,0.0,40550.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42070.0
3,CA03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,941.0,0.0,...,0.0,21373.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22086.0
4,CE01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,449.0,0.0,...,0.0,10962.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11328.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,C000E_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,267.0,0.0,...,0.0,62521.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65920.0
87,C000R_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,267.0,0.0,...,0.0,62521.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65920.0
88,C000D_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,268.0,0.0,...,0.0,62527.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65929.0
89,C000T_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,267.0,0.0,...,0.0,62521.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65920.0
90,C000S_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,267.0,0.0,...,0.0,62521.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65920.0

In [804]:
final_save_part1.set_index('Unnamed: 0', inplace=True)
final_save_part2.set_index('Unnamed: 0', inplace=True)

In [805]:
len(final_save_part1)

91

In [806]:
final_save_part1.iloc[43]

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
         ...
115          NaN
116          NaN
117          NaN
118          NaN
119    99.594519
Name: C000_dmg_mean_2030, Length: 120, dtype: float64

In [807]:
#don't use if it was fixed in future years

# final_save_part1.iloc[43] = final_save_part1.iloc[43]*2

# final_save_part1.iloc[43]

In [808]:
# final_save_part2.iloc[43]

In [809]:
# final_save_part2.iloc[83]

In [810]:
final_save_part2.iloc[10].unique()

array([   0.,    6.,   10.,  459.,  695., 1268.,  334.,  466., 1024.,
       1325., 1699., 3675., 3773., 4019., 4250., 4418.])

In [811]:
final_save = final_save_part1.copy()
for i in range(0,len(final_save_part1)):
    if i == 43:
        print('i=',i)
        final_save_part1.iloc[i] = final_save_part1.iloc[i].fillna(0)
        final_save_part2.iloc[i] = final_save_part2.iloc[i].fillna(0)
        

        final_save.iloc[i,:] = (final_save_part1.iloc[i,:]+final_save_part2.iloc[i,:])/2
        
        
        
    else: 
        final_save_part1.iloc[i] = final_save_part1.iloc[i].fillna(0)
        final_save_part2.iloc[i] = final_save_part2.iloc[i].fillna(0)

        final_save.iloc[i,:] = final_save_part1.iloc[i,:]+final_save_part2.iloc[i,:]

i= 43

In [812]:
final_save.iloc[43]

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
          ...
115      0.000000
116      0.000000
117      0.000000
118      0.000000
119    100.642053
Name: C000_dmg_mean_2030, Length: 120, dtype: float64

In [813]:
final_save_part1.iloc[10]

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
115       0.0
116       0.0
117       0.0
118       0.0
119    8155.0
Name: CNS04, Length: 120, dtype: float64

In [814]:
final_save_part2.iloc[10]

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
115       0.0
116       0.0
117       0.0
118       0.0
119    4418.0
Name: CNS04, Length: 120, dtype: float64

In [815]:
final_save.iloc[10]

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
        ...
115        0.0
116        0.0
117        0.0
118        0.0
119    12573.0
Name: CNS04, Length: 120, dtype: float64

In [816]:
final_save

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
C000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3224.0,0.0,0.0,...,0.0,111829.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,116099.0
CA01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,480.0,0.0,0.0,...,0.0,16376.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16976.0
CA02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1793.0,0.0,0.0,...,0.0,62790.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65304.0
CA03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,951.0,0.0,0.0,...,0.0,32723.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33881.0
CE01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,456.0,0.0,0.0,...,0.0,16250.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16842.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C000E_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273.0,0.0,0.0,...,0.0,96975.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102595.0
C000R_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273.0,0.0,0.0,...,0.0,96975.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102595.0
C000D_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,274.0,0.0,0.0,...,0.0,96985.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102609.0
C000T_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273.0,0.0,0.0,...,0.0,96975.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102595.0
C000S_2030,0.0,0.0,0.0,0.0,0.0,0.0,0.0,273.0,0.0,0.0,...,0.0,96975.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,102595.0

In [817]:
year_1

2100

In [818]:
final_save.to_csv('final_save_{0}.csv'.format(year_1))