In [1]:
year_1=2090

In [2]:
import pandas as pd
Emp_home_select_2030_part2_new2 = pd.read_pickle('Emp_home_select_{0}_part2_new2.pickle'.format(year_1))

In [3]:


Emp_home_select_2030_part2_new2['geometry'] = Emp_home_select_2030_part2_new2['geometry'].to_crs('epsg:4326')

In [4]:
Emp_home_select_2030_part2_new2 = Emp_home_select_2030_part2_new2.astype({"h_geocode":'int64'})

In [5]:
Emp_home_select_2030_part2_new2['C000'].sum()

55257.0

In [6]:
Emp_home_select_2030_new_values =  Emp_home_select_2030_part2_new2[Emp_home_select_2030_part2_new2['C000'] > 0]
len(Emp_home_select_2030_new_values)

14897

In [7]:
Emp_cells_2030_old = pd.read_pickle('bldgs_RES_remain_{0}.pickle'.format(year_1-10))

In [8]:
Emp_cells = Emp_cells_2030_old

In [9]:
Emp_cells =  Emp_cells.dropna(subset=['cell'])
len(Emp_cells)

386384

In [10]:
Emp_cells =  Emp_cells.dropna(subset=['h_geocode'])
len(Emp_cells)

386384

In [11]:
Emp_cells = Emp_cells.astype({"cell":'int64',"fd_id":'int64',"h_geocode":'int64'})

In [12]:
Emp_cells = Emp_cells.drop_duplicates(subset=['fd_id'])
len(Emp_cells)

386384

In [13]:
Emp_cells_ = Emp_cells.select_dtypes(exclude=['geometry','object'])

In [14]:
Emp_cells_sum = Emp_cells_.groupby(["h_geocode"], as_index=False).sum()
Emp_cells_sum

,h_geocode,fid,fd_id,num_story,sqft,found_ht,med_yr_blt,val_struct,val_cont,val_vehic,...,pop2amo65,pop2pmu65,pop2pmo65,o65disable,u65disable,x,y,grnd_elv_m,ground_elv,cell
0,120150101001000,8054380.0,4425817035,9.0,11811.000,13.5,17892,1.185217e+06,5.926086e+05,243000.0,...,1,1,1,1.62,0.72,-735.239518,242.828809,139.862380,458.866091,9
1,120150101001005,9757172.0,4918383615,10.0,7013.172,15.0,19880,9.480002e+05,4.740001e+05,270000.0,...,4,7,4,1.80,0.80,-816.830538,269.608335,174.225683,571.606591,10
2,120150101001008,793994.0,491656353,1.0,1326.000,0.5,1988,1.289394e+05,6.446971e+04,27000.0,...,0,0,0,0.18,0.08,-81.702815,27.026356,14.668072,48.123597,1
3,120150101001009,51944699.0,30976282669,63.0,172142.000,71.0,125244,1.413285e+07,7.066425e+06,1701000.0,...,18,23,18,11.34,5.04,-5158.930288,1700.195751,483.715984,1586.994749,63
4,120150101001010,16173685.0,9833426779,20.0,51581.000,13.0,39760,4.606934e+06,2.303467e+06,540000.0,...,7,9,7,3.60,1.60,-1638.340688,539.979517,138.793900,455.360580,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22063,121150027481010,14346167.0,3450388481,7.0,13258.000,3.5,14028,1.488367e+06,7.441835e+05,189000.0,...,2,5,2,1.19,0.35,-574.859939,189.559891,61.200643,200.789516,7
22064,121150027481011,6168832.0,1478757675,3.0,5261.000,1.5,6012,5.884929e+05,2.942465e+05,81000.0,...,1,2,1,0.51,0.15,-246.429690,81.252528,26.698642,87.593972,3
22065,121150027482002,12323164.0,2957502259,6.0,10727.000,3.0,12024,1.192809e+06,5.964047e+05,162000.0,...,4,5,4,1.02,0.30,-492.851425,162.474747,49.971078,163.947111,6
22066,121150027482003,10294134.0,2464608641,5.0,8561.000,2.5,10020,8.456077e+05,4.228038e+05,135000.0,...,2,4,2,0.85,0.25,-410.709463,135.390427,40.981065,134.452317,5
22067,121150027483006,7113247.0,988841711,2.0,3212.000,1.0,4008,3.217641e+05,1.608821e+05,54000.0,...,0,2,0,0.34,0.10,-164.295440,54.161031,16.902210,55.453447,2

In [15]:
Emp_cells_sum = Emp_cells_sum[['h_geocode','cell']]
Emp_cells_sum

             h_geocode  cell
0      120150101001000     9
1      120150101001005    10
2      120150101001008     1
3      120150101001009    63
4      120150101001010    20
...                ...   ...
22063  121150027481010     7
22064  121150027481011     3
22065  121150027482002     6
22066  121150027482003     5
22067  121150027483006     2

[22068 rows x 2 columns]

In [16]:
Emp_cells_sum = Emp_cells_sum.astype({"h_geocode":'int64'})
# Emp_cells_sum = Emp_cells_sum [['h_geocode','cell']]

In [17]:
import pandas as pd

Emp_home_select_2030_new_values_merge = pd.merge(Emp_home_select_2030_new_values, Emp_cells_sum,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

In [18]:
Emp_work = pd.read_pickle('Emp_work.pickle')

In [19]:
Emp_work['w_geocode']

9        120210113042009
15       120210001021033
16       120210112062003
17       120210111141006
58       121150006012024
              ...
43986    120210108012000
43987    120210103003013
43989    120210102082001
43990    120210105112010
43991    120210104371010
Name: w_geocode, Length: 15195, dtype: object

In [20]:
OD_main= pd.read_pickle("/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/OD_main.pkl")

In [21]:
OD_main

               w_geocode        h_geocode
0        120010002011000  120010006003047
1        120010002011000  120010012025015
2        120010002011000  120010017022003
3        120010002011000  120010019072015
4        120010002011000  120010022181001
...                  ...              ...
7645809  121339703032101  121339703032084
7645810  121339703032101  121339703032092
7645811  121339703032101  121339703032096
7645812  121339703032142  120632101001066
7645813  121339703032142  121339701032003

[7645814 rows x 2 columns]

In [22]:


OD_main = OD_main.astype({"h_geocode":'int64',"w_geocode":'int64' })

In [23]:
len(Emp_home_select_2030_new_values_merge)

14897

In [24]:
Emp_home_select_2030_new_values_merge

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CT02,CD01,CD02,CD03,CD04,CS01,CS02,createdate,geometry,cell
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",NaN
1,12,021,010411,1000,120210104111000,Block 1000,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,20231016,"POLYGON ((-81.69629 26.18436, -81.69546 26.184...",338.0
2,12,021,010408,1005,120210104081005,Block 1005,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,20231016,"POLYGON ((-81.73524 26.20540, -81.73522 26.205...",92.0
3,12,081,002003,1002,120810020031002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,2.0,1.0,2.0,2.0,20231016,"POLYGON ((-82.50990 27.50864, -82.50986 27.508...",46.0
4,12,081,001904,2006,120810019042006,Block 2006,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,1.0,2.0,1.0,20231016,"POLYGON ((-82.52838 27.51722, -82.52836 27.518...",178.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14892,12,081,001502,3039,120810015023039,Block 3039,G5040,NaN,NaN,NaN,...,1.0,2.0,2.0,2.0,2.0,3.0,5.0,20231016,"POLYGON ((-82.55902 27.51934, -82.55849 27.519...",NaN
14893,12,081,001914,2082,120810019142082,Block 2082,G5040,NaN,NaN,NaN,...,1.0,1.0,4.0,6.0,4.0,9.0,6.0,20231016,"POLYGON ((-82.36136 27.55343, -82.36129 27.553...",4.0
14894,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,3.0,0.0,8.0,2.0,1.0,6.0,5.0,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",NaN
14895,12,081,001802,1021,120810018021021,Block 1021,G5040,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,20231016,"POLYGON ((-82.72426 27.51747, -82.72346 27.518...",2.0
14896,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,1.0,1.0,4.0,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0

In [25]:
Emp_home_select_2030_new_values_merge['cell'] = Emp_home_select_2030_new_values_merge['cell'].fillna(0)

In [26]:
Emp_home_select_2030_new_values_merge['C000'].unique()

array([ 2.,  1.,  4.,  3., 12.,  8.,  9.,  6., 15., 45., 14., 10.,  7.,
        5., 26., 11., 18., 20., 13., 22., 19., 16., 17., 32., 21., 23.,
       38., 33., 44., 41., 24., 42., 43., 46., 37., 28., 29., 34., 25.,
       49., 48., 39., 27., 30., 60., 35., 36., 59., 47., 31., 61., 51.,
       53., 62.])

In [27]:
# number of projected employees are more than number of cells

Emp_home_select_2030_new_values_merge_s = Emp_home_select_2030_new_values_merge[Emp_home_select_2030_new_values_merge['C000']- Emp_home_select_2030_new_values_merge['cell'] > 0]


len(Emp_home_select_2030_new_values_merge_s)

7362

In [28]:
Emp_home_select_2030_new_values_merge_s['C000'].sum()

37155.0

In [29]:
Emp_home_select_2030_new_values_merge_s_dup = Emp_home_select_2030_new_values_merge_s.drop_duplicates(subset=['h_geocode'])
Emp_home_select_2030_new_values_merge_s_dup['h_geocode']

0        120710012051002
5        120879718001022
7        121150023023000
11       120210112043005
13       120879717003014
              ...
14891    120810020183029
14892    120810015023039
14893    120810019142082
14894    120810007043047
14896    120810020102028
Name: h_geocode, Length: 7362, dtype: int64

In [30]:
Emp_home_select_2030_new_values_merge_s['h_geocode']

0        120710012051002
5        120879718001022
7        121150023023000
11       120210112043005
13       120879717003014
              ...
14891    120810020183029
14892    120810015023039
14893    120810019142082
14894    120810007043047
14896    120810020102028
Name: h_geocode, Length: 7362, dtype: int64

In [31]:
Emp_home_select_2030_new_values_merge_s['C000']

0         2.0
5         3.0
7         1.0
11       12.0
13        1.0
         ...
14891     2.0
14892     8.0
14893    15.0
14894    11.0
14896     8.0
Name: C000, Length: 7362, dtype: float64

In [32]:
Emp_home_select_2030_new_values_merge_s['cell']

0        0.0
5        0.0
7        0.0
11       0.0
13       0.0
        ...
14891    0.0
14892    0.0
14893    4.0
14894    0.0
14896    6.0
Name: cell, Length: 7362, dtype: float64

In [33]:
Emp_home_select_2030_new_values_merge_home_work = pd.merge(Emp_home_select_2030_new_values_merge_s, OD_main,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

In [34]:
Emp_home_select_2030_new_values_merge_home_work['h_geocode']

0         120710012051002
1         120710012051002
2         120710012051002
3         120710012051002
4         120710012051002
               ...
116264    120810020102028
116265    120810020102028
116266    120810020102028
116267    120810020102028
116268    120810020102028
Name: h_geocode, Length: 116269, dtype: int64

In [35]:
Emp_work_geo = Emp_work[['w_geocode','geometry']]

In [36]:
# To drop Null values in h_geocode
Emp_work_geo_select = []

Emp_work_geo_select = Emp_work_geo.dropna(subset=['w_geocode'])
Emp_work_geo_select

             w_geocode                                           geometry
9      120210113042009  POLYGON ((-81.43523 26.42843, -81.43424 26.428...
15     120210001021033  POLYGON ((-81.79587 26.14958, -81.79449 26.149...
16     120210112062003  POLYGON ((-81.54530 26.28530, -81.53442 26.285...
17     120210111141006  POLYGON ((-81.58065 26.12690, -81.58065 26.127...
58     121150006012024  POLYGON ((-82.53674 27.30010, -82.53671 27.300...
...                ...                                                ...
43986  120210108012000  POLYGON ((-81.72085 26.09891, -81.72050 26.099...
43987  120210103003013  POLYGON ((-81.79861 26.19522, -81.79598 26.195...
43989  120210102082001  POLYGON ((-81.80221 26.23201, -81.80210 26.232...
43990  120210105112010  POLYGON ((-81.69014 26.15579, -81.68997 26.155...
43991  120210104371010  POLYGON ((-81.76449 26.26234, -81.76422 26.262...

[15195 rows x 2 columns]

In [37]:
Emp_work_geo_select = Emp_work_geo_select.astype({"w_geocode":'int64'})

In [38]:
# Emp_work_geo_select.to_pickle("Emp_work_geo_select.pkl")

In [39]:
Emp_home_select_2030_new_values_home_work2 = pd.merge(Emp_home_select_2030_new_values_merge_home_work, Emp_work_geo_select,  how='left', 
                left_on=['w_geocode'], right_on = ['w_geocode'])

In [40]:
Emp_home_select_2030_new_values_home_work2['geometry_y'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [41]:

Emp_home_select_2030_new_values_home_work2['geometry_y'] = Emp_home_select_2030_new_values_home_work2['geometry_y'].to_crs('epsg:4326')

In [42]:
len(Emp_home_select_2030_new_values_home_work2)

117218

In [43]:
Emp_home_select_2030_new_values_home_work2['geometry_y'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [44]:
#The following home zone doesn't have work zone in AL State, so we will find the closest available zone using (find_cells) 

Emp_home_select_2030_new_values_home_work2[Emp_home_select_2030_new_values_home_work2['GEOID20']== '010030107032226']

Empty GeoDataFrame
Columns: [STATEFP20, COUNTYFP20, TRACTCE20, BLOCKCE20, GEOID20, NAME20, MTFCC20, UR20, UACE20, UATYPE20, FUNCSTAT20, ALAND20, AWATER20, INTPTLAT20, INTPTLON20, h_geocode, C000, CA01, CA02, CA03, CE01, CE02, CE03, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, CR01, CR02, CR03, CR04, CR05, CR07, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, createdate, geometry_x, cell, w_geocode, geometry_y]
Index: []

[0 rows x 62 columns]

In [45]:
# To drop Null values in h_geocode
#geometry_x for h_geocode #geometry_y for w_geocode

Emp_home_select_2030_new_values_home_work3 = []

Emp_home_select_2030_new_values_home_work3 = Emp_home_select_2030_new_values_home_work2.dropna(subset=['geometry_y'])
Emp_home_select_2030_new_values_home_work3

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CD02,CD03,CD04,CS01,CS02,createdate,geometry_x,cell,w_geocode,geometry_y
23,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.01216 26.91745, -82.01002 26.917..."
24,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.00568 26.92149, -82.00567 26.922..."
25,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810..."
26,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810..."
27,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201502e+14,"POLYGON ((-82.00338 27.01668, -82.00338 27.017..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117212,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,1.0,4.0,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.46366 27.38394, -82.46365 27.384..."
117213,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,1.0,4.0,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.46410 27.35960, -82.46408 27.359..."
117214,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,1.0,4.0,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.45138 27.32471, -82.45138 27.324..."
117215,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,1.0,4.0,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.54382 27.27843, -82.54381 27.278..."
117216,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,1.0,4.0,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.43180 27.36554, -82.43180 27.365..."

In [46]:
Emp_home_select_2030_new_values_home_work3= Emp_home_select_2030_new_values_home_work3.reset_index()
Emp_home_select_2030_new_values_home_work3=Emp_home_select_2030_new_values_home_work3.drop(['index'],axis=1)

In [47]:
Emp_home_select_2030_new_values_home_work3['centr_x'] = ''
Emp_home_select_2030_new_values_home_work3['centr_y'] = ''

# Emp_home_select_2030_new_values_home_work3.columns.get_loc("centr_x")]   #this works with .iloc

for n in range(0,len(Emp_home_select_2030_new_values_home_work3)):
    Emp_home_select_2030_new_values_home_work3.loc[n,"centr_x"]\
    = Emp_home_select_2030_new_values_home_work3.loc[n,"geometry_x"].centroid.wkt
    
    Emp_home_select_2030_new_values_home_work3.loc[n,"centr_y"]\
    = Emp_home_select_2030_new_values_home_work3.loc[n,"geometry_y"].centroid.wkt

In [48]:
Emp_home_select_2030_new_values_home_work3

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CD04,CS01,CS02,createdate,geometry_x,cell,w_geocode,geometry_y,centr_x,centr_y
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.01216 26.91745, -82.01002 26.917...",POINT (-81.83670946952485 26.60879448950761),POINT (-82.00393932791506 26.906692300176676)
1,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.00568 26.92149, -82.00567 26.922...",POINT (-81.83670946952485 26.60879448950761),POINT (-82.00371617488155 26.919173431524626)
2,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810...",POINT (-81.83670946952485 26.60879448950761),POINT (-81.92500197920806 26.788264429264913)
3,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810...",POINT (-81.83670946952485 26.60879448950761),POINT (-81.92500197920806 26.788264429264913)
4,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201502e+14,"POLYGON ((-82.00338 27.01668, -82.00338 27.017...",POINT (-81.83670946952485 26.60879448950761),POINT (-82.00091384765571 27.015878602423022)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84536,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.46366 27.38394, -82.46365 27.384...",POINT (-82.09801803749535 27.25923835532114),POINT (-82.45976788288165 27.384769503511873)
84537,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.46410 27.35960, -82.46408 27.359...",POINT (-82.09801803749535 27.25923835532114),POINT (-82.45951590142182 27.360822447704876)
84538,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.45138 27.32471, -82.45138 27.324...",POINT (-82.09801803749535 27.25923835532114),POINT (-82.45073429345088 27.32422453634444)
84539,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.54382 27.27843, -82.54381 27.278...",POINT (-82.09801803749535 27.25923835532114),POINT (-82.5371374888324 27.282827163678583)
84540,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.43180 27.36554, -82.43180 27.365...",POINT (-82.09801803749535 27.25923835532114),POINT (-82.42250755803403 27.374379996634605)

In [49]:
from shapely import wkt
import geopandas as gpd

Emp_home_select_2030_new_values_home_work3['centr_x'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_home_work3['centr_x'])
Emp_home_select_2030_new_values_home_work3['centr_y'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_home_work3['centr_y'])

Emp_home_select_2030_new_values_home_work3 = gpd.GeoDataFrame(Emp_home_select_2030_new_values_home_work3, geometry='centr_x')
Emp_home_select_2030_new_values_home_work3 = gpd.GeoDataFrame(Emp_home_select_2030_new_values_home_work3, geometry='centr_y')

Emp_home_select_2030_new_values_home_work3

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CD04,CS01,CS02,createdate,geometry_x,cell,w_geocode,geometry_y,centr_x,centr_y
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.01216 26.91745, -82.01002 26.917...",POINT (-81.83671 26.60879),POINT (-82.00394 26.90669)
1,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-82.00568 26.92149, -82.00567 26.922...",POINT (-81.83671 26.60879),POINT (-82.00372 26.91917)
2,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810...",POINT (-81.83671 26.60879),POINT (-81.92500 26.78826)
3,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201501e+14,"POLYGON ((-81.95546 26.81051, -81.95464 26.810...",POINT (-81.83671 26.60879),POINT (-81.92500 26.78826)
4,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.201502e+14,"POLYGON ((-82.00338 27.01668, -82.00338 27.017...",POINT (-81.83671 26.60879),POINT (-82.00091 27.01588)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84536,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.46366 27.38394, -82.46365 27.384...",POINT (-82.09802 27.25924),POINT (-82.45977 27.38477)
84537,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.46410 27.35960, -82.46408 27.359...",POINT (-82.09802 27.25924),POINT (-82.45952 27.36082)
84538,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.45138 27.32471, -82.45138 27.324...",POINT (-82.09802 27.25924),POINT (-82.45073 27.32422)
84539,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.54382 27.27843, -82.54381 27.278...",POINT (-82.09802 27.25924),POINT (-82.53714 27.28283)
84540,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,2.0,6.0,2.0,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.211500e+14,"POLYGON ((-82.43180 27.36554, -82.43180 27.365...",POINT (-82.09802 27.25924),POINT (-82.42251 27.37438)

In [50]:
from shapely.ops import transform

# Emp_home_select_2030_new_values_home_work3.columns.get_loc("centr_x") #this works with .iloc

for n in range(0,len(Emp_home_select_2030_new_values_home_work3)):
    Emp_home_select_2030_new_values_home_work3.loc[n, "centr_x"] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_home_work3.loc[n, "centr_x"])
#    
    Emp_home_select_2030_new_values_home_work3.loc[n, "centr_y"] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_home_work3.loc[n, "centr_y"])

In [51]:

coord_list_x =  Emp_home_select_2030_new_values_home_work3['centr_x'].geometry.apply(lambda p: list(p.coords)[0])

coord_list_y =  Emp_home_select_2030_new_values_home_work3['centr_y'].geometry.apply(lambda p: list(p.coords)[0])


# rc = dataset_ex[column_name].apply(lambda x: pd.Series(x, dtype="object"))


Emp_home_select_2030_new_values_home_work3['centr_x_co'] = coord_list_x

Emp_home_select_2030_new_values_home_work3['centr_y_co'] = coord_list_y

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

In [52]:
from geopy.distance import geodesic as GD  

Emp_home_select_2030_new_values_home_work3['dist'] = ''

# Emp_home_select_2030_new_values_home_work3.columns.get_loc("dist") #this works with .iloc

for n in range(0,len(Emp_home_select_2030_new_values_home_work3)):
#     print('n=',n)
    Emp_home_select_2030_new_values_home_work3.loc[n,"dist"]\
    = GD(Emp_home_select_2030_new_values_home_work3.loc[n,"centr_x_co"],Emp_home_select_2030_new_values_home_work3.loc[n,"centr_y_co"]).km

In [53]:
#Remove those zones that w_geocode is the same as h_geocode (zones people live and work in the same one)

Emp_home_select_2030_new_values_home_work3___ = Emp_home_select_2030_new_values_home_work3[Emp_home_select_2030_new_values_home_work3['w_geocode']!=Emp_home_select_2030_new_values_home_work3['h_geocode']]


len(Emp_home_select_2030_new_values_home_work3___)

84419

In [54]:
Emp_home_select_2030_new_values_home_work3_ = Emp_home_select_2030_new_values_home_work3___.select_dtypes(exclude=['geometry'])

In [55]:
len(Emp_home_select_2030_new_values_home_work3_)

84419

In [56]:
len(Emp_home_select_2030_new_values_home_work3_['h_geocode'].unique())

7185

In [57]:
Emp_home_select_2030_new_values_home_work3_final =\
    Emp_home_select_2030_new_values_home_work3.loc[Emp_home_select_2030_new_values_home_work3_.groupby(['h_geocode'])['dist'].idxmin()].sort_index()

In [58]:
len(Emp_home_select_2030_new_values_home_work3_final)

7185

In [59]:
Emp_home_select_2030_new_values_home_work3_final

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,createdate,geometry_x,cell,w_geocode,geometry_y,centr_x,centr_y,centr_x_co,centr_y_co,dist
82,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,1.207100e+14,"POLYGON ((-81.83893 26.60236, -81.83888 26.602...",POINT (26.60879 -81.83671),POINT (26.60195 -81.83745),"(26.60879448950761, -81.83670946952485)","(26.60195360533018, -81.83745360718054)",0.761567
355,12,087,971800,1022,120879718001022,Block 1022,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",POINT (24.56733 -81.73019),POINT (24.57052 -81.73536),"(24.567331297140306, -81.73018543710354)","(24.570518191572866, -81.73536038670079)",0.631994
472,12,115,002302,3000,121150023023000,Block 3000,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.43367 27.11708, -82.43367 27.117...",0.0,1.211500e+14,"POLYGON ((-82.42052 27.10943, -82.42051 27.109...",POINT (27.11349 -82.42622),POINT (27.10871 -82.41868),"(27.11349255516845, -82.42621758713184)","(27.108710051714546, -82.41867619011576)",0.916516
571,12,021,011204,3005,120210112043005,Block 3005,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-81.42547 26.41482, -81.42466 26.414...",0.0,1.202101e+14,"POLYGON ((-81.41836 26.41846, -81.41740 26.418...",POINT (26.41290 -81.42360),POINT (26.41759 -81.41786),"(26.41290162493938, -81.42359538452847)","(26.41759257720198, -81.417863363065)",0.77274
647,12,087,971700,3014,120879717003014,Block 3014,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-81.67570 24.60202, -81.67570 24.602...",0.0,1.208797e+14,"POLYGON ((-81.66069 24.60108, -81.66053 24.601...",POINT (24.59994 -81.66875),POINT (24.59892 -81.65765),"(24.599937349116697, -81.66874555206641)","(24.59892101661512, -81.65765004619693)",1.129322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84491,12,081,002018,3029,120810020183029,Block 3029,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.42543 27.48683, -82.42515 27.486...",0.0,1.208100e+14,"POLYGON ((-82.45919 27.44140, -82.45919 27.442...",POINT (27.48524 -82.42345),POINT (27.44915 -82.45439),"(27.48523508150931, -82.42345191216556)","(27.44914815856054, -82.45438614070632)",5.033827
84499,12,081,001502,3039,120810015023039,Block 3039,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.55902 27.51934, -82.55849 27.519...",0.0,1.208100e+14,"POLYGON ((-82.56244 27.52125, -82.56139 27.524...",POINT (27.51857 -82.55875),POINT (27.52317 -82.55625),"(27.518572133283566, -82.55874980382144)","(27.523171713919925, -82.55625207125853)",0.566279
84507,12,081,001914,2082,120810019142082,Block 2082,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.36136 27.55343, -82.36129 27.553...",4.0,1.208100e+14,"POLYGON ((-82.36456 27.56590, -82.36438 27.566...",POINT (27.55162 -82.35746),POINT (27.56211 -82.30733),"(27.551618395711092, -82.35745569012428)","(27.56211304452596, -82.30732997745707)",5.085242
84513,12,081,000704,3047,120810007043047,Block 3047,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...",0.0,1.208100e+14,"POLYGON ((-82.56678 27.47713, -82.56306 27.477...",POINT (27.49049 -82.53898),POINT (27.47570 -82.56439),"(27.490487410652122, -82.53898111624851)","(27.47569707264196, -82.56439020787943)",2.99863
84529,12,081,002010,2028,120810020102028,Block 2028,G5040,NaN,NaN,NaN,...,20231016,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...",6.0,1.208100e+14,"POLYGON ((-82.14689 27.34123, -82.14686 27.341...",POINT (27.25924 -82.09802),POINT (27.33388 -82.10382),"(27.25923835532114, -82.09801803749535)","(27.33387966816501, -82.10382416391673)",8.290817

In [60]:
len(Emp_home_select_2030_new_values_home_work3_final['dist'].unique())

7182

In [61]:
df1_dup= pd.DataFrame(Emp_home_select_2030_new_values_home_work3_final.pivot_table(index=['dist'], aggfunc='size'), columns=['size'])

df1_dup[df1_dup['size']>1]

          size
dist
0.575836     2
0.591535     2
0.673161     2

In [62]:
Emp_home_select_2030_new_values_home_work3_final_missing = Emp_home_select_2030_new_values_home_work2.loc[~Emp_home_select_2030_new_values_home_work2['GEOID20'].isin(Emp_home_select_2030_new_values_home_work3_final['GEOID20'])]
len(Emp_home_select_2030_new_values_home_work3_final_missing)

255

In [63]:
len(Emp_home_select_2030_new_values_home_work3_final)

7185

In [64]:
import pandas as pd 
Emp_home_select_2030_new_values_home_work3_final_=pd.concat([Emp_home_select_2030_new_values_home_work3_final, Emp_home_select_2030_new_values_home_work3_final_missing], axis=0)
len(Emp_home_select_2030_new_values_home_work3_final_)

7440

In [65]:
Emp_home_select_2030_new_values_home_work3_final['C000'].sum()

36292.0

In [66]:
Emp_home_select_2030_new_values_home_work3_final_['C000'].sum()

37641.0

In [67]:
Emp_home_select_2030_new_values_home_work3_final_['C000']

82         2.0
355        3.0
472        1.0
571       12.0
647        1.0
          ...
116326     1.0
116426    10.0
116973     1.0
116982    11.0
117027    20.0
Name: C000, Length: 7440, dtype: float64

In [68]:
Emp_home_select_2030_new_values_home_work3_final_['C000'].sum()

37641.0

In [69]:
select = Emp_home_select_2030_new_values_home_work3_final_

In [70]:
 #geometry_x for h_geocode #geometry_y for w_geocode
select= select[['h_geocode','geometry_x','C000','CA01','CA02','CA03','CR01','CR02','CR03','CR04','CR05','CR07','CE01',
                'CE02','CE03','CT01','CT02','CD01','CD02','CD03','CD04','CS01','CS02','CNS01','CNS02','CNS03','CNS04',
                'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                'CNS17','CNS18','CNS19','CNS20','cell','w_geocode','geometry_y','dist']]

In [71]:
len(select)

7440

In [72]:
select_min_select2 = select

In [73]:
# h_geocode_x is h_geocode associated with each w_geocode
# h_geocode_y is original h_geocode (projected employees)
#geometry_x for h_geocode_y #geometry_y for w_geocode



select_min_OD = pd.merge(OD_main, select_min_select2,  how='right', 
                left_on=['w_geocode'], right_on = ['w_geocode'])

In [74]:
len(select_min_OD)

4195418

In [75]:
select_hgeocode = pd.merge(select_min_OD, Emp_cells_sum,  how='left', 
                left_on=['h_geocode_x'], right_on = ['h_geocode'])

In [76]:
len(select_hgeocode)

4195418

In [77]:
#cell_y for h_geocode_x (associate with each w_geocode)
select_hgeocode =  select_hgeocode.dropna(subset=['cell_y'])
len(select_hgeocode)

2339870

In [78]:
# select_hgeocode = select_hgeocode.drop(['row_num'], axis = 1)
select_hgeocode = select_hgeocode.astype({"h_geocode":'int64'})

In [79]:
# Emp_home_geo = Emp_home_select[['geometry','h_geocode']]
# Emp_home_geo= Emp_home_geo.astype ({"h_geocode":'int64'})

In [80]:
# Emp_home_geo.to_pickle("Emp_home_geo.pkl")

In [81]:
Emp_home_geo= pd.read_pickle('Emp_home_geo.pkl')

In [82]:
len(Emp_home_geo)

34223

In [83]:
Emp_home_geo

                                                 geometry        h_geocode
54      POLYGON ((-81.70222 26.25009, -81.70186 26.250...  120210104352008
55      POLYGON ((-81.71808 26.24722, -81.71795 26.247...  120210104351004
56      POLYGON ((-81.79335 26.17518, -81.79232 26.175...  120210002001025
57      POLYGON ((-81.43775 26.42658, -81.43746 26.426...  120210113042013
58      POLYGON ((-81.43369 26.42571, -81.43158 26.425...  120210114002005
...                                                   ...              ...
143190  POLYGON ((-82.48703 27.56261, -82.48697 27.562...  120810019081011
143191  POLYGON ((-82.57396 27.45439, -82.57092 27.454...  120810002014001
143192  POLYGON ((-82.57562 27.52858, -82.57510 27.528...  120810014051003
143311  POLYGON ((-82.12026 27.26250, -82.11883 27.265...  120810020102028
143312  POLYGON ((-82.11041 27.46021, -82.10932 27.460...  120810019142045

[34223 rows x 2 columns]

In [84]:
select_hgeocode['geometry_x1'] = select_hgeocode['geometry_x']
select_hgeocode['geometry_y1'] = select_hgeocode['geometry_y']

In [85]:
select_hgeocode = select_hgeocode.drop(['geometry_x','geometry_y'], axis = 1)

In [86]:
# h_geocode_x is h_geocode associated with each w_geocode
# h_geocode_y is original h_geocode (projected employees)
#geometry_x1 for h_geocode_y        #geometry for h_geocode_x       #geometry_y1 for w_geocode
#cell_x for h_geocode_y #cell_y for h_geocode_x


select_hgeocode_geo = pd.merge(select_hgeocode, Emp_home_geo,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

select_hgeocode_geo

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS18,CNS19,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry
0,1.207100e+14,1.207104e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.761567,120710401171000,437.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553..."
1,1.207100e+14,1.207104e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.761567,120710401174006,1.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.81464 26.55431, -81.81258 26.554..."
2,1.207100e+14,1.207105e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.761567,120710503122003,31.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.75083 26.37834, -81.75082 26.378..."
3,1.208797e+14,1.208797e+14,120879718001022,3.0,0.0,2.0,1.0,2.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.631994,120879713001011,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.10946 24.70668, -81.10944 24.706..."
4,1.208797e+14,1.208797e+14,120879718001022,3.0,0.0,2.0,1.0,2.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.631994,120879722004008,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.77761 24.55928, -81.77736 24.559..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2339865,1.209502e+14,1.211500e+14,120150105052037,20.0,0.0,20.0,0.0,20.0,0.0,0.0,...,2.0,0.0,0.0,1.0,NaN,121150014043008,35.0,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",None,"POLYGON ((-82.42951 27.31204, -82.42949 27.312..."
2339866,1.209502e+14,1.211500e+14,120150105052037,20.0,0.0,20.0,0.0,20.0,0.0,0.0,...,2.0,0.0,0.0,1.0,NaN,121150019052006,16.0,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",None,"POLYGON ((-82.54661 27.26325, -82.54657 27.263..."
2339867,1.209502e+14,1.211500e+14,120150105052037,20.0,0.0,20.0,0.0,20.0,0.0,0.0,...,2.0,0.0,0.0,1.0,NaN,121150019092007,94.0,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",None,"POLYGON ((-82.54106 27.25625, -82.54049 27.256..."
2339868,1.209502e+14,1.211500e+14,120150105052037,20.0,0.0,20.0,0.0,20.0,0.0,0.0,...,2.0,0.0,0.0,1.0,NaN,121150020112011,53.0,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",None,"POLYGON ((-82.52377 27.25148, -82.52352 27.251..."
2339869,1.209502e+14,1.211500e+14,120150105052037,20.0,0.0,20.0,0.0,20.0,0.0,0.0,...,2.0,0.0,0.0,1.0,NaN,121150020121004,64.0,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",None,"POLYGON ((-82.51995 27.24354, -82.51993 27.243..."

In [87]:
select_hgeocode_geo_ = select_hgeocode_geo.dropna(subset=['geometry_y1'])
len(select_hgeocode_geo_)

2330262

In [88]:
select_hgeocode_geo3 = select_hgeocode_geo_.dropna(subset=['cell_y'])
len(select_hgeocode_geo3)

2330262

In [89]:
select_hgeocode_geo3['centr_x'] = ''
select_hgeocode_geo3['centr_y'] = ''


for n in range(0,len(select_hgeocode_geo3)):
    select_hgeocode_geo3.iloc[n,select_hgeocode_geo3.columns.get_loc("centr_x")]\
    = select_hgeocode_geo3.iloc\
    [n,select_hgeocode_geo3.columns.get_loc("geometry")].centroid.wkt
    
    select_hgeocode_geo3.iloc[n,select_hgeocode_geo3.columns.get_loc("centr_y")]\
    = select_hgeocode_geo3.iloc\
    [n,select_hgeocode_geo3.columns.get_loc("geometry_y1")].centroid.wkt

In [90]:
from shapely import wkt
import geopandas as gpd

select_hgeocode_geo3['centr_x'] = gpd.GeoSeries.from_wkt(select_hgeocode_geo3['centr_x'])
select_hgeocode_geo3['centr_y'] = gpd.GeoSeries.from_wkt(select_hgeocode_geo3['centr_y'])

select_hgeocode_geo3 = gpd.GeoDataFrame(select_hgeocode_geo3, geometry='centr_x')
select_hgeocode_geo3 = gpd.GeoDataFrame(select_hgeocode_geo3, geometry='centr_y')

select_hgeocode_geo3

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,centr_x,centr_y
0,1.207100e+14,1.207104e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.761567,120710401171000,437.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",POINT (-81.82858 26.55344),POINT (-81.83745 26.60195)
1,1.207100e+14,1.207104e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.761567,120710401174006,1.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.81464 26.55431, -81.81258 26.554...",POINT (-81.80925 26.55189),POINT (-81.83745 26.60195)
2,1.207100e+14,1.207105e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.761567,120710503122003,31.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.75083 26.37834, -81.75082 26.378...",POINT (-81.74807 26.37807),POINT (-81.83745 26.60195)
3,1.208797e+14,1.208797e+14,120879718001022,3.0,0.0,2.0,1.0,2.0,1.0,0.0,...,0.0,0.0,0.631994,120879713001011,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.10946 24.70668, -81.10944 24.706...",POINT (-81.10911 24.70639),POINT (-81.73536 24.57052)
4,1.208797e+14,1.208797e+14,120879718001022,3.0,0.0,2.0,1.0,2.0,1.0,0.0,...,0.0,0.0,0.631994,120879722004008,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.77761 24.55928, -81.77736 24.559...",POINT (-81.77679 24.55938),POINT (-81.73536 24.57052)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2330257,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,0.0,6.0,8.290817,121150027331022,100.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.39038 27.02087, -82.38975 27.020...",POINT (-82.37616 27.01467),POINT (-82.10382 27.33388)
2330258,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,0.0,6.0,8.290817,121150027361021,10.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.20371 27.04334, -82.20137 27.047...",POINT (-82.20209 27.04517),POINT (-82.10382 27.33388)
2330259,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,0.0,6.0,8.290817,121150027442000,50.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.20319 27.10020, -82.20317 27.100...",POINT (-82.17761 27.10542),POINT (-82.10382 27.33388)
2330260,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,0.0,6.0,8.290817,121150027451019,5.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.19375 27.03498, -82.18954 27.034...",POINT (-82.19155 27.03457),POINT (-82.10382 27.33388)
2330261,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,0.0,6.0,8.290817,121150027471005,3.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.11871 27.07115, -82.11796 27.071...",POINT (-82.11544 27.07240),POINT (-82.10382 27.33388)

In [91]:
from shapely.ops import transform

for n in range(0,len(select_hgeocode_geo3)):
    select_hgeocode_geo3.iloc[n, select_hgeocode_geo3.columns.get_loc("centr_x")] = transform(lambda x, y: (y, x), select_hgeocode_geo3.iloc[n, select_hgeocode_geo3.columns.get_loc("centr_x")])
#    
    select_hgeocode_geo3.iloc[n, select_hgeocode_geo3.columns.get_loc("centr_y")] = transform(lambda x, y: (y, x), select_hgeocode_geo3.iloc[n, select_hgeocode_geo3.columns.get_loc("centr_y")])

In [92]:
coord_list_x =  select_hgeocode_geo3['centr_x'].geometry.apply(lambda p: list(p.coords)[0])
coord_list_y =  select_hgeocode_geo3['centr_y'].geometry.apply(lambda p: list(p.coords)[0])


select_hgeocode_geo3['centr_x_co'] = coord_list_x

select_hgeocode_geo3['centr_y_co'] = coord_list_y

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

In [93]:
select_hgeocode_geo3= select_hgeocode_geo3.reset_index()
select_hgeocode_geo3=select_hgeocode_geo3.drop(['index'],axis=1)
select_hgeocode_geo3

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,centr_x,centr_y,centr_x_co,centr_y_co
0,1.207100e+14,1.207104e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.761567,120710401171000,437.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",POINT (26.55344 -81.82858),POINT (26.60195 -81.83745),"(26.553440439226623, -81.82857774635599)","(26.60195360533018, -81.83745360718054)"
1,1.207100e+14,1.207104e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.761567,120710401174006,1.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.81464 26.55431, -81.81258 26.554...",POINT (26.55189 -81.80925),POINT (26.60195 -81.83745),"(26.55188845469163, -81.8092548148376)","(26.60195360533018, -81.83745360718054)"
2,1.207100e+14,1.207105e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.761567,120710503122003,31.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.75083 26.37834, -81.75082 26.378...",POINT (26.37807 -81.74807),POINT (26.60195 -81.83745),"(26.37806981170607, -81.74807257700093)","(26.60195360533018, -81.83745360718054)"
3,1.208797e+14,1.208797e+14,120879718001022,3.0,0.0,2.0,1.0,2.0,1.0,0.0,...,0.631994,120879713001011,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.10946 24.70668, -81.10944 24.706...",POINT (24.70639 -81.10911),POINT (24.57052 -81.73536),"(24.706386615281172, -81.10910699357544)","(24.570518191572866, -81.73536038670079)"
4,1.208797e+14,1.208797e+14,120879718001022,3.0,0.0,2.0,1.0,2.0,1.0,0.0,...,0.631994,120879722004008,1.0,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...","POLYGON ((-81.73600 24.56951, -81.73600 24.569...","POLYGON ((-81.77761 24.55928, -81.77736 24.559...",POINT (24.55938 -81.77679),POINT (24.57052 -81.73536),"(24.55937963100572, -81.77679184859768)","(24.570518191572866, -81.73536038670079)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2330257,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,8.290817,121150027331022,100.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.39038 27.02087, -82.38975 27.020...",POINT (27.01467 -82.37616),POINT (27.33388 -82.10382),"(27.014670637763288, -82.37615936385619)","(27.33387966816501, -82.10382416391673)"
2330258,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,8.290817,121150027361021,10.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.20371 27.04334, -82.20137 27.047...",POINT (27.04517 -82.20209),POINT (27.33388 -82.10382),"(27.04517331707139, -82.20208679016757)","(27.33387966816501, -82.10382416391673)"
2330259,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,8.290817,121150027442000,50.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.20319 27.10020, -82.20317 27.100...",POINT (27.10542 -82.17761),POINT (27.33388 -82.10382),"(27.10541797130614, -82.1776106032465)","(27.33387966816501, -82.10382416391673)"
2330260,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,8.290817,121150027451019,5.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.19375 27.03498, -82.18954 27.034...",POINT (27.03457 -82.19155),POINT (27.33388 -82.10382),"(27.034569140309202, -82.191553654932)","(27.33387966816501, -82.10382416391673)"
2330261,1.208100e+14,1.211500e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,8.290817,121150027471005,3.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.11871 27.07115, -82.11796 27.071...",POINT (27.07240 -82.11544),POINT (27.33388 -82.10382),"(27.072395378622705, -82.11544371261999)","(27.33387966816501, -82.10382416391673)"

In [94]:
from geopy.distance import geodesic as GD  

select_hgeocode_geo3['dist_x'] = ''

for n in range(0,len(select_hgeocode_geo3)):
#     print('n=',n)
    select_hgeocode_geo3.loc[n,"dist_x"]\
    = GD(select_hgeocode_geo3.loc[n,"centr_x_co"],select_hgeocode_geo3.loc[n,"centr_y_co"]).km

In [95]:
len(select_hgeocode_geo3)

2330262

In [96]:
select_hgeocode_geo4_1 = select_hgeocode_geo3.drop(['centr_x_co','centr_y_co','centr_x','centr_y'], axis = 1)

In [97]:
select_hgeocode_geo4_2 = select_hgeocode_geo4_1[select_hgeocode_geo4_1['cell_y']>select_hgeocode_geo4_1['C000']]
len(select_hgeocode_geo4_2)

1765678

In [98]:
select_hgeocode_geo4_2_1 =  select_hgeocode_geo4_2[select_hgeocode_geo4_2['w_geocode'] != select_hgeocode_geo4_2['h_geocode_y']]
len(select_hgeocode_geo4_2_1)

1765678

In [99]:
select_hgeocode_geo4_2_2 = select_hgeocode_geo4_2_1[select_hgeocode_geo4_2_1['w_geocode'] != select_hgeocode_geo4_2_1['h_geocode_x']]
len(select_hgeocode_geo4_2_2)

1765002

In [100]:
#to get the min dist from orginal h_geocode (h_geocode_y) to w_geocode



select_hgeocode_geo5_1 =\
    select_hgeocode_geo4_2_2.loc[ select_hgeocode_geo4_2_2.groupby(['h_geocode_y'])['dist_x'].idxmin()].sort_index()

len(select_hgeocode_geo5_1)

6966

In [101]:
len(select_hgeocode_geo5_1['h_geocode_y'].unique())

6966

## This is the output I'm looking for

In [102]:
del select

In [103]:
del select_min_OD

In [104]:
del OD_main

In [105]:
select_hgeocode_geo5_3 = select_hgeocode_geo5_1

In [106]:
# h_geocode_x is h_geocode associated with each w_geocode
# h_geocode_y is original h_geocode (projected employees)
#geometry_x1 for h_geocode_y        #geometry for h_geocode_x       #geometry_y1 for w_geocode
#cell_x for h_geocode_y #cell_y for h_geocode_x


# select_hgeocode_geo5_6_ = select_hgeocode_geo5_3.drop_duplicates(subset=['h_geocode_y'])
select_hgeocode_geo5_6_ = select_hgeocode_geo5_3

select_hgeocode_geo5_6_

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS19,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,dist_x
0,1.207100e+14,1.207104e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.761567,120710401171000,437.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",5.447355
35,1.211500e+14,1.211500e+14,121150023023000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.916516,121150023061010,7.0,"POLYGON ((-82.43367 27.11708, -82.43367 27.117...","POLYGON ((-82.42052 27.10943, -82.42051 27.109...","POLYGON ((-82.41329 27.12622, -82.41310 27.126...",2.208549
76,1.202101e+14,1.202101e+14,120210112043005,12.0,2.0,6.0,4.0,9.0,3.0,0.0,...,0.0,0.0,0.0,0.77274,120210113062003,14.0,"POLYGON ((-81.42547 26.41482, -81.42466 26.414...","POLYGON ((-81.41836 26.41846, -81.41740 26.418...","POLYGON ((-81.46519 26.43521, -81.46470 26.435...",4.918122
86,1.208797e+14,1.208797e+14,120879717003014,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.129322,120879718001011,89.0,"POLYGON ((-81.67570 24.60202, -81.67570 24.602...","POLYGON ((-81.66069 24.60108, -81.66053 24.601...","POLYGON ((-81.74231 24.58633, -81.74224 24.586...",7.984476
101,1.208100e+14,1.208100e+14,120810020254005,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.730409,120810020242010,44.0,"POLYGON ((-82.47852 27.50409, -82.47840 27.504...","POLYGON ((-82.47461 27.51143, -82.47454 27.511...","POLYGON ((-82.47844 27.51307, -82.47833 27.513...",0.109147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2329581,1.208100e+14,1.208100e+14,120810020183029,2.0,0.0,1.0,1.0,2.0,0.0,0.0,...,0.0,0.0,0.0,5.033827,120810020121004,56.0,"POLYGON ((-82.42543 27.48683, -82.42515 27.486...","POLYGON ((-82.45919 27.44140, -82.45919 27.442...","POLYGON ((-82.46830 27.44550, -82.46819 27.445...",0.783195
2329894,1.208100e+14,1.208100e+14,120810015023039,8.0,2.0,4.0,2.0,6.0,1.0,0.0,...,0.0,0.0,0.0,0.566279,120810015012012,24.0,"POLYGON ((-82.55902 27.51934, -82.55849 27.519...","POLYGON ((-82.56244 27.52125, -82.56139 27.524...","POLYGON ((-82.55752 27.53963, -82.55649 27.539...",1.657977
2329994,1.208100e+14,1.208100e+14,120810019142082,15.0,3.0,7.0,5.0,14.0,0.0,0.0,...,0.0,0.0,4.0,5.085242,120810019141037,26.0,"POLYGON ((-82.36136 27.55343, -82.36129 27.553...","POLYGON ((-82.36456 27.56590, -82.36438 27.566...","POLYGON ((-82.38413 27.64185, -82.38412 27.641...",10.390985
2330000,1.208100e+14,1.208100e+14,120810007043047,11.0,2.0,6.0,3.0,5.0,6.0,0.0,...,0.0,1.0,0.0,2.99863,120810001053014,249.0,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...","POLYGON ((-82.56678 27.47713, -82.56306 27.477...","POLYGON ((-82.57124 27.47295, -82.57124 27.473...",0.594089
2330194,1.208100e+14,1.208100e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,0.0,0.0,6.0,8.290817,120810020101013,28.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.16255 27.35193, -82.16252 27.355...",5.639469

In [107]:
len(Emp_home_select_2030_new_values_home_work3_final)

7185

In [108]:
len(Emp_home_select_2030_new_values_home_work3_final_)

7440

In [109]:
Emp_home_select_2030_new_values_home_work3_final_['h_geocode']

82        120710012051002
355       120879718001022
472       121150023023000
571       120210112043005
647       120879717003014
               ...
116326    120150303013030
116426    120210101082002
116973    120150105052077
116982    120150204022186
117027    120150105052037
Name: h_geocode, Length: 7440, dtype: int64

In [110]:
Emp_home_select_2030_new_values_home_work3_final['h_geocode']

82       120710012051002
355      120879718001022
472      121150023023000
571      120210112043005
647      120879717003014
              ...
84491    120810020183029
84499    120810015023039
84507    120810019142082
84513    120810007043047
84529    120810020102028
Name: h_geocode, Length: 7185, dtype: int64

In [111]:
Emp_home_select_2030_new_values_home_work3_final['h_geocode']

82       120710012051002
355      120879718001022
472      121150023023000
571      120210112043005
647      120879717003014
              ...
84491    120810020183029
84499    120810015023039
84507    120810019142082
84513    120810007043047
84529    120810020102028
Name: h_geocode, Length: 7185, dtype: int64

In [112]:
select_min_select2_missing = select_min_select2.loc[~select_min_select2['h_geocode'].isin(Emp_home_select_2030_new_values_home_work3_final['h_geocode'])]
select_min_select2_missing

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS15,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist
70717,120710403083056,"POLYGON ((-81.59997 26.55253, -81.59995 26.552...",6.0,0.0,5.0,1.0,6.0,0.0,0.0,0.0,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.205100e+14,None,NaN
70718,120710403083056,"POLYGON ((-81.59997 26.55253, -81.59995 26.552...",6.0,0.0,5.0,1.0,6.0,0.0,0.0,0.0,...,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.210303e+14,None,NaN
74562,120150203011144,"POLYGON ((-82.15527 27.02277, -82.15432 27.022...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.201105e+14,None,NaN
74563,120150203011144,"POLYGON ((-82.15527 27.02277, -82.15432 27.022...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.209901e+14,None,NaN
74760,120150203021011,"POLYGON ((-82.14349 26.99068, -82.14239 26.990...",8.0,3.0,5.0,0.0,6.0,2.0,0.0,0.0,...,1.0,1.0,1.0,2.0,0.0,0.0,2.0,1.201106e+14,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116326,120150303013030,"POLYGON ((-82.34240 26.93723, -82.34240 26.937...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.211138e+14,None,NaN
116426,120210101082002,"POLYGON ((-81.79477 26.29432, -81.79450 26.294...",10.0,10.0,0.0,0.0,10.0,0.0,0.0,0.0,...,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1.210103e+14,None,NaN
116973,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN
116982,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",11.0,0.0,11.0,0.0,11.0,0.0,0.0,0.0,...,0.0,3.0,0.0,1.0,0.0,1.0,0.0,1.209502e+14,None,NaN
117027,120150105052037,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",20.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,...,2.0,4.0,0.0,2.0,0.0,0.0,1.0,1.209502e+14,None,NaN

In [113]:
# select_2040_hgeocode_geo4_3_1 is the remaining zones from select_2040_hgeocode_geo4_3 
# after excluding zones that workzones number = homezone number (zones poeple work and live)

select_2030_hgeocode_geo4_3_1 = select_min_select2.loc[~select_min_select2['h_geocode'].isin(select_hgeocode_geo5_6_['h_geocode_y'])]
len(select_2030_hgeocode_geo4_3_1)

474

In [114]:
import pandas as pd 
select_2030_hgeocode_geo4_3_1_conc=pd.concat([select_2030_hgeocode_geo4_3_1, select_min_select2_missing], axis=0)
len(select_2030_hgeocode_geo4_3_1_conc)

729

In [115]:
Emp_cells_sum

             h_geocode  cell
0      120150101001000     9
1      120150101001005    10
2      120150101001008     1
3      120150101001009    63
4      120150101001010    20
...                ...   ...
22063  121150027481010     7
22064  121150027481011     3
22065  121150027482002     6
22066  121150027482003     5
22067  121150027483006     2

[22068 rows x 2 columns]

In [116]:
Emp_cells_sum_no_dups = Emp_cells_sum.drop_duplicates(subset=['h_geocode'])
Emp_cells_sum_no_dups_pre = Emp_cells_sum_no_dups
Emp_cells_sum_no_dups_pre = Emp_cells_sum_no_dups
Emp_cells_sum_no_dups_final = Emp_cells_sum_no_dups_pre.loc[~Emp_cells_sum_no_dups_pre['h_geocode'].isin(select_hgeocode_geo5_6_['h_geocode_x'])]

len(Emp_cells_sum_no_dups_final)

19423

In [117]:
Emp_home_select_2030_new_geo = Emp_home_select_2030_part2_new2[['h_geocode','geometry']]

In [118]:
Emp_home_select_2030_new_geo = Emp_home_select_2030_new_geo.astype({"h_geocode":'int64'})

In [119]:
Emp_cells_sum_no_dups_final_geo = pd.merge(Emp_cells_sum_no_dups_final,Emp_home_select_2030_new_geo, how='left',
                                          left_on=['h_geocode'],right_on = ['h_geocode'])
Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo.dropna(subset=['geometry'])
len(Emp_cells_sum_no_dups_final_geo2)

19423

In [120]:
def find_coordinates(Emp_cells_sum_no_dups_final_geo2):

    from shapely import wkt
    import geopandas as gpd
    from shapely.ops import transform

    
    temp = Emp_cells_sum_no_dups_final_geo2.copy()

    Emp_cells_sum_no_dups_final_geo2['centr'] = ''
    
#     Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.reset_index()
#     Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.drop(['index'], axis = 1)
    
#     print(Emp_cells_sum_no_dups_final_geo2)
        
#     for i in range (0,len(Emp_cells_sum_no_dups_final_geo2)):
    if 'geometry' in Emp_cells_sum_no_dups_final_geo2.columns:
        print('Yes')
    else: 
        print('No')
        Emp_cells_sum_no_dups_final_geo2.rename(columns = {'geometry_x':'geometry'}, inplace = True)

    

    for n in range(0,len(Emp_cells_sum_no_dups_final_geo2)):
        Emp_cells_sum_no_dups_final_geo2.iloc[n,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("centr")]\
        = Emp_cells_sum_no_dups_final_geo2.iloc\
        [n,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("geometry")].centroid.wkt

    Emp_cells_sum_no_dups_final_geo2['centr'] = gpd.GeoSeries.from_wkt(Emp_cells_sum_no_dups_final_geo2['centr'])
    Emp_cells_sum_no_dups_final_geo2 = gpd.GeoDataFrame(Emp_cells_sum_no_dups_final_geo2, geometry='centr')

    for n in range(0,len(Emp_cells_sum_no_dups_final_geo2)):
        Emp_cells_sum_no_dups_final_geo2.iloc[n, Emp_cells_sum_no_dups_final_geo2.columns.get_loc("centr")] = transform(lambda x, y: (y, x),
                            Emp_cells_sum_no_dups_final_geo2.iloc[n, Emp_cells_sum_no_dups_final_geo2.columns.get_loc("centr")])

    coord_list =  Emp_cells_sum_no_dups_final_geo2['centr'].geometry.apply(lambda p: list(p.coords)[0])
    Emp_cells_sum_no_dups_final_geo2['centr_co'] = coord_list
        
    if 'geometry' in temp.columns:
        print('Yes')
    else: 
        print('No')
        Emp_cells_sum_no_dups_final_geo2.rename(columns = {'geometry':'geometry_x'}, inplace = True)
        Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.drop(['centr_x_co','centr'],axis=1)
        Emp_cells_sum_no_dups_final_geo2.rename(columns = {'centr_co':'centr_x_co'}, inplace = True)


    return Emp_cells_sum_no_dups_final_geo2

In [121]:
Emp_cells_sum_no_dups_final_geo2= find_coordinates(Emp_cells_sum_no_dups_final_geo2)

Yes

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

Yes

In [122]:
# Emp_home_select_2030_new_values_home_work3 for (h_geocode and w_geocode relations) 

Emp_home_select_2030_new_values_home_work3_subset = Emp_home_select_2030_new_values_home_work3[['h_geocode','centr_x_co']]

select_2030_hgeocode_geo4_3_1_geo = pd.merge(select_2030_hgeocode_geo4_3_1_conc,Emp_home_select_2030_new_values_home_work3_subset, how='left',
                                          left_on=['h_geocode'],right_on = ['h_geocode'])
select_2030_hgeocode_geo4_3_1_geo2 = select_2030_hgeocode_geo4_3_1_geo.drop_duplicates(subset=['h_geocode'])
select_2030_hgeocode_geo4_3_1_geo2

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist,centr_x_co
0,120879718001022,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",3.0,0.0,2.0,1.0,2.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",0.631994,"(24.567331297140306, -81.73018543710354)"
89,120879719003003,"POLYGON ((-81.76164 24.56620, -81.76155 24.566...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.75942 24.57020, -81.75927 24.570...",0.275114,"(24.56654979307335, -81.75848011676781)"
221,120879720003001,"POLYGON ((-81.77867 24.55585, -81.77860 24.555...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.77687 24.55700, -81.77674 24.557...",0.344982,"(24.55379872565682, -81.77423283950421)"
322,120710103064008,"POLYGON ((-81.96485 26.64868, -81.96481 26.648...",14.0,2.0,7.0,5.0,13.0,1.0,0.0,0.0,...,2.0,0.0,2.0,0.0,0.0,5.0,1.207101e+14,"POLYGON ((-81.95863 26.63968, -81.95862 26.640...",0.322215,"(26.64349915458726, -81.96157126866642)"
424,121150027142000,"POLYGON ((-82.43564 27.13785, -82.43560 27.138...",6.0,1.0,3.0,2.0,6.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,1.211500e+14,"POLYGON ((-82.42548 27.14909, -82.42516 27.149...",0.687964,"(27.1430981901613, -82.42181956145436)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,120150303013030,"POLYGON ((-82.34240 26.93723, -82.34240 26.937...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.211138e+14,None,NaN,NaN
3521,120210101082002,"POLYGON ((-81.79477 26.29432, -81.79450 26.294...",10.0,10.0,0.0,0.0,10.0,0.0,0.0,0.0,...,2.0,0.0,2.0,0.0,0.0,0.0,1.210103e+14,None,NaN,NaN
3522,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,NaN
3523,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",11.0,0.0,11.0,0.0,11.0,0.0,0.0,0.0,...,3.0,0.0,1.0,0.0,1.0,0.0,1.209502e+14,None,NaN,NaN
3524,120150105052037,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",20.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,...,4.0,0.0,2.0,0.0,0.0,1.0,1.209502e+14,None,NaN,NaN

In [123]:
#this cell trying to find those rows that don't have centr_x_co

select_2030_hgeocode_geo4_3_1_geo22w2w2 = select_2030_hgeocode_geo4_3_1_geo2.dropna(subset=['centr_x_co'])
select_2030_hgeocode_geo4_3_1_geo22w2w2_find = select_2030_hgeocode_geo4_3_1_geo2.loc[~select_2030_hgeocode_geo4_3_1_geo2['h_geocode'].isin(select_2030_hgeocode_geo4_3_1_geo22w2w2['h_geocode'])]
                                                                                     
select_2030_hgeocode_geo4_3_1_geo22w2w2_find

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist,centr_x_co
3270,120710403083056,"POLYGON ((-81.59997 26.55253, -81.59995 26.552...",6.0,0.0,5.0,1.0,6.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,1.205100e+14,None,NaN,NaN
3272,120150203011144,"POLYGON ((-82.15527 27.02277, -82.15432 27.022...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.201105e+14,None,NaN,NaN
3274,120150203021011,"POLYGON ((-82.14349 26.99068, -82.14239 26.990...",8.0,3.0,5.0,0.0,6.0,2.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,2.0,1.201106e+14,None,NaN,NaN
3276,120710401212017,"POLYGON ((-81.73454 26.61990, -81.73412 26.619...",1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.210302e+14,None,NaN,NaN
3277,120150209001046,"POLYGON ((-82.06817 26.98937, -82.06532 26.989...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,120150303013030,"POLYGON ((-82.34240 26.93723, -82.34240 26.937...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.211138e+14,None,NaN,NaN
3521,120210101082002,"POLYGON ((-81.79477 26.29432, -81.79450 26.294...",10.0,10.0,0.0,0.0,10.0,0.0,0.0,0.0,...,2.0,0.0,2.0,0.0,0.0,0.0,1.210103e+14,None,NaN,NaN
3522,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,NaN
3523,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",11.0,0.0,11.0,0.0,11.0,0.0,0.0,0.0,...,3.0,0.0,1.0,0.0,1.0,0.0,1.209502e+14,None,NaN,NaN
3524,120150105052037,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",20.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,...,4.0,0.0,2.0,0.0,0.0,1.0,1.209502e+14,None,NaN,NaN

In [124]:
#getting centr_x_co using their geometery

select_2030_hgeocode_geo4_3_1_geo22w2w2_find= find_coordinates(select_2030_hgeocode_geo4_3_1_geo22w2w2_find)

No
No

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/var/folders/pc/11vhsnt944j5yjbbz3_d41k00000gq/T/ipykernel_15208/3361184365.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Emp_cells_sum_no_dups_final_geo2.rename(columns = {'geometry_x':'geometry'}, inplace = True)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geoseries.py:645: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

In [125]:
select_2030_hgeocode_geo4_3_1_geo22w2w2_find

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist,centr_x_co
3270,120710403083056,"POLYGON ((-81.59997 26.55253, -81.59995 26.552...",6.0,0.0,5.0,1.0,6.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,1.205100e+14,None,NaN,"(26.55276237912144, -81.5994759262279)"
3272,120150203011144,"POLYGON ((-82.15527 27.02277, -82.15432 27.022...",1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.201105e+14,None,NaN,"(27.02153284242703, -82.15480086799396)"
3274,120150203021011,"POLYGON ((-82.14349 26.99068, -82.14239 26.990...",8.0,3.0,5.0,0.0,6.0,2.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,2.0,1.201106e+14,None,NaN,"(26.990053223452303, -82.14296197591025)"
3276,120710401212017,"POLYGON ((-81.73454 26.61990, -81.73412 26.619...",1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.210302e+14,None,NaN,"(26.61940328185898, -81.73360444655309)"
3277,120150209001046,"POLYGON ((-82.06817 26.98937, -82.06532 26.989...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.209901e+14,None,NaN,"(26.988949923691493, -82.06674888482104)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,120150303013030,"POLYGON ((-82.34240 26.93723, -82.34240 26.937...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.211138e+14,None,NaN,"(26.93761298178636, -82.34180269963774)"
3521,120210101082002,"POLYGON ((-81.79477 26.29432, -81.79450 26.294...",10.0,10.0,0.0,0.0,10.0,0.0,0.0,0.0,...,2.0,0.0,2.0,0.0,0.0,0.0,1.210103e+14,None,NaN,"(26.293580091263486, -81.79463804289828)"
3522,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,"(26.86072744671804, -82.0168655661004)"
3523,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",11.0,0.0,11.0,0.0,11.0,0.0,0.0,0.0,...,3.0,0.0,1.0,0.0,1.0,0.0,1.209502e+14,None,NaN,"(27.004866401536365, -82.20261830319743)"
3524,120150105052037,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",20.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,...,4.0,0.0,2.0,0.0,0.0,1.0,1.209502e+14,None,NaN,"(26.866524742515672, -82.00328806014292)"

In [126]:
#add back to the zones that need to find cells for them (using nearest availble zones)

select_2030_hgeocode_geo4_3_1_geo2=pd.concat([select_2030_hgeocode_geo4_3_1_geo22w2w2,select_2030_hgeocode_geo4_3_1_geo22w2w2_find], axis=0)
select_2030_hgeocode_geo4_3_1_geo2

,h_geocode,geometry_x,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS16,CNS17,CNS18,CNS19,CNS20,cell,w_geocode,geometry_y,dist,centr_x_co
0,120879718001022,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",3.0,0.0,2.0,1.0,2.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",0.631994,"(24.567331297140306, -81.73018543710354)"
89,120879719003003,"POLYGON ((-81.76164 24.56620, -81.76155 24.566...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.75942 24.57020, -81.75927 24.570...",0.275114,"(24.56654979307335, -81.75848011676781)"
221,120879720003001,"POLYGON ((-81.77867 24.55585, -81.77860 24.555...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.77687 24.55700, -81.77674 24.557...",0.344982,"(24.55379872565682, -81.77423283950421)"
322,120710103064008,"POLYGON ((-81.96485 26.64868, -81.96481 26.648...",14.0,2.0,7.0,5.0,13.0,1.0,0.0,0.0,...,2.0,0.0,2.0,0.0,0.0,5.0,1.207101e+14,"POLYGON ((-81.95863 26.63968, -81.95862 26.640...",0.322215,"(26.64349915458726, -81.96157126866642)"
424,121150027142000,"POLYGON ((-82.43564 27.13785, -82.43560 27.138...",6.0,1.0,3.0,2.0,6.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,1.211500e+14,"POLYGON ((-82.42548 27.14909, -82.42516 27.149...",0.687964,"(27.1430981901613, -82.42181956145436)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,120150303013030,"POLYGON ((-82.34240 26.93723, -82.34240 26.937...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.211138e+14,None,NaN,"(26.93761298178636, -82.34180269963774)"
3521,120210101082002,"POLYGON ((-81.79477 26.29432, -81.79450 26.294...",10.0,10.0,0.0,0.0,10.0,0.0,0.0,0.0,...,2.0,0.0,2.0,0.0,0.0,0.0,1.210103e+14,None,NaN,"(26.293580091263486, -81.79463804289828)"
3522,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,"(26.86072744671804, -82.0168655661004)"
3523,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",11.0,0.0,11.0,0.0,11.0,0.0,0.0,0.0,...,3.0,0.0,1.0,0.0,1.0,0.0,1.209502e+14,None,NaN,"(27.004866401536365, -82.20261830319743)"
3524,120150105052037,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",20.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,...,4.0,0.0,2.0,0.0,0.0,1.0,1.209502e+14,None,NaN,"(26.866524742515672, -82.00328806014292)"

In [127]:
def find_cells(Emp_cells_sum_no_dups_final_geo2, select_2030_hgeocode_geo4_3_1_geo2):
    from geopy.distance import geodesic as GD  

    Emp_cells_sum_no_dups_final_geo2['cell_remain'] =Emp_cells_sum_no_dups_final_geo2['cell']

    select_2030_hgeocode_geo4_3_1_geo2['h_geocode_x'] = ''
    select_2030_hgeocode_geo4_3_1_geo2['dist_x'] = ''

    for n1 in range(0,len(select_2030_hgeocode_geo4_3_1_geo2)):
        temprory_hgeocode_final = pd.DataFrame(columns = ['h_geocode', 'dist','cell'])
        temprory = []
        temprory_hgeocode = []
        temprory_cell = []
        temprory3 = []
        temprory4 = []
        print('n1=',n1)
        for l in range(0,len(Emp_cells_sum_no_dups_final_geo2)):
#             print('l=',l)
#             print('select_2030_hgeocode_geo4_3_1_geo2[C000]=',select_2030_hgeocode_geo4_3_1_geo2.iloc[n,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")])
#             print('Emp_cells_sum_no_dups_final_geo2[cell_remain]=',Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")])
            if  (select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")] < Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")]) and (Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")]>0) :
                temprory2= GD(Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("centr_co")],
                                 select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("centr_x_co")]).km
                temprory2_h = Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("h_geocode")]
    #             print('temprory2_h=',Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("h_geocode")])

                temprory2_c = Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")]

                temprory.append(temprory2)
                temprory_hgeocode.append(temprory2_h)
                temprory_cell.append(temprory2_c)
                continue   

        if len(temprory_hgeocode) == 0:
            break
                
#         print('temprory_hgeocode=',temprory_hgeocode)
#         print('temprory_hgeocode=',temprory_hgeocode)
        temprory_hgeocode_final['h_geocode'] = temprory_hgeocode
        temprory_hgeocode_final['dist'] = temprory
        temprory_hgeocode_final['cell'] = temprory_cell
#         print('temprory_hgeocode_final=',temprory_hgeocode_final)
#         print('temprory_hgeocode_final_select=',temprory_hgeocode_final[temprory_hgeocode_final['h_geocode'] == 10030105001012 ])
#         print('temprory_hgeocode_final_select2=',temprory_hgeocode_final[temprory_hgeocode_final['h_geocode'] == 10030101001014 ])
        temprory3 = temprory_hgeocode_final[temprory_hgeocode_final.dist == temprory_hgeocode_final.dist.min()]
    #     print('temprory3=',temprory3)
        temprory4 = temprory3.drop_duplicates(subset=['h_geocode'])
        print('temprory4=',temprory4)  
        select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("h_geocode_x")] = temprory4.h_geocode.to_numpy()[0]
        select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("dist_x")] = temprory4.dist.to_numpy()[0]

        for l in range(0,len(Emp_cells_sum_no_dups_final_geo2)):
            for s in range(0,len(temprory4)):
                if Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("h_geocode")] == temprory4.iloc[s,temprory4.columns.get_loc("h_geocode")]: 
                    print('RHS=',temprory4.iloc[s,temprory4.columns.get_loc("h_geocode")])
                    print('C000=',select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")])
                    Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")] =  Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")] -  select_2030_hgeocode_geo4_3_1_geo2.iloc[n1,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")]
                    print('cell_remain=',Emp_cells_sum_no_dups_final_geo2.iloc[l,Emp_cells_sum_no_dups_final_geo2.columns.get_loc("cell_remain")])
                    break
                else:
                    continue
    #     Emp_cells_sum_no_dups_final_geo2.loc[Emp_cells_sum_no_dups_final_geo2['h_geocode'] == temprory3['h_geocode'],'cell_remain'] = Emp_cells_sum_no_dups_final_geo2.loc[Emp_cells_sum_no_dups_final_geo2['h_geocode'] == temprory3['h_geocode'],'cell_remain'] - select_2030_hgeocode_geo4_3_1_geo2.iloc[n,select_2030_hgeocode_geo4_3_1_geo2.columns.get_loc("C000")]

    return

In [128]:
find_cells(Emp_cells_sum_no_dups_final_geo2,select_2030_hgeocode_geo4_3_1_geo2)

n1= 0
temprory4=             h_geocode      dist  cell
8955  120879720002005  2.646203     4
RHS= 120879720002005
C000= 3.0
cell_remain= 1
n1= 1
temprory4=              h_geocode      dist  cell
11766  120879719003005  0.465509     2
RHS= 120879719003005
C000= 1.0
cell_remain= 1
n1= 2
temprory4=              h_geocode      dist  cell
11767  120879720001005  0.558742     3
RHS= 120879720001005
C000= 1.0
cell_remain= 2
n1= 3
temprory4=             h_geocode      dist  cell
1219  120710103064023  0.712168    20
RHS= 120710103064023
C000= 14.0
cell_remain= 6
n1= 4
temprory4=             h_geocode      dist  cell
8021  121150027142018  0.840429     8
RHS= 121150027142018
C000= 6.0
cell_remain= 2
n1= 5
temprory4=             h_geocode      dist  cell
9447  120810004101006  0.158768    20
RHS= 120810004101006
C000= 1.0
cell_remain= 19
n1= 6
temprory4=             h_geocode      dist  cell
2944  120710015023000  0.379109    16
RHS= 120710015023000
C000= 2.0
cell_remain= 14
n1= 7
temprory4=             h_geocode      dist  cell
4430  120710403041005  0.522059    12
RHS= 120710403041005
C000= 5.0
cell_remain= 7
n1= 8
temprory4=             h_geocode      dist  cell
7677  120710403016033  0.378409     2
RHS= 120710403016033
C000= 1.0
cell_remain= 1
n1= 9
temprory4=          h_geocode      dist  cell
0  120150101001010  5.755028    20
RHS= 120150101001010
C000= 15.0
cell_remain= 5
n1= 10
temprory4=             h_geocode      dist  cell
3841  120710201032028  0.599661     9
RHS= 120710201032028
C000= 5.0
cell_remain= 4
n1= 11
temprory4=             h_geocode      dist  cell
8253  120810007041018  0.265399    12
RHS= 120810007041018
C000= 2.0
cell_remain= 10
n1= 12
temprory4=             h_geocode      dist  cell
7936  120879704004002  1.773423     5
RHS= 120879704004002
C000= 4.0
cell_remain= 1
n1= 13
temprory4=            h_geocode      dist  cell
150  120210101102007  0.100524    25
RHS= 120210101102007
C000= 24.0
cell_remain= 1
n1= 14
temprory4=             h_geocode      dist  cell
6417  120879711001035  3.955322    10
RHS= 120879711001035
C000= 6.0
cell_remain= 4
n1= 15
temprory4=              h_geocode      dist  cell
10163  120879720002010  3.624436     3
RHS= 120879720002010
C000= 2.0
cell_remain= 1
n1= 16
temprory4=          h_geocode      dist  cell
0  120150102001026  1.506901    27
RHS= 120150102001026
C000= 14.0
cell_remain= 13
n1= 17
temprory4=             h_geocode      dist  cell
3794  121150027452073  0.141296    16
RHS= 121150027452073
C000= 15.0
cell_remain= 1
n1= 18
temprory4=           h_geocode      dist  cell
80  120150203023025  1.257022    13
RHS= 120150203023025
C000= 11.0
cell_remain= 2
n1= 19
temprory4=             h_geocode      dist  cell
9039  120810015011023  0.102051     7
RHS= 120810015011023
C000= 2.0
cell_remain= 5
n1= 20
temprory4=             h_geocode      dist  cell
8817  120810012022011  0.129485     9
RHS= 120810012022011
C000= 2.0
cell_remain= 7
n1= 21
temprory4=             h_geocode      dist  cell
7940  120879708001008  0.430953    10
RHS= 120879708001008
C000= 4.0
cell_remain= 6
n1= 22
temprory4=             h_geocode     dist  cell
8937  120879715021027  7.69319     4
RHS= 120879715021027
C000= 3.0
cell_remain= 1
n1= 23
temprory4=             h_geocode      dist  cell
7966  120879721002006  1.329948     5
RHS= 120879721002006
C000= 4.0
cell_remain= 1
n1= 24
temprory4=             h_geocode      dist  cell
5811  120879706001001  0.331353    13
RHS= 120879706001001
C000= 7.0
cell_remain= 6
n1= 25
temprory4=             h_geocode       dist  cell
4817  120879716001017  24.667466    10
RHS= 120879716001017
C000= 9.0
cell_remain= 1
n1= 26
temprory4=              h_geocode      dist  cell
11824  120879728004026  1.188714     4
RHS= 120879728004026
C000= 1.0
cell_remain= 3
n1= 27
temprory4=             h_geocode      dist  cell
3506  120710015022008  0.243332     2
RHS= 120710015022008
C000= 1.0
cell_remain= 1
n1= 28
temprory4=             h_geocode       dist  cell
4055  120879716002012  29.705748    41
RHS= 120879716002012
C000= 11.0
cell_remain= 30
n1= 29
temprory4=             h_geocode       dist  cell
7964  120879717001006  14.263773     8
RHS= 120879717001006
C000= 4.0
cell_remain= 4
n1= 30
temprory4=             h_geocode       dist  cell
3726  120879716002012  30.452292    30
RHS= 120879716002012
C000= 12.0
cell_remain= 18
n1= 31
temprory4=             h_geocode     dist  cell
8953  120879721002023  1.80422     4
RHS= 120879721002023
C000= 3.0
cell_remain= 1
n1= 32
temprory4=             h_geocode       dist  cell
7108  120879716001012  23.639532     6
RHS= 120879716001012
C000= 5.0
cell_remain= 1
n1= 33
temprory4=             h_geocode    dist  cell
6405  120879706001034  7.1614     8
RHS= 120879706001034
C000= 6.0
cell_remain= 2
n1= 34
temprory4=              h_geocode      dist  cell
11759  120879719003021  0.719014     2
RHS= 120879719003021
C000= 1.0
cell_remain= 1
n1= 35
temprory4=              h_geocode      dist  cell
10166  120879722004016  0.257222     3
RHS= 120879722004016
C000= 2.0
cell_remain= 1
n1= 36
temprory4=             h_geocode      dist  cell
8949  120879721002019  1.958498     4
RHS= 120879721002019
C000= 3.0
cell_remain= 1
n1= 37
temprory4=             h_geocode       dist  cell
3433  120879716002012  28.856413    18
RHS= 120879716002012
C000= 13.0
cell_remain= 5
n1= 38
temprory4=            h_geocode      dist  cell
480  120150204011032  1.629154    21
RHS= 120150204011032
C000= 2.0
cell_remain= 19
n1= 39
temprory4=             h_geocode      dist  cell
2532  120710102051080  0.453078     7
RHS= 120710102051080
C000= 5.0
cell_remain= 2
n1= 40
temprory4=            h_geocode      dist  cell
582  120710103074000  4.588138    37
RHS= 120710103074000
C000= 32.0
cell_remain= 5
n1= 41
temprory4=             h_geocode      dist  cell
2853  120710011012012  0.166695     3
RHS= 120710011012012
C000= 2.0
cell_remain= 1
n1= 42
temprory4=             h_geocode      dist  cell
5239  120810001051011  0.231794    11
RHS= 120810001051011
C000= 5.0
cell_remain= 6
n1= 43
temprory4=             h_geocode      dist  cell
9490  120810019151018  0.254789     3
RHS= 120810019151018
C000= 2.0
cell_remain= 1
n1= 44
temprory4=             h_geocode      dist  cell
2753  120810008132008  0.276039    16
RHS= 120810008132008
C000= 13.0
cell_remain= 3
n1= 45
temprory4=             h_geocode      dist  cell
3552  120710102073018  0.092358    14
RHS= 120710102073018
C000= 3.0
cell_remain= 11
n1= 46
temprory4=             h_geocode      dist  cell
4531  120710104043050  0.321288    12
RHS= 120710104043050
C000= 2.0
cell_remain= 10
n1= 47
temprory4=             h_geocode      dist  cell
1045  120710103083017  0.268465    19
RHS= 120710103083017
C000= 17.0
cell_remain= 2
n1= 48
temprory4=              h_geocode      dist  cell
13566  121150027462149  0.148801     4
RHS= 121150027462149
C000= 2.0
cell_remain= 2
n1= 49
temprory4=           h_geocode   dist  cell
70  120150207002014  0.496    18
RHS= 120150207002014
C000= 13.0
cell_remain= 5
n1= 50
temprory4=             h_geocode      dist  cell
7038  121150027471001  1.356945    12
RHS= 121150027471001
C000= 8.0
cell_remain= 4
n1= 51
temprory4=             h_geocode      dist  cell
4876  120710402081002  0.715125    11
RHS= 120710402081002
C000= 4.0
cell_remain= 7
n1= 52
temprory4=            h_geocode      dist  cell
141  120150202052023  0.126401     8
RHS= 120150202052023
C000= 6.0
cell_remain= 2
n1= 53
temprory4=             h_geocode      dist  cell
4685  120810019084043  0.537101    26
RHS= 120810019084043
C000= 8.0
cell_remain= 18
n1= 54
temprory4=             h_geocode      dist  cell
1218  120710103073015  0.503859    25
RHS= 120710103073015
C000= 14.0
cell_remain= 11
n1= 55
temprory4=             h_geocode     dist  cell
2974  120710102062052  0.09443     5
RHS= 120710102062052
C000= 4.0
cell_remain= 1
n1= 56
temprory4=             h_geocode      dist  cell
5320  120710104043050  0.273695    10
RHS= 120710104043050
C000= 1.0
cell_remain= 9
n1= 57
temprory4=             h_geocode      dist  cell
1372  120710104232035  0.172423    27
RHS= 120710104232035
C000= 15.0
cell_remain= 12
n1= 58
temprory4=             h_geocode     dist  cell
9294  120810019084043  0.21734    18

RHS= 120810019084043
C000= 2.0
cell_remain= 16
n1= 59
temprory4=             h_geocode      dist  cell
6165  120710401372004  0.634581    18
RHS= 120710401372004
C000= 2.0
cell_remain= 16
n1= 60
temprory4=            h_geocode      dist  cell
687  120710103074019  2.024649    31
RHS= 120710103074019
C000= 27.0
cell_remain= 4
n1= 61
temprory4=             h_geocode     dist  cell
7564  120710402123000  0.33492    34
RHS= 120710402123000
C000= 1.0
cell_remain= 33
n1= 62
temprory4=           h_geocode      dist  cell
51  120150208001010  1.500228    18
RHS= 120150208001010
C000= 17.0
cell_remain= 1
n1= 63
temprory4=            h_geocode      dist  cell
956  120210106062010  0.286477    32
RHS= 120210106062010
C000= 9.0
cell_remain= 23
n1= 64
temprory4=             h_geocode      dist  cell
3143  120710403016028  0.718795    11
RHS= 120710403016028
C000= 8.0
cell_remain= 3
n1= 65
temprory4=             h_geocode      dist  cell
1759  121150015041016  0.214747    42
RHS= 121150015041016
C000= 26.0
cell_remain= 16
n1= 66
temprory4=             h_geocode      dist  cell
3542  120710104132013  0.137215    11
RHS= 120710104132013
C000= 4.0
cell_remain= 7
n1= 67
temprory4=             h_geocode      dist  cell
2605  120810006032004  0.226323    14
RHS= 120810006032004
C000= 13.0
cell_remain= 1
n1= 68
temprory4=            h_geocode      dist  cell
583  120210104213004  0.467819    15
RHS= 120210104213004
C000= 10.0
cell_remain= 5
n1= 69
temprory4=              h_geocode      dist  cell
10149  120879720001036  0.078713     3
RHS= 120879720001036
C000= 2.0
cell_remain= 1
n1= 70
temprory4=             h_geocode      dist  cell
7928  120879706001001  1.866373     6
RHS= 120879706001001
C000= 4.0
cell_remain= 2
n1= 71
temprory4=             h_geocode      dist  cell
1976  120210104323004  0.376556    21
RHS= 120210104323004
C000= 2.0
cell_remain= 19
n1= 72
temprory4=              h_geocode      dist  cell
11724  120879711001041  0.207144     5
RHS= 120879711001041
C000= 1.0
cell_remain= 4
n1= 73
temprory4=             h_geocode      dist  cell
1230  120810004031029  0.780696    26
RHS= 120810004031029
C000= 25.0
cell_remain= 1
n1= 74
temprory4=             h_geocode      dist  cell
7121  120810005041004  0.076106    30
RHS= 120810005041004
C000= 3.0
cell_remain= 27
n1= 75
temprory4=             h_geocode      dist  cell
9705  120810007043022  0.111557     3
RHS= 120810007043022
C000= 1.0
cell_remain= 2
n1= 76
temprory4=             h_geocode      dist  cell
5716  120710403015014  0.840253    20
RHS= 120710403015014
C000= 3.0
cell_remain= 17
n1= 77
temprory4=             h_geocode      dist  cell
1114  120710104042054  0.445759    19
RHS= 120710104042054
C000= 16.0
cell_remain= 3
n1= 78
temprory4=            h_geocode      dist  cell
885  120210113031004  4.516759    17
RHS= 120210113031004
C000= 15.0
cell_remain= 2
n1= 79
temprory4=             h_geocode      dist  cell
7071  120879704004007  0.079624     9
RHS= 120879704004007
C000= 5.0
cell_remain= 4
n1= 80
temprory4=             h_geocode      dist  cell
6725  120710401091003  0.650327     5
RHS= 120710401091003
C000= 1.0
cell_remain= 4
n1= 81
temprory4=             h_geocode       dist  cell
5271  120879727001037  22.032436    11
RHS= 120879727001037
C000= 8.0
cell_remain= 3
n1= 82
temprory4=             h_geocode      dist  cell
9367  121150027421019  0.583906    10
RHS= 121150027421019
C000= 5.0
cell_remain= 5
n1= 83
temprory4=             h_geocode      dist  cell
2880  120710403131099  2.872092    10
RHS= 120710403131099
C000= 9.0
cell_remain= 1
n1= 84
temprory4=             h_geocode      dist  cell
4042  121150027423082  0.613202    15
RHS= 121150027423082
C000= 14.0
cell_remain= 1
n1= 85
temprory4=              h_geocode     dist  cell
11873  121150027451004  0.27057     5
RHS= 121150027451004
C000= 3.0
cell_remain= 2
n1= 86
temprory4=             h_geocode      dist  cell
3420  120710101072008  0.165399     3
RHS= 120710101072008
C000= 2.0
cell_remain= 1
n1= 87
temprory4=              h_geocode      dist  cell
10031  120810008143005  0.444004    81
RHS= 120810008143005
C000= 1.0
cell_remain= 80
n1= 88
temprory4=             h_geocode       dist  cell
1594  120879710022010  40.535171    56
RHS= 120879710022010
C000= 27.0
cell_remain= 29
n1= 89
temprory4=             h_geocode      dist  cell
1692  120710102064065  0.281762    10
RHS= 120710102064065
C000= 9.0
cell_remain= 1
n1= 90
temprory4=             h_geocode      dist  cell
3072  120710402072026  0.671925    15
RHS= 120710402072026
C000= 8.0
cell_remain= 7
n1= 91
temprory4=           h_geocode      dist  cell
31  120150201041023  3.426544    32
RHS= 120150201041023
C000= 26.0
cell_remain= 6
n1= 92
temprory4=             h_geocode      dist  cell
7157  120710402051029  0.094582     2
RHS= 120710402051029
C000= 1.0
cell_remain= 1
n1= 93
temprory4=            h_geocode      dist  cell
774  120710104182007  0.383568   124
RHS= 120710104182007
C000= 25.0
cell_remain= 99
n1= 94
temprory4=             h_geocode      dist  cell
8069  120710403142108  0.325147     2
RHS= 120710403142108
C000= 1.0
cell_remain= 1
n1= 95
temprory4=             h_geocode     dist  cell
2689  120710502062019  0.09306    18
RHS= 120710502062019
C000= 10.0
cell_remain= 8
n1= 96
temprory4=             h_geocode      dist  cell
6178  120710401384028  1.871276     3
RHS= 120710401384028
C000= 2.0
cell_remain= 1
n1= 97
temprory4=             h_geocode       dist  cell
2755  120879727003011  38.160502    33
RHS= 120879727003011
C000= 16.0
cell_remain= 17
n1= 98
temprory4=              h_geocode      dist  cell
13440  121150027451058  0.185187     6
RHS= 121150027451058
C000= 2.0
cell_remain= 4
n1= 99
temprory4=             h_geocode      dist  cell
8908  120879709001054  0.323432    11
RHS= 120879709001054
C000= 3.0
cell_remain= 8
n1= 100
temprory4=             h_geocode      dist  cell
5190  121150027361005  0.214071    12
RHS= 121150027361005
C000= 11.0
cell_remain= 1
n1= 101
temprory4=             h_geocode      dist  cell
3182  120710403101007  0.611974    15
RHS= 120710403101007
C000= 8.0
cell_remain= 7
n1= 102
temprory4=             h_geocode     dist  cell
2106  120710005023025  0.70952     5
RHS= 120710005023025
C000= 4.0
cell_remain= 1
n1= 103
temprory4=             h_geocode      dist  cell
7920  120879707002022  0.291876     5
RHS= 120879707002022
C000= 4.0
cell_remain= 1
n1= 104
temprory4=             h_geocode      dist  cell
4763  120710104153013  0.175064     7
RHS= 120710104153013
C000= 2.0
cell_remain= 5
n1= 105
temprory4=              h_geocode      dist  cell
15231  121150027423090  0.253328     6
RHS= 121150027423090
C000= 1.0
cell_remain= 5
n1= 106
temprory4=             h_geocode       dist  cell
4033  120879715011023  35.075909    14
RHS= 120879715011023
C000= 11.0
cell_remain= 3
n1= 107
temprory4=             h_geocode      dist  cell
2779  120710202011006  1.999654    10
RHS= 120710202011006
C000= 8.0
cell_remain= 2
n1= 108
temprory4=             h_geocode      dist  cell
8071  120710403142143  0.181171     5
RHS= 120710403142143
C000= 1.0
cell_remain= 4
n1= 109
temprory4=             h_geocode      dist  cell
3991  120710403142073  1.466732    11
RHS= 120710403142073
C000= 6.0
cell_remain= 5
n1= 110
temprory4=             h_geocode    dist  cell
5241  120710104041045  0.2904    11
RHS= 120710104041045
C000= 1.0
cell_remain= 10
n1= 111
temprory4=            h_geocode      dist  cell
846  120150301021074  0.279827     3
RHS= 120150301021074
C000= 2.0
cell_remain= 1
n1= 112
temprory4=           h_geocode      dist  cell
53  120150202042024  0.917029    16
RHS= 120150202042024
C000= 13.0
cell_remain= 3
n1= 113
temprory4=             h_geocode      dist  cell
2376  120710403101017  2.211001    12
RHS= 120710403101017
C000= 11.0
cell_remain= 1
n1= 114
temprory4=             h_geocode      dist  cell
1631  120710101112020  0.629836    23
RHS= 120710101112020
C000= 9.0
cell_remain= 14
n1= 115
temprory4=             h_geocode      dist  cell
1301  120710012042004  2.018624    34
RHS= 120710012042004
C000= 9.0
cell_remain= 25
n1= 116
temprory4=             h_geocode      dist  cell
4965  120710102102030  1.162534     4
RHS= 120710102102030
C000= 1.0
cell_remain= 3

n1= 117
temprory4=             h_geocode       dist  cell
6395  120879716001019  23.094909     8
RHS= 120879716001019
C000= 6.0
cell_remain= 2
n1= 118
temprory4=             h_geocode      dist  cell
1390  120710008001012  2.296151     9
RHS= 120710008001012
C000= 8.0
cell_remain= 1
n1= 119
temprory4=             h_geocode      dist  cell
4952  120710102092017  0.615713     2
RHS= 120710102092017
C000= 1.0
cell_remain= 1
n1= 120
temprory4=            h_geocode      dist  cell
777  120150210011049  0.274889     4
RHS= 120150210011049
C000= 2.0
cell_remain= 2
n1= 121
temprory4=             h_geocode      dist  cell
7848  120710403081111  0.095073     2
RHS= 120710403081111
C000= 1.0
cell_remain= 1
n1= 122
temprory4=             h_geocode      dist  cell
1774  120210101021020  0.232758    74
RHS= 120210101021020
C000= 1.0
cell_remain= 73
n1= 123
temprory4=             h_geocode      dist  cell
6794  120710403141146  0.962497     3
RHS= 120710403141146
C000= 2.0
cell_remain= 1
n1= 124
temprory4=             h_geocode      dist  cell
4484  120710403141133  0.825727     6
RHS= 120710403141133
C000= 5.0
cell_remain= 1
n1= 125
temprory4=             h_geocode      dist  cell
7345  120710402081092  0.320468     2
RHS= 120710402081092
C000= 1.0
cell_remain= 1
n1= 126
temprory4=             h_geocode      dist  cell
1278  120710402074028  1.600023    51
RHS= 120710402074028
C000= 19.0
cell_remain= 32
n1= 127
temprory4=             h_geocode      dist  cell
4488  120710403151058  0.278052    11
RHS= 120710403151058
C000= 5.0
cell_remain= 6
n1= 128
temprory4=             h_geocode      dist  cell
1935  120710101112000  0.380804    12
RHS= 120710101112000
C000= 7.0
cell_remain= 5
n1= 129
temprory4=             h_geocode      dist  cell
3385  120710104203024  0.220301     9
RHS= 120710104203024
C000= 5.0
cell_remain= 4
n1= 130
temprory4=             h_geocode      dist  cell
8643  120710503201006  0.415429     4
RHS= 120710503201006
C000= 1.0
cell_remain= 3
n1= 131
temprory4=             h_geocode      dist  cell
3674  120710401272015  0.091292     7
RHS= 120710401272015
C000= 6.0
cell_remain= 1
n1= 132
temprory4=            h_geocode      dist  cell
395  120150206021017  0.333683     5
RHS= 120150206021017
C000= 4.0
cell_remain= 1
n1= 133
temprory4=             h_geocode      dist  cell
1390  120710402123000  0.945252    33
RHS= 120710402123000
C000= 18.0
cell_remain= 15
n1= 134
temprory4=             h_geocode      dist  cell
7220  120710402055024  0.133501     5
RHS= 120710402055024
C000= 1.0
cell_remain= 4
n1= 135
temprory4=             h_geocode      dist  cell
1067  121150027231002  0.624201    48
RHS= 121150027231002
C000= 46.0
cell_remain= 2
n1= 136
temprory4=             h_geocode      dist  cell
1444  120150305012096  0.312412     6
RHS= 120150305012096
C000= 1.0
cell_remain= 5
n1= 137
temprory4=             h_geocode      dist  cell
1112  120710102062043  1.399331    18
RHS= 120710102062043
C000= 15.0
cell_remain= 3
n1= 138
temprory4=              h_geocode      dist  cell
11708  121150022031031  0.181157     4
RHS= 121150022031031
C000= 2.0
cell_remain= 2
n1= 139
temprory4=             h_geocode      dist  cell
7908  120879705002064  3.921932     5
RHS= 120879705002064
C000= 4.0
cell_remain= 1
n1= 140
temprory4=             h_geocode      dist  cell
6426  120710402113023  0.142305     3
RHS= 120710402113023
C000= 2.0
cell_remain= 1
n1= 141
temprory4=             h_geocode      dist  cell
4995  120810013002040  0.818865    11
RHS= 120810013002040
C000= 7.0
cell_remain= 4
n1= 142
temprory4=             h_geocode      dist  cell
8653  120710503203015  0.291535    30
RHS= 120710503203015
C000= 1.0
cell_remain= 29
n1= 143
temprory4=             h_geocode      dist  cell
4784  120879715021042  36.39188    11
RHS= 120879715021042
C000= 9.0
cell_remain= 2
n1= 144
temprory4=             h_geocode      dist  cell
2197  120710401201012  1.830909    81
RHS= 120710401201012
C000= 11.0
cell_remain= 70
n1= 145
temprory4=             h_geocode      dist  cell
3418  120710402072017  1.765039    11
RHS= 120710402072017
C000= 7.0
cell_remain= 4
n1= 146
temprory4=             h_geocode      dist  cell
7044  120810017011004  0.297976     7
RHS= 120810017011004
C000= 4.0
cell_remain= 3
n1= 147
temprory4=             h_geocode      dist  cell
3513  120710101091017  0.068312    40
RHS= 120710101091017
C000= 2.0
cell_remain= 38
n1= 148
temprory4=             h_geocode      dist  cell
7037  120810016041053  0.324087    16
RHS= 120810016041053
C000= 4.0
cell_remain= 12
n1= 149
temprory4=           h_geocode      dist  cell
54  120150105061015  0.449372     5
RHS= 120150105061015
C000= 4.0
cell_remain= 1
n1= 150
temprory4=             h_geocode      dist  cell
4800  121150027423049  1.997647    16
RHS= 121150027423049
C000= 12.0
cell_remain= 4
n1= 151
temprory4=             h_geocode      dist  cell
3996  120710401093009  0.317089    16
RHS= 120710401093009
C000= 5.0
cell_remain= 11
n1= 152
temprory4=             h_geocode      dist  cell
1303  120710101111039  0.747263    13
RHS= 120710101111039
C000= 12.0
cell_remain= 1
n1= 153
temprory4=           h_geocode      dist  cell
33  120150210032021  1.779663   101
RHS= 120150210032021
C000= 27.0
cell_remain= 74
n1= 154
temprory4=            h_geocode      dist  cell
145  120150105052049  0.107543     5
RHS= 120150105052049
C000= 1.0
cell_remain= 4
n1= 155
temprory4=             h_geocode      dist  cell
6967  120810014051040  0.030084     6
RHS= 120810014051040
C000= 4.0
cell_remain= 2
n1= 156
temprory4=            h_geocode      dist  cell
127  120150105032080  0.992963     2
RHS= 120150105032080
C000= 1.0
cell_remain= 1
n1= 157
temprory4=              h_geocode      dist  cell
11449  120810020203023  0.693511     2
RHS= 120810020203023
C000= 1.0
cell_remain= 1
n1= 158
temprory4=             h_geocode      dist  cell
3559  120710403151069  3.159947     8
RHS= 120710403151069
C000= 7.0
cell_remain= 1
n1= 159
temprory4=            h_geocode     dist  cell
683  120150204023049  0.85075     3
RHS= 120150204023049
C000= 1.0
cell_remain= 2
n1= 160
temprory4=            h_geocode      dist  cell
933  120710004022011  1.261698    23
RHS= 120710004022011
C000= 14.0
cell_remain= 9
n1= 161
temprory4=             h_geocode      dist  cell
8312  120810019142082  0.837377     4
RHS= 120810019142082
C000= 3.0
cell_remain= 1
n1= 162
temprory4=             h_geocode      dist  cell
7536  120710402122003  0.356597     2
RHS= 120710402122003
C000= 1.0
cell_remain= 1
n1= 163
temprory4=             h_geocode      dist  cell
1611  120810012022028  0.485313    27
RHS= 120810012022028
C000= 22.0
cell_remain= 5
n1= 164
temprory4=           h_geocode      dist  cell
67  120150206011033  0.488342    15
RHS= 120150206011033
C000= 13.0
cell_remain= 2
n1= 165
temprory4=             h_geocode      dist  cell
5559  120710402081174  0.903073    12
RHS= 120710402081174
C000= 3.0
cell_remain= 9
n1= 166
temprory4=            h_geocode      dist  cell
289  120150206011038  0.195559     6
RHS= 120150206011038
C000= 5.0
cell_remain= 1
n1= 167
temprory4=             h_geocode      dist  cell
1624  120710101111058  0.513652    15
RHS= 120710101111058
C000= 9.0
cell_remain= 6
n1= 168
temprory4=             h_geocode      dist  cell
9057  120810016022001  0.324233     8
RHS= 120810016022001
C000= 2.0
cell_remain= 6
n1= 169
temprory4=             h_geocode      dist  cell
1539  120710102071019  0.681082    11
RHS= 120710102071019
C000= 10.0
cell_remain= 1
n1= 170
temprory4=             h_geocode     dist  cell
4198  120810001053026  0.68558    13
RHS= 120810001053026
C000= 7.0
cell_remain= 6
n1= 171
temprory4=             h_geocode       dist  cell
5781  120879727003011  22.591173    17
RHS= 120879727003011
C000= 7.0
cell_remain= 10
n1= 172
temprory4=             h_geocode      dist  cell
8970  120810014042014  0.108065    11
RHS= 120810014042014
C000= 2.0
cell_remain= 9
n1= 173
temprory4=             h_geocode      dist  cell
6816  120710403152028  0.198924     5
RHS= 120710403152028
C000= 2.0
cell_remain= 3
n1= 174
temprory4=             h_geocode      dist  cell
1793  120710302024018  0.294608    37
RHS= 120710302024018
C000= 13.0
cell_remain= 24
n1= 175
temprory4=             h_geocode      dist  cell
8907  120879721002018  3.272144     4

RHS= 120879721002018
C000= 3.0
cell_remain= 1
n1= 176
temprory4=             h_geocode       dist  cell
3131  120879710022010  61.082977    29
RHS= 120879710022010
C000= 14.0
cell_remain= 15
n1= 177
temprory4=             h_geocode      dist  cell
4461  121150018042038  0.533031    14
RHS= 121150018042038
C000= 11.0
cell_remain= 3
n1= 178
temprory4=             h_geocode      dist  cell
6355  120710402093015  0.793183     7
RHS= 120710402093015
C000= 2.0
cell_remain= 5
n1= 179
temprory4=             h_geocode      dist  cell
3639  120710502051036  0.205927    11
RHS= 120710502051036
C000= 7.0
cell_remain= 4
n1= 180
temprory4=            h_geocode      dist  cell
200  120150204022079  1.883094    10
RHS= 120150204022079
C000= 6.0
cell_remain= 4
n1= 181
temprory4=             h_geocode       dist  cell
1978  120879715021031  36.411214    57
RHS= 120879715021031
C000= 22.0
cell_remain= 35
n1= 182
temprory4=             h_geocode      dist  cell
5510  120710402072026  0.234088     7
RHS= 120710402072026
C000= 3.0
cell_remain= 4
n1= 183
temprory4=             h_geocode      dist  cell
5550  120710402081164  0.753071     5
RHS= 120710402081164
C000= 3.0
cell_remain= 2
n1= 184
temprory4=             h_geocode      dist  cell
5568  120710402093001  0.578411     5
RHS= 120710402093001
C000= 3.0
cell_remain= 2
n1= 185
temprory4=            h_geocode      dist  cell
263  120150202061027  0.093002     5
RHS= 120150202061027
C000= 3.0
cell_remain= 2
n1= 186
temprory4=             h_geocode      dist  cell
1836  120810007042031  1.019416    24
RHS= 120810007042031
C000= 18.0
cell_remain= 6
n1= 187
temprory4=             h_geocode       dist  cell
6361  120879709001054  21.737162     8
RHS= 120879709001054
C000= 6.0
cell_remain= 2
n1= 188
temprory4=           h_geocode     dist  cell
98  120150302014001  0.78819    27
RHS= 120150302014001
C000= 13.0
cell_remain= 14
n1= 189
temprory4=              h_geocode    dist  cell
10616  121150012023001  0.1036    12
RHS= 121150012023001
C000= 2.0
cell_remain= 10
n1= 190
temprory4=              h_geocode      dist  cell
13509  121150027462083  1.556657     4
RHS= 121150027462083
C000= 2.0
cell_remain= 2
n1= 191
temprory4=            h_geocode      dist  cell
365  120150304022022  0.449748    19
RHS= 120150304022022
C000= 6.0
cell_remain= 13
n1= 192
temprory4=              h_geocode      dist  cell
11381  121150027342069  1.036414     4
RHS= 121150027342069
C000= 3.0
cell_remain= 1
n1= 193
temprory4=             h_geocode      dist  cell
6904  121150027402030  0.098536    11
RHS= 121150027402030
C000= 8.0
cell_remain= 3
n1= 194
temprory4=           h_geocode      dist  cell
74  120150202031037  0.423032     8
RHS= 120150202031037
C000= 7.0
cell_remain= 1
n1= 195
temprory4=             h_geocode      dist  cell
5290  120710401262048  0.098263    10
RHS= 120710401262048
C000= 3.0
cell_remain= 7
n1= 196
temprory4=           h_geocode      dist  cell
28  120150205012067  4.463499    50
RHS= 120150205012067
C000= 28.0
cell_remain= 22
n1= 197
temprory4=             h_geocode      dist  cell
1733  120710101091041  0.041932    21
RHS= 120710101091041
C000= 8.0
cell_remain= 13
n1= 198
temprory4=             h_geocode      dist  cell
5697  121150027401085  0.324929    12
RHS= 121150027401085
C000= 10.0
cell_remain= 2
n1= 199
temprory4=           h_geocode      dist  cell
48  120150204024024  1.824832    28
RHS= 120150204024024
C000= 15.0
cell_remain= 13
n1= 200
temprory4=            h_geocode      dist  cell
641  120710103074005  0.651295    30
RHS= 120710103074005
C000= 29.0
cell_remain= 1
n1= 201
temprory4=             h_geocode      dist  cell
7015  121150016023003  0.074516    24
RHS= 121150016023003
C000= 6.0
cell_remain= 18
n1= 202
temprory4=             h_geocode      dist  cell
6671  120710403082010  0.091319     3
RHS= 120710403082010
C000= 2.0
cell_remain= 1
n1= 203
temprory4=            h_geocode      dist  cell
391  120150301022091  0.626465    16
RHS= 120150301022091
C000= 5.0
cell_remain= 11
n1= 204
temprory4=           h_geocode      dist  cell
22  120150105061007  5.119498    24
RHS= 120150105061007
C000= 10.0
cell_remain= 14
n1= 205
temprory4=             h_geocode      dist  cell
7058  120879727001011  3.029471     7
RHS= 120879727001011
C000= 5.0
cell_remain= 2
n1= 206
temprory4=             h_geocode      dist  cell
7553  120710402123018  0.142431     2
RHS= 120710402123018
C000= 1.0
cell_remain= 1
n1= 207
temprory4=              h_geocode      dist  cell
11714  120879716002027  0.126398     4
RHS= 120879716002027
C000= 1.0
cell_remain= 3
n1= 208
temprory4=             h_geocode    dist  cell
1328  120710206003003  0.9329    20
RHS= 120710206003003
C000= 17.0
cell_remain= 3
n1= 209
temprory4=             h_geocode      dist  cell
5083  120710403131055  1.522043     5
RHS= 120710403131055
C000= 4.0
cell_remain= 1
n1= 210
temprory4=           h_geocode      dist  cell
89  120150105052002  0.241375     6
RHS= 120150105052002
C000= 2.0
cell_remain= 4
n1= 211
temprory4=             h_geocode      dist  cell
6677  120710403082105  0.365525     3
RHS= 120710403082105
C000= 2.0
cell_remain= 1
n1= 212
temprory4=             h_geocode      dist  cell
6854  120710401242023  0.142183     4
RHS= 120710401242023
C000= 1.0
cell_remain= 3
n1= 213
temprory4=            h_geocode      dist  cell
556  120710104041021  1.150275    77
RHS= 120710104041021
C000= 34.0
cell_remain= 43
n1= 214
temprory4=             h_geocode      dist  cell
1496  120710403152004  3.969306    20
RHS= 120710403152004
C000= 17.0
cell_remain= 3
n1= 215
temprory4=              h_geocode      dist  cell
11722  120879720001024  0.073776     3
RHS= 120879720001024
C000= 1.0
cell_remain= 2
n1= 216
temprory4=              h_geocode    dist  cell
13482  121150027461070  0.2563     8
RHS= 121150027461070
C000= 2.0
cell_remain= 6
n1= 217
temprory4=             h_geocode       dist  cell
6361  120879715011010  33.774068     7
RHS= 120879715011010
C000= 6.0
cell_remain= 1
n1= 218
temprory4=             h_geocode      dist  cell
3340  120810011071015  0.316344    24
RHS= 120810011071015
C000= 11.0
cell_remain= 13
n1= 219
temprory4=             h_geocode      dist  cell
3972  120710403131086  1.848915     7
RHS= 120710403131086
C000= 6.0
cell_remain= 1
n1= 220
temprory4=            h_geocode      dist  cell
491  120150203011143  0.390038     3
RHS= 120150203011143
C000= 1.0
cell_remain= 2
n1= 221
temprory4=            h_geocode      dist  cell
118  120150203021061  0.514879    10
RHS= 120150203021061
C000= 8.0
cell_remain= 2
n1= 222
temprory4=             h_geocode      dist  cell
6880  120710401243010  0.334657     4
RHS= 120710401243010
C000= 1.0
cell_remain= 3
n1= 223
temprory4=            h_geocode     dist  cell
943  120150209001037  0.09145     2
RHS= 120150209001037
C000= 1.0
cell_remain= 1
n1= 224
temprory4=            h_geocode      dist  cell
695  120150204024096  1.198563     4
RHS= 120150204024096
C000= 1.0
cell_remain= 3
n1= 225
temprory4=              h_geocode      dist  cell
10579  120810016043009  0.315392     2
RHS= 120810016043009
C000= 1.0
cell_remain= 1
n1= 226
temprory4=              h_geocode      dist  cell
10445  120810014042003  0.349341     5
RHS= 120810014042003
C000= 1.0
cell_remain= 4
n1= 227
temprory4=            h_geocode      dist  cell
321  120150302012005  1.195421     9
RHS= 120150302012005
C000= 6.0
cell_remain= 3
n1= 228
temprory4=             h_geocode      dist  cell
4244  120710402072004  2.710115     6
RHS= 120710402072004
C000= 5.0
cell_remain= 1
n1= 229
temprory4=              h_geocode      dist  cell
10212  120810011082041  0.106627     3
RHS= 120810011082041
C000= 1.0
cell_remain= 2
n1= 230
temprory4=             h_geocode      dist  cell
6357  120879710022010  3.997751    15
RHS= 120879710022010
C000= 6.0
cell_remain= 9
n1= 231
temprory4=            h_geocode      dist  cell
489  120150203011055  0.417391     2
RHS= 120150203011055
C000= 1.0
cell_remain= 1
n1= 232
temprory4=             h_geocode      dist  cell
1244  120150302013062  0.157795     2
RHS= 120150302013062
C000= 1.0
cell_remain= 1
n1= 233
temprory4=             h_geocode      dist  cell
1425  120150305012037  0.715686     4
RHS= 120150305012037
C000= 1.0
cell_remain= 3

n1= 234
temprory4=             h_geocode      dist  cell
2093  120710005021004  0.785403     7
RHS= 120710005021004
C000= 4.0
cell_remain= 3
n1= 235
temprory4=              h_geocode      dist  cell
14769  121150027363014  0.192129     3
RHS= 121150027363014
C000= 1.0
cell_remain= 2
n1= 236
temprory4=             h_geocode      dist  cell
5592  120810016043015  1.085637     7
RHS= 120810016043015
C000= 6.0
cell_remain= 1
n1= 237
temprory4=             h_geocode      dist  cell
9419  120810019141007  5.748603     8
RHS= 120810019141007
C000= 2.0
cell_remain= 6
n1= 238
temprory4=            h_geocode      dist  cell
124  120150202032009  0.346765     5
RHS= 120150202032009
C000= 4.0
cell_remain= 1
n1= 239
temprory4=              h_geocode      dist  cell
12740  121150027311015  0.260966    85
RHS= 121150027311015
C000= 2.0
cell_remain= 83
n1= 240
temprory4=             h_geocode      dist  cell
2486  120210111071042  0.584387     3
RHS= 120210111071042
C000= 2.0
cell_remain= 1
n1= 241
temprory4=             h_geocode      dist  cell
2162  120210106022002  0.813347     8
RHS= 120210106022002
C000= 2.0
cell_remain= 6
n1= 242
temprory4=              h_geocode      dist  cell
11881  121150024041042  0.168193    14
RHS= 121150024041042
C000= 2.0
cell_remain= 12
n1= 243
temprory4=             h_geocode      dist  cell
7107  120710401384000  0.130026     2
RHS= 120710401384000
C000= 1.0
cell_remain= 1
n1= 244
temprory4=             h_geocode     dist  cell
5141  120810020231009  0.84535    10
RHS= 120810020231009
C000= 8.0
cell_remain= 2
n1= 245
temprory4=              h_geocode      dist  cell
10197  120810011082004  0.304351     2
RHS= 120810011082004
C000= 1.0
cell_remain= 1
n1= 246
temprory4=             h_geocode      dist  cell
6308  120710402081061  0.569443    24
RHS= 120710402081061
C000= 2.0
cell_remain= 22
n1= 247
temprory4=             h_geocode      dist  cell
2485  120210111071021  0.313297     3
RHS= 120210111071021
C000= 2.0
cell_remain= 1
n1= 248
temprory4=             h_geocode      dist  cell
2859  120710403151056  0.814269    10
RHS= 120710403151056
C000= 9.0
cell_remain= 1
n1= 249
temprory4=            h_geocode      dist  cell
516  120150204024096  1.291289     3
RHS= 120150204024096
C000= 2.0
cell_remain= 1
n1= 250
temprory4=             h_geocode      dist  cell
7897  121150001021005  0.231311     5
RHS= 121150001021005
C000= 4.0
cell_remain= 1
n1= 251
temprory4=             h_geocode      dist  cell
5505  120710402073029  0.712459     4
RHS= 120710402073029
C000= 3.0
cell_remain= 1
n1= 252
temprory4=             h_geocode    dist  cell
8651  120710503222007  0.6677   239
RHS= 120710503222007
C000= 1.0
cell_remain= 238
n1= 253
temprory4=            h_geocode      dist  cell
200  120150203021063  0.091516     9
RHS= 120150203021063
C000= 5.0
cell_remain= 4
n1= 254
temprory4=             h_geocode      dist  cell
8893  120710601021004  0.395709     3
RHS= 120710601021004
C000= 1.0
cell_remain= 2
n1= 255
temprory4=             h_geocode      dist  cell
9600  120810020113004  0.283837    30
RHS= 120810020113004
C000= 2.0
cell_remain= 28
n1= 256
temprory4=            h_geocode      dist  cell
515  120150204024078  0.549178     4
RHS= 120150204024078
C000= 2.0
cell_remain= 2
n1= 257
temprory4=             h_geocode      dist  cell
7316  120710503211004  0.173969     4
RHS= 120710503211004
C000= 2.0
cell_remain= 2
n1= 258
temprory4=             h_geocode      dist  cell
6727  120710403121062  0.546886     3
RHS= 120710403121062
C000= 2.0
cell_remain= 1
n1= 259
temprory4=             h_geocode      dist  cell
8154  120810006011013  0.328058     5
RHS= 120810006011013
C000= 2.0
cell_remain= 3
n1= 260
temprory4=            h_geocode      dist  cell
692  120710901002008  2.033529    76
RHS= 120710901002008
C000= 45.0
cell_remain= 31
n1= 261
temprory4=             h_geocode      dist  cell
3021  120210111091023  0.471114    10
RHS= 120210111091023
C000= 1.0
cell_remain= 9
n1= 262
temprory4=             h_geocode      dist  cell
1722  120210108082011  0.591719    11
RHS= 120210108082011
C000= 4.0
cell_remain= 7
n1= 263
temprory4=             h_geocode      dist  cell
6791  120710401212041  0.197743    11
RHS= 120710401212041
C000= 1.0
cell_remain= 10
n1= 264
temprory4=             h_geocode      dist  cell
3163  120810017053006  0.233178    14
RHS= 120810017053006
C000= 12.0
cell_remain= 2
n1= 265
temprory4=             h_geocode      dist  cell
1850  120210111071012  0.472936    14
RHS= 120210111071012
C000= 4.0
cell_remain= 10
n1= 266
temprory4=              h_geocode      dist  cell
12299  121150026012023  0.107953     3
RHS= 121150026012023
C000= 2.0
cell_remain= 1
n1= 267
temprory4=             h_geocode      dist  cell
5026  120810016022003  0.786061    13
RHS= 120810016022003
C000= 7.0
cell_remain= 6
n1= 268
temprory4=             h_geocode      dist  cell
7381  120710402093037  0.142561     2
RHS= 120710402093037
C000= 1.0
cell_remain= 1
n1= 269
temprory4=             h_geocode      dist  cell
6674  120710403083081  0.302751     4
RHS= 120710403083081
C000= 2.0
cell_remain= 2
n1= 270
temprory4=            h_geocode      dist  cell
926  120710003033018  0.526651    16
RHS= 120710003033018
C000= 14.0
cell_remain= 2
n1= 271
temprory4=             h_geocode      dist  cell
3776  120710019152010  0.607455    36
RHS= 120710019152010
C000= 1.0
cell_remain= 35
n1= 272
temprory4=            h_geocode      dist  cell
473  120150204011032  0.457295    19
RHS= 120150204011032
C000= 2.0
cell_remain= 17
n1= 273
temprory4=             h_geocode      dist  cell
8439  121150025072022  0.179644     8
RHS= 121150025072022
C000= 5.0
cell_remain= 3
n1= 274
temprory4=             h_geocode      dist  cell
3741  120710019102017  0.298013     2
RHS= 120710019102017
C000= 1.0
cell_remain= 1
n1= 275
temprory4=             h_geocode      dist  cell
8861  120879710022010  0.741171     9
RHS= 120879710022010
C000= 3.0
cell_remain= 6
n1= 276
temprory4=             h_geocode      dist  cell
4205  120710101102052  0.571806     4
RHS= 120710101102052
C000= 1.0
cell_remain= 3
n1= 277
temprory4=             h_geocode      dist  cell
8869  120879715021050  9.738874     9
RHS= 120879715021050
C000= 3.0
cell_remain= 6
n1= 278
temprory4=             h_geocode     dist  cell
4697  121150027332027  2.80723    39
RHS= 121150027332027
C000= 12.0
cell_remain= 27
n1= 279
temprory4=             h_geocode     dist  cell
5796  120710403082022  0.09064     9
RHS= 120710403082022
C000= 3.0
cell_remain= 6
n1= 280
temprory4=             h_geocode      dist  cell
1512  120710503122003  1.386621    31
RHS= 120710503122003
C000= 18.0
cell_remain= 13
n1= 281
temprory4=            h_geocode      dist  cell
346  120150303021007  0.822645    12
RHS= 120150303021007
C000= 6.0
cell_remain= 6
n1= 282
temprory4=             h_geocode      dist  cell
8914  121150002004010  0.220309     7
RHS= 121150002004010
C000= 3.0
cell_remain= 4
n1= 283
temprory4=           h_geocode      dist  cell
16  120150102001047  1.272362     3
RHS= 120150102001047
C000= 2.0
cell_remain= 1
n1= 284
temprory4=            h_geocode      dist  cell
485  120150204022000  0.349848     5
RHS= 120150204022000
C000= 2.0
cell_remain= 3
n1= 285
temprory4=             h_geocode      dist  cell
5703  120710403023017  0.325147     6
RHS= 120710403023017
C000= 3.0
cell_remain= 3
n1= 286
temprory4=             h_geocode      dist  cell
3756  120710019122006  0.378696     4
RHS= 120710019122006
C000= 1.0
cell_remain= 3
n1= 287
temprory4=              h_geocode      dist  cell
10545  120810016032020  0.321761     8
RHS= 120810016032020
C000= 1.0
cell_remain= 7
n1= 288
temprory4=              h_geocode      dist  cell
10928  121150026032014  0.210896     6
RHS= 121150026032014
C000= 3.0
cell_remain= 3
n1= 289
temprory4=             h_geocode      dist  cell
6973  120810015013017  0.655612     8
RHS= 120810015013017
C000= 4.0
cell_remain= 4
n1= 290
temprory4=              h_geocode      dist  cell
11619  120879705002061  1.054411     3
RHS= 120879705002061
C000= 1.0
cell_remain= 2
n1= 291
temprory4=             h_geocode      dist  cell
3827  120710402092013  1.564914     8
RHS= 120710402092013
C000= 6.0
cell_remain= 2
n1= 292
temprory4=            h_geocode      dist  cell
614  120150305013009  0.837704   165
RHS= 120150305013009
C000= 4.0
cell_remain= 161

n1= 293
temprory4=             h_geocode      dist  cell
3546  120710403152029  3.718658     8
RHS= 120710403152029
C000= 7.0
cell_remain= 1
n1= 294
temprory4=              h_geocode      dist  cell
11654  120879710021011  0.399813     2
RHS= 120879710021011
C000= 1.0
cell_remain= 1
n1= 295
temprory4=             h_geocode      dist  cell
3948  120710403101012  2.273638     7
RHS= 120710403101012
C000= 6.0
cell_remain= 1
n1= 296
temprory4=            h_geocode      dist  cell
455  120150305011044  0.771168    96
RHS= 120150305011044
C000= 5.0
cell_remain= 91
n1= 297
temprory4=             h_geocode     dist  cell
3189  120710019161004  0.65848     5
RHS= 120710019161004
C000= 2.0
cell_remain= 3
n1= 298
temprory4=             h_geocode      dist  cell
4057  120810007042048  0.141252    29
RHS= 120810007042048
C000= 8.0
cell_remain= 21
n1= 299
temprory4=            h_geocode      dist  cell
305  120150203021004  0.267676    10
RHS= 120150203021004
C000= 3.0
cell_remain= 7
n1= 300
temprory4=             h_geocode      dist  cell
3370  121150027213001  1.387061    50
RHS= 121150027213001
C000= 16.0
cell_remain= 34
n1= 301
temprory4=          h_geocode      dist  cell
8  120150105052017  3.416221    25
RHS= 120150105052017
C000= 24.0
cell_remain= 1
n1= 302
temprory4=             h_geocode      dist  cell
4125  120810018011015  0.248908    10
RHS= 120810018011015
C000= 9.0
cell_remain= 1
n1= 303
temprory4=           h_geocode      dist  cell
85  120150105032112  0.724267     3
RHS= 120150105032112
C000= 2.0
cell_remain= 1
n1= 304
temprory4=             h_geocode      dist  cell
2536  120710208023025  1.042419    14
RHS= 120710208023025
C000= 9.0
cell_remain= 5
n1= 305
temprory4=             h_geocode      dist  cell
2633  120710401212041  0.320276    10
RHS= 120710401212041
C000= 9.0
cell_remain= 1
n1= 306
temprory4=            h_geocode      dist  cell
101  120150203023003  1.544056    11
RHS= 120150203023003
C000= 9.0
cell_remain= 2
n1= 307
temprory4=             h_geocode      dist  cell
5806  120710403111001  0.595223     8
RHS= 120710403111001
C000= 3.0
cell_remain= 5
n1= 308
temprory4=            h_geocode     dist  cell
713  120150302021033  0.89178     5
RHS= 120150302021033
C000= 3.0
cell_remain= 2
n1= 309
temprory4=            h_geocode      dist  cell
145  120150105053039  0.778343     2
RHS= 120150105053039
C000= 1.0
cell_remain= 1
n1= 310
temprory4=             h_geocode      dist  cell
3473  120710102071025  1.217079     4
RHS= 120710102071025
C000= 3.0
cell_remain= 1
n1= 311
temprory4=          h_geocode      dist  cell
2  120150101001011  8.066292     5
RHS= 120150101001011
C000= 4.0
cell_remain= 1
n1= 312
temprory4=              h_geocode      dist  cell
10562  120810017011007  0.105078     7
RHS= 120810017011007
C000= 1.0
cell_remain= 6
n1= 313
temprory4=            h_geocode      dist  cell
151  120150105053193  0.667552     2
RHS= 120150105053193
C000= 1.0
cell_remain= 1
n1= 314
temprory4=            h_geocode      dist  cell
189  120150301022011  0.762669    22
RHS= 120150301022011
C000= 8.0
cell_remain= 14
n1= 315
temprory4=             h_geocode    dist  cell
7858  120879708003047  1.5544     6
RHS= 120879708003047
C000= 4.0
cell_remain= 2
n1= 316
temprory4=            h_geocode      dist  cell
435  120210001012029  0.122529     9
RHS= 120210001012029
C000= 6.0
cell_remain= 3
n1= 317
temprory4=             h_geocode      dist  cell
3264  121150027422003  2.747874    23
RHS= 121150027422003
C000= 17.0
cell_remain= 6
n1= 318
temprory4=            h_geocode      dist  cell
286  120150210011054  0.493184     7
RHS= 120150210011054
C000= 6.0
cell_remain= 1
n1= 319
temprory4=             h_geocode      dist  cell
4562  120710701023051  0.238876     7
RHS= 120710701023051
C000= 6.0
cell_remain= 1
n1= 320
temprory4=             h_geocode     dist  cell
2044  120810017052010  0.42001    32
RHS= 120810017052010
C000= 18.0
cell_remain= 14
n1= 321
temprory4=             h_geocode      dist  cell
1538  120210112081028  1.804896    74
RHS= 120210112081028
C000= 6.0
cell_remain= 68
n1= 322
temprory4=              h_geocode      dist  cell
11609  120879706001034  0.244842     2
RHS= 120879706001034
C000= 1.0
cell_remain= 1
n1= 323
temprory4=              h_geocode      dist  cell
10057  120879715021050  9.932004     6
RHS= 120879715021050
C000= 2.0
cell_remain= 4
n1= 324
temprory4=             h_geocode      dist  cell
1422  120150305012066  0.092852     2
RHS= 120150305012066
C000= 1.0
cell_remain= 1
n1= 325
temprory4=              h_geocode      dist  cell
14106  121150026021004  0.201981    16
RHS= 121150026021004
C000= 1.0
cell_remain= 15
n1= 326
temprory4=             h_geocode      dist  cell
5756  120710701022014  0.699934    19
RHS= 120710701022014
C000= 4.0
cell_remain= 15
n1= 327
temprory4=             h_geocode      dist  cell
2629  120710101081108  0.334646     6
RHS= 120710101081108
C000= 4.0
cell_remain= 2
n1= 328
temprory4=             h_geocode      dist  cell
4385  120710403041033  0.274311    21
RHS= 120710403041033
C000= 5.0
cell_remain= 16
n1= 329
temprory4=              h_geocode     dist  cell
15574  121150027472026  0.03732     2
RHS= 121150027472026
C000= 1.0
cell_remain= 1
n1= 330
temprory4=            h_geocode      dist  cell
529  120150203021054  0.550397     2
RHS= 120150203021054
C000= 1.0
cell_remain= 1
n1= 331
temprory4=             h_geocode      dist  cell
6592  120710701023018  0.868381     6
RHS= 120710701023018
C000= 3.0
cell_remain= 3
n1= 332
temprory4=            h_geocode      dist  cell
420  120150203031013  0.633688     5
RHS= 120150203031013
C000= 2.0
cell_remain= 3
n1= 333
temprory4=             h_geocode      dist  cell
4435  120710403102044  0.512503     6
RHS= 120710403102044
C000= 5.0
cell_remain= 1
n1= 334
temprory4=            h_geocode      dist  cell
295  120150204022019  1.356555     5
RHS= 120150204022019
C000= 4.0
cell_remain= 1
n1= 335
temprory4=             h_geocode      dist  cell
2903  120210109071006  0.170956     3
RHS= 120210109071006
C000= 1.0
cell_remain= 2
n1= 336
temprory4=             h_geocode      dist  cell
1448  120150305013168  0.273217     2
RHS= 120150305013168
C000= 1.0
cell_remain= 1
n1= 337
temprory4=           h_geocode     dist  cell
47  120150304011003  1.34699    23
RHS= 120150304011003
C000= 22.0
cell_remain= 1
n1= 338
temprory4=           h_geocode      dist  cell
57  120150103011060  0.415629     4
RHS= 120150103011060
C000= 1.0
cell_remain= 3
n1= 339
temprory4=            h_geocode      dist  cell
764  120150210011082  0.334034     4
RHS= 120150210011082
C000= 2.0
cell_remain= 2
n1= 340
temprory4=           h_geocode      dist  cell
91  120150304021018  0.332567    18
RHS= 120150304021018
C000= 14.0
cell_remain= 4
n1= 341
temprory4=             h_geocode      dist  cell
8521  121150027472060  0.713822     8
RHS= 121150027472060
C000= 6.0
cell_remain= 2
n1= 342
temprory4=             h_geocode      dist  cell
7897  121150003001024  0.153464     5
RHS= 121150003001024
C000= 4.0
cell_remain= 1
n1= 343
temprory4=            h_geocode      dist  cell
149  120150105053121  1.236963     3
RHS= 120150105053121
C000= 1.0
cell_remain= 2
n1= 344
temprory4=             h_geocode      dist  cell
5837  120710403151037  0.091404     4
RHS= 120710403151037
C000= 3.0
cell_remain= 1
n1= 345
temprory4=              h_geocode      dist  cell
12099  121150007003029  0.093078     8
RHS= 121150007003029
C000= 1.0
cell_remain= 7
n1= 346
temprory4=            h_geocode      dist  cell
427  120210104291008  0.251109   206
RHS= 120210104291008
C000= 16.0
cell_remain= 190
n1= 347
temprory4=             h_geocode      dist  cell
9068  121150006022011  0.393721    49
RHS= 121150006022011
C000= 3.0
cell_remain= 46
n1= 348
temprory4=             h_geocode      dist  cell
6871  120710501064001  0.494816    76
RHS= 120710501064001
C000= 2.0
cell_remain= 74
n1= 349
temprory4=             h_geocode      dist  cell
7160  120810019092009  0.442528    15
RHS= 120810019092009
C000= 4.0
cell_remain= 11
n1= 350
temprory4=             h_geocode      dist  cell
1489  120210108082020  0.328649    24
RHS= 120210108082020
C000= 5.0
cell_remain= 19
n1= 351
temprory4=             h_geocode      dist  cell
1042  120150301011110  0.566544     6
RHS= 120150301011110
C000= 1.0
cell_remain= 5

n1= 352
temprory4=             h_geocode      dist  cell
6642  120710403081104  0.730577     3
RHS= 120710403081104
C000= 2.0
cell_remain= 1
n1= 353
temprory4=             h_geocode      dist  cell
6905  121150027421037  1.350866    10
RHS= 121150027421037
C000= 8.0
cell_remain= 2
n1= 354
temprory4=            h_geocode      dist  cell
693  120150204024214  0.399776     3
RHS= 120150204024214
C000= 1.0
cell_remain= 2
n1= 355
temprory4=             h_geocode      dist  cell
5533  120710402093015  0.774455     5
RHS= 120710402093015
C000= 3.0
cell_remain= 2
n1= 356
temprory4=            h_geocode      dist  cell
949  120810014061001  1.355337    48
RHS= 120810014061001
C000= 37.0
cell_remain= 11
n1= 357
temprory4=            h_geocode      dist  cell
128  120150202062047  1.101374    10
RHS= 120150202062047
C000= 7.0
cell_remain= 3
n1= 358
temprory4=             h_geocode      dist  cell
6905  121150027422013  1.119138    13
RHS= 121150027422013
C000= 8.0
cell_remain= 5
n1= 359
temprory4=             h_geocode      dist  cell
6654  120710403083083  0.342601     4
RHS= 120710403083083
C000= 2.0
cell_remain= 2
n1= 360
temprory4=              h_geocode       dist  cell
10045  120879715021050  13.517958     4
RHS= 120879715021050
C000= 2.0
cell_remain= 2
n1= 361
temprory4=            h_geocode      dist  cell
222  120210005001002  0.401344    64
RHS= 120210005001002
C000= 12.0
cell_remain= 52
n1= 362
temprory4=            h_geocode      dist  cell
965  120150209002098  0.091697     4
RHS= 120150209002098
C000= 1.0
cell_remain= 3
n1= 363
temprory4=             h_geocode      dist  cell
3021  120710101091034  0.264536     5
RHS= 120710101091034
C000= 3.0
cell_remain= 2
n1= 364
temprory4=              h_geocode     dist  cell
10943  121150027101007  1.99931     8
RHS= 121150027101007
C000= 3.0
cell_remain= 5
n1= 365
temprory4=             h_geocode      dist  cell
6318  120710503211016  0.171282     4
RHS= 120710503211016
C000= 3.0
cell_remain= 1
n1= 366
temprory4=              h_geocode      dist  cell
10153  121150020163015  0.349399     4
RHS= 121150020163015
C000= 3.0
cell_remain= 1
n1= 367
temprory4=             h_geocode      dist  cell
3729  120710019102021  0.411218     2
RHS= 120710019102021
C000= 1.0
cell_remain= 1
n1= 368
temprory4=             h_geocode      dist  cell
7614  120810011082000  0.104822     5
RHS= 120810011082000
C000= 3.0
cell_remain= 2
n1= 369
temprory4=            h_geocode      dist  cell
767  120150210023024  0.389281    20
RHS= 120150210023024
C000= 2.0
cell_remain= 18
n1= 370
temprory4=              h_geocode       dist  cell
11718  120879727003075  44.999156     2
RHS= 120879727003075
C000= 1.0
cell_remain= 1
n1= 371
temprory4=            h_geocode      dist  cell
208  120150303011026  0.898489    17
RHS= 120150303011026
C000= 8.0
cell_remain= 9
n1= 372
temprory4=             h_geocode      dist  cell
8009  120710403142097  0.181755     2
RHS= 120710403142097
C000= 1.0
cell_remain= 1
n1= 373
temprory4=            h_geocode      dist  cell
149  120150105053121  1.273262     2
RHS= 120150105053121
C000= 1.0
cell_remain= 1
n1= 374
temprory4=             h_geocode      dist  cell
1051  120150305012096  0.791697     5
RHS= 120150305012096
C000= 2.0
cell_remain= 3
n1= 375
temprory4=            h_geocode      dist  cell
780  120150305011023  0.494162     7
RHS= 120150305011023
C000= 3.0
cell_remain= 4
n1= 376
temprory4=             h_geocode      dist  cell
4916  120710102083023  0.261873     2
RHS= 120710102083023
C000= 1.0
cell_remain= 1
n1= 377
temprory4=            h_geocode      dist  cell
774  121150007003006  0.483933    58
RHS= 121150007003006
C000= 53.0
cell_remain= 5
n1= 378
temprory4=              h_geocode      dist  cell
10039  120879715021031  8.969132    35
RHS= 120879715021031
C000= 2.0
cell_remain= 33
n1= 379
temprory4=             h_geocode      dist  cell
5762  120710303001013  2.985829     5
RHS= 120710303001013
C000= 2.0
cell_remain= 3
n1= 380
temprory4=            h_geocode      dist  cell
786  120150305012057  0.438275     4
RHS= 120150305012057
C000= 3.0
cell_remain= 1
n1= 381
temprory4=             h_geocode      dist  cell
8016  120710403151000  0.251879     3
RHS= 120710403151000
C000= 1.0
cell_remain= 2
n1= 382
temprory4=              h_geocode      dist  cell
14450  121150027231028  0.599366     5
RHS= 121150027231028
C000= 1.0
cell_remain= 4
n1= 383
temprory4=             h_geocode      dist  cell
5622  120810018023011  0.244102    13
RHS= 120810018023011
C000= 6.0
cell_remain= 7
n1= 384
temprory4=            h_geocode      dist  cell
145  120150105053058  0.088412     3
RHS= 120150105053058
C000= 1.0
cell_remain= 2
n1= 385
temprory4=             h_geocode      dist  cell
3726  120710019102005  0.487893     2
RHS= 120710019102005
C000= 1.0
cell_remain= 1
n1= 386
temprory4=             h_geocode      dist  cell
7820  120710403082119  0.352628     3
RHS= 120710403082119
C000= 1.0
cell_remain= 2
n1= 387
temprory4=           h_geocode      dist  cell
33  120150103011040  0.320475     3
RHS= 120150103011040
C000= 2.0
cell_remain= 1
n1= 388
temprory4=              h_geocode     dist  cell
15489  121150027462121  0.86836     2
RHS= 121150027462121
C000= 1.0
cell_remain= 1
n1= 389
temprory4=           h_geocode      dist  cell
13  120150103011068  0.154047    15
RHS= 120150103011068
C000= 5.0
cell_remain= 10
n1= 390
temprory4=             h_geocode      dist  cell
2063  120710401384003  5.843237    18
RHS= 120710401384003
C000= 12.0
cell_remain= 6
n1= 391
temprory4=             h_geocode      dist  cell
1328  120150303011021  0.241101     2
RHS= 120150303011021
C000= 1.0
cell_remain= 1
n1= 392
temprory4=            h_geocode      dist  cell
334  120210101082010  0.303945    53
RHS= 120210101082010
C000= 10.0
cell_remain= 43
n1= 393
temprory4=            h_geocode      dist  cell
140  120150105052069  0.437789     3
RHS= 120150105052069
C000= 1.0
cell_remain= 2
n1= 394
temprory4=           h_geocode      dist  cell
82  120150204013026  2.970047    15
RHS= 120150204013026
C000= 11.0
cell_remain= 4
n1= 395
temprory4=          h_geocode      dist  cell
8  120150105052009  1.822689    59
RHS= 120150105052009
C000= 20.0
cell_remain= 39

In [129]:
select_2030_hgeocode_geo4_3_1_geo2.rename(columns = {'cell':'cell_x','geometry_x':'geometry_x1','geometry_y':'geometry_y1'}, inplace = True)
select_2030_hgeocode_geo4_3_1_geo2

,h_geocode,geometry_x1,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS18,CNS19,CNS20,cell_x,w_geocode,geometry_y1,dist,centr_x_co,h_geocode_x,dist_x
0,120879718001022,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",3.0,0.0,2.0,1.0,2.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",0.631994,"(24.567331297140306, -81.73018543710354)",120879720002005,2.646203
89,120879719003003,"POLYGON ((-81.76164 24.56620, -81.76155 24.566...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.75942 24.57020, -81.75927 24.570...",0.275114,"(24.56654979307335, -81.75848011676781)",120879719003005,0.465509
221,120879720003001,"POLYGON ((-81.77867 24.55585, -81.77860 24.555...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.77687 24.55700, -81.77674 24.557...",0.344982,"(24.55379872565682, -81.77423283950421)",120879720001005,0.558742
322,120710103064008,"POLYGON ((-81.96485 26.64868, -81.96481 26.648...",14.0,2.0,7.0,5.0,13.0,1.0,0.0,0.0,...,2.0,0.0,0.0,5.0,1.207101e+14,"POLYGON ((-81.95863 26.63968, -81.95862 26.640...",0.322215,"(26.64349915458726, -81.96157126866642)",120710103064023,0.712168
424,121150027142000,"POLYGON ((-82.43564 27.13785, -82.43560 27.138...",6.0,1.0,3.0,2.0,6.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,1.211500e+14,"POLYGON ((-82.42548 27.14909, -82.42516 27.149...",0.687964,"(27.1430981901613, -82.42181956145436)",121150027142018,0.840429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,120150303013030,"POLYGON ((-82.34240 26.93723, -82.34240 26.937...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.211138e+14,None,NaN,"(26.93761298178636, -82.34180269963774)",120150303011021,0.241101
3521,120210101082002,"POLYGON ((-81.79477 26.29432, -81.79450 26.294...",10.0,10.0,0.0,0.0,10.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,1.210103e+14,None,NaN,"(26.293580091263486, -81.79463804289828)",120210101082010,0.303945
3522,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,"(26.86072744671804, -82.0168655661004)",120150105052069,0.437789
3523,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",11.0,0.0,11.0,0.0,11.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.209502e+14,None,NaN,"(27.004866401536365, -82.20261830319743)",120150204013026,2.970047
3524,120150105052037,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",20.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,...,2.0,0.0,0.0,1.0,1.209502e+14,None,NaN,"(26.866524742515672, -82.00328806014292)",120150105052009,1.822689

In [130]:
select_2030_hgeocode_geo4_3_1_geo2[select_2030_hgeocode_geo4_3_1_geo2['h_geocode']==10030102001033]

Empty GeoDataFrame
Columns: [h_geocode, geometry_x1, C000, CA01, CA02, CA03, CR01, CR02, CR03, CR04, CR05, CR07, CE01, CE02, CE03, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, cell_x, w_geocode, geometry_y1, dist, centr_x_co, h_geocode_x, dist_x]
Index: []

[0 rows x 50 columns]

In [131]:
select_2030_hgeocode_geo4_3_1_geo2.rename(columns = {'cell':'cell_x','geometry_x':'geometry_x1','geometry_y':'geometry_y1'}, inplace = True)
select_2030_hgeocode_geo4_3_1_geo2

,h_geocode,geometry_x1,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS18,CNS19,CNS20,cell_x,w_geocode,geometry_y1,dist,centr_x_co,h_geocode_x,dist_x
0,120879718001022,"POLYGON ((-81.73758 24.57436, -81.73680 24.574...",3.0,0.0,2.0,1.0,2.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.73600 24.56951, -81.73600 24.569...",0.631994,"(24.567331297140306, -81.73018543710354)",120879720002005,2.646203
89,120879719003003,"POLYGON ((-81.76164 24.56620, -81.76155 24.566...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.75942 24.57020, -81.75927 24.570...",0.275114,"(24.56654979307335, -81.75848011676781)",120879719003005,0.465509
221,120879720003001,"POLYGON ((-81.77867 24.55585, -81.77860 24.555...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.208797e+14,"POLYGON ((-81.77687 24.55700, -81.77674 24.557...",0.344982,"(24.55379872565682, -81.77423283950421)",120879720001005,0.558742
322,120710103064008,"POLYGON ((-81.96485 26.64868, -81.96481 26.648...",14.0,2.0,7.0,5.0,13.0,1.0,0.0,0.0,...,2.0,0.0,0.0,5.0,1.207101e+14,"POLYGON ((-81.95863 26.63968, -81.95862 26.640...",0.322215,"(26.64349915458726, -81.96157126866642)",120710103064023,0.712168
424,121150027142000,"POLYGON ((-82.43564 27.13785, -82.43560 27.138...",6.0,1.0,3.0,2.0,6.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,1.211500e+14,"POLYGON ((-82.42548 27.14909, -82.42516 27.149...",0.687964,"(27.1430981901613, -82.42181956145436)",121150027142018,0.840429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,120150303013030,"POLYGON ((-82.34240 26.93723, -82.34240 26.937...",1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.211138e+14,None,NaN,"(26.93761298178636, -82.34180269963774)",120150303011021,0.241101
3521,120210101082002,"POLYGON ((-81.79477 26.29432, -81.79450 26.294...",10.0,10.0,0.0,0.0,10.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,1.210103e+14,None,NaN,"(26.293580091263486, -81.79463804289828)",120210101082010,0.303945
3522,120150105052077,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.206105e+14,None,NaN,"(26.86072744671804, -82.0168655661004)",120150105052069,0.437789
3523,120150204022186,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",11.0,0.0,11.0,0.0,11.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.209502e+14,None,NaN,"(27.004866401536365, -82.20261830319743)",120150204013026,2.970047
3524,120150105052037,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",20.0,0.0,20.0,0.0,20.0,0.0,0.0,0.0,...,2.0,0.0,0.0,1.0,1.209502e+14,None,NaN,"(26.866524742515672, -82.00328806014292)",120150105052009,1.822689

In [132]:
select_2030_hgeocode_geo4_3_1_geo2.rename(columns = {'h_geocode':'h_geocode_y'}, inplace = True)

In [133]:
select_2030_hgeocode_geo4_3_1_geo2 = select_2030_hgeocode_geo4_3_1_geo2.drop(['centr_x_co'], axis =1 )

In [134]:
select_hgeocode_geo5_6_

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS19,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,dist_x
0,1.207100e+14,1.207104e+14,120710012051002,2.0,1.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.761567,120710401171000,437.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",5.447355
35,1.211500e+14,1.211500e+14,121150023023000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.916516,121150023061010,7.0,"POLYGON ((-82.43367 27.11708, -82.43367 27.117...","POLYGON ((-82.42052 27.10943, -82.42051 27.109...","POLYGON ((-82.41329 27.12622, -82.41310 27.126...",2.208549
76,1.202101e+14,1.202101e+14,120210112043005,12.0,2.0,6.0,4.0,9.0,3.0,0.0,...,0.0,0.0,0.0,0.77274,120210113062003,14.0,"POLYGON ((-81.42547 26.41482, -81.42466 26.414...","POLYGON ((-81.41836 26.41846, -81.41740 26.418...","POLYGON ((-81.46519 26.43521, -81.46470 26.435...",4.918122
86,1.208797e+14,1.208797e+14,120879717003014,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.129322,120879718001011,89.0,"POLYGON ((-81.67570 24.60202, -81.67570 24.602...","POLYGON ((-81.66069 24.60108, -81.66053 24.601...","POLYGON ((-81.74231 24.58633, -81.74224 24.586...",7.984476
101,1.208100e+14,1.208100e+14,120810020254005,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.730409,120810020242010,44.0,"POLYGON ((-82.47852 27.50409, -82.47840 27.504...","POLYGON ((-82.47461 27.51143, -82.47454 27.511...","POLYGON ((-82.47844 27.51307, -82.47833 27.513...",0.109147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2329581,1.208100e+14,1.208100e+14,120810020183029,2.0,0.0,1.0,1.0,2.0,0.0,0.0,...,0.0,0.0,0.0,5.033827,120810020121004,56.0,"POLYGON ((-82.42543 27.48683, -82.42515 27.486...","POLYGON ((-82.45919 27.44140, -82.45919 27.442...","POLYGON ((-82.46830 27.44550, -82.46819 27.445...",0.783195
2329894,1.208100e+14,1.208100e+14,120810015023039,8.0,2.0,4.0,2.0,6.0,1.0,0.0,...,0.0,0.0,0.0,0.566279,120810015012012,24.0,"POLYGON ((-82.55902 27.51934, -82.55849 27.519...","POLYGON ((-82.56244 27.52125, -82.56139 27.524...","POLYGON ((-82.55752 27.53963, -82.55649 27.539...",1.657977
2329994,1.208100e+14,1.208100e+14,120810019142082,15.0,3.0,7.0,5.0,14.0,0.0,0.0,...,0.0,0.0,4.0,5.085242,120810019141037,26.0,"POLYGON ((-82.36136 27.55343, -82.36129 27.553...","POLYGON ((-82.36456 27.56590, -82.36438 27.566...","POLYGON ((-82.38413 27.64185, -82.38412 27.641...",10.390985
2330000,1.208100e+14,1.208100e+14,120810007043047,11.0,2.0,6.0,3.0,5.0,6.0,0.0,...,0.0,1.0,0.0,2.99863,120810001053014,249.0,"POLYGON ((-82.53952 27.49138, -82.53849 27.491...","POLYGON ((-82.56678 27.47713, -82.56306 27.477...","POLYGON ((-82.57124 27.47295, -82.57124 27.473...",0.594089
2330194,1.208100e+14,1.208100e+14,120810020102028,8.0,1.0,4.0,3.0,8.0,0.0,0.0,...,0.0,0.0,6.0,8.290817,120810020101013,28.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.16255 27.35193, -82.16252 27.355...",5.639469

In [135]:
len(select_2030_hgeocode_geo4_3_1_geo2)

396

In [136]:
import pandas as pd 
select_hgeocode_geo5_6=pd.concat([select_hgeocode_geo5_6_, select_2030_hgeocode_geo4_3_1_geo2], axis=0)
len(select_hgeocode_geo5_6)

7362

In [137]:
select_hgeocode_geo5_6['C000'].sum()

37155.0

In [138]:
Emp_home_select_2030_new_values_merge_s['C000'].sum() #if the out of this cell = the out of previous cell (correct)

37155.0

In [139]:
select_hgeocode_geo5_6 = select_hgeocode_geo5_6.astype({"C000":'int64',"CNS01":'int64',"CNS02":'int64',"CNS03":'int64',
                                                       "CNS04":'int64',"CNS05":'int64',"CNS06":'int64',"CNS07":'int64',
                                                       "CNS08":'int64',"CNS09":'int64',"CNS10":'int64',"CNS11":'int64',
                                                       "CNS12":'int64',"CNS13":'int64',"CNS14":'int64',"CNS15":'int64',
                                                       "CNS16":'int64',"CNS17":'int64',"CNS18":'int64',"CNS19":'int64',
                                                       "CNS20":'int64', "CR01":'int64','CR02':'int64' ,'CR03' :'int64',
                                                       "CR04" :'int64', "CR05":'int64','CR07':'int64' ,"CA01" :'int64',
                                                       "CA02" :'int64',"CA03" :'int64',"CE01":'int64' ,"CE02" :'int64',
                                                       "CE03" :'int64',"CT01" :'int64',"CT02":'int64' ,"CD01" :'int64',
                                                       "CD02" :'int64',"CD03" :'int64',"CD04":'int64' ,"CS01" :'int64',
                                                       "CS02" :'int64'})

In [140]:
select_hgeocode_geo5_6

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,CNS19,CNS20,cell_x,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,dist_x
0,1.207100e+14,120710401171000.0,120710012051002,2,1,1,0,2,0,0,...,0,0,0.0,0.761567,1.207104e+14,437.0,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...","POLYGON ((-81.83893 26.60236, -81.83888 26.602...","POLYGON ((-81.83468 26.54684, -81.83188 26.553...",5.447355
35,1.211500e+14,121150023061010.0,121150023023000,1,0,1,0,1,0,0,...,0,0,0.0,0.916516,1.211500e+14,7.0,"POLYGON ((-82.43367 27.11708, -82.43367 27.117...","POLYGON ((-82.42052 27.10943, -82.42051 27.109...","POLYGON ((-82.41329 27.12622, -82.41310 27.126...",2.208549
76,1.202101e+14,120210113062003.0,120210112043005,12,2,6,4,9,3,0,...,0,0,0.0,0.77274,1.202101e+14,14.0,"POLYGON ((-81.42547 26.41482, -81.42466 26.414...","POLYGON ((-81.41836 26.41846, -81.41740 26.418...","POLYGON ((-81.46519 26.43521, -81.46470 26.435...",4.918122
86,1.208797e+14,120879718001011.0,120879717003014,1,0,1,0,1,0,0,...,0,0,0.0,1.129322,1.208797e+14,89.0,"POLYGON ((-81.67570 24.60202, -81.67570 24.602...","POLYGON ((-81.66069 24.60108, -81.66053 24.601...","POLYGON ((-81.74231 24.58633, -81.74224 24.586...",7.984476
101,1.208100e+14,120810020242010.0,120810020254005,1,0,1,0,1,0,0,...,0,0,0.0,0.730409,1.208100e+14,44.0,"POLYGON ((-82.47852 27.50409, -82.47840 27.504...","POLYGON ((-82.47461 27.51143, -82.47454 27.511...","POLYGON ((-82.47844 27.51307, -82.47833 27.513...",0.109147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3520,1.211138e+14,120150303011021,120150303013030,1,0,1,0,1,0,0,...,0,0,0.0,NaN,NaN,NaN,"POLYGON ((-82.34240 26.93723, -82.34240 26.937...",None,None,0.241101
3521,1.210103e+14,120210101082010,120210101082002,10,10,0,0,10,0,0,...,0,0,0.0,NaN,NaN,NaN,"POLYGON ((-81.79477 26.29432, -81.79450 26.294...",None,None,0.303945
3522,1.206105e+14,120150105052069,120150105052077,1,0,0,1,1,0,0,...,0,0,0.0,NaN,NaN,NaN,"POLYGON ((-82.01875 26.86052, -82.01875 26.861...",None,None,0.437789
3523,1.209502e+14,120150204013026,120150204022186,11,0,11,0,11,0,0,...,0,1,0.0,NaN,NaN,NaN,"POLYGON ((-82.20353 27.00496, -82.20348 27.005...",None,None,2.970047
3524,1.209502e+14,120150105052009,120150105052037,20,0,20,0,20,0,0,...,0,0,1.0,NaN,NaN,NaN,"POLYGON ((-82.00479 26.86726, -82.00421 26.867...",None,None,1.822689

In [141]:
# Emp_cells = Emp_cells_2030_old.copy()

In [142]:
Emp_cells

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
360,120150201011010,1898.0,491767073,76VV2X3Q+JV7-3-3-4-4,120150201012010,RES,RES1-1SNB,W,1.0,1999.0,...,0.18,0.08,-82.010330,27.004031,NaN,5.329113,17.483967,POINT (-82.01033 27.00403),015,1
379,120150202061034,1938.0,491915584,76VV2VFQ+CPH-4-2-3-3,120150202021046,RES,RES1-1SNB,W,1.0,1657.0,...,0.18,0.08,-82.110648,27.023557,NaN,4.227000,13.868111,POINT (-82.11065 27.02356),015,1
380,120150205012069,1941.0,491927247,76RVXV77+MPR-3-3-4-2,120150205012065,RES,RES1-1SNB,W,1.0,1462.0,...,0.18,0.08,-82.135730,26.964231,AE,0.900085,2.953035,POINT (-82.13573 26.96423),015,1
385,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.18,0.08,-82.306143,26.923544,NaN,3.585037,11.761934,POINT (-82.30614 26.92354),015,1
386,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.13,0.03,-81.728035,25.913643,NaN,3.590633,11.780292,POINT (-81.72803 25.91364),021,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544324,120710303001023,7362124.0,498226804,76RWP93W+264-0-0-0-0,120710303001022,RES,RES1-1SNB,W,1.0,510.0,...,0.17,0.05,-81.604428,26.702522,NaN,3.825020,12.549277,POINT (-81.60443 26.70252),071,1
2544591,120710302011004,7362643.0,498226048,76RWM7W6+V2V-0-0-0-0,120710302011005,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.739960,26.697237,AE,2.931039,9.616270,POINT (-81.73996 26.69724),071,1
2544592,120710302011004,7362644.0,498226050,76RWM7V5+6PJ-0-0-0-0,120710302011017,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.740725,26.693076,AE,3.146635,10.323605,POINT (-81.74073 26.69308),071,1
2544599,120710302012002,7362651.0,498226064,76RWM7R5+3WR-0-0-0-0,120710302011024,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.740242,26.690234,AE,1.498931,4.917752,POINT (-81.74024 26.69023),071,1
2544610,120710302011004,7362662.0,498226086,76RWM7X8+8GX-0-0-0-0,120710302011005,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.733640,26.698365,NaN,3.087558,10.129784,POINT (-81.73364 26.69836),071,1

In [143]:
Emp_cells2 =Emp_cells

In [144]:
# Emp_cells= Emp_cells.drop(['min_2030'],axis=1)

In [145]:
# Emp_cells2=Emp_cells2.drop(['row_num'],axis=1)

In [146]:
Emp_cells2 =  Emp_cells2.dropna(subset=['h_geocode'])
len(Emp_cells2)

386384

In [147]:
Emp_cells2 =  Emp_cells2.dropna(subset=['fd_id'])
len(Emp_cells2)

386384

In [148]:
Emp_cells2 = Emp_cells2.drop_duplicates(subset=['fd_id'])
len(Emp_cells2)

386384

In [149]:
Emp_cells2 = Emp_cells2.astype({"h_geocode":'int64',"fd_id":'int64'})

In [150]:
import pandas as pd
file = '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/DepthDamageFunction.xlsx'
xl = pd.ExcelFile(file)
print(xl.sheet_names)
WD_Coast = xl.parse('RES(Coastline)')

WD_Coast_final= WD_Coast.iloc[1:30,1:60].squeeze() #Buildings water damages

['RES(Riverline)', 'Other(Riverline)', 'RES(Coastline)', 'Sheet1', 'Sheet9', 'Recovery']

In [151]:
WD_Coast_final = WD_Coast_final.astype('float64')

In [152]:
# WD_Coast_final.to_pickle("WD_Coast_final.pkl")

In [153]:
select_hgeocode_geo5_6['C000'].sum()

37155

In [154]:
select_hgeocode_geo5_6['h_geocode_y']

0       120710012051002
35      121150023023000
76      120210112043005
86      120879717003014
101     120810020254005
             ...
3520    120150303013030
3521    120210101082002
3522    120150105052077
3523    120150204022186
3524    120150105052037
Name: h_geocode_y, Length: 7362, dtype: int64

In [155]:
select_hgeocode_geo5_6['h_geocode_y']

0       120710012051002
35      121150023023000
76      120210112043005
86      120879717003014
101     120810020254005
             ...
3520    120150303013030
3521    120210101082002
3522    120150105052077
3523    120150204022186
3524    120150105052037
Name: h_geocode_y, Length: 7362, dtype: int64

In [156]:
# select_hgeocode_geo5_6_try = select_hgeocode_geo5_6.drop_duplicates(subset=['h_geocode_x'])
# len(select_hgeocode_geo5_6_try)

In [157]:
select_hgeocode_geo5_6['h_geocode_x']

0       120710401171000.0
35      121150023061010.0
76      120210113062003.0
86      120879718001011.0
101     120810020242010.0
              ...
3520      120150303011021
3521      120210101082010
3522      120150105052069
3523      120150204013026
3524      120150105052009
Name: h_geocode_x, Length: 7362, dtype: object

In [158]:
select_hgeocode_geo5_6['h_geocode_x']

0       120710401171000.0
35      121150023061010.0
76      120210113062003.0
86      120879718001011.0
101     120810020242010.0
              ...
3520      120150303011021
3521      120210101082010
3522      120150105052069
3523      120150204013026
3524      120150105052009
Name: h_geocode_x, Length: 7362, dtype: object

In [159]:
Emp_cells2['fd_id'].max()

498226804

In [160]:
# select_hgeocode_geo5_6 = select_hgeocode_geo5_6.drop(['level_0'], axis = 1)

select_hgeocode_geo5_6 = select_hgeocode_geo5_6.reset_index()

In [161]:

select_hgeocode_geo5_6 = select_hgeocode_geo5_6.drop(['index'],axis=1)

In [162]:
dataframes_temp={}


# list of data frames
# Assume that the original dataframe is named 'original_df'
for i in range(0, 1): #0,90
    dataframes_temp[i] = select_hgeocode_geo5_6.copy()
    
# Convert the dictionary to a list of tuples
dataframes = list(dataframes_temp.values())
    

for k in range(0, 1):# 0,90
    dataframes[k] = dataframes[k].rename("{}_{}".format("{}_a",k).format)

# dictionary to save data frames
select_hgeocode_geo5_6_dic2_cells={} 

for key1, value1 in enumerate(dataframes):    
#     print('key1',key1)
#     print('value1',value1)

    select_hgeocode_geo5_6_dic2_cells[key1] = value1 # assigning data frame from list to key in dictionary

In [163]:
Emp_cells2 = Emp_cells2.reset_index()
Emp_cells2 = Emp_cells2.drop(['index'],axis=1)

In [164]:

dataframes_cells_temp={}


# list of data frames
# Assume that the original dataframe is named 'original_df'
for i in range(0, 1): #0,90
    dataframes_cells_temp[i] = Emp_cells2.copy()
    
# Convert the dictionary to a list of tuples
dataframes_cells = list(dataframes_cells_temp.values())
    

for k in range(0, 1): #0,90
    dataframes_cells[k] = dataframes_cells[k].rename("{}_{}".format("{}_a",k).format)

# dictionary to save data frames
Emp_cells2_dic={} 

for key1, value1 in enumerate(dataframes_cells):    
#     print('key1',key1)
#     print('value1',value1)

    Emp_cells2_dic[key1] = value1 # assigning data frame from list to key in dictionary

In [165]:
len(Emp_cells2_dic[0])

386384

In [166]:
len(Emp_cells2_dic[0]['fd_id'].unique())

386384

In [167]:

# for i in range(0,1):
#     Emp_cells2_dic[i] = Emp_cells2_dic[i][['h_geocode','fd_id','cell','geometry']]

In [168]:
import warnings
warnings.filterwarnings("ignore")

In [169]:
Emp_cells2['fd_id'].max()

498226804

In [170]:
def cells_calc_x_cells(Emp_home, Emp_cells):
    import time
    from scipy.interpolate import interp1d
    from iteration_utilities import deepflatten
    import random
    start = time.time()
    

    for i in range(0,len(Emp_home)):
        print('i=',i)
    

        temp22=[]
        temp30 = [[498226819,498226820,498226821]] #one number after Emp_cells2['row_num'].max()
        # temp25 = {}
        my_list = []
        my_dicts = {}
        Emp_home[i]['cells_used'] = ''
        for q in range (0,len(Emp_home[i])):
            temp22_1 = Emp_cells[i][Emp_cells[i]['h_geocode']== Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("h_geocode_x")]]
            list_temp30 = list(deepflatten(temp30, depth=1))
            temp22 = temp22_1.loc[~temp22_1['fd_id'].isin(list_temp30)]
            temp23 = sorted(temp22['fd_id'])
            if len(temp23) == 0:
#                 print('temp23=',temp23)
                temp24 = temp23
#                 print('len(temp24)=', len(temp24))
            if Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")] > len(temp23):
                temp24 = temp23
            else:
                temp24 = random.sample(population=temp23, k=Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")])
                temp24 = sorted(temp24)
            temp25 = temp22.loc[temp22['fd_id'].isin(temp24)]
            temp30.append(temp24)

            my_list.append(temp25)
            pd.DataFrame(Emp_home[i]).iloc[q,Emp_home[i].columns.get_loc("cells_used")]= len(temp24)

        cells2_2030=temp30 
        
    end = time.time()
    print(end - start)
    return cells2_2030
        
#         for key, value in en

In [171]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [172]:
def cells_calc_x(i, Emp_home, Emp_cells, cells2_2030):
    import time
    from scipy.interpolate import interp1d
    from iteration_utilities import deepflatten
#     start = time.time()
    
    
#     my_list_2=[]
#     my_list_3=[]
#     my_list_4=[]

#     for i in range(0,len(Emp_home)):   # 0 , len(Emp_home)
#     print('i=',i)


    temp22=[]
    temp30 = [[498226819,498226820,498226821]] #one number after Emp_cells2['row_num'].max()
    # temp25 = {}
    my_list = []
#         my_list_2=[]
#         my_list_3=[]
    my_dicts = {}
    Emp_home['cells_used'] = ''
    for q in range (0,len(Emp_home)):
        temp22_1 = Emp_cells[Emp_cells['h_geocode']== Emp_home.iloc[q,Emp_home.columns.get_loc("h_geocode_x")]]
        list_temp30 = list(deepflatten(temp30, depth=1))
        temp22 = temp22_1.loc[~temp22_1['fd_id'].isin(list_temp30)]
        temp23 = sorted(temp22['fd_id'])
        temp24 = cells2_2030[1:][q]
        temp25 = temp22.loc[temp22['fd_id'].isin(temp24)]
        temp30.append(temp24)
        my_list.append(temp25)
        pd.DataFrame(Emp_home).iloc[q,Emp_home.columns.get_loc("cells_used")]= len(temp24)

    for key, value in enumerate(my_list):
        my_dicts[key] = value

    Emp_home['C000_dmg']=''
    Emp_home['C000_dmg_mean']=''
    result_temp1 = []
    temp26 = []
    temp26_2 = []
    temp26_4 = []
    result_2 = []
    result_3 = []
    result_4 = []
    for k in range (0,len(Emp_home)):
        result_1 = []
        for value in my_dicts[k]["min_2030"]:
            result_temp1= value
            result_1.append(result_temp1)
        my_dicts[k]["SLR"] = result_1 #maybe replace result_1 with min_2030 (we don't need the previous 3 lines)
        my_dicts[k]['damage_SLR']=''
        for j in range(0, len(my_dicts[k])):
#                 print('row_num=', pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("row_num")])
#                 print('SLR=',pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] )
            if pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] == 0:
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = 0
            elif pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] > 7:
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = 100
            else: 
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = interp1d(WD_Coast_final['Depth.1']+pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("found_ht")]*0.3048,WD_Coast_final['R11N'],
                                                           bounds_error=False, fill_value=(0,1))(pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")])
#                 print('damage=',pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] )


        my_dicts[k] = my_dicts[k].astype({"damage_SLR":'float'})
        temp26 = len(my_dicts[k][my_dicts[k]["damage_SLR"]>50]) # damage is larger than 50%
        result_2.append(temp26)
        temp26_2 = (my_dicts[k][my_dicts[k]["damage_SLR"]>50])["damage_SLR"].mean()
        result_3.append(temp26_2)
        temp26_4 =my_dicts[k]["damage_SLR"]
        result_4.append(temp26_4)
    my_list_2.append(result_2)
    my_list_3.append(result_3)
    my_list_4.append(result_4)

#     end = time.time()
#     print(end - start)
    return my_list_2, my_list_3,my_list_4

In [173]:
# cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)

In [174]:
import os
from iteration_utilities import deepflatten

if os.path.exists('cells2_2030_for{0}.pickle'.format(year_1)):
    cells2_2030_temp = pd.read_pickle('cells2_2030_for{0}.pickle'.format(year_1))
    select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_cells_for{0}_Renters.pickle'.format(year_1))
    cells2_2030_temp2= cells2_2030_temp.values.tolist()
    
    cells2_2030=[]
    for i in range(0,len(cells2_2030_temp2)):
        df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
        df_temp = df_temp.astype(int)
        cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
        cells2_2030.append(cells2_2030_temp3)
    
else:
    cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
    pd.DataFrame(cells2_2030).to_pickle('cells2_2030_for{0}.pickle'.format(year_1))
    select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_cells_for{0}_Renters.pickle'.format(year_1))

i= 0
23.99872374534607

In [175]:
# select_hgeocode_geo5_6_dic2_cells[0]['C000']

In [176]:
# select_hgeocode_geo5_6_dic2_cells[0]['C000'].sum()

In [177]:
# select_hgeocode_geo5_6_dic2_cells[0]['cells_used'].sum()

In [178]:

from iteration_utilities import deepflatten

list_cells2_2030 = list(deepflatten(cells2_2030[1:], depth=1))

In [179]:
len(pd.DataFrame(list_cells2_2030)[0].unique())

29614

In [180]:
from iteration_utilities import deepflatten

list_cells2_2030 = list(deepflatten(cells2_2030, depth=1))
Emp_cells2_2030_dic_find = {}
for i in range(0, len(Emp_cells2_dic)):
    Emp_cells2_2030_dic_find[i] = Emp_cells2_dic[i].loc[Emp_cells2_dic[i]['fd_id'].isin(list_cells2_2030)]
len(Emp_cells2_2030_dic_find[0])

29614

In [181]:
Emp_cells2_2030_dic_find[0]

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
11_a_0,121150011012006,2117.0,492858865,76VV9F8C+JQJ-2-1-2-2,121150011012022,RES,RES1-1SNB,C,1.0,756.0,...,0.17,0.05,-82.528119,27.366591,NaN,8.452579,27.731561,POINT (-82.52812 27.36659),115,1
19_a_0,120210106053002,2289.0,493680983,76RW4773+4CH-4-4-4-4,120210106053002,RES,RES1-1SNB,W,1.0,1875.0,...,0.13,0.03,-81.746404,26.112817,NaN,2.016436,6.615603,POINT (-81.74640 26.11282),021,1
20_a_0,120210104011007,2417.0,494317506,76RW567C+WV7-3-3-4-3,120210104011009,RES,RES1-1SNB,W,1.0,2043.0,...,0.13,0.03,-81.777816,26.164790,NaN,1.686519,5.533199,POINT (-81.77782 26.16479),021,1
34_a_0,120210109062001,2667.0,495400878,76QWW9C4+P95-0-0-0-0,120210109031002,RES,RES1-1SNB,M,1.0,576.0,...,0.13,0.03,-81.644004,25.921763,NaN,1.454248,4.771156,POINT (-81.64400 25.92176),021,1
51_a_0,120810020173004,2780.0,495736994,76VVCH52+HMX-0-0-0-0,120810020171020,RES,RES1-1SNB,W,1.0,1388.0,...,0.17,0.04,-82.448256,27.408986,AE,1.227577,4.027483,POINT (-82.44826 27.40899),081,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386256_a_0,120710402113048,7359255.0,498223950,76RWJC82+GM4-0-0-0-0,120710402037052,RES,RES1-1SNB,M,1.0,1011.0,...,0.17,0.05,-81.598303,26.616257,NaN,7.485678,24.559312,POINT (-81.59830 26.61626),071,1
386323_a_0,120710402074001,7360060.0,498224771,76RWJCG2+QWG-0-0-0-0,120710402074001,RES,RES1-1SNB,W,1.0,637.0,...,0.17,0.05,-81.597658,26.626932,AE,6.779694,22.243092,POINT (-81.59766 26.62693),071,1
386361_a_0,120710302051004,7361575.0,498226246,76RWP73R+Q9V-0-0-0-0,120710302031002,RES,RES1-1SNB,W,1.0,1519.0,...,0.17,0.05,-81.709084,26.704479,NaN,2.988203,9.803816,POINT (-81.70908 26.70448),071,1
386366_a_0,120710303003023,7361648.0,498226323,76RWP8G7+XGR-0-0-0-0,120710303003036,RES,RES1-1SNB,M,1.0,1353.0,...,0.17,0.05,-81.686240,26.727499,NaN,3.338566,10.953300,POINT (-81.68624 26.72750),071,1
386372_a_0,120710402092013,7361700.0,498226382,76RWMCJH+X33-0-0-0-0,120710402092016,RES,RES1-1SNB,W,1.0,1595.0,...,0.17,0.05,-81.572337,26.682376,NaN,6.129911,20.111259,POINT (-81.57234 26.68238),071,1

In [182]:
Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find[0][['fd_id','geometry']]
Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find_1.reset_index()
Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find_1.drop(['index'],axis=1)
Emp_cells2_2030_dic_find_1

           fd_id                    geometry
0      492858865  POINT (-82.52812 27.36659)
1      493680983  POINT (-81.74640 26.11282)
2      494317506  POINT (-81.77782 26.16479)
3      495400878  POINT (-81.64400 25.92176)
4      495736994  POINT (-82.44826 27.40899)
...          ...                         ...
29609  498223950  POINT (-81.59830 26.61626)
29610  498224771  POINT (-81.59766 26.62693)
29611  498226246  POINT (-81.70908 26.70448)
29612  498226323  POINT (-81.68624 26.72750)
29613  498226382  POINT (-81.57234 26.68238)

[29614 rows x 2 columns]

In [183]:
zs2_dic_0 = Emp_cells2_2030_dic_find_1.copy()
zs2_dic_0 = zs2_dic_0.drop(['geometry'],axis=1)
zs2_dic_0.rename(columns={'row_num':'min'}, inplace=True)
zs2_dic_0['min']=0.0
zs2_dic_0

           fd_id  min
0      492858865  0.0
1      493680983  0.0
2      494317506  0.0
3      495400878  0.0
4      495736994  0.0
...          ...  ...
29609  498223950  0.0
29610  498224771  0.0
29611  498226246  0.0
29612  498226323  0.0
29613  498226382  0.0

[29614 rows x 2 columns]

In [184]:
# Create an empty list
zs2_dic_0_list = []

# Iterate over each row in the DataFrame
for index, row in zs2_dic_0.iterrows():
    # Append a dictionary to the list with the 'min' key and the row value
    zs2_dic_0_list.append({'min': row['min']})

In [185]:
# Get the list of all pickle file paths
Raster_file_paths = []
for k in range(0,6): 
    if k==2 or k==3 or k==4:
        continue
    else:
        print('k=',k)
        for x in range(0,40): 
            Raster_file_path = '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_{0}_{1}.tif'.format(k,x)
            Raster_file_paths.append(Raster_file_path)

# for i in range(0,1): #0,90
#     cell_open_read2[i] = pd.read_pickle(pickle_file_paths[i])

k= 0
k= 1
k= 5

In [186]:
len(Raster_file_paths)

120

In [314]:
#list_iterate is the number of hazards to be skipped calculations (zonal stats)

list_iterate=[]
for l in range(0,len(Raster_file_paths),8):
    list_iterate.append(l)
    list_iterate.append(l+1)
    list_iterate.append(l+2)
    list_iterate.append(l+3)
    list_iterate.append(l+4)
    list_iterate.append(l+5)
#     list_iterate.append(l+6)

In [315]:
# list_iterate

In [316]:
for l in range(0,len(Raster_file_paths)):
    if l in list_iterate:
        print('yes')
    else:
        print(l)

yes
yes
yes
yes
yes
yes
6
7
yes
yes
yes
yes
yes
yes
14
15
yes
yes
yes
yes
yes
yes
22
23
yes
yes
yes
yes
yes
yes
30
31
yes
yes
yes
yes
yes
yes
38
39
yes
yes
yes
yes
yes
yes
46
47
yes
yes
yes
yes
yes
yes
54
55
yes
yes
yes
yes
yes
yes
62
63
yes
yes
yes
yes
yes
yes
70
71
yes
yes
yes
yes
yes
yes
78
79
yes
yes
yes
yes
yes
yes
86
87
yes
yes
yes
yes
yes
yes
94
95
yes
yes
yes
yes
yes
yes
102
103
yes
yes
yes
yes
yes
yes
110
111
yes
yes
yes
yes
yes
yes
118
119

In [317]:
Raster_file_paths_new=[]
for i in range(0,len(Raster_file_paths)):
    if i not in list_iterate:
        Raster_file_paths_new_temp=Raster_file_paths[i]
        Raster_file_paths_new.append(Raster_file_paths_new_temp)

In [318]:
Raster_file_paths_new

['/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_6.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_7.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_14.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_15.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_22.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_23.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_30.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_31.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_38.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_0_39.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_6.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_7.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_14.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_15.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_22.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_23.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_30.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_31.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_38.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_1_39.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_6.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_7.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_14.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_15.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_22.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_23.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_30.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_31.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_38.tif',
 '/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/Raster_final_Florida/Florida_SLR_2030_5_39.tif']

In [319]:
new_list=[]
for i in range(0,len(Raster_file_paths)):
    if i not in list_iterate:
        new_list_temp=i
        new_list.append(new_list_temp)

In [320]:
new_list

[6,
 7,
 14,
 15,
 22,
 23,
 30,
 31,
 38,
 39,
 46,
 47,
 54,
 55,
 62,
 63,
 70,
 71,
 78,
 79,
 86,
 87,
 94,
 95,
 102,
 103,
 110,
 111,
 118,
 119]

In [321]:
from rasterstats import zonal_stats
import time
from joblib import Parallel, delayed
import joblib

def worker(i, Raster_file_paths_new, Emp_cells2_2030_dic_find_1):
    return zonal_stats(Emp_cells2_2030_dic_find_1, Raster_file_paths_new[i], stats=['min'])

def main():
    global zs2_dic
    zs2_dic = {}

    start = time.time()

    num_cores = joblib.cpu_count()
    results = Parallel(n_jobs=5)(delayed(worker)(i, Raster_file_paths_new, Emp_cells2_2030_dic_find_1) for i in range(0,len(Raster_file_paths_new)))

    # The 'retrieve' argument returns the results from all the jobs as soon as they are ready.
    zs2_dic = dict(enumerate(results))

    end = time.time()
    print(end - start)

    return zs2_dic

if __name__ == "__main__":
    zs2_dic = main()
#     print(zs2_dic)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

262.2367260456085

In [322]:
# from rasterstats import zonal_stats
# import time

# zs2_dic = {}

# start = time.time()
# for k in range(0,len(Raster_file_paths_new)):
#     print('k=',k)
# #     if k in list_iterate:
# #         print('Skipped')
# #         zs2_dic[k] = zs2_dic_0_list
# #     else:
#     zs2_dic[k] = zonal_stats(Emp_cells2_2030_dic_find_1, Raster_file_paths_new[k],
#                     stats=['min'])
# end = time.time()
# print(end - start)

In [323]:
len(pd.DataFrame(list_cells2_2030)[0].unique())

29617

In [324]:
import pandas as pd

import time

Emp_cells2_2030_dic_find_1_dic = {}
demstats_df2_dic = {}

start = time.time()
for k in range(0,len(Raster_file_paths_new)):
    print('k=',k)
    demstats_df2_dic[k] = pd.DataFrame(zs2_dic[k])
    demstats_df2_dic[k].rename(columns={'min':'min_2030'}, inplace=True)
    Emp_cells2_2030_dic_find_1_dic[k] = pd.concat([Emp_cells2_2030_dic_find_1, demstats_df2_dic[k]], axis=1)
    
end = time.time()
print(end - start)

k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.23199009895324707

In [325]:
# Emp_cells2_2030_dic_find_1_dic[89][Emp_cells2_2030_dic_find_1_dic[89]['min_2030']>0]

In [326]:
# Emp_cells2_2030_dic_find_1_dic[719].to_file('Emp_cells2_2030_dic_find_1_dic_719.shp')

In [327]:
import geopandas as gpd
#To read shapefile
fp13 = "/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/FL_Levee_polygon_min_H_calc.shp"
Emp_home_levee = gpd.read_file(fp13)

In [328]:
Emp_home_levee =  Emp_home_levee[['min_ht','geometry']]

In [329]:
cell_open_read3={}

for i in range(0,len(Raster_file_paths_new)):
    cell_open_read3[i] = Emp_cells2_2030_dic_find_1_dic[i][['min_2030','fd_id']]

In [330]:
Emp_cells2_dic[0].head()

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
0_a_0,120150201011010,1898.0,491767073,76VV2X3Q+JV7-3-3-4-4,120150201012010,RES,RES1-1SNB,W,1.0,1999.0,...,0.18,0.08,-82.010330,27.004031,NaN,5.329113,17.483967,POINT (-82.01033 27.00403),015,1
1_a_0,120150202061034,1938.0,491915584,76VV2VFQ+CPH-4-2-3-3,120150202021046,RES,RES1-1SNB,W,1.0,1657.0,...,0.18,0.08,-82.110648,27.023557,NaN,4.227000,13.868111,POINT (-82.11065 27.02356),015,1
2_a_0,120150205012069,1941.0,491927247,76RVXV77+MPR-3-3-4-2,120150205012065,RES,RES1-1SNB,W,1.0,1462.0,...,0.18,0.08,-82.135730,26.964231,AE,0.900085,2.953035,POINT (-82.13573 26.96423),015,1
3_a_0,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.18,0.08,-82.306143,26.923544,NaN,3.585037,11.761934,POINT (-82.30614 26.92354),015,1
4_a_0,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.13,0.03,-81.728035,25.913643,NaN,3.590633,11.780292,POINT (-81.72803 25.91364),021,1

In [331]:
# Emp_cells2_dic[0] = Emp_cells2_dic[0].drop(['min_2030'],axis=1)

In [332]:
Emp_cells2_dic_filter = {}
for i in range(0,1):
    Emp_cells2_dic_filter[i]=Emp_cells2_dic[i][['h_geocode','fd_id','found_ht','geometry','cell']]

In [333]:
import pandas as pd

Emp_cells2_dic2={}

for i in range(0,len(Raster_file_paths_new)):#0,90
    Emp_cells2_dic2[i] = pd.merge(Emp_cells2_dic_filter[0], cell_open_read3[i],  how='left', 
                    left_on=['fd_id'], right_on = ['fd_id'])

In [334]:
Emp_select_levee_120 = gpd.sjoin(Emp_cells2_dic2[len(Emp_cells2_dic2)-1], Emp_home_levee, op="intersects", how='left')
Emp_select_levee_120.head()

,h_geocode,fd_id,found_ht,geometry,cell,min_2030,index_right,min_ht
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN,NaN,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN,NaN,NaN
2,120150205012069,491927247,0.5,POINT (-82.13573 26.96423),1,NaN,NaN,NaN
3,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,NaN,NaN,NaN
4,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,NaN,NaN,NaN

In [335]:
Emp_select_levee_120[~Emp_select_levee_120['min_ht'].isna()][
    ~Emp_select_levee_120[~Emp_select_levee_120['min_ht'].isna()]
['min_2030'].isna()]

Empty GeoDataFrame
Columns: [h_geocode, fd_id, found_ht, geometry, cell, min_2030, index_right, min_ht]
Index: []

In [336]:
del Emp_select_levee_120

In [337]:
del cell_open_read3

In [338]:
del Emp_cells2_dic_filter

In [339]:
Emp_cells2_dic2[1]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120150205012069,491927247,0.5,POINT (-82.13573 26.96423),1,NaN
3,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,NaN
4,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,NaN
...,...,...,...,...,...,...
386379,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
386380,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
386381,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
386382,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
386383,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [340]:
Emp_cells2['geometry'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [341]:
# Emp_cells2[Emp_cells2['row_num']==162935]['geometry'][128557]

In [342]:
Emp_cells2_2030_dic_find_1

           fd_id                    geometry
0      492858865  POINT (-82.52812 27.36659)
1      493680983  POINT (-81.74640 26.11282)
2      494317506  POINT (-81.77782 26.16479)
3      495400878  POINT (-81.64400 25.92176)
4      495736994  POINT (-82.44826 27.40899)
...          ...                         ...
29609  498223950  POINT (-81.59830 26.61626)
29610  498224771  POINT (-81.59766 26.62693)
29611  498226246  POINT (-81.70908 26.70448)
29612  498226323  POINT (-81.68624 26.72750)
29613  498226382  POINT (-81.57234 26.68238)

[29614 rows x 2 columns]

In [343]:
# Emp_cells2_2030_dic_find_1.to_pickle('Emp_cells2_2030_dic_find_1.pickle')

In [344]:
def check_input_type(input):
    if isinstance(input, pd.DataFrame):
        return True
    elif isinstance(input, dict):
        return False
    else:
        return False
# checking input types
check_input_type(select_hgeocode_geo5_6)

True

In [345]:
def find_cells_SLR(select_hgeocode_geo5_6, Emp_cells2):
    from iteration_utilities import deepflatten
    from rasterstats import zonal_stats
    import time
    import os


    dataframes_temp={}



    # list of data frames
    for i in range(0, 1): #0,90
        dataframes_temp[i] = select_hgeocode_geo5_6.copy()

    # Convert the dictionary to a list of tuples
    dataframes = list(dataframes_temp.values())

    for k in range(0, 1):# 0,90
        dataframes[k] = dataframes[k].rename("{}_{}".format("{}_a",k).format)

    # dictionary to save data frames
    select_hgeocode_geo5_6_dic2_cells={} 

    for key1, value1 in enumerate(dataframes):    
        select_hgeocode_geo5_6_dic2_cells[key1] = value1 # assigning data frame from list to key in dictionary
        
     
    Emp_cells2 = Emp_cells2.reset_index()
    Emp_cells2 = Emp_cells2.drop(['index'],axis=1)
    
    Emp_cells2= Emp_cells2.drop(['min_2030'],axis=1)
    
    
    dataframes_cells_temp={}


    # list of data frames
    for i in range(0, 1): #0,90
        dataframes_cells_temp[i] = Emp_cells2.copy()

    # Convert the dictionary to a list of tuples
    dataframes_cells = list(dataframes_cells_temp.values())


    for k in range(0, 1): #0,90
        dataframes_cells[k] = dataframes_cells[k].rename("{}_{}".format("{}_a",k).format)

    # dictionary to save data frames
    Emp_cells2_dic={} 

    for key1, value1 in enumerate(dataframes_cells):    
        Emp_cells2_dic[key1] = value1 # assigning data frame from list to key in dictionary


#     for i in range(0,1):
#         Emp_cells2_dic[i] = Emp_cells2_dic[i][['h_geocode','row_num','cell','geometry']]
    
    if 'h_geocode_x' in select_hgeocode_geo5_6.columns:
        print('Yes')
        
        if 'loop_num' in select_hgeocode_geo5_6.columns:
            
            loop_num = select_hgeocode_geo5_6['loop_num'][0]


            if os.path.exists('cells2_2030_1_try{1}_for{0}.pickle'.format(year_1,loop_num)):
                cells2_2030_temp = pd.read_pickle('cells2_2030_1_try{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_cells{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
                cells2_2030_temp2= cells2_2030_temp.values.tolist()

                cells2_2030=[]
                for i in range(0,len(cells2_2030_temp2)):
                    df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                    df_temp = df_temp.astype(int)
                    cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                    cells2_2030.append(cells2_2030_temp3)
            else:
                cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
                pd.DataFrame(cells2_2030).to_pickle('cells2_2030_1_try{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_cells{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
        
        
        elif 'loop_num_2' in select_hgeocode_geo5_6.columns:
            
            loop_num = select_hgeocode_geo5_6['loop_num_2'][0]


            if os.path.exists('cells2_2030_3_try{1}_for{0}.pickle'.format(year_1,loop_num)):
                cells2_2030_temp = pd.read_pickle('cells2_2030_3_try{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_cells__{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
                cells2_2030_temp2= cells2_2030_temp.values.tolist()

                cells2_2030=[]
                for i in range(0,len(cells2_2030_temp2)):
                    df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                    df_temp = df_temp.astype(int)
                    cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                    cells2_2030.append(cells2_2030_temp3)
            else:
                cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
                pd.DataFrame(cells2_2030).to_pickle('cells2_2030_3_try{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_cells__{1}_for{0}_Renters.pickle'.format(year_1,loop_num))

        elif 'loop_num_3' in select_hgeocode_geo5_6.columns:
            
            loop_num = select_hgeocode_geo5_6['loop_num_3'][0]


            if os.path.exists('cells2_2030_4_{1}_for{0}.pickle'.format(year_1,loop_num)):
                cells2_2030_temp = pd.read_pickle('cells2_2030_4_{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_cells_4_{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
                cells2_2030_temp2= cells2_2030_temp.values.tolist()

                cells2_2030=[]
                for i in range(0,len(cells2_2030_temp2)):
                    df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                    df_temp = df_temp.astype(int)
                    cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                    cells2_2030.append(cells2_2030_temp3)
            else:
                cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
                pd.DataFrame(cells2_2030).to_pickle('cells2_2030_4_{1}_for{0}.pickle'.format(year_1,loop_num))
                select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_cells_4_{1}_for{0}_Renters.pickle'.format(year_1,loop_num))
        
        else: 
            if os.path.exists('cells2_2030_3_for{0}.pickle'.format(year_1)):
                cells2_2030_temp = pd.read_pickle('cells2_2030_3_for{0}.pickle'.format(year_1))
                select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_3cells_for{0}_Renters.pickle'.format(year_1))
                cells2_2030_temp2= cells2_2030_temp.values.tolist()

                cells2_2030=[]
                for i in range(0,len(cells2_2030_temp2)):
                    df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                    df_temp = df_temp.astype(int)
                    cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                    cells2_2030.append(cells2_2030_temp3)
            else:
                cells2_2030 =  cells_calc_x_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
                pd.DataFrame(cells2_2030).to_pickle('cells2_2030_3_for{0}.pickle'.format(year_1))
                select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_3cells_for{0}_Renters.pickle'.format(year_1))


                
    else: 
        print('No')
        if os.path.exists('cells2_2030_2_for{0}.pickle'.format(year_1)):
            cells2_2030_temp = pd.read_pickle('cells2_2030_2_for{0}.pickle'.format(year_1))
            select_hgeocode_geo5_6_dic2_cells= pd.read_pickle('select_hgeocode_geo5_6_dic2_2cells_for{0}_Renters.pickle'.format(year_1))
            cells2_2030_temp2= cells2_2030_temp.values.tolist()
    
            cells2_2030=[]
            for i in range(0,len(cells2_2030_temp2)):
                df_temp = pd.DataFrame(cells2_2030_temp2[i]).dropna()
                df_temp = df_temp.astype(int)
                cells2_2030_temp3 = list(deepflatten(df_temp.values.tolist(),depth=1))
                cells2_2030.append(cells2_2030_temp3)
        else:
            cells2_2030 =  cells_calc_cells(select_hgeocode_geo5_6_dic2_cells,Emp_cells2_dic)
            pd.DataFrame(cells2_2030).to_pickle('cells2_2030_2_for{0}.pickle'.format(year_1))
            select_hgeocode_geo5_6_dic2_cells[0].to_pickle('select_hgeocode_geo5_6_dic2_2cells_for{0}_Renters.pickle'.format(year_1))
    
    print('your here 1')
    
    
    list_cells2_2030 = list(deepflatten(cells2_2030[1:], depth=1))
    
    Emp_cells2_2030_dic_find = {}
    for i in range(0, len(Emp_cells2_dic)):
        Emp_cells2_2030_dic_find[i] = Emp_cells2_dic[i].loc[Emp_cells2_dic[i]['fd_id'].isin(list_cells2_2030)]    
    Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find[0][['fd_id','geometry']]
    Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find_1.reset_index()
    Emp_cells2_2030_dic_find_1 = Emp_cells2_2030_dic_find_1.drop(['index'],axis=1)
    
    print('your here 2')

    zs2_dic_0 = Emp_cells2_2030_dic_find_1.copy()
    zs2_dic_0 = zs2_dic_0.drop(['geometry'],axis=1)
    zs2_dic_0.rename(columns={'fd_id':'min'}, inplace=True)
    zs2_dic_0['min']=0.0
    # Create an empty list
    zs2_dic_0_list = []

    # Iterate over each row in the DataFrame
    for index, row in zs2_dic_0.iterrows():
        # Append a dictionary to the list with the 'min' key and the row value
        zs2_dic_0_list.append({'min': row['min']})

    
    zs2_dic = {}

    def worker(i, Raster_file_paths_new, Emp_cells2_2030_dic_find_1):
        return zonal_stats(Emp_cells2_2030_dic_find_1, Raster_file_paths_new[i], stats=['min'])
    
    def main():
        global zs2_dic
        zs2_dic = {}

        start = time.time()

        num_cores = joblib.cpu_count()
        results = Parallel(n_jobs=num_cores)(delayed(worker)(i, Raster_file_paths_new, Emp_cells2_2030_dic_find_1) for i in range(0,len(Raster_file_paths_new)))

        # The 'retrieve' argument returns the results from all the jobs as soon as they are ready.
        zs2_dic = dict(enumerate(results))

        end = time.time()
        print(end - start)

        return zs2_dic

    if __name__ == "__main__":
        zs2_dic = main()
    
    print('your here 3')

    
    Emp_cells2_2030_dic_find_1_dic = {}
    demstats_df2_dic = {}

    start = time.time()
    for k in range(0,len(Raster_file_paths_new)):
        print('k=',k)
        demstats_df2_dic[k] = pd.DataFrame(zs2_dic[k])
        demstats_df2_dic[k].rename(columns={'min':'min_2030'}, inplace=True)
        Emp_cells2_2030_dic_find_1_dic[k] = pd.concat([Emp_cells2_2030_dic_find_1, demstats_df2_dic[k]], axis=1)

    end = time.time()
    print(end - start)
    
    cell_open_read3={}

    for i in range(0,len(Raster_file_paths_new)):
        cell_open_read3[i] = Emp_cells2_2030_dic_find_1_dic[i][['min_2030','fd_id']]
        
    Emp_cells2_dic2={}
    Emp_select_levee_120={}

    for i in range(0,len(Raster_file_paths_new)):#0,90
        Emp_cells2_dic2[i] = pd.merge(Emp_cells2_dic[0], cell_open_read3[i],  how='left', 
                        left_on=['fd_id'], right_on = ['fd_id'])
        
        
    for i in range(0,len(Raster_file_paths_new)):#0,90
        Emp_select_levee_120[i] = gpd.sjoin(Emp_cells2_dic2[i], Emp_home_levee, op="intersects", how='left')
        Emp_select_levee_120[i]['zero']=0
        mask = Emp_select_levee_120[i]['min_ht'] > Emp_select_levee_120[i]['min_2030']
    
        # Update the 'min_2030' column with the values from 'min_ht' where the mask is True
        Emp_select_levee_120[i].loc[mask, 'min_2030'] = Emp_select_levee_120[i].loc[mask, 'zero']
        Emp_select_levee_120[i]=Emp_select_levee_120[i].drop(['index_right','min_ht','zero'],axis=1)
        
        Emp_cells2_dic2[i] = Emp_select_levee_120[i].copy()
        
        
    del Emp_select_levee_120
        

    del cell_open_read3
        
    dataframes2_temp={}

    if check_input_type(select_hgeocode_geo5_6_dic2_cells) :
        
        select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.reset_index()

        if 'index' in select_hgeocode_geo5_6_dic2_cells.columns:
            select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.drop(['index'],axis=1)
        if 'level_0' in select_hgeocode_geo5_6_dic2_cells.columns:
            select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.drop(['level_0'],axis=1)

        # list of data frames
        # Assume that the original dataframe is named 'original_df'
        for i in range(0, len(new_list)):
            dataframes2_temp[i] = select_hgeocode_geo5_6_dic2_cells.copy()

        
    else:

        select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].reset_index()

        if 'index' in select_hgeocode_geo5_6_dic2_cells[0].columns:
            select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].drop(['index'],axis=1)
        if 'level_0' in select_hgeocode_geo5_6_dic2_cells[0].columns:
            select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].drop(['level_0'],axis=1)

        # list of data frames
        # Assume that the original dataframe is named 'original_df'
        for i in range(0, len(Raster_file_paths_new)):
            dataframes2_temp[i] = select_hgeocode_geo5_6_dic2_cells[0].copy()

    # Convert the dictionary to a list of tuples
    dataframes2 = list(dataframes2_temp.values())

    for k in range(0, len(Raster_file_paths_new)):
        dataframes2[k] = dataframes2[k].rename("{}_{}".format("{}_a",k).format)

    # dictionary to save data frames
    select_hgeocode_geo5_6_dic2_cells_dic={} 

    for key2, value2 in enumerate(dataframes2):    
        select_hgeocode_geo5_6_dic2_cells_dic[key2] = value2 # assigning data frame from list to key in dictionary
        
        
        
        
    return Emp_cells2_dic2, cells2_2030, select_hgeocode_geo5_6_dic2_cells_dic

In [346]:
# Emp_cells2_dic2 = find_cells_SLR(select_hgeocode_geo5_6, Emp_cells2)

In [347]:
len(dataframes_temp)

45

In [348]:
dataframes_temp={}

if check_input_type(select_hgeocode_geo5_6_dic2_cells) :

    select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.reset_index()

    if 'index' in select_hgeocode_geo5_6_dic2_cells.columns:
        select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.drop(['index'],axis=1)
    if 'level_0' in select_hgeocode_geo5_6_dic2_cells.columns:
        select_hgeocode_geo5_6_dic2_cells=select_hgeocode_geo5_6_dic2_cells.drop(['level_0'],axis=1)

    # list of data frames
    # Assume that the original dataframe is named 'original_df'
    for i in range(0, len(new_list)):
        dataframes_temp[i] = select_hgeocode_geo5_6_dic2_cells.copy()


else:

    select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].reset_index()

    if 'index' in select_hgeocode_geo5_6_dic2_cells[0].columns:
        select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].drop(['index'],axis=1)
    if 'level_0' in select_hgeocode_geo5_6_dic2_cells[0].columns:
        select_hgeocode_geo5_6_dic2_cells[0]=select_hgeocode_geo5_6_dic2_cells[0].drop(['level_0'],axis=1)

    # list of data frames
    # Assume that the original dataframe is named 'original_df'
    for i in range(0, len(Raster_file_paths_new)):
        dataframes_temp[i] = select_hgeocode_geo5_6_dic2_cells[0].copy()
    
# Convert the dictionary to a list of tuples
dataframes = list(dataframes_temp.values())
    

for k in range(0, len(Raster_file_paths_new)):# 0,90
    dataframes[k] = dataframes[k].rename("{}_{}".format("{}_a",k).format)

# dictionary to save data frames
select_hgeocode_geo5_6_dic2={} 

for key1, value1 in enumerate(dataframes):    
#     print('key1',key1)
#     print('value1',value1)

    select_hgeocode_geo5_6_dic2[key1] = value1 # assigning data frame from list to key in dictionary

In [349]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [350]:
Emp_cells2_dic2[0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120150205012069,491927247,0.5,POINT (-82.13573 26.96423),1,NaN
3,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,NaN
4,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,NaN
...,...,...,...,...,...,...
386379,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
386380,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
386381,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
386382,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
386383,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [351]:
from joblib import Parallel, delayed

my_list_2=[]
my_list_3=[]
my_list_4=[]

start = time.time()


# Step 3: Use the provided code snippet to parallelize the calculations using the 'worker' function
result = Parallel(n_jobs=5)(delayed(cells_calc_x)(i, select_hgeocode_geo5_6_dic2[i], Emp_cells2_dic2[i], cells2_2030) for i in range(0,len(Raster_file_paths_new)))

# Convert the result to a dictionary with keys as indices
zs2_dic = dict(enumerate(result))

# Step 4: After calculating the results, retrieve the values from the 'zs2_dic' dictionary and store them in the lists 'my_list_2', 'my_list_3', and 'my_list_4'
my_list_2 = [zs2_dic[i][0] for i in range(len(Raster_file_paths_new))]
my_list_3 = [zs2_dic[i][1] for i in range(len(Raster_file_paths_new))]
my_list_4 = [zs2_dic[i][2] for i in range(len(Raster_file_paths_new))]

end = time.time()
print(end - start)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

281.97225618362427

In [352]:
# my_list_2, my_list_3,my_list_4 =  cells_calc_x(select_hgeocode_geo5_6_dic2,Emp_cells2_dic2,cells2_2030)

In [353]:
len(select_hgeocode_geo5_6_dic2[0])

7362

In [354]:
len(cells2_2030)

7363

In [355]:
len(my_list_2[0])

1

In [356]:
my_list_2_final={}
my_list_3_final={}
my_list_4_final={}

for l in range(0,len(Raster_file_paths_new)):
    my_list_2_final[l]= my_list_2[l][0]
    my_list_3_final[l]= my_list_3[l][0]
    my_list_4_final[l]= my_list_4[l][0]

In [357]:
my_list_2={}
my_list_3={}
my_list_4={}

In [358]:
def list_4_calc(my_list_4,cells2_2030_2,Emp_cells2_try4_dic2):
    my_list_4_test3=[]
    for k in range(0,len(my_list_4)):
        my_list_4_test2=[]
        for i in range(0,len(my_list_4[k])):
            if len(my_list_4[k][i])==0:
                continue
            else:
                temo_list= list(deepflatten(my_list_4[k][i], depth=1))
                my_list_4_test2.append(temo_list)
        my_list_4_test3.append(my_list_4_test2)
        
    my_list_4_test4=[]
    for k in range(0,len(my_list_4)):
        my_list_4_test4_temp = list(deepflatten(my_list_4_test3[k], depth=1))
        my_list_4_test4.append(my_list_4_test4_temp)
    
    cells2_2030_2_list = list(deepflatten(cells2_2030_2[1:], depth=1))

    
    df_test=[]
    df_test = pd.DataFrame({'fd_id': cells2_2030_2_list})
    # Loop through the list of lists and add each list as a new column in the DataFrame
    for i, list_1 in enumerate(my_list_4_test4):
        df_test[f'damage{i}'] = list_1
        
    Emp_cells2_try4_dic2_test2 = Emp_cells2_try4_dic2[0][Emp_cells2_try4_dic2[0]['fd_id'].isin(df_test['fd_id'])]

    Emp_cells2_try4_dic2_test_final = pd.merge(Emp_cells2_try4_dic2_test2, df_test,  how='left', 
                        left_on=['fd_id'], right_on = ['fd_id']) 
    
    return Emp_cells2_try4_dic2_test_final

In [359]:
# Emp_cells2_dic2[719][Emp_cells2_dic2[719]['row_num']==5046 ]

In [360]:
Emp_cells2_dic_list4 =list_4_calc(my_list_4_final,cells2_2030,Emp_cells2_dic)

In [361]:
# Emp_cells2_dic_list4[Emp_cells2_dic_list4['damage89']>0]

In [362]:
# Emp_cells2_dic_list4[Emp_cells2_dic_list4['fd_id']==499824024]['found_ht']

In [363]:
# Emp_cells2_2030_dic_find_1_dic[28][Emp_cells2_2030_dic_find_1_dic[28]['fd_id']==499824024]

In [364]:
# Emp_cells2_2030_dic_find_1_dic[10][Emp_cells2_2030_dic_find_1_dic[10]['fd_id']==499824024]

In [365]:
# Emp_cells2_dic_list4[Emp_cells2_dic_list4['fd_id']==499824024].to_csv('499824024.csv')

In [366]:
def custom_sort(col):
    base = int(col.lstrip('damage'))
    if col[0] == 'd':
        return base
    else:
        return float('inf')

In [367]:
# def list4_2_full (Emp_cells2_dic_list4_2):
#     Emp_cells2_dic_list4_2_modify = Emp_cells2_dic_list4_2.copy()

#     for k in range(0,len(my_list_4)):
#         Emp_cells2_dic_list4_2_modify= Emp_cells2_dic_list4_2_modify.drop(['damage{0}'.format(k)],axis=1)

#     Emp_cells2_dic_list4_2_modify

#     for index, i in enumerate(new_list):
#     #     print(f"i: {i}, j: {index+1}")
#         Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = Emp_cells2_dic_list4_2['damage{0}'.format(index)]

#     for i in list_iterate:
#         Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = 0
#     Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify.iloc[:,33:]
#     Emp_cells2_dic_list4_2_modify_select2 = Emp_cells2_dic_list4_2_modify.iloc[:,:33]

#     sorted_columns = sorted(Emp_cells2_dic_list4_2_modify_select.columns, key=custom_sort)
#     sorted_Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify_select[sorted_columns]

#     Emp_cells2_dic_list4_2 = pd.concat([ Emp_cells2_dic_list4_2_modify_select2,sorted_Emp_cells2_dic_list4_2_modify_select],axis=1)

#     return Emp_cells2_dic_list4_2

In [368]:
# Emp_cells2_dic_list4 = list4_2_full(Emp_cells2_dic_list4)

In [369]:
Emp_cells2_dic_list4

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage20,damage21,damage22,damage23,damage24,damage25,damage26,damage27,damage28,damage29
0,121150011012006,2117.0,492858865,76VV9F8C+JQJ-2-1-2-2,121150011012022,RES,RES1-1SNB,C,1.0,756.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,120210106053002,2289.0,493680983,76RW4773+4CH-4-4-4-4,120210106053002,RES,RES1-1SNB,W,1.0,1875.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
2,120210104011007,2417.0,494317506,76RW567C+WV7-3-3-4-3,120210104011009,RES,RES1-1SNB,W,1.0,2043.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
3,120210109062001,2667.0,495400878,76QWW9C4+P95-0-0-0-0,120210109031002,RES,RES1-1SNB,M,1.0,576.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
4,120810020173004,2780.0,495736994,76VVCH52+HMX-0-0-0-0,120810020171020,RES,RES1-1SNB,W,1.0,1388.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29609,120710402113048,7359255.0,498223950,76RWJC82+GM4-0-0-0-0,120710402037052,RES,RES1-1SNB,M,1.0,1011.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29610,120710402074001,7360060.0,498224771,76RWJCG2+QWG-0-0-0-0,120710402074001,RES,RES1-1SNB,W,1.0,637.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29611,120710302051004,7361575.0,498226246,76RWP73R+Q9V-0-0-0-0,120710302031002,RES,RES1-1SNB,W,1.0,1519.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
29612,120710303003023,7361648.0,498226323,76RWP8G7+XGR-0-0-0-0,120710303003036,RES,RES1-1SNB,M,1.0,1353.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29613,120710402092013,7361700.0,498226382,76RWMCJH+X33-0-0-0-0,120710402092016,RES,RES1-1SNB,W,1.0,1595.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [370]:

dataframes3_list_2_temp={}
dataframes3_list_3_temp={}


for k in range(0, len(new_list)):
    dataframes3_list_2_temp[k] = pd.DataFrame(my_list_2_final[k]).copy()
    dataframes3_list_3_temp[k] = pd.DataFrame(my_list_3_final[k]).copy()    
    
dataframes3_list_2 = list(dataframes3_list_2_temp.values())
dataframes3_list_3 = list(dataframes3_list_3_temp.values())


for k in range(0, len(new_list)):
    dataframes3_list_2[k] = dataframes3_list_2[k].rename("{}_{}".format("{}_a",k).format)
    dataframes3_list_3[k] = dataframes3_list_3[k].rename("{}_{}".format("{}_a",k).format)

In [371]:
# dictionary to save data frames
my_dicts_2={}
my_dicts_3={} 

for key_list2, value_list2 in enumerate(dataframes3_list_2):    
    my_dicts_2[key_list2] = value_list2 # assigning data frame from list to key in dictionary
for key_list3, value_list3 in enumerate(dataframes3_list_3):    
    my_dicts_3[key_list3] = value_list3 # assigning data frame from list to key in dictionary

In [372]:
for i in range(0,len(select_hgeocode_geo5_6_dic2)):
    select_hgeocode_geo5_6_dic2[i]['C000_dmg'] = my_dicts_2[i]
    select_hgeocode_geo5_6_dic2[i]['C000_dmg_mean'] = my_dicts_3[i]

In [373]:
len(select_hgeocode_geo5_6_dic2)

30

In [374]:
# select_hgeocode_geo5_6_dic2[89][select_hgeocode_geo5_6_dic2[89]['C000_dmg']>0]['C000_dmg'].sum()

In [375]:
# def dataframe_full (select_hgeocode_geo5_6_dic2):

#     select_hgeocode_geo5_6_dic2_full={}

#     for index, i in enumerate(new_list):
#         #     print(f"i: {i}, j: {index+1}")
#             select_hgeocode_geo5_6_dic2_full[i] = select_hgeocode_geo5_6_dic2[index]


#     for i in list_iterate:
#             select_hgeocode_geo5_6_dic2_full[i] = select_hgeocode_geo5_6_dic2[0].copy()
#             select_hgeocode_geo5_6_dic2_full[i]['C000_dmg'] = 0
#             select_hgeocode_geo5_6_dic2_full[i]['C000_dmg_mean'] = 0
#     return select_hgeocode_geo5_6_dic2_full

In [376]:
# select_hgeocode_geo5_6_dic2_full = dataframe_full(select_hgeocode_geo5_6_dic2)

In [377]:
select_hgeocode_geo5_6_dic2[0]['C000'].sum()

37155

In [378]:
select_hgeocode_geo5_6_dic2[0]['cells_used'].sum()

29614

In [379]:
len(Emp_cells2_dic2[0])

386384

In [380]:

from iteration_utilities import deepflatten

list_cells2_2030 = list(deepflatten(cells2_2030, depth=1))
Emp_cells2_2030_dic = {}
for i in range(0, 1):
    Emp_cells2_2030_dic[i] = Emp_cells2_dic2[i].loc[~Emp_cells2_dic2[i]['fd_id'].isin(list_cells2_2030)]
len(Emp_cells2_2030_dic[0])

356770

In [381]:
Emp_cells2_2030_dic[0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120150205012069,491927247,0.5,POINT (-82.13573 26.96423),1,NaN
3,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,NaN
4,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,NaN
...,...,...,...,...,...,...
386379,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
386380,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
386381,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
386382,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
386383,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [382]:
select_hgeocode_geo5_6_dic2[0]['C000'].sum()

37155

In [383]:
len(Emp_cells2_dic2[0]) - len(Emp_cells2_2030_dic[0])

29614

In [384]:
len(Emp_cells2_dic[0])-len(Emp_cells2_2030_dic[0])

29614

In [385]:
select_hgeocode_geo5_6_dic2[0][select_hgeocode_geo5_6_dic2[0]['C000']<0]

Empty DataFrame
Columns: [w_geocode, h_geocode_x, h_geocode_y, C000, CA01, CA02, CA03, CR01, CR02, CR03, CR04, CR05, CR07, CE01, CE02, CE03, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, cell_x, dist, h_geocode, cell_y, geometry_x1, geometry_y1, geometry, dist_x, cells_used, C000_dmg, C000_dmg_mean]
Index: []

[0 rows x 55 columns]

In [386]:
select_hgeocode_geo5_6_try2 = select_hgeocode_geo5_6_dic2[0].loc[select_hgeocode_geo5_6_dic2[0]['C000']!=select_hgeocode_geo5_6_dic2[0]['cells_used']]
select_hgeocode_geo5_6_try2

,w_geocode,h_geocode_x,h_geocode_y,C000,CA01,CA02,CA03,CR01,CR02,CR03,...,dist,h_geocode,cell_y,geometry_x1,geometry_y1,geometry,dist_x,cells_used,C000_dmg,C000_dmg_mean
203_a_0,1.208100e+14,120810004101003.0,120810004061002,16,4,7,5,16,0,0,...,0.739847,1.208100e+14,17.0,"POLYGON ((-82.62046 27.48126, -82.61986 27.481...","POLYGON ((-82.62464 27.48327, -82.62456 27.483...","POLYGON ((-82.62917 27.47696, -82.62910 27.477...",0.770489,8,0,NaN
264_a_0,1.202101e+14,120210104114005.0,120210104221007,20,2,12,6,16,4,0,...,1.580271,1.202101e+14,27.0,"POLYGON ((-81.70261 26.19707, -81.70153 26.197...","POLYGON ((-81.68948 26.19118, -81.68846 26.191...","POLYGON ((-81.70292 26.18063, -81.70173 26.181...",1.731299,5,0,NaN
377_a_0,1.207100e+14,120710011012021.0,120710011013025,5,1,3,1,4,1,0,...,0.538371,1.207100e+14,7.0,"POLYGON ((-81.86190 26.61358, -81.86112 26.613...","POLYGON ((-81.86388 26.61166, -81.86185 26.611...","POLYGON ((-81.87174 26.62387, -81.87158 26.623...",1.902641,3,0,NaN
408_a_0,1.208797e+14,120879718001011.0,120879719001023,13,1,8,4,13,0,0,...,0.888735,1.208797e+14,89.0,"POLYGON ((-81.75621 24.56846, -81.75617 24.568...","POLYGON ((-81.76456 24.57063, -81.76403 24.570...","POLYGON ((-81.74231 24.58633, -81.74224 24.586...",3.269836,2,0,NaN
427_a_0,1.207100e+14,120710003031009.0,120710006004004,6,1,4,1,3,3,0,...,0.7659,1.207100e+14,7.0,"POLYGON ((-81.83507 26.64115, -81.83490 26.641...","POLYGON ((-81.84026 26.64836, -81.83989 26.648...","POLYGON ((-81.82713 26.67307, -81.82712 26.673...",3.161819,5,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6956_a_0,1.207100e+14,120710010011003.0,120710501064010,3,1,2,0,2,0,1,...,12.945794,1.207100e+14,38.0,"POLYGON ((-81.85334 26.49401, -81.85333 26.494...","POLYGON ((-81.87195 26.61154, -81.86769 26.611...","POLYGON ((-81.89058 26.59695, -81.89055 26.597...",1.71739,0,0,NaN
6959_a_0,1.208100e+14,120810006012006.0,120810019163004,7,2,4,1,6,1,0,...,11.587041,1.208100e+14,8.0,"POLYGON ((-82.51255 27.58683, -82.51128 27.588...","POLYGON ((-82.56547 27.49466, -82.56543 27.495...","POLYGON ((-82.58754 27.48921, -82.58549 27.489...",2.241067,0,0,NaN
6960_a_0,1.208797e+14,120879714021097.0,120879714011032,3,0,3,0,3,0,0,...,0.899217,1.208797e+14,41.0,"POLYGON ((-81.35092 24.67245, -81.35092 24.672...","POLYGON ((-81.36233 24.67438, -81.36080 24.674...","POLYGON ((-81.37982 24.69698, -81.37981 24.697...",3.090782,0,0,NaN
6962_a_0,1.208100e+14,120810015012012.0,120810015023039,8,2,4,2,6,1,0,...,0.566279,1.208100e+14,24.0,"POLYGON ((-82.55902 27.51934, -82.55849 27.519...","POLYGON ((-82.56244 27.52125, -82.56139 27.524...","POLYGON ((-82.55752 27.53963, -82.55649 27.539...",1.657977,3,0,NaN
6965_a_0,1.208100e+14,120810020101013.0,120810020102028,8,1,4,3,8,0,0,...,8.290817,1.208100e+14,28.0,"POLYGON ((-82.12026 27.26250, -82.11883 27.265...","POLYGON ((-82.14689 27.34123, -82.14686 27.341...","POLYGON ((-82.16255 27.35193, -82.16252 27.355...",5.639469,0,0,NaN

In [387]:
select_hgeocode_geo5_6_try2['C000'].sum()

8924

In [388]:
(select_hgeocode_geo5_6_try2['C000']-select_hgeocode_geo5_6_try2['cells_used']).sum()

7541

In [389]:
def try_function(select_hgeocode_geo5_6_try2,Emp_cells2_2030_1_dic, select_hgeocode_geo4_2_2):

    select_hgeocode_geo5_6_try2 = select_hgeocode_geo5_6_try2.astype({"cells_used":'int64'})
    
    print('select_hgeocode_geo5_6_try2[cells_used]=', select_hgeocode_geo5_6_try2['cells_used'].sum())
    
    select_hgeocode_geo5_6_try2['C000'] = select_hgeocode_geo5_6_try2['C000']- select_hgeocode_geo5_6_try2['cells_used']

    select_hgeocode_geo5_6_try2 = select_hgeocode_geo5_6_try2.astype({"C000":'int64'})
    
    print('select_hgeocode_geo5_6_try2[C000]=', select_hgeocode_geo5_6_try2['C000'].sum())
    
#     if 'h_geocode_y' in select_hgeocode_geo5_6_try2.columns:
#         print('Yes')
#     else: 
#         print('No')
#         select_hgeocode_geo5_6_try2.rename(columns = {'h_geocode':'h_geocode_y'}, inplace = True)
        
    
    select_hgeocode_geo5_6_try2_c000 = select_hgeocode_geo5_6_try2[['C000','h_geocode_y']]    
        
    select_hgeocode_geo5_6_try3 = select_hgeocode_geo4_2_2.loc[select_hgeocode_geo4_2_2['h_geocode_y'].isin(select_hgeocode_geo5_6_try2['h_geocode_y'])]
        
    
#     print('len select_hgeocode_geo5_6_try3', len(select_hgeocode_geo5_6_try3))
    
    select_hgeocode_geo5_6_try3_missing = select_hgeocode_geo5_6_try2.loc[~select_hgeocode_geo5_6_try2['h_geocode_y'].isin(select_hgeocode_geo5_6_try3['h_geocode_y'])]
    
    print('len select_hgeocode_geo5_6_try3_missing', len(select_hgeocode_geo5_6_try3_missing))
            
    select_hgeocode_geo5_6_try3_ = pd.merge(
        select_hgeocode_geo5_6_try3, select_hgeocode_geo5_6_try2_c000, how="left", on=["h_geocode_y"])
    
#     print('len select_hgeocode_geo5_6_try3_', len(select_hgeocode_geo5_6_try3_))
    
    select_hgeocode_geo5_6_try3_ = select_hgeocode_geo5_6_try3_.drop(['C000_x'],axis=1)
    select_hgeocode_geo5_6_try3_.rename(columns={'C000_y':'C000'},inplace= True)
    
    select_hgeocode_geo5_6_try4 = select_hgeocode_geo5_6_try3_.loc[~select_hgeocode_geo5_6_try3_['h_geocode_x'].isin(select_hgeocode_geo5_6_try2['h_geocode_x'])]
    
#     print('len select_hgeocode_geo5_6_try4', len(select_hgeocode_geo5_6_try4))

    
    #to get the min dist from orginal h_geocode (h_geocode_y) to w_geocode
    select_hgeocode_geo5_6_try4 = select_hgeocode_geo5_6_try4.select_dtypes(exclude=['geometry'])
    select_hgeocode_geo4_3_try = select_hgeocode_geo5_6_try4.groupby(["h_geocode_y"], as_index=False).min()

    select_hgeocode_geo4_3_try = select_hgeocode_geo4_3_try[['dist']]
    select_hgeocode_geo5_1_try = pd.merge(select_hgeocode_geo4_3_try, select_hgeocode_geo5_6_try4,  how='left', 
                    left_on=['dist'], right_on = ['dist'])


#     select_hgeocode_geo5_1_try = select_hgeocode_geo5_1_try.drop(['level_0','index'],axis=1)
    select_hgeocode_geo5_1_try = select_hgeocode_geo5_1_try.reset_index()
    select_hgeocode_geo5_1_try = select_hgeocode_geo5_1_try.astype({"index":'object'})
    
    
    
    select_hgeocode_geo5_1_try_ = select_hgeocode_geo5_1_try.loc[select_hgeocode_geo5_1_try['h_geocode_x'].isin(Emp_cells2_2030_1_dic[0]['h_geocode'])]
    
#     print('len select_hgeocode_geo5_1_try_', len(select_hgeocode_geo5_1_try_))

#     select_hgeocode_geo5_2_try = select_hgeocode_geo5_1_try_.groupby(["h_geocode_y"], as_index=False)['dist_x'].min()
    select_hgeocode_geo5_2_try = select_hgeocode_geo5_1_try_.groupby(["h_geocode_y"], as_index=False)['dist_x'].min()

    
    select_hgeocode_geo5_2_try = select_hgeocode_geo5_2_try[['dist_x']]
    select_hgeocode_geo5_3_try = pd.merge(select_hgeocode_geo5_2_try, select_hgeocode_geo5_1_try_,  how='left', 
                    left_on=['dist_x'], right_on = ['dist_x'])
    
#     print('len select_hgeocode_geo5_3_try', len(select_hgeocode_geo5_3_try))

    select_hgeocode_geo5_6_try_ = select_hgeocode_geo5_3_try.drop_duplicates(subset=['h_geocode_y']) # this should be select_hgeocode_geo5_6_try 
    
    select_hgeocode_geo5_6_try_missing = select_hgeocode_geo5_6_try2.loc[~select_hgeocode_geo5_6_try2['h_geocode_y'].isin(select_hgeocode_geo5_6_try_['h_geocode_y'])]
    
    print('select_hgeocode_geo5_6_try_missing_h_geocode_x', select_hgeocode_geo5_6_try_missing['h_geocode_x'])
    
    print('select_hgeocode_geo5_6_try_missing_h_geocode_y', select_hgeocode_geo5_6_try_missing['h_geocode_y'])


    print('len select_hgeocode_geo4_2_2', len(select_hgeocode_geo4_2_2))

    
    select_hgeocode_geo4_2_2_missing = select_hgeocode_geo4_2_2.loc[select_hgeocode_geo4_2_2['h_geocode_y'].isin(select_hgeocode_geo5_6_try_missing['h_geocode_y'])]
    print('len select_hgeocode_geo4_2_2_missing', len(select_hgeocode_geo4_2_2_missing))

    select_hgeocode_geo4_2_2_exist =  select_hgeocode_geo4_2_2.loc[~select_hgeocode_geo4_2_2['h_geocode_y'].isin(select_hgeocode_geo5_6_try_missing['h_geocode_y'])]
    
    print('len select_hgeocode_geo4_2_2_exist', len(select_hgeocode_geo4_2_2_exist))

    select_hgeocode_geo4_2_2_missing2 = select_hgeocode_geo4_2_2_missing.loc[~select_hgeocode_geo4_2_2_missing['h_geocode_x'].isin(select_hgeocode_geo5_6_try_missing['h_geocode_x'])]
    
    print('len select_hgeocode_geo4_2_2_missing2', len(select_hgeocode_geo4_2_2_missing2))
    
    select_hgeocode_geo4_2_2_final = pd.concat([select_hgeocode_geo4_2_2_exist,select_hgeocode_geo4_2_2_missing2], axis=0 )

    print('len select_hgeocode_geo4_2_2_final', len(select_hgeocode_geo4_2_2_final))

    
    print('len select_hgeocode_geo5_6_try_missing', len(select_hgeocode_geo5_6_try_missing))
    
    select_hgeocode_geo5_6_try_missing_final = select_hgeocode_geo5_6_try_missing.loc[~select_hgeocode_geo5_6_try_missing['h_geocode_y'].isin(select_hgeocode_geo5_6_try3_missing['h_geocode_y'])]
    
    print('len select_hgeocode_geo5_6_try_missing_final', len(select_hgeocode_geo5_6_try_missing_final))
    print('len select_hgeocode_geo5_6_try_missing_final_h_geocode_x', select_hgeocode_geo5_6_try_missing_final['h_geocode_x'])

    select_hgeocode_geo5_6_try =  select_hgeocode_geo5_6_try_       
    
#     print('len select_hgeocode_geo5_6_try', len(select_hgeocode_geo5_6_try))
                                                      
    
    find_cells = Emp_cells2_2030_1_dic[0].loc[Emp_cells2_2030_1_dic[0]['h_geocode'].isin(select_hgeocode_geo5_6_try['h_geocode_x'])]
    
    find_cells_sum = find_cells.groupby(["h_geocode"], as_index=False)['cell'].sum()
    
#     for select_hgeocode_geo5_1_try
    
#     print('find_cells(cells_num)=',find_cells_sum)
    
    
    
    select_hgeocode_geo5_6_try = select_hgeocode_geo5_6_try.drop(['index'],axis=1)
    select_hgeocode_geo5_6_try = select_hgeocode_geo5_6_try.reset_index()
#     print('select_hgeocode_geo5_6_try=',pd.DataFrame(select_hgeocode_geo5_6_try))



#     select_hgeocode_geo5_6_try['C000']= select_hgeocode_geo5_6_try['C000'].replace('',np.nan.fillna(0))
    print('select_hgeocode_geo5_6_try[C000]=',select_hgeocode_geo5_6_try['C000'].unique())
    
    select_hgeocode_geo5_6_try = select_hgeocode_geo5_6_try.dropna(subset=['C000'])
    
    print('select_hgeocode_geo5_6_try[C000]=',select_hgeocode_geo5_6_try['C000'].unique())

    select_hgeocode_geo5_6_try = select_hgeocode_geo5_6_try.astype({"C000":'int64',"CNS01":'int64',"CNS02":'int64',"CNS03":'int64',
                                                           "CNS04":'int64',"CNS05":'int64',"CNS06":'int64',"CNS07":'int64',
                                                           "CNS08":'int64',"CNS09":'int64',"CNS10":'int64',"CNS11":'int64',
                                                           "CNS12":'int64',"CNS13":'int64',"CNS14":'int64',"CNS15":'int64',
                                                           "CNS16":'int64',"CNS17":'int64',"CNS18":'int64',"CNS19":'int64',
                                                           "CNS20":'int64', "CR01":'int64','CR02':'int64' ,'CR03' :'int64',
                                                           "CR04" :'int64', "CR05":'int64','CR07':'int64' ,"CA01" :'int64',
                                                           "CA02" :'int64',"CA03" :'int64',"CE01":'int64' ,"CE02" :'int64',
                                                           "CE03" :'int64',"CT01" :'int64',"CT02":'int64' ,"CD01" :'int64',
                                                           "CD02" :'int64',"CD03" :'int64',"CD04":'int64' ,"CS01" :'int64',
                                                           "CS02" :'int64'})

    
    print('select_hgeocode_geo5_6_try[C000]=', select_hgeocode_geo5_6_try['C000'].sum())

    
    dataframes2_temp={}


    # list of data frames
    # Assume that the original dataframe is named 'original_df'
    for i in range(0, 1):
        dataframes2_temp[i] = select_hgeocode_geo5_6_try.copy()

    # Convert the dictionary to a list of tuples
    dataframes2 = list(dataframes2_temp.values())

    for k in range(0, 1):
        dataframes2[k] = dataframes2[k].rename("{}_{}".format("{}_a",k).format)

    # dictionary to save data frames
    select_hgeocode_geo5_6_try_dic={} 

    for key2, value2 in enumerate(dataframes2):    
        select_hgeocode_geo5_6_try_dic[key2] = value2 # assigning data frame from list to key in dictionary

    return select_hgeocode_geo5_6_try_dic , select_hgeocode_geo4_2_2_final, select_hgeocode_geo5_6_try_missing #,select_hgeocode_geo5_6_try_missing

In [390]:
def dmg_calc(my_list_2,my_list_3,select_hgeocode_geo5_6_dic2):
    dataframes3_list_2_temp={}
    dataframes3_list_3_temp={}


    for k in range(0, len(Raster_file_paths_new)):
        dataframes3_list_2_temp[k] = pd.DataFrame(my_list_2[k]).copy()
        dataframes3_list_3_temp[k] = pd.DataFrame(my_list_3[k]).copy()    

    dataframes3_list_2 = list(dataframes3_list_2_temp.values())
    dataframes3_list_3 = list(dataframes3_list_3_temp.values())


    for k in range(0, len(Raster_file_paths_new)):
        dataframes3_list_2[k] = dataframes3_list_2[k].rename("{}_{}".format("{}_a",k).format)
        dataframes3_list_3[k] = dataframes3_list_3[k].rename("{}_{}".format("{}_a",k).format)


    # dictionary to save data frames
    my_dicts_2={}
    my_dicts_3={} 

    for key_list2, value_list2 in enumerate(dataframes3_list_2):    
        my_dicts_2[key_list2] = value_list2 # assigning data frame from list to key in dictionary
    for key_list3, value_list3 in enumerate(dataframes3_list_3):    
        my_dicts_3[key_list3] = value_list3 # assigning data frame from list to key in dictionary


    for i in range(0,len(select_hgeocode_geo5_6_dic2)):
        select_hgeocode_geo5_6_dic2[i]['C000_dmg'] = my_dicts_2[i]
        select_hgeocode_geo5_6_dic2[i]['C000_dmg_mean'] = my_dicts_3[i]
        
    return select_hgeocode_geo5_6_dic2

In [391]:
select_hgeocode_geo5_6_try2[select_hgeocode_geo5_6_try2['C000']<0]

Empty DataFrame
Columns: [w_geocode, h_geocode_x, h_geocode_y, C000, CA01, CA02, CA03, CR01, CR02, CR03, CR04, CR05, CR07, CE01, CE02, CE03, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, cell_x, dist, h_geocode, cell_y, geometry_x1, geometry_y1, geometry, dist_x, cells_used, C000_dmg, C000_dmg_mean]
Index: []

[0 rows x 55 columns]

In [392]:
# select_hgeocode_geo5_6_try_dic,select_hgeocode_geo5_6_try_dic_missing = try_function(select_hgeocode_geo5_6_try2,Emp_cells2_2030_dic,select_hgeocode_geo4_2_2)

In [393]:
def list4_2_full (Emp_cells2_dic_list4_2):
    Emp_cells2_dic_list4_2_modify = Emp_cells2_dic_list4_2.copy()

    for k in range(0,len(my_list_4)):
        Emp_cells2_dic_list4_2_modify= Emp_cells2_dic_list4_2_modify.drop(['damage{0}'.format(k)],axis=1)

    Emp_cells2_dic_list4_2_modify

    for index, i in enumerate(new_list):
    #     print(f"i: {i}, j: {index+1}")
        Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = Emp_cells2_dic_list4_2['damage{0}'.format(index)]

    for i in list_iterate:
        Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = 0
    Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify.iloc[:,33:]
    Emp_cells2_dic_list4_2_modify_select2 = Emp_cells2_dic_list4_2_modify.iloc[:,:33]

    sorted_columns = sorted(Emp_cells2_dic_list4_2_modify_select.columns, key=custom_sort)
    sorted_Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify_select[sorted_columns]

    Emp_cells2_dic_list4_2 = pd.concat([ Emp_cells2_dic_list4_2_modify_select2,sorted_Emp_cells2_dic_list4_2_modify_select],axis=1)

    return Emp_cells2_dic_list4_2

In [394]:
# Emp_cells2_dic_list4 = list4_2_full(Emp_cells2_dic_list4)

In [395]:
len(select_hgeocode_geo5_6_try2)

1800

In [396]:
def dataframe_full (select_hgeocode_geo5_6_dic2):

    select_hgeocode_geo5_6_dic2_full={}

    for index, i in enumerate(new_list):
        #     print(f"i: {i}, j: {index+1}")
            select_hgeocode_geo5_6_dic2_full[i] = select_hgeocode_geo5_6_dic2[index]


    for i in list_iterate:
            select_hgeocode_geo5_6_dic2_full[i] = select_hgeocode_geo5_6_dic2[0].copy()
            select_hgeocode_geo5_6_dic2_full[i]['C000_dmg'] = 0
            select_hgeocode_geo5_6_dic2_full[i]['C000_dmg_mean'] = 0
    return select_hgeocode_geo5_6_dic2_full

In [397]:
# select_hgeocode_geo5_6_dic2_full = dataframe_full(select_hgeocode_geo5_6_dic2)

In [398]:

from iteration_utilities import deepflatten

list_cells2_2030 = list(deepflatten(cells2_2030, depth=1))
Emp_cells2_2030_1_try1_dic = {}
for i in range(0, 1):
    Emp_cells2_2030_1_try1_dic[i] = Emp_cells2_dic2[i].loc[~Emp_cells2_dic2[i]['fd_id'].isin(list_cells2_2030)]
#     Emp_cells2_2030_1_try1_dic[i]=Emp_cells2_2030_1_try1_dic[i].drop(['min_2030'],axis=1)
    
len(Emp_cells2_2030_1_try1_dic[0])

356770

In [399]:
len(Emp_cells2_2030_1_try1_dic[0])

356770

In [400]:
len(Emp_cells2_dic2[0])-len(Emp_cells2_2030_1_try1_dic[0])

29614

In [401]:
# for x in range(0, 2):
#     globals()['list_cells2_2030_1_try%s_dic' % x] = 'Hello'
    
#     print(len(globals()['list_cells2_2030_1_try%s_dic' % x]))

In [402]:
select_hgeocode_geo5_6_dic2[0]['C000'].sum()

37155

In [403]:
select_hgeocode_geo5_6_try2[select_hgeocode_geo5_6_try2['C000']<0]

Empty DataFrame
Columns: [w_geocode, h_geocode_x, h_geocode_y, C000, CA01, CA02, CA03, CR01, CR02, CR03, CR04, CR05, CR07, CE01, CE02, CE03, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, cell_x, dist, h_geocode, cell_y, geometry_x1, geometry_y1, geometry, dist_x, cells_used, C000_dmg, C000_dmg_mean]
Index: []

[0 rows x 55 columns]

In [404]:
Emp_cells2_2030_1_try1_dic[0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120150205012069,491927247,0.5,POINT (-82.13573 26.96423),1,NaN
3,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,NaN
4,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,NaN
...,...,...,...,...,...,...
386379,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
386380,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
386381,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
386382,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
386383,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [405]:
select_hgeocode_geo5_6['w_geocode'][0]

120710012052012.0

In [406]:
# select_hgeocode_geo4_2_2 is the dataframe that has the connection between h_geocode_y and nearest h_geocode_x
# from nearest (w_geocode_x)

select_hgeocode_geo4_2_2_try1 = select_hgeocode_geo4_2_2.copy()


for j in range(2,30):
    print('j loop =',j)
    globals()['select_hgeocode_geo5_6_try_try%s_dic' % j] ={}
    globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % j] =[]
    globals()['cells2_2030_1_try%s' % j] = []
    globals()['list_cells2_2030_1_try%s' % j] = []
    globals()['select_hgeocode_geo5_6_try%s' % (j+1)] = []
    
    my_list_2=[]
    my_list_3=[]
    my_list_4=[]
    
#     print(globals()['select_hgeocode_geo5_6_try_try%s' % i])
    
#     print(globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)])

    
    globals()['select_hgeocode_geo5_6_try_try%s_dic' % j] , globals()['select_hgeocode_geo4_2_2_try%s' % j], globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = try_function(globals()['select_hgeocode_geo5_6_try%s' % j], globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)], globals()['select_hgeocode_geo4_2_2_try%s' % (j-1)])
    
    globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0]['loop_num'] = j
    
    globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)], globals()['cells2_2030_1_try%s' % j], globals()['select_hgeocode_geo5_6_try_try%s_dic' % j] = find_cells_SLR(globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0], globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)][0])
    
#     my_list_2, my_list_3,my_list_4 =  cells_calc_x(globals()['select_hgeocode_geo5_6_try_try%s_dic' % j[i]],globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)[i]], globals()['cells2_2030_1_try%s' % j])
    
    start = time.time()
    
    result = Parallel(n_jobs=-1)(delayed(cells_calc_x)(i, globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][i],globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)][i], globals()['cells2_2030_1_try%s' % j]) for i in range(0,len(Raster_file_paths_new)))
    
    zs2_dic3 = dict(enumerate(result))
    
    my_list_2 = [zs2_dic3[i][0] for i in range(len(Raster_file_paths_new))]
    my_list_3 = [zs2_dic3[i][1] for i in range(len(Raster_file_paths_new))]
    my_list_4 = [zs2_dic3[i][2] for i in range(len(Raster_file_paths_new))]
    
    my_list_2_final={}
    my_list_3_final={}
    my_list_4_final={}

    for l in range(0,len(Raster_file_paths_new)):
        my_list_2_final[l]= my_list_2[l][0]
        my_list_3_final[l]= my_list_3[l][0]
        my_list_4_final[l]= my_list_4[l][0]

    end = time.time()
    print(end - start)
    
    globals()['select_hgeocode_geo5_6_try_try%s_dic' % j]= dmg_calc(my_list_2_final, my_list_3_final,globals()['select_hgeocode_geo5_6_try_try%s_dic' % j])
    
#     globals()['select_hgeocode_geo5_6_try_try%s_dic_full' % j] = dataframe_full(globals()['select_hgeocode_geo5_6_try_try%s_dic' % j])
    
    globals()['Emp_cells2_2030_1_try_list%s' % j]  =list_4_calc(my_list_4_final,globals()['cells2_2030_1_try%s' % j], Emp_cells2_dic)
#     globals()['Emp_cells2_2030_1_try_list%s' % j]  = list4_2_full(globals()['Emp_cells2_2030_1_try_list%s' % j])
    
    
    globals()['list_cells2_2030_1_try%s' % j] = list(deepflatten(globals()['cells2_2030_1_try%s' % j], depth=1))
    globals()['Emp_cells2_2030_1_try%s_dic' % j] = {}
    for k in range(0, 1):
        globals()['Emp_cells2_2030_1_try%s_dic' % j][k] = globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)][k].loc[~globals()['Emp_cells2_2030_1_try%s_dic' % (j-1)][k]['fd_id'].isin(globals()['list_cells2_2030_1_try%s' % j])]

    globals()['select_hgeocode_geo5_6_try%s' % (j+1)] = globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0].loc[globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0]['C000']!=globals()['select_hgeocode_geo5_6_try_try%s_dic' % j][0]['cells_used']]
    print('len(select_hgeocode_geo5_6_try))=',len(globals()['select_hgeocode_geo5_6_try%s' % (j+1)]) )
    if len(globals()['select_hgeocode_geo5_6_try%s' % (j+1)])>0:
        if len(globals()['select_hgeocode_geo5_6_try%s' % (j+1)])!=len(globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)]):
            continue
        else: break
    else: 
        break

j loop = 2
select_hgeocode_geo5_6_try2[cells_used]= 1383
select_hgeocode_geo5_6_try2[C000]= 7541
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x 503_a_0     120879718001011.0
524_a_0     120879718001011.0
534_a_0     120879718001011.0
585_a_0     120879718001011.0
588_a_0     120879718001011.0
591_a_0     120879718001011.0
2471_a_0    120879727001036.0
3066_a_0    120879718001011.0
3238_a_0    120150206021011.0
4404_a_0    120879719003000.0
4462_a_0    120879718001011.0
4546_a_0    120810004101003.0
5054_a_0    121150027461003.0
5368_a_0    120879704004000.0
6284_a_0    120879718001011.0
6566_a_0    120879718001011.0
6775_a_0    120879708001016.0
Name: h_geocode_x, dtype: object
select_hgeocode_geo5_6_try_missing_h_geocode_y 503_a_0     120879721001025
524_a_0     120879724001019
534_a_0     120879719003012
585_a_0     120879722001004
588_a_0     120879724001010
591_a_0     120879728002007
2471_a_0    120879705002024
3066_a_0    120879720001000
3238_a_0    120150105041028
4404_a_0    120879728002014
4462_a_0    120879714011002
4546_a_0    120810008041014
5054_a_0    121150027213052
5368_a_0    120879707002012
6284_a_0    120879728002021
6566_a_0    120879720001032
6775_a_0    120879708003013
Name: h_geocode_y, dtype: int64
len select_hgeocode_geo4_2_2 1765002
len select_hgeocode_geo4_2_2_missing 22
len select_hgeocode_geo4_2_2_exist 1764980
len select_hgeocode_geo4_2_2_missing2 4
len select_hgeocode_geo4_2_2_final 1764984
len select_hgeocode_geo5_6_try_missing 17
len select_hgeocode_geo5_6_try_missing_final 17
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x 503_a_0     120879718001011.0
524_a_0     120879718001011.0
534_a_0     120879718001011.0
585_a_0     120879718001011.0
588_a_0     120879718001011.0
591_a_0     120879718001011.0
2471_a_0    120879727001036.0
3066_a_0    120879718001011.0
3238_a_0    120150206021011.0
4404_a_0    120879719003000.0
4462_a_0    120879718001011.0
4546_a_0    120810004101003.0
5054_a_0    121150027461003.0
5368_a_0    120879704004000.0
6284_a_0    120879718001011.0
6566_a_0    120879718001011.0
6775_a_0    120879708001016.0
Name: h_geocode_x, dtype: object
select_hgeocode_geo5_6_try[C000]= [ 2  4 21  1  3  9  6 11  8  5 20 10  7 19 13 18 12 16 36 14 27 15 17 22
 23 24 39 62 51 30 41 28]
select_hgeocode_geo5_6_try[C000]= [ 2  4 21  1  3  9  6 11  8  5 20 10  7 19 13 18 12 16 36 14 27 15 17 22
 23 24 39 62 51 30 41 28]
select_hgeocode_geo5_6_try[C000]= 7416
Yes
i= 0
3.59506893157959
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

29.153214931488037
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.05319690704345703
39.55841279029846
len(select_hgeocode_geo5_6_try))= 805
j loop = 3
select_hgeocode_geo5_6_try2[cells_used]= 313
select_hgeocode_geo5_6_try2[C000]= 2989
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x 1639_a_0    1.208797e+14
1641_a_0    1.208797e+14
1647_a_0    1.208797e+14
Name: h_geocode_x, dtype: float64
select_hgeocode_geo5_6_try_missing_h_geocode_y 1639_a_0    120879728001011
1641_a_0    120879728002008
1647_a_0    120879728004012
Name: h_geocode_y, dtype: int64
len select_hgeocode_geo4_2_2 1764984
len select_hgeocode_geo4_2_2_missing 9
len select_hgeocode_geo4_2_2_exist 1764975
len select_hgeocode_geo4_2_2_missing2 6
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 3
len select_hgeocode_geo5_6_try_missing_final 3
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x 1639_a_0    1.208797e+14
1641_a_0    1.208797e+14
1647_a_0    1.208797e+14
Name: h_geocode_x, dtype: float64
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  6  5  7  9 11  8 13 36 14 10 19 15 17 18 16 27 22 12 23 28]
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  6  5  7  9 11  8 13 36 14 10 19 15 17 18 16 27 22 12 23 28]
select_hgeocode_geo5_6_try[C000]= 2977
Yes
i= 0
1.5447371006011963
your here 1
your here 2
9.556230068206787
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.03112506866455078

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

16.520332098007202
len(select_hgeocode_geo5_6_try))= 457
j loop = 4
select_hgeocode_geo5_6_try2[cells_used]= 188
select_hgeocode_geo5_6_try2[C000]= 1571
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 3  1  2  6  7  5  8 13  4 10 14  9 19 15 17 22 18 16 11 12 23]
select_hgeocode_geo5_6_try[C000]= [ 3  1  2  6  7  5  8 13  4 10 14  9 19 15 17 22 18 16 11 12 23]
select_hgeocode_geo5_6_try[C000]= 1571
Yes
i= 0
0.8644430637359619
your here 1
your here 2
3.7492120265960693
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.023454904556274414
9.741306066513062
len(select_hgeocode_geo5_6_try))= 322
j loop = 5
select_hgeocode_geo5_6_try2[cells_used]= 50
select_hgeocode_geo5_6_try2[C000]= 1054
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 5  1  2  6  3  4  7  8 10 19 15 17 22 18 16 14  9 11 12 13]
select_hgeocode_geo5_6_try[C000]= [ 5  1  2  6  3  4  7  8 10 19 15 17 22 18 16 14  9 11 12 13]
select_hgeocode_geo5_6_try[C000]= 1054
Yes
i= 0
0.6078822612762451
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

2.451338052749634
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.025310277938842773

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

7.417034149169922
len(select_hgeocode_geo5_6_try))= 250
j loop = 6
select_hgeocode_geo5_6_try2[cells_used]= 53
select_hgeocode_geo5_6_try2[C000]= 739
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 2  1  3  5  4  8  6 10  7  9 17 22 15 18 16 11 12]
select_hgeocode_geo5_6_try[C000]= [ 2  1  3  5  4  8  6 10  7  9 17 22 15 18 16 11 12]
select_hgeocode_geo5_6_try[C000]= 739
Yes
i= 0
0.46596813201904297
your here 1
your here 2
1.3034272193908691
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.02248382568359375

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

6.139293909072876
len(select_hgeocode_geo5_6_try))= 203
j loop = 7
select_hgeocode_geo5_6_try2[cells_used]= 34
select_hgeocode_geo5_6_try2[C000]= 560
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  5  4  8  6  7 10 17 15 18 16 11 12]
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  5  4  8  6  7 10 17 15 18 16 11 12]
select_hgeocode_geo5_6_try[C000]= 560
Yes
i= 0
0.3785269260406494
your here 1
your here 2
1.4129018783569336
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.02399301528930664
5.324602127075195
len(select_hgeocode_geo5_6_try))= 166
j loop = 8
select_hgeocode_geo5_6_try2[cells_used]= 21
select_hgeocode_geo5_6_try2[C000]= 401
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  5  7  6 11  8 12 10]
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  5  7  6 11  8 12 10]
select_hgeocode_geo5_6_try[C000]= 401
Yes
i= 0
0.30606889724731445
your here 1
your here 2
0.7070279121398926
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.021966218948364258

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

4.943471193313599
len(select_hgeocode_geo5_6_try))= 119
j loop = 9
select_hgeocode_geo5_6_try2[cells_used]= 7
select_hgeocode_geo5_6_try2[C000]= 299
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  5  7 11  8 12 10  6]
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  5  7 11  8 12 10  6]
select_hgeocode_geo5_6_try[C000]= 299
Yes
i= 0
0.22574424743652344
your here 1
your here 2
0.45038676261901855
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.02091217041015625

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

4.356424331665039
len(select_hgeocode_geo5_6_try))= 101
j loop = 10
select_hgeocode_geo5_6_try2[cells_used]= 9
select_hgeocode_geo5_6_try2[C000]= 240
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  5  6  8 12 10]
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  4  5  6  8 12 10]
select_hgeocode_geo5_6_try[C000]= 240
Yes
i= 0
0.18906283378601074
your here 1
your here 2
0.5633070468902588
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.02289104461669922

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

4.275922060012817
len(select_hgeocode_geo5_6_try))= 80
j loop = 11
select_hgeocode_geo5_6_try2[cells_used]= 10
select_hgeocode_geo5_6_try2[C000]= 163
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  5  4  8  6 10]
select_hgeocode_geo5_6_try[C000]= [ 1  2  3  5  4  8  6 10]
select_hgeocode_geo5_6_try[C000]= 163
Yes
i= 0
0.150068998336792
your here 1
your here 2
0.4048151969909668
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.022148847579956055

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

4.080109119415283
len(select_hgeocode_geo5_6_try))= 60
j loop = 12
select_hgeocode_geo5_6_try2[cells_used]= 2
select_hgeocode_geo5_6_try2[C000]= 109
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 9]
select_hgeocode_geo5_6_try[C000]= [1 2 3 9]
select_hgeocode_geo5_6_try[C000]= 109
Yes
i= 0
0.11143326759338379
your here 1
your here 2
0.15019774436950684
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.020772933959960938
3.57151198387146
len(select_hgeocode_geo5_6_try))= 53
j loop = 13
select_hgeocode_geo5_6_try2[cells_used]= 3
select_hgeocode_geo5_6_try2[C000]= 93
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3 9]
select_hgeocode_geo5_6_try[C000]= [1 2 3 9]
select_hgeocode_geo5_6_try[C000]= 93
Yes
i= 0
0.09961915016174316
your here 1
your here 2
0.15793895721435547
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.021580219268798828
3.644826889038086
len(select_hgeocode_geo5_6_try))= 46
j loop = 14
select_hgeocode_geo5_6_try2[cells_used]= 2
select_hgeocode_geo5_6_try2[C000]= 76
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= 76
Yes
i= 0
0.086029052734375
your here 1
your here 2
0.1217043399810791
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.02057504653930664

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

3.5322561264038086
len(select_hgeocode_geo5_6_try))= 36
j loop = 15
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 65
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= 65
Yes
i= 0
0.06824302673339844
your here 1
your here 2
0.07213521003723145
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.020185232162475586
3.5636539459228516
len(select_hgeocode_geo5_6_try))= 32
j loop = 16
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 60
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 3 2]
select_hgeocode_geo5_6_try[C000]= [1 3 2]
select_hgeocode_geo5_6_try[C000]= 60
Yes
i= 0
0.061270713806152344
your here 1
your here 2
0.401170015335083
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.020886898040771484
3.426347017288208
len(select_hgeocode_geo5_6_try))= 7
j loop = 17
select_hgeocode_geo5_6_try2[cells_used]= 1
select_hgeocode_geo5_6_try2[C000]= 12
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= [1 2 3]
select_hgeocode_geo5_6_try[C000]= 12
Yes
i= 0
0.013829708099365234
your here 1
your here 2
0.05003213882446289
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.020261049270629883
3.3330280780792236
len(select_hgeocode_geo5_6_try))= 5
j loop = 18
select_hgeocode_geo5_6_try2[cells_used]= 0
select_hgeocode_geo5_6_try2[C000]= 9
len select_hgeocode_geo5_6_try3_missing 0
select_hgeocode_geo5_6_try_missing_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try_missing_h_geocode_y Series([], Name: h_geocode_y, dtype: int64)
len select_hgeocode_geo4_2_2 1764981
len select_hgeocode_geo4_2_2_missing 0
len select_hgeocode_geo4_2_2_exist 1764981
len select_hgeocode_geo4_2_2_missing2 0
len select_hgeocode_geo4_2_2_final 1764981
len select_hgeocode_geo5_6_try_missing 0
len select_hgeocode_geo5_6_try_missing_final 0
len select_hgeocode_geo5_6_try_missing_final_h_geocode_x Series([], Name: h_geocode_x, dtype: float64)
select_hgeocode_geo5_6_try[C000]= [2 1 3]
select_hgeocode_geo5_6_try[C000]= [2 1 3]
select_hgeocode_geo5_6_try[C000]= 9
Yes
i= 0
0.01016378402709961
your here 1
your here 2
0.0968770980834961
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.020286083221435547

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

3.3296539783477783
len(select_hgeocode_geo5_6_try))= 0

In [407]:
# # select_hgeocode_geo4_2_2 is the dataframe that has the connection between h_geocode_y and nearest h_geocode_x
# # from nearest (w_geocode_x)

# select_hgeocode_geo4_2_2_try1 = select_hgeocode_geo4_2_2.copy()


# for i in range(2,20):
#     print('i loop =',i)
#     globals()['select_hgeocode_geo5_6_try_try%s_dic' % i] ={}
#     globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % i] =[]
#     globals()['cells2_2030_1_try%s' % i] = []
#     globals()['list_cells2_2030_1_try%s' % i] = []
#     globals()['select_hgeocode_geo5_6_try%s' % (i+1)] = []
    
    
    
# #     print(globals()['select_hgeocode_geo5_6_try_try%s' % i])
    
# #     print(globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)])

    
#     globals()['select_hgeocode_geo5_6_try_try%s_dic' % i] , globals()['select_hgeocode_geo4_2_2_try%s' % i], globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)] = try_function(globals()['select_hgeocode_geo5_6_try%s' % i], globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)], globals()['select_hgeocode_geo4_2_2_try%s' % (i-1)])
    
#     globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0]['loop_num'] = i
    
#     globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)], globals()['cells2_2030_1_try%s' % i], globals()['select_hgeocode_geo5_6_try_try%s_dic' % i] = find_cells_SLR(globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0], globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)][0])
    
#     my_list_2, my_list_3,my_list_4 =  cells_calc_x(globals()['select_hgeocode_geo5_6_try_try%s_dic' % i],globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)], globals()['cells2_2030_1_try%s' % i])
#     globals()['select_hgeocode_geo5_6_try_try%s_dic' % i]= dmg_calc(my_list_2, my_list_3,globals()['select_hgeocode_geo5_6_try_try%s_dic' % i])
    
# #     globals()['select_hgeocode_geo5_6_try_try%s_dic_full' % i] = dataframe_full(globals()['select_hgeocode_geo5_6_try_try%s_dic' % i])
    
#     globals()['Emp_cells2_2030_1_try_list%s' % i]  =list_4_calc(my_list_4,globals()['cells2_2030_1_try%s' % i], Emp_cells2_dic)
# #     globals()['Emp_cells2_2030_1_try_list%s' % i]  = list4_2_full(globals()['Emp_cells2_2030_1_try_list%s' % i])
    
    
#     globals()['list_cells2_2030_1_try%s' % i] = list(deepflatten(globals()['cells2_2030_1_try%s' % i], depth=1))
#     globals()['Emp_cells2_2030_1_try%s_dic' % i] = {}
#     for k in range(0, len(Emp_cells2_dic2)):
#         globals()['Emp_cells2_2030_1_try%s_dic' % i][k] = globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)][k].loc[~globals()['Emp_cells2_2030_1_try%s_dic' % (i-1)][k]['fd_id'].isin(globals()['list_cells2_2030_1_try%s' % i])]

#     globals()['select_hgeocode_geo5_6_try%s' % (i+1)] = globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0].loc[globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0]['C000']!=globals()['select_hgeocode_geo5_6_try_try%s_dic' % i][0]['cells_used']]
#     print('len(select_hgeocode_geo5_6_try))=',len(globals()['select_hgeocode_geo5_6_try%s' % (i+1)]) )
#     if len(globals()['select_hgeocode_geo5_6_try%s' % (i+1)])>0:
#         if len(globals()['select_hgeocode_geo5_6_try%s' % (i+1)])!=len(globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)]):
#             continue
#         else: break
#     else: 
#         break

In [408]:
Emp_cells2_2030_1_try_list2

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage20,damage21,damage22,damage23,damage24,damage25,damage26,damage27,damage28,damage29
0,120150105052018,870915.0,491733638,76RVVX8V+X39-4-3-2-3,120150105023020,RES,RES1-1SNB,W,1.0,1782.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,120150105052018,870923.0,491733655,76RVVX9Q+53C-3-2-4-3,120150105023020,RES,RES1-1SNB,M,1.0,1827.0,...,0.0,0.0,0.0,0.0,25.139886,44.824926,62.869548,86.819674,97.892508,100.0
2,120150105052018,872788.0,491736408,76RVVX8R+JXV-4-3-3-3,120150105023020,RES,RES1-1SNB,W,1.0,1880.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,120150105052018,872791.0,491736414,76RVVX9R+4F2-4-2-3-4,120150105023020,RES,RES1-1SNB,W,1.0,1965.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4,120150105052018,872792.0,491736416,76RVVXCR+42H-7-4-6-4,120150105023020,RES,RES1-1SNB,W,1.0,2139.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4422,120710403042019,7354632.0,498219339,76RWH8VW+H8P-0-0-0-0,120710403042033,RES,RES1-1SNB,W,1.0,1391.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4423,120710403042019,7356543.0,498221236,76RWH8WX+7MX-0-0-0-0,120710403042033,RES,RES1-1SNB,W,1.0,1391.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4424,120710403042019,7356589.0,498221284,76RWH8VX+JJ3-0-0-0-0,120710403042033,RES,RES1-1SNB,W,1.0,1402.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4425,120710403113012,7356759.0,498221458,76RWH9R5+393-0-0-0-0,120710403112012,RES,RES1-1SNB,M,1.0,1376.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4426,120710403113012,7356801.0,498221500,76RWH9Q6+PMM-0-0-0-0,120710403112012,RES,RES1-1SNB,M,1.0,1376.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

In [409]:
# len(select_hgeocode_geo5_6_try20)

In [410]:
len(globals()['select_hgeocode_geo5_6_try{0}'.format(2)])

1800

In [411]:
for i in range(2,30):
    if len(globals()['select_hgeocode_geo5_6_try{0}'.format(i)])==0:
        loop_ended = i-1
        break
loop_ended

18

In [412]:
for i in range(1,loop_ended+1):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

In [413]:
for i in range(1,loop_ended+1):
    globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(i)] = globals()['Emp_cells2_2030_1_try{0}_dic'.format(i)][0]

In [414]:
for i in range(1,loop_ended+1):
    del globals()['Emp_cells2_2030_1_try{0}_dic'.format(i)]

In [415]:
# Emp_cells2_2030_1_try5_dic_0 = Emp_cells2_2030_1_try5_dic[0]
# Emp_cells2_2030_1_try5_dic={}

In [416]:
len(Emp_cells2_2030_1_try1_dic_0)- len( globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)])

7404

In [417]:
select_hgeocode_geo5_6_try_try2_dic_missing['C000'].sum()

125

In [418]:
globals()['Emp_cells2_2030_1_try{0}_'.format(loop_ended)]=[]
globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)]=[]


globals()['Emp_cells2_2030_1_try{0}_'.format(loop_ended)] = globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)].select_dtypes(exclude=['geometry','object'])
globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)] = globals()['Emp_cells2_2030_1_try{0}_'.format(loop_ended)].groupby(["h_geocode"], as_index=False).sum()

In [419]:
globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)]

             h_geocode        fd_id  found_ht  cell  min_2030
0      120150101001000   4425817035      13.5     9       0.0
1      120150101001005   3441594921      10.5     7       0.0
2      120150101001008    491656353       0.5     1       0.0
3      120150101001009  23108594843      54.0    47       0.0
4      120150101001010   2458356555       3.5     5       0.0
...                ...          ...       ...   ...       ...
21119  121150027481003  19226673394      19.5    39       0.0
21120  121150027481009  12332393747      12.5    25       0.0
21121  121150027481010   3450388481       3.5     7       0.0
21122  121150027482003   2464608641       2.5     5       0.0
21123  121150027483006    988841711       1.0     2       0.0

[21124 rows x 5 columns]

In [420]:
# number of cells are more than number of projected employees

Emp_home_select_2030_new_values_merge_u = Emp_home_select_2030_new_values_merge[Emp_home_select_2030_new_values_merge['C000']- Emp_home_select_2030_new_values_merge['cell'] <= 0]


len(Emp_home_select_2030_new_values_merge_u)

7535

In [421]:
Emp_home_select_2030_new_values_merge_u  = Emp_home_select_2030_new_values_merge_u.astype({
            "C000":'int64',"CNS01":'int64',"CNS02":'int64',"CNS03":'int64',
            "CNS04":'int64',"CNS05":'int64',"CNS06":'int64',"CNS07":'int64',
            "CNS08":'int64',"CNS09":'int64',"CNS10":'int64',"CNS11":'int64',
            "CNS12":'int64',"CNS13":'int64',"CNS14":'int64',"CNS15":'int64',
            "CNS16":'int64',"CNS17":'int64',"CNS18":'int64',"CNS19":'int64',
            "CNS20":'int64', "CR01":'int64','CR02':'int64' ,'CR03' :'int64',
            "CR04" :'int64', "CR05":'int64','CR07':'int64' ,"CA01" :'int64',
            "CA02" :'int64',"CA03" :'int64',"CE01":'int64' ,"CE02" :'int64',
            "CE03" :'int64',"CT01" :'int64',"CT02":'int64' ,"CD01" :'int64',
            "CD02" :'int64',"CD03" :'int64',"CD04":'int64' ,"CS01" :'int64',
            "CS02" :'int64',"cell":'int64'})

In [422]:
Emp_home_select_2030_new_values_merge_u = Emp_home_select_2030_new_values_merge_u.reset_index()

In [423]:
def cells_calc_cells(Emp_home, Emp_cells):
    import time
    from scipy.interpolate import interp1d
    from iteration_utilities import deepflatten
    import random
    start = time.time()
    

    for i in range(0,len(Emp_home)):
        print('i=',i)

        temp22=[]
        temp30 = [[498226819,498226820,498226821]] #one number after Emp_cells2['row_num'].max()
        # temp25 = {}
        my_list = []
        my_dicts = {}
        Emp_home[i]['cells_used'] = ''
        for q in range (0,len(Emp_home[i])):
            temp22_1 = Emp_cells[i][Emp_cells[i]['h_geocode']== Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("h_geocode")]]
            list_temp30 = list(deepflatten(temp30, depth=1))
            temp22 = temp22_1.loc[~temp22_1['fd_id'].isin(list_temp30)]
            temp23 = sorted(temp22['fd_id'])
            if len(temp23) == 0:
#                 print('temp23=',temp23)
                temp24 = temp23
#                 print('len(temp24)=', len(temp24))
                
            if Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")] > len(temp23):
                temp24 = temp23
            else:
#                 temp23 = sorted(temp22['fd_id'])
                temp24 = random.sample(population=temp23, k=Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")])
                temp24 = sorted(temp24)

#             temp24= temp23[0:Emp_home[i].iloc[q,Emp_home[i].columns.get_loc("C000")]]
            temp25 = temp22.loc[temp22['fd_id'].isin(temp24)]
            temp30.append(temp24)

            my_list.append(temp25)
            pd.DataFrame(Emp_home[i]).iloc[q,Emp_home[i].columns.get_loc("cells_used")]= len(temp24)

        cells2_2030=temp30 
        
    end = time.time()
    print(end - start)
    return cells2_2030
        
#         for key, value in en

In [424]:
Emp_home_select_2030_new_values_merge_u['cell'].sum()

159455

In [425]:

Emp_home_select_2030_new_values_merge_u  = Emp_home_select_2030_new_values_merge_u.drop(['cell'],axis=1)

Emp_home_select_2030_new_values_merge_u = pd.merge(Emp_home_select_2030_new_values_merge_u, globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)],  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

In [426]:
Emp_home_select_2030_new_values_merge_u['cell'].sum()

143261.0

In [427]:
globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)], cells2_2030_2, Emp_home_select_2030_new_values_merge_u_dic  = find_cells_SLR(Emp_home_select_2030_new_values_merge_u, globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)])

No
i= 0
19.43581223487854
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

109.35129189491272
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.11689591407775879

In [428]:
globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)][0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120150205012069,491927247,0.5,POINT (-82.13573 26.96423),1,0.0
3,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,NaN
4,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,NaN
...,...,...,...,...,...,...
349361,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
349362,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
349363,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
349364,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
349365,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [429]:
import warnings
warnings.filterwarnings("ignore")

In [430]:
import numpy as np

def unique(list1):
    x = np.array(list1)
    print(np.unique(x))

In [431]:
Emp_cells2['fd_id'].max()

498226804

In [432]:

for k in range(0,len(Raster_file_paths)):
    if k in list_iterate:
        print('Skipped')
    else:
        print(k)

Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
6
7
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
14
15
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
22
23
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
30
31
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
38
39
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
46
47
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
54
55
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
62
63
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
70
71
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
78
79
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
86
87
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
94
95
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
102
103
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
110
111
Skipped
Skipped
Skipped
Skipped
Skipped
Skipped
118
119

In [433]:
def cells_calc(i, Emp_home, Emp_cells, cells2_2030):
    import time
    from scipy.interpolate import interp1d
    from iteration_utilities import deepflatten
#     start = time.time()
    
    
#     my_list_2=[]
#     my_list_3=[]
#     my_list_4=[]

#     for i in range(0,len(Emp_home)):   # 0 , len(Emp_home)
#     print('i=',i)


    temp22=[]
    temp30 = [[498226819,498226820,498226821]] #one number after Emp_cells2['row_num'].max()
    # temp25 = {}
    my_list = []
#         my_list_2=[]
#         my_list_3=[]
    my_dicts = {}
    Emp_home['cells_used'] = ''
    for q in range (0,len(Emp_home)):
        temp22_1 = Emp_cells[Emp_cells['h_geocode']== Emp_home.iloc[q,Emp_home.columns.get_loc("h_geocode")]]
        list_temp30 = list(deepflatten(temp30, depth=1))
        temp22 = temp22_1.loc[~temp22_1['fd_id'].isin(list_temp30)]
        temp23 = sorted(temp22['fd_id'])
        temp24 = cells2_2030[1:][q]
        temp25 = temp22.loc[temp22['fd_id'].isin(temp24)]
        temp30.append(temp24)
        my_list.append(temp25)
        pd.DataFrame(Emp_home).iloc[q,Emp_home.columns.get_loc("cells_used")]= len(temp24)

    for key, value in enumerate(my_list):
        my_dicts[key] = value

    Emp_home['C000_dmg']=''
    Emp_home['C000_dmg_mean']=''
    result_temp1 = []
    temp26 = []
    temp26_2 = []
    temp26_4 = []
    result_2 = []
    result_3 = []
    result_4 = []
    for k in range (0,len(Emp_home)):
        result_1 = []
        for value in my_dicts[k]["min_2030"]:
            result_temp1= value
            result_1.append(result_temp1)
        my_dicts[k]["SLR"] = result_1 #maybe replace result_1 with min_2030 (we don't need the previous 3 lines)
        my_dicts[k]['damage_SLR']=''
        for j in range(0, len(my_dicts[k])):
#                 print('row_num=', pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("row_num")])
#                 print('SLR=',pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] )
            if pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] == 0:
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = 0
            elif pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")] > 7:
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = 100
            else: 
                pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] = interp1d(WD_Coast_final['Depth.1']+pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("found_ht")]*0.3048,WD_Coast_final['R11N'],
                                                           bounds_error=False, fill_value=(0,1))(pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("SLR")])
#                 print('damage=',pd.DataFrame(my_dicts[k]).iloc[j,my_dicts[k].columns.get_loc("damage_SLR")] )


        my_dicts[k] = my_dicts[k].astype({"damage_SLR":'float'})
        temp26 = len(my_dicts[k][my_dicts[k]["damage_SLR"]>50]) # damage is larger than 50%
        result_2.append(temp26)
        temp26_2 = (my_dicts[k][my_dicts[k]["damage_SLR"]>50])["damage_SLR"].mean()
        result_3.append(temp26_2)
        temp26_4 =my_dicts[k]["damage_SLR"]
        result_4.append(temp26_4)
    my_list_2.append(result_2)
    my_list_3.append(result_3)
    my_list_4.append(result_4)

#     end = time.time()
#     print(end - start)
    return my_list_2, my_list_3,my_list_4

In [435]:
globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)][0]

,h_geocode,fd_id,found_ht,geometry,cell,min_2030
0,120150201011010,491767073,0.5,POINT (-82.01033 27.00403),1,NaN
1,120150202061034,491915584,0.5,POINT (-82.11065 27.02356),1,NaN
2,120150205012069,491927247,0.5,POINT (-82.13573 26.96423),1,0.0
3,120150304011001,492073948,1.5,POINT (-82.30614 26.92354),1,NaN
4,120210110032002,492083201,8.0,POINT (-81.72803 25.91364),1,NaN
...,...,...,...,...,...,...
349361,120710303001023,498226804,1.5,POINT (-81.60443 26.70252),1,NaN
349362,120710302011004,498226048,0.5,POINT (-81.73996 26.69724),1,NaN
349363,120710302011004,498226050,1.5,POINT (-81.74073 26.69308),1,NaN
349364,120710302012002,498226064,1.5,POINT (-81.74024 26.69023),1,NaN
349365,120710302011004,498226086,1.5,POINT (-81.73364 26.69836),1,NaN

In [436]:
Emp_home_select_2030_new_values_merge_u['cell'].sum()

143261.0

In [437]:

# Emp_home_select_2030_new_values_merge_u  = Emp_home_select_2030_new_values_merge_u.drop(['cell'],axis=1)

# Emp_home_select_2030_new_values_merge_u = pd.merge(Emp_home_select_2030_new_values_merge_u, globals()['Emp_cells2_2030_1_try{0}_sum'.format(loop_ended)],  how='left', 
#                 left_on=['h_geocode'], right_on = ['h_geocode'])

In [438]:
Emp_home_select_2030_new_values_merge_u['cell'].sum()

143261.0

In [439]:
# from concurrent.futures import ProcessPoolExecutor

In [440]:
from joblib import Parallel, delayed

In [441]:
del zs2_dic

In [442]:
my_list_2=[]
my_list_3=[]
my_list_4=[]

start = time.time()

# Step 3: Use the provided code snippet to parallelize the calculations using the 'worker' function
result = Parallel(n_jobs=5)(delayed(cells_calc)(i, Emp_home_select_2030_new_values_merge_u_dic[i], globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)][i], cells2_2030_2) for i in range(0,len(Raster_file_paths_new)))

# Convert the result to a dictionary with keys as indices
zs2_dic2 = dict(enumerate(result))

# Step 4: After calculating the results, retrieve the values from the 'zs2_dic' dictionary and store them in the lists 'my_list_2', 'my_list_3', and 'my_list_4'
my_list_2 = [zs2_dic2[i][0] for i in range(len(Raster_file_paths_new))]
my_list_3 = [zs2_dic2[i][1] for i in range(len(Raster_file_paths_new))]
my_list_4 = [zs2_dic2[i][2] for i in range(len(Raster_file_paths_new))]

end = time.time()
print(end - start)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

279.2200360298157

In [443]:
# my_list_2, my_list_3,my_list_4  = cells_calc(Emp_home_select_2030_new_values_merge_u_dic,globals()['Emp_cells2_try{0}_dic2'.format(loop_ended)],cells2_2030_2)

In [444]:
my_list_2

[[[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   ...]],
 [[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   ...]],
 [[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   ...]],
 [[0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,

In [445]:
my_list_2_final={}
my_list_3_final={}
my_list_4_final={}

for l in range(0,len(Raster_file_paths_new)):
    my_list_2_final[l]= my_list_2[l][0]
    my_list_3_final[l]= my_list_3[l][0]
    my_list_4_final[l]= my_list_4[l][0]
    
my_list_2={}
my_list_3={}
my_list_4={}

In [446]:
# cells2_2030_2_list = list(deepflatten(cells2_2030_2[1:], depth=1))

Emp_cells2_dic_list4_2 =list_4_calc(my_list_4_final,cells2_2030_2,Emp_cells2_dic)

In [447]:
Emp_cells2_dic_list4_2

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage20,damage21,damage22,damage23,damage24,damage25,damage26,damage27,damage28,damage29
0,120150205012069,1941.0,491927247,76RVXV77+MPR-3-3-4-2,120150205012065,RES,RES1-1SNB,W,1.0,1462.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.000000,100.000000,100.000000
1,120810008132000,1965.0,492084718,76VVCFQR+MVG-3-3-4-2,120810008072014,RES,RES1-1SNB,W,1.0,1962.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.625502,10.940463,31.257199
2,120210101104009,2512.0,494730579,76RW759M+CH4-3-3-3-4,120210101104009,RES,RES1-1SNB,M,1.0,1284.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.000000,100.000000,100.000000
3,120150101001005,793949.0,491656308,76RWW8WJ+HQG-3-3-3-4,120150101002000,RES,RES1-1SNB,W,1.0,1200.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
4,120150101001008,793994.0,491656353,76VW27GW+GVV-3-3-4-2,120150101002000,RES,RES1-1SNB,W,1.0,1326.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16992,120710402113048,7359217.0,498223918,76RWJ98X+9W7-0-0-0-0,120710402037051,RES,RES1-1SNB,M,1.0,791.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
16993,120710402113048,7359223.0,498223931,76RWJC82+MP2-0-0-0-0,120710402037052,RES,RES1-1SNB,M,1.0,1011.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
16994,120710402113048,7359224.0,498223933,76RWJC82+MP2-0-0-0-0,120710402037052,RES,RES1-1SNB,M,1.0,1011.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
16995,120710402113048,7359258.0,498223956,76RWJC82+GM4-0-0-0-0,120710402037052,RES,RES1-1SNB,M,1.0,1011.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
16996,120710302051004,7361576.0,498226248,76RWP73R+PGF-0-0-0-0,120710302031002,RES,RES1-1SNB,W,1.0,1519.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.000000,100.000000,100.000000

In [448]:
# Emp_cells2_dic_list4_2[Emp_cells2_dic_list4_2['damage89']>0]

In [449]:
# Emp_cells2_dic_list4_2 = list4_2_full(Emp_cells2_dic_list4_2)

In [450]:
# Emp_cells2_dic_list4_2[Emp_cells2_dic_list4_2['damage179']>0]

In [451]:
Emp_home_select_2030_new_values_merge_u_dic = dmg_calc(my_list_2_final, my_list_3_final,Emp_home_select_2030_new_values_merge_u_dic)

In [452]:
# Emp_home_select_2030_new_values_merge_u_dic_full = dataframe_full(Emp_home_select_2030_new_values_merge_u_dic)

In [453]:
# len(Emp_home_select_2030_new_values_merge_u_dic_full)

In [454]:
Emp_home_select_2030_new_values_merge_u_dic[0]['C000'].sum()

18102

In [455]:
# unique(Emp_home_select_2030_new_values_merge_u_dic[0]['C000_dmg_mean'])

In [456]:
list_cells2_2030_2 = list(deepflatten(cells2_2030_2, depth=1))
Emp_cells2_2030_2_dic = []
# for i in range(0, len(Emp_cells2_dic2)):

Emp_cells2_2030_2_dic =globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)].loc[~globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)]['fd_id'].isin(list_cells2_2030_2)]
len(Emp_cells2_2030_2_dic)

332369

In [457]:
Emp_cells2_2030_2_=[]
Emp_cells2_2030_2_sum=[]

# for i in range(0, len(Emp_cells2_dic2)):
Emp_cells2_2030_2_ = Emp_cells2_2030_2_dic.select_dtypes(exclude=['geometry','object'])
Emp_cells2_2030_2_sum = Emp_cells2_2030_2_.groupby(["h_geocode"], as_index=False).sum()
Emp_cells2_2030_2_sum

             h_geocode        fd_id  found_ht  cell  min_2030
0      120150101001000   3934160594      12.0     8       0.0
1      120150101001005   1474969444       4.5     3       0.0
2      120150101001009  23108594843      54.0    47       0.0
3      120150101001010   2458356555       3.5     5       0.0
4      120150101001011    491661116       1.5     1       0.0
...                ...          ...       ...   ...       ...
19878  121150027472071    988826660       1.0     2       0.0
19879  121150027481003  10351110515      10.5    21       0.0
19880  121150027481009  12332393747      12.5    25       0.0
19881  121150027481010   3450388481       3.5     7       0.0
19882  121150027482003   2464608641       2.5     5       0.0

[19883 rows x 5 columns]

In [458]:

len(globals()['Emp_cells2_2030_1_try{0}_dic_0'.format(loop_ended)])-len(Emp_cells2_2030_2_dic)

16997

In [459]:
len(Emp_cells2)-len(Emp_cells2_2030_2_dic)

54015

In [460]:
Emp_home_select_2030_new_values_merge_u_dic[0]['C000'].sum()

18102

In [461]:
OD_main=pd.read_pickle('/Users/Malihafez/Documents/Mobile/Data/USA_Buildings/Florida/OD_main.pkl')

In [462]:
OD_main= OD_main.astype({"h_geocode":'int64'})
OD_main= OD_main.astype({"w_geocode":'int64'})

In [463]:
Emp_home_select_2030_new_values_merge_u_try2 = Emp_home_select_2030_new_values_merge_u_dic[0].loc[Emp_home_select_2030_new_values_merge_u_dic[0]['C000']!=Emp_home_select_2030_new_values_merge_u_dic[0]['cells_used']]
Emp_home_select_2030_new_values_merge_u_try2

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CS02,createdate,geometry,fd_id,found_ht,cell,min_2030,cells_used,C000_dmg,C000_dmg_mean
5_a_0,12,115,002605,2004,121150026052004,Block 2004,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-82.35307 26.95837, -82.35306 26.959...",NaN,NaN,NaN,NaN,0,0,NaN
18_a_0,12,115,001301,2007,121150013012007,Block 2007,G5040,NaN,NaN,NaN,...,0,20231016,"POLYGON ((-82.46383 27.34403, -82.46351 27.344...",NaN,NaN,NaN,NaN,0,0,NaN
41_a_0,12,087,971501,1003,120879715011003,Block 1003,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-81.50261 24.66138, -81.50261 24.661...",NaN,NaN,NaN,NaN,0,0,NaN
61_a_0,12,115,001702,1003,121150017021003,Block 1003,G5040,NaN,NaN,NaN,...,2,20231016,"POLYGON ((-82.49564 27.29597, -82.49564 27.296...",NaN,NaN,NaN,NaN,0,0,NaN
66_a_0,12,071,001919,2000,120710019192000,Block 2000,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-81.92193 26.49757, -81.92172 26.500...",NaN,NaN,NaN,NaN,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7448_a_0,12,021,000102,1067,120210001021067,Block 1067,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-81.80399 26.14697, -81.80367 26.147...",NaN,NaN,NaN,NaN,0,0,NaN
7451_a_0,12,115,002744,1028,121150027441028,Block 1028,G5040,NaN,NaN,NaN,...,4,20231016,"POLYGON ((-82.23802 27.10697, -82.23795 27.112...",986058720.0,1.0,2.0,0.0,2,0,NaN
7494_a_0,12,081,001202,3035,120810012023035,Block 3035,G5040,NaN,NaN,NaN,...,0,20231016,"POLYGON ((-82.59252 27.49783, -82.59157 27.497...",NaN,NaN,NaN,NaN,0,0,NaN
7518_a_0,12,071,040305,1042,120710403051042,Block 1042,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-81.62493 26.60327, -81.62492 26.603...",NaN,NaN,NaN,NaN,0,0,NaN
7527_a_0,12,071,001207,2006,120710012072006,Block 2006,G5040,NaN,NaN,NaN,...,1,20231016,"POLYGON ((-81.84636 26.56767, -81.84628 26.567...",NaN,NaN,NaN,NaN,0,0,NaN

In [464]:
def try_function2(Emp_home_select_2030_new_values_merge_u_try2,Emp_cells2_2030_2_sum):

    Emp_home_select_2030_new_values_merge_u_try2['C000'] = Emp_home_select_2030_new_values_merge_u_try2['C000']- Emp_home_select_2030_new_values_merge_u_try2['cells_used']

    Emp_home_select_2030_new_values_merge_u_try3 = pd.merge(Emp_home_select_2030_new_values_merge_u_try2, OD_main,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])
    
    Emp_home_select_2030_new_values_merge_u_try4 = pd.merge(Emp_home_select_2030_new_values_merge_u_try3, Emp_work_geo_select,  how='left', 
                left_on=['w_geocode'], right_on = ['w_geocode'])
    
    Emp_home_select_2030_new_values_merge_u_try4['geometry_y']\
    = Emp_home_select_2030_new_values_merge_u_try4['geometry_y'].to_crs({'init': 'epsg:4326'})

    Emp_home_select_2030_new_values_merge_u_try5 = []
    Emp_home_select_2030_new_values_merge_u_try5 = Emp_home_select_2030_new_values_merge_u_try4.dropna(subset=['geometry_y'])


    print('step1 done')
    
    Emp_home_select_2030_new_values_merge_u_try5['centr_x'] = ''
    Emp_home_select_2030_new_values_merge_u_try5['centr_y'] = ''
  
    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5)):
        Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_x")]\
        = Emp_home_select_2030_new_values_merge_u_try5.iloc\
        [n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("geometry_x")].centroid.wkt

        Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_y")]\
        = Emp_home_select_2030_new_values_merge_u_try5.iloc\
        [n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("geometry_y")].centroid.wkt
    
    
    Emp_home_select_2030_new_values_merge_u_try5['centr_x'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_merge_u_try5['centr_x'])
    Emp_home_select_2030_new_values_merge_u_try5['centr_y'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_merge_u_try5['centr_y'])

    Emp_home_select_2030_new_values_merge_u_try5 = gpd.GeoDataFrame(Emp_home_select_2030_new_values_merge_u_try5, geometry='centr_x')
    Emp_home_select_2030_new_values_merge_u_try5 = gpd.GeoDataFrame(Emp_home_select_2030_new_values_merge_u_try5, geometry='centr_y')
    
    print('step2 done')

    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5)):
        Emp_home_select_2030_new_values_merge_u_try5.iloc[n, Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_x")] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_merge_u_try5.iloc[n, Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_x")])
        Emp_home_select_2030_new_values_merge_u_try5.iloc[n, Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_y")] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_merge_u_try5.iloc[n, Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_y")])
    
    coord_list_x =  Emp_home_select_2030_new_values_merge_u_try5['centr_x'].geometry.apply(lambda p: list(p.coords)[0])
    coord_list_y =  Emp_home_select_2030_new_values_merge_u_try5['centr_y'].geometry.apply(lambda p: list(p.coords)[0])
    Emp_home_select_2030_new_values_merge_u_try5['centr_x_co'] = coord_list_x
    Emp_home_select_2030_new_values_merge_u_try5['centr_y_co'] = coord_list_y
    
    from geopy.distance import geodesic as GD  

    Emp_home_select_2030_new_values_merge_u_try5['dist'] = ''
    
    print('step3 done')

    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5)):
        Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("dist")]\
        = GD(Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_x_co")],Emp_home_select_2030_new_values_merge_u_try5.iloc[n,Emp_home_select_2030_new_values_merge_u_try5.columns.get_loc("centr_y_co")]).km

    print('step4 done')
        
    #to get the min dist from orginal h_geocode (h_geocode_y) to w_geocode

    Emp_home_select_2030_new_values_merge_u_try5_ = Emp_home_select_2030_new_values_merge_u_try5.select_dtypes(exclude=['geometry'])

    Emp_home_select_2030_new_values_merge_u_try5_1 = Emp_home_select_2030_new_values_merge_u_try5_.groupby(["h_geocode"], as_index=False).min()

    Emp_home_select_2030_new_values_merge_u_try5_1 = Emp_home_select_2030_new_values_merge_u_try5_1[['dist']]
    Emp_home_select_2030_new_values_merge_u_try5_2 = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_1,
                                                              Emp_home_select_2030_new_values_merge_u_try5,
                                                              how='left', left_on=['dist'], right_on = ['dist'])
    
    # h_geocode_x is h_geocode associated with each w_geocode
    # h_geocode_y is original h_geocode (projected employees)
    #geometry_x for h_geocode_y #geometry_y for w_geocode

    Emp_home_select_2030_new_values_merge_u_try5_OD = pd.merge(OD_main, Emp_home_select_2030_new_values_merge_u_try5_2,
                                                               how='right', left_on=['w_geocode'], right_on = ['w_geocode'])

    
    Emp_home_select_2030_new_values_merge_u_try5_OD = Emp_home_select_2030_new_values_merge_u_try5_OD.drop(['centr_x','centr_x','centr_x_co','centr_y_co'], axis = 1)
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_OD, Emp_cells2_2030_2_sum,  how='left', 
                left_on=['h_geocode_x'], right_on = ['h_geocode'])

    
    #cell_y for h_geocode_x (associate with each w_geocode)
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode =  Emp_home_select_2030_new_values_merge_u_try5_hgeocode.dropna(subset=['cell_y'])
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode = Emp_home_select_2030_new_values_merge_u_try5_hgeocode.astype({"h_geocode":'int64'})

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode['geometry_x1'] = Emp_home_select_2030_new_values_merge_u_try5_hgeocode['geometry_x']
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode['geometry_y1'] = Emp_home_select_2030_new_values_merge_u_try5_hgeocode['geometry_y']
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode = Emp_home_select_2030_new_values_merge_u_try5_hgeocode.drop(['geometry_x','geometry_y'], axis = 1)
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_hgeocode, Emp_home_geo,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo = Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.dropna(subset=['cell_y'])

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x'] = ''
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y'] = ''
    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo)):
        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_x")]\
        = Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc\
        [n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("geometry")].centroid.wkt

        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_y")]\
        = Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc\
        [n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("geometry_y1")].centroid.wkt

    print('step5 done')
    
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x'])
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y'] = gpd.GeoSeries.from_wkt(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y'])

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo = gpd.GeoDataFrame(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo, geometry='centr_x')
    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo = gpd.GeoDataFrame(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo, geometry='centr_y')

    print('step6 done')

    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo)):
        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n, Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_x")] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n, Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_x")])
        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n, Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_y")] = transform(lambda x, y: (y, x), Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n, Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_y")])
    
    print('step7 done')
    
    coord_list_x =  Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x'].geometry.apply(lambda p: list(p.coords)[0])
    coord_list_y =  Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y'].geometry.apply(lambda p: list(p.coords)[0])

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_x_co'] = coord_list_x

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['centr_y_co'] = coord_list_y

    Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo['dist_x'] = ''
    for n in range(0,len(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo)):
        Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("dist_x")]\
        = GD(Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_x_co")],Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.iloc[n,Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.columns.get_loc("centr_y_co")]).km

    print('step8 done')
    
    Emp_home_select_2030_new_values_merge_u_try5_4 = Emp_home_select_2030_new_values_merge_u_try5_hgeocode_geo.drop(['centr_x_co','centr_y_co','centr_x','centr_y'], axis = 1)


    Emp_home_select_2030_new_values_merge_u_try5_4_ = Emp_home_select_2030_new_values_merge_u_try5_4.drop(['cell_y'], axis = 1)

    Emp_cells2_2030_2_sum_ = Emp_cells2_2030_2_sum.copy()

    Emp_cells2_2030_2_sum_.rename(columns = {'cell':'cell_y'}, inplace = True)

    Emp_home_select_2030_new_values_merge_u_try5_4__ = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_4_,Emp_cells2_2030_2_sum_, how='left', left_on=['h_geocode_x'], right_on = ['h_geocode'],suffixes=('', '_remove'))

    Emp_home_select_2030_new_values_merge_u_try5_4_2 = Emp_home_select_2030_new_values_merge_u_try5_4__[Emp_home_select_2030_new_values_merge_u_try5_4__['cell_y']>Emp_home_select_2030_new_values_merge_u_try5_4__['C000']]
    
    Emp_home_select_2030_new_values_merge_u_try5_4_2 = Emp_home_select_2030_new_values_merge_u_try5_4_2.drop(['h_geocode_remove'],axis = 1)
    
    #Ignore the working zones that are the same as residential zones(when searching for new home zones for new employees)
    Emp_home_select_2030_new_values_merge_u_try5_4_2_1 =  Emp_home_select_2030_new_values_merge_u_try5_4_2[Emp_home_select_2030_new_values_merge_u_try5_4_2['w_geocode'] != Emp_home_select_2030_new_values_merge_u_try5_4_2['h_geocode_y']]

    Emp_home_select_2030_new_values_merge_u_try5_4_2_2 = Emp_home_select_2030_new_values_merge_u_try5_4_2_1[Emp_home_select_2030_new_values_merge_u_try5_4_2_1['w_geocode'] != Emp_home_select_2030_new_values_merge_u_try5_4_2_1['h_geocode_x']]

    
    #to get the min dist from orginal h_geocode (h_geocode_y) to w_geocode

    Emp_home_select_2030_new_values_merge_u_try5_4_2_2_ = Emp_home_select_2030_new_values_merge_u_try5_4_2_2.select_dtypes(exclude=['geometry'])

    Emp_home_select_2030_new_values_merge_u_try5_4_3 = Emp_home_select_2030_new_values_merge_u_try5_4_2_2_.groupby(["h_geocode_y"], as_index=False).min()
    Emp_home_select_2030_new_values_merge_u_try5_4_3 = Emp_home_select_2030_new_values_merge_u_try5_4_3[['dist']]
    Emp_home_select_2030_new_values_merge_u_try5_5 = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_4_3, Emp_home_select_2030_new_values_merge_u_try5_4_2_2,  how='left', 
                    left_on=['dist'], right_on = ['dist'])
    
    Emp_home_select_2030_new_values_merge_u_try5_5_1 = Emp_home_select_2030_new_values_merge_u_try5_5.reset_index()
    Emp_home_select_2030_new_values_merge_u_try5_5_1 = Emp_home_select_2030_new_values_merge_u_try5_5_1.astype({"index":'object'})
    Emp_home_select_2030_new_values_merge_u_try5_5_2 = Emp_home_select_2030_new_values_merge_u_try5_5_1.groupby(["h_geocode_y"], as_index=False)['dist_x'].min()
    Emp_home_select_2030_new_values_merge_u_try5_5_2 = Emp_home_select_2030_new_values_merge_u_try5_5_2[['dist_x']]
    Emp_home_select_2030_new_values_merge_u_try5_5_3 = pd.merge(Emp_home_select_2030_new_values_merge_u_try5_5_2, Emp_home_select_2030_new_values_merge_u_try5_5_1,  how='left', 
                left_on=['dist_x'], right_on = ['dist_x'])
    Emp_home_select_2030_new_values_merge_u_try5_5_6 = Emp_home_select_2030_new_values_merge_u_try5_5_3.drop_duplicates(subset=['h_geocode_y'])
    Emp_home_select_2030_new_values_merge_u_try5_5_6 = Emp_home_select_2030_new_values_merge_u_try5_5_6.astype({"C000":'int64'})

    return Emp_home_select_2030_new_values_merge_u_try5_5_6, Emp_home_select_2030_new_values_merge_u_try5_4_2_2_

In [465]:
Emp_home_select_2030_new_values_merge_u_try5_5_6, Emp_home_select_2030_new_values_merge_u_try5_4_2_2_ = try_function2(Emp_home_select_2030_new_values_merge_u_try2, Emp_cells2_2030_2_sum)

Emp_home_select_2030_new_values_merge_u_try5_5_6

step1 done
step2 done
step3 done
step4 done
step5 done
step6 done
step7 done
step8 done

,dist_x,index,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,...,fd_id_y,found_ht_y,min_2030_y,geometry_x1,geometry_y1,geometry,fd_id,found_ht,cell_y,min_2030
0,2.584469,0,0.176535,120150103011020,120150103012032,12,015,010301,1002,120150103011002,...,3.446669e+09,10.5,0.0,"POLYGON ((-82.05434 26.93868, -82.05432 26.938...","POLYGON ((-82.05228 26.93739, -82.05166 26.937...","POLYGON ((-82.05914 26.91076, -82.05913 26.911...",3446668633,10.5,7,0.0
1,2.8669,25,2.577578,120150103011023,120150104022005,12,015,010301,2015,120150103012015,...,4.034202e+10,93.5,0.0,"POLYGON ((-82.04649 26.91343, -82.04604 26.912...","POLYGON ((-82.05066 26.93473, -82.04956 26.935...","POLYGON ((-82.07079 26.91293, -82.07079 26.913...",40342023605,93.5,82,0.0
2,2.8669,10266,17.309958,120150103011023,120150104022005,12,015,030501,2057,120150305012057,...,4.034202e+10,93.5,0.0,"POLYGON ((-82.22406 26.91270, -82.22398 26.913...","POLYGON ((-82.05066 26.93473, -82.04956 26.935...","POLYGON ((-82.07079 26.91293, -82.07079 26.913...",40342023605,93.5,82,0.0
3,1.415021,485,2.075123,120150103011005,120150104021004,12,015,010402,1007,120150104021007,...,1.967373e+09,2.0,0.0,"POLYGON ((-82.06202 26.91107, -82.06203 26.911...","POLYGON ((-82.06545 26.92941, -82.06528 26.929...","POLYGON ((-82.06488 26.92035, -82.06486 26.920...",1967373125,2.0,4,0.0
4,2.325463,643,1.412605,120150103013019,120150104053007,12,015,010405,2005,120150104052005,...,2.155034e+11,599.5,0.0,"POLYGON ((-82.03284 26.89669, -82.03272 26.896...","POLYGON ((-82.04394 26.90387, -82.04372 26.904...","POLYGON ((-82.07083 26.90300, -82.07082 26.903...",215503403406,599.5,438,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556,2.812433,76069,2.027223,120150204022040,120150204021027,12,115,002745,1080,121150027451080,...,1.477126e+09,3.5,0.0,"POLYGON ((-82.18596 27.04521, -82.18572 27.045...","POLYGON ((-82.20346 27.03282, -82.20344 27.032...","POLYGON ((-82.17170 27.03026, -82.16819 27.030...",1477125928,3.5,3,0.0
560,3.098967,76143,1.462556,121150027461075,121150027422023,12,115,002746,1028,121150027461028,...,3.450550e+09,3.5,0.0,"POLYGON ((-82.13887 27.03872, -82.13886 27.039...","POLYGON ((-82.13366 27.03474, -82.13364 27.036...","POLYGON ((-82.16428 27.04425, -82.16278 27.045...",3450549845,3.5,7,0.0
561,4.108243,76221,3.935575,120150204021170,121150027461036,12,115,002746,1069,121150027461069,...,9.908324e+08,1.0,0.0,"POLYGON ((-82.12907 27.04193, -82.12831 27.042...","POLYGON ((-82.16367 27.01931, -82.16069 27.019...","POLYGON ((-82.13281 27.04680, -82.13205 27.047...",990832442,1.0,2,0.0
565,2.836071,76436,2.299126,121150027471015,121150027472050,12,115,002747,1027,121150027471027,...,1.484256e+09,1.5,0.0,"POLYGON ((-82.14160 27.04363, -82.14139 27.044...","POLYGON ((-82.12428 27.06175, -82.12412 27.061...","POLYGON ((-82.14553 27.04152, -82.14531 27.041...",1484256400,1.5,3,0.0
566,1.380903,76498,1.374591,121150027412003,121150027412041,12,115,002748,1011,121150027481011,...,3.943483e+09,4.0,0.0,"POLYGON ((-82.14477 27.08355, -82.14475 27.084...","POLYGON ((-82.15781 27.09027, -82.15775 27.090...","POLYGON ((-82.17201 27.08512, -82.17082 27.086...",3943483239,4.0,8,0.0

In [466]:
Emp_home_select_2030_new_values_merge_u_try5_4_2_2_

,w_geocode,h_geocode_x,dist,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,...,C000_dmg_mean,h_geocode,fd_id_y,found_ht_y,min_2030_y,dist_x,fd_id,found_ht,cell_y,min_2030
0,120150103011020,120150103012032,0.176535,12,015,010301,1002,120150103011002,Block 1002,G5040,...,NaN,120150103012032,3.446669e+09,10.5,0.0,2.584469,3446668633,10.5,7,0.0
1,120150103011020,120150104011000,0.176535,12,015,010301,1002,120150103011002,Block 1002,G5040,...,NaN,120150104011000,2.493819e+11,461.0,0.0,3.255427,249381879845,461.0,507,0.0
3,120150103011020,120150201012007,0.176535,12,015,010301,1002,120150103011002,Block 1002,G5040,...,NaN,120150201012007,8.163656e+10,109.0,0.0,7.901446,81636563932,109.0,166,0.0
4,120150103011020,120150201013001,0.176535,12,015,010301,1002,120150103011002,Block 1002,G5040,...,NaN,120150201013001,3.051775e+10,78.0,0.0,7.827273,30517751458,78.0,62,0.0
5,120150103011020,120150201033000,0.176535,12,015,010301,1002,120150103011002,Block 1002,G5040,...,NaN,120150201033000,1.017950e+11,155.5,0.0,10.843572,101795045243,155.5,207,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195130,121150027412009,121150027452004,1.531607,12,115,002748,2002,121150027482002,Block 2002,G5040,...,NaN,121150027452004,1.977776e+09,2.0,0.0,1.892079,1977776392,2.0,4,0.0
195131,121150027412009,121150027452038,1.531607,12,115,002748,2002,121150027482002,Block 2002,G5040,...,NaN,121150027452038,5.422259e+09,5.5,0.0,3.607635,5422258909,5.5,11,0.0
195132,121150027412009,121150027461000,1.531607,12,115,002748,2002,121150027482002,Block 2002,G5040,...,NaN,121150027461000,2.464530e+09,2.5,0.0,4.821643,2464529752,2.5,5,0.0
195134,121150027412009,121150027471005,1.531607,12,115,002748,2002,121150027482002,Block 2002,G5040,...,NaN,121150027471005,1.485164e+09,1.5,0.0,4.193886,1485164468,1.5,3,0.0
195136,121150027412009,121150027481003,1.531607,12,115,002748,2002,121150027482002,Block 2002,G5040,...,NaN,121150027481003,1.035111e+10,10.5,0.0,2.670016,10351110515,10.5,21,0.0

In [467]:
# select_2030__merge_try2 is the remaining zones from Emp_home_select_2030_new_values_merge_u_try5_5_6

select_2030__merge_try2 = Emp_home_select_2030_new_values_merge_u_try2.loc[~Emp_home_select_2030_new_values_merge_u_try2['h_geocode'].isin(Emp_home_select_2030_new_values_merge_u_try5_5_6['h_geocode_y'])]
len(select_2030__merge_try2)

52

In [468]:
#geometery_y1 for w_geocode and geometery_x1 for h_geocode

for j in range(2,loop_ended+1):
    globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].astype({"h_geocode":'int64'})

In [469]:
# select_hgeocode_geo5_6_try_try2_dic_missing = select_hgeocode_geo5_6_try_try2_dic_missing.drop(['w_geocode','h_geocode','h_geocode_x','geometry'], axis = 1)

# select_hgeocode_geo5_6_try_try2_dic_missing.rename(columns = {'h_geocode_y':'h_geocode'}, inplace = True)

for j in range(2,loop_ended+1):
    if 'geometry' in globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].columns:    
        globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].drop(['w_geocode','h_geocode','h_geocode_x','geometry'], axis = 1)
    else:
        globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].drop(['w_geocode','h_geocode','h_geocode_x'], axis = 1)

    globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].rename(columns = {'h_geocode_y':'h_geocode'}, inplace = True)

In [470]:
Emp_home_select_2030_part2_new2_temp =Emp_home_select_2030_part2_new2[['h_geocode','geometry']]

In [471]:
Emp_home_select_2030_part2_new2_temp.head()

         h_geocode                                           geometry
0  120710012051002  POLYGON ((-81.84015 26.61223, -81.83993 26.612...
1  120210104111000  POLYGON ((-81.69629 26.18436, -81.69546 26.184...
2  120210104081005  POLYGON ((-81.73524 26.20540, -81.73522 26.205...
3  120210112081028  POLYGON ((-81.44029 26.32594, -81.44019 26.326...
4  120810020031002  POLYGON ((-82.50990 27.50864, -82.50986 27.508...

In [472]:
select_hgeocode_geo5_6_try_try3_dic_missing

,dist_x,dist,h_geocode,CA01,CA02,CA03,CR01,CR02,CR03,CR04,...,CNS18,CNS19,CNS20,cell_x,cell_y,C000,loop_num,cells_used,C000_dmg,C000_dmg_mean
1639_a_0,26.829769,0.651159,120879728001011,2,1,0,3,0,0,0,...,1,0,0,2.0,26.0,3,2,0,0,NaN
1641_a_0,25.621885,0.810531,120879728002008,0,1,1,2,0,0,0,...,0,1,0,1.0,41.0,2,2,0,0,NaN
1647_a_0,25.987754,0.730258,120879728004012,1,3,3,6,1,0,0,...,1,0,0,0.0,33.0,7,2,0,0,NaN

In [473]:
for j in range(2,loop_ended+1):
    if 'geometry_x1' in globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].columns:       
        globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].rename(columns = {'geometry_x1':'geometry'}, inplace = True)
        globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)].drop(['geometry_y1'], axis = 1)

    else:
         globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)] = pd.merge( globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (j)], Emp_home_select_2030_part2_new2_temp,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])

In [474]:
select_hgeocode_geo5_6_try_try2_dic_missing

,h_geocode,C000,CA01,CA02,CA03,CR01,CR02,CR03,CR04,CR05,...,CNS19,CNS20,cell_x,dist,cell_y,geometry,dist_x,cells_used,C000_dmg,C000_dmg_mean
503_a_0,120879721001025,22,1,13,8,19,2,0,1,0,...,1,0,0.0,0.872714,89.0,"POLYGON ((-81.78695 24.56095, -81.78688 24.561...",4.734925,0,0,NaN
524_a_0,120879724001019,5,0,4,1,4,1,0,0,0,...,0,0,1.0,0.069614,89.0,"POLYGON ((-81.80399 24.55218, -81.80366 24.552...",7.833751,0,0,NaN
534_a_0,120879719003012,1,0,1,0,1,0,0,0,0,...,0,1,0.0,0.090602,89.0,"POLYGON ((-81.75916 24.56518, -81.75879 24.565...",3.080889,0,0,NaN
585_a_0,120879722001004,18,7,7,4,14,2,1,1,0,...,1,0,0.0,0.778254,89.0,"POLYGON ((-81.78714 24.55596, -81.78705 24.556...",6.798081,0,0,NaN
588_a_0,120879724001010,15,2,8,5,12,2,0,0,0,...,0,0,1.0,0.1854,89.0,"POLYGON ((-81.80274 24.55160, -81.80241 24.551...",7.833751,0,0,NaN
591_a_0,120879728002007,16,2,8,6,15,1,0,0,0,...,0,0,0.0,0.261622,89.0,"POLYGON ((-81.79376 24.55317, -81.79356 24.553...",6.798081,0,0,NaN
2471_a_0,120879705002024,4,1,2,1,4,0,0,0,0,...,0,0,0.0,0.418079,19.0,"POLYGON ((-80.43384 25.10050, -80.43359 25.100...",5.691259,0,0,NaN
3066_a_0,120879720001000,4,0,3,1,4,0,0,0,0,...,0,0,0.0,0.851354,89.0,"POLYGON ((-81.77930 24.55553, -81.77912 24.555...",5.021404,0,0,NaN
3238_a_0,120150105041028,2,0,1,1,2,0,0,0,0,...,0,0,0.0,4.759542,47.0,"POLYGON ((-81.99622 26.86641, -81.99542 26.867...",15.893255,0,0,NaN
4404_a_0,120879728002014,4,0,3,3,5,1,0,0,0,...,0,0,3.0,0.499302,10.0,"POLYGON ((-81.79127 24.55333, -81.79122 24.553...",4.662564,2,0,NaN
4462_a_0,120879714011002,5,0,5,0,4,0,0,0,0,...,0,0,0.0,1.087882,89.0,"POLYGON ((-81.35215 24.67840, -81.35214 24.678...",40.514415,0,0,NaN
4546_a_0,120810008041014,10,1,4,5,10,0,0,0,0,...,0,0,8.0,0.871174,17.0,"POLYGON ((-82.50720 27.45969, -82.50716 27.459...",11.354553,0,0,NaN
5054_a_0,121150027213052,1,0,3,1,4,0,0,0,0,...,0,1,1.0,15.832012,7.0,"POLYGON ((-82.27100 27.04969, -82.27098 27.049...",0.869845,3,0,NaN
5368_a_0,120879707002012,3,1,1,1,3,0,0,0,0,...,0,0,0.0,1.1844,6.0,"POLYGON ((-80.51841 25.00793, -80.51807 25.008...",16.537123,0,0,NaN
6284_a_0,120879728002021,2,0,1,1,2,0,0,0,0,...,0,0,0.0,0.209485,89.0,"POLYGON ((-81.79090 24.55144, -81.79073 24.551...",6.798081,0,0,NaN
6566_a_0,120879720001032,6,0,4,2,5,1,0,0,0,...,0,0,0.0,0.958363,89.0,"POLYGON ((-81.78554 24.55002, -81.78548 24.550...",6.474892,0,0,NaN
6775_a_0,120879708003013,7,1,2,4,7,0,0,0,0,...,0,0,0.0,4.392962,9.0,"POLYGON ((-80.55124 24.97801, -80.55111 24.978...",2.499913,0,0,NaN

In [475]:
select_hgeocode_geo5_6_try_try2_dic_missing.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 503_a_0 to 6775_a_0
Data columns (total 50 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   h_geocode      17 non-null     int64
 1   C000           17 non-null     int64
 2   CA01           17 non-null     int64
 3   CA02           17 non-null     int64
 4   CA03           17 non-null     int64
 5   CR01           17 non-null     int64
 6   CR02           17 non-null     int64
 7   CR03           17 non-null     int64
 8   CR04           17 non-null     int64
 9   CR05           17 non-null     int64
 10  CR07           17 non-null     int64
 11  CE01           17 non-null     int64
 12  CE02           17 non-null     int64
 13  CE03           17 non-null     int64
 14  CT01           17 non-null     int64
 15  CT02           17 non-null     int64
 16  CD01           17 non-null     int64
 17  CD02           17 non-null     int64
 18  CD03           17 non-null     int64
 19  CD04           17 non-null     int64
 20  CS01           17 non-null     int64
 21  CS02           17 non-null     int64
 22  CNS01          17 non-null     int64
 23  CNS02          17 non-null     int64
 24  CNS03          17 non-null     int64
 25  CNS04          17 non-null     int64
 26  CNS05          17 non-null     int64
 27  CNS06          17 non-null     int64
 28  CNS07          17 non-null     int64
 29  CNS08          17 non-null     int64
 30  CNS09          17 non-null     int64
 31  CNS10          17 non-null     int64
 32  CNS11          17 non-null     int64
 33  CNS12          17 non-null     int64
 34  CNS13          17 non-null     int64
 35  CNS14          17 non-null     int64
 36  CNS15          17 non-null     int64
 37  CNS16          17 non-null     int64
 38  CNS17          17 non-null     int64
 39  CNS18          17 non-null     int64
 40  CNS19          17 non-null     int64
 41  CNS20          17 non-null     int64
 42  cell_x         17 non-null     float64
 43  dist           17 non-null     object
 44  cell_y         17 non-null     float64
 45  geometry       17 non-null     geometry
 46  dist_x         17 non-null     object
 47  cells_used     17 non-null     int64
 48  C000_dmg       17 non-null     int64
 49  C000_dmg_mean  0 non-null      float64
dtypes: float64(3), geometry(1), int64(44), object(2)
memory usage: 6.8+ KB

In [476]:
select_hgeocode_geo5_6_try_try3_dic_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 51 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   dist_x         3 non-null      object
 1   dist           3 non-null      object
 2   h_geocode      3 non-null      int64
 3   CA01           3 non-null      int64
 4   CA02           3 non-null      int64
 5   CA03           3 non-null      int64
 6   CR01           3 non-null      int64
 7   CR02           3 non-null      int64
 8   CR03           3 non-null      int64
 9   CR04           3 non-null      int64
 10  CR05           3 non-null      int64
 11  CR07           3 non-null      int64
 12  CE01           3 non-null      int64
 13  CE02           3 non-null      int64
 14  CE03           3 non-null      int64
 15  CT01           3 non-null      int64
 16  CT02           3 non-null      int64
 17  CD01           3 non-null      int64
 18  CD02           3 non-null      int64
 19  CD03           3 non-null      int64
 20  CD04           3 non-null      int64
 21  CS01           3 non-null      int64
 22  CS02           3 non-null      int64
 23  CNS01          3 non-null      int64
 24  CNS02          3 non-null      int64
 25  CNS03          3 non-null      int64
 26  CNS04          3 non-null      int64
 27  CNS05          3 non-null      int64
 28  CNS06          3 non-null      int64
 29  CNS07          3 non-null      int64
 30  CNS08          3 non-null      int64
 31  CNS09          3 non-null      int64
 32  CNS10          3 non-null      int64
 33  CNS11          3 non-null      int64
 34  CNS12          3 non-null      int64
 35  CNS13          3 non-null      int64
 36  CNS14          3 non-null      int64
 37  CNS15          3 non-null      int64
 38  CNS16          3 non-null      int64
 39  CNS17          3 non-null      int64
 40  CNS18          3 non-null      int64
 41  CNS19          3 non-null      int64
 42  CNS20          3 non-null      int64
 43  cell_x         3 non-null      float64
 44  cell_y         3 non-null      float64
 45  C000           3 non-null      int64
 46  loop_num       3 non-null      int64
 47  cells_used     3 non-null      int64
 48  C000_dmg       3 non-null      int64
 49  C000_dmg_mean  0 non-null      float64
 50  geometry       3 non-null      geometry
dtypes: float64(3), geometry(1), int64(45), object(2)
memory usage: 1.3+ KB

In [477]:
# for i in range(2, loop_ended+1):
#     globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)] = gpd.GeoDataFrame(globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)], geometry='geometry')
    
#     globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)] = globals()['select_hgeocode_geo5_6_try_try%s_dic_missing' % (i)].to_crs("EPSG:4326")

select_2030__merge_try2_=pd.concat([select_2030__merge_try2, select_hgeocode_geo5_6_try_try2_dic_missing,select_hgeocode_geo5_6_try_try3_dic_missing], axis=0)
    
len(select_2030__merge_try2_)

72

In [478]:
select_2030__merge_try2_

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,cell,min_2030,cells_used,C000_dmg,C000_dmg_mean,cell_x,dist,cell_y,dist_x,loop_num
5_a_0,12,115,002605,2004,121150026052004,Block 2004,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18_a_0,12,115,001301,2007,121150013012007,Block 2007,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
41_a_0,12,087,971501,1003,120879715011003,Block 1003,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
66_a_0,12,071,001919,2000,120710019192000,Block 2000,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
95_a_0,12,071,040126,2039,120710401262039,Block 2039,G5040,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6566_a_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,0.0,0.958363,89.0,6.474892,NaN
6775_a_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,0.0,4.392962,9.0,2.499913,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,2.0,0.651159,26.0,26.829769,2.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,1.0,0.810531,41.0,25.621885,2.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0,NaN,0.0,0.730258,33.0,25.987754,2.0

In [479]:
Emp_cells_sum_no_dups_final_geo2

,h_geocode,cell,geometry,centr,centr_co,cell_remain
0,120150101001000,9,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",9
1,120150101001008,1,"POLYGON ((-81.77097 27.03391, -81.76417 27.033...",POINT (27.02625 -81.72729),"(27.026252036266474, -81.7272941973198)",1
2,120150101001010,20,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",5
3,120150101001011,5,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",1
4,120150101001014,4,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",4
...,...,...,...,...,...,...
19418,121150027472073,2,"POLYGON ((-82.12287 27.06476, -82.12237 27.065...",POINT (27.06582 -82.12108),"(27.065824891085622, -82.12107856295184)",2
19419,121150027481009,25,"POLYGON ((-82.13040 27.07920, -82.13034 27.079...",POINT (27.07793 -82.12790),"(27.077931190230956, -82.1279005987348)",25
19420,121150027481010,7,"POLYGON ((-82.12372 27.07904, -82.12370 27.079...",POINT (27.07993 -82.12237),"(27.079930391502035, -82.12236528182576)",7
19421,121150027482003,5,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)",5
19422,121150027483006,2,"POLYGON ((-82.14904 27.07975, -82.14903 27.079...",POINT (27.08024 -82.14807),"(27.080241752622683, -82.14807465817486)",2

In [480]:
if 'cell' in Emp_cells_sum_no_dups_final_geo2.columns:   
    Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.drop(['cell'], axis = 1)
else:
    pass
Emp_cells_sum_no_dups_final_geo2

,h_geocode,geometry,centr,centr_co,cell_remain
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",9
1,120150101001008,"POLYGON ((-81.77097 27.03391, -81.76417 27.033...",POINT (27.02625 -81.72729),"(27.026252036266474, -81.7272941973198)",1
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",5
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",1
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",4
...,...,...,...,...,...
19418,121150027472073,"POLYGON ((-82.12287 27.06476, -82.12237 27.065...",POINT (27.06582 -82.12108),"(27.065824891085622, -82.12107856295184)",2
19419,121150027481009,"POLYGON ((-82.13040 27.07920, -82.13034 27.079...",POINT (27.07793 -82.12790),"(27.077931190230956, -82.1279005987348)",25
19420,121150027481010,"POLYGON ((-82.12372 27.07904, -82.12370 27.079...",POINT (27.07993 -82.12237),"(27.079930391502035, -82.12236528182576)",7
19421,121150027482003,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)",5
19422,121150027483006,"POLYGON ((-82.14904 27.07975, -82.14903 27.079...",POINT (27.08024 -82.14807),"(27.080241752622683, -82.14807465817486)",2

In [481]:
if 'cell_remain' in Emp_cells_sum_no_dups_final_geo2.columns:   
    Emp_cells_sum_no_dups_final_geo2 = Emp_cells_sum_no_dups_final_geo2.drop(['cell_remain'], axis = 1)
else:
    pass
Emp_cells_sum_no_dups_final_geo2

,h_geocode,geometry,centr,centr_co
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)"
1,120150101001008,"POLYGON ((-81.77097 27.03391, -81.76417 27.033...",POINT (27.02625 -81.72729),"(27.026252036266474, -81.7272941973198)"
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)"
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)"
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)"
...,...,...,...,...
19418,121150027472073,"POLYGON ((-82.12287 27.06476, -82.12237 27.065...",POINT (27.06582 -82.12108),"(27.065824891085622, -82.12107856295184)"
19419,121150027481009,"POLYGON ((-82.13040 27.07920, -82.13034 27.079...",POINT (27.07793 -82.12790),"(27.077931190230956, -82.1279005987348)"
19420,121150027481010,"POLYGON ((-82.12372 27.07904, -82.12370 27.079...",POINT (27.07993 -82.12237),"(27.079930391502035, -82.12236528182576)"
19421,121150027482003,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)"
19422,121150027483006,"POLYGON ((-82.14904 27.07975, -82.14903 27.079...",POINT (27.08024 -82.14807),"(27.080241752622683, -82.14807465817486)"

In [482]:
Emp_cells_sum_no_dups_final_geo2_2030_final2 = pd.merge(Emp_cells_sum_no_dups_final_geo2, Emp_cells2_2030_2_sum,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])
len(Emp_cells_sum_no_dups_final_geo2_2030_final2)

19423

In [483]:
Emp_cells_sum_no_dups_final_geo2_2030_final2

,h_geocode,geometry,centr,centr_co,fd_id,found_ht,cell,min_2030
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",3.934161e+09,12.0,8.0,0.0
1,120150101001008,"POLYGON ((-81.77097 27.03391, -81.76417 27.033...",POINT (27.02625 -81.72729),"(27.026252036266474, -81.7272941973198)",NaN,NaN,NaN,NaN
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",2.458357e+09,3.5,5.0,0.0
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",4.916611e+08,1.5,1.0,0.0
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",1.969459e+09,4.0,4.0,0.0
...,...,...,...,...,...,...,...,...
19418,121150027472073,"POLYGON ((-82.12287 27.06476, -82.12237 27.065...",POINT (27.06582 -82.12108),"(27.065824891085622, -82.12107856295184)",NaN,NaN,NaN,NaN
19419,121150027481009,"POLYGON ((-82.13040 27.07920, -82.13034 27.079...",POINT (27.07793 -82.12790),"(27.077931190230956, -82.1279005987348)",1.233239e+10,12.5,25.0,0.0
19420,121150027481010,"POLYGON ((-82.12372 27.07904, -82.12370 27.079...",POINT (27.07993 -82.12237),"(27.079930391502035, -82.12236528182576)",3.450388e+09,3.5,7.0,0.0
19421,121150027482003,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)",2.464609e+09,2.5,5.0,0.0
19422,121150027483006,"POLYGON ((-82.14904 27.07975, -82.14903 27.079...",POINT (27.08024 -82.14807),"(27.080241752622683, -82.14807465817486)",NaN,NaN,NaN,NaN

In [484]:
Emp_cells_sum_no_dups_final_geo2_2030_final2 = Emp_cells_sum_no_dups_final_geo2_2030_final2.drop([
    'min_2030'
],axis=1)

In [485]:
Emp_home_select_2030_new_values_merge[Emp_home_select_2030_new_values_merge['C000']<0]

Empty GeoDataFrame
Columns: [STATEFP20, COUNTYFP20, TRACTCE20, BLOCKCE20, GEOID20, NAME20, MTFCC20, UR20, UACE20, UATYPE20, FUNCSTAT20, ALAND20, AWATER20, INTPTLAT20, INTPTLON20, h_geocode, C000, CA01, CA02, CA03, CE01, CE02, CE03, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, CR01, CR02, CR03, CR04, CR05, CR07, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, createdate, geometry, cell]
Index: []

[0 rows x 60 columns]

In [486]:
select_2030__merge_try2 = select_2030__merge_try2_.copy()

In [487]:

        
select_2030__merge_try2['centr'] = ''


for n in range(0,len(select_2030__merge_try2)):
    select_2030__merge_try2.iloc[n,select_2030__merge_try2.columns.get_loc("centr")]\
    = select_2030__merge_try2.iloc\
    [n,select_2030__merge_try2.columns.get_loc("geometry")].centroid.wkt
    
select_2030__merge_try2['centr'] = gpd.GeoSeries.from_wkt(select_2030__merge_try2['centr'])
select_2030__merge_try2 = gpd.GeoDataFrame(select_2030__merge_try2, geometry='centr')

for n in range(0,len(select_2030__merge_try2)):
    select_2030__merge_try2.iloc[n, select_2030__merge_try2.columns.get_loc("centr")] = transform(lambda x, y: (y, x),
                        select_2030__merge_try2.iloc[n, select_2030__merge_try2.columns.get_loc("centr")])

coord_list =  select_2030__merge_try2['centr'].geometry.apply(lambda p: list(p.coords)[0])
select_2030__merge_try2['centr_x_co'] = coord_list

In [488]:
# select_2030__merge_try2['h_geocode']

In [489]:
select_2030__merge_try2.head()

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,cells_used,C000_dmg,C000_dmg_mean,cell_x,dist,cell_y,dist_x,loop_num,centr,centr_x_co
5_a_0,12,115,002605,2004,121150026052004,Block 2004,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (26.95461 -82.34589),"(26.954611386035243, -82.34589082148906)"
18_a_0,12,115,001301,2007,121150013012007,Block 2007,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (27.34150 -82.45741),"(27.341499508170507, -82.45741485009053)"
41_a_0,12,087,971501,1003,120879715011003,Block 1003,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (24.66277 -81.48720),"(24.66276660460335, -81.48720077363569)"
66_a_0,12,071,001919,2000,120710019192000,Block 2000,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (26.50478 -81.91652),"(26.504775688210522, -81.9165180202837)"
95_a_0,12,071,040126,2039,120710401262039,Block 2039,G5040,NaN,NaN,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,POINT (26.62115 -81.69825),"(26.621151017710368, -81.69825316723083)"

In [490]:
# Emp_home_select_2030_part2_new2_temp

In [491]:
# select_2030__merge_try2_temp = pd.merge(select_2030__merge_try2, Emp_home_select_2030_part2_new2_temp,  how='left', 
#                 left_on=['geometry'], right_on = ['geometry'])
# select_2030__merge_try2_temp.head()

In [492]:
# select_2030__merge_try2_temp= select_2030__merge_try2_temp.drop(['h_geocode_x'],axis=1)

# select_2030__merge_try2_temp.rename(columns = {'h_geocode_y':'h_geocode'}, inplace = True)

In [493]:
# select_2030__merge_try2=select_2030__merge_try2_temp.copy()

In [494]:
select_2030__merge_try2 = select_2030__merge_try2.astype({"h_geocode":'int64'})
select_2030__merge_try2['h_geocode']

5_a_0       121150026052004
18_a_0      121150013012007
41_a_0      120879715011003
66_a_0      120710019192000
95_a_0      120710401262039
                 ...
6566_a_0    120879720001032
6775_a_0    120879708003013
0           120879728001011
1           120879728002008
2           120879728004012
Name: h_geocode, Length: 72, dtype: int64

In [495]:
len(Emp_cells_sum_no_dups_final_geo2_2030_final2)

19423

In [496]:
Emp_cells_sum_no_dups_final_geo2_2030_final2 = Emp_cells_sum_no_dups_final_geo2_2030_final2.loc[~Emp_cells_sum_no_dups_final_geo2_2030_final2['h_geocode'].isin(select_2030__merge_try2['h_geocode'])]

len(Emp_cells_sum_no_dups_final_geo2_2030_final2)

19408

In [497]:
select_2030__merge_try2 = select_2030__merge_try2.reset_index()

select_2030__merge_try2 = select_2030__merge_try2.drop(['index'], axis = 1)

In [498]:
Emp_cells_sum_no_dups_final_geo2_2030_final2

,h_geocode,geometry,centr,centr_co,fd_id,found_ht,cell
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",3.934161e+09,12.0,8.0
1,120150101001008,"POLYGON ((-81.77097 27.03391, -81.76417 27.033...",POINT (27.02625 -81.72729),"(27.026252036266474, -81.7272941973198)",NaN,NaN,NaN
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",2.458357e+09,3.5,5.0
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",4.916611e+08,1.5,1.0
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",1.969459e+09,4.0,4.0
...,...,...,...,...,...,...,...
19418,121150027472073,"POLYGON ((-82.12287 27.06476, -82.12237 27.065...",POINT (27.06582 -82.12108),"(27.065824891085622, -82.12107856295184)",NaN,NaN,NaN
19419,121150027481009,"POLYGON ((-82.13040 27.07920, -82.13034 27.079...",POINT (27.07793 -82.12790),"(27.077931190230956, -82.1279005987348)",1.233239e+10,12.5,25.0
19420,121150027481010,"POLYGON ((-82.12372 27.07904, -82.12370 27.079...",POINT (27.07993 -82.12237),"(27.079930391502035, -82.12236528182576)",3.450388e+09,3.5,7.0
19421,121150027482003,"POLYGON ((-82.14311 27.07849, -82.14189 27.078...",POINT (27.07784 -82.14192),"(27.077840226809027, -82.14191780763095)",2.464609e+09,2.5,5.0
19422,121150027483006,"POLYGON ((-82.14904 27.07975, -82.14903 27.079...",POINT (27.08024 -82.14807),"(27.080241752622683, -82.14807465817486)",NaN,NaN,NaN

In [499]:
find_cells(Emp_cells_sum_no_dups_final_geo2_2030_final2,select_2030__merge_try2)

n1= 0
temprory4=             h_geocode      dist  cell
9896  121150026051022  0.417923   9.0
RHS= 121150026051022
C000= 3
cell_remain= 6.0
n1= 1
temprory4=              h_geocode      dist  cell
11275  121150013012008  0.058587  11.0
RHS= 121150013012008
C000= 1
cell_remain= 10.0
n1= 2
temprory4=             h_geocode      dist  cell
9097  120879715011023  1.878416   3.0
RHS= 120879715011023
C000= 2
cell_remain= 1.0
n1= 3
temprory4=             h_geocode   dist  cell
3379  120710019192003  0.383   3.0
RHS= 120710019192003
C000= 1
cell_remain= 2.0
n1= 4
temprory4=             h_geocode      dist  cell
3667  120710401262050  0.403502   7.0
RHS= 120710401262050
C000= 5
cell_remain= 2.0
n1= 5
temprory4=             h_geocode      dist  cell
6162  120710401231011  0.854592  22.0
RHS= 120710401231011
C000= 1
cell_remain= 21.0
n1= 6
temprory4=              h_geocode      dist  cell
10613  120879705002061  2.358153   2.0
RHS= 120879705002061
C000= 1
cell_remain= 1.0
n1= 7
temprory4=             h_geocode       dist  cell
3308  120879715021018  33.383533  13.0
RHS= 120879715021018
C000= 12
cell_remain= 1.0
n1= 8
temprory4=              h_geocode      dist  cell
10688  120879727002008  0.553851   2.0
RHS= 120879727002008
C000= 1
cell_remain= 1.0
n1= 9
temprory4=              h_geocode      dist  cell
13685  121150027391013  0.114635   7.0
RHS= 121150027391013
C000= 1
cell_remain= 6.0
n1= 10
temprory4=             h_geocode      dist  cell
6358  120879715021031  7.891683   9.0
RHS= 120879715021031
C000= 5
cell_remain= 4.0
n1= 11
temprory4=              h_geocode      dist  cell
10715  121150001033014  0.385112  11.0
RHS= 121150001033014
C000= 1
cell_remain= 10.0
n1= 12
temprory4=              h_geocode      dist  cell
10658  120879716001003  2.186486   2.0
RHS= 120879716001003
C000= 1
cell_remain= 1.0
n1= 13
temprory4=             h_geocode      dist  cell
5258  120810009011009  0.452467   6.0
RHS= 120810009011009
C000= 5
cell_remain= 1.0
n1= 14
temprory4=             h_geocode      dist  cell
2903  120710019231022  0.250277  17.0
RHS= 120710019231022
C000= 2
cell_remain= 15.0
n1= 15
temprory4=             h_geocode      dist  cell
9095  120879715021033  3.226126   6.0
RHS= 120879715021033
C000= 2
cell_remain= 4.0
n1= 16
temprory4=             h_geocode      dist  cell
2682  120710017082007  0.297227  20.0
RHS= 120710017082007
C000= 2
cell_remain= 18.0
n1= 17
temprory4=             h_geocode      dist  cell
6128  120710401201007  0.059215   6.0
RHS= 120710401201007
C000= 1
cell_remain= 5.0
n1= 18
temprory4=             h_geocode      dist  cell
2832  120710019172006  0.740793  16.0
RHS= 120710019172006
C000= 2
cell_remain= 14.0
n1= 19
temprory4=             h_geocode       dist  cell
7981  120879715021033  10.564237   4.0
RHS= 120879715021033
C000= 3
cell_remain= 1.0
n1= 20
temprory4=              h_geocode      dist  cell
10651  120879715011006  0.545985   3.0
RHS= 120879715011006
C000= 1
cell_remain= 2.0
n1= 21
temprory4=             h_geocode      dist  cell
7970  120879704004039  0.251529   4.0
RHS= 120879704004039
C000= 3
cell_remain= 1.0
n1= 22
temprory4=             h_geocode       dist  cell
2104  120879710012029  94.679403  25.0
RHS= 120879710012029
C000= 19
cell_remain= 6.0
n1= 23
temprory4=             h_geocode      dist  cell
7574  121150027441020  1.067168   8.0
RHS= 121150027441020
C000= 6
cell_remain= 2.0
n1= 24
temprory4=             h_geocode      dist  cell
5892  120710207001009  0.425779  13.0
RHS= 120710207001009
C000= 1
cell_remain= 12.0
n1= 25
temprory4=              h_geocode     dist  cell
10656  120879716002019  0.77497   3.0
RHS= 120879716002019
C000= 1
cell_remain= 2.0
n1= 26
temprory4=             h_geocode       dist  cell
7979  120879715021031  24.686509   4.0
RHS= 120879715021031
C000= 3
cell_remain= 1.0
n1= 27
temprory4=             h_geocode      dist  cell
5905  120710207003013  0.136267   5.0
RHS= 120710207003013
C000= 1
cell_remain= 4.0
n1= 28
temprory4=              h_geocode      dist  cell
10654  120879716001021  0.603098   2.0
RHS= 120879716001021
C000= 1
cell_remain= 1.0
n1= 29
temprory4=             h_geocode     dist  cell
3043  120710014011003  0.78399   5.0
RHS= 120710014011003
C000= 1
cell_remain= 4.0
n1= 30
temprory4=              h_geocode      dist  cell
10134  121150018013019  0.182215   3.0
RHS= 121150018013019
C000= 2
cell_remain= 1.0
n1= 31
temprory4=            h_geocode      dist  cell
331  120150202052016  0.179241   7.0
RHS= 120150202052016
C000= 1
cell_remain= 6.0
n1= 32
temprory4=             h_geocode       dist  cell
6355  120879711002068  39.954632   6.0
RHS= 120879711002068
C000= 5
cell_remain= 1.0
n1= 33
temprory4=              h_geocode      dist  cell
10665  120879721002024  0.272115   2.0
RHS= 120879721002024
C000= 1
cell_remain= 1.0
n1= 34
temprory4=             h_geocode       dist  cell
7977  120879711001035  75.636733   4.0
RHS= 120879711001035
C000= 3
cell_remain= 1.0
n1= 35
temprory4=              h_geocode      dist  cell
10691  120879728001015  0.159176   2.0
RHS= 120879728001015
C000= 1
cell_remain= 1.0
n1= 36
temprory4=             h_geocode      dist  cell
4654  120710901002054  0.823029   8.0
RHS= 120710901002054
C000= 5
cell_remain= 3.0
n1= 37
temprory4=             h_geocode      dist  cell
2513  120710403102045  0.185694  15.0
RHS= 120710403102045
C000= 9
cell_remain= 6.0
n1= 38
temprory4=              h_geocode      dist  cell
12293  121150022033013  0.117242   4.0
RHS= 121150022033013
C000= 1
cell_remain= 3.0
n1= 39
temprory4=             h_geocode     dist  cell
5335  120810003111017  0.11135   5.0
RHS= 120810003111017
C000= 4
cell_remain= 1.0
n1= 40
temprory4=             h_geocode      dist  cell
7084  120879709001055  2.951207   8.0
RHS= 120879709001055
C000= 4
cell_remain= 4.0
n1= 41
temprory4=             h_geocode     dist  cell
9452  120810014021008  0.67024   2.0
RHS= 120810014021008
C000= 1
cell_remain= 1.0
n1= 42
temprory4=            h_geocode      dist  cell
130  120150202051026  0.182957   8.0
RHS= 120150202051026
C000= 5
cell_remain= 3.0
n1= 43
temprory4=              h_geocode      dist  cell
11174  121150026031018  0.237571  12.0
RHS= 121150026031018
C000= 2
cell_remain= 10.0
n1= 44
temprory4=              h_geocode      dist  cell
10648  120879715021032  0.535189   2.0
RHS= 120879715021032
C000= 1
cell_remain= 1.0
n1= 45
temprory4=            h_geocode      dist  cell
711  120150207003001  0.182539  16.0
RHS= 120150207003001
C000= 1
cell_remain= 15.0
n1= 46
temprory4=            h_geocode      dist  cell
124  120150105053043  0.983029   2.0
RHS= 120150105053043
C000= 1
cell_remain= 1.0
n1= 47
temprory4=              h_geocode      dist  cell
10702  121150027461014  0.187732   5.0
RHS= 121150027461014
C000= 3
cell_remain= 2.0
n1= 48
temprory4=            h_geocode      dist  cell
307  120150203012004  0.254099  12.0
RHS= 120150203012004
C000= 2
cell_remain= 10.0
n1= 49
temprory4=             h_geocode      dist  cell
2442  120710003061028  0.191682   4.0
RHS= 120710003061028
C000= 2
cell_remain= 2.0
n1= 50
temprory4=             h_geocode      dist  cell
9095  120879722004002  0.158851   3.0
RHS= 120879722004002
C000= 2
cell_remain= 1.0
n1= 51
temprory4=            h_geocode      dist  cell
748  120150302014057  0.096275   4.0
RHS= 120150302014057
C000= 2
cell_remain= 2.0
n1= 52
temprory4=            h_geocode       dist  cell
495  120210110032007  149.50982  67.0
RHS= 120210110032007
C000= 22
cell_remain= 45.0
n1= 53
temprory4=             h_geocode       dist  cell
6350  120879710012010  83.115905  16.0
RHS= 120879710012010
C000= 5
cell_remain= 11.0
n1= 54
temprory4=              h_geocode      dist  cell
10659  120879721002011  1.284028   3.0
RHS= 120879721002011
C000= 1
cell_remain= 2.0
n1= 55
temprory4=            h_geocode        dist  cell
588  120210110032007  150.067045  45.0
RHS= 120210110032007
C000= 18
cell_remain= 27.0
n1= 56
temprory4=            h_geocode        dist  cell
687  120210110032007  150.654359  27.0
RHS= 120210110032007
C000= 15
cell_remain= 12.0
n1= 57
temprory4=            h_geocode        dist  cell
653  120210110032011  150.484831  19.0
RHS= 120210110032011
C000= 16
cell_remain= 3.0
n1= 58
temprory4=             h_geocode      dist  cell
7085  120879727003011  27.70848   9.0

RHS= 120879727003011
C000= 4
cell_remain= 5.0
n1= 59
temprory4=             h_geocode       dist  cell
7082  120879710012010  80.597668  11.0
RHS= 120879710012010
C000= 4
cell_remain= 7.0
n1= 60
temprory4=           h_geocode      dist  cell
78  120150105052024  0.964816   3.0
RHS= 120150105052024
C000= 2
cell_remain= 1.0
n1= 61
temprory4=             h_geocode      dist  cell
7082  120879710012010  81.84079   7.0
RHS= 120879710012010
C000= 4
cell_remain= 3.0
n1= 62
temprory4=             h_geocode       dist  cell
6349  120879710012029  35.543944   6.0
RHS= 120879710012029
C000= 5
cell_remain= 1.0
n1= 63
temprory4=             h_geocode      dist  cell
3005  120810008042009  0.270415  19.0
RHS= 120810008042009
C000= 10
cell_remain= 9.0
n1= 64
temprory4=              h_geocode      dist  cell
13237  121150027213045  0.089184   5.0
RHS= 121150027213045
C000= 1
cell_remain= 4.0
n1= 65
temprory4=             h_geocode      dist  cell
7964  120879706001043  3.437041   4.0
RHS= 120879706001043
C000= 3
cell_remain= 1.0
n1= 66
temprory4=             h_geocode      dist  cell
9107  120879728004035  0.407189   3.0
RHS= 120879728004035
C000= 2
cell_remain= 1.0
n1= 67
temprory4=             h_geocode        dist  cell
5692  120879709001009  111.019177  14.0
RHS= 120879709001009
C000= 6
cell_remain= 8.0
n1= 68
temprory4=             h_geocode       dist  cell
5129  120879709001018  23.209887  12.0
RHS= 120879709001018
C000= 7
cell_remain= 5.0
n1= 69
temprory4=             h_geocode       dist  cell
7967  120879710022010  91.985194   5.0
RHS= 120879710022010
C000= 3
cell_remain= 2.0
n1= 70
temprory4=             h_geocode      dist  cell
9104  120879728003018  0.396678   3.0
RHS= 120879728003018
C000= 2
cell_remain= 1.0
n1= 71
temprory4=             h_geocode        dist  cell
5128  120879709001009  111.786956   8.0
RHS= 120879709001009
C000= 7
cell_remain= 1.0

In [500]:
select_2030__merge_try2

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,C000_dmg,C000_dmg_mean,cell_x,dist,cell_y,dist_x,loop_num,centr,centr_x_co,h_geocode_x
0,12,115,002605,2004,121150026052004,Block 2004,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.417923,NaN,POINT (26.95461 -82.34589),"(26.954611386035243, -82.34589082148906)",121150026051022
1,12,115,001301,2007,121150013012007,Block 2007,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.058587,NaN,POINT (27.34150 -82.45741),"(27.341499508170507, -82.45741485009053)",121150013012008
2,12,087,971501,1003,120879715011003,Block 1003,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,1.878416,NaN,POINT (24.66277 -81.48720),"(24.66276660460335, -81.48720077363569)",120879715011023
3,12,071,001919,2000,120710019192000,Block 2000,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.383,NaN,POINT (26.50478 -81.91652),"(26.504775688210522, -81.9165180202837)",120710019192003
4,12,071,040126,2039,120710401262039,Block 2039,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.403502,NaN,POINT (26.62115 -81.69825),"(26.621151017710368, -81.69825316723083)",120710401262050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,0.958363,89.0,111.019177,NaN,POINT (24.54995 -81.78501),"(24.54995184765915, -81.7850111513444)",120879709001009
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,4.392962,9.0,23.209887,NaN,POINT (24.97974 -80.54928),"(24.97974343507609, -80.54928081838041)",120879709001018
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,2.0,0.651159,26.0,91.985194,2.0,POINT (24.55802 -81.79194),"(24.55802145708066, -81.79193635302525)",120879710022010
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,1.0,0.810531,41.0,0.396678,2.0,POINT (24.55319 -81.79262),"(24.553192378257176, -81.79262041911755)",120879728003018
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,0.730258,33.0,111.786956,2.0,POINT (24.54911 -81.79267),"(24.549111922594275, -81.79267479553012)",120879709001009

In [501]:

select_2030__merge_try2 = select_2030__merge_try2.astype({"C000":'int64'})

# select_2030__merge_try2 = select_2030__merge_try2.drop(['level_0'], axis = 1)

# select_2030__merge_try2 = select_2030__merge_try2.reset_index()

select_2030__merge_try2

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,C000_dmg,C000_dmg_mean,cell_x,dist,cell_y,dist_x,loop_num,centr,centr_x_co,h_geocode_x
0,12,115,002605,2004,121150026052004,Block 2004,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.417923,NaN,POINT (26.95461 -82.34589),"(26.954611386035243, -82.34589082148906)",121150026051022
1,12,115,001301,2007,121150013012007,Block 2007,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.058587,NaN,POINT (27.34150 -82.45741),"(27.341499508170507, -82.45741485009053)",121150013012008
2,12,087,971501,1003,120879715011003,Block 1003,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,1.878416,NaN,POINT (24.66277 -81.48720),"(24.66276660460335, -81.48720077363569)",120879715011023
3,12,071,001919,2000,120710019192000,Block 2000,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.383,NaN,POINT (26.50478 -81.91652),"(26.504775688210522, -81.9165180202837)",120710019192003
4,12,071,040126,2039,120710401262039,Block 2039,G5040,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0.403502,NaN,POINT (26.62115 -81.69825),"(26.621151017710368, -81.69825316723083)",120710401262050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,0.958363,89.0,111.019177,NaN,POINT (24.54995 -81.78501),"(24.54995184765915, -81.7850111513444)",120879709001009
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,4.392962,9.0,23.209887,NaN,POINT (24.97974 -80.54928),"(24.97974343507609, -80.54928081838041)",120879709001018
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,2.0,0.651159,26.0,91.985194,2.0,POINT (24.55802 -81.79194),"(24.55802145708066, -81.79193635302525)",120879710022010
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,1.0,0.810531,41.0,0.396678,2.0,POINT (24.55319 -81.79262),"(24.553192378257176, -81.79262041911755)",120879728003018
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0.0,0.730258,33.0,111.786956,2.0,POINT (24.54911 -81.79267),"(24.549111922594275, -81.79267479553012)",120879709001009

In [502]:
select_2030__merge_try2['geometry'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [503]:
# Emp_home_select_2030_new_values_merge_u_try5_5_6= Emp_home_select_2030_new_values_merge_u_try5_5_6.drop(['level_0'],axis=1)

In [504]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_geo = gpd.GeoDataFrame(
    Emp_home_select_2030_new_values_merge_u_try5_5_6, geometry=Emp_home_select_2030_new_values_merge_u_try5_5_6['geometry'], crs="EPSG:4326"
)
# Emp_home_select_2030_new_values_merge_u_try5_5_6['geometry'] = Emp_home_select_2030_new_values_merge_u_try5_5_6['geometry'].to_crs('epsg:4326')

In [505]:
len(Emp_home_select_2030_new_values_merge_u_try5_5_6)

407

In [506]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_geo['geometry']=Emp_home_select_2030_new_values_merge_u_try5_5_6_geo['geometry'].to_crs('epsg:4326')

In [507]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_geo['geometry'].crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [508]:
select_2030__merge_try2 = gpd.GeoDataFrame(
    select_2030__merge_try2, geometry=select_2030__merge_try2['geometry'], crs="EPSG:4326"
)

In [509]:
# select_2030__merge_try2.drop(['geometry_y1'],axis=1)

In [510]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_geo=Emp_home_select_2030_new_values_merge_u_try5_5_6_geo.drop(['geometry_x1','geometry_y1'],axis=1)

In [511]:
import pandas as pd 
Emp_home_select_2030_new_values_merge_u_try5_5_6_=pd.concat([Emp_home_select_2030_new_values_merge_u_try5_5_6_geo, select_2030__merge_try2], axis=0)
len(Emp_home_select_2030_new_values_merge_u_try5_5_6_)

479

In [512]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_

,dist_x,index,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,...,min_2030_y,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co
0,2.584469,0,0.176535,1.201501e+14,120150103012032,12,015,010301,1002,120150103011002,...,0.0,"POLYGON ((-82.05914 26.91076, -82.05913 26.911...",3.446669e+09,10.5,7.0,0.0,NaN,NaN,None,NaN
1,2.8669,25,2.577578,1.201501e+14,120150104022005,12,015,010301,2015,120150103012015,...,0.0,"POLYGON ((-82.07079 26.91293, -82.07079 26.913...",4.034202e+10,93.5,82.0,0.0,NaN,NaN,None,NaN
2,2.8669,10266,17.309958,1.201501e+14,120150104022005,12,015,030501,2057,120150305012057,...,0.0,"POLYGON ((-82.07079 26.91293, -82.07079 26.913...",4.034202e+10,93.5,82.0,0.0,NaN,NaN,None,NaN
3,1.415021,485,2.075123,1.201501e+14,120150104021004,12,015,010402,1007,120150104021007,...,0.0,"POLYGON ((-82.06488 26.92035, -82.06486 26.920...",1.967373e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
4,2.325463,643,1.412605,1.201501e+14,120150104053007,12,015,010405,2005,120150104052005,...,0.0,"POLYGON ((-82.07083 26.90300, -82.07082 26.903...",2.155034e+11,599.5,438.0,0.0,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,111.019177,NaN,0.958363,NaN,120879709001009,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.78554 24.55002, -81.78548 24.550...",NaN,NaN,89.0,NaN,NaN,NaN,POINT (24.54995 -81.78501),"(24.54995184765915, -81.7850111513444)"
68,23.209887,NaN,4.392962,NaN,120879709001018,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-80.55124 24.97801, -80.55111 24.978...",NaN,NaN,9.0,NaN,NaN,NaN,POINT (24.97974 -80.54928),"(24.97974343507609, -80.54928081838041)"
69,91.985194,NaN,0.651159,NaN,120879710022010,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.79256 24.55797, -81.79238 24.558...",NaN,NaN,26.0,NaN,NaN,2.0,POINT (24.55802 -81.79194),"(24.55802145708066, -81.79193635302525)"
70,0.396678,NaN,0.810531,NaN,120879728003018,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.79315 24.55357, -81.79282 24.553...",NaN,NaN,41.0,NaN,NaN,2.0,POINT (24.55319 -81.79262),"(24.553192378257176, -81.79262041911755)"
71,111.786956,NaN,0.730258,NaN,120879709001009,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.79328 24.54920, -81.79314 24.549...",NaN,NaN,33.0,NaN,NaN,2.0,POINT (24.54911 -81.79267),"(24.549111922594275, -81.79267479553012)"

In [513]:

# Emp_home_select_2030_new_values_merge_u_try5_5_6_ = Emp_home_select_2030_new_values_merge_u_try5_5_6_.drop(['level_0'], axis = 1)
Emp_home_select_2030_new_values_merge_u_try5_5_6_ = Emp_home_select_2030_new_values_merge_u_try5_5_6_.reset_index()

Emp_home_select_2030_new_values_merge_u_try5_5_6_['C000']

0      6
1      1
2      2
3      2
4      1
      ..
474    6
475    7
476    3
477    2
478    7
Name: C000, Length: 479, dtype: int64

In [514]:

Emp_home_select_2030_new_values_merge_u_try5_5_6_ = Emp_home_select_2030_new_values_merge_u_try5_5_6_.drop(['level_0'], axis = 1)

In [515]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_['C000'].sum()

1242

In [516]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_

,dist_x,index,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,...,min_2030_y,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co
0,2.584469,0,0.176535,1.201501e+14,120150103012032,12,015,010301,1002,120150103011002,...,0.0,"POLYGON ((-82.05914 26.91076, -82.05913 26.911...",3.446669e+09,10.5,7.0,0.0,NaN,NaN,None,NaN
1,2.8669,25,2.577578,1.201501e+14,120150104022005,12,015,010301,2015,120150103012015,...,0.0,"POLYGON ((-82.07079 26.91293, -82.07079 26.913...",4.034202e+10,93.5,82.0,0.0,NaN,NaN,None,NaN
2,2.8669,10266,17.309958,1.201501e+14,120150104022005,12,015,030501,2057,120150305012057,...,0.0,"POLYGON ((-82.07079 26.91293, -82.07079 26.913...",4.034202e+10,93.5,82.0,0.0,NaN,NaN,None,NaN
3,1.415021,485,2.075123,1.201501e+14,120150104021004,12,015,010402,1007,120150104021007,...,0.0,"POLYGON ((-82.06488 26.92035, -82.06486 26.920...",1.967373e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
4,2.325463,643,1.412605,1.201501e+14,120150104053007,12,015,010405,2005,120150104052005,...,0.0,"POLYGON ((-82.07083 26.90300, -82.07082 26.903...",2.155034e+11,599.5,438.0,0.0,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,111.019177,NaN,0.958363,NaN,120879709001009,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.78554 24.55002, -81.78548 24.550...",NaN,NaN,89.0,NaN,NaN,NaN,POINT (24.54995 -81.78501),"(24.54995184765915, -81.7850111513444)"
475,23.209887,NaN,4.392962,NaN,120879709001018,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-80.55124 24.97801, -80.55111 24.978...",NaN,NaN,9.0,NaN,NaN,NaN,POINT (24.97974 -80.54928),"(24.97974343507609, -80.54928081838041)"
476,91.985194,NaN,0.651159,NaN,120879710022010,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.79256 24.55797, -81.79238 24.558...",NaN,NaN,26.0,NaN,NaN,2.0,POINT (24.55802 -81.79194),"(24.55802145708066, -81.79193635302525)"
477,0.396678,NaN,0.810531,NaN,120879728003018,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.79315 24.55357, -81.79282 24.553...",NaN,NaN,41.0,NaN,NaN,2.0,POINT (24.55319 -81.79262),"(24.553192378257176, -81.79262041911755)"
478,111.786956,NaN,0.730258,NaN,120879709001009,NaN,NaN,NaN,NaN,NaN,...,NaN,"POLYGON ((-81.79328 24.54920, -81.79314 24.549...",NaN,NaN,33.0,NaN,NaN,2.0,POINT (24.54911 -81.79267),"(24.549111922594275, -81.79267479553012)"

In [517]:
# dataframes4_temp={}


# # list of data frames
# # Assume that the original dataframe is named 'original_df'
# for i in range(0, 720):
#     dataframes4_temp[i] = Emp_home_select_2030_new_values_merge_u_try5_5_6_.copy()

# # Convert the dictionary to a list of tuples
# dataframes4 = list(dataframes4_temp.values())

# for k in range(0, 720):
#     dataframes4[k] = dataframes4[k].rename("{}_{}".format("{}_a",k).format)

# # dictionary to save data frames
# Emp_home_select_2030_new_values_merge_u_try5_5_6_dic={} 

# for key4, value4 in enumerate(dataframes4):    
#     Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[key4] = value4 # assigning data frame from list to key in dictionary

In [519]:
# Emp_cells2_2030_2_dic[0]

In [520]:
Emp_cells2_2030_2_dic, cells2_2030_3, Emp_home_select_2030_new_values_merge_u_try5_5_6_dic = find_cells_SLR(Emp_home_select_2030_new_values_merge_u_try5_5_6_, Emp_cells2_2030_2_dic)

Yes
i= 0
0.8861699104309082
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

8.844429969787598
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.0326230525970459

In [521]:
# Emp_cells2_2030_2_dic[89][Emp_cells2_2030_2_dic[89]['min_2030']>0]

In [522]:
# to_findit = Emp_cells2_2030_2_dic[719][Emp_cells2_2030_2_dic[719]['row_num']==32642]
# to_findit.to_file('to_findit.shp')

In [523]:
# Emp_cells2_2030_2_dic[719][Emp_cells2_2030_2_dic[719]['row_num']==32642]

In [524]:
# Emp_cells_2030_old[Emp_cells_2030_old['row_num']==32642]

In [525]:
cells2_2030_3

[[498226819, 498226820, 498226821],
 [492234861, 492234863, 492488063, 492488064, 492493957, 492493967],
 [491857427],
 [491852617, 491882983],
 [491843304, 491843334],
 [491832137],
 [491804112],
 [491801459, 491801507, 491801520],
 [491733644, 491735271, 491736461, 491736515],
 [491804191, 491810437],
 [491795571],
 [491800248,
  491800261,
  491800264,
  491800266,
  491800269,
  491800276,
  491800277,
  491800282,
  491800283,
  491800293,
  491800296],
 [491800255],
 [491890029, 491900713],
 [492385098],
 [491852995, 491852996],
 [492134581],
 [492235037],
 [491907933],
 [491907947],
 [491898232, 491898233, 491898241],
 [491898235],
 [],
 [],
 [],
 [],
 [491903880],
 [492243217],
 [492266613],
 [492266608],
 [492041757],
 [492254985, 492254991, 492254993, 492254996],
 [492254986, 492254999],
 [],
 [492239191, 492239195, 492239199, 492239202, 492239205, 492239206],
 [491919889],
 [491919871, 491919883, 491919885, 491919890],
 [491919882],
 [492925433, 492925434, 492925439],
 [492266440, 492266442, 492266443, 492266447],
 [492337768, 492337779, 492337782],
 [491911862, 491911872],
 [492314669],
 [492314664],
 [492905735, 492905739, 492905759],
 [491915919, 491915920, 491915926],
 [492239137, 492239141],
 [492153690],
 [492169050, 492169054, 492169057, 492169058, 492169066],
 [491902006],
 [495673589],
 [491989536, 491991791],
 [491898736, 491898749],
 [491898748],
 [495032855, 495032864],
 [492360630, 492360631, 492360632],
 [491896312, 491896320, 491896322, 491896323, 491896324],
 [491896302, 491896305, 491896308, 491896313, 491896318, 491896321, 491896325],
 [491905390, 491905393, 491905395, 491905404, 491905405],
 [492337911, 492337913, 492337919, 492337922, 492337926],
 [491902103, 491902128, 491902292, 491902322],
 [491901997],
 [492176325, 492176326, 492176327, 492176328, 492176330],
 [492254804],
 [491897692],
 [491852837],
 [492354082],
 [491994251],
 [491994249, 491994262, 491994269],
 [492182419],
 [492008156, 492009627, 492009640],
 [492353922],
 [492058353, 492058361, 492431904, 492431932],
 [492069207],
 [492207717, 492207722],
 [492294169],
 [494379293, 495421539, 495421574],
 [494532829],
 [494567712],
 [494423328, 494423371, 495406568],
 [494560958, 494561689],
 [494730568],
 [493690383, 493690454, 493692534],
 [494715904],
 [495028224],
 [492395493, 496086968, 496088426, 496090159],
 [492571073],
 [492501367, 492501382, 494897879],
 [492538884],
 [494129183, 494129287, 494129292],
 [493186099, 493186102, 493214378],
 [492145775],
 [492111090],
 [492122061,
  492124425,
  492124429,
  492124453,
  492124494,
  492124518,
  492124534,
  492126361,
  492126382],
 [492126425],
 [492115377, 492115380],
 [492164190, 492164266, 492164305, 492164403, 492164560],
 [494844724],
 [492140028, 492140046],
 [496599464],
 [497818694],
 [494821069],
 [497959040],
 [497137433, 497140961, 497140962],
 [497141047],
 [497141018],
 [497137455, 497137477],
 [496965794, 496965818, 496965869],
 [497830154, 497830159],
 [496845863, 496845923, 496845955],
 [497162690, 497162699, 497162713],
 [497060188],
 [498218836],
 [498218869, 498218878],
 [496976178, 496976203],
 [496965649, 496965671, 496965835, 496965865, 496965870],
 [497122008],
 [497520022],
 [496972738],
 [496837491],
 [498198804, 498199087],
 [498198847],
 [497292009, 497292010, 497292011, 497292024, 497292025],
 [497085432],
 [497085433],
 [498160433, 498160623, 498160627, 498160813, 498160819, 498160833],
 [498198263, 498198453],
 [498162535],
 [497202204],
 [498162531],
 [497140984],
 [496981658, 496981660, 496981710, 496981716],
 [497698822, 497698823],
 [498162874],
 [497559881, 497559883, 497559890],
 [497525383],
 [497540933, 497540936, 497540939, 497540942, 497540944],
 [498164235],
 [496981456, 496981510, 496985728],
 [496995135, 496997547],
 [496995337, 496997543, 496997560, 496997577, 496997578, 497892251],
 [497011817, 498167773, 498167807, 498168006],
 [498164259],
 [497073027, 497073102, 498162208],
 [497064811],
 [497108768],
 [498087204, 498087208, 498087214, 498087233],
 [497050008, 498159944],
 [497052081],
 [497265238, 497265285],
 [497085113, 497085117, 497085118],
 [497275018],
 [497609695],
 [497348864],
 [497335694, 497336050],
 [497226518, 497226529],
 [497745613, 497745619],
 [497745615],
 [],
 [497205228, 497205513],
 [497168000],
 [497987655],
 [497781390],
 [497739616],
 [497595151, 497595163],
 [497284649],
 [497129830],
 [496650554, 496650573, 496650623, 496650627, 496650635, 496650636, 496650646],
 [497175096,
  497175100,
  497175105,
  497175108,
  497175112,
  497175116,
  497175118,
  497175124,
  497175130,
  497175132,
  497175136],
 [497183204, 497183208],
 [497978326, 497978375],
 [497566987],
 [497749743],
 [497124063, 497126068],
 [497571428],
 [497185662, 497185671],
 [497264667, 497264681, 497264687, 497264689, 497264692],
 [497181672, 497181679, 497181691],
 [497257778,
  497257779,
  497257780,
  497257782,
  497257783,
  497257784,
  497257786,
  497257788,
  497257789],
 [497137500, 497137552, 497157138],
 [497140997, 497141059],
 [497190519],
 [497136458, 497136464, 497136475],
 [497137601],
 [496997907],
 [497137406,
  497137486,
  497137518,
  497137524,
  497137541,
  497137561,
  497140977,
  497141001,
  497141040,
  497141043,
  497157146],
 [497137534, 497141053],
 [497754409],
 [497754419],
 [497770844],
 [497601845, 497601849, 497601861, 497601883],
 [497612792],
 [497764201,
  497764202,
  497764203,
  497764206,
  497764207,
  497764208,
  497764209,
  497764213],
 [497286584],
 [497286592],
 [497181349],
 [497239435],
 [497723563],
 [497190286, 497190296, 497190298, 497190301],
 [497190295, 497190297],
 [497190294],
 [497352276, 497352403],
 [497306925, 497306934],
 [497306914, 497306930, 497306939, 497306941],
 [497320862],
 [497587277, 497587287, 497587290, 497587292, 497587305],
 [497278443, 497278445, 497278451, 497278454],
 [497284361],
 [497614782],
 [497369366, 497369367],
 [497770646],
 [497974165, 497974205],
 [497245771, 497246150],
 [497548761],
 [496845887, 496845894, 496845912, 496845925, 496887432, 496887434],
 [497674209],
 [497085055],
 [497085061],
 [497150678, 497150689, 497150714],
 [497530010, 498215668],
 [497041590],
 [497207062],
 [497205310, 497207023],
 [497085046, 497085056],
 [497571420],
 [497801343],
 [497154769, 497978828],
 [],
 [496644354, 496644361, 496644367, 497821059, 497821273, 497869091],
 [496796607],
 [496663872],
 [498198423],
 [496636195, 496636220, 496636230, 496636237],
 [496636211, 496636215, 496636250, 496636271, 496636357],
 [496636263, 496638390, 497884056],
 [496716134, 496716215],
 [498210364, 498210379],
 [496672504, 496672539],
 [496681428],
 [496679453, 496679911, 496681460, 496681533],
 [496574437],
 [496626988],
 [497879552, 497879556],
 [497477448, 497477456, 497477458],
 [498219317],
 [497461380, 497461387],
 [497461388, 497461403],
 [497469441, 497469463],
 [496566195,
  496566207,
  496566209,
  496566225,
  496566226,
  496566243,
  496566253,
  496566265,
  496566279,
  496566283,
  498221734,
  498223772,
  498223776,
  498223808,
  498223812,
  498223966,
  498223968,
  498223978,
  498223980,
  498224016,
  498224035,
  498224045,
  498224092,
  498224116,
  498224134,
  498224145],
 [496561999, 496562001],
 [496584362],
 [498072917],
 [497517709],
 [496931605, 496931612],
 [497672092],
 [497509490, 497509492],
 [496816427, 496816452, 496816453, 496817024, 496817666],
 [496731165, 496731219],
 [495687168, 495689570],
 [497444590, 497444726],
 [495938153],
 [495583209],
 [495583201, 495583202, 495583205, 495583211, 495583212, 495583215],
 [496033847, 496034315, 496039185],
 [495456839, 495456849],
 [494941127, 494941129],
 [494878837, 494878845, 494878878, 494878906],
 [494911009, 494911049, 495968804, 495968868],
 [494715336],
 [495522600],
 [494708458, 494710543],
 [494715357, 494715361, 494716296, 494717031, 494717240],
 [494715360],
 [494717242],
 [495938117],
 [495480064, 495480071, 495480074, 495480075],
 [495480062, 495480073],
 [495937628,
  495941326,
  495941590,
  495941618,
  495941954,
  495947607,
  495947637,
  495947670],
 [495313172],
 [494708456],
 [493791730],
 [493692338],
 [493906538, 493906560, 493906570, 493906622, 493906633],
 [493630999],
 [495767087],
 [495447819, 495447821],
 [495319858, 495319861],
 [493598182, 493603948, 493607564],
 [494878699, 494878709],
 [494722667],
 [494634619, 494634635, 494638640],
 [494634108, 494634606, 494641475, 494645063],
 [493765157],
 [494317924, 494318953],
 [494153574, 494153587, 494194523, 494194524, 494194531],
 [495132771, 495133567],
 [493586221, 493586223, 493586224, 493586232],
 [492114383,
  492114386,
  492114399,
  492116544,
  492116558,
  492116566,
  492116570,
  492116575,
  492116591,
  492116599,
  492116616,
  492116621,
  492116679,
  492116682,
  492116714,
  492116741,
  492116744,
  492116767,
  492116782],
 [492583412],
 [493906472],
 [495554924, 495554928, 495554936, 495554938, 495554946, 495554958, 495554964],
 [495197534],
 [492386571, 492386580, 492386599, 492386607, 492386612],
 [492976404, 492976405],
 [492274353],
 [497360886],
 [492320339],
 [492500615],
 [492432485, 493024146],
 [492374671],
 [494270393],
 [493017170],
 [492374783],
 [492380324],
 [492396783],
 [492554859],
 [492086007],
 [492396798],
 [492397586, 492490184],
 [492253127],
 [492179396],
 [492539066],
 [492169842],
 [491874905, 491874983],
 [492179492, 492589049],
 [492253128],
 [492612348],
 [492129258, 492129267, 492129289],
 [492255603, 492255605],
 [492469963],
 [492244875],
 [495205845],
 [495194106, 495194438, 495194453, 495194457],
 [494292998],
 [495734992],
 [493721256, 493721266],
 [494914479, 494914484],
 [497282215, 497282222],
 [494170616,
  494175075,
  494175092,
  494175105,
  494175109,
  494215480,
  494215487,
  494943703,
  494944563,
  495207603,
  495207607],
 [494215492, 494943692, 494944555],
 [494876795],
 [496632683, 496632729, 496632775, 496632781],
 [493857464],
 [494133578, 494133882, 495722714, 495722740],
 [493827809, 493827814, 495193336, 495193342],
 [495007733, 495008187, 495008191, 495008203, 495008212],
 [495222150],
 [493805935, 493805936, 493805953],
 [494308010, 494308035],
 [494982938],
 [494296270, 494299200],
 [495807360],
 [494167420, 494167424, 494167426],
 [494167414],
 [494982865],
 [493656737],
 [495804861, 495808431],
 [493448733],
 [493448735],
 [495139800, 495139825],
 [493397083],
 [494876704, 494876705, 494876707],
 [494837527, 494837576],
 [494837533],
 [493391658, 493392916, 493392922],
 [495186894, 495186895, 495186897, 495186900],
 [493692974, 495752416, 495752494],
 [495214238,
  495214240,
  495214245,
  495214248,
  495214258,
  495214280,
  495214282,
  495214302,
  495214303],
 [494186401, 494186620],
 [494186403, 494186404, 494186610, 494186612, 494186622],
 [493543530,
  493543539,
  493543541,
  493545979,
  493546015,
  493546634,
  493546670,
  493546714,
  493547572,
  493547581,
  493547584,
  493547671,
  493547711,
  493547715],
 [493719461, 495657558, 495659841, 495660835, 495661092],
 [493489532, 493489548],
 [495155308],
 [493334991, 493334992, 493334995],
 [493335003],
 [492017308, 492017311, 492017329],
 [492842805, 492842806],
 [493250573],
 [492041752, 492041843, 492041882, 492041899, 492041924, 492041926],
 [494584453, 494584459],
 [493158752],
 [493024614],
 [494516879],
 [494444092, 494444098, 494444103],
 [494444099],
 [493144797, 493144965],
 [493232286],
 [494546221, 494546279],
 [494482278, 494482279],
 [495086743],
 [494477193, 494477205],
 [494477192, 494477195, 494477196, 494477197, 494477199, 494477203],
 [492941481, 492941482],
 [492941484],
 [492911289, 492911306, 492911545],
 [494444109, 494444115, 494444116],
 [494444112],
 [492919259],
 [492159707],
 [495068219],
 [495068217],
 [495088710],
 [492375306, 492375312],
 [492935688, 492935690, 492935692, 492935693, 492935696],
 [495416223],
 [495425974],
 [492935402, 492935404, 492935406],
 [493150318, 493151284, 493151286],
 [494833134],
 [492183692, 492183697],
 [497832462],
 [497654887, 497654894, 497654895, 497654898, 497654899],
 [496728993],
 [492500614],
 [492397562,
  492397567,
  492397569,
  492397571,
  492397576,
  492397577,
  492397578,
  492397579,
  492397583,
  492397594,
  492397597],
 [492476130],
 [493029811],
 [492169367, 492169577, 492169892, 492169915, 492170063],
 [495775759],
 [492402688],
 [494369180, 494369182, 494369184, 494369185, 494369196],
 [497296202, 497296224],
 [492170152, 492174393],
 [497831685, 497831687],
 [497471147],
 [497195734, 497195772],
 [492169358, 492170088, 492170106],
 [492589051],
 [492298941, 492298942, 492298946],
 [492097297,
  492097298,
  492097299,
  492097320,
  492097326,
  492097332,
  492097343,
  492097347,
  492097353,
  492097365,
  492097377,
  492097388,
  492097390,
  492097398,
  492396193,
  492396195,
  492396197,
  492396201,
  493011156],
 [494426712, 494426726, 494426728, 494428043, 494428047, 494428049],
 [497117122],
 [492184245],
 [492169611, 492169972, 492170037],
 [497717564],
 [492534400],
 [498164373],
 [494106558, 494106562],
 [491904319],
 [492396675, 492396676, 492396679, 492396680, 492396681],
 [492241827],
 [492396709, 492396715, 492396724],
 [492424523],
 [497644448, 497644449, 497644451, 497644454, 497644457],
 [496603127,
  496603129,
  496603131,
  496603136,
  496603137,
  496603142,
  496603143,
  496603144,
  496603147],
 [495143851],
 [492097866, 492097876, 492097882, 492097883],
 [492382341, 492382435, 492382469, 492382572],
 [495536680],
 [491905252, 491905254, 491905260, 491905268, 491905271],
 [493166288, 493168879],
 [492397607],
 [491900916],
 [492395268],
 [494399024, 494399029, 494399031],
 [491915605, 491915607],
 [497528413, 497528415],
 [492539064, 492539068],
 [492281413, 492281414],
 [495393421,
  495393430,
  495393435,
  495393561,
  495393568,
  495393574,
  495393577,
  495393578,
  495393772,
  495393773,
  495393779,
  495393782,
  495393783,
  495393784,
  495393788,
  495393791,
  495393794,
  495393796,
  495393799,
  495393806,
  495393809,
  495393814],
 [492119819, 492120075, 492120676, 492120699, 492120702],
 [492469965],
 [495182838,
  495393424,
  495393425,
  495393429,
  495393431,
  495393432,
  495393433,
  495393436,
  495393567,
  495393569,
  495393581,
  495393751,
  495393755,
  495393769,
  495393776,
  495393787,
  495393789,
  495393800],
 [495393422,
  495393423,
  495393426,
  495393428,
  495393563,
  495393564,
  495393565,
  495393579,
  495393763,
  495393766,
  495393775,
  495393803,
  495393805,
  495393808,
  495393812],
 [493420803,
  495343256,
  495343258,
  495343259,
  495343262,
  495343270,
  495343277,
  495343279,
  495343280,
  495343293,
  495343295,
  495343306,
  495343310,
  495343315,
  495343317,
  495343319],
 [492274295, 492274378, 492274388, 492274471],
 [492120694, 492120701, 492582642, 493008098],
 [492318000, 492318004],
 [492120664, 492120688, 492120707, 492120710],
 [492097383, 492097402, 492097405, 492396189, 492396199],
 [495554820,
  495554823,
  495554833,
  495554835,
  495554839,
  495554861,
  495554863,
  495554872,
  495554876,
  495554878],
 [495299908],
 [492353769, 492353779, 492353780],
 [492414319, 492414321],
 [492389532, 492389533, 492389545, 492389568, 492389611, 492389618],
 [492383020, 492389401, 492389420, 492389457, 492389466, 492389469, 492389488],
 [492085953, 492085957, 493011968],
 [492567478, 492567487],
 [492389526, 492389550, 492389554, 492389584, 492389587, 492389598, 492389621]]

In [526]:
# Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[89]['cells_used']

In [527]:
del zs2_dic2

In [528]:
#Because we used find_cells, then h_geocode_x should be used as new home zone for projcted empoloyees
#So cells_calc_x should be used (it takes h_geocode_x) 

my_list_2=[]
my_list_3=[]
my_list_4=[]

start = time.time()

result = Parallel(n_jobs=-5)(delayed(cells_calc_x)(i, Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[i], Emp_cells2_2030_2_dic[i], cells2_2030_3) for i in range(0,len(Raster_file_paths_new)))

# Convert the result to a dictionary with keys as indices
zs2_dic2 = dict(enumerate(result))

# Step 4: After calculating the results, retrieve the values from the 'zs2_dic' dictionary and store them in the lists 'my_list_2', 'my_list_3', and 'my_list_4'
my_list_2 = [zs2_dic2[i][0] for i in range(len(Raster_file_paths_new))]
my_list_3 = [zs2_dic2[i][1] for i in range(len(Raster_file_paths_new))]
my_list_4 = [zs2_dic2[i][2] for i in range(len(Raster_file_paths_new))]

end = time.time()
print(end - start)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

14.015765905380249

In [529]:
# #Because we used find_cells, then h_geocode_x should be used as new home zone for projcted empoloyees
# #So cells_calc_x should be used (it takes h_geocode_x) 

# my_list_2, my_list_3,my_list_4 = cells_calc_x(Emp_home_select_2030_new_values_merge_u_try5_5_6_dic,Emp_cells2_2030_2_dic, cells2_2030_3)

In [530]:
my_list_2_final={}
my_list_3_final={}
my_list_4_final={}

for l in range(0,len(Raster_file_paths_new)):
    my_list_2_final[l]= my_list_2[l][0]
    my_list_3_final[l]= my_list_3[l][0]
    my_list_4_final[l]= my_list_4[l][0]
    
my_list_2={}
my_list_3={}
my_list_4={}

In [531]:
Emp_cells2_dic_list4_3 =list_4_calc(my_list_4_final,cells2_2030_3,Emp_cells2_dic)

In [532]:
Emp_cells2_dic_list4_3

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage20,damage21,damage22,damage23,damage24,damage25,damage26,damage27,damage28,damage29
0,120150105052018,870918.0,491733644,76RVVX9R+F2H-5-3-4-4,120150105023020,RES,RES1-1SNB,M,1.0,1874.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0
1,120150105052018,872771.0,491735271,76RVVX9R+G98-4-4-4-3,120150105023020,RES,RES1-1SNB,W,1.0,1477.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0
2,120150105052018,874008.0,491736461,76RVVX9Q+H6W-5-4-4-4,120150105023020,RES,RES1-1SNB,W,1.0,2021.0,...,0.0,0.0,0.0,0.0,11.302007,21.480062,36.275505,60.22564,71.298469,100.0
3,120150105052018,874081.0,491736515,76RVVXCR+58H-4-4-4-4,120150105023020,RES,RES1-1SNB,W,1.0,1846.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0
4,120150201033005,932866.0,491795571,76VV2XG8+XFM-4-3-4-3,120150201033003,RES,RES1-1SNB,W,1.0,1475.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,120710402111000,7359347.0,498224045,76RWJ96X+XGP-0-0-0-0,120710402031000,RES,RES1-1SNB,W,1.0,931.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0
1220,120710402111000,7359392.0,498224092,76RWJC62+R2J-0-0-0-0,120710402031000,RES,RES1-1SNB,M,1.0,864.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0
1221,120710402111000,7359404.0,498224116,76RWJC72+498-0-0-0-0,120710402031000,RES,RES1-1SNB,W,1.0,922.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0
1222,120710402111000,7359435.0,498224134,76RWJC72+6FH-0-0-0-0,120710402031000,RES,RES1-1SNB,W,1.0,671.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0
1223,120710402111000,7359441.0,498224145,76RWJC62+V6V-0-0-0-0,120710402031000,RES,RES1-1SNB,M,1.0,804.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.0

In [533]:
# Emp_cells2_dic_list4_3 = list4_2_full(Emp_cells2_dic_list4_3)

In [534]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic=dmg_calc(my_list_2_final, my_list_3_final, Emp_home_select_2030_new_values_merge_u_try5_5_6_dic)

In [535]:
# Emp_home_select_2030_new_values_merge_u_try5_5_6_dic_full = dataframe_full(Emp_home_select_2030_new_values_merge_u_try5_5_6_dic)

In [536]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000'].sum()

1242

In [537]:
select_hgeocode_geo5_6_try_try2_dic_missing['C000'].sum()

125

In [548]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0] = Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0].astype({"cells_used":'int64'})

merge_u_try2= Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0][Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000'] != Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['cells_used']]


merge_u_try2

,dist_x,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,...,min_2030_y,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co
21_a_0,2.18308,3.27359,1.201502e+14,120150202053020,12,015,020206,2058,120150202062058,Block 2058,...,0.0,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
22_a_0,2.18308,3.395047,1.201502e+14,120150202053020,12,015,020303,3005,120150203033005,Block 3005,...,0.0,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
23_a_0,2.18308,2.015315,1.201502e+14,120150202053020,12,015,020601,2017,120150206012017,Block 2017,...,0.0,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
24_a_0,2.18308,1.967096,1.201502e+14,120150202053020,12,015,020800,1002,120150208001002,Block 1002,...,0.0,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
32_a_0,2.781441,1.640535,1.201502e+14,120150202061011,12,015,020303,4018,120150203034018,Block 4018,...,0.0,"POLYGON ((-82.11872 27.03250, -82.11823 27.032...",2.953530e+09,6.0,6.0,0.0,NaN,NaN,None,NaN
56_a_0,2.573692,2.052069,1.201502e+14,120150208001019,12,015,020602,2015,120150206022015,Block 2015,...,0.0,"POLYGON ((-82.08570 27.00105, -82.08201 27.001...",5.902756e+09,6.0,12.0,0.0,NaN,NaN,None,NaN
157_a_0,2.11624,1.699308,1.207101e+14,120710103062005,12,071,010413,3012,120710104133012,Block 3012,...,0.0,"POLYGON ((-81.96571 26.65417, -81.96553 26.654...",1.493237e+09,3.5,3.0,0.0,NaN,NaN,None,NaN
226_a_0,3.997312,3.590329,1.207100e+14,120710103052003,12,071,020700,3015,120710207003015,Block 3015,...,0.0,"POLYGON ((-81.91549 26.64060, -81.91547 26.644...",1.342279e+10,28.5,27.0,0.0,NaN,NaN,None,NaN
384_a_0,1.892079,1.531607,1.211500e+14,121150027452004,12,115,002748,2002,121150027482002,Block 2002,...,0.0,"POLYGON ((-82.17368 27.07203, -82.17296 27.072...",1.977776e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
391_a_0,1.443845,5.455434,1.211500e+14,121150027401063,12,115,002744,1028,121150027441028,Block 1028,...,0.0,"POLYGON ((-82.20419 27.08727, -82.20149 27.087...",3.955818e+09,4.0,8.0,0.0,NaN,NaN,None,NaN
396_a_0,1.592629,1.38298,1.211500e+14,121150027451042,12,115,002745,2041,121150027452041,Block 2041,...,0.0,"POLYGON ((-82.17366 27.04619, -82.17275 27.047...",1.977776e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
414_a_0,33.383533,NaN,NaN,120879715021018,12,087,971800,1011,120879718001011,Block 1011,...,NaN,"POLYGON ((-81.74231 24.58633, -81.74224 24.586...",NaN,NaN,NaN,NaN,NaN,NaN,POINT (24.58195 -81.73427),"(24.581948494796585, -81.73426762009751)"

In [549]:
merge_u_try2['cells_used']

21_a_0      0
22_a_0      0
23_a_0      0
24_a_0      0
32_a_0      0
56_a_0      7
157_a_0     0
226_a_0     0
384_a_0     1
391_a_0     6
396_a_0     1
414_a_0    11
Name: cells_used, dtype: int64

In [550]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0][Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000']<0]

Empty GeoDataFrame
Columns: [dist_x, dist, w_geocode, h_geocode_x, STATEFP20, COUNTYFP20, TRACTCE20, BLOCKCE20, GEOID20, NAME20, MTFCC20, UR20, UACE20, UATYPE20, FUNCSTAT20, ALAND20, AWATER20, INTPTLAT20, INTPTLON20, h_geocode_y, C000, CA01, CA02, CA03, CE01, CE02, CE03, CNS01, CNS02, CNS03, CNS04, CNS05, CNS06, CNS07, CNS08, CNS09, CNS10, CNS11, CNS12, CNS13, CNS14, CNS15, CNS16, CNS17, CNS18, CNS19, CNS20, CR01, CR02, CR03, CR04, CR05, CR07, CT01, CT02, CD01, CD02, CD03, CD04, CS01, CS02, createdate, fd_id_x, found_ht_x, cell_x, min_2030_x, cells_used, C000_dmg, C000_dmg_mean, h_geocode, fd_id_y, found_ht_y, min_2030_y, geometry, fd_id, found_ht, cell_y, min_2030, cell, loop_num, centr, centr_x_co]
Index: []

[0 rows x 82 columns]

In [551]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000'].sum()

1242

In [552]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['cells_used'].sum()

1224

In [553]:
merge_u_try2['C000'].sum()

44

In [544]:
merge_u_try2 = merge_u_try2.reset_index()
# merge_u_try2 = merge_u_try2.drop(['level_0'], axis=1)
merge_u_try2

,index,dist_x,dist,w_geocode,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,...,min_2030_y,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,centr_x_co
0,21_a_0,2.18308,3.27359,1.201502e+14,120150202053020,12,015,020206,2058,120150202062058,...,0.0,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
1,22_a_0,2.18308,3.395047,1.201502e+14,120150202053020,12,015,020303,3005,120150203033005,...,0.0,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
2,23_a_0,2.18308,2.015315,1.201502e+14,120150202053020,12,015,020601,2017,120150206012017,...,0.0,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
3,24_a_0,2.18308,1.967096,1.201502e+14,120150202053020,12,015,020800,1002,120150208001002,...,0.0,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
4,32_a_0,2.781441,1.640535,1.201502e+14,120150202061011,12,015,020303,4018,120150203034018,...,0.0,"POLYGON ((-82.11872 27.03250, -82.11823 27.032...",2.953530e+09,6.0,6.0,0.0,NaN,NaN,None,NaN
5,56_a_0,2.573692,2.052069,1.201502e+14,120150208001019,12,015,020602,2015,120150206022015,...,0.0,"POLYGON ((-82.08570 27.00105, -82.08201 27.001...",5.902756e+09,6.0,12.0,0.0,NaN,NaN,None,NaN
6,157_a_0,2.11624,1.699308,1.207101e+14,120710103062005,12,071,010413,3012,120710104133012,...,0.0,"POLYGON ((-81.96571 26.65417, -81.96553 26.654...",1.493237e+09,3.5,3.0,0.0,NaN,NaN,None,NaN
7,226_a_0,3.997312,3.590329,1.207100e+14,120710103052003,12,071,020700,3015,120710207003015,...,0.0,"POLYGON ((-81.91549 26.64060, -81.91547 26.644...",1.342279e+10,28.5,27.0,0.0,NaN,NaN,None,NaN
8,384_a_0,1.892079,1.531607,1.211500e+14,121150027452004,12,115,002748,2002,121150027482002,...,0.0,"POLYGON ((-82.17368 27.07203, -82.17296 27.072...",1.977776e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
9,391_a_0,1.443845,5.455434,1.211500e+14,121150027401063,12,115,002744,1028,121150027441028,...,0.0,"POLYGON ((-82.20419 27.08727, -82.20149 27.087...",3.955818e+09,4.0,8.0,0.0,NaN,NaN,None,NaN
10,396_a_0,1.592629,1.38298,1.211500e+14,121150027451042,12,115,002745,2041,121150027452041,...,0.0,"POLYGON ((-82.17366 27.04619, -82.17275 27.047...",1.977776e+09,2.0,4.0,0.0,NaN,NaN,None,NaN
11,414_a_0,33.383533,NaN,NaN,120879715021018,12,087,971800,1011,120879718001011,...,NaN,"POLYGON ((-81.74231 24.58633, -81.74224 24.586...",NaN,NaN,NaN,NaN,NaN,NaN,POINT (24.58195 -81.73427),"(24.581948494796585, -81.73426762009751)"

In [564]:
merge_u_try2['h_geocode_y']['396_a_0']

121150027452041.0

In [563]:
merge_u_try2['h_geocode_y']

21_a_0     1.201502e+14
22_a_0     1.201502e+14
23_a_0     1.201502e+14
24_a_0     1.201502e+14
32_a_0     1.201502e+14
56_a_0     1.201502e+14
157_a_0    1.207101e+14
226_a_0    1.207102e+14
384_a_0    1.211500e+14
391_a_0    1.211500e+14
396_a_0    1.211500e+14
414_a_0             NaN
Name: h_geocode_y, dtype: float64

In [562]:
merge_u_try2['GEOID20']

21_a_0     120150202062058
22_a_0     120150203033005
23_a_0     120150206012017
24_a_0     120150208001002
32_a_0     120150203034018
56_a_0     120150206022015
157_a_0    120710104133012
226_a_0    120710207003015
384_a_0    121150027482002
391_a_0    121150027441028
396_a_0    121150027452041
414_a_0    120879718001011
Name: GEOID20, dtype: object

In [565]:
merge_u_try2['h_geocode_y'] = merge_u_try2['GEOID20']

In [568]:
merge_u_try2 = merge_u_try2.drop(['w_geocode'],axis=1)

In [570]:
merge_u_try2 = merge_u_try2.astype({"h_geocode_y":'int64'})

In [571]:
merge_u_try2['h_geocode_x']

21_a_0     120150202053020
22_a_0     120150202053020
23_a_0     120150202053020
24_a_0     120150202053020
32_a_0     120150202061011
56_a_0     120150208001019
157_a_0    120710103062005
226_a_0    120710103052003
384_a_0    121150027452004
391_a_0    121150027401063
396_a_0    121150027451042
414_a_0    120879715021018
Name: h_geocode_x, dtype: object

In [572]:
merge_u_try2['C000']

21_a_0      1
22_a_0      1
23_a_0      1
24_a_0      1
32_a_0      3
56_a_0      9
157_a_0     1
226_a_0     4
384_a_0     2
391_a_0     7
396_a_0     2
414_a_0    12
Name: C000, dtype: int64

In [573]:
merge_u_try2['cells_used']

21_a_0      0
22_a_0      0
23_a_0      0
24_a_0      0
32_a_0      0
56_a_0      7
157_a_0     0
226_a_0     0
384_a_0     1
391_a_0     6
396_a_0     1
414_a_0    11
Name: cells_used, dtype: int64

In [574]:

# Emp_home_select_2030_new_values_merge_u_try5_4_2_2_[Emp_home_select_2030_new_values_merge_u_try5_4_2_2_['h_geocode_y']==10970028005002]

In [575]:
list_cells2_2030_3 = list(deepflatten(cells2_2030_3, depth=1))
Emp_cells2_2030_3_dic = []
# for i in range(0, len(Emp_cells2_dic2)):
Emp_cells2_2030_3_dic = Emp_cells2_2030_2_dic[0].loc[~Emp_cells2_2030_2_dic[0]['fd_id'].isin(list_cells2_2030_3)]
len(Emp_cells2_2030_3_dic)

331145

In [576]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic[0]['C000'].sum()

1242

In [577]:
len(Emp_cells2_2030_2_dic[0]) - len(Emp_cells2_2030_3_dic)

1224

In [578]:
select_hgeocode_geo5_6_try_try2_dic_missing['C000'].sum()

125

In [579]:
len(Emp_cells2) - len(Emp_cells2_2030_3_dic)

55239

In [580]:
Emp_home_select_2030_part2_new2['C000'].sum()

55257.0

## Unlock if merge_u_try2 exists

In [581]:
merge_u_try2['loop_num_3'] = 1

In [582]:
merge_u_try2 = merge_u_try2.astype({"h_geocode_x":'int64'})

In [583]:
merge_u_try2['C000'] = merge_u_try2['C000']-merge_u_try2['cells_used']

In [584]:
merge_u_try2= find_coordinates(merge_u_try2)

Yes
Yes

In [585]:
merge_u_try2=merge_u_try2.drop(['centr_x_co'],axis=1)

In [586]:
merge_u_try2.rename(columns = {'centr_co':'centr_x_co'}, inplace = True)
merge_u_try2.head()

,dist_x,dist,h_geocode_x,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,...,geometry,fd_id,found_ht,cell_y,min_2030,cell,loop_num,centr,loop_num_3,centr_x_co
21_a_0,2.18308,3.27359,120150202053020,12,015,020206,2058,120150202062058,Block 2058,G5040,...,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.01050 -82.09220),1,"(27.010504661164557, -82.09220141131873)"
22_a_0,2.18308,3.395047,120150202053020,12,015,020303,3005,120150203033005,Block 3005,G5040,...,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.01050 -82.09220),1,"(27.010504661164557, -82.09220141131873)"
23_a_0,2.18308,2.015315,120150202053020,12,015,020601,2017,120150206012017,Block 2017,G5040,...,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.01050 -82.09220),1,"(27.010504661164557, -82.09220141131873)"
24_a_0,2.18308,1.967096,120150202053020,12,015,020800,1002,120150208001002,Block 1002,G5040,...,"POLYGON ((-82.09391 27.01094, -82.09303 27.010...",1.967593e+09,2.0,4.0,0.0,NaN,NaN,POINT (27.01050 -82.09220),1,"(27.010504661164557, -82.09220141131873)"
32_a_0,2.781441,1.640535,120150202061011,12,015,020303,4018,120150203034018,Block 4018,G5040,...,"POLYGON ((-82.11872 27.03250, -82.11823 27.032...",2.953530e+09,6.0,6.0,0.0,NaN,NaN,POINT (27.02989 -82.11719),1,"(27.029893846918426, -82.11719379355578)"

In [587]:
Emp_cells2_2030_3_=[]
Emp_cells2_2030_3_sum=[]

# for i in range(0, len(Emp_cells2_dic2)):
Emp_cells2_2030_3_ = Emp_cells2_2030_3_dic.select_dtypes(exclude=['geometry','object'])
Emp_cells2_2030_3_sum = Emp_cells2_2030_3_.groupby(["h_geocode"], as_index=False).sum()
Emp_cells2_2030_3_sum

             h_geocode        fd_id  found_ht  cell  min_2030
0      120150101001000   3934160594      12.0     8       0.0
1      120150101001005   1474969444       4.5     3       0.0
2      120150101001009  23108594843      54.0    47       0.0
3      120150101001010   2458356555       3.5     5       0.0
4      120150101001011    491661116       1.5     1       0.0
...                ...          ...       ...   ...       ...
19854  121150027472071    988826660       1.0     2       0.0
19855  121150027481003   8872376375       9.0    18       0.0
19856  121150027481009  12332393747      12.5    25       0.0
19857  121150027481010   3450388481       3.5     7       0.0
19858  121150027482003   2464608641       2.5     5       0.0

[19859 rows x 5 columns]

In [588]:
Emp_cells2_2030_3_sum=  Emp_cells2_2030_3_sum[['h_geocode','cell']]

In [589]:

Emp_cells_sum_no_dups_final_geo2_2030_final2=Emp_cells_sum_no_dups_final_geo2_2030_final2.drop(['cell'],axis=1)

Emp_cells_sum_no_dups_final_geo2_2030_final2 = pd.merge(Emp_cells_sum_no_dups_final_geo2, Emp_cells2_2030_3_sum,  how='left', 
                left_on=['h_geocode'], right_on = ['h_geocode'])
Emp_cells_sum_no_dups_final_geo2_2030_final2.head()

,h_geocode,geometry,centr,centr_co,cell
0,120150101001000,"POLYGON ((-81.76067 27.01824, -81.75391 27.018...",POINT (26.99423 -81.63713),"(26.9942250731224, -81.63713494337912)",8.0
1,120150101001008,"POLYGON ((-81.77097 27.03391, -81.76417 27.033...",POINT (27.02625 -81.72729),"(27.026252036266474, -81.7272941973198)",NaN
2,120150101001010,"POLYGON ((-81.92338 26.99877, -81.92337 26.998...",POINT (26.99827 -81.91668),"(26.998266609031422, -81.91668264469278)",5.0
3,120150101001011,"POLYGON ((-81.87515 26.99988, -81.87514 27.000...",POINT (26.99440 -81.86809),"(26.994399018510077, -81.86809247619532)",1.0
4,120150101001014,"POLYGON ((-81.95050 26.99490, -81.94761 26.994...",POINT (26.99454 -81.94673),"(26.994537345518484, -81.94672924253014)",4.0

In [590]:
find_cells(Emp_cells_sum_no_dups_final_geo2_2030_final2,merge_u_try2)

n1= 0
temprory4=            h_geocode      dist  cell
347  120150202053021  0.095134   3.0
RHS= 120150202053021
C000= 1
cell_remain= 2.0
n1= 1
temprory4=            h_geocode      dist  cell
347  120150202053021  0.095134   2.0
RHS= 120150202053021
C000= 1
cell_remain= 1.0
n1= 2
temprory4=            h_geocode      dist  cell
345  120150202053018  0.180668   2.0
RHS= 120150202053018
C000= 1
cell_remain= 1.0
n1= 3
temprory4=            h_geocode      dist  cell
344  120150202053017  0.180806   6.0
RHS= 120150202053017
C000= 1
cell_remain= 5.0
n1= 4
temprory4=              h_geocode      dist  cell
10669  121150027461119  0.636552   5.0
RHS= 121150027461119
C000= 3
cell_remain= 2.0
n1= 5
temprory4=            h_geocode     dist  cell
516  120150208001023  0.18931   5.0
RHS= 120150208001023
C000= 2
cell_remain= 3.0
n1= 6
temprory4=             h_geocode      dist  cell
4487  120710103062002  0.186581   4.0
RHS= 120710103062002
C000= 1
cell_remain= 3.0
n1= 7
temprory4=             h_geocode      dist  cell
2766  120710103052008  0.441576  10.0
RHS= 120710103052008
C000= 4
cell_remain= 6.0
n1= 8
temprory4=              h_geocode      dist  cell
14026  121150027452005  0.098164   2.0
RHS= 121150027452005
C000= 1
cell_remain= 1.0
n1= 9
temprory4=              h_geocode      dist  cell
13652  121150027401072  0.092006  12.0
RHS= 121150027401072
C000= 1
cell_remain= 11.0
n1= 10
temprory4=              h_geocode      dist  cell
14006  121150027451041  0.091394   7.0
RHS= 121150027451041
C000= 1
cell_remain= 6.0
n1= 11
temprory4=              h_geocode      dist  cell
10604  120879721003023  3.951548   2.0
RHS= 120879721003023
C000= 1
cell_remain= 1.0

In [591]:
merge_u_try2=merge_u_try2.drop(['loop_num'],axis=1)

In [592]:
# merge_u_try2=merge_u_try2.drop(['loop_num'],axis=1)
Emp_cells2_2030_3_dic2, cells2_2030_4, merge_u_try2_dic = find_cells_SLR(merge_u_try2, Emp_cells2_2030_3_dic)

Yes
i= 0
0.023051023483276367
your here 1
your here 2

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

1.0734479427337646
your here 3
k= 0
k= 1
k= 2
k= 3
k= 4
k= 5
k= 6
k= 7
k= 8
k= 9
k= 10
k= 11
k= 12
k= 13
k= 14
k= 15
k= 16
k= 17
k= 18
k= 19
k= 20
k= 21
k= 22
k= 23
k= 24
k= 25
k= 26
k= 27
k= 28
k= 29
0.025152206420898438

In [593]:
from joblib import Parallel, delayed

my_list_2=[]
my_list_3=[]
my_list_4=[]

start = time.time()


# Step 3: Use the provided code snippet to parallelize the calculations using the 'worker' function
result = Parallel(n_jobs=6)(delayed(cells_calc_x)(i, merge_u_try2_dic[i], Emp_cells2_2030_3_dic2[i], cells2_2030_4) for i in range(0,len(Raster_file_paths_new)))

# Convert the result to a dictionary with keys as indices
zs2_dic2 = dict(enumerate(result))

# Step 4: After calculating the results, retrieve the values from the 'zs2_dic' dictionary and store them in the lists 'my_list_2', 'my_list_3', and 'my_list_4'
my_list_2 = [zs2_dic2[i][0] for i in range(len(Raster_file_paths_new))]
my_list_3 = [zs2_dic2[i][1] for i in range(len(Raster_file_paths_new))]
my_list_4 = [zs2_dic2[i][2] for i in range(len(Raster_file_paths_new))]

end = time.time()
print(end - start)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/_compat.py:124: UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

3.6445119380950928

/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/Malihafez/miniforge3/lib/python3.10/site-packages/geopandas/geodataframe.py:1538: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [594]:
my_list_2_final={}
my_list_3_final={}
my_list_4_final={}

for l in range(0,len(Raster_file_paths_new)):
    my_list_2_final[l]= my_list_2[l][0]
    my_list_3_final[l]= my_list_3[l][0]
    my_list_4_final[l]= my_list_4[l][0]
    
my_list_2={}
my_list_3={}
my_list_4={}

In [595]:
merge_u_try2_dic = dmg_calc(my_list_2_final, my_list_3_final,merge_u_try2_dic)

In [596]:
merge_u_try2_dic_full = dataframe_full(merge_u_try2_dic)

In [597]:
Emp_cells2_2030_4_dic2_list = list_4_calc(my_list_4_final,cells2_2030_4,Emp_cells2_dic)
Emp_cells2_2030_4_dic2_list

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage20,damage21,damage22,damage23,damage24,damage25,damage26,damage27,damage28,damage29
0,120150208001023,1031796.0,491894783,76VV2W28+VC9-3-3-2-2,120150208001022,RES,RES1-1SNB,M,1.0,1302.00,...,77.323721,82.737105,91.349311,98.813219,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
1,120150208001023,1031799.0,491894786,76VV2W28+V77-3-2-2-3,120150208001022,RES,RES1-1SNB,W,1.0,1128.00,...,85.391741,90.805126,99.417332,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2,120150202053021,1301528.0,492164379,76VV2W55+QCF-2-3-3-2,120150202025021,RES,RES1-1SNB,W,1.0,904.00,...,15.006819,17.821780,22.300126,27.271847,49.499527,69.184567,87.229189,100.000000,100.000000,100.000000
3,120150202053021,1301534.0,492164386,76VV2W54+QW7-3-3-2-3,120150202025021,RES,RES1-1SNB,W,1.0,1144.00,...,8.149348,10.747774,15.121769,19.003001,35.694993,55.380033,73.424655,97.374781,100.000000,100.000000
4,120879721003023,1374944.0,492237795,76PWH6GG+MXJ-6-4-5-5,120879721003027,RES,RES1-1SNB,M,1.0,3528.58,...,0.000000,0.000000,1.361483,4.944163,15.914572,27.213062,45.257684,69.207820,80.280654,100.000000
5,120150202053017,1382277.0,492245105,76VV2W65+F96-3-3-4-3,120150202025017,RES,RES1-1SNB,W,1.0,1827.00,...,0.000000,0.000000,0.000000,0.000000,12.886830,23.123050,39.435098,63.385234,74.458063,100.000000
6,120150202053018,1448563.0,492311412,76VV2W75+627-3-3-4-3,120150202025018,RES,RES1-1SNB,W,1.0,2047.00,...,0.000000,0.000000,0.000000,0.000000,9.318008,19.330729,32.142173,56.092309,67.165142,100.000000
7,121150027461119,2044883.0,492908048,76VV2VPP+86J-3-4-3-3,121150027123292,RES,RES1-1SNB,W,1.0,1427.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,121150027461119,2045100.0,492908053,76VV2VPM+7W9-3-2-4-3,121150027123292,RES,RES1-1SNB,W,1.0,1285.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,121150027461119,2045101.0,492908054,76VV2VMP+Q5F-4-3-3-3,121150027123292,RES,RES1-1SNB,W,1.0,2145.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,121150027451041,2072562.0,492935593,76VV2RWG+XQF-3-3-4-3,121150027122113,RES,RES1-1SNB,W,1.0,1300.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.463193,22.221066,53.120466
11,121150027452005,4211634.0,495075543,76VV3RCH+CGR-4-4-4-4,121150027122029,RES,RES1-1SNB,W,1.0,1861.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,121150027401072,4482276.0,495345926,76VV3QQX+4VX-3-3-3-2,121150027121128,RES,RES1-1SNB,W,1.0,1610.00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,120710103062002,6419042.0,497283735,76RWM23P+RQJ-4-3-4-2,120710103062032,RES,RES1-1SNB,W,1.0,1399.00,...,0.000000,0.000000,7.572919,11.155596,22.643623,40.153546,58.198163,82.148294,93.221128,100.000000
14,120710103052008,6985688.0,497850900,76RWJ3WR+G77-3-3-3-3,120710103052005,RES,RES1-1SNB,W,1.0,1730.00,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
15,120710103052008,6988335.0,497850901,76RWJ3WR+G2H-2-3-3-3,120710103052005,RES,RES1-1SNB,W,1.0,1357.00,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
16,120710103052008,6988338.0,497850927,76RWJ3WR+M7F-2-2-2-2,120710103052005,RES,RES1-1SNB,W,1.0,1050.00,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
17,120710103052008,6988341.0,497850930,76RWJ3WR+M97-3-4-3-2,120710103052005,RES,RES1-1SNB,W,1.0,1224.00,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [598]:
len(new_list)

30

In [599]:
len(list_iterate)

90

In [600]:
Emp_cells2_2030_4_dic2_list=Emp_cells2_2030_4_dic2_list.drop(['cell'],axis=1)

In [601]:
def list4_2_full (Emp_cells2_dic_list4_2):
    Emp_cells2_dic_list4_2_modify = Emp_cells2_dic_list4_2.copy()

    for k in range(0,len(my_list_4_final)):
        Emp_cells2_dic_list4_2_modify= Emp_cells2_dic_list4_2_modify.drop(['damage{0}'.format(k)],axis=1)

    Emp_cells2_dic_list4_2_modify

    for index, i in enumerate(new_list):
    #     print(f"i: {i}, j: {index+1}")
        Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = Emp_cells2_dic_list4_2['damage{0}'.format(index)]

    for i in list_iterate:
        Emp_cells2_dic_list4_2_modify['damage{0}'.format(i)] = 0
    Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify.iloc[:,33:]
    Emp_cells2_dic_list4_2_modify_select2 = Emp_cells2_dic_list4_2_modify.iloc[:,:33]

    sorted_columns = sorted(Emp_cells2_dic_list4_2_modify_select.columns, key=custom_sort)
    sorted_Emp_cells2_dic_list4_2_modify_select = Emp_cells2_dic_list4_2_modify_select[sorted_columns]

    Emp_cells2_dic_list4_2 = pd.concat([ Emp_cells2_dic_list4_2_modify_select2,sorted_Emp_cells2_dic_list4_2_modify_select],axis=1)

    return Emp_cells2_dic_list4_2

In [602]:
Emp_cells2_2030_4_dic2_list = list4_2_full(Emp_cells2_2030_4_dic2_list)

In [603]:
list_cells2_2030_4 = list(deepflatten(cells2_2030_4, depth=1))
Emp_cells2_2030_4_dic = []
# for i in range(0, len(Emp_cells2_dic2)):
Emp_cells2_2030_4_dic = Emp_cells2_2030_3_dic.loc[~Emp_cells2_2030_3_dic['fd_id'].isin(list_cells2_2030_4)]
len(Emp_cells2_2030_4_dic)

331127

In [604]:
Emp_home_select_2030_part2_new2['C000'].sum()

55257.0

In [605]:
len(Emp_cells2_dic2[0])- len(Emp_cells2_2030_4_dic)

55257

In [606]:
# # Emp_cells2_2030_1_try_list9


# for i in range(2, loop_ended+1):
#     print(i)
#     pd_trail = pd.concat([globals()['Emp_cells2_2030_1_try_list{0}'.format(i)]],axis=1)

In [607]:
# len(Emp_cells2_2030_1_try_list2)+len(Emp_cells2_2030_1_try_list3)+len(Emp_cells2_2030_1_try_list4)\
# +len(Emp_cells2_2030_1_try_list5)+len(Emp_cells2_2030_1_try_list6)+len(Emp_cells2_2030_1_try_list7)\
# +len(Emp_cells2_2030_1_try_list8)

In [608]:
Emp_cells2_dic_list4_3=Emp_cells2_dic_list4_3.drop(['cell'],axis=1)

In [609]:
Emp_cells2_dic_list4_3 = list4_2_full(Emp_cells2_dic_list4_3)

In [614]:
Emp_cells2_dic_list4=Emp_cells2_dic_list4.drop(['cell'],axis=1)

In [615]:
Emp_cells2_dic_list4 = list4_2_full(Emp_cells2_dic_list4)

In [617]:
Emp_cells2_dic_list4_2=Emp_cells2_dic_list4_2.drop(['cell'],axis=1)

In [618]:
Emp_cells2_dic_list4_2 = list4_2_full(Emp_cells2_dic_list4_2)

In [620]:
for i in range(2, loop_ended+1):
    globals()['Emp_cells2_2030_1_try_list{0}'.format(i)] = globals()['Emp_cells2_2030_1_try_list{0}'.format(i)].drop(['cell'],axis=1)
    globals()['Emp_cells2_2030_1_try_list{0}'.format(i)] = list4_2_full(globals()['Emp_cells2_2030_1_try_list{0}'.format(i)])

In [621]:
# Assuming the dataframes are named in a sequential manner
dataframes = []
for i in range(2, loop_ended+1):
    dataframe_name = f"Emp_cells2_2030_1_try_list{i}"
    dataframe = eval(dataframe_name)
    dataframes.append(dataframe)

In [622]:
# Assuming all the dataframes have the same columns
# We will store them in a list and then concatenate them
# Assuming the dataframes are named in a sequential manner
dataframes = []
for i in range(2, loop_ended+1):
    dataframe_name = f"Emp_cells2_2030_1_try_list{i}"
    dataframe = eval(dataframe_name)
    dataframes.append(dataframe)

# We will initialize total_dataframe with the first dataframe
total_dataframe = dataframes[0]

# We will then loop through the remaining dataframes
for dataframe in dataframes[1:]:
    # And append each dataframe to the total_dataframe
    total_dataframe = pd.concat(dataframes, ignore_index=True)

# Now total_dataframe contains all the data from the other dataframes
pd.DataFrame(total_dataframe)

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage110,damage111,damage112,damage113,damage114,damage115,damage116,damage117,damage118,damage119
0,120150105052018,870915.0,491733638,76RVVX8V+X39-4-3-2-3,120150105023020,RES,RES1-1SNB,W,1.0,1782.0,...,0.000000,0.000000,0,0,0,0,0,0,0.000000,0.0
1,120150105052018,870923.0,491733655,76RVVX9Q+53C-3-2-4-3,120150105023020,RES,RES1-1SNB,M,1.0,1827.0,...,62.869548,86.819674,0,0,0,0,0,0,97.892508,100.0
2,120150105052018,872788.0,491736408,76RVVX8R+JXV-4-3-3-3,120150105023020,RES,RES1-1SNB,W,1.0,1880.0,...,0.000000,0.000000,0,0,0,0,0,0,0.000000,0.0
3,120150105052018,872791.0,491736414,76RVVX9R+4F2-4-2-3-4,120150105023020,RES,RES1-1SNB,W,1.0,1965.0,...,0.000000,0.000000,0,0,0,0,0,0,0.000000,0.0
4,120150105052018,872792.0,491736416,76RVVXCR+42H-7-4-6-4,120150105023020,RES,RES1-1SNB,W,1.0,2139.0,...,0.000000,0.000000,0,0,0,0,0,0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7399,120710103052003,6272929.0,497137588,76RWJ3WP+Q7P-4-4-3-3,120710103052015,RES,RES1-1SNB,W,1.0,2977.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
7400,120710103052003,6276343.0,497140982,76RWJ3RP+C7G-3-1-3-2,120710103052014,RES,RES1-1SNB,C,1.0,1003.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
7401,120710103052003,6276381.0,497141020,76RWJ3RP+P46-4-4-5-4,120710103052014,RES,RES1-1SNB,W,1.0,2258.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
7402,120710103052003,6292504.0,497157167,76RWJ3XQ+837-5-3-5-4,120710103052003,RES,RES1-1SNB,W,1.0,2156.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
7403,120710103052003,6848065.0,497712818,76RWJ3RR+55M-3-4-2-3,120710103052013,RES,RES1-1SNB,W,1.0,1596.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0

In [623]:
len(pd.DataFrame(total_dataframe)['fd_id'].unique())

7404

In [624]:
list4_final_out = pd.concat([Emp_cells2_dic_list4, pd.DataFrame(total_dataframe), Emp_cells2_dic_list4_2, Emp_cells2_dic_list4_3, Emp_cells2_2030_4_dic2_list],axis=0) 
       
list4_final_out

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage110,damage111,damage112,damage113,damage114,damage115,damage116,damage117,damage118,damage119
0,121150011012006,2117.0,492858865,76VV9F8C+JQJ-2-1-2-2,121150011012022,RES,RES1-1SNB,C,1.0,756.0,...,0.000000,0.000000,0,0,0,0,0,0,0.000000,0.0
1,120210106053002,2289.0,493680983,76RW4773+4CH-4-4-4-4,120210106053002,RES,RES1-1SNB,W,1.0,1875.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
2,120210104011007,2417.0,494317506,76RW567C+WV7-3-3-4-3,120210104011009,RES,RES1-1SNB,W,1.0,2043.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
3,120210109062001,2667.0,495400878,76QWW9C4+P95-0-0-0-0,120210109031002,RES,RES1-1SNB,M,1.0,576.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
4,120810020173004,2780.0,495736994,76VVCH52+HMX-0-0-0-0,120810020171020,RES,RES1-1SNB,W,1.0,1388.0,...,0.000000,0.000000,0,0,0,0,0,0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,120710103062002,6419042.0,497283735,76RWM23P+RQJ-4-3-4-2,120710103062032,RES,RES1-1SNB,W,1.0,1399.0,...,58.198163,82.148294,0,0,0,0,0,0,93.221128,100.0
14,120710103052008,6985688.0,497850900,76RWJ3WR+G77-3-3-3-3,120710103052005,RES,RES1-1SNB,W,1.0,1730.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
15,120710103052008,6988335.0,497850901,76RWJ3WR+G2H-2-3-3-3,120710103052005,RES,RES1-1SNB,W,1.0,1357.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
16,120710103052008,6988338.0,497850927,76RWJ3WR+M7F-2-2-2-2,120710103052005,RES,RES1-1SNB,W,1.0,1050.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
17,120710103052008,6988341.0,497850930,76RWJ3WR+M97-3-4-3-2,120710103052005,RES,RES1-1SNB,W,1.0,1224.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0

In [625]:
list4_final_out = list4_final_out.rename(columns={'damage' + str(i): 'damage' + str(i+1) for i in range(0, 720)})

In [626]:
list4_final_out

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,damage111,damage112,damage113,damage114,damage115,damage116,damage117,damage118,damage119,damage120
0,121150011012006,2117.0,492858865,76VV9F8C+JQJ-2-1-2-2,121150011012022,RES,RES1-1SNB,C,1.0,756.0,...,0.000000,0.000000,0,0,0,0,0,0,0.000000,0.0
1,120210106053002,2289.0,493680983,76RW4773+4CH-4-4-4-4,120210106053002,RES,RES1-1SNB,W,1.0,1875.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
2,120210104011007,2417.0,494317506,76RW567C+WV7-3-3-4-3,120210104011009,RES,RES1-1SNB,W,1.0,2043.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
3,120210109062001,2667.0,495400878,76QWW9C4+P95-0-0-0-0,120210109031002,RES,RES1-1SNB,M,1.0,576.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
4,120810020173004,2780.0,495736994,76VVCH52+HMX-0-0-0-0,120810020171020,RES,RES1-1SNB,W,1.0,1388.0,...,0.000000,0.000000,0,0,0,0,0,0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,120710103062002,6419042.0,497283735,76RWM23P+RQJ-4-3-4-2,120710103062032,RES,RES1-1SNB,W,1.0,1399.0,...,58.198163,82.148294,0,0,0,0,0,0,93.221128,100.0
14,120710103052008,6985688.0,497850900,76RWJ3WR+G77-3-3-3-3,120710103052005,RES,RES1-1SNB,W,1.0,1730.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
15,120710103052008,6988335.0,497850901,76RWJ3WR+G2H-2-3-3-3,120710103052005,RES,RES1-1SNB,W,1.0,1357.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
16,120710103052008,6988338.0,497850927,76RWJ3WR+M7F-2-2-2-2,120710103052005,RES,RES1-1SNB,W,1.0,1050.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0
17,120710103052008,6988341.0,497850930,76RWJ3WR+M97-3-4-3-2,120710103052005,RES,RES1-1SNB,W,1.0,1224.0,...,100.000000,100.000000,0,0,0,0,0,0,100.000000,100.0

In [627]:
# list4_final_out = list4_final_out.reset_index()

In [628]:
# list4_final_out= list4_final_out.drop(['index'],axis=1)

In [629]:
year_1

2090

In [630]:
#Allocated cells with damages 

list4_final_out.to_file('Buildings_list4_final_out_{0}.shp'.format(year_1))

In [631]:
Emp_cells

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
360,120150201011010,1898.0,491767073,76VV2X3Q+JV7-3-3-4-4,120150201012010,RES,RES1-1SNB,W,1.0,1999.0,...,0.18,0.08,-82.010330,27.004031,NaN,5.329113,17.483967,POINT (-82.01033 27.00403),015,1
379,120150202061034,1938.0,491915584,76VV2VFQ+CPH-4-2-3-3,120150202021046,RES,RES1-1SNB,W,1.0,1657.0,...,0.18,0.08,-82.110648,27.023557,NaN,4.227000,13.868111,POINT (-82.11065 27.02356),015,1
380,120150205012069,1941.0,491927247,76RVXV77+MPR-3-3-4-2,120150205012065,RES,RES1-1SNB,W,1.0,1462.0,...,0.18,0.08,-82.135730,26.964231,AE,0.900085,2.953035,POINT (-82.13573 26.96423),015,1
385,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.18,0.08,-82.306143,26.923544,NaN,3.585037,11.761934,POINT (-82.30614 26.92354),015,1
386,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.13,0.03,-81.728035,25.913643,NaN,3.590633,11.780292,POINT (-81.72803 25.91364),021,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544324,120710303001023,7362124.0,498226804,76RWP93W+264-0-0-0-0,120710303001022,RES,RES1-1SNB,W,1.0,510.0,...,0.17,0.05,-81.604428,26.702522,NaN,3.825020,12.549277,POINT (-81.60443 26.70252),071,1
2544591,120710302011004,7362643.0,498226048,76RWM7W6+V2V-0-0-0-0,120710302011005,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.739960,26.697237,AE,2.931039,9.616270,POINT (-81.73996 26.69724),071,1
2544592,120710302011004,7362644.0,498226050,76RWM7V5+6PJ-0-0-0-0,120710302011017,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.740725,26.693076,AE,3.146635,10.323605,POINT (-81.74073 26.69308),071,1
2544599,120710302012002,7362651.0,498226064,76RWM7R5+3WR-0-0-0-0,120710302011024,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.740242,26.690234,AE,1.498931,4.917752,POINT (-81.74024 26.69023),071,1
2544610,120710302011004,7362662.0,498226086,76RWM7X8+8GX-0-0-0-0,120710302011005,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.733640,26.698365,NaN,3.087558,10.129784,POINT (-81.73364 26.69836),071,1

In [632]:
Emp_cells2_2030_3_dic_out = Emp_cells[Emp_cells['fd_id'].isin(Emp_cells2_2030_4_dic['fd_id'])]

In [633]:
Emp_cells2_2030_3_dic_out

,h_geocode,fid,fd_id,bid,cbfips,st_damcat,occtype,bldgtype,num_story,sqft,...,o65disable,u65disable,x,y,firmzone,grnd_elv_m,ground_elv,geometry,COUNTYFP,cell
360,120150201011010,1898.0,491767073,76VV2X3Q+JV7-3-3-4-4,120150201012010,RES,RES1-1SNB,W,1.0,1999.0,...,0.18,0.08,-82.010330,27.004031,NaN,5.329113,17.483967,POINT (-82.01033 27.00403),015,1
379,120150202061034,1938.0,491915584,76VV2VFQ+CPH-4-2-3-3,120150202021046,RES,RES1-1SNB,W,1.0,1657.0,...,0.18,0.08,-82.110648,27.023557,NaN,4.227000,13.868111,POINT (-82.11065 27.02356),015,1
385,120150304011001,1961.0,492073948,76RVWMFV+CG9-3-4-2-3,120150304011001,RES,RES1-1SNB,M,1.0,1684.0,...,0.18,0.08,-82.306143,26.923544,NaN,3.585037,11.761934,POINT (-82.30614 26.92354),015,1
386,120210110032002,1964.0,492083201,76QWW77C+FQ4-8-8-7-4,120210110021008,RES,RES1-1SNB,M,1.0,992.0,...,0.13,0.03,-81.728035,25.913643,NaN,3.590633,11.780292,POINT (-81.72803 25.91364),021,1
393,120810020212027,1973.0,492122842,76VVCHV3+323-4-5-4-4,120810020072028,RES,RES1-1SNB,W,1.0,2784.0,...,0.17,0.04,-82.447449,27.442633,NaN,11.965964,39.258414,POINT (-82.44745 27.44263),081,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544324,120710303001023,7362124.0,498226804,76RWP93W+264-0-0-0-0,120710303001022,RES,RES1-1SNB,W,1.0,510.0,...,0.17,0.05,-81.604428,26.702522,NaN,3.825020,12.549277,POINT (-81.60443 26.70252),071,1
2544591,120710302011004,7362643.0,498226048,76RWM7W6+V2V-0-0-0-0,120710302011005,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.739960,26.697237,AE,2.931039,9.616270,POINT (-81.73996 26.69724),071,1
2544592,120710302011004,7362644.0,498226050,76RWM7V5+6PJ-0-0-0-0,120710302011017,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.740725,26.693076,AE,3.146635,10.323605,POINT (-81.74073 26.69308),071,1
2544599,120710302012002,7362651.0,498226064,76RWM7R5+3WR-0-0-0-0,120710302011024,RES,RES1-1SNB,W,1.0,1462.0,...,0.17,0.05,-81.740242,26.690234,AE,1.498931,4.917752,POINT (-81.74024 26.69023),071,1
2544610,120710302011004,7362662.0,498226086,76RWM7X8+8GX-0-0-0-0,120710302011005,RES,RES1-1SNB,M,1.0,1462.0,...,0.17,0.05,-81.733640,26.698365,NaN,3.087558,10.129784,POINT (-81.73364 26.69836),071,1

In [634]:
Emp_cells2_2030_3_dic_out.to_pickle("bldgs_RES_remain_{0}.pickle".format(year_1))

In [635]:
def prepare_sum(Emp_home_select_2030_new_values_merge_u_dic):
    select = {}
    Emp_home_select_2030_new_values_merge_u_dic_ = {}
    Emp_home_select_2030_new_values_merge_u_dic_sum = {}
    Emp_home_select_2030_new_values_merge_u_dic_mean={}

    for i in range (0,len(Emp_home_select_2030_new_values_merge_u_dic)):
        select[i] = Emp_home_select_2030_new_values_merge_u_dic[i][Emp_home_select_2030_new_values_merge_u_dic[i]["C000_dmg"]>0]
        
        
        Emp_home_select_2030_new_values_merge_u_dic_[i] =  select[i].select_dtypes(exclude=['geometry'])    
        Emp_home_select_2030_new_values_merge_u_dic_[i] =  Emp_home_select_2030_new_values_merge_u_dic_[i][[
            'C000','CA01','CA02','CA03','CR01','CR02','CR03','CR04','CR05','CR07','CE01','CE02','CE03',
            'CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12',
            'CNS13','CNS14','CNS15','CNS16','CNS17','CNS18','CNS19','CNS20','C000_dmg','C000_dmg_mean',
            'CD01','CD02','CD03','CD04','CT01','CT02','CS01','CS02','C000_2030','CNS01_2030','CNS02_2030',
        'CNS03_2030','CNS04_2030','CNS05_2030','CNS06_2030','CNS07_2030','CNS08_2030','CNS09_2030','CNS10_2030',
        'CNS11_2030','CNS12_2030','CNS13_2030','CNS14_2030','CNS15_2030','CNS16_2030','CNS17_2030','CNS18_2030',
        'CNS19_2030','CNS20_2030','CR01_2030','CR02_2030','CR03_2030','CR04_2030','CR05_2030','CR07_2030',
        'CA01_2030','CA02_2030','CA03_2030','CE01_2030','CE02_2030','CE03_2030','CT01_2030','CT02_2030','CD01_2030',
        'CD02_2030','CD03_2030','CD04_2030','CS01_2030','CS02_2030','C000A_2030','C000E_2030','C000R_2030',
        'C000D_2030','C000T_2030','C000S_2030']] 
        Emp_home_select_2030_new_values_merge_u_dic_sum[i] = (Emp_home_select_2030_new_values_merge_u_dic_[i][Emp_home_select_2030_new_values_merge_u_dic_[i]["C000_dmg"]>0]).sum()
        Emp_home_select_2030_new_values_merge_u_dic_sum[i] =Emp_home_select_2030_new_values_merge_u_dic_sum[i].astype('int64')
        Emp_home_select_2030_new_values_merge_u_dic_mean[i] = Emp_home_select_2030_new_values_merge_u_dic_[i][['C000_dmg_mean']]
        Emp_home_select_2030_new_values_merge_u_dic_sum[i]['C000_dmg_mean_2030'] = (Emp_home_select_2030_new_values_merge_u_dic_mean[i][Emp_home_select_2030_new_values_merge_u_dic_mean[i]["C000_dmg_mean"]>0]).mean()[0]

    return Emp_home_select_2030_new_values_merge_u_dic_sum

In [636]:
for i in range(0,10):
    if i ==0:
        print('no damage')
    else:
        print(i)

no damage
1
2
3
4
5
6
7
8
9

In [637]:
def select_sum(select_hgeocode_geo5_6_dic_sum):
    import numpy as np
    import random
    select1 = {}
    select = {}
    unselect ={}
    final1 = {}
    final2 = {}
    bucket = []
    bucket2 = []

    bucket_list = [['empty','empty'], 23121210]
    bucket.append(bucket_list)
    
    bucket_list2 = [['empty','empty'], 23121212]
    bucket2.append(bucket_list2)


    for i in range (0,len(select_hgeocode_geo5_6_dic_sum)):
        
        if 'h_geocode_y' in select_hgeocode_geo5_6_dic_sum[i].columns:
            pass
        else: 
            select_hgeocode_geo5_6_dic_sum[i].rename(columns = {'h_geocode':'h_geocode_y'}, inplace = True)
        
        print('i=',i)
        max_value = []
        select1[i] = select_hgeocode_geo5_6_dic_sum[i][select_hgeocode_geo5_6_dic_sum[i]["C000_dmg"]>0]
        
#         print('select1[C000_dmg]',select1[i]['C000_dmg'])
        
        unselect[i] =select1[i].drop(['C000','CA01','CA02','CA03','CR01','CR02','CR03','CR04','CR05','CR07','CE01','CE02','CE03',
            'CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12',
            'CNS13','CNS14','CNS15','CNS16','CNS17','CNS18','CNS19','CNS20','C000_dmg','C000_dmg_mean',
            'CD01','CD02','CD03','CD04','CT01','CT02','CS01','CS02','h_geocode_y'],axis=1)
        
        select[i] =select1[i][['C000','CA01','CA02','CA03','CR01','CR02','CR03','CR04','CR05','CR07','CE01','CE02','CE03',
            'CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12',
            'CNS13','CNS14','CNS15','CNS16','CNS17','CNS18','CNS19','CNS20','C000_dmg','C000_dmg_mean',
            'CD01','CD02','CD03','CD04','CT01','CT02','CS01','CS02','h_geocode_y']]
        
        select[i] = select[i].reset_index()
        
        
        select[i]['C000_2030'] ={}
        select[i]['CNS01_2030'] ={}
        select[i]['CNS02_2030'] ={}
        select[i]['CNS03_2030'] ={}
        select[i]['CNS04_2030'] ={}
        select[i]['CNS05_2030'] ={}
        select[i]['CNS06_2030'] ={}
        select[i]['CNS07_2030'] ={}
        select[i]['CNS08_2030'] ={}
        select[i]['CNS09_2030'] ={}
        select[i]['CNS10_2030'] ={}
        select[i]['CNS11_2030'] ={}
        select[i]['CNS12_2030'] ={}
        select[i]['CNS13_2030'] ={}
        select[i]['CNS14_2030'] ={}
        select[i]['CNS15_2030'] ={}
        select[i]['CNS16_2030'] ={}
        select[i]['CNS17_2030'] ={}
        select[i]['CNS18_2030'] ={}
        select[i]['CNS19_2030'] ={}
        select[i]['CNS20_2030'] ={}
        select[i]['C000_2030']  ={}
        select[i]['CA01_2030'] ={}
        select[i]['CA02_2030'] ={}
        select[i]['CA03_2030'] ={}
        select[i]['CE01_2030'] ={}
        select[i]['CE02_2030'] ={}
        select[i]['CE03_2030'] ={}
        select[i]['CR01_2030'] ={}
        select[i]['CR02_2030'] ={}
        select[i]['CR03_2030'] ={}
        select[i]['CR04_2030'] ={}
        select[i]['CR05_2030'] ={}
        select[i]['CR07_2030'] ={}
        select[i]['CD01_2030'] ={}
        select[i]['CD02_2030'] ={}
        select[i]['CD03_2030'] ={}
        select[i]['CD04_2030'] ={}
        select[i]['CT01_2030'] ={}
        select[i]['CT02_2030'] ={}
        select[i]['CS01_2030'] ={}
        select[i]['CS02_2030'] ={}
        select[i]['C000A_2030'] ={}
        select[i]['C000E_2030'] ={}
        select[i]['C000R_2030'] ={}
        select[i]['C000S_2030'] ={}
        select[i]['C000T_2030'] ={}
        select[i]['C000D_2030'] ={}
        
        for q in range (0,len(select[i])):
#             print('select[i][CNS01]=',select[i]['CNS01'])
#             print('select[i]=',select[i])
#             print('select[i][CNS01][q]=',select[i]['CNS01'][q])
#             if pd.isna(select[i]['CNS01'][q]):
#                 select[i]['CNS01'][q].replace(np.nan, 0, inplace=True)
#                 print('CNS01=',pd.DataFrame(select[i]['CNS01'][q]))
#             else:
#                 pass
#             print('CNS01=',select[i]['CNS01'][q])
#             print('C000=',select[i]['C000'][q])
#             print('C000_dmg=',select[i]['C000_dmg'][q])
#             print('h_geocode_y=',select[i]['h_geocode_y'][q])

            select[i]['CNS01_2030'][q]=Round_up((select[i]['CNS01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS02_2030'][q]=Round_up((select[i]['CNS02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS03_2030'][q]=Round_up((select[i]['CNS03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS04_2030'][q]=Round_up((select[i]['CNS04'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS05_2030'][q]=Round_up((select[i]['CNS05'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS06_2030'][q]=Round_up((select[i]['CNS06'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS07_2030'][q]=Round_up((select[i]['CNS07'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS08_2030'][q]=Round_up((select[i]['CNS08'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS09_2030'][q]=Round_up((select[i]['CNS09'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS10_2030'][q]=Round_up((select[i]['CNS10'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS11_2030'][q]=Round_up((select[i]['CNS11'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS12_2030'][q]=Round_up((select[i]['CNS12'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS13_2030'][q]=Round_up((select[i]['CNS13'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS14_2030'][q]=Round_up((select[i]['CNS14'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS15_2030'][q]=Round_up((select[i]['CNS15'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS16_2030'][q]=Round_up((select[i]['CNS16'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS17_2030'][q]=Round_up((select[i]['CNS17'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS18_2030'][q]=Round_up((select[i]['CNS18'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS19_2030'][q]=Round_up((select[i]['CNS19'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CNS20_2030'][q]=Round_up((select[i]['CNS20'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CA01_2030'][q]=Round_up((select[i]['CA01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CA02_2030'][q]=Round_up((select[i]['CA02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CA03_2030'][q]=Round_up((select[i]['CA03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CE01_2030'][q]=Round_up((select[i]['CE01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CE02_2030'][q]=Round_up((select[i]['CE02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CE03_2030'][q]=Round_up((select[i]['CE03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR01_2030'][q]=Round_up((select[i]['CR01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR02_2030'][q]=Round_up((select[i]['CR02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR03_2030'][q]=Round_up((select[i]['CR03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR04_2030'][q]=Round_up((select[i]['CR04'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR05_2030'][q]=Round_up((select[i]['CR05'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CR07_2030'][q]=Round_up((select[i]['CR07'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CD01_2030'][q]=Round_up((select[i]['CD01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CD02_2030'][q]=Round_up((select[i]['CD02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CD03_2030'][q]=Round_up((select[i]['CD03'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CD04_2030'][q]=Round_up((select[i]['CD04'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CT01_2030'][q]=Round_up((select[i]['CT01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CT02_2030'][q]=Round_up((select[i]['CT02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CS01_2030'][q]=Round_up((select[i]['CS01'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])
            select[i]['CS02_2030'][q]=Round_up((select[i]['CS02'][q]/select[i]['C000'][q])*select[i]['C000_dmg'][q])      
            
#             print('CD01=',select[i]['CD01'][q])
#             print('CD02=',select[i]['CD02'][q])
#             print('CD03=',select[i]['CD03'][q])
#             print('CD04=',select[i]['CD04'][q])            
#             print('CD01_2030=',select[i]['CD01_2030'][q])
#             print('CD02_2030=',select[i]['CD02_2030'][q])
#             print('CD03_2030=',select[i]['CD03_2030'][q])
#             print('CD04_2030=',select[i]['CD04_2030'][q])
#             print('C000_dmg=',select[i]['C000_dmg'][q])
#             print('C000=',select[i]['C000'][q])

            select[i]['C000_2030'][q] = select[i]['CNS01_2030'][q]\
                                                            +select[i]['CNS02_2030'][q]\
                                                            +select[i]['CNS03_2030'][q]\
                                                            +select[i]['CNS04_2030'][q]\
                                                            +select[i]['CNS05_2030'][q]\
                                                            +select[i]['CNS06_2030'][q]\
                                                            +select[i]['CNS07_2030'][q]\
                                                            +select[i]['CNS08_2030'][q]\
                                                            +select[i]['CNS09_2030'][q]\
                                                            +select[i]['CNS10_2030'][q]\
                                                            +select[i]['CNS11_2030'][q]\
                                                            +select[i]['CNS12_2030'][q]\
                                                            +select[i]['CNS13_2030'][q]\
                                                            +select[i]['CNS14_2030'][q]\
                                                            +select[i]['CNS15_2030'][q]\
                                                            +select[i]['CNS16_2030'][q]\
                                                            +select[i]['CNS17_2030'][q]\
                                                            +select[i]['CNS18_2030'][q]\
                                                            +select[i]['CNS19_2030'][q]\
                                                            +select[i]['CNS20_2030'][q]
#             print('q=',q)
#             print('C000_2030',select[i]['C000_2030'] )


            select[i]['C000A_2030'][q] = select[i]['CA01_2030'][q]\
                                                             +select[i]['CA02_2030'][q]\
                                                             +select[i]['CA03_2030'][q]

            select[i]['C000E_2030'][q] = select[i]['CE01_2030'][q]\
                                                             +select[i]['CE02_2030'][q]\
                                                             +select[i]['CE03_2030'][q]

            select[i]['C000R_2030'][q] = select[i]['CR01_2030'][q]\
                                                             +select[i]['CR02_2030'][q]\
                                                             +select[i]['CR03_2030'][q]\
                                                             +select[i]['CR04_2030'][q]\
                                                             +select[i]['CR05_2030'][q]\
                                                             +select[i]['CR07_2030'][q]

            select[i]['C000D_2030'][q] = select[i]['CD01_2030'][q]\
                                                             +select[i]['CD02_2030'][q]\
                                                             +select[i]['CD03_2030'][q]\
                                                             +select[i]['CD04_2030'][q]

            select[i]['C000T_2030'][q] = select[i]['CT01_2030'][q]\
                                                             +select[i]['CT02_2030'][q]

            select[i]['C000S_2030'][q] = select[i]['CS01_2030'][q]\
                                                             +select[i]['CS02_2030'][q]
                
                
                
            if select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] == 1 :
#                 print('C000_dmg - C000_2030=', select[i]['C000_dmg'][q] - select[i]['C000_2030'][q])
#                 print('select[i][h_geocode_y] =',(select[i]['h_geocode_y'][q]))
                max_value_test0 = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                             'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                             'CNS19','CNS20']].iloc[q,:]).T.max().max() 
                max_value_columns_test0 = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].max() == max_value_test0]
#                 print('max_value_columns_test0=',max_value_columns_test0)
                max_value_random_test0 = random.choice(max_value_columns_test0) 
#                 print('max_value_random_test0=',max_value_random_test0)

                if (i in range(0,len(select_hgeocode_geo5_6_dic_sum),3)) and (select[i]['h_geocode_y'][q]) not in (pd.DataFrame(bucket2)[1].values):
                    max_value_0 = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.max().max() 
                    max_value_columns_0 = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].max() == max_value_0]
                    max_value_random_0 = random.choice(max_value_columns_0) 
                    
                    bucket_list2 = [max_value_random_0,select[i]['h_geocode_y'][q]]
#                     print('bucket_list=',bucket_list2)
                    
#                     print('max_value_random_0_if=',max_value_random_0)
                elif ((select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket2)[1].values)) :
                    max_value_random_0_temp = pd.DataFrame(bucket2)[0].values[pd.DataFrame(bucket2)[1].values == (select[i]['h_geocode_y'][q])]
#                     print('(max_value_random_0_temp[0])',(max_value_random_0_temp[0]))
#                     print('(max_value_random_0_temp)',(max_value_random_0_temp))

                    if isinstance((max_value_random_0_temp)[0], list) :
#                         print('used this one (if)')
                        max_value_random_0_list = max_value_random_0_temp[0]
                        max_value_random_0 = random.choice(max_value_random_0_list) 
                        
                    else:
                        max_value_random_0 = max_value_random_0_temp[0]
#                         print('used this (else)')
#                     print('max_value_random_0_elif=',max_value_random_0)   

                else:
                    max_value_random_0 = max_value_random_test0
                    bucket_list2 = [max_value_random_0,select[i]['h_geocode_y'][q]]

#                 print('max_value_random_0=',max_value_random_0)   
#                 print('LHS_before',select[i][max_value_random_0+'_2030'][q])
                select[i][max_value_random_0+'_2030'][q] =select[i][max_value_random_0+'_2030'][q]\
                    + (select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] )
#                 print('LHS_after',select[i][max_value_random_0+'_2030'][q])

                
            if select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] > 1 :
#                 print('C000_dmg - C000_2030=', select[i]['C000_dmg'][q] - select[i]['C000_2030'][q])
#                 print('select[i][h_geocode_y] =',(select[i]['h_geocode_y'][q]))
                max_value_test = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                             'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                             'CNS19','CNS20']].iloc[q,:]).T.max().max() 
                max_value_columns_test = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].max() == max_value_test]
#                 print('max_value_columns_test=',max_value_columns_test)
#                 print('len(max_value_columns_test)=',len(max_value_columns_test))
#                 print('max_value_columns_test[0]=',max_value_columns_test[0])
#                 print('C000_2030[q]',select[i]['C000_2030'][q] )
#                 select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                select[i]['C000_dmg'] = select[i]['C000_dmg'].astype(int)

                if len(max_value_columns_test) >1 :
#                     select[i]['C000_2030'] = select[i]['C000_2030'][q].astype(int)
                    if (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]) > len(max_value_columns_test):
                        temp_list = ['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                 'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                 'CNS19','CNS20']
                        temp_select = list(set(temp_list)-set(max_value_columns_test))
#                         print('temp_select=',temp_select)
                        max_value_test_try2 = pd.DataFrame(select[i][temp_select].iloc[q,:]).T.max().max()                     
                        max_value_columns_test_try2 = [col for col in pd.DataFrame(select[i][temp_select].iloc[q,:]).T.columns if pd.DataFrame(select[i][temp_select].iloc[q,:]).T[col].max() == max_value_test_try2]
                        temp_select_final = list(set(max_value_columns_test) | set(max_value_columns_test_try2))
#                         print('temp_select_final=',temp_select_final)
#                         print('k=',(select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                        if (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]) < len(temp_select_final):
                            select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                            max_value_random_test = random.sample(temp_select_final, k= (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                        else:
                            max_value_random_test=temp_select_final
                    else:
                        pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                        select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                        max_value_random_test = random.sample(max_value_columns_test, k= (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                        
                else:
                    max_value_random_test = max_value_columns_test[0]

#                 print('max_value_random_test=',max_value_random_test)
                if (i in range(0,len(select_hgeocode_geo5_6_dic_sum),3)) and (select[i]['h_geocode_y'][q]) not in (pd.DataFrame(bucket2)[1].values):
                    max_value_ = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.max().max() 
                    max_value_columns_ = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].max() == max_value_]
                    
#                     select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                    if len(max_value_columns_) > 1 :
                        if (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]) > len(max_value_columns_test):
                            temp_list = ['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                     'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                     'CNS19','CNS20']
                            temp_select_ = list(set(temp_list)-set(max_value_columns_))
#                             print('temp_select_=',temp_select_)
                            max_value_try2 = pd.DataFrame(select[i][temp_select_].iloc[q,:]).T.max().max()                     
                            max_value_columns_try2 = [col for col in pd.DataFrame(select[i][temp_select_].iloc[q,:]).T.columns if pd.DataFrame(select[i][temp_select_].iloc[q,:]).T[col].max() == max_value_try2]
                            temp_select_final_ = list(set(max_value_columns_) | set(max_value_columns_try2))
                            if (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]) < len(temp_select_final):
                                select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                                max_value_random_ = random.sample(temp_select_final_, k= (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                            else:
                                max_value_random_=temp_select_final_
                        else:
                            max_value_random_ = random.sample(max_value_columns_, k= (select[i]['C000_dmg'][q]-select[i]['C000_2030'][q]))
                    else:
                        max_value_random_ = max_value_columns_[0]
                    bucket_list2 = [max_value_random_,select[i]['h_geocode_y'][q]]
#                     print('max_value_random_if=',max_value_random_)
#                     print('bucket_list2=',bucket_list2)

                elif ((select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket2)[1].values)) :
                    max_value_random_temp = pd.DataFrame(bucket2)[0].values[pd.DataFrame(bucket2)[1].values == (select[i]['h_geocode_y'][q])]
                    max_value_random_ = max_value_random_temp[0]
#                     print('max_value_random_elif=',max_value_random_)
                    
                else:
                    max_value_random_ = max_value_random_test
                    bucket_list2 = [max_value_random_,select[i]['h_geocode_y'][q]]
#                     print('max_value_random_else=',max_value_random_)

                if isinstance((max_value_random_), list) :
                    for o in range(0, len(max_value_random_)):
                        select[i][max_value_random_[o]+'_2030'][q] =select[i][max_value_random_[o]+'_2030'][q]\
                            + ((select[i]['C000_dmg'][q] - select[i]['C000_2030'][q])/len(max_value_random_) )    
                else:
                    select[i][max_value_random_+'_2030'][q] =(select[i][max_value_random_+'_2030'][q])\
                    + (select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] )
    
                
            if select[i]['C000D_2030'][q] < select[i]['C000_dmg'][q]:
                max_value = pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T.max().max() #to find the max number of employees between CD01, CD02, CD03,CD04
                max_value_columns = [col for col in pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T[col].max() == max_value]
                max_value_random = random.choice(max_value_columns) # to select one column rondomly in case two or more columns have the same number of employees
#                 print('max_value_random=',max_value_random)
#                 print('C000_D_2030_before=' , select[i][max_value_random][q]\
#                       + (select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] ))
                select[i][max_value_random+'_2030'][q] =(select[i][max_value_random+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000D_2030'][q] )
#                 print('C000_D_2030_after=' , (select[i][max_value_random][q])\
#                       + (select[i]['C000_dmg'][q] - select[i]['C000_2030'][q] ))
                
            if select[i]['C000A_2030'][q] < select[i]['C000_dmg'][q]:
                max_value2 = pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T.max().max() #to find the max number of employees between CD01, CD02, CD03,CD04
                max_value_columns2 = [col for col in pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T[col].max() == max_value2]
                max_value_random2 = random.choice(max_value_columns2) # to select one column rondomly in case two or more columns have the same number of employees
                select[i][max_value_random2+'_2030'][q] =(select[i][max_value_random2+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000A_2030'][q] )

            if select[i]['C000E_2030'][q] < select[i]['C000_dmg'][q]:
                max_value3 = pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T.max().max() 
                max_value_columns3 = [col for col in pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T[col].max() == max_value3]
                max_value_random3 = random.choice(max_value_columns3) 
                select[i][max_value_random3+'_2030'][q] =(select[i][max_value_random3+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000E_2030'][q] )
                
            if select[i]['C000R_2030'][q] < select[i]['C000_dmg'][q]:
                max_value4 = pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T.max().max() 
                max_value_columns4 = [col for col in pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T[col].max() == max_value4]
                max_value_random4 = random.choice(max_value_columns4) 
                select[i][max_value_random4+'_2030'][q] =(select[i][max_value_random4+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000R_2030'][q] )
                
            if select[i]['C000T_2030'][q] < select[i]['C000_dmg'][q]:
                max_value4 = pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T.max().max() 
                max_value_columns4 = [col for col in pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T[col].max() == max_value4]
                max_value_random4 = random.choice(max_value_columns4) 
                select[i][max_value_random4+'_2030'][q] =(select[i][max_value_random4+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000T_2030'][q] )
                
            if select[i]['C000S_2030'][q] < select[i]['C000_dmg'][q]:
                max_value5 = pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T.max().max() 
                max_value_columns5 = [col for col in pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T[col].max() == max_value5]
                max_value_random5 = random.choice(max_value_columns5) 
                select[i][max_value_random5+'_2030'][q] =(select[i][max_value_random5+'_2030'][q])\
                + (select[i]['C000_dmg'][q] - select[i]['C000S_2030'][q] )
                
            if select[i]['C000D_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
                min_value = pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T.min().min() #to find the min number of employees between CD01, CD02, CD03,CD04
                min_value_columns = [col for col in pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CD01','CD02','CD03','CD04']].iloc[q,:]).T[col].min() == min_value]
                min_value_random = random.choice(min_value_columns) # to select one column rondomly in case two or more columns have the same number of employees
#                 print('min_value_random2=',min_value_random)
#                 print('C000_D_2030_before=' , select[i][min_value_random+'_2030'][q])
                select[i][min_value_random+'_2030'][q] =select[i][min_value_random+'_2030'][q]\
                    - (select[i]['C000D_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('C000_D_2030_after=' , select[i][min_value_random+'_2030'][q])
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))

    
            if select[i]['C000_2030'][q] - select[i]['C000_dmg'][q] == 1 :
#                 print('C000_2030 - C000_dmg=', select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])

#                 print('check_null_1_before', select[i].isnull().values.any())
                select[i].replace(0, np.nan, inplace=True)
#                 print('select[i][h_geocode_y] =',(select[i]['h_geocode_y'][q]))
#                 print('pd.DataFrame(bucket)[1].values)=',pd.DataFrame(bucket)[1].values)
#                 print('pd.DataFrame(bucket)[1].values)',(select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket)[1].values))
                min_value_test0 = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                             'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                             'CNS19','CNS20']].iloc[q,:]).T.min().min() 
                min_value_columns_test0 = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].min() == min_value_test0]
#                 print('min_value_columns_test0=',min_value_columns_test0)
                min_value_random_test0 = random.choice(min_value_columns_test0) 
#                 print('min_value_random_test0=',min_value_random_test0)

                if (i in range(0,len(select_hgeocode_geo5_6_dic_sum),3)) and (select[i]['h_geocode_y'][q]) not in (pd.DataFrame(bucket)[1].values):
                    min_value_0 = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.min().min() 
                    min_value_columns_0 = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].min() == min_value_0]
                    min_value_random_0 = random.choice(min_value_columns_0) 
                    
                    bucket_list = [min_value_random_0,select[i]['h_geocode_y'][q]]
#                     print('bucket_list=',bucket_list)
                    
#                     print('min_value_random_0_if=',min_value_random_0)
                elif ((select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket)[1].values)) :
                    min_value_random_0_temp = pd.DataFrame(bucket)[0].values[pd.DataFrame(bucket)[1].values == (select[i]['h_geocode_y'][q])]
#                     print('len(min_value_random_0_temp)',len(pd.DataFrame(min_value_random_0_temp)[0].T))
#                     print('(min_value_random_0_temp[0])',(min_value_random_0_temp[0]))
#                     print('(min_value_random_0_temp)',(min_value_random_0_temp))

                    if isinstance((min_value_random_0_temp)[0], list) :
#                         print('used this one (if)')
                        min_value_random_0_list = min_value_random_0_temp[0]
                        min_value_random_0 = random.choice(min_value_random_0_list) 
                        
                    else:
                        min_value_random_0 = min_value_random_0_temp[0]
#                         print('used this (else)')
#                     print('min_value_random_0_elif=',min_value_random_0)   

                else:
                    min_value_random_0 = min_value_random_test0
                    bucket_list = [min_value_random_0,select[i]['h_geocode_y'][q]]

                    
#                 bucket.append(bucket_list)
#                 print('bucket=',bucket)
#                 print('min_value_random_0=',min_value_random_0)   
#                 print('LHS_before',select[i][min_value_random_0+'_2030'][q])
                select[i][min_value_random_0+'_2030'][q] =select[i][min_value_random_0+'_2030'][q]\
                    - (select[i]['C000_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('LHS_after',select[i][min_value_random_0+'_2030'][q])

#                 print('check_null_1_after', select[i].isnull().values.any())
                select[i].replace(np.nan, 0, inplace=True)
#                 print('check_null_1_after2', select[i].isnull().values.any())
            
                
            if select[i]['C000_2030'][q] - select[i]['C000_dmg'][q] > 1 :
#                 print('C000_2030 - C000_dmg=', select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 print('select[i][h_geocode_y] =',(select[i]['h_geocode_y'][q]))
#                 print('pd.DataFrame(bucket)[1].values)=',pd.DataFrame(bucket)[1].values)
#                 print('pd.DataFrame(bucket)[1].values)',(select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket)[1].values))
                min_value_test = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                             'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                             'CNS19','CNS20']].iloc[q,:]).T.min().min() 
                min_value_columns_test = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].min() == min_value_test]
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                select[i]['C000_dmg'] = select[i]['C000_dmg'].astype(int)
#                 print('min_value_columns_test=',min_value_columns_test)
#                 print('select[i][C000_2030][q]=', select[i]['C000_2030'][q])
#                 print('select[i][C000_dmg][q]=', select[i]['C000_dmg'][q])
                
                if len(min_value_columns_test) >1 :
#                     select[i]['C000_2030'] = select[i]['C000_2030'][q].astype(int)
                    if (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]) > len(min_value_columns_test):
                        temp_list = ['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                 'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                 'CNS19','CNS20']
                        temp_select = list(set(temp_list)-set(min_value_columns_test))
#                         print('temp_select=',temp_select)
                        min_value_test_try2 = pd.DataFrame(select[i][temp_select].iloc[q,:]).T.min().min()                     
                        min_value_columns_test_try2 = [col for col in pd.DataFrame(select[i][temp_select].iloc[q,:]).T.columns if pd.DataFrame(select[i][temp_select].iloc[q,:]).T[col].min() == min_value_test_try2]
                        temp_select_final = list(set(min_value_columns_test) | set(min_value_columns_test_try2))
#                         print('temp_select_final=',temp_select_final)
                        select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                        min_value_random_test = random.sample(temp_select_final, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))
                    else:
                        pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                        select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                        min_value_random_test = random.sample(min_value_columns_test, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))
                        
                else:
                    min_value_random_test = min_value_columns_test[0]
                    
#                 print('min_value_random_test_error=',min_value_random_test)

#                 min_value_random_test = random.sample(min_value_columns_test, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))


                if (i in range(0,len(select_hgeocode_geo5_6_dic_sum),3)) and (select[i]['h_geocode_y'][q]) not in (pd.DataFrame(bucket)[1].values):
                    pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
                    min_value_ = pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.min().min() 
                    min_value_columns_ = [col for col in pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                         'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                         'CNS19','CNS20']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CNS01','CNS02','CNS03','CNS04',
                                                         'CNS05','CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
                                                         'CNS17','CNS18','CNS19','CNS20']].iloc[q,:]).T[col].min() == min_value_]
#                 pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
#                 print('C000_2030=',select[i]['C000_2030'][q])
#                 print('C000_dmg=',select[i]['C000_dmg'][q])
#                 print('C000_2030_type', select[i]['C000_2030'][q].dtype)
#                 print('C000_2030_type_true_false=', select[i]['C000_2030'][q].dtype == 'float64' )
#                 print('C000_2030_list', select[i]['C000_2030'])
#                 if select[i]['C000_2030'][q].dtype == 'float64':  
                    
#                 print('C000_2030=',select[i]['C000_2030'][q])
#                 print('C000_2030_type', select[i]['C000_2030'][q].dtype)

                    pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                    select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
        
                    if len(min_value_columns_) >1 :
    #                     select[i]['C000_2030'] = select[i]['C000_2030'][q].astype(int)
                        if (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]) > len(min_value_columns_):
                            temp_list = ['CNS01','CNS02','CNS03','CNS04','CNS05','CNS06','CNS07','CNS08','CNS09',
                                                     'CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16','CNS17','CNS18',
                                                     'CNS19','CNS20']
                            temp_select = list(set(temp_list)-set(min_value_columns_))
    #                         print('temp_select=',temp_select)
                            min_value_try2 = pd.DataFrame(select[i][temp_select].iloc[q,:]).T.min().min()                     
                            min_value_columns_try2 = [col for col in pd.DataFrame(select[i][temp_select].iloc[q,:]).T.columns if pd.DataFrame(select[i][temp_select].iloc[q,:]).T[col].min() == min_value_try2]
                            temp_select_final = list(set(min_value_columns_) | set(min_value_columns_try2))
#                             print('temp_select_final=',temp_select_final)
                            select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                            min_value_random_ = random.sample(temp_select_final, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))
                        else:
                            pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                            select[i]['C000_2030'] = select[i]['C000_2030'].astype(int)
                            min_value_random_ = random.sample(min_value_columns_, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))

                    else:
                        min_value_random_ = min_value_columns_[0]
        
#                     min_value_random_ = random.sample(min_value_columns_, k= (select[i]['C000_2030'][q]-select[i]['C000_dmg'][q]))
                    bucket_list = [min_value_random_,select[i]['h_geocode_y'][q]]
#                     print('min_value_random_if=',min_value_random_)
#                     print('bucket_list=',bucket_list)
#                     print('bucket_list[0]=',bucket_list[0])

                elif ((select[i]['h_geocode_y'][q]) in (pd.DataFrame(bucket)[1].values)) :
                    min_value_random_temp = pd.DataFrame(bucket)[0].values[pd.DataFrame(bucket)[1].values == (select[i]['h_geocode_y'][q])]
                    min_value_random_ = min_value_random_temp[0]
#                     print('min_value_random_elif=',min_value_random_)    
                    
                else: 
                    min_value_random_ = min_value_random_test
                    bucket_list = [min_value_random_,select[i]['h_geocode_y'][q]]
#                     print('min_value_random_else=',min_value_random_)    
          
                if isinstance((min_value_random_), list) :
                    for o in range(0, len(min_value_random_)):
    #                     print('o=',o)
    #                     print('q=',q)
    #                     print('min_value_random_',min_value_random_)
    #                     print('LHS=',select[i][min_value_random_[o]+'_2030'][q])

    #                     print('RHS=',select[i][min_value_random_[o]+'_2030'][q]\
    #                         - ((select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])/len(min_value_random_) ))
                        select[i][min_value_random_[o]+'_2030'][q] =select[i][min_value_random_[o]+'_2030'][q]\
                            - ((select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])/len(min_value_random_) )
                else:
                    select[i][min_value_random_+'_2030'][q] =select[i][min_value_random_+'_2030'][q]\
                            - ((select[i]['C000_2030'][q] - select[i]['C000_dmg'][q])/len(min_value_random_) )
    

                
            if select[i]['C000A_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 if i in range(0,720,3) : 
                min_value2 = pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T.min().min() 
                min_value_columns2 = [col for col in pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CA01','CA02','CA03']].iloc[q,:]).T[col].min() == min_value2]
                min_value_random2 = random.choice(min_value_columns2) 
#                 print('min_value_random2_if=',min_value_random2)                
#                 else:
#                     print('min_value_random2_else=',min_value_random2)                

                select[i][min_value_random2+'_2030'][q] =select[i][min_value_random2+'_2030'][q]\
                    - (select[i]['C000A_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_3', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
            if select[i]['C000E_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 if i in range(0,720,3) : 
                min_value3 = pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T.min().min()
                min_value_columns3 = [col for col in pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CE01','CE02','CE03']].iloc[q,:]).T[col].min() == min_value3]
                min_value_random3 = random.choice(min_value_columns3) 
#                 print('min_value_random3_if=',min_value_random3)     
#                 else:
#                     print('min_value_random3_else=',min_value_random3)     
                    
                select[i][min_value_random3+'_2030'][q] =select[i][min_value_random3+'_2030'][q]\
                    - (select[i]['C000E_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_4', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
            if select[i]['C000R_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 if i in range(0,15,3) : 
                min_value4 = pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T.min().min()
                min_value_columns4 = [col for col in pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CR01','CR02','CR03','CR04','CR05','CR07']].iloc[q,:]).T[col].min() == min_value4]
                min_value_random4 = random.choice(min_value_columns4) 
#                 print('min_value_random4_if=',min_value_random4)     
#                 else:
#                     print('min_value_random4_if=',min_value_random4)     
                    
                select[i][min_value_random4+'_2030'][q] =select[i][min_value_random4+'_2030'][q]\
                    - (select[i]['C000R_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_5', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
            if select[i]['C000T_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True))
#                 if i in range(0,15,3) : 
                min_value5 = pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T.min().min()
                min_value_columns5 = [col for col in pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CT01','CT02']].iloc[q,:]).T[col].min() == min_value5]
                min_value_random5 = random.choice(min_value_columns5) 
#                 print('min_value_random5_if=',min_value_random5)     
#                 else:
#                     print('min_value_random5_if=',min_value_random5)     
                    
                select[i][min_value_random5+'_2030'][q] =select[i][min_value_random5+'_2030'][q]\
                    - (select[i]['C000T_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_6', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
            if select[i]['C000S_2030'][q] > select[i]['C000_dmg'][q]:
                pd.DataFrame(select[i].replace(0, np.nan, inplace=True)) 
                min_value6 = pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T.min().min()
                min_value_columns6 = [col for col in pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T.columns if pd.DataFrame(select[i][['CS01','CS02']].iloc[q,:]).T[col].min() == min_value6]
                min_value_random6 = random.choice(min_value_columns6) 
#                 print('min_value_random6_if=',min_value_random6)     

                select[i][min_value_random6+'_2030'][q] =select[i][min_value_random6+'_2030'][q]\
                    - (select[i]['C000S_2030'][q] - select[i]['C000_dmg'][q] )
#                 print('check_null_7', select[i].isnull().values.any())
                pd.DataFrame(select[i].replace(np.nan, 0, inplace=True))
                
                
#             print('check_null_final', select[i].isnull().values.any())
            select[i]['C000A_2030'][q] = select[i]['CA01_2030'][q]\
                                                             +select[i]['CA02_2030'][q]\
                                                             +select[i]['CA03_2030'][q]

            select[i]['C000E_2030'][q] = select[i]['CE01_2030'][q]\
                                                             +select[i]['CE02_2030'][q]\
                                                             +select[i]['CE03_2030'][q]

            select[i]['C000R_2030'][q] = select[i]['CR01_2030'][q]\
                                                             +select[i]['CR02_2030'][q]\
                                                             +select[i]['CR03_2030'][q]\
                                                             +select[i]['CR04_2030'][q]\
                                                             +select[i]['CR05_2030'][q]\
                                                             +select[i]['CR07_2030'][q]

            select[i]['C000D_2030'][q] = select[i]['CD01_2030'][q]\
                                                             +select[i]['CD02_2030'][q]\
                                                             +select[i]['CD03_2030'][q]\
                                                             +select[i]['CD04_2030'][q]

            select[i]['C000T_2030'][q] = select[i]['CT01_2030'][q]\
                                                             +select[i]['CT02_2030'][q]\

            select[i]['C000S_2030'][q] = select[i]['CS01_2030'][q]\
                                                             +select[i]['CS02_2030'][q]\

                

            select[i]['C000_2030'][q] = select[i]['CNS01_2030'][q]\
                                                            +select[i]['CNS02_2030'][q]\
                                                            +select[i]['CNS03_2030'][q]\
                                                            +select[i]['CNS04_2030'][q]\
                                                            +select[i]['CNS05_2030'][q]\
                                                            +select[i]['CNS06_2030'][q]\
                                                            +select[i]['CNS07_2030'][q]\
                                                            +select[i]['CNS08_2030'][q]\
                                                            +select[i]['CNS09_2030'][q]\
                                                            +select[i]['CNS10_2030'][q]\
                                                            +select[i]['CNS11_2030'][q]\
                                                            +select[i]['CNS12_2030'][q]\
                                                            +select[i]['CNS13_2030'][q]\
                                                            +select[i]['CNS14_2030'][q]\
                                                            +select[i]['CNS15_2030'][q]\
                                                            +select[i]['CNS16_2030'][q]\
                                                            +select[i]['CNS17_2030'][q]\
                                                            +select[i]['CNS18_2030'][q]\
                                                            +select[i]['CNS19_2030'][q]\
                                                            +select[i]['CNS20_2030'][q]
#         print('select[CA01_2030]=',select[i]['CA01_2030'])

            if bucket_list in bucket:
                pass
            else:                
                bucket.append(bucket_list)
#                 print('bucket=',bucket)
                
            if bucket_list2 in bucket2:
                pass
            else:                
                bucket2.append(bucket_list2)
#                 print('bucket2=',bucket2)
    

        select[i].set_index('index', inplace=True)
    
        final1[i] = pd.concat([select[i], unselect[i]], axis=1)
        final1[i].sort_index(inplace=True)
#         print('final1[CA01_2030]=',final1[i]['CA01_2030'])

#         final2[i] = pd.concat([final1[i], unselect1[i]], axis=0)
    return final1

# use the following function to combine all C000_dmg to the Emp_home_select_2030_part1_new2

In [638]:
dataframes2_temp2={}


# list of data frames
# Assume that the original dataframe is named 'original_df'
for i in range(0, len(Raster_file_paths)):
    dataframes2_temp2[i] = Emp_home_select_2030_part2_new2.copy()

# Convert the dictionary to a list of tuples
dataframes2_part2 = list(dataframes2_temp2.values())


# dictionary to save data frames
Emp_home_select_2030_part2_new2_dic={} 

for key22, value22 in enumerate(dataframes2_part2):    
    Emp_home_select_2030_part2_new2_dic[key22] = value22 # assigning data frame from list to key in dictionary

In [639]:
def get_accurate_C000(select_hgeocode_geo5_6_try3, Emp_home_select_2030_part1_new2_dic, n ):
    
    select_hgeocode_geo5_6_try3_C000={}
    Emp_home_select_2030_part1_new2_dic2={}
    
    for i in range(0, len(select_hgeocode_geo5_6_try3)):
        if 'h_geocode_y' in select_hgeocode_geo5_6_try3[i].columns:
            pass
        else: 
            select_hgeocode_geo5_6_try3[i].rename(columns = {'h_geocode':'h_geocode_y'}, inplace = True)    
            
        select_hgeocode_geo5_6_try3_C000[i] = select_hgeocode_geo5_6_try3[i][['h_geocode_y','C000_dmg','C000_dmg_mean','C000']]

        select_hgeocode_geo5_6_try3_C000[i].rename(columns = {'h_geocode_y':'h_geocode',
                                                               'C000_dmg':'C000_dmg_'+str(n),
                                                              'C000_dmg_mean':'C000_dmg_mean_'+str(n),
                                                               'C000':'C000_'+str(n)}, inplace = True)
        
        
        Emp_home_select_2030_part1_new2_dic2[i] = pd.merge(
            Emp_home_select_2030_part1_new2_dic[i], select_hgeocode_geo5_6_try3_C000[i], how="left", on=["h_geocode"])

    return Emp_home_select_2030_part1_new2_dic2

In [640]:
# len(select_hgeocode_geo5_6_dic2_full)

In [641]:
Emp_home_select_2030_part2_new2_dic[0].head()

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CT01,CT02,CD01,CD02,CD03,CD04,CS01,CS02,createdate,geometry
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,2.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612..."
1,12,021,010411,1000,120210104111000,Block 1000,G5040,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,20231016,"POLYGON ((-81.69629 26.18436, -81.69546 26.184..."
2,12,021,010408,1005,120210104081005,Block 1005,G5040,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,20231016,"POLYGON ((-81.73524 26.20540, -81.73522 26.205..."
3,12,021,011208,1028,120210112081028,Block 1028,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20231016,"POLYGON ((-81.44029 26.32594, -81.44019 26.326..."
4,12,081,002003,1002,120810020031002,Block 1002,G5040,NaN,NaN,NaN,...,4.0,0.0,0.0,1.0,2.0,1.0,2.0,2.0,20231016,"POLYGON ((-82.50990 27.50864, -82.50986 27.508..."

In [642]:
len(select_hgeocode_geo5_6_dic2)

30

In [643]:
select_hgeocode_geo5_6_dic2_full = dataframe_full(select_hgeocode_geo5_6_dic2)

In [644]:
len(select_hgeocode_geo5_6_dic2_full)

120

In [645]:

Emp_home_select_2030_part2_new2_dic = get_accurate_C000(select_hgeocode_geo5_6_dic2_full,Emp_home_select_2030_part2_new2_dic, 1 )

In [646]:
len(Emp_home_select_2030_part2_new2_dic)

120

In [647]:
for i in range(2, loop_ended+1):
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18

In [648]:
# len(globals()['select_hgeocode_geo5_6_try_try{0}_dic_full'.format(i)])

In [649]:
for i in range(2, loop_ended+1):
    globals()['select_hgeocode_geo5_6_try_try{0}_dic_full'.format(i)] = dataframe_full(globals()['select_hgeocode_geo5_6_try_try{0}_dic'.format(i)])

In [650]:
for i in range(2, loop_ended+1):
    Emp_home_select_2030_part2_new2_dic = get_accurate_C000(globals()['select_hgeocode_geo5_6_try_try{0}_dic_full'.format(i)],Emp_home_select_2030_part2_new2_dic, i )

In [651]:
Emp_home_select_2030_new_values_merge_u_dic_full = dataframe_full(Emp_home_select_2030_new_values_merge_u_dic)

In [652]:

Emp_home_select_2030_part2_new2_dic = get_accurate_C000(Emp_home_select_2030_new_values_merge_u_dic_full,Emp_home_select_2030_part2_new2_dic, loop_ended+1 )

In [653]:
loop_ended+2

20

In [654]:
Emp_home_select_2030_new_values_merge_u_try5_5_6_dic_full = dataframe_full(Emp_home_select_2030_new_values_merge_u_try5_5_6_dic)

In [655]:

Emp_home_select_2030_part2_new2_dic = get_accurate_C000(Emp_home_select_2030_new_values_merge_u_try5_5_6_dic_full,Emp_home_select_2030_part2_new2_dic, loop_ended+2 )

In [656]:
merge_u_try2_dic_full = dataframe_full(merge_u_try2_dic)

In [657]:
len(merge_u_try2_dic_full)

120

In [658]:
len(Emp_home_select_2030_part2_new2_dic)

120

In [659]:
Emp_home_select_2030_part2_new2_dic = get_accurate_C000(merge_u_try2_dic_full,Emp_home_select_2030_part2_new2_dic, loop_ended+3 )

In [660]:
prefix = 'C000_dmg_'
numbers = list(range(1, loop_ended+3+1))
columns_to_sum = [prefix + str(num) for num in numbers]

In [661]:
columns_to_sum

['C000_dmg_1',
 'C000_dmg_2',
 'C000_dmg_3',
 'C000_dmg_4',
 'C000_dmg_5',
 'C000_dmg_6',
 'C000_dmg_7',
 'C000_dmg_8',
 'C000_dmg_9',
 'C000_dmg_10',
 'C000_dmg_11',
 'C000_dmg_12',
 'C000_dmg_13',
 'C000_dmg_14',
 'C000_dmg_15',
 'C000_dmg_16',
 'C000_dmg_17',
 'C000_dmg_18',
 'C000_dmg_19',
 'C000_dmg_20',
 'C000_dmg_21']

In [662]:
for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    for j in range(1,loop_ended+3+1 ):
        Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_{0}'.format(j)] = Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_{0}'.format(j)].fillna(0)
    
  
    
    prefix = 'C000_dmg_'
    numbers = list(range(1, loop_ended+3+1))
    columns_to_sum = [prefix + str(num) for num in numbers]

    Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_total'] = Emp_home_select_2030_part2_new2_dic[i][columns_to_sum].sum(axis=1)

In [663]:
Emp_home_select_2030_part2_new2_dic[0]['C000_dmg_total'].sum()

0.0

In [664]:
1418+263+21+1+1+205+24

1933

In [665]:
for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    for j in range(1,loop_ended+3+1 ):
        Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_mean_{0}'.format(j)] = Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_mean_{0}'.format(j)].fillna(0)

        
    prefix2 = 'C000_dmg_mean_'
    numbers = list(range(1, loop_ended+3+1))
    columns_to_sum2 = [prefix2 + str(num) for num in numbers]    
           
    Emp_home_select_2030_part2_new2_dic[i]['C000_dmg_mean_total'] = Emp_home_select_2030_part2_new2_dic[i][columns_to_sum2].sum(axis=1)

In [666]:
combined_list = columns_to_sum + columns_to_sum2
combined_list

['C000_dmg_1',
 'C000_dmg_2',
 'C000_dmg_3',
 'C000_dmg_4',
 'C000_dmg_5',
 'C000_dmg_6',
 'C000_dmg_7',
 'C000_dmg_8',
 'C000_dmg_9',
 'C000_dmg_10',
 'C000_dmg_11',
 'C000_dmg_12',
 'C000_dmg_13',
 'C000_dmg_14',
 'C000_dmg_15',
 'C000_dmg_16',
 'C000_dmg_17',
 'C000_dmg_18',
 'C000_dmg_19',
 'C000_dmg_20',
 'C000_dmg_21',
 'C000_dmg_mean_1',
 'C000_dmg_mean_2',
 'C000_dmg_mean_3',
 'C000_dmg_mean_4',
 'C000_dmg_mean_5',
 'C000_dmg_mean_6',
 'C000_dmg_mean_7',
 'C000_dmg_mean_8',
 'C000_dmg_mean_9',
 'C000_dmg_mean_10',
 'C000_dmg_mean_11',
 'C000_dmg_mean_12',
 'C000_dmg_mean_13',
 'C000_dmg_mean_14',
 'C000_dmg_mean_15',
 'C000_dmg_mean_16',
 'C000_dmg_mean_17',
 'C000_dmg_mean_18',
 'C000_dmg_mean_19',
 'C000_dmg_mean_20',
 'C000_dmg_mean_21']

In [667]:
prefix3 = 'C000_'
numbers = list(range(1, loop_ended+3+1))
columns_to_sum3 = [prefix3 + str(num) for num in numbers]    

combined_list = columns_to_sum+columns_to_sum2+columns_to_sum3


for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    Emp_home_select_2030_part2_new2_dic[i]= Emp_home_select_2030_part2_new2_dic[i].drop(combined_list, axis=1)

In [668]:
for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    Emp_home_select_2030_part2_new2_dic[i].rename(columns = {'C000_dmg_total':'C000_dmg'
                                                            }, inplace = True)

In [669]:
for i in range(0, len(Emp_home_select_2030_part2_new2_dic)):
    Emp_home_select_2030_part2_new2_dic[i].rename(columns = {'C000_dmg_mean_total':'C000_dmg_mean'
                                                            }, inplace = True)

In [670]:
def Round_up(num):

    from decimal import localcontext, Decimal, ROUND_HALF_UP
    with localcontext() as ctx:
        ctx.rounding = ROUND_HALF_UP
        n = Decimal(num)
        nnnn = n.to_integral_value()
        int_number = int ( nnnn )
    return int_number

In [671]:
Emp_home_select_2030_part2_new2_dic[0].head()

,STATEFP20,COUNTYFP20,TRACTCE20,BLOCKCE20,GEOID20,NAME20,MTFCC20,UR20,UACE20,UATYPE20,...,CD01,CD02,CD03,CD04,CS01,CS02,createdate,geometry,C000_dmg,C000_dmg_mean
0,12,071,001205,1002,120710012051002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,1.0,1.0,20231016,"POLYGON ((-81.84015 26.61223, -81.83993 26.612...",0.0,0.0
1,12,021,010411,1000,120210104111000,Block 1000,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,1.0,0.0,20231016,"POLYGON ((-81.69629 26.18436, -81.69546 26.184...",0.0,0.0
2,12,021,010408,1005,120210104081005,Block 1005,G5040,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,1.0,0.0,20231016,"POLYGON ((-81.73524 26.20540, -81.73522 26.205...",0.0,0.0
3,12,021,011208,1028,120210112081028,Block 1028,G5040,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,20231016,"POLYGON ((-81.44029 26.32594, -81.44019 26.326...",0.0,0.0
4,12,081,002003,1002,120810020031002,Block 1002,G5040,NaN,NaN,NaN,...,0.0,1.0,2.0,1.0,2.0,2.0,20231016,"POLYGON ((-82.50990 27.50864, -82.50986 27.508...",0.0,0.0

In [672]:
# Emp_home_select_2030_part1_new2_dic[1]['h_geocode_y']

In [673]:
Emp_home_select_2030_part2_new2['C000']

0        2.0
1        1.0
2        1.0
3        0.0
4        4.0
        ...
34218    1.0
34219    0.0
34220    0.0
34221    0.0
34222    8.0
Name: C000, Length: 34223, dtype: float64

In [674]:
len(Raster_file_paths)

120

In [675]:
Emp_home_select_2030_part2_new2_dic_sum= select_sum(Emp_home_select_2030_part2_new2_dic)

i= 0
i= 1
i= 2
i= 3
i= 4
i= 5
i= 6
i= 7
i= 8
i= 9
i= 10
i= 11
i= 12
i= 13
i= 14
i= 15
i= 16
i= 17
i= 18
i= 19
i= 20
i= 21
i= 22
i= 23
i= 24
i= 25
i= 26
i= 27
i= 28
i= 29
i= 30
i= 31
i= 32
i= 33
i= 34
i= 35
i= 36
i= 37
i= 38
i= 39
i= 40
i= 41
i= 42
i= 43
i= 44
i= 45
i= 46
i= 47
i= 48
i= 49
i= 50
i= 51
i= 52
i= 53
i= 54
i= 55
i= 56
i= 57
i= 58
i= 59
i= 60
i= 61
i= 62
i= 63
i= 64
i= 65
i= 66
i= 67
i= 68
i= 69
i= 70
i= 71
i= 72
i= 73
i= 74
i= 75
i= 76
i= 77
i= 78
i= 79
i= 80
i= 81
i= 82
i= 83
i= 84
i= 85
i= 86
i= 87
i= 88
i= 89
i= 90
i= 91
i= 92
i= 93
i= 94
i= 95
i= 96
i= 97
i= 98
i= 99
i= 100
i= 101
i= 102
i= 103
i= 104
i= 105
i= 106
i= 107
i= 108
i= 109
i= 110
i= 111
i= 112
i= 113
i= 114
i= 115
i= 116
i= 117
i= 118
i= 119

In [676]:
# Emp_home_select_2030_part2_new2_dic_sum[150]

In [677]:
# # # bucket_list= [['CNS01', 'CNS04', 'CNS12', 'CNS18', 'CNS15'], 10030107111003]
# # #bucket_out11 is the list of randomly selected minimum or maximum sectors ('CNS01', 'CNS04', 'CNS12', 'CNS18', 'CNS15')
# # #for each home zone (10030107111003) that will be used to fit C000_dmg to them 

# # #In this example ['CNS01', 'CNS04', 'CNS12', 'CNS15', 'CNS16', 'CNS18'] all have value of 1 after Round_up
# # # but C000_dmg is only 1 so to choose which sector will take that damage we randomly selected 5 sectors to opt out
# # # which are the bucket_out11 and the remaining sector 'CNS16' will take that damage


# Emp_home_select_2030_part2_new2_dic_sum2 = select_sum(Emp_home_select_2030_part2_new2_dic)

In [678]:
# Save_again = Emp_home_select_2030_new_values_merge_u_dic_sum[0][Emp_home_select_2030_new_values_merge_u_dic_sum[0]['C000_dmg']>0]

# Save_again.to_csv('Save_again.csv')

In [679]:
# Emp_home_select_2030_part2_new2_dic_sum2[0]

In [680]:
Emp_home_select_2030_part2_new2_dic_sum_result = prepare_sum(Emp_home_select_2030_part2_new2_dic_sum)

In [681]:

# Emp_home_select_2030_part2_new2_dic_sum_result[719]

In [682]:

# Emp_home_select_2030_part2_new2_dic_sum_result[719]

In [683]:
Emp_home_select_2030_new_values_final ={}
for i in range (0, len(Emp_home_select_2030_part2_new2_dic_sum_result)):
    Emp_home_select_2030_new_values_final[i] =Emp_home_select_2030_part2_new2_dic_sum_result[i]
    
#     Emp_home_select_2030_new_values_final[i]['C000_dmg_mean_2030'] = Emp_home_select_2030_new_values_final[i]['C000_dmg_mean_2030']
#     Emp_home_select_2030_new_values_final[i]['CA01_2030'] = (Emp_home_select_2030_new_values_final[i]['CA01_2030']/Emp_home_select_2030_new_values_final[i]['C000A_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CA02_2030'] = (Emp_home_select_2030_new_values_final[i]['CA02_2030']/Emp_home_select_2030_new_values_final[i]['C000A_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CA03_2030'] = (Emp_home_select_2030_new_values_final[i]['CA03_2030']/Emp_home_select_2030_new_values_final[i]['C000A_2030'])*100

#     Emp_home_select_2030_new_values_final[i]['CE01_2030'] = (Emp_home_select_2030_new_values_final[i]['CE01_2030']/Emp_home_select_2030_new_values_final[i]['C000E_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CE02_2030'] = (Emp_home_select_2030_new_values_final[i]['CE02_2030']/Emp_home_select_2030_new_values_final[i]['C000E_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CE03_2030'] = (Emp_home_select_2030_new_values_final[i]['CE03_2030']/Emp_home_select_2030_new_values_final[i]['C000E_2030'])*100

#     Emp_home_select_2030_new_values_final[i]['CR01_2030'] = (Emp_home_select_2030_new_values_final[i]['CR01_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR02_2030'] = (Emp_home_select_2030_new_values_final[i]['CR02_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR03_2030'] = (Emp_home_select_2030_new_values_final[i]['CR03_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR04_2030'] = (Emp_home_select_2030_new_values_final[i]['CR04_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR05_2030'] = (Emp_home_select_2030_new_values_final[i]['CR05_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CR07_2030'] = (Emp_home_select_2030_new_values_final[i]['CR07_2030']/Emp_home_select_2030_new_values_final[i]['C000R_2030'])*100

#     Emp_home_select_2030_new_values_final[i]['CT01_2030'] = (Emp_home_select_2030_new_values_final[i]['CT01_2030']/Emp_home_select_2030_new_values_final[i]['C000T_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CT02_2030'] = (Emp_home_select_2030_new_values_final[i]['CT02_2030']/Emp_home_select_2030_new_values_final[i]['C000T_2030'])*100

#     Emp_home_select_2030_new_values_final[i]['CS01_2030'] = (Emp_home_select_2030_new_values_final[i]['CS01_2030']/Emp_home_select_2030_new_values_final[i]['C000S_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CS02_2030'] = (Emp_home_select_2030_new_values_final[i]['CS02_2030']/Emp_home_select_2030_new_values_final[i]['C000S_2030'])*100
   
#     Emp_home_select_2030_new_values_final[i]['CD01_2030'] = (Emp_home_select_2030_new_values_final[i]['CD01_2030']/Emp_home_select_2030_new_values_final[i]['C000D_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CD02_2030'] = (Emp_home_select_2030_new_values_final[i]['CD02_2030']/Emp_home_select_2030_new_values_final[i]['C000D_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CD03_2030'] = (Emp_home_select_2030_new_values_final[i]['CD03_2030']/Emp_home_select_2030_new_values_final[i]['C000D_2030'])*100
#     Emp_home_select_2030_new_values_final[i]['CD04_2030'] = (Emp_home_select_2030_new_values_final[i]['CD04_2030']/Emp_home_select_2030_new_values_final[i]['C000D_2030'])*100

In [684]:
for i in range (0, len(Emp_home_select_2030_new_values_final)):
    Emp_home_select_2030_new_values_final[i] = Emp_home_select_2030_new_values_final[i][[
        'C000','CA01','CA02','CA03','CE01','CE02','CE03', 'CNS01','CNS02','CNS03','CNS04','CNS05',
        'CNS06','CNS07','CNS08','CNS09','CNS10','CNS11','CNS12','CNS13','CNS14','CNS15','CNS16',
        'CNS17','CNS18','CNS19','CNS20','CR01','CR02','CR03','CR04','CR05','CR07','CD01','CD02',
        'CD03','CD04','CT01','CT02','CS01','CS02','C000_dmg','C000_dmg_mean','C000_dmg_mean_2030',
        'CNS01_2030','CNS02_2030','CNS03_2030','CNS04_2030','CNS05_2030','CNS06_2030','CNS07_2030',
        'CNS08_2030','CNS09_2030','CNS10_2030','CNS11_2030','CNS12_2030','CNS13_2030','CNS14_2030',
        'CNS15_2030','CNS16_2030','CNS17_2030','CNS18_2030','CNS19_2030','CNS20_2030',
        'CA01_2030','CA02_2030','CA03_2030','CE01_2030','CE02_2030','CE03_2030','CR01_2030',
        'CR02_2030','CR03_2030','CR04_2030','CR05_2030','CR07_2030','CD01_2030','CD02_2030',
        'CD03_2030','CD04_2030','CT01_2030','CT02_2030','CS01_2030','CS02_2030','C000_2030',
        'C000A_2030','C000E_2030','C000R_2030','C000D_2030','C000T_2030','C000S_2030'

    ]]

In [685]:
len(Raster_file_paths)

120

In [686]:
len(Emp_home_select_2030_new_values_final)

120

In [687]:
final_save=[]
for i in range(0,len(Raster_file_paths)):
    temp_save = Emp_home_select_2030_new_values_final[i]
    final_save.append(temp_save)

In [688]:
pd.DataFrame(final_save)['C000_dmg']

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
        ...
115        0.0
116        0.0
117        0.0
118    31531.0
119    32918.0
Name: C000_dmg, Length: 120, dtype: float64

In [689]:
year_1

2090

In [690]:
pd.DataFrame(final_save).T.to_csv('FL_{0}_new_values_final5_5_part2.csv'.format(year_1))

In [691]:
import pandas as pd
final_save_part2= pd.read_csv('FL_{0}_new_values_final5_5_part2.csv'.format(year_1))
final_save_part2

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,110,111,112,113,114,115,116,117,118,119
0,C000,0.0,0.0,0.0,0.0,0.0,0.0,3.0,8.0,0.0,...,33590.0,34620.0,0.0,0.0,0.0,0.0,0.0,0.0,34994.0,36122.0
1,CA01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4614.0,4760.0,0.0,0.0,0.0,0.0,0.0,0.0,4808.0,4931.0
2,CA02,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,0.0,...,18917.0,19483.0,0.0,0.0,0.0,0.0,0.0,0.0,19704.0,20390.0
3,CA03,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,...,10084.0,10404.0,0.0,0.0,0.0,0.0,0.0,0.0,10509.0,10829.0
4,CE01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4741.0,4889.0,0.0,0.0,0.0,0.0,0.0,0.0,4930.0,5063.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,C000E_2030,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,...,29858.0,31021.0,0.0,0.0,0.0,0.0,0.0,0.0,31531.0,32918.0
87,C000R_2030,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,...,29858.0,31022.0,0.0,0.0,0.0,0.0,0.0,0.0,31533.0,32918.0
88,C000D_2030,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,...,29862.0,31025.0,0.0,0.0,0.0,0.0,0.0,0.0,31535.0,32921.0
89,C000T_2030,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,...,29858.0,31021.0,0.0,0.0,0.0,0.0,0.0,0.0,31531.0,32918.0
90,C000S_2030,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,...,29858.0,31021.0,0.0,0.0,0.0,0.0,0.0,0.0,31531.0,32918.0

In [692]:
final_save_part1= pd.read_csv('FL_{0}_new_values_final5_5.csv'.format(year_1))
final_save_part1

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,110,111,112,113,114,115,116,117,118,119
0,C000,0.0,0.0,0.0,0.0,0.0,0.0,1995.0,2565.0,0.0,...,64464.0,66653.0,0.0,0.0,0.0,0.0,0.0,0.0,67339.0,68888.0
1,CA01,0.0,0.0,0.0,0.0,0.0,0.0,320.0,399.0,0.0,...,9717.0,10075.0,0.0,0.0,0.0,0.0,0.0,0.0,10172.0,10446.0
2,CA02,0.0,0.0,0.0,0.0,0.0,0.0,1096.0,1412.0,0.0,...,35387.0,36683.0,0.0,0.0,0.0,0.0,0.0,0.0,37084.0,37972.0
3,CA03,0.0,0.0,0.0,0.0,0.0,0.0,579.0,754.0,0.0,...,19396.0,19931.0,0.0,0.0,0.0,0.0,0.0,0.0,20119.0,20506.0
4,CE01,0.0,0.0,0.0,0.0,0.0,0.0,258.0,361.0,0.0,...,9742.0,10104.0,0.0,0.0,0.0,0.0,0.0,0.0,10201.0,10425.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,C000E_2030,0.0,0.0,0.0,0.0,0.0,0.0,186.0,236.0,0.0,...,54935.0,56900.0,0.0,0.0,0.0,0.0,0.0,0.0,57644.0,59939.0
87,C000R_2030,0.0,0.0,0.0,0.0,0.0,0.0,186.0,236.0,0.0,...,54935.0,56900.0,0.0,0.0,0.0,0.0,0.0,0.0,57644.0,59940.0
88,C000D_2030,0.0,0.0,0.0,0.0,0.0,0.0,194.0,244.0,0.0,...,54945.0,56908.0,0.0,0.0,0.0,0.0,0.0,0.0,57654.0,59950.0
89,C000T_2030,0.0,0.0,0.0,0.0,0.0,0.0,186.0,236.0,0.0,...,54935.0,56900.0,0.0,0.0,0.0,0.0,0.0,0.0,57644.0,59939.0
90,C000S_2030,0.0,0.0,0.0,0.0,0.0,0.0,186.0,236.0,0.0,...,54935.0,56900.0,0.0,0.0,0.0,0.0,0.0,0.0,57644.0,59939.0

In [693]:
final_save_part1.set_index('Unnamed: 0', inplace=True)
final_save_part2.set_index('Unnamed: 0', inplace=True)

In [694]:
len(final_save_part1)

91

In [695]:
final_save_part1.iloc[43]

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
         ...
115          NaN
116          NaN
117          NaN
118    99.469016
119    99.709098
Name: C000_dmg_mean_2030, Length: 120, dtype: float64

In [696]:
#don't use if it was fixed in future years

# final_save_part1.iloc[43] = final_save_part1.iloc[43]*2

# final_save_part1.iloc[43]

In [697]:
# final_save_part2.iloc[43]

In [698]:
# final_save_part2.iloc[83]

In [699]:
final_save_part2.iloc[10].unique()

array([0.000e+00, 1.000e+00, 3.000e+00, 2.670e+02, 3.630e+02, 4.680e+02,
       6.370e+02, 7.490e+02, 1.186e+03, 3.350e+02, 3.690e+02, 4.300e+02,
       4.930e+02, 7.970e+02, 9.560e+02, 1.076e+03, 1.269e+03, 1.341e+03,
       1.593e+03, 3.326e+03, 3.353e+03, 3.415e+03, 3.443e+03, 3.545e+03,
       3.632e+03, 3.704e+03, 3.809e+03, 3.844e+03, 3.973e+03])

In [700]:
final_save = final_save_part1.copy()
for i in range(0,len(final_save_part1)):
    if i == 43:
        print('i=',i)
        final_save_part1.iloc[i] = final_save_part1.iloc[i].fillna(0)
        final_save_part2.iloc[i] = final_save_part2.iloc[i].fillna(0)
        

        final_save.iloc[i,:] = (final_save_part1.iloc[i,:]+final_save_part2.iloc[i,:])/2
        
        
        
    else: 
        final_save_part1.iloc[i] = final_save_part1.iloc[i].fillna(0)
        final_save_part2.iloc[i] = final_save_part2.iloc[i].fillna(0)

        final_save.iloc[i,:] = final_save_part1.iloc[i,:]+final_save_part2.iloc[i,:]

i= 43

In [701]:
final_save.iloc[43]

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
          ...
115      0.000000
116      0.000000
117      0.000000
118    100.420783
119    100.884824
Name: C000_dmg_mean_2030, Length: 120, dtype: float64

In [702]:
final_save_part1.iloc[10]

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
115       0.0
116       0.0
117       0.0
118    7389.0
119    7528.0
Name: CNS04, Length: 120, dtype: float64

In [703]:
final_save_part2.iloc[10]

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
115       0.0
116       0.0
117       0.0
118    3844.0
119    3973.0
Name: CNS04, Length: 120, dtype: float64

In [704]:
final_save.iloc[10]

0          0.0
1          0.0
2          0.0
3          0.0
4          0.0
        ...
115        0.0
116        0.0
117        0.0
118    11233.0
119    11501.0
Name: CNS04, Length: 120, dtype: float64

In [705]:
final_save

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
C000,0.0,0.0,0.0,0.0,0.0,0.0,1998.0,2573.0,0.0,0.0,...,98054.0,101273.0,0.0,0.0,0.0,0.0,0.0,0.0,102333.0,105010.0
CA01,0.0,0.0,0.0,0.0,0.0,0.0,320.0,399.0,0.0,0.0,...,14331.0,14835.0,0.0,0.0,0.0,0.0,0.0,0.0,14980.0,15377.0
CA02,0.0,0.0,0.0,0.0,0.0,0.0,1098.0,1418.0,0.0,0.0,...,54304.0,56166.0,0.0,0.0,0.0,0.0,0.0,0.0,56788.0,58362.0
CA03,0.0,0.0,0.0,0.0,0.0,0.0,580.0,756.0,0.0,0.0,...,29480.0,30335.0,0.0,0.0,0.0,0.0,0.0,0.0,30628.0,31335.0
CE01,0.0,0.0,0.0,0.0,0.0,0.0,258.0,361.0,0.0,0.0,...,14483.0,14993.0,0.0,0.0,0.0,0.0,0.0,0.0,15131.0,15488.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C000E_2030,0.0,0.0,0.0,0.0,0.0,0.0,187.0,238.0,0.0,0.0,...,84793.0,87921.0,0.0,0.0,0.0,0.0,0.0,0.0,89175.0,92857.0
C000R_2030,0.0,0.0,0.0,0.0,0.0,0.0,187.0,238.0,0.0,0.0,...,84793.0,87922.0,0.0,0.0,0.0,0.0,0.0,0.0,89177.0,92858.0
C000D_2030,0.0,0.0,0.0,0.0,0.0,0.0,195.0,246.0,0.0,0.0,...,84807.0,87933.0,0.0,0.0,0.0,0.0,0.0,0.0,89189.0,92871.0
C000T_2030,0.0,0.0,0.0,0.0,0.0,0.0,187.0,238.0,0.0,0.0,...,84793.0,87921.0,0.0,0.0,0.0,0.0,0.0,0.0,89175.0,92857.0
C000S_2030,0.0,0.0,0.0,0.0,0.0,0.0,187.0,238.0,0.0,0.0,...,84793.0,87921.0,0.0,0.0,0.0,0.0,0.0,0.0,89175.0,92857.0

In [1]:
year_1

NameError: name 'year_1' is not defined

In [707]:
final_save.to_csv('final_save_{0}.csv'.format(year_1))